### ISSUE TITLE
Mame adds "0" to end of the file extension with "-snapview native" enabled

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#10005]
mame: `0.244 (mame0244-430-g5d31d021d23)`
OS: Windows 10 21H2

command: `mame sf2 -snapview native -aviwrite test.avi`

The result is a filename `test.avi0`, removing `-snapview native` it creates the correct `test.avi`. The other modes (`auto`, `internal`, `pixel`) causes no issues.

**Comment by cd4053** [comment]
> Remember `-snapview native` needs to mangle the snapshot names as it produces multiple output files if the system has multiple screens.

Thank you, I'll use other modes than.

> What if you just use `-aviwrite test`? Will it call the file `test0.avi` in that case, or will the file just be called `test0`?

Using `-aviwrite test` it produces a file named `test0`, without the `.avi` extension.

**Comment by cd4053** [comment]
Thanks.

**Comment by cuavas** [comment]
Fixed in 875ee33542ffef5065bccb5f20af972bd8caa890.  For a system with a single screen (or no screens), it will produce `test.avi`.  For systems with multiple screens, it will produce `test0.avi`, `test1.avi`, etc.

**Comment by cd4053** [comment]
Thank you.
