### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by macm2pro** [mamedev/mame#10025]
Why is no Mac version build by the mame team and only a windows version?

It would be interesting to have Intel and M1/M2 version for Mac, along with the windows exec available for download.

What do you think?

**Comment by macm2pro** [comment]
I understand for linux it's kind of impossible to provide an exec. that works everywhere but for MacOS, it should be the same as for windows (when using minimum version of the OS).
However not being a developer, I can't compile it myself.

**Comment by rb6502** [comment]
We don't have the resources, it's dead easy for even non-technical users to build MAME on macOS, and builds are available in a timely fashion at https://sdlmame.lngn.net/ for Intel.  (For non-technical players, we recommend running the Intel binary under Rosetta as some games don't run correctly in the ARM native build).

**Comment by macm2pro** [comment]
Is windows ARM version planned? Or are the same problems occuring there?

**Comment by macm2pro** [comment]
Is the same reason also the reason that there's no android version available?
Anno 2022 it's a bit of a shame no mobile version exists. But I understand it needs more resources.

Are there plans for the far future to provide android versions?
It seems possible because retroarch has an android core and I didn't see any game not working (on ARM phone and tablet)

**Comment by rb6502** [comment]
No developers have Windows on ARM and you're the first person to ask about it so there clearly isn't much demand.

Mobile's rough for a number of reasons (touch controls for starters) and nobody's volunteered to make it happen.

**Comment by cuavas** [comment]
> Mobile's rough for a number of reasons (touch controls for starters) and nobody's volunteered to make it happen.

Half the reason I keep slowly untangling the UI code is so I can get touch controls to work in a sane way.

**Comment by intrepidsilence** [comment]
> We don't have the resources, it's dead easy for even non-technical users to build MAME on macOS, and builds are available in a timely fashion at https://sdlmame.lngn.net/ for Intel. (For non-technical players, we recommend running the Intel binary under Rosetta as some games don't run correctly in the ARM native build).

@rb6502 Is there a report tracking these ARM macOS issues? I could not find it. TIA!

**Comment by galibert** [comment]
I think that means cpu cores that are drc-only, which iirc are the tgpx4 (model2c) and powerpc (model3, some macs, bebox, probably some other stuff I don't remember about).

**Comment by galibert** [comment]
As to why the drc does not generate arm64 code yet... well nobody did the work, and people looking at the drc are not convinced it should stay the way it is in the first place, so writing a new backend is not that tempting.
