### ISSUE TITLE
0.245 unbuild.

### ISSUE THREAD

**Issue by hiroshica** [mamedev/mame#10064]
"https://www.mamedev.org/tools/" I dropped the MSYS2 written here, git clone and built it, but I get the following error.
Compiling generated/version.cpp...
Emitting mame_mame_vers.rc...
usage: makedep.py [-h] [-r <srcroot>] <command> ...
makedep.py: error: argument <command>: invalid choice: 'Shioya/working/srcs/mame/' (choose from 'sourcesproject', 'filterproject', 'sourcesfilter', 'driverlist', 'reconcilelist')
Compiling resources generated/resource/mame_mame_vers.rc...
make[2]: *** [mame.make:338: ../../../../generated/mame/mame/drivlist.cpp] エラー 2
make[2]: *** 未完了のジョブを待っています....
make[1]: *** [Makefile:1102: mame] エラー 2
make: *** [makefile:1119: windows_x64] エラー 2

**Comment by Robbbert** [comment]
The error indicates you're using code that is later than that available on the release page.

Are you trying to build the latest git instead?

**Comment by hiroshica** [comment]
git checkout -b mame0245 mame0245 and the build error is here.
Compiling src/mame/mame.cpp...
Building driver list...
Compiling generated/version.cpp...
Emitting mame_mame_vers.rc...
usage: verinfo.py [-h] [--target <target>] [--subtarget <subtarget>] [--executable <executable>] [--format <format>] [--resources <resfile>] [-o <outfile>] <srcfile>
verinfo.py: error: unrecognized arguments: ../../../../generated/version.cpp
make[2]: *** [mame.make:342: ../../../../generated/resource/mame_mame_vers.rc] エラー 2
make[2]: *** 未完了のジョブを待っています....
39087 driver(s) found
make[1]: *** [Makefile:1204: mame] エラー 2
make: *** [makefile:1113: windows_x64] エラー 2

Here is the error message that was generated by extracting and building the distributed mame0245s.
Compiling src/mame/mame.cpp...
Building driver list...
Compiling generated/version.cpp...
Emitting mame_mame_vers.rc...
usage: verinfo.py [-h] [--target <target>] [--subtarget <subtarget>]
                  [--executable <executable>] [--format <format>]
                  [--resources <resfile>] [-o <outfile>]
                  <srcfile>
verinfo.py: error: unrecognized arguments: ../../../../generated/version.cpp
make[2]: *** [mame.make:342: ../../../../generated/resource/mame_mame_vers.rc] Error 2
make[2]: *** Waiting for unfinished jobs....
39087 driver(s) found
make[1]: *** [Makefile:1204: mame] Error 2
make: *** [makefile:1113: windows_x64] Error 2

**Comment by cuavas** [comment]
Your project files are out-of-sync with your source, or you have local modifications to the code that are incompatible with the latest source.  This will only happen if scripts/src/main.lua does not match scripts/build/verinfo.py.  Remove the entire build directory, ensure your source code is not locally modified and try again.

**Comment by galibert** [comment]
Lets us know how it goes with a clean source, thanks.

**Comment by hiroshica** [comment]
mame0245s.exe is the source as expanded, not the github code <= this is clean

**Comment by hiroshica** [comment]
当然 Make clean も試しにしています。　これで初期化されないなら
makefile はバグです

**Comment by cuavas** [comment]
Do you have spaces or other characters that could be misinterpreted by the shell in the path to your source directory?  The scripts make no attempt to quote or escape command arguments.

**Comment by hiroshica** [comment]
スペースはありますが、 mame0244 tagではエスケープできていたのに　mame024 tag でできないのは
手抜きですよね。　なるほど、今のMAME Dev Teamの考えはわかりました。自分のところさえ動けば他人の環境は
どうでもいいんですね。

**Comment by Robbbert** [comment]
Translated:

understood. Then, I will stop messing with the source group until CMake is introduced.
Thank you very much.
