### ISSUE TITLE
attempt to call a nil value (global 'define')

### ISSUE THREAD

**Issue by Arbars** [mamedev/mame#10080]
Hi there!

Trying to build MAME for Linux.
GENie from 3rdparty bundle
GCC10
Make 4.3

Build output:

+ ./bin/linux/genie embed
...src/RPM/BUILD/mame-0245/3rdparty/genie/scripts/genie.lua:80: attempt to call a nil value (global 'define')
stack traceback:
	...src/RPM/BUILD/mame-0245/3rdparty/genie/scripts/genie.lua:80: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:109: in function 'dofile'
	[string "_WORKING_DIR        = os.getcwd()..."]:46: in function '_premake_main'

Maybe I missing something?

**Comment by cuavas** [comment]
What’s your full make command?  What Linux distro is this?  Are you building from a path containing any characters that could be interpreted by the shell?

**Comment by Arbars** [comment]
Distro: ALT Workstation K P10


Well, I'm just trying to use list of flags from Fedora spec file:
<pre class="syntaxhighlightblock"><code class="lang-rpm-specfile hljs">

NOWERROR=1 \
--
  | OPTIMIZE=2 \
  | PYTHON_EXECUTABLE=python3 \
  | VERBOSE=1 \
  | USE_SYSTEM_LIB_EXPAT=1 \
  | USE_SYSTEM_LIB_FLAC=1 \
  | USE_SYSTEM_LIB_GLM=1 \
  | USE_SYSTEM_LIB_JPEG=1 \
  | USE_SYSTEM_LIB_PORTAUDIO=1 \
  | USE_SYSTEM_LIB_PORTMIDI=1 \
  | USE_SYSTEM_LIB_PUGIXML=1 \
  | USE_SYSTEM_LIB_RAPIDJSON=1 \
  | USE_SYSTEM_LIB_SQLITE3=1 \
  | USE_SYSTEM_LIB_UTF8PROC=1 \
  | USE_SYSTEM_LIB_ZLIB=1 \
  | SDL_INI_PATH="%{_sysconfdir}/%{name};" \
  | TOOLS=1 \
  | OPT_FLAGS="$RPM_OPT_FLAGS" \
  | LDOPTS="$RPM_LD_FLAGS"

</code></pre>
But I got those error. After that I just rewrite list and error is gone. I think in our distro building with python3 is not possible...
My List:

<pre class="syntaxhighlightblock"><code class="lang-rpm-specfile hljs">
make OPTIMISE="%optflags" \
    $MAME_FLAGS \
    TOOLS=1 \
    NOWERROR=1 \
    ARCHOPTS=-U_FORTIFY_SOURCE \
    USE_SYSTEM_LIB_ASIO=1 \
    USE_SYSTEM_LIB_EXPAT=1 \
    USE_SYSTEM_LIB_FLAC=1 \
    USE_SYSTEM_LIB_GLM=1 \
    USE_SYSTEM_LIB_JPEG=1 \
    USE_SYSTEM_LIB_PORTAUDIO=1 \
    USE_SYSTEM_LIB_PORTMIDI=1 \
    USE_SYSTEM_LIB_RAPIDJSON=1 \
    USE_SYSTEM_LIB_SQLITE3=1 \
    USE_SYSTEM_LIB_UTF8PROC=1 \
    USE_SYSTEM_LIB_ZLIB=1 
</code></pre>

**Comment by cuavas** [comment]
Most of the build scripts require Python 3 at this point – `PYTHON_EXECUTABLE` is set to `python3` by default in makefile at line 445.
