### ISSUE TITLE
grapplerplus unknown device

### ISSUE THREAD

**Issue by exoscoriae** [mamedev/mame#10107]
According to the driver page here:
https://wiki.mamedev.org/index.php/Driver:Apple_II

The following command line addition: -sl1 grapplerplus -sl1:grapplerplus:prn ap2000

Should launch the apple2gs machine with the grapplerplus as a second screen.

However it currently (mame 0.245) gives the error:
unknown slot option 'grapplerplus' in slot 'sl1'

The parallel driver works fine however. Has support for this been deprecated?

**Comment by einstein95** [comment]
The device is called `grapplus` in MAME

**Comment by exoscoriae** [comment]
thank you. Is there a resource that lists the device names?

**Comment by einstein95** [comment]
You can do `mame apple2gs -listslots` to list what devices can be used in what slot for a driver

**Comment by cuavas** [comment]
> I've fixed the device shortname referenced in the wiki link provided.

That isn’t the device short name (the short name is `a2grapplerplus` which you can see in the source or in `-listxml` output).  That’s a slot option value – as @einstein95 said, you can see possible values with `-listslots`.
