### ISSUE TITLE
Namco NA-1 CPU being little fast than IRL cabinets

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [mamedev/mame#10142]
I was doing something (searching youtube) and found this. The CPU is little fast than IRL machines, found on japanese namco channel.
https://youtu.be/Gkj3PQvGtXg

**Comment by 0kmg** [comment]
The video is not real hardware though; it says it's the Wii Virtual Console.

**Comment by cuavas** [comment]
This report is not valid.
