### ISSUE TITLE
SG1000/SC3000 gdbstub segfaults

### ISSUE THREAD

**Issue by helmha** [mamedev/mame#10141]
I was having trouble getting *-debugger gdbstub* to work with Sega SG1000/SC3000 as it always segfaulted. It works with Spectrum and SVI328. Had a look at Mame sourcecode and I think I found the problem in the header file *src/mame/sega/sg1000.h*:

```
class sg1000_state : public driver_device {
public:
  sg1000_state(const machine_config &mconfig, device_type type, const char *tag)
      : driver_device(mconfig, type, tag),
        m_maincpu(*this,  "Z80_TAG"),    <---- this is the problematic line

```

Code above segfaults, so I modified it as follows:
```
        ...
        m_maincpu(*this, "maincpu"), 
```

and now gdbstub works as it should also with SG1000/SC3000.

**Comment by cuavas** [comment]
If the GDB stub debugger requires a CPU to have a particular tag, that’s a problem with the GDB stub debugger.
