### ISSUE TITLE
ldplayer fails to link

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#1015]
As of 0.175, ldplayer does not build anymore:
> Compiling src/ldplayer/ldplayer.cpp...
> g++    -MMD -MP -MP -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x86 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/devices -I../../../../../src/ldplayer -I../../../../../src/lib -I../../../../../src/lib/util -I../../../../../3rdparty -I../../../../generated/ldplayer/layout -I../../../../generated/resource -I../../../../../scripts   -g -m32 -pipe -Wno-deprecated-declarations -O2 -fno-strict-aliasing -O2 -g1 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-unused-result -Wno-array-bounds -m32 -x c++ -std=c++14 -Woverloaded-virtual -Wsuggest-override  -o "../../../../linux_gcc/obj/x32/Release/src/ldplayer/ldplayer.o" -c "../../../../../src/ldplayer/ldplayer.cpp"
>../../../../../src/ldplayer/ldplayer.cpp: In member function 'chd_file* ldplayer_state::get_disc()':
>../../../../../src/ldplayer/ldplayer.cpp:184:8: error: 'osd_directory_entry' does not name a type
  const osd_directory_entry *dir;
        ^~~~~~~~~~~~~~~~~~~
>../../../../../src/ldplayer/ldplayer.cpp:185:10: error: 'dir' was not declared in this scope
  while ((dir = path.next()) != NULL)
          ^~~
>ldplayer.make:271: recipe for target '../../../../linux_gcc/obj/x32/Release/src/ldplayer/ldplayer.o' failed
>make[2]: *** [../../../../linux_gcc/obj/x32/Release/src/ldplayer/ldplayer.o] Error 1
>make[1]: *** [ldplayer] Error 2

**Comment by Osso13** [comment]
Thanks for the report, fixed.
