### ISSUE TITLE
maclc3 : Regression : Playing sounds freezes the emulated machine

### ISSUE THREAD

**Issue by Saph32** [mamedev/mame#10159]
Since MAME 0.246, playing sounds on the emulated Macintosh LC 3 causes the machine to be unresponsive. This wasn't happening with MAME 0.245.

Repro steps:
- Use System 7.5.5 image from https://wiki.mamedev.org/index.php/Driver:Mac_68K
- Command line : mame.exe maclc3 -hard1 mac755.chd -ram 32M
- Go to Sound control panel
- Click on the various alert sounds
- The system will freeze

**Comment by rb6502** [comment]
Thanks for the report!  This has been corrected in e5fcbccff879fdc20f6532a5d13d5a259918836d.
