### ISSUE TITLE
ZX Spectrum +3e wasn't a system but was an updated rom created by a person

### ISSUE THREAD

**Issue by simzy39** [mamedev/mame#10151]
@holub 

Driver [specpls3.cpp](https://github.com/mamedev/mame/blob/master/src/mame/sinclair/specpls3.cpp) lists ZX Spectrum 3e as a machine by Amstrad, but it wasn't a board/machine.

+3e was an updated rom made by Garry Lancaster, [Link 1](https://www.retroisle.com/sinclair/zxspectrum/Technical/Hardware/spectrum+3e.php#blowown), [Link 2](https://sinclair.wiki.zxnet.co.uk/wiki/%2B3e).

The rom also appears to have multiple versions, the current version being v1.38 (driver doesn't indicate this info, and I don't know which version is now in Mame).

I don't understand what the driver means by: ZX Spectrum +3e 8bit IDE, ZX Spectrum +3e 8bit ZXATASP, and ZX Spectrum +3e 8bit ZXCF. Are these roms?

**Comment by rb6502** [comment]
Those are all marked MACHINE_UNOFFICIAL, which means they're preset configurations to make things easier for users.

**Comment by cuavas** [comment]
MAME has system definitions for various common third-party and homebrew modifications of various systems.  Please discuss this on a forum or something.
