### ISSUE TITLE
Renegade: Sprite vertical offset

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#10167]
The sprites are drawn in MAME lower than they should. Compare this MAME snapshot:

![0000](https://user-images.githubusercontent.com/1863036/182150414-fc698f17-870a-426a-ab47-3dbc1e219fa9.png)

with this video [recording](https://youtu.be/-c1ZEp7MlNo?t=35). Check the boss for reference

**Comment by DavidHaywood** [comment]
I'm not sure what MAME version you're using, but that isn't where they're drawn in MAME, MAME appears to be the same (or at least very close to) the PCB video.

**Comment by angelosa** [comment]
Most likely fixed already two years ago -> https://github.com/mamedev/mame/commit/0dec5b71a3c0a0a73010aef2d3882c1c63f679da#diff-b160c309d3c9319b16a046e75d7391a6b96437d80f6896c367ceb6dc00e04ed8R78

![0002](https://user-images.githubusercontent.com/9251271/199828638-5946813b-c653-4c73-9128-09823b2b9369.png)

**Comment by MooglyGuy** [comment]
@jotego Would you please confirm whether this issue was due to you testing with an older version of MAME, and close this issue report if so? Thanks in advance!

**Comment by jotego** [comment]
Yes, let me check it

**Comment by MooglyGuy** [comment]
Thank you, while you're checking Renegade, did you have any luck extracting more info about the sprite line buffers in #10163 ?

**Comment by jotego** [comment]
The problem was in MAME 0.220, which seems to be what Ubuntu comes with. It does not occur in MAME 0.248
