### ISSUE TITLE
CHD - source part checksums.

### ISSUE THREAD

**Issue by midget35** [mamedev/mame#10177]
Can we please adapt the CHD metadata to include the checksums of the parts that are assimilated when the CHD is created? Eg Redump or Tosec sets might be the original source.

I believe this is vital for quickly identifying if a CHD's 'content' has recently been marked a 'bad dump', or if a rare alternative has just been discovered, etc., that should be included in the software list.

This would be a vital facility for those of us wishing to prove the viability and completeness of MAME SL CHDs.

**Comment by i30817** [comment]
They already refused this.

The only way is to use something like https://github.com/Manorhos/imageparse

then calculate the checksums yourself by iterating on the tracks that program 'makes a representation of'.


btw, that program doesn't support parent-child relationships but i suppose it's just a question of opening a bug report, which i did, because the current chd-rs supports them.

I'm also thinking of making a python wheel for it, in the style of https://github.com/chyyran/chd-rs-py (which unfortunately is only geared to 'read' a chd, not 'read as if it was divided into tracks').

**Comment by i30817** [comment]
BTW, the next version of imageparse will have both delta chd loading and a method to get the tracks sha1, and i'm doing a python binding, which if i manage to make work with the github maturin actions might end up on pypi, for your scripting pleasure.

**Comment by midget35** [comment]
> They already refused this.
> 
> The only way is to use something like https://github.com/Manorhos/imageparse
> 
> then calculate the checksums yourself by iterating on the tracks that program 'makes a representation of'.
> 
> btw, that program doesn't support parent-child relationships but i suppose it's just a question of opening a bug report, which i did, because the current chd-rs supports them.
> 
> For reference you can use github CI to build maturin (rust-python compilation program) wheels with this action: https://github.com/messense/maturin-action
> 
> I'm also thinking of making a python wheel for it, in the style of https://github.com/chyyran/chd-rs-py (which unfortunately is only geared to 'read' a chd, not 'read as if it was divided into tracks').
> 
> then you could do something like this but for the image parsing program, given a set of 'possible chd parent files' which you scan from the current directory, or a child directory, or a parent directory or 'something':
> 
> Spoiler warning
> i'm actually unsure that will work because i haven't tested it with a parent child yet.
> 
> edit: tested, it works (i think) after fixing a missing return in the is_cdrom method.

Thank you. Yes, I read your previous GIT issue many times over last week. It is what prompted me to create this issue.

I am aspiring to be as concise as possible. Looking at the MAME landing page (and what might be considered the mission statement), we can see this line:

"MAME’s purpose is to preserve decades of software history."

Given that statement, I do not see how this feature request (and elements of your previous request) can reasonably be closed. Obviously - I am not demanding anything. I do not expect anything. I simply want this issue to remain open. Not doing so is antithetical to the MAME project.

**Comment by rb6502** [comment]
It's already possible to extract the CHD to a disc and check the software version.  What you're describing is useful for niche activities that are not related to preservation.  So yes, I can in fact close this.

**Comment by midget35** [comment]
Please reconsider this decision. I genuinely have no idea what you mean by 'niche activities'. I am asking you to consider the rationale behind the request, rather than assuming negative consequences.

**Comment by midget35** [comment]
It is hubris to assume that a 'flawed' input, once converted to chd, would result in a perfect, irreducible, and inscrutable form. We don't want to do this.
