### ISSUE TITLE
Atari 8-bit: Elektra Glide graphics crashes (character mess).

### ISSUE THREAD

**Issue by CO-Windler** [mamedev/mame#10176]
I can not send this bug-report though Mametesters, because I got banned as an act of despotism. Please re-enable my account.
(They falsely claimed that I had posted too often false bug reports or whatever, because they failed to verify them, or that I did not include a requested  screenshot. (That's because my MAME is on a different computer than the machine I access the forum with. All my reports were genuine.)

On MAME Atari 8-bit emulation (I tried 800, 800XL each PAL and NTSC) the game "Elektra Glide" makes graphics bug. The title screen looks ok, but when the race starts, after few seconds a mess of big letters/characters appear in the middle of the screen. The car race itself continues, but you can't see the road properly. It looks like something goes very wrong with the display list.

System: MAME 0.246 on Win10

**Comment by MooglyGuy** [comment]
> An act of despotism

Emulation, serious business

**Comment by cuavas** [comment]
> I can not send this bug-report though Mametesters, because I got banned as an act of despotism. Please re-enable my account.

You need to drop the attitude and learn to accept guidance.  Failing that, you’ll be banned here, too.

**Comment by CO-Windler** [comment]
Hey, I did accept guidelines. If I remember well, it was about a rare sound glitch in Pole Position (arcade, it sometimes truncates explosions), and they requested me to record it/send a video. The laptop with my MAME is fairly slow (IBM X61t, Core2Duo 1600MHz with Intel graphics) and the small harddisk quite full, so it was impossible to capture in the background some 10 minutes of the gameplay video while waiting for the glitch to happen. I also do not and will never own a brainfryer, so I can't simply upload it with some smartphone swipes to social media or whatever they think. Theoretically I could have filmed it with a digicam on a big tripod stand, but that's much work. It is sheer impudence to ban me for not fulfilling their request and not replying in time. (And there is nowhere in the guidelines a law that defines a time limit for replies. I go online once per day and have no brainfryer in my pocket to reply within minutes. Hence it's despotism.)

**Comment by cuavas** [comment]
This is your last warning - drop the attitude.

**Comment by CO-Windler** [comment]
I got misincarnated. This mankind does not need me anyway. So I will swallow some drain pipe cleaner now to exit this incarnation.  
⚰️

**Comment by happppp** [comment]
If you're not exaggerating, call a friend/family, or suicide hotline.
And have some tea instead.
