### ISSUE TITLE
ncv1 ncv2 namcondl.ccp incorrectly reported refreshrate?

### ISSUE THREAD

**Issue by riggles1** [mamedev/mame#10227]
Both Namco Classic Collection vol 1+2 when you boot them up on the info screen say that they're 58.557786Hz (correct refresh for this system).
However when you check the machine info right away it says that they're 60.606061Hz.

Using MAME 246 (win10 64-bit) https://imgur.com/NuAodfA

Wondering if this is expected behavior? (this causes a bug with a custom rotation for a CRT with calamity switchres setup, long story short this causes crackling in these two games until you set the mame menu>slider>refresh slider to 58.55Hz, but this is forked and not related to main).

I'm more curious about if this game is supposed to report one thing, but set another, seems wrong and unlike any other game with a different refresh like 58Hz that I've tried (58Hz Gekirindan, modeline switching games like Astra Superstars, no issues with calamity switchres)

Is it correct to post this here? Since it's regarding how MAME sets a different refresh than it should. Or should this be a mametesters report?

Abnormal Check is also affected, same machine. namcondl.ccp

**Comment by 0kmg** [comment]
Yes, please do use mametesters for issues that affect released versions of MAME (like this report), GitHub Issues for problems with the development source tree.

That being said I think this may just be a known not-implemented-yet issue. It looks like the video display device (Yamaha YGV608) adjusts the timings while the system is running, which explains why the refresh rate changes.

Maybe @rb6502 or @angelosa can tell us if we need an open ticket here?

**Comment by rb6502** [comment]
Lots of systems in MAME can and do change video modes parameters at runtime.  This has been problematic for CRT setups (and it can be annoying when recording gameplay with -aviwrite), but it's not specifically a fault in MAME.

A comment in the code indicates that at least some of the modes of the supported ncv1/ncv2 games do program a video mode matching the original Namco hardware, including the 60.6060... refresh rate so the "correct" mode will vary based on what game you're currently playing.  This likely merits some investigation to make sure we aren't just forcing that mode on all mode switches, but at a glance it doesn't seem to be.

**Comment by cuavas** [comment]
This will happen with any system that has a programmable CRTC that switches modes while running.  If the system always programs the same video mode during gameplay, you can set the screen timing parameters in machine configuration to match that mode, but if the system uses different video modes at different times (or with different settings), one has to be chosen arbitrarily for the machine configuration.  Often the highest supported resolution is used, or the resolution of the most widely available monitor used with the card for computer video cards.

I don’t think it’s worth opening issues for these.  If you can show that the system always uses the same video timing parameters, you can open a pull request to set that in machine configuration.  Otherwise you’re going to have to deal with it.

**Comment by riggles1** [comment]
That's the thing, switchres works with any other refresh switching game mid game, and it was working with this until I set an accurate game rotation for vertical on a vertically oriented CRT. It would only do these Hz switches when forcing itself to not be displayed correctly

For some reason even after restart it was having issues last night, but but today it's working flawlessly, switches the CRT from ~58.6Hz (boot) to ~60.6Hz (gameplay) exactly like it should (using Calamity's switchres).

Really weird little bug, but hey now everything is working like it should! Never seen something go from not working to working the next day. 

But anyway, I just wanted to see if the 58-60Hz change was accurate for this game (in the case that MAME itself was reporting an incorrect refresh despite what the game wants). So that was my reasoning with posting it right here instead of MAMETesters or getting in touch with Calamity (since mid game switchres changes works with any other game that does this).

Glad it came down to fresh settings and a full restart resolving things :) thanks for the confirmation that MAME is performing like it should!

Thanks a lot for the replies, hope this post can help others who are facing issues with this machine with a CRT setup. Switchres can handle it no problems, so keep deleting settings and restarting, and get in touch with me so I can help if necessary as well.
