### ISSUE TITLE
chdman createcd TOC -> CHD -> TOC shows a few differences in TOC and BIN

### ISSUE THREAD

**Issue by vpelletier** [mamedev/mame#10230]
Note before starting: as such, this is not an anomaly report, but rather a surprising situation I noticed. I have no clear idea on the impact this can have in practice.

I made a backup copy of a PSX CD:
```
cdrdao read-cd --read-raw --read-subchan rw_raw --datafile SLES-02208.bin SLES-02208.toc
```
then converted it to CHD:
```
chdman createcd -v -o SLES-02208.chd -i SLES-02208.toc
```
and out of curiosity converted it back to TOC:
```
chdman extractcd -o SLES-02208_out.toc -i SLES-02208.chd
```

Here are the differences for the TOC:
```patch
--- SLES-02208.toc      2022-08-06 22:50:02.488896385 +0900
+++ SLES-02208_out.toc  2022-08-16 00:50:38.385692013 +0900
@@ -1,10 +1,10 @@
-CD_ROM_XA
+CD_ROM


 // Track 1
 TRACK MODE2_RAW RW_RAW
 NO COPY
-DATAFILE "SLES-02208.bin" 36:35:54 // length in bytes: 403134192
+DATAFILE "SLES-02208_out.bin" 36:35:54 // length in bytes: 403134192


 // Track 2
@@ -13,6 +13,7 @@
 NO PRE_EMPHASIS
 TWO_CHANNEL_AUDIO
 ZERO AUDIO RW_RAW 00:02:00
-DATAFILE "SLES-02208.bin" #403134192 03:30:00 // length in bytes: 38556000
+DATAFILE "SLES-02208_out.bin" #403134192 03:30:00 // length in bytes: 38556000
 START 00:02:00

+
```
Obviously, the only meaningful difference here is the first line. As per `cdrdao(1)`:
```
TOC FILES
[...]
   Header
[...]
       CD_ROM The disc contains just mode 1 tracks or mode 1 and audio tracks (mixed mode CD).

       CD_ROM_XA
              The disc contains mode 2 form 1 or mode 2 form 2 tracks. Audio tracks are allowed, too.
              This type must be used if multi session disks are created (option --multi).
```

This CD contains a `MODE2` (...`_RAW`) track, so `CD_ROM_XA` (input) seems correct, and `CD_ROM` (reconstructed file) incorrect.

The differences in the BIN file seem to be either between both track or at the beginning of the second track (0x18076020 bytes / 2448 bytes per sector = near the end of sector 164679, which is the length of the first track). I do not know enough of the CDROM format to tell if this difference is significant, and I do not know if this is related to the `CD_ROM{,_XA}` difference. Here is the first differing hunk in the original file:
```
1807 6020: 80 80 80 80 80 80 80 C0  80 80 80 80 80 80 C0 80  ........ ........
1807 6030: 80 80 80 80 80 80 80 C0  80 80 80 80 80 80 80 80  ........ ........
1807 6040: 80 80 80 80 80 80 80 80  80 80 80 80 80 80 80 80  ........ ........
1807 6050: 80 80 80 80 80 80 80 80  80 80 C0 C0 80 C0 C0 80  ........ ........
1807 6060: 80 80 C0 C0 C0 80 80 C0  80 C0 80 C0 80 C0 80 80  ........ ........
1807 6070: C0 C0 80 80 80 80 C0 C0  80 C0 C0 C0 80 C0 C0 C0  ........ ........
```
The corresponding region in the generated output is all 0x00.

The further differing hunks contain a few 0x40 bytes in the original file which also become 0x00 in the generated one, with the second hunk being from 0x180769B0 to 0x18076A0F (inclusive, taking whole 0x10 bytes-aligned runs). The last differing hunk is from 0x180CF0F0 to 0x180CF14F (inclusive, taking whole 0x10 bytes-aligned runs).

The CHD info output is:
```
$ chdman info -v -i SLES-02208.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.246 (unknown)
Input file:   SLES-02208.chd
File Version: 5
Logical size: 441,697,536 bytes
Hunk Size:    19,584 bytes
Total Hunks:  22,554
Unit Size:    2,448 bytes
Total Units:  180,432
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     238,192,365 bytes
Ratio:        53.9%
SHA1:         415407d4e3cf270069aa0fc0d2e637a25b8ed971
Data SHA1:    2d4243fe5eb31e62c00924fa73ee5416ad7a6738
Metadata:     Tag='CHT2'  Index=0  Length=95 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:RW_RAW FRAMES:164679 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0.
Metadata:     Tag='CHT2'  Index=1  Length=92 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:RW_RAW FRAMES:15750 PREGAP:150 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0.

     Hunks  Percent  Name
----------  -------  ------------------------------------
    18,334    81.3%  CD LZMA
     2,251    10.0%  CD Deflate
     1,969     8.7%  CD FLAC
```

The entire original TOC is:
```
CD_ROM_XA


// Track 1
TRACK MODE2_RAW RW_RAW
NO COPY
DATAFILE "SLES-02208.bin" 36:35:54 // length in bytes: 403134192


// Track 2
TRACK AUDIO RW_RAW
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ZERO AUDIO RW_RAW 00:02:00
DATAFILE "SLES-02208.bin" #403134192 03:30:00 // length in bytes: 38556000
START 00:02:00
```

Then, out of one more layer of curiosity, I converted the generated file to CHD again:
```
$ chdman info -v -i SLES-02208_out.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.246 (unknown)
Input file:   SLES-02208_out.chd
File Version: 5
Logical size: 441,697,536 bytes
Hunk Size:    19,584 bytes
Total Hunks:  22,554
Unit Size:    2,448 bytes
Total Units:  180,432
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     238,189,881 bytes
Ratio:        53.9%
SHA1:         9fff78749487bdc4b1a288ecc1852a4b41cf5e59
Data SHA1:    9f9131b23d63f6705a3b2aec95f7ab88661867df
Metadata:     Tag='CHT2'  Index=0  Length=95 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:RW_RAW FRAMES:164679 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0.
Metadata:     Tag='CHT2'  Index=1  Length=92 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:RW_RAW FRAMES:15750 PREGAP:150 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0.

     Hunks  Percent  Name
----------  -------  ------------------------------------
        17     0.1%  Copy from self
    18,334    81.3%  CD LZMA
     2,251    10.0%  CD Deflate
     1,952     8.7%  CD FLAC
```

The `Data SHA1` differs from the original conversion, and there are a few "Copy from self" hunks.

**Comment by DavidHaywood** [comment]
last time I tried using TOC as a source it didn't round-trip properly either, and that was years ago, the image didn't work properly either.

I'm not sure TOC as a source is really properly supported.

**Comment by vpelletier** [comment]
> I'm not sure TOC as a source is really properly supported

Judging by the source code, TOC is the main supported format: TOC is called `MODE_NORMAL`, CUE and GDI having their own names (`MODE_CUEBIN` and `MODE_GDI`). My understanding is that TOC supports subchannels, which are entirely missing in CUE, so TOC would be "more supported" than CUE/BIN for preservation purposes (ex: not needing SBI files for libcrypt PSX games - as the one I picked, as the subchannels are just there in the image).

The original TOC and the CHD (first generation anyway, I have not tested the ones produced from the CHD) are working fine so far.

Maybe these differences are just fine and can be ignored, I was doing a round-trip to see if I could delete the TOC/BIN files to free up space if they could be reproduced losslessly from CHD. As I cannot tell if these differences are meaningful, I'll keep those around some more.

**Comment by DavidHaywood** [comment]
Failure to round-trip however makes it lossy, and is a major bug IMHO however you look at it.

**Comment by 987123879113** [comment]
re: `CD_ROM_XA`
Looks like it just doesn't try to detect if it should be `CD_ROM` or `CD_ROM_XA` and is hardcoded to use `CD_ROM`. 
https://github.com/mamedev/mame/blob/c20662d2400d6b80693bd038187ed9acd3be71d5/src/tools/chdman.cpp#L1401-L1403

re: Roundtrip problem
I was just about to convert something with toc/bin and decided to try it out myself and I also see the same roundtrip problem. The data is in the CHD. The problem is that the `read_subcode` function isn't passing the phys flag to `read_partial_sector`, which in turn ends up handling pregap incorrectly here: 

https://github.com/mamedev/mame/blob/25c64006b7ca4bbb0d575b46c6c5c4f214dac7ed/src/lib/util/cdrom.cpp#L382-L392

If you set the `EXTRA_VERBOSE` then you'll see the "PG missing sector" messages exactly where the data is getting zero'd out in the extracted CD data.

Passing the `phys` flag to `read_partial_sector` properly results in the same input and output BINs:
```
>chdman createcd -i 886A02.toc -o 886A02_toc_test.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.246 (mame0226-7972-gf792846cfa6-dirty)
Output CHD:   886A02_toc_test.chd
Input file:   886A02.toc
Input tracks: 69
Input length: 66:40:61
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
Logical size: 734,781,888
Compression complete ... final ratio = 63.2%            

>chdman extractcd -i 886A02_toc_test.chd -o 886A02_toc_test2.toc
chdman - MAME Compressed Hunks of Data (CHD) manager 0.246 (mame0226-7972-gf792846cfa6-dirty)
Output TOC:   886A02_toc_test2.toc
Output Data:  886A02_toc_test2.bin
Input CHD:    886A02_toc_test.chd
Extraction complete                                    

>sha1sum -b 886A02.bin 886A02_toc_test2.bin
5324f6b05eb864a4d89ba9b2014640d9069d0df3 *886A02.bin
5324f6b05eb864a4d89ba9b2014640d9069d0df3 *886A02_toc_test2.bin
```

I tried some redump PS1 bin/cues at it just to test to make sure the extracted data works in other cases and the SHA-1s match with redump after roundtripping bin/cue -> chd -> bin/cue (and bin/toc to be sure).

I'll send off a PR to fix the roundtrip problem.

**Comment by 987123879113** [comment]
@vpelletier The changes I submitted to fix both bugs mentioned in this issue are in the master branch now. Please try it out when you get a chance. It should be in this month's MAME release, or if you can compile it yourself or download Github build artifacts.
