### ISSUE TITLE
Mac m1 why not setting language

### ISSUE THREAD

**Issue by dorameonsu** [mamedev/mame#10243]
<img width="1336" alt="WechatIMG974" src="https://user-images.githubusercontent.com/85793026/185627304-0ade3ef9-d95b-489b-b821-d05ba489438e.png">

**Comment by cuavas** [comment]
Please describe the issue you’re experiencing in text, as well as how you’re starting MAME.  I expect what’s happening is that the working directory is set to your home directory, so MAME isn’t seeing the translation files.  See here: https://docs.mamedev.org/commandline/commandline-all.html#file-names-and-directory-paths

**Comment by dorameonsu** [comment]
> Please describe the issue you’re experiencing in text, as well as how you’re starting MAME. I expect what’s happening is that the working directory is set to your home directory, so MAME isn’t seeing the translation files. See here: https://docs.mamedev.org/commandline/commandline-all.html#file-names-and-directory-paths

thanks  I solved
