### ISSUE TITLE
Implementation Question RE: Star Force

### ISSUE THREAD

**Issue by AidyCC** [mamedev/mame#10258]
Hi

I'd like to get a better understanding of how the sound works in Star Force (driver: senjyo.cpp).

The hardware has 3 SN76496 chips, each of which has 3 channels giving the hardware 9 channels in total.

Analyzing the code from the SF sound ROM shows that there are actually 10 sound channels used in the game.  The first 9 are the ones provided by the sound chips but the last one seems to get it's frequency from the z80ctc chip on port 0x0a.

My question is where in the emulation code is that 10th channel managed and the sound generated?

Thanks.

**Comment by einstein95** [comment]
https://github.com/mamedev/mame/blob/master/src/devices/machine/z80ctc.cpp

**Comment by cuavas** [comment]
Please use discussion forums for discussions – don’t abuse the issue tracker.

Some forums you could consider:
* https://github.com/orgs/mamedev/discussions
* https://www.reddit.com/r/MAME/
* https://forum.mamedev.org/
