### ISSUE TITLE
Sega System32 games in the wrong aspect ratio

### ISSUE THREAD

**Issue by Alevam-Inc** [mamedev/mame#10286]
The pixel aspect ratio for Sega System32 games should be 10:7 (320x224), but instead it's 13:7 in MAME for some reason.

**Comment by cuavas** [comment]
The screens are configured for 416*224 on start.  MAME often configures the maximum supported screen resolution for systems that support multiple video modes.

**Comment by Alevam-Inc** [comment]
I guess that makes sense. Is there any way to fix it?

**Comment by rb6502** [comment]
It's not broken.  MAME correctly produces a 4:3 image regardless of the underlying video mode if you haven't messed with the settings.

**Comment by cuavas** [comment]
If you want a view that displays square pixels for the current video mode when a machine switches video modes, MAME can’t do that automatically.

You can create an external layout file with a view with whatever aspect ratio you want and put it in an appropriate place in your artwork folder.

**Comment by Alevam-Inc** [comment]
How would I go about doing that?

**Comment by rb6502** [comment]
What is your use case where presenting these games in their correct 4:3 aspect ratio doesn't work?

**Comment by cuavas** [comment]
Take it to a discussion forum.  Layout files are documented here: https://docs.mamedev.org/techspecs/layout_files.html
