### ISSUE TITLE
[ubuntu 22.04][GCC 11][amd64][0.247] Compilation with precompiled headers does not work when custom ARCHOPTS are supplied

### ISSUE THREAD

**Issue by lvd2** [mamedev/mame#10310]
When compiling MAME 0.247 with custom ARCHOPTS:
```
make clean
make VERBOSE=1 REGENIE=1 ARCHOPTS='-march=native -mtune=native'
```
the compilation fails like this:
```
Precompiling src/emu/emu.h...
g++    -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/lib/util"  -m64 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -march=native -mtune=native -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-stringop-truncation -Wno-stringop-overflow -Wno-nonnull -Wno-stringop-overread -m64 -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -x c++-header -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/lib/util" -o "../../../../linux_gcc/obj/x64/Release/emu.h.gch" -c "../../../../../src/emu/emu.h"
Compiling src/emu/drivers/empty.cpp...
g++    -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/lib/util"  -m64 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -march=native -mtune=native -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-stringop-truncation -Wno-stringop-overflow -Wno-nonnull -Wno-stringop-overread -m64 -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -include ../../../../linux_gcc/obj/x64/Release/emu.h -o "../../../../linux_gcc/obj/x64/Release/src/emu/drivers/empty.o" -c "../../../../../src/emu/drivers/empty.cpp"
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: note: use -Winvalid-pch for more information
<command-line>: fatal error: ../../../../linux_gcc/obj/x64/Release/emu.h: No such file or directory
compilation terminated.
```
(the full log is in attach)

When additionally supplying PRECOMPILE=0 or just removing ARCHOPTS -- the compilation continues.

The same thing happens with 0.246.

[mame_compile.log.gz](https://github.com/mamedev/mame/files/9491229/mame_compile.log.gz)

**Comment by cuavas** [comment]
This should only happen if you make a change that causes compile options to change in a way that makes the precompiled header incompatible, and don’t manually remove the precompiled header file.  Changes that can cause this include:
* Upgading/downgrading your compiler
* Upgrading/downgrading system and/or standard library header files
* Changing certain build options

GENie doesn’t generate dependencies for macro definitions or compile options, and isn’t aware of when you change things in the host environment.  You may need to manually remove the precompiled header file if you make changes like this.  Given it will require everything to be recompiled anyway, it’s often just as easy to remove the entire build products directory (build/linux_gcc in your case).

**Comment by lvd2** [comment]
This happens already with a freshly cloned repo like this:
```
git clone https://github.com/mamedev/mame.git
cd mame
git switch --detach mame0247
```
(then make as in first comment)

**Comment by cuavas** [comment]
Can you please test with GCC 10 or GCC 12?  There have been persistent issues with GCC 11 on Linux.  For example see these threads:
* https://www.reddit.com/r/MAME/comments/wz3m9o/compilation_error/
* https://github.com/mamedev/mame/issues/9930

Also, if possible, please try using GCC built in its default configuration.  Ubuntu packagers are known to make various modifications, including predefining `FORTIFY_SOURCE`.  It’s possible some other Ubuntu modification is causing an issue.

**Comment by danmons** [comment]
I've tested with:

Working:
* Ubuntu 20.04 and GCC 9.4 - compiles and links fine
* crosstool-ng cross-compile environment for RPi armhf and aarch64, GCC 10.2 - compiles and links fine
* Arch Linux and GCC 12.2 - compiles and links fine

Not working:
* Ubuntu 22.04 and GCC 11.2 - compiles, but fails to link.

**Comment by cuavas** [comment]
Please take it up with the Ubuntu GCC packagers to determine whether it is caused by some Ubuntu configuration issue. If it's found to an issue in GCC itself, open an upstream issue. We don't have the resources to deal with broken toolchains.

In the mean time, disable precompiled headers, or use a different compiler (e.g. clang or a locally-inatalled GCC).

**Comment by lvd2** [comment]
I've made some research and it seems this is actually not a MAME bug. The build (or actually the beginning of it) as described was successfull in VMs with (server edition) ubuntu 22.04 (gcc 11), ubuntu 22.10 (gcc 12) and ubuntu 20.04 (gcc 9).
