### ISSUE TITLE
Mame failed to build with "error C1083: Cannot open source file: '..\..\..\..\..\src\mame\gaelco\wrally_v.cpp': No such file or directory" with MSVC on Windows

### ISSUE THREAD

**Issue by nnfdnkns** [mamedev/mame#10335]
Hi all,

Mame failed to build with "error C1083: Cannot open source file: '..\..\..\..\..\src\mame\gaelco\wrally_v.cpp': No such file or directory" with MSVC on Windows.Could you please help look at this issue?

**Environment:**
Windows: windows server 2019
VS: 2019

**Repro steps:**
1.open VS2019 x64 tools command
2.git clone https://github.com/mamedev/mame  F:\gitP\mamedev\mame
3.cd F:\gitP\mamedev\mame
4.git submodule update --init --recursive
5.set PATH=F:\gitP\mamedev\mame\..\tools\msys64\usr\bin;F:\gitP\mamedev\mame\..\tools\msys64\mingw64\bin;%PATH%
6.make SUBTARGET=tiny PTR64=1 TOOLS=1 OPTIMIZE=0 NOWERROR=1 MODERN_WIN_API=1 NO_USE_PORTAUDIO=1 vs2019 -j4 2>&1
7.cd F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019
8.msbuild /m /p:Platform=x64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 mametiny.sln /t:Rebuild 2>&1

**Error info:**
41>c1xx : fatal error C1083: Cannot open source file: '..\..\..\..\..\src\mame\gaelco\wrally_v.cpp': No such file or directory (C:\repos\msvc\src\vctools\Compiler\CxxFE\sl\p1\c\p0io.c:1588) [F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019\mame_tiny.vcxproj]

**log**
[build.log](https://github.com/mamedev/mame/files/9564105/build.log)

**Comment by cuavas** [comment]
Already fixed in f9728327f89e5cadaa36d3ddab9458580a00ac59

**Comment by nnfdnkns** [comment]
Ok, thank you!
