### ISSUE TITLE
Original photoplay arcade donation

### ISSUE THREAD

**Issue by maikeru99** [mamedev/mame#10340]
I could soon probably get an original photoplay arcade (made by funworld). Is there a way to send this to anyone who could work in improving the emulation of the board?

**Comment by ICEknigh7** [comment]
Where are you located?

**Comment by maikeru99** [comment]
Spain

**Comment by ICEknigh7** [comment]
I'll see what can be done.

**Comment by clawgrip** [comment]
Please, mail me: clawgrip@hotmail.com (Madrid, Spain)

**Comment by angelosa** [comment]
Closing, don't see anything that warrants otherwise.
