### ISSUE TITLE
MAME should not prevent running a system if a BIOS that is not selected is not present.

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#10351]
Since this request keeps being closed on MAME testers with no discussion, I am trying to open it over here. First I was told it wasn't related to a specific driver, and it was closed, then I was told to open it as a feature request and it was closed with a status of won't fix with no further explanation.

An error should be thrown a the time the BIOS is actually attempting to load. Missing additional BIOS ROMs should not prevent a system from running if they are not needed. I think the way to fix this might be to mark the ROM as optional and the change the way optional ROMs are handled so that it distinguishes between an invalid check sum and file not found. If the check sum is invalid, it should throw a warning and continue because someone might be testing or debugging a ROM, but if the file is missing at the time of loading, it should throw an error and abort.

Saying this is too hard to fix or saying this is how it works is NOT a reason to mark this issue as invalid. Marking this as invalid without discussion is necessarily aggressive and counter productive. MAME should be throwing an error at the time MAME actually attempts to load the ROM, not when the emulation is launched. Saying "oh, just launch it from the command line" is NOT answer, as that simply makes the user interface pointless. If you are going to have a GUI, then support it and make it work PROPERLY. We should discuss it first before marking it as invalid without discussion since it hamper the use of the GUI.

**Comment by galibert** [comment]
Discuss what?  It is too hard to fix, so unless you're ready to fix it yourself and send a PR you're just wasting everyone's time.

**Comment by DavidHaywood** [comment]
This is now the 3rd place you've tried to open this.

It's by design.  You don't like the design.

As best this is a feature request, but the way you're going about it is just going to ensure nobody ever looks at it.
