### ISSUE TITLE
chdman createcd : the hunk size cannot be set to any other value except a multiple of 2448

### ISSUE THREAD

**Issue by crashGG** [mamedev/mame#10352]
When compressing a cd image with chdman, the hunk size cannot be set to any other value except a multiple of 2448
<img width="484" alt="2022-09-19_102620" src="https://user-images.githubusercontent.com/80488411/190968768-e550ade9-9ecd-4f00-ada0-24cc4d3f679f.png">

As we all know, most console CD images are 2352 per sector, like psx ,ps2 with mode2/2352 ,Dreamcast with mode1/2352

This will cause the chd hunk to be unable to align with the disc sector, thus increasing the access delay of the image file.

**Comment by darkstar** [comment]
The raw sector size of a CD ROM is 2448 bytes per sector (2352 bytes data + 96 bytes subchannel).

Some console games (CD+G ?) actually use the full 2448 bytes so I guess that's why it has to be a multiple of 2448 bytes....

**Comment by crashGG** [comment]
> The raw sector size of a CD ROM is 2448 bytes per sector (2352 bytes data + 96 bytes subchannel).
> 
> Some console games (CD+G ?) actually use the full 2448 bytes so I guess that's why it has to be a multiple of 2448 bytes....
yes ,you are right. chdman uses full 2448 bytes as logical sector，No matter how many bytes per sector the disc image is physically
