### ISSUE TITLE
Add complete support for "Rikki & Vikki"

### ISSUE THREAD

**Issue by soundsnow** [mamedev/mame#10369]
https://github.com/gstanton/ProSystem1_3/pull/5

**Comment by soundsnow** [comment]
https://github.com/libretro/prosystem-libretro/pull/71
https://github.com/libretro/prosystem-libretro/pull/72
https://github.com/libretro/prosystem-libretro/pull/73

**Comment by DavidHaywood** [comment]
this looks like a 'request' not an 'issue'

and from what I can tell the ugly libretro stuff you're linking to is just emulating a 'virtual console' using images from steam, not something that exists in physical form?

either way, not the place for requests.

**Comment by startaq** [comment]
There is a physical version: http://www.penguinet.net/Games/Rikki_Vikki/Purchase/index.php

**Comment by soundsnow** [comment]
[BupSystem](http://tailchao.com/BupSystem) was the only emulator that supported this game

	<game name="Rikki & Vikki (World) (Aftermarket) (Unl)">
		<description>Rikki & Vikki (World) (Aftermarket) (Unl)</description>
		<rom name="Rikki & Vikki (World) (Aftermarket) (Unl).a78" size="524288" crc="3ea5d821" md5="b3bc889e9cc498636990c5a4d980e85c" sha1="b26d3125a109fed15e380dc32f2e55d84f350450" sha256="974dc24cbd7a817571aefd12bde86d1730b2c57a436d4d0ad15a094329e1e5a2"/>
	</game>

**Comment by soundsnow** [comment]
https://github.com/mamedev/mame/blob/master/hash/a7800.xml
I can't find Rikki or Vikki here, so MAME must not support it
I'm very puzzled that this game isn't exactly cold on YouTube, but the MAME contributors don't seem to know it exists
And it's a good game

**Comment by angelosa** [comment]
We don't open "issues" for new games additions.
