### ISSUE TITLE
Guide to compile with arm64 processors

### ISSUE THREAD

**Issue by flashboss** [mamedev/mame#10366]
Hi, how I compile the 0.235 mame sources using my processor on a mac osx with arm64 processor?

Try this command:

make -j$(sysctl -n hw.ncpu) NOWERROR=1 PYTHON_EXECUTABLE=python3

I get:

ld: symbol(s) not found for architecture arm64

**Comment by cuavas** [comment]
Please use forums to ask questions.  That isn’t what issue trackers are for.
