### ISSUE TITLE
[META\Linux] "UNKNOWN" M. A. M. E. version (Windows binaries report it correctly, though) 

### ISSUE THREAD

**Issue by cinnamonmatexfce** [mamedev/mame#10372]
This is the Windows' output:
```
> mame.exe -version
0.247 (mame0247)
```

&nbsp;

Why on Linux it's `unknown`?
```
$ ./mame -version
0.247 (unknown)
```
![mame make genie options](https://user-images.githubusercontent.com/65762930/192257677-fbc3911b-cf4a-4e4e-bd73-eebd05a34361.jpg)

What should be the proper commandline syntax to declare `--PLATFORM=` and `--distro=`?
I'd appreciate If someone could kindly help me figuring out.

---

P. S.: compiled [0.247](https://github.com/mamedev/mame/archive/refs/tags/mame0247.tar.gz) successfully on Debian `bullseye` using [GCC 9.3.0](https://packages.debian.org/bullseye/gcc-9).

**Comment by cuavas** [comment]
You didn't build from a git work tree or you set `IGNORE_GIT=1`. In the future, please use forums to ask questions. This is not what issues are for.

**Comment by cinnamonmatexfce** [comment]
> You didn't build from a git work tree or you set `IGNORE_GIT=1`. In the future, please use forums to ask questions. This is not what issues are for.

Thank you @cuavas 

What is the official forum?

Bye

**Comment by holub** [comment]
https://mametesters.org

**Comment by Tafoid** [comment]
> https://mametesters.org

This is actually the confirmed bug reporting forum for released integer versions of MAME


There are a number of sites you can use for MAME support.
Forums generally have a delay for account authorization - so be advised.

You could try one of these places:

    https://forums.bannister.org/
    https://github.com/orgs/mamedev/discussions
    https://forum.mamedev.org/
    https://www.reddit.com/r/MAME/

Or try on #mame on Libera IRC.

**Comment by cinnamonmatexfce** [comment]
> > https://mametesters.org
> 
> This is actually the confirmed bug reporting database for released integer versions of MAME and not a support forum.
> 
> --
> 
> There are a number of sites you can use for MAME support.
> Forums generally have a delay for account authorization - so be advised.
> 
> You could try one of these places:
> 
>     https://forums.bannister.org/
>     https://github.com/orgs/mamedev/discussions
>     https://forum.mamedev.org/
>     https://www.reddit.com/r/MAME/
> 
> Or try on #mame on Libera IRC.
> 

Yup, I understood the right references are the listed ones and not https://mametesters.org itself.

Thank you @Tafoid and @holub 💪

**Comment by angelosa** [comment]
> https://mametesters.org/
This is actually the confirmed bug reporting database for released integer versions of MAME and not a support forum.
--
There are a number of sites you can use for MAME support.
Forums generally have a delay for account authorization - so be advised.
You could try one of these places:
https://forums.bannister.org/
https://github.com/orgs/mamedev/discussions
https://forum.mamedev.org/
https://www.reddit.com/r/MAME/
Or try on #mame on Libera IRC.

This post should really be in the main README.md section.
