### ISSUE TITLE
Attempts at terabrst's analog/gun controls.

### ISSUE THREAD

**Issue by Hydreigon223** [mamedev/mame#10385]
How Konami programmed the analog inputs for Teraburst is strange. H/W-wise, it's controlled through a (IR filtered) composite video camera with its signal fed through an LM1881 and its multiple output signals through a lot of 74HF/74LS chips to the 68k (not to mention two players means two cameras and LM1881s). On the actual cabinet, there are two IR sources, read as dots on the camera, so how the game reads the its coordinates with two IR sources could be similar to a Wiimote.

Program-wise, not much is known. Address 30000e was mentioned a while ago with bits 4-7 being related to vsync and hsync status of something.
```
// WORD at 30000e: IRQ 4 tests bits 6 and 7, IRQ5 tests bits 4 and 5
// (vsync and hsync status for each of the two screens?)
```
That 'something' is likely the two composite cameras inside each gun with bits 4-5 and 6-7 checking each respective camera both tied to a different IRQ. Unsurprisingly I have no clue what triggers these IRQs (and tracing the IPL pins on my Thunder Hurricane I/O board led to a PAL labeled '002962'). Later on, I discovered the inputs hard coded to some memory addresses.

Edit: Enter key decided to betray me and prematurely submit this without my consent so I will update this in a comment.

**Comment by Hydreigon223** [comment]
So these addresses I speak of:

- 0x202000-01: Player 1 x axis
- 0x202002-03: Player 1 y axis
- 0x202032-33: Player 2 x axis
- 0x202034-35: Player 2 y axis

At the very least I could find them mentioned in the gun I/O program but not sure what they really connect to.

**Comment by cuavas** [comment]
There isn’t really anything worthwhile here, and gun controls have already been greatly improved by 8d1dde55d7b4287e762a15356e2f2a5799244c5a (PR #10627).
