### ISSUE TITLE
GCC 12.2.0 compile error

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#10399]
I have tried to compile a 32bit MAME version with msys64-2022-01-12.exe updated to GCC 12.2.0.
And the only file that i cannot compile is src/mame/misc/astrcorp.cpp.
Get this error:

-----
Compiling src/mame/misc/astrcorp.cpp...
Archiving libformats.a...
In file included from D:/1/msys64/mingw32/include/c++/12.2.0/list:60,
                 from ../../../../../src/emu/emu.h:24,
                 from ../../../../../src/mame/misc/astrcorp.cpp:62:
In static member function 'static _Tp* std::__copy_move<_IsMove, true, std::random_access_iterator_tag>::__copy_m(const _Tp*, const _Tp*, _Tp*) [with _Tp = unsigned char; bool _IsMove = false]',
    inlined from '_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = unsigned char*; _OI = unsigned char*]' at D:/1/msys64/mingw32/include/c++/12.2.0/bits/stl_algobase.h:495:30,
    inlined from '_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = false; _II = unsigned char*; _OI = unsigned char*]' at D:/1/msys64/mingw32/include/c++/12.2.0/bits/stl_algobase.h:522:42,
    inlined from '_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = unsigned char*; _OI = unsigned char*]' at D:/1/msys64/mingw32/include/c++/12.2.0/bits/stl_algobase.h:529:31,
    inlined from '_OI std::copy(_II, _II, _OI) [with _II = unsigned char*; _OI = unsigned char*]' at D:/1/msys64/mingw32/include/c++/12.2.0/bits/stl_algobase.h:620:7,
    inlined from '_OutputIterator std::__copy_n(_RandomAccessIterator, _Size, _OutputIterator, random_access_iterator_tag) [with _RandomAccessIterator = unsigned char*; _Size = unsigned int; _OutputIterator = unsigned char*]' at D:/1/msys64/mingw32/include/c++/12.2.0/bits/stl_algo.h:728:23,
    inlined from '_OIter std::copy_n(_IIter, _Size, _OIter) [with _IIter = unsigned char*; _Size = unsigned int; _OIter = unsigned char*]' at D:/1/msys64/mingw32/include/c++/12.2.0/bits/stl_algo.h:760:27,
    inlined from 'void {anonymous}::magibomb_state::init_magibomb()' at ../../../../../src/mame/misc/astrcorp.cpp:2119:13:
D:/1/msys64/mingw32/include/c++/12.2.0/bits/stl_algobase.h:431:30: error: 'void* __builtin_memcpy(void*, const void*, unsigned int)' accessing 2147483649 or more bytes at offsets 0 and 0 overlaps 2147483651 bytes at offset -2 [-Werror=restrict]
  431 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
make[2]: *** [misc.make:2476: ../../../../mingw-gcc/obj/x32/Release/src/mame/misc/astrcorp.o] Error 1
make[1]: *** [Makefile:277: misc] Error 2
make: *** [makefile:1140: windows_x86] Error 2
-----

The compiler don't like this line (2119 in src/mame/misc/astrcorp.cpp):
std::copy_n(rom, size, &tmp[0]);

**Comment by cuavas** [comment]
Suppress the warning or report it to the GCC maintainers.  We’ve had issues with spurious warnings about out-of-bounds accesses in the past on 32-bit x86 GCC builds.  In particular, GCC 7 suffers from these issues: https://docs.mamedev.org/initialsetup/compilingmame.html#issues-with-specific-compiler-versions
