### ISSUE TITLE
Bank Panic - info about the "out" IO register.

### ISSUE THREAD

**Issue by pcornier** [mamedev/mame#10395]
The bit 2 of the "out" register is used to turn the display on/off during screen transitions. It controls the clear signal of the final color register.

The bit 3 of the "out" register is used as the high bit (bit 4) of the color address. The game can switch between palette one and two by modifying this bit. It seems to happen only at the end of the first door scrolling on level 3. The only difference between the two palettes is color 7 (2F/40)
.

**Comment by happppp** [comment]
I see, so it has day and night levels (the latter uses the other palette).
Thanks for pointing it out, the fix is in this commit: https://github.com/mamedev/mame/commit/77f4f7b7d77a650156846a040e452fa099a9a9cc
