### ISSUE TITLE
[Linux] 8BitDo Arcade Stick doesn't work

### ISSUE THREAD

**Issue by cmalvi** [mamedev/mame#10405]
OS: ArchLinux

It only works partially if launched from steam (without P1 and P2 functionality), but doesn't work using alone or with a frontend 

Also, if the controller is set in "Switch mode" (Dinput I think), mame crash on launch

**Comment by cuavas** [comment]
If it doesn’t work with current master with the `sdlgame` module, it’s either an issue with SDL or with the drivers.  As of 68472d3d72ea4bbc545c0669348172b4e96c7b41, MAME’s input modules are quite a bit more solid than they were in the past.
