### ISSUE TITLE
game and watch minimun resolution very high 

### ISSUE THREAD

**Issue by MistyDreams** [mamedev/mame#10411]
Here is a list of the 3 games to see ones without artwork and the other is with artwork.

```
gnw_ball   1671 x 1080, 5689 x 3196
gnw_bjack   960 x 1333, 3482 x 2631
gnw_dkjrp  1920 x 1049, 7472 x 5978  
```
Without artwork runs fine, with it you will crawl. if using software. I image thats a big by load any standards. Is this a know issue?

https://github.com/mamedev/mame/blob/fecf31406e79432245ce4d040f8e67da60391bc6/src/emu/render.cpp#L1311-L1372

**Comment by happppp** [comment]
It's high res to keep the SVG shapes unpixelated. A lot of drivers with SVG 'screens' have righ resolution.
Ideally MAME should scale the SVG to the host window size instead of relying on the MAME screen device.

**Comment by happppp** [comment]
You mean the restriction on resizing the OS window?
For Windows, I reduced that limitation:
https://github.com/mamedev/mame/commit/e508e8a3f9dc258b411d78703897a117213c5c0f
part2: https://github.com/mamedev/mame/commit/057458b168346b4d80a588ad278e650577def079

**Comment by happppp** [comment]
Ok, so it looks like the same limitation I worked on in those linked commits in my prev message, right?
If I had a Linux PC I would have changed it the same day I did on Windows.
