### ISSUE TITLE
Build failure on kFreeBSD

### ISSUE THREAD

**Issue by jmallach** [mamedev/mame#1044]
Hello,

While building 0.175 on kFreeBSD, I encounter the following:

    Compiling 3rdparty/bgfx/3rdparty/ocornut-imgui/imgui_draw.cpp...
    ../../../../../3rdparty/bgfx/3rdparty/ocornut-imgui/imgui_draw.cpp: In member function 'void ImDrawList::AddPolyline(const ImVec2*, int, ImU32, bool, float, bool)':
    ../../../../../3rdparty/bgfx/3rdparty/ocornut-imgui/imgui_draw.cpp:439:100: error: 'alloca' was not declared in this scope
     ormals = (ImVec2*)alloca(points_count * (thick_line ? 5 : 3) * sizeof(ImVec2));
                                                                                  ^
    ../../../../../3rdparty/bgfx/3rdparty/ocornut-imgui/imgui_draw.cpp: In member function 'void ImDrawList::AddConvexPolyFilled(const ImVec2*, int, ImU32, bool)':
    ../../../../../3rdparty/bgfx/3rdparty/ocornut-imgui/imgui_draw.cpp:620:77: error: 'alloca' was not declared in this scope
             ImVec2* temp_normals = (ImVec2*)alloca(points_count * sizeof(ImVec2));

**Comment by ajrhacker** [comment]
Is a1f9b62dd0a491d6b26291837d43181c0e9e66fa enough to fix this?

**Comment by jmallach** [comment]
Sorry, I didn't realise I commented on the actual commit, not issue. No, this commit does not fix it.

**Comment by coderbounty-cowboy** [comment]
Coderbounty posted: http://coderbounty.com/issue/68

**Comment by h0tw1r3** [comment]
What version of kFreeBSD?

**Comment by h0tw1r3** [comment]
Following up. I was able to build mame HEAD on jessie-kFreeBSD with a number small build patches, mostly to `uv`.

**Comment by jmallach** [comment]
With the fixes from #1093, and using system libuv, yes, the build succeeds, as can be seen here: https://buildd.debian.org/status/fetch.php?pkg=mame&arch=kfreebsd-amd64&ver=0.176-2&stamp=1469694187

This bug should have been closed a week ago.

**Comment by jmallach** [comment]
These are Debian's libuv portability patches: https://sources.debian.net/src/libuv/0.10.36-3/debian/patches/ . It might be a good idea to merge a good part of these into 3rdparty.

**Comment by stilett0** [comment]
so who wins the $20? :smiley: (man, that was totally random...)

**Comment by h0tw1r3** [comment]
@jmallach @mmicko UV upstream PR for proper GNU/kFreeBSD support https://github.com/libuv/libuv/pull/959

**Comment by jmallach** [comment]
TBH, if anyone deserves these $20, it's @stevenc99. But how on earth did these $20 appear out of nowhere?
