### ISSUE TITLE
Actua Soccer Tournament ArcadePC

### ISSUE THREAD

**Issue by mjhardisty** [mamedev/mame#10466]
Hello, I have an ArcadePC that runs Actua Soccer Arcade Tournament Edition - similar hardware to the Quake machine that was cracked recently to allow it to run. The Actua Soccer machine uses a similar dongle. I've posted many times to the author of the crack but to no avail - would anyone be interested in taking on the project to look at the code and remove the protection?

**Comment by ICEknigh7** [comment]
Hello, this is for MAME issues.

**Comment by DavidHaywood** [comment]
While I don't know if anybody will look into it, having a proper unmodified image of the HDD for future emulation purposes is kind of important.

If you have a proper HDD image from the system (as in a proper drive image, not just all the files zipped up) then you should contact the team using the form on https://www.mamedev.org/contact.html at the very least, to ensure that image is safe for the future.

I'm seeing a worrying trend lately where for PC based games only the already hacked/deprotected versions are being archived / distributed.

**Comment by angelosa** [comment]
Addendum: should make sure that all the chipset matches what we have in quakeat.cpp
https://github.com/mamedev/mame/blob/9d6064fdceba15ae896e295271d037269b014897/src/mame/pc/quakeat.cpp#L41

This is very important, to cite myself:
> MAME emulates a PC at root, so any dump should pass thru the BIOS routines then the kernel then finally the actual boot routines
You can try to bypass A and B by booting MAME with any of the Pentium class PC machines such as shutms11 with the HDD dump, but again without the real chipset they **_will_** hang in one place or another

**Comment by mjhardisty** [comment]
Ive used the contact form.

**Comment by Hydreigon223** [comment]
I may suggest renaming the driver from quakeat.cpp to quckslvr.cpp because of the base computer being the same.

**Comment by angelosa** [comment]
Absolutely no. 
Unless you have a better name that fits "Quantum3D Heavy Metal HM233G (part of Quantum3D's Quicksilver family)", and quckslvr.cpp (sic) definitely isn't. 
Also we don't have any of these emulated and nobody really analyzed what this is all about so quakeat.cpp stands. And by "analyzing" I mean checking out what went retail, what is actually dumped BIOS wise, hooking up said BIOS to the driver etcetera etcetera etcetera.

**Comment by angelosa** [comment]
> Ive used the contact form.

You didn't used it properly. If you want this to be emulated use the contact form to actually _send a dump of the hard drive and (if you can) of the BIOS_, then eventually somebody will jump on the train about parallel port dongle details.

As it stands this issue is about a dump that isn't even in MAME, closing.
