### ISSUE TITLE
failed retrieving file 'mame.db.sig' from repo.mamedev.org

### ISSUE THREAD

**Issue by firewave** [mamedev/mame#10487]
I installed the `mame-essentials` as outlined under and this results in the following errors when running `pacman -Syu`:

```
error: failed retrieving file 'mame.db.sig' from repo.mamedev.org : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
```

**Comment by firewave** [comment]
The same.

**Comment by firewave** [comment]
```
$ cat /etc/pacman.conf | grep SigLevel
#SigLevel = Never
SigLevel    = Required
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required
# SigLevel = Never
#SigLevel = Optional TrustAll
```

If that is necessary it should be put into the documentation.

Although I feel that if reducing the security of the system is really bad. MSYS2 is probably a extremely low-risk attack vector but still...

**Comment by Robbbert** [comment]
My pacman.conf

#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
HoldPkg      = pacman
#XferCommand = /usr/bin/curl -C - -f %u > %o
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

NoUpgrade   = /etc/pacman.conf
#NoExtract   =

# Misc options
#UseSyslog
#Color
#TotalDownload
CheckSpace
#VerbosePkgLists

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel = Never
#SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

[mingw32]
Include = /etc/pacman.d/mirrorlist.mingw32

[mingw64]
Include = /etc/pacman.d/mirrorlist.mingw64

[msys]
Include = /etc/pacman.d/mirrorlist.msys

[mame]
Include = /etc/pacman.d/mirrorlist.mame

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs


This is the important part of my batch file for updating:
pacman -Sy
pacman -S bash pacman msys2-runtime --noconfirm --needed
pacman -Su --noconfirm
pacman -Syuu --noconfirm

**Comment by firewave** [comment]
I followed https://docs.mamedev.org/initialsetup/compilingmame.html#using-a-standard-msys2-installation. I forgot to mention that in the report. Sorry about that.

**Comment by MooglyGuy** [comment]
Thanks for the clarification. Based on the last-changed file dates (2016), it looks like the mame-essentials repo hasn't been updated in 6 years, and that entire section should probably be stripped from the documentation in favor of directing people towards a side-by-side install of the packaged tools available here: https://www.mamedev.org/tools/

@cuavas As Firehawke is no longer available to maintain the documentation, would it be possible for a team member to find the time to either update that repo, or delete that section from the docs?

**Comment by cuavas** [comment]
I’ll check the instructions for adding the MAMEdev repo.  I probably didn’t update it after pacman’s defaults changed.

**Comment by cuavas** [comment]
OK, we have three versions of the mame-essentials package in source control:
* https://github.com/mamedev/buildtools/tree/master/mame-essentials (1.0-0 x86_64)
* https://github.com/mamedev/MAME-packages/tree/master/mame-essentials-i686 (1.0.0-1 i686)
* https://github.com/mamedev/MAME-packages/tree/master/mame-essentials-x86_64 (1.0.5-1 x86_64)

None of these actually match the latest 1.0.6-1 x86_64 package that’s currently served on https://repo.mamedev.org/

On top of that, I’m not quite sure how to update the server anyway.  For now, it’s probably easiest to just add `SigLevel = Never` to pacman.conf itself.  Instructions added in a858c508c9e92bfc243738163d1852df72a4f810.  You can just add the `SigLevel = Never` line below the `Include` line in your existing pacman.conf.

**Comment by firewave** [comment]
Ah, cool. You can set that per repo. That's very neat.

Thanks for updating the documentation.

**Comment by cuavas** [comment]
The updated documentation should be enough for now – as far as I can tell it will work.
