### ISSUE TITLE
galaxian.cpp: can't load fully in Github web interface

### ISSUE THREAD

**Issue by angelosa** [mamedev/mame#1049]
Tried with OS X 10.11 + Safari and Firefox browsers.
Anything below line 10941 isn't shown at all when viewing the file.

**Comment by Osso13** [comment]
is this still happening? On Windows 10 + latest Firefox it shows the full file.

**Comment by cuavas** [comment]
It’s not like it’s an issue with MAME anyway.  There are limits on all web-based version control browsing systems for performance and scalability reasons.  You can complain to GitHub, but it’s unlikely they’ll change the limits for us.
