### ISSUE TITLE
Express Raider - additional info

### ISSUE THREAD

**Issue by pcornier** [mamedev/mame#10521]
To answer this question:
```cpp
ROM_LOAD( "cy-14.9b", 0x0300, 0x0100, CRC(52aad300) SHA1(ff09772b930afa87e28d0628ef85a589a3d149c9) ) /* ??? */
```
This is a priority ROM (schematics DE-0221-1 page 9/15)

```text
    Priority ROM address:
    x....... = fg col bit 1 | fg col bit 0
    .x...... = bit 7 of tilerom attribute
    ..xxx... = bit 2-0 of sprite color
    .....xxx = bit 2-0 of bg color
```

Then value is
```text
    ......00: background
    ......01: sprite
    ......10: foreground
```

The same bits are also used to build the color address, bit 7 & 6.

About cz03.12d, this is actually 12F, 12D is a 74283 on board and schematics.

**Comment by happppp** [comment]
Thanks, gfx emulation matches this PROM. It's straightforward, no weirdness with the layer select according to PROM contents, so nothing needs changing there.
I changed "???" to "priority".
