### ISSUE TITLE
Path usage in .lay files - works in Windows but not Linux

### ISSUE THREAD

**Issue by RandyR99** [mamedev/mame#10567]
The following statement (inside custom artwork file _artsy.zip_, within the _artsy.lay_ file) works in MAME 0.249 in Windows:

`<image file="..\lights\RED6_SEL.png" state="1"/>`

where _lights.zip_ is also in the artwork folder. But does not work in Linux. It gives the following error:

`Unable to load component image '..\lights\RED6_SEL.png'`

Changing the backslashes to forward slashes did not solve it. The error just changes to:

`Unable to load component image '../lights/RED6_SEL'`

If I create a folder inside _artsy.zip_ called _lights_ and containing _RED6_SEL.png_, it works.

What is the correct method (path format) for referencing components in other zip files? It doesn't appear to be mentioned in the docs. And is the forward/backslash important or does MAME handle the difference.

Thanks.

Randy

**Comment by RandyR99** [comment]
Strangely enough, if I extract the artsy.zip file into a folder called artsy it works. Somehow the path is getting stripped off. Here is the verbose output when using the folder:

`unzip: opened archive file artwork/artsy/../lights.zip and sending to cache`

But when I turn artsy into an archive (artsy.zip or artsy.7z) I see:

`Unable to load component image '../lights/RED6_SEL'`

It's as if MAME 'forgets' where it is.

Randy

**Comment by RandyR99** [comment]
It's set to artwork.

**Comment by RandyR99** [comment]
I set it to:

`artpath                   $HOME/src/mame-mame0248/artwork`

Same result:

`Unable to load component image '../lights/RED6_SEL'`

**Comment by RandyR99** [comment]
Yes. It also fails in Linux (Manjaro) on another system with v0.249 actually installed (using the .mame folder for the files).

Thanks for your help @MistyDreams 

Randy

**Comment by cuavas** [comment]
It’s not supported – artwork is supposed to be self-contained.

**Comment by RandyR99** [comment]
But it works on Windows. Although I was just using an example (artsy.lay) the use case is for chessboard custom artwork running in Linux on a Raspberry Pi. It doesn't seem efficient to have images for 2D and 3D pieces, as well as LED lights and other shared images placed inside over 200 different zip files.

Would adding this support be difficult? I'm not a programmer.

Randy
