### ISSUE TITLE
[LUA ERROR] shows up when opening games with cheats on MAME 0.239

### ISSUE THREAD

**Issue by PichuBoy000** [mamedev/mame#10562]
Currently, when trying to use cheats, this message appears upon game bootup.

`[LUA ERROR] in execute_function: plugins/cheat_xml.lua:21: attempt to index a nil value (local 'str')`

The cheats do not work when this error pops up, and with following other issues trying to fix it, the same error seems to show up no matter what.

_NOTE: Just want to clear up that I'm currently on 0.239 to use the Konami Firebeat Hardware, as the newer versions crash the emulator, but I know they're planning to fix that at some point._

**Comment by MooglyGuy** [comment]
Is this with all of the 0.239 support files as well, or did you copy just the MAME 0.239 executable over top of the latest version?

**Comment by PichuBoy000** [comment]
I think this is the 0.239 install, ill try reinstalling the version and trying again just in case I messed something up.

**Comment by PichuBoy000** [comment]
Checking MAME again after a fresh install, it now works correctly, and I can use cheats now.
Thanks.
