### ISSUE TITLE
[MAME 0.249] bug: BGFX not working

### ISSUE THREAD

**Issue by tranzedude** [mamedev/mame#10577]
Hey

While I got BGFX working in older MAME versions, suddenly MAME doesn't enable BGFX anymore in MAME 0.249.

Steps to reproduce. I use this MAME build: https://github.com/mamedev/mame/releases/download/mame0249/mame0249b_64bit.exe
I edited the following values in a newly written mame.ini file using MAME 0.249 (leaving ALL other values to their defaults) in order to enable BGFX (as it always worked like this in older versions):

- in section OSD VIDEO OPTIONS:

Value for "video" changed to "bgfx"

- in section BGFX POST-PROCESSING OPTIONS:

Value for "bgfx_screen_chains" changed to "crt-geom"

Am I missing some values that have been changed in MAME 0.249 to enable BGFX? Because it doesn't work like this.
Also when using the tilde key allows me to cycle through all screen chains and when selecting my favorite "crt-geom" it's displayed as in the screenshot, which is not how  "crt-geom" looked in the past. There is not CRT-like effect at all as you can see in the screenshot. It just "pixelated" the screen in a very strong way, which is not what "crt-geom" was doing in older MAME versions.

![afbeelding](https://user-images.githubusercontent.com/118472172/203130827-05dd7297-03c0-44ce-b493-bd9747e3e7a6.png)

 In earlier MAME versions it didn't look at all like this.
Here is a screenshot of how it looked before. You can clearly see the CRT-like effect is applied here.

![test](https://user-images.githubusercontent.com/118472172/203131105-b2078b8c-823f-4b27-8a6a-a4a665ca11fc.png)

In addition, running MAME with -video bgfx in the command line doesn't help too.

I attached my mame.ini file (zipped).
Am I missing a value somewhere to enable BGFX, which is added in MAME 0.249 or is this a bug?

[mame.zip](https://github.com/mamedev/mame/files/10059555/mame.zip)

Tranzedude

**Comment by tranzedude** [comment]
For some weird reason, it works if you run MAME a second time with exactly the same mame.ini file :). 
Why could this be?

**Comment by cuavas** [comment]
I can’t reproduce this – cycling through effects works, including crt-geom.  I suggest you ask for help on a user forum.  Maybe try https://reddit.com/r/MAME/

**Comment by tranzedude** [comment]
- Do you have edited more values in the "OSD VIDEO OPTIONS" and "GFX POST-PROCESSING OPTIONS" then I did?

- How do you run MAME at the command line?

Can you give me the exact command line string you pass to MAME?

I move to a forum after your answer :)

**Comment by cuavas** [comment]
I simply ran `mame -video bgfx`.  The only settings in my mame.ini are `artpath`, `rompath`, `window`, `joystick_deadzone`, and `joystick_saturation`.

**Comment by tranzedude** [comment]
If you run MAME on the command line like this below, BGFX does not work. So please re-open this issue.
There is a big bug in MAME's command line parser which causes errors in BGFX as you can see below.

MAME Command Line string:

`mame asterix -rompath "F:\MAME ROMs\Roms";"F:\MAME ROMs\Software" -artpath "F:\MAME ROMs\Artwork" -samplepath "F:\MAME ROMs\Samples" -video bgfx`

MAME Standard Error output: 

`Unable to load PNG 'bgfx/chains/crt-geom/aperture_1_2_bgr.png' from path 'F:\MAME ROMs\Artwork'
Unable to load chain bgfx\chains\/crt-geom.json, falling back to no post processing
Unable to load PNG 'bgfx/chains/hq2x.png' from path 'F:\MAME ROMs\Artwork'
Unable to load chain bgfx\chains\/eagle/super-eagle.json, falling back to no post processing
Unable to load PNG 'bgfx/chains/crt-geom/aperture_2_4_rgb.png' from path 'F:\MAME ROMs\Artwork'
Unable to load chain bgfx\chains\/Fighters.json, falling back to no post processing
Unable to load PNG 'slot-mask.png' from path 'F:\MAME ROMs\Artwork'
Unable to load chain bgfx\chains\/hlsl.json, falling back to no post processing
Unable to load PNG 'bgfx/chains/crt-geom/aperture_2_4_rgb.png' from path 'F:\MAME ROMs\Artwork'
Unable to load chain bgfx\chains\/Fighters.json, falling back to no post processing
Unable to load PNG 'bgfx/chains/hq2x.png' from path 'F:\MAME ROMs\Artwork'
Unable to load chain bgfx\chains\/eagle/super-eagle.json, falling back to no post processing
Unable to load PNG 'bgfx/chains/crt-geom/aperture_1_2_bgr.png' from path 'F:\MAME ROMs\Artwork'
Unable to load chain bgfx\chains\/crt-geom.json, falling back to no post processing`

**Comment by tranzedude** [comment]
Why does MAME even try to read 'bgfx/chains/crt-geom/aperture_1_2_bgr.png' from my Artwork path?!?
It has nothing to do with the artwork path at all...

**Comment by tranzedude** [comment]
If you use following command line string WITHOUT an artpath specified, it works.

`mame asterix -rompath "F:\MAME ROMs\Roms";"F:\MAME ROMs\Software" -samplepath "F:\MAME ROMs\Samples" -video bgfx`

So there is a bug in the MAME command line parser which causes BGFX not to run because of errors (see below).
If you add a "-artpath" in the command line, for some reason MAME tries to load BGFX .PNG files in the artpath you specified in the command line which is clearly a bug.
If you remove the "-artpath", BGFX works again.

Thanks for reading
