### ISSUE TITLE
Multiple screens with different update frequencies bug.

### ISSUE THREAD

**Issue by Hydreigon223** [mamedev/mame#10597]
It's been known for years MAME's current core can't handle partial updates on multi-screen systems with different update frequencies. The only two 'multi-screen different frequency update' systems I can think of are Race Drivin' Panorama and Silent Scope; the former having an 'ugly hack' installed to force the three screens to stay in sync and the latter having busted timings due to the side effect of both screens running at different update frequencies.

I don't know there's an approachable solution in the works to fix this right now.

**Comment by cuavas** [comment]
Please don’t open useless issues when you have nothing to contribute.  Besides, you can easily get different combinations of screens in computer drivers by installing multiple video cards and setting different monitor types, or with serial terminals on any systems that have different system screen refresh rates to MAME’s 50Hz HLE terminal.
