### ISSUE TITLE
RetroAchievements support

### ISSUE THREAD

**Issue by TheFetishMachine** [mamedev/mame#10590]
RetroAchievements is a website that lets you earn achievements for a variety of platforms (mostly retro consoles and computers) by hooking into emulators and using the memory exposed to make achievements that trigger whenever needed. I think it's a pretty cool service and I think addition into MAME could be worthwhile. PCSX2 and Duckstation have recently added support and Bizhawk support is being tested currently. Here is a link to the [RetroArch website](https://retroachievements.org/).

Here are the two relevant github links for [RAIntegration](https://github.com/RetroAchievements/RAIntegration) and [rcheevos](https://github.com/RetroAchievements/rcheevos)

While RAIntegration is windows only it is only meant for achievement developers; rcheevos is multiplatform and is meant for runtime/casual support.

**Comment by happppp** [comment]
Seems you asked at the wrong place, try here:
https://github.com/libretro/mame/issues

**Comment by startaq** [comment]
Maybe it could be done with a LUA plugin, but it's not something that would be officially supported.

**Comment by TheFetishMachine** [comment]
> Seems you asked at the wrong place, try here: https://github.com/libretro/mame/issues

Thanks for the redirection! Though, for the record, RetroAchievements is not limited to RetroArch/Libretro support; PCSX2 and Duckstation support is on their standalones, for example.

**Comment by angelosa** [comment]
I find hard to believe that PCSX2 does it inside the emulator given it's plugin driven by definition.

**Comment by cuavas** [comment]
We aren’t interested in developing or maintaining it ourselves, and it wouldn’t be accepted as a core feature.  You can implement it as a Lua plugin if you like.

**Comment by TheFetishMachine** [comment]
> We aren’t interested in developing or maintaining it ourselves, and it wouldn’t be accepted as a core feature. You can implement it as a Lua plugin if you like.

I understand, it is fair, and thank you for the reply.
