### ISSUE TITLE
Deleting save states does not work when path contains environment variable references

### ISSUE THREAD

**Issue by j8r** [mamedev/mame#10593]
After saving a state with F7 + left shift, then with F7 (or F7 + left shift), trying to delete the save prompts a confirmation box which says to press RETURN (which is Enter) to confirm the deletion.

After pressing Enter, the box disappears but the save is still there. Indeed, after exiting the game it is still present in `~/.mame/sta` and from the F7 save states UI. 

I use the latest MAME 0.249 on Debian.

Related pull request: https://github.com/mamedev/mame/pull/8211

**Comment by cuavas** [comment]
I tested this with a recent build on Windows and it worked fine.
* Did you build MAME yourself or did you get a binary from somewhere?
* If you built MAME yourself, what options did you use?
* What’s your save state folder setting (`state_directory`)?

Can other people with Linux and/or macOS reproduce this?

**Comment by cuavas** [comment]
Also, if removing the file fails, MAME should give a popup message at the bottom of the screen indicating that there was an error, and print an error message (goes to standard error by default).

**Comment by cd4053** [comment]
From my Debian, mame deletes the state file (`whatever.sta`), however, it doesn't delete the respective game/romname folder.
If you start `mame sf2` and save a state, mame create `sta\sf2\q.sta`, after you delete the state from UI, mame left an empty `sta\sf2` folder.

**Comment by cuavas** [comment]
> From my Debian, mame deletes the state file (`whatever.sta`), however, it doesn't delete the respective game/romname folder.
> If you start `mame sf2` and save a state, mame create `sta\sf2\q.sta`, after you delete the state from UI, mame left an empty `sta\sf2` folder.

That's expected behaviour. Thanks for confirming.

**Comment by j8r** [comment]
On my side, the directory still exists along with the file. I tried with an empty `~/.mame` and a `~/.mame` which has the files created by `mame -createconfig`.
I also tried with Wayland and X11.
It is like pressing enter cancels instead of validating, I didn't mistake Esc and RETURN.

**Comment by cuavas** [comment]
You haven’t answered the questions.

**Comment by j8r** [comment]
I use the MAME package from Debian, `0.249+dfsg.1-1`, and as implied by my above comment, the default directories are used, which is `$HOME/.mame/sta`.

**Comment by cuavas** [comment]
Well, if it’s working for @cd4053 with MAME built from unmodified source, and it’s not working for you with a Debian package, that suggests it’s an issue with Debian modifications.

**Comment by cuavas** [comment]
Gah, actually, that’s possibly not it.  It’s likely that it’s not substituting environment variables when it tries to delete the file.  See #9859.  What if you put a path with no environment variable references in it?

**Comment by j8r** [comment]
It works, good catch! :grinning:

**Comment by j8r** [comment]
Thanks a lot, the easy workaround for now is then `sed "s|state_directory .*|state_directory           $HOME/.mame/sta|" mame.ini ~/.mame/mame.ini`.

**Comment by j8r** [comment]
Thanks a lot, the easy workaround for now is then `sed -i "s|state_directory .*|state_directory $HOME/.mame/sta|" ~/.mame/mame.ini`.

**Comment by cuavas** [comment]
Fixed by #9859 (13910382a5e846677f30d1645bfb44e4983de557).
