### ISSUE TITLE
Ridge Racer, priority issue? [namcos22]

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#10603]
Version: `0.249 (mame0249-319-gcd499b33839)`
OS: Linux
![0001](https://user-images.githubusercontent.com/80734530/204083492-a05600d1-060e-419e-8876-6e6c7f7e270c.png)

**Comment by happppp** [comment]
Nope not a bug.
When uncertain, please check youtube and such for pcb footage before posting. Also, IMO https://mametesters.org/view_all_bug_page.php is a better place for these kind of driver bug reports.
