### ISSUE TITLE
pause and config menu bound to the same button broken

### ISSUE THREAD

**Issue by fartboygh** [mamedev/mame#10606]
If the functions 'pause' and 'config menu' are bound to the same button, the first time you press it, it won't pause.

**Comment by fartboygh** [comment]
Still not fixed as of 0.251

**Comment by cuavas** [comment]
Sorry, this isn’t intended to work.  If you try doing stuff like this, you can keep the pieces when it breaks.

**Comment by fartboygh** [comment]
I'm sorry but that response doesn't exactly make sense. Why wouldn't binding two functions to one button just not work? Is it hard coded on purpose?

**Comment by angelosa** [comment]
Making silly changes to the configuration is bound to throw uncomfortable results, and there's no real solution other than just expecting user to either fill the general input responsibly, or at worst, go to the `default.cfg `and delete it to restore.

**Comment by fartboygh** [comment]
What's silly about it? Other emulators pause the emulation and pop up the menu just fine.

**Comment by ICEknigh7** [comment]
> What's silly about it? Other emulators pause the emulation and pop up the menu just fine.
To be fair... yeah, it doesn't sound like a too crazy idea to have the emulator pause when opening the menu.

**Comment by cuavas** [comment]
> > What's silly about it? Other emulators pause the emulation and pop up the menu just fine.
> 
> To be fair... yeah, it doesn't sound like a too crazy idea to have the emulator pause when opening the menu.

See what you’re asking for is something different.  You want a feature that makes emulation pause automatically whenever a menu is displayed.  That’s not the same thing as asking for MAME to respond to multiple conflicting UI inputs simultaneously.

**Comment by fartboygh** [comment]
How are they conflicting?

**Comment by cuavas** [comment]
> How are they conflicting?

You're trying to use the same button (or combination of buttons) for multiple UI actions. That's conflicting by definition.

**Comment by fartboygh** [comment]
Seems like you arbitrarily decided that. There's no logic behind it.

**Comment by angelosa** [comment]
https://ux.stackexchange.com/questions/63280/one-button-for-two-actions

> You buttons should always say what they do. Avoid vague terms and, most especially, **do not confuse the user by having a single button do two things!** Also, giving the user two text fields can cause issue - if I only type something into the second box, what happens?

ABC of UX ...
