### ISSUE TITLE
Bubble Bobble console errors

### ISSUE THREAD

**Issue by Tasosgemah** [mamedev/mame#10613]
When i run Bubble Bobble with the console visible, i get these errors

pal16l8.bin NOT FOUND (NO GOOD DUMP KNOWN) (tried in bublbobl)
pal16l8.bin NOT FOUND (NO GOOD DUMP KNOWN) (tried in bublbobl)
pal16r4.bin NOT FOUND (NO GOOD DUMP KNOWN) (tried in bublbobl)
WARNING: the machine might not run correctly.

Is this normal?

**Comment by cuavas** [comment]
Yes, there are no known dumps of those chips, which is a problem for people maintaining these boards if those chips fall.

In the future, use forums to ask questions. Don't clutter issue trackers.
