### ISSUE TITLE
Handheld game - Casio Castle adventure - CG-131 (1988)

### ISSUE THREAD

**Issue by Torinde** [mamedev/mame#10646]
[Here](http://pica-pic.com) is a collection of 26 handheld electronic games. Some of them are supported by MAME. At least one apparently [isn't](http://adb.arcadeitalia.net/default.php): [Casio Castle adventure](http://pica-pic.com/castle_adventure/), CG-131, 1988.

The website has playable Flash versions of all the games.

**Comment by happppp** [comment]
I'm approx 100% certain these are simulators, not emulators (correct me if I'm wrong).
So even if this was open source, it's not relevant to MAME.

**Comment by einstein95** [comment]
Yes, all the games on the site are Flash-made simulations of LCD games

**Comment by Torinde** [comment]
OK. Games are also present in Flashpoint.
