### ISSUE TITLE
technos combatrives new rom set ?

### ISSUE THREAD

**Issue by Franck78** [mamedev/mame#10657]
@aaronsgiles 

(sorry to ping you Aaaron)

I think I have an unknown ROM set. He is why

Background have problems on a real board

To determine what kind of board I have, I start by dumping why I can, eg socketed ROMS EPROMS

17 ROMS, 4 soldered not dumped

the 4 ROMs are 28J4,28J5,28J6,28J7

The 13 remaining chips are

4 ROMs (28J0,28J1,28J2,28J3) identified correctly identical to the 4 soldered.

This leave me with 9 EPROMS

28A17 is identified

all other are unkown (using arcadeFraidi as identification tool)

I burnt a full set of eprom with known images. The board runs identical and my background bug tile is still present.

So I think I have a valid new set. 

What di I do with it ? Someone interested ?

Franck

Board is TA-0028-P1-22

**Comment by happppp** [comment]
Hi, see here:
https://wiki.mamedev.org/index.php?title=Submitting_Source_Code
