### ISSUE TITLE
An IMPORTANT LEGAL ISSUE ****DO NOT CLOSE****

### ISSUE THREAD

**Issue by GrahamNoble23** [mamedev/mame#10662]
You are wrong. One of your members has stolen from me.
https://github.com/mamedev/mame/issues/10661

Your member is still active and making new Pull Requests. They are not gone.
Toaplan DT7 is from my game board and it is my property.

**Comment by happppp** [comment]
Nice troll attempt.
I have good news, the DT7 in that PR is not the watermarked one from 'you'.

**Comment by rb6502** [comment]
Owning a copy of a game gives you zero rights to the game.  Otherwise tens of millions of people would own Super Mario.

**Comment by cuavas** [comment]
> Your member is still active and making new Pull Requests. They are not gone.

The whole point of pull requests is that people outside the team can open them.
