### ISSUE TITLE
A Legal Issue IMPORTANT

### ISSUE THREAD

**Issue by GrahamNoble23** [mamedev/mame#10661]
To whom it may concern.

I am requesting assistance in amicably resolving a legal dispute pertaining to the unauthorized duplication and distribution of my personal property.

It has been brought to my attention the following web address herein “The Pull Request“ 
https://github.com/mamedev/mame/pull/10375
and the cosponsoring video evidencing “The Pull Request“ 
https://www.youtube.com/watch?v=7Zo-wJjwuUw 

It is my belief that what I will herein refer to as “The Game“ Toaplan’s Dynamic Trail 7 was fraudulently obtained from ones person and has been handled by one of your members “DavidHaywood“ without my permission.

A little background is necessary.

I have been the proud owner of the arcade machine housing “The Game“ in addition to a number of further machines for a period no less than twenty years after purchasing “The Game“ from a local operator. I kept meticulous backups of the EPROM devices storing the data for my games. The backups will be herein known as “my property“

An act of suspected arson at my residence in August of 2020 resulted in the loss of these machines, including “The Game“

My backup data for “The Game“ had been securely stored off-site and in the hands of close personal associates so “my property“ was not affected by the arson attack only the cabinets and game boards were lost.

After inquiring locally I was led to believe that it would be possible to recreate the destroyed machine using the emulation of RetroArch and so commissioned a software developer to produce the requisite emulation. The terms of the contract made clear that “my property“ was not to be duplicated or further distributed nor was it permitted to use any other emulator nor the details of the coding to be published.

To bind the contract and protect “my property“ an eight character signature was placed in each of the binary files unbeknownst to the contractor. The signature in question was formed of the letters TT followed by the bank account number provided by the contractor. Herein “the signature“

The contractor failed to deliver on the contract after taking payment and I now believe they have defrauded me and furthermore distributed “my property“ without permission.

Referencing “The Pull Request“ the term “obviously watermarked“ was used. It is upon this turn of phrase I stack my case for the EPROM data obtained by yourselves to be an unauthorized duplication of “my property“. I ask here that “DavidHaywood“ provide confirmation that the “obviously watermarked“ content was “the signature“ placed prior by oneself in each binary.

I also request from yourselves full contact information for “DavidHaywood“ in order to forward legal proceedings. I wish to resolve this amicably so an out of court settlement over the unauthorized handling of “my property“ is my preference if compliance is met in a timely way.

Furthermore I ask that all copies of this data and emulation code you may have obtained are deleted with immediate effect.

Thank You for your time.  Sincerely Graham

**Comment by cuavas** [comment]
Merely owning a copy of a piece of software does not grant intellectual property rights.  The current copyright holder of the Toaplan intellectual property, including DT7, is Tatsujin, trading as Toaplan.  By stating that you provided a developer with a watermarked copy of the ROM data, you are admitting to distributing an unauthorised derivative work.

David Haywood is not a member of this project, and has not been for a number is years.
