### ISSUE TITLE
ioport access from lua

### ISSUE THREAD

**Issue by shattered** [mamedev/mame#1067]
https://github.com/mamedev/mame/commit/d705e4a28d49b9eeeadc9c019a12cf580ae5ee8f breaks ioport access from lua, f.e. the sample in http://www.mamecheat.co.uk/forums/viewtopic.php?f=2&t=12245 no longer works.   Simpler test case:

for k, entry in pairs(manager:machine():ioport().ports) do print(string.format("%s:\n\t%s", k, entry:read())) end

After the change,  "[LUA ERROR] credit_find.lua:1: attempt to index a userdata value (local 'entry')" is reported.

**Comment by cracyc** [comment]
Should be fixed.
