### ISSUE TITLE
`-sixaxis` option purpose?

### ISSUE THREAD

**Issue by j8r** [mamedev/mame#10688]
It is unclear what the `-sixaxis` option does from the description "`use special handling for PS3 Sixaxis controllers` ".
I've a Sixaxis, but what this "special handling" changes?

I was still unclear for me by looking to the [the code](https://github.com/mamedev/mame/blob/master/src/osd/modules/input/input_sdl.cpp) at `sdl_sixaxis_joystick_device`.

**Comment by rb6502** [comment]
For the analog sticks, it scales the axis value read.  For all other analog axes it offsets the values to make them map to MAME conventions better (this avoids some trouble with the analog triggers, for instance).

**Comment by j8r** [comment]
Thanks for the clarifications! After testing, it indeed changes the behavior of analog triggers. Without the option, the pressure seems to be taken into account when registering a an input for instance, which adds things like `JOYCODE_1_RZAXIS_POS_SWITCH`.

However, I think the name -and the description - can be confusing. Sixaxis was the name of the first PS3 controller, which has been replaced by the DualShock 3 a year later (which I have).
Plus, `-sixaxis` may be relevant for PS4/PS5 controllers too, which have also analog triggers.

**Comment by cuavas** [comment]
The purpose of the option is to convert button displacement to digital “pressed” or “not pressed” values when using Sixaxis controllers.  What it does or doesn’t do to other controllers is not the point.  If you want to improve the description, open a pull request against the [relevant documentation page](https://docs.mamedev.org/commandline/sdlconfig.html).  Issue trackers are for reporting bugs, not asking general questions.
