### ISSUE TITLE
Request to add the extension of pc8801:HMB-20

### ISSUE THREAD

**Issue by denjhang** [mamedev/mame#10703]
http://mydocuments.g2.xrea.com/html/p8/nrtdrv88.html
This sound card is actually ym2151 x2 + ay8910 (ym2149)
A sound driver called NRTDRV is currently using this sound card to produce music.

It looks like this hardware is different from the JMB-X1, I know I reported this issue before.
https://github.com/mamedev/mame/issues/8709

**Comment by angelosa** [comment]
Not sure I'm following: in what exactly this is different than JMB-X1?

**Comment by denjhang** [comment]
I can't find any information about the HMB-20 hardware. It's just that the author wrote on his page that JMB-X1 must use NRTDRV88J to play music, and NRTDRV for PC-8801 is a dedicated driver for HMB-20.
The specific differences can only be explored from the source code of the two drivers. The good news is that the source code for both drivers is available for download.

**Comment by denjhang** [comment]
[nrtdrv88_20211208.zip](https://github.com/mamedev/mame/files/10256713/nrtdrv88_20211208.zip)
[NRTDRV88J_r1.00.zip](https://github.com/mamedev/mame/files/10256719/NRTDRV88J_r1.00.zip)

**Comment by denjhang** [comment]
I found that HMB-20 driver is not suitable for JMB-X1. When using JMB-X1 to run HMB-20 driver, there is only PSG sound, which means there is a difference between the two.

**Comment by angelosa** [comment]
Ah ok, I see. It's a single OPM attached to 0x88-0x89, while whatever they call "PSG" just comes from the internally installed Sound Board 1/2. This is trivial to implement.

**Comment by angelosa** [comment]
https://github.com/mamedev/mame/commit/f0fb9723c920e88fd3f43999a4fcdac9d258b905 should deal with it, you can hear the implementation at https://www.youtube.com/watch?v=Ll1lJtpN7rE
