### ISSUE TITLE
[Nitpick] Konami DJ MAIN is appended from Konami GX, But Why GX Is CPU Hog While DJMAIN is Not?

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [mamedev/mame#10722]
There's a possible way why Konami GX is CPU Hog:
1. Trying to Support a Variety of Games
2. Heavy Processor Load (like an overclocked CPU or GPU (graphic processor))

I don't know why Konami GX is CPU Hog, but the CPU Load is >200~1200% Difference.
Even with BIOS Screen Error (can speed up to 600% on my computer), Why Pop'n Stage (can speed up over 1200% (unleashed) on my computer) Is Not taking much?

**Comment by happppp** [comment]
2: kind of, it's the sound DSP (TMS57002).
Perhaps there are places where it can be optimized, but so can everything else in MAME. Not worth a github issue report.

**Comment by rb6502** [comment]
GX has 3 strong processors (68020, 68000, TMS57002).  DJMain has 1.  DJMain also has much weaker sprites.

**Comment by cuavas** [comment]
@TRRESTGHGYTCFTGBCXSZD issue tracker are not for asking questions or vague complaints.  If you continue to do this you will be blocked from the project.
