### ISSUE TITLE
devices/cpu/mcs48: Timing of UPI's IN and OUT opcodes

### ISSUE THREAD

**Issue by devsaurus** [mamedev/mame#10749]
## Observation

The `IN A, DBB` and `OUT DBB, A` opcodes are modeled to consume 2 cycles each.

https://github.com/mamedev/mame/blob/2d893a60b4675359285737be173dfa632269cab3/src/devices/cpu/mcs48/mcs48.cpp#L710-L712
https://github.com/mamedev/mame/blob/2d893a60b4675359285737be173dfa632269cab3/src/devices/cpu/mcs48/mcs48.cpp#L851-L853

## Reference

This contradicts the UPI-41 manual where the opcodes are documented with 1 cycle per instruction:

`IN A, DBB` on page A-6:
https://archive.org/details/bitsavers_intel804891AssemblyLanguageReferenceManualDec78_2416096/page/n163/mode/2up

`OUT DBB, A` on page A-10:
https://archive.org/details/bitsavers_intel804891AssemblyLanguageReferenceManualDec78_2416096/page/n167/mode/2up

Table 2-3 Instruction Timing Diagram on page 15:
https://www.manualslib.com/manual/728346/Intel-Upi-41a.html?page=19#manual

**Comment by happppp** [comment]
Looks good to me. You want to try making a pull request?
If no, then what's your prefered handle? (I'll place it in the commit) devsaurus or your name?

**Comment by devsaurus** [comment]
I better stay away from a PR to avoid any mess :)
Just use devsaurus as reference, thanks a lot!

**Comment by happppp** [comment]
Sure, here it is: https://github.com/mamedev/mame/commit/da58d779741f1430dd526c4e5e6a6e3a1803c804

**Comment by jotego** [comment]
Great!
