### ISSUE TITLE
perfectly GREAT and ON topic issue

### ISSUE THREAD

**Issue by 486DX2** [mamedev/mame#10741]
this issue is NOT off topic and will save all contributors A LOT of time.
Many time is wasted by manually editing XML files, which you shouldn't do anyway...

https://github.com/mamedev/mame/issues/10740

If you close it again, you're on your own and have fun wasting even more time editing XML files
If you don't realize this, then it's real shame!

**Comment by cuavas** [comment]
Nice one JJ.
