### ISSUE TITLE
idea: software list XML tool

### ISSUE THREAD

**Issue by 486DX2** [mamedev/mame#10740]
Hi

I see following things are endlessly repeated and I think you are all using text editors:

- update games in a software list XML file
- clean up of whitespace characters in XML file
- add games  in a software list XML file
- ...

So wouldn't it be a lot of time saving if MAME had an internal tool to work with the software list XML files?
Adding, updating, removing games and making sure no clean up is needed anymore.
Before you say: please make a PR, I'm not a developer :)

**Comment by cuavas** [comment]
It’s not worth it.  By the time you’ve created a GUI for all the metadata fields, it’ll be just as intimidating as dealing with the original XML.  You also need to look at the file with comments in context to know where the appropriate place to add an item is.  You’d end up putting a huge amount of effort into producing a tool that doesn’t cover all the use cases and requires the would-be contributor to manually check the result anyway.

**Comment by 486DX2** [comment]
The tool must use the DTD for the software lists. In this case you can make a 100% correct tool.
The tool should detect the place where previous entries were added and only save new entries in the same way.

Can you give me an example what a tool that follows the DTD and does the 2nd sentence can NOT do?

Manually check the result? No! That's what the tool must do.
The XML files are very basic and certainly not so complex as the XML structure for the arcade games. It will not be a huge amount of work. 

So as a conclusion: it's definitely worth it, unless you want to keep editing manually forever and waste an amount of time that's many times more (and spread accross all contributors) as developing this tool 1 time...

**Comment by 486DX2** [comment]
> You also need to look at the file with comments in context to know where the appropriate place to add an item is. 

Items can be added where you want. The order of them in the software list doesn't matter.

I'm very curious for an example of what you actually mean. Take a software list XML file and give me an example what you mean by this?

**Comment by cuavas** [comment]
* You’re not a contributor.
* You don’t understand the requirements to make the proposed tool useful.
* You lack the skills to build the tool you’re proposing.

I strongly suggest thinking carefully before opening more issues.
