### ISSUE TITLE
[Nitpick] "Echoing" is not present on real Konami GX Taisen Tokkae-dama

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [mamedev/mame#10755]
Mame's Emulation Nonsense causes emulation to "echo" where real machines don't.
Video:
Emulation "Echoing": https://www.youtube.com/watch?v=HFSMbWCkhCY
Real Machine Plays Normally: https://www.youtube.com/watch?v=h2k2XCDlvXY&t=86s
TAS Video Plays Normally: https://www.nicovideo.jp/watch/sm17159922

**Comment by cuavas** [comment]
It's a characteristic of the DirectSound audio output module when emulation is running below 100% speed. Welcome to the block list.

**Comment by happppp** [comment]
He's saying some sfx like that 'rock papa' voice is not supposed to echo/reverb.
But it'd need actual PCB reference. That video looks more like it's an older version of MAME.

**Comment by angelosa** [comment]
At worst Konami GX has a TMS DSP for audio effects, which had a big yellow warning last time I checked. Nitpick: there's a fantastic website named [MAMEtesters](https://www.mametesters.org/), use it.
