### ISSUE TITLE
macadb keypad mapping

### ISSUE THREAD

**Issue by ksherlock** [mamedev/mame#10772]
The mapping on clear and = looks suspicious (and doesn't work correctly for apple2gs; clear is = and = is nothing).

https://github.com/mamedev/mame/blob/0e56ddc1e9d342c3df768dbb569c611e577630f8/src/mame/apple/macadb.cpp#L174

https://github.com/mamedev/mame/blob/0e56ddc1e9d342c3df768dbb569c611e577630f8/src/mame/apple/macadb.cpp#L184

I would expect something more like:

```
PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("Keypad Clear") PORT_CODE(KEYCODE_NUMLOCK) PORT_CHAR(UCHAR_MAMEKEY(NUMLOCK))     // 0x47

PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_EQUALS_PAD) PORT_CHAR(UCHAR_MAMEKEY(EQUALS_PAD)) // 0x51
```

(which does work)

**Comment by rb6502** [comment]
This should be resolved in https://github.com/mamedev/mame/commit/8b2ed93002fcdde8e5c24de8b2c2289acc13ceab.
