### ISSUE TITLE
Jvs host and device classes do not support more than one command per packet

### ISSUE THREAD

**Issue by yz70s** [mamedev/mame#1079]
Jvs specification says that a jvs packet can contain more than one command.
Currently the classes jvs_host and jvs_device (files jvshost.cpp and jvsdev.cpp) do not support this.

As shown in page 19 of file jvst_ver3.pdf, in a request packet there can be more than one command between the length and checksum bytes.
Then in the response packet, after the length byte there is a single status byte followed by a set of report bytes for each of the commands, the checksum byte at the end.

**Comment by p1pkin** [comment]
are you sure ?
look closely at  jvsdev.cpp jvs_device::message   
		while(s < send_buffer + send_size) {
			int len = handle_message(s, send_size-(s-send_buffer), d);

but indeed we need better and standardized JVS interface code, which will satisfy both HLE and LLE of JVS IO boards.
btw, in most cases at the end it is nothing more than UART and 3-state "sense" line (used for addressing only).
I'd bet Chihiro used some motherboard's (or some MCU ?) 165xx-compatible UART for this.

**Comment by yz70s** [comment]
I am going to check it soon, since chihiro sends more than 1 command per packet :)
Chihiro uses a cypress ezusb chip with the uart of its internal 8051 cpu

**Comment by yz70s** [comment]
Ok checked it and in fact it does support more than one command per packet
