### ISSUE TITLE
Request to add ZX SPECTRUM NEXT models

### ISSUE THREAD

**Issue by denjhang** [mamedev/mame#10819]
This model has many interesting programs

**Comment by cuavas** [comment]
Do you have relevant info that would allow people to emulate these systems?

**Comment by denjhang** [comment]
https://wiki.specnext.dev/Emulators
https://github.com/mikedailly/CSpectPlugins

**Comment by denjhang** [comment]
https://emutopia.com/index.php/emulators/item/364-sinclair-zx-spectrum/1895-cspect
