### ISSUE TITLE
Game controller not working right in Metal Hawk (Rev C)

### ISSUE THREAD

**Issue by Cibomatto2002** [mamedev/mame#10817]
### MAME version

MAME 0.251.0

### System information

Operating System
			Windows 10 Home 64-bit
		CPU
			AMD Ryzen 7 2700	28 °C
			Pinnacle Ridge 12nm Technology
		RAM
			16.0GB Dual-Channel DDR4 @ 1197MHz (17-17-17-39)
		Motherboard
			Dell Inc. 0VYXHD (AM4)	31 °C
		Graphics
			C27F390 (1280x720@59Hz)
			4096MB ATI AMD Radeon RX 580 (Dell)	33 °C
		Storage
			931GB Seagate ST1000DM010-2EP102 (SATA )	30 °C
		Optical Drives
			No optical disk drives detected
		Audio
			Realtek High Definition Audio

### Incorrect behaviour

Can't go up and down with the game controller to more buttons need to be mapped to the controller the R key and the F key

### Expected behaviour

to go up and down with the controller and not needing the keyboard to do it.

### Steps to reproduce

play the game and when it says down you will need to use the keyboard R and F keys to go up and down.

**Comment by happppp** [comment]
That's not a MAME issue, it works fine here after remapping it to the joypad right analog stick. Yes, the default is R and F.
Press TAB -> input settings -> input assignments(this game), you can change the controls there.

**Comment by cuavas** [comment]
The current defaults are wrong though.

**Comment by happppp** [comment]
Some drivers use AD_STICK_Z, but that one maps by default to RT, which is a half-axis.

**Comment by cuavas** [comment]
That’s an issue with the Xinput module – it should map the right stick to Z/rZ for consistency with DirectInput and SDL.  It also doesn’t give the correct item IDs for the D-pad directions.

**Comment by cuavas** [comment]
06da34a209ac5482a3e06c07d5a0f3305c049c52 changes the collective pitch control to be a player 1 input, and makes Xinput item IDs more consistent with DirectInput and SDL.  You’ll still probably want to manually configure inputs for Metal Hawk, as collective pitch will be on the X axis of the right analog stick by default, and reassigning weapon buttons to shoulder buttons will make the game more playable when your thumbs are both busy with sticks.
