### ISSUE TITLE
EF9345 mishandles hiding the status line

### ISSUE THREAD

**Issue by EtchedPixels** [mamedev/mame#10841]
### MAME version

Current github as of filing

### System information

Not applicable

### INI configuration details

```INI
Not applicable
```

### Emulated system/software

EF9345

### Incorrect behaviour

The EF9345 driver should hide the status line when the configuration bits indicate to do so.

void ef9345_device::update_scanline(uint16_t scanline) 

honours the flag but only for scan line 0, whereas it applies for scanlines 0-9 (the first character row).

Found because I'm using a C language fork of the same code in a different emulator project to debug an EF9345 card I've been building

### Expected behaviour

Scan lines 0-9 should be margin colour

### Steps to reproduce

Set flag, inspect output

**Comment by sronco** [comment]
If I understand your report correctly, this is not a problem because the ef9345_device::update_scanline is configured to be called every 10 scanlines (0, 10, 20, ..), so "if (scanline == 0)" includes scanlines 0-9.

**Comment by EtchedPixels** [comment]
ok
