### ISSUE TITLE
Games that crash retroarch using mame current core android

### ISSUE THREAD

**Issue by 71knight** [mamedev/mame#10852]
Newman Athletics loads but stays at black screen.  Donkey Kong Jr plays for about 2 minutes then crashes retroarch.  Vitua racing is missing track graphics.  Star wars arcade by sega has backward shadows under ships.  Using mame version 0.251 for Android.

**Comment by happppp** [comment]
Kale forgot to mention the reason for closing. It's pretty simple: your bug report is for the Retroach port, not mainline MAME (MAME doesn't have support for Android yet).
FWIW my 1st guess: CPU endian issues.
