### ISSUE TITLE
Mame Bug for rotation in Ikari Warriors (rotation skip) Arcade Rom

### ISSUE THREAD

**Issue by GlensRetroShow** [mamedev/mame#10896]
### MAME version

looks like all versions except 0.191 

### System information

Windows 7,10 and 11 X86 builds
intel or AMD CPU

### Emulated system/software

Arcade Rom 

### Incorrect behaviour

Mame Bug for rotation in Ikari Warriors 
Hi, I have been developing a new 8 way joystick that will have 8/12/20 way rotation for playing games like
Ikari Warriors 
Forgotten worlds
Heavy Barrel
Front line
And so on.. There has been a bug in MAME where some rotations are skipped.  Can this be addressed?
Bug- http://forum.arcadecontrols.com/index.php?topic=147040.0
It looks like it was fixed in 0.191 then they unfixed again and still an issue
My controller will give people the ability to play this right but with the Bug, they will not be able to play it correctly.
My GRS Super Stick
https://www.youtube.com/watch?v=iyXXt4KSW94&t=1s
i would be happy to get a unit to the MameDev Team if needed.

Respectfully,
Glen Planamento
Glen's Retro Show

### Expected behaviour

for Ikari Warriors and other rotation games, the turn is not skipped.  each rotation should move left or right correctly 

### Steps to reproduce

ran mame and Ikari Warriors  rom

playing the game using left or right arrows it will skip or jump past the desired tuning

Bug- http://forum.arcadecontrols.com/index.php?topic=147040.0 

### Additional details

PC X86 build

**Comment by DavidHaywood** [comment]
There's some protection on these games to stop you swapping in an unapproved stick, or the games report a protection fail after a certain number of turns, it's possible sometimes it's meant to skip to prevent that failure.

**Comment by GlensRetroShow** [comment]
Oh 😮

So it's a form of copy protection

Thank you for this information

Respectfully
Glen Planamento
Glen's Retro Show

**Comment by angelosa** [comment]
> And so on.. There has been a bug in MAME where some rotations are skipped. Can this be addressed?

Cannot reproduce with bleeding edge, and I know the bug since I've fixed it back then. 
I believe you have a mismatch between what MAME expects and your stick, between `input (this system) -> positional` mapping and `analog input adjustements`. 
I don't expect a real rotary to work out with whatever defaults they are in (analog defaults are sketchy and don't always work for every single device, for example I have to bump down the Positional Sensitivity from '15' to '1' if I want to use my mouse instead of digital buttons).

**Comment by GlensRetroShow** [comment]
Thanks for the message back

I have a few modes in the GRS Super Stick and.i be ok adding a new mode of
needed
Mode 1 is the left and right rotation just does the left and right keyboard
arrow keys
Mode 2 the left and right rotation is seen as a mouse moving left or right
Mode 3 is a joystick HAT

Yes I use

1
95
Reverse off

Under analog  settings

If there is anything more I can send including one of my sticks I be happy
too for inspection

Respectfully
Glen Planamento
Glen's Retro Show

**Comment by GlensRetroShow** [comment]
I think we may have come up with a solution

Testing now

Thank you for all your time In messaging me and giving me some details to
look further into

Respectfully

Glen planamento
Glen's Retro Show
