### ISSUE TITLE
Default Bezel with pre compiled MAME releases.

### ISSUE THREAD

**Issue by arthur071169** [mamedev/mame#1094]
Allow use of a default bezel without needing to compile.  Offer a 'use bezel' with option of resolution and aspect ratios.
Point to supplied bezel Images deployed with pre compiled mame.

This will allow user to replace with the supplied images (eg) 800x600, 1024x768, 1280x1024 for 4x3 ratio, and similar for 16x9 (up to 1920 x1080 for hidef widescreen).  I use bezels for some games but sometimes a nice " generic black moulded plastic surround" would be less garish for certain others.

**Comment by arthur071169** [comment]
Polite bump request for this feature.  The bezel packs etc are great, but a blank faux generic arcade one would be great for games that do not have full Bezel artwork.  If there were the option to have 'bezels on' and where a game specific one is missing the default one is shown, that would be great.

**Comment by phulshof** [comment]
This feature should be coming in 0.194. 😀
