### ISSUE TITLE
Maintain curved screen effect when using Bezels in HLSL.

### ISSUE THREAD

**Issue by arthur071169** [mamedev/mame#1095]
Maintain curved screen edged (HLSL) when using a bezel.
Currently all screen curvature is lost when using a bezel image.

**Comment by Enverex** [comment]
You probably want to title your issues with something relevant to your request. Currently the titles are rather useless to anyone reading.

**Comment by ImJezze** [comment]
The issue you describe was fixed in 172. I tested Pac-Man with bezel in the latest release 176 and it works just fine. Can you give some more details, please?

**Comment by ImJezze** [comment]
I close this as not reproducible.
