### ISSUE TITLE
hlsl bloom is broken in Mame 0.252 but okay in prior releases

### ISSUE THREAD

**Issue by old-gamer** [mamedev/mame#10977]
### MAME version

0.252 (mame0252)

### System information

Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 8.00 GB
AMD A6-5200 APU with Radeon(TM) HD Graphics       2.00 GHz
d3d video output

### Emulated system/software

all vector based games

### Incorrect behaviour

hlsl bloom effect does not work at all in fullscreen, looks odd in windowed mode.

### Expected behaviour

hlsl bloom effect should cause a glow to be cast around vector graphics in fs/win modes

### Steps to reproduce

1. enable d3d and hlsl
2. run any vector game

### Additional details

attaching comparisons between fullscreen and windowed modes from mame 251 and 252 to better illustrate the issue:
![251-vector-fs](https://user-images.githubusercontent.com/127580438/224469577-efaea696-80db-4294-beb3-33e17ea2892d.png)
![251-vector-windowed](https://user-images.githubusercontent.com/127580438/224469579-4c2ea88e-4d3d-4ed0-ac95-ff943b1cda22.png)
![252-vector-fs](https://user-images.githubusercontent.com/127580438/224469584-e00bac35-a620-4d1f-aeec-86a95514acbd.png)
![252-vector-windowed](https://user-images.githubusercontent.com/127580438/224469586-27d7e3c0-f56d-488d-a465-c9f6c0214ef5.png)

Dunno what happened but I noticed a lot of the hlsl files got slightly rewritten last release and that's where this problem began.  251 and prior are okay AFAIK.  This happens right out of the box. I only changed the size of the screenshot setting.

**Comment by old-gamer** [comment]
Tested this on the other laptop, same results.  Included a short video converted to webm since github doesn't support mame's avi.
### System information

Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 4.00 GB
Intel(R) Pentium(R) CPU B950 @ 2.10GHz
d3d video output
[0000.webm](https://user-images.githubusercontent.com/127580438/224502104-ee3fe501-973d-426f-9d1e-ed0874957459.webm)
Very nice shimmer effect though, I guess?  The avi was HUGE, 441mb for a few seconds seems excessive for something so low-res.

**Comment by cuavas** [comment]
@MooglyGuy can you take a look at this?  We’ve had a few reports of issues with bloom when using D3D HLSL in 0.252.

**Comment by MooglyGuy** [comment]
Yeah, I'll have a look either tomorrow or later this evening. Thanks for the heads-up.

**Comment by old-gamer** [comment]
Thank you gentlemen.  I thought there was mention somewhere else of this (reddit maybe?) but I only remember distortion.fx got a workaround and nothing else.
