### ISSUE TITLE
UI font scaling issues when using uismall.bdf at different line sizes in fs/windowed modes

### ISSUE THREAD

**Issue by old-gamer** [mamedev/mame#10978]
### MAME version

0.252 (mame0252)

### System information

Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 8.00 GB
AMD A6-5200 APU with Radeon(TM) HD Graphics 2.00 GHz
d3d video output

### INI configuration details

```INI
uifont                    uismall.bdf
```

### Incorrect behaviour

font in left column jumps sizes, font in middle column skips certain sizes

### Expected behaviour

sizing of font should be incremental and consistent when changing the line size

### Steps to reproduce

1. change uifont to uismall.bdf
2. run mame and play with the line size in options

### Additional details

here is line size 30 (default) fullscreen, consistent fonts in all columns:
![fontdefaultfullscreen](https://user-images.githubusercontent.com/127580438/224471944-06651f97-3eab-4160-b2e4-5b791f99374b.png)

this is with lines 31, look at left column!:
![font31linesfullscreen](https://user-images.githubusercontent.com/127580438/224471970-9e3d8642-507b-445e-a680-d3130422f98f.png)

now in windowed mode, 37 lines look at middle column now:
![font37lineswindowed](https://user-images.githubusercontent.com/127580438/224471988-b6d39dc4-b852-4041-8ae1-27b5164f8ea0.png)

compare this to above, 38 lines rendered:
![font38lineswindowed](https://user-images.githubusercontent.com/127580438/224472018-aa4d7445-0e78-4bba-8799-b5349bff3c19.png)

I think cuavas fixed something last month with this, can't remember the link, but it is still a bit wonky to me.

**Comment by cuavas** [comment]
For low-resolution bitmap fonts, MAME restricts scaling to integer factors in the vertical direction at small sizes.  This is intentional.
