### ISSUE TITLE
apple2: Video-7 RGB DGHR monochrome mode behaves like mixed mode

### ISSUE THREAD

**Issue by inexorabletash** [mamedev/mame#10975]
### MAME version

0.252 via Ample

### System information

macOS 13.2.1 M1 MacBook Air

### Emulated system/software

apple2ee

### Incorrect behaviour

Recent updates have caused the apple2 Video-7 RGB double-hire mode 1 (monochrome 560x192) to behave the same as mode 3 (mixed). That is, bytes with the high bit set produce color output instead of monochrome.

mame64 apple2ee -skip_gameinfo -nosamples -window -nomax -video bgfx -sl4 '' -flop1 'DHGR_RGB_Mode_Tests.dsk' -nothrottle

When the system is running, in Machine Configuration, select Monitor Type: Video-7 RGB

Try the attached disk image:

[DHGR_RGB_Mode_Tests.dsk.zip](https://github.com/mamedev/mame/files/10944084/DHGR_RGB_Mode_Tests.dsk.zip)

The program loads a DHGR image and switches to DHGR mode 2 (COLOR 140x192). Press 1 to switch to mode 1 (MONOCHROME 560x192). Note that with the latest MAME there are color blocks rather than the entire display being monochrome. This is due to high bits set in the image, and is how mode 3 should display, not mode 1.

### Expected behaviour

In mode 1 the display should be entirely in monochrome. This is a regression from previous MAME builds.

**Comment by xotmatrix** [comment]
MAME (monochrome appears identical to mixed mode)
![mame_2023-03-10_12-02-13](https://user-images.githubusercontent.com/14209329/224377764-1f42df96-ce8f-44a3-b73a-9e27a4b7c228.png)

AppleWin (expected monochrome result)
![AppleWin_2023-03-10_12-02-46](https://user-images.githubusercontent.com/14209329/224377792-b04575d1-1a74-4568-954a-8ec88adb61a9.png)

**Comment by rb6502** [comment]
@benrg any ideas on this before I dive in?

**Comment by benrg** [comment]
I'm sure it's my fault. I'll look at it.

**Comment by rb6502** [comment]
This has now been resolved.  The same typo also broke IIgs monochrome DHGR and selecting "B&W" as the monitor type.

**Comment by inexorabletash** [comment]
Thanks! (I thought that line looked sketchy but I'm not set up to build.)

**Comment by rb6502** [comment]
It was actually a bit sketchier than that - there's a better fix in 2ea68c9 :-)
