### ISSUE TITLE
Sound bugs in Aurail and clones

### ISSUE THREAD

**Issue by old-gamer** [mamedev/mame#10985]
### MAME version

0.252 (mame0252)

### System information

Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 8.00 GB
AMD A6-5200 APU with Radeon(TM) HD Graphics 2.00 GHz
d3d video output

and another machine
Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 4.00 GB
Intel(R) Pentium(R) CPU B950 @ 2.10GHz
d3d video output

### INI configuration details

```INI
default settings all
```

### Emulated system/software

aurail and clones

### Incorrect behaviour

Game plays some of the sound effects and voice samples incorrectly or at wrong times.  Hard to get exact reproduction on each play as there is no pattern to the behavior.

### Expected behaviour

Game should play sound effects correctly/where appropriate.

### Steps to reproduce

1. play the game or let the demo run

### Additional details

It is hard to explain.  I discovered this game through one of Haze's videos on youtube around the time of mame 0.232, so I will note here that the sound bugs are not present on that release, but I don't know which version this started on as I didn't test all of them.  I think I went back to 0.249 or 0.248, so somewhere between those and 0.232.

Sometimes a random voice sample will play, or play only partially, at random times while other things are going on.  Other times it sounds like a voice playing real deep, kind of like it is in slow motion.  One that seems more consistent is the sample that says "remove control", which I don't even know where that is supposed to play in the game.  Last time I played I remember clearing at least 10 levels before I hit the wall with the difficulty which is why I set it down for so long, and I don't remember hearing that sample one time ever.  It randomly plays after exploding one of the first pairs of tanks.

Besides that there are other random drums and garbled stuff playing during some explosions and gun shooting.  It's better to just play and listen to the sounds.  I have some videos that are just too large to put here or convert online so unfortunately that really keeps me from showing you more :/

This video shows messed up sounds during shooting the small tadpole looking enemies in the demonstration mode, there's also a pop and the sound drops a bit afterward which was something I noticed happening sometimes as well:
[0000.webm](https://user-images.githubusercontent.com/127580438/224520989-93d6e1d9-179b-4f00-9aee-127644e6325f.webm)

To me it sounds like the sound gets temporarily overdriven and pops then drops out after some voices.  Like I said, I can't make it do all the things every time, and the video output is too big, and this was tested on 2 machines AMD and Intel.  Maybe someone else will have a better time with it to see or explain.

**Comment by DavidHaywood** [comment]
maybe another victim of sound latches no longer syncing? (haven't checked) @happppp ?

**Comment by happppp** [comment]
I can only trigger it when I play for a bit and then press F3 (soft reset).

**Comment by DavidHaywood** [comment]
ah, one for @wilbertpol to look into then?  seems a bit more complex than the sync problem I was hoping for ;)

**Comment by happppp** [comment]
Sega System 16 B writes to the 7759 MD pin.
I fixed it. But it silences upd7759 in system16b vgmplay songs since it doesn't know that hardware toggles the MD pin manually instead of always being in slave mode.
