### ISSUE TITLE
K054539 Reverb doesn't seem to be enabled

### ISSUE THREAD

**Issue by RaijinXBlade** [mamedev/mame#10988]
### MAME version

0.252

### System information

N/A

### Incorrect behaviour

Tested with Violent Storm, as that game, as far as I've seen, has one of the most obvious uses of the Reverb feature. I tested against an old album of the soundtrack released by Konami in the 90s, as well as the old Hoot music player, where the feature oddly works.

Reverb feature in the K054539 emulation simply doesn't appear to be enabled, or its simply breaking somewhere. Additionally, VGMPlay, another tool using MAME emulation 100% has broken Reverb as well just to note that, which I also used to test against MAME.

### Expected behaviour

I will send a few examples, some of the broken behavior, and some of the correct behavior. MAME and VGMPlay are the broken examples, Hoot, however is working.

[k054539 examples (violent storm).zip](https://github.com/mamedev/mame/files/10953047/k054539.examples.violent.storm.zip)

Lastly, here is a recording from the Konami Album that I mentioned, which the Hoot recording reflects more accurately.
https://www.youtube.com/watch?v=bmImud5c6lo

**Comment by cuavas** [comment]
Do you actually have a recording from the original arcade hardware for comparison purposes?  Soundtrack albums are not a valid reference as they have additional mastering work.

**Comment by RaijinXBlade** [comment]
Unfortunately I don't, minus 1 gameplay video on Youtube, but the guy is talking over the gameplay, so you can't hear anything anyway... However based on these examples, I'm highly confident that the original sounds closer to the Hoot recording and Youtube video, minus the additional mastering from the video like you mentioned. Plus, it doesn't make much sense to me that Hoot plays them with the Reverb intact exactly like the album version, yet they aren't in MAME. This applies to other games I've heard the album and Hoot versions for.

The reason I used Violent Storm too is because as far as I've heard, none of the other K054539 games have such pronounced use of the Reverb feature. Others definitely do for sure, like Mystic Warriors, Bucky O'Hare, Lethal Enforcers, etc. but it's harder to tell in those games without isolating the channels, and even then, it can still be hard to tell.

**Comment by cuavas** [comment]
I’m sorry, but soundtrack albums and other emulators are not a valid comparison.  We can only consider recordings from original hardware as references.

**Comment by RaijinXBlade** [comment]
Understandable, I suppose, although that sample chip does indeed have a reverb feature regardless of what examples I can provide that simply isn't enabled or broken in the emulation. That was the whole point of this report.

**Comment by RaijinXBlade** [comment]
Actually, no... I'm sorry but after some thought, I feel I must fight back on this. You can simply ignore all of the recordings except for the MAME recording and you can audibly hear that the effect is disabled. The k054539 has a reverb effect, and it's even noted in the emulation, but it's not working.
That is a bug, simple as that. Please reconsider this issue.

**Comment by FoxhackDN** [comment]
> Actually, no... I'm sorry but after some thought, I feel I must fight back on this. You can simply ignore all of the recordings except for the MAME recording and you can audibly hear that the effect is disabled. The k054539 has a reverb effect, and it's even noted in the emulation, but it's not working. That is a bug, simple as that. Please reconsider this issue.

Wait, is this for Violent Storm, the Konami game? Because their soundtracks released in the 90s had an annoying habit of inserting reverb on them. They sound nothing like the actual games. They're not trustworthy sources of actual game audio.

**Comment by philipjbennett** [comment]
We're aware that the 054539 reverb isn't emulated and I've provided digital
sound captures from various Konami PCBs to those who have expressed
interest in working on this.

**Comment by RaijinXBlade** [comment]
> > Actually, no... I'm sorry but after some thought, I feel I must fight back on this. You can simply ignore all of the recordings except for the MAME recording and you can audibly hear that the effect is disabled. The k054539 has a reverb effect, and it's even noted in the emulation, but it's not working. That is a bug, simple as that. Please reconsider this issue.
> 
> Wait, is this for Violent Storm, the Konami game? Because their soundtracks released in the 90s had an annoying habit of inserting reverb and other effects. Many don't sound like the actual games did and they're not trustworthy sources of actual game audio.

You can read what I said above if you want. It is for Violent Storm, and I am suggesting now to ignore any example audio I have provided except for the MAME one proper. The reverb effect noted in the emulator is simply not working, and all you need is that example to hear for yourself. Seems like a simple fix, and if so, you can enable the reverb in the code and then compare again for yourself.
