### ISSUE TITLE
Media selection dialog in debugger hangs process.

### ISSUE THREAD

**Issue by cracyc** [mamedev/mame#11008]
### MAME version

0.252

### System information

Windows 10

### Incorrect behaviour

Opening the file selector dialog from the main debug window hangs the process with the main thread in an cross thread call and the new dialog thread waiting for something in ntuser.

### Expected behaviour

Replacing owner with nullptr in dialog->Show(owner) (https://github.com/mamedev/mame/blob/master/src/osd/modules/debugger/win/consolewininfo.cpp#L172) fixes it.

**Comment by cuavas** [comment]
I don’t know exactly when this started happening:
* The switch to common item dialogs happened in 9ce44fa048793de5e14d1e7af98e8b5ca148d0f3 (MAME 0.245)
* It works up to MAME 0.251
* It’s broken in MAME 0.252

Unfortunately there’s a lot of refactoring in between.

**Comment by Tafoid** [comment]
As I reported to @cuavas on IRC, breakage detected in source changes done on January 28-29, 2023 (my time) with daily binary testing - there most likely being something awry in https://github.com/mamedev/mame/commit/68472d3d72ea4bbc545c0669348172b4e96c7b41

**Comment by cuavas** [comment]
> there most likely being something awry in 68472d3d72ea4bbc545c0669348172b4e96c7b41

I object to this characterisation unless you can substantiate it.  The controller crashes turned out to be an issue that was there all along with abuse of the DirectInput API.  This could very well end up being some similar abuse of COM that’s been there all along and just got aggravated somehow.  Do you have any actual evidence that it’s something awry with that commit?

**Comment by Tafoid** [comment]
> > there most likely being something awry in [68472d3](https://github.com/mamedev/mame/commit/68472d3d72ea4bbc545c0669348172b4e96c7b41)
> 
> I object to this characterisation unless you can substantiate it. The controller crashes turned out to be an issue that was there all along with abuse of the DirectInput API. This could very well end up being some similar abuse of COM that’s been there all along and just got aggravated somehow. Do you have any actual evidence that it’s something awry with that commit?

No, no direct proof.  I can only speculate with the information that is available to me.  Checking available artifact binaries for that day seems to suggest to me the big commit I linked could have either caused this error to surface or caused its direct regression.
You can check the [daily diff and log files](https://mameload.mameworld.info/diff_01fcb2e0decf670a4cdee3d37b6f7ebde9b8f02b-c6b00ccff2870f0acb45e8b2ca9ac783708a2869.7z) here if that helps at all.

**Comment by cuavas** [comment]
Observations with a build of 68472d3d72ea4bbc545c0669348172b4e96c7b41:
* Running directly with `-sound dsound` it will sometimes work and sometimes freeze
* Running under GDB with `-sound dsound` it will always work
* Running directly with `-sound xaudio2` it will always freeze
* Running under GDB with `-sound xaudio2` it will always freeze

The difference is that with `dsound`, a COM object is instantiated at some point before `CoInitialize` is ever called, while with `xaudio2` it explicitly initialises COM with a multi-threaded apartment.

Testing with MAME 0.251, it also hangs when using `-sound xaudio2`.  It’s something going wrong with COM – it’s never worked properly with a multi-threaded apartment, and apparently only worked by chance in the first place.

We really need to sort out our use of COM – just expecting it to work with no calls to CoInitializeEx, and creating contradictory apartment types in input_winhybrid.cpp and xaudio2_sound.cpp is very bad form.

**Comment by cuavas** [comment]
For reasons I’m not going to explain here, the common item dialogs can’t work in a multi-threaded apartment if they’re shown from their owning window’s thread.  The simplest thing to do right now is to always create a single-threaded apartment on the main thread.  Xaudio2 doesn’t seem to suffer any detrimental effects.
