### ISSUE TITLE
Mame's lut-default.png needs colors flipped

### ISSUE THREAD

**Issue by old-gamer** [mamedev/mame#11001]
### MAME version

0.252 (mame0252) to at least 0.240

### System information

Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 8.00 GB
AMD A6-5200 APU with Radeon(TM) HD Graphics 2.00 GHz
d3d video output

and another machine
Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 4.00 GB
Intel(R) Pentium(R) CPU B950 @ 2.10GHz
d3d video output

### Incorrect behaviour

lut-default.png produces wrong colors

### Expected behaviour

Should output correct colors

### Steps to reproduce

1. start mame
2. enable d3d with hlsl and turn on the 3D lut option

### Additional details

I tested every version that came with this file, and 2 before that (0.241 and 0.240), and this image does the same thing in all of them.  I then used one of those new NES images posted over at reddit this past week and they all work correctly.  Seems you have the color cube going the wrong way with the colors.

I used the "01 - NES NTSC.png" and noted that the colors look correct with it because they have the red and blue on the correct axes.  The one in mame is reversed:
mame
![lut-default](https://user-images.githubusercontent.com/127580438/226184341-4106e9a8-dce0-4437-9b4e-8100df131e6e.png)
01 - NES NTSC.png
![01 - NES NTSC](https://user-images.githubusercontent.com/127580438/226184367-681ea6d8-2749-4531-9886-c1e2907003d4.png)

comparison (hangon with mame default)
![0001](https://user-images.githubusercontent.com/127580438/226184439-7fd64d89-1c12-45b1-8ef5-bb66edc9b126.png)
and with 01 - NES NTSC.png:
![0002](https://user-images.githubusercontent.com/127580438/226184596-6b73c317-7d4d-4010-a48d-4a04f5d74425.png)

Also the default mame lut messes up the UI as well, causes wrong colors on menus, dunno what it does with artwork as I don't use artwork for the games:
No lut:
![UILUT2a](https://user-images.githubusercontent.com/127580438/226185233-e844203b-af93-400c-8791-60b07bfd58e2.png)
with lut:
![UILUT2b](https://user-images.githubusercontent.com/127580438/226185241-a12761a4-e156-4586-ae7c-5e919ad16246.png)

link to the reddit post with NES luts: https://www.reddit.com/r/emulation/comments/11sdauq/37_new_nes_3d_luts_for_mame/
link to download: https://www.mediafire.com/file/mxo1yj0alevfwtx/nes_mame_luts.zip

edit- If I may ask, how exactly does the lookup table interact with the chroma settings?  Does it work independently or with it?  It confuses me as I thought the chroma settings were to simulate the television standard (BT.601) and the lut kind of does the same thing?

**Comment by MooglyGuy** [comment]
At the moment, the LUT chain operates standalone with the BGFX backend, so no additional processing is performed.

With the Direct3D 9 backend and the HLSL post-processing pipeline enabled, it appears that the LUT is applied _last_, after all other post-processing.

To me, that doesn't make too much sense - the impression I get from Wellington's NES LUTs is that they should most likely be applied first in the pipeline rather than last, so I'm changing the Direct3D 9 backend accordingly.

**Comment by MooglyGuy** [comment]
A pull request to swap the Red and Blue channels in lut-default.png has been submitted, as well as the above change as to where the LUT is applied when using `-video d3d`. Note that the latter change is a code change, so unless you get set up with a build environment, you're not going to be able to test that part of the change until the nightly builds are run.

**Comment by old-gamer** [comment]
Duly noted, and with this hunk of junk machine, by the time mame would be built the problems would be fixed lol. Thanks for your time and for all the cleanups going on.  I feel like 0.253 may be a lot tidier now all around.

**Comment by MooglyGuy** [comment]
> Duly noted, and with this hunk of junk machine, by the time mame would be built the problems would be fixed lol. Thanks for your time and for all the cleanups going on. I feel like 0.253 may be a lot tidier now all around.

Totally, and if you do end up finding any more notable regressions vs. 0.251 or other obvious post-processing bugs, keep 'em coming.

**Comment by old-gamer** [comment]
Ok if you say so.  I don't want to spam your hub with wrongful issues though, I try to be careful and intelligent with this.  I know you guys deal with a lot of knuckleheads ;)

**Comment by MooglyGuy** [comment]
Oh, totally, but it never hurts to double-check over on, say, the Bannister forums whether something's a regression, bug, or "weird but intended", and file a Github issue if determine to be the former two. :)

**Comment by old-gamer** [comment]
Oh you're right, I never think to look there for bugs etc, just here and mametesters.  Anyway I'll shut up on this now so everyone can do what they gotta do.
