### ISSUE TITLE
K053260 Fade-in bugged (Sample Reverse function)

### ISSUE THREAD

**Issue by RaijinXBlade** [mamedev/mame#11067]
### MAME version

0.253

### System information

N/A

### Incorrect behaviour

Hello again. I reported a K0 chip related issue before, and I remember what I was told last time, but I feel the need to bring these up when I come across them regardless just to make these known.

To be brief, there appears to be a reverse sample function in the K053260, and Turtles in Time seems to use it. In MAME, some sections of music bug out instead, as it appears to expect a fade-in.

### Expected behaviour

I have some examples here, yes I know, the comparisons are Hoot again, but I can't find an album recording of this game (regardless of any post processing Konami adds, you can still hear how it's supposed to sound in those albums).
It seems to me there are some people in this community that know all about these issues with the K0 chips and have provided recordings from the actual PCB. Unfortunately, I am unable to do so, and expect this to be ignored. Once more, I do just want to make people aware as I come across these issues, and I am sure enough that they are indeed bugs that I can report them confidently.

[Turtles in Time examples.zip](https://github.com/mamedev/mame/files/11132780/Turtles.in.Time.examples.zip)
Here, the Boss them and Night Riders stage theme are provided. The issues are heard at the end of each recording, and I have also provided the isolated channels as well. Listen for the fade-ins. The Hoot recordings better reflect what the hardware is doing. MAME simply ignores them, and even behaves oddly in the case of the Boss theme (it plays a 'plonk' sound for some reason).

Sorry again for the trouble.

### Additional details

This may be of some use. https://www.patreon.com/posts/konami-053260-80375018

**Comment by happppp** [comment]
Should be good after https://github.com/mamedev/mame/commit/9b84136e68231ff7fb042c457aae1217045a56ff

**Comment by happppp** [comment]
FWIW here are some uses that are easier to spot:

trigon game start (plane takes off)
bad: some guy is talking
good: engine sound

rollerg titlescreen
bad: loud misplaced bass guitar
good: sweep sound

**Comment by RaijinXBlade** [comment]
Ah, yes you are right, sorry. I only tested Turtles in Time, and wasn't as familiar with the others.

Thank you for addressing this issue. It appears to be working well.
