### ISSUE TITLE
Overclock Slider very slow (0.175)

### ISSUE THREAD

**Issue by Catarax** [mamedev/mame#1108]
Go to the overclock maincpu slider, 100% by default, it's like you have a to "RIGHT" 3/4 times to go to 101%.

It takes really a looooong time to overclock to maximum (even if you keep pressed on the right key). 
Hitting only one time should add 1% directly.

While some old build like MAME Plus! XT (unofficial) was really fast to switch.

**Comment by Tafoid** [comment]
MAME already allows for a stepping of slider values.  Holding LEFT CTRL while using arrows will increment a full integer value at a time.  Holding LEFT ALT while using arrows will bring values to MAXIMUM or MINIMUM allowed.

**Comment by Catarax** [comment]
Thanks for the tip!
