### ISSUE TITLE
Improve startup user experience

### ISSUE THREAD

**Issue by RalfVB** [mamedev/mame#11082]
MAME offers a lot of great functionality that's useful for frontend developers.

There's just one thing left to wish for - grant frontends more control over how starting up MAME is presented.

The first thing MAME does (from the user's perspective) is display it's window - even when the ROM you're trying to run fails validation. MAME should not show it's window until it is ready to emulate. This is how MAME worked a long time ago, and it's regrettable they changed this.

If the ROM is ok, you're then left staring at a black window that displays loading progress, which is pointless since there are few systems that do not load near-instantly on modern PC's anyway. The point is, it doesn't look good, it's not handled gracefully, and it's not even useful in practice. User experience matters.

Here's how it should behave:

1. Launch MAME
2. MAME sends loading/decryption status information to stdout. We can use this to show a progress bar, for example.
3. When ready, show window. We can then 'grab' this window and have external control over it. 

This would help integrating MAME in modern gaming setups tremendously.

Thanks for reading!

**Comment by cuavas** [comment]
Spamming duplicate issues is very bad behaviour.

**Comment by RalfVB** [comment]
So is posting your picture when you're as ugly as you are Vas.

Op za 8 apr 2023 om 12:31 schreef Vas Crabb ***@***.***>:
