### ISSUE TITLE
Saving in cfg overclock cheats

### ISSUE THREAD

**Issue by Catarax** [mamedev/mame#1109]
I would like that Mame save our custom overclock to the cfg of a game.
Instead of having to do it every time I start the game.

Thanks!

**Comment by Tafoid** [comment]
When overclocked, many machines can show instabilities. malfunction, hang, or cause other visual or audio bugs which tend to trigger false testing reports.  As a result, much like the warning screens for problem games and machines, we have a long standing policy of not allowing this option (or removal of important information screens).

If you want to chronically overclock emulated CPU speeds, it is suggested that you adjust the driver source to the level you require before compiling.  The slider option is meant to be there as a Developer tool (only triggered with -cheat) and is not viewed as a permanent solution.  Once a Developer gets the correct CPU speed, they simply adjust the source files and it's done.  You can do this yourself as well with your local compile/source tree and you'll not have to deal with sliders anymore.

As it stands I only know of 2.. maybe 3 drivers which people commonly overclock (Double Dragon, Neo-Geo (mslug), Hard Drivin).

**Comment by Catarax** [comment]
Thanks a lot for the details, I overclocked the driver, all is fine!
Have you a recommended MHZ value for overclocking a Neo-Geo? (Will close after)
