### ISSUE TITLE
hcastle: Rain goes over the floor

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#11096]
### MAME version

0.248

### System information

Ubuntu mate 20.04

### Incorrect behaviour

On Haunted Castle the rain covers the `STAGE=01` text as well as the ground.

![0028](https://user-images.githubusercontent.com/1863036/231389459-27d9a962-44c9-42aa-9a5a-4c0378035359.png)

### Expected behaviour

The rain should stop at the ground, see original board in [this YT video](https://www.youtube.com/watch?v=jMOR-M1l9u4).

### Steps to reproduce

`mame hcastle` and watch the attract mode until the rain starts

**Comment by rb6502** [comment]
In that video, the rain *does* cover the ground.  It's pretty obvious when they get the game over and the rain freezes.  It's definitely not in front of the text though (which it is in MAME and in Konami's official emulator on the Switch).

**Comment by 987123879113** [comment]
The rain is covering even the "STAGE=01" text in that video. Watch as soon as the rain starts to fall, before it reaches the bottom of the screen. It's really noticeable when the rain reaches the text at that point. Pay attention to the upper sides of the T which are getting obscured by the rain drops.

Here's a direct recording of a PCB: https://www.youtube.com/watch?v=CE6dF3STK1k

**Comment by rb6502** [comment]
Wow, good find!  With the direct-feed footage you can see that the rain covers all the other layers.  I guess this is not a bug then.

**Comment by DavidHaywood** [comment]
https://www.youtube.com/watch?v=umn5npUM_XE  here's another PCB recording

**Comment by jotego** [comment]
I think you're right. It's hard to tell whether the bottom 8 pixels are getting rain or not, but I think they do indeed. That other video is much clearer, @DavidHaywood thank you!
