### ISSUE TITLE
SCSI controller not working anymore in HP 9000/3xx systems

### ISSUE THREAD

**Issue by rzero9** [mamedev/mame#11126]
### MAME version

0.253 (mame0253-267-gd2a0073a61a)

### System information

Windows Server 2022 Standard (64-bit), US English
Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 20 GB RAM

### Emulated system/software

hp9k360 and other machines in hp9k_3xx.cpp

### Incorrect behaviour

The emulated machine displays "register test failed" after the SCSI controller test and cannot boot from hard disk or a CD.

![0000](https://user-images.githubusercontent.com/13178957/233003630-9f7976b0-cbbd-43e4-9cd1-35e4653025c9.png)

### Expected behaviour

The machine should display the boot selection menu on the right side and be able to boot from CD or hard disk. This behavior is correct in the official MAME 0.253 release, so this is a recent regression.

![0000](https://user-images.githubusercontent.com/13178957/233004017-dbedb321-d806-4db5-9f98-de7527e5afc8.png)

### Steps to reproduce

1. Start MAME with the HP-UX 9.10 install CD from the software list (mame hp9k360 hpux_9_10).
2. After a few seconds, the startup screen will display "register test failed" and it won't display the boot selection menu.

**Comment by pmackinlay** [comment]
Should be fixed by c78d0d86dc1a80dfb5b89e15558fa7257d8f0b41.

**Comment by rzero9** [comment]
Tested and working now. Thanks!
