### ISSUE TITLE
[pitfight] attract mode sound switch on/off

### ISSUE THREAD

**Issue by bobrosspainting** [mamedev/mame#11137]
Hello friends,

Please excuse me, this is my first issue and i'm not a developer.
I try to be as clear as possible!

Macbook Pro M2
SDL Mame 0.253
rom: pitfight

I noticed in the attract mode sequence of pitfight, there is sometimes sound and sometimes no sound at all.
The sound seems to dissapear randomly, so I mean: a full attract mode loop has sound EVERYWHERE and the next has no sound AT ALL, etc etc (see screenshots below for the screens which have sound, normally)
I remember this game as a kid in the arcade and there was always sound in the attract mode.

Yesterday I completed the game and the attract mode that follows right after the ending credits, has no sound at all too. 4 or 5 loops of the soundless attract mode later, the sound is there again.

I thought this was a suspicious thing so I reported it :)
What could be the reason? I don't think the real game switched between sound/no sound in the attract mode loop?

Here are screenshots of the attract mode that definitely have sound:

The logo;

![0000](https://user-images.githubusercontent.com/130948185/233685564-29215e34-9cfe-4f72-80d0-00eee5b95197.png)

The presentation of the 3 fighters:

![0000](https://user-images.githubusercontent.com/130948185/233683401-ba9ba36a-a277-42fb-a8f8-f1570f1583e5.png)

![0001](https://user-images.githubusercontent.com/130948185/233683417-47165e5d-2649-48d6-a28a-ad349796d2e4.png)

![0002](https://user-images.githubusercontent.com/130948185/233683423-03d96a54-74d1-4fc8-b089-0ba6abae43b8.png)

The demo fight after this has punch sounds too (when they fight).

All those sounds are gone completely in random attract mode appearance (while the next attract mode loop has sound again (everywhere above), etc etc)

**Comment by happppp** [comment]
It's how the game was designed.
See also: https://mametesters.org/view.php?id=2244

**Comment by bobrosspainting** [comment]
I was wondering how you know for 100% this is not a bug in the driver atarig1.cpp used by pit fighter?
Can you give me other Atari games behaving the same in the attract mode that are NOT using atarig1.cpp ?

Otherwise it could be a bug in atarig1.cpp, if we don't have the real PCB as a proof?
