### ISSUE TITLE
Lua and ACT Apricot PC/XI doesn't receive F12 keypost properly

### ISSUE THREAD

**Issue by mcfilmmakers** [mamedev/mame#11144]
``I have a script as follows (please spare me the speeches on the print lines.. I'm trying to debug). I'm launching using this commandline:

mame.exe apricotxi -exp:1 512k -script "apricot_flop.lua" -flop1 msdos32 -flop2 ap006

The script
```
co = coroutine.create(function (a)
    emu.wait(1)
    print("1")
    emu.wait(1)
    print("2")
    emu.wait(1)
    print("3")
    emu.wait(1)
    print("4")
    emu.wait(1)
    print("5")
    emu.wait(1)
    print("6")
    emu.wait(1)
    print("7")
    emu.wait(1)
    print("8")
    emu.wait(1)
    print("9")
    emu.wait(1)
    print("10")
    emu.wait(1)
    print("11")
    emu.wait(1)
    print("12")
    emu.wait(1)
    print("13")
    emu.wait(1)
    print("14")
    emu.wait(1)
    print("15")
    emu.wait(1)
    print("16")
    emu.wait(1)
    print("17")
    emu.wait(1)
    print("18")
    emu.wait(1)
    print("19")
    emu.wait(1)
    print("20")
    emu.wait(1)
    print("21")
    emu.keypost("\n")
    print("pressed enter")
    emu.wait(1)
    print("1")
    emu.wait(1)
    print("2")
    emu.wait(1)
    print("3")
    emu.wait(1)
    print("4")
    emu.wait(1)
    print("5")
    emu.wait(1)
    print("6")
    emu.wait(1)
    print("7")
    emu.wait(1)
    print("8")
    emu.wait(1)
    print("9")
    emu.keypost("F12")
    print("pressed F12")
    emu.wait(1)
    print("1")
    emu.keypost("F12")
    print("pressed F12 again")
    emu.wait(1)
    print("1")
end)

coroutine.resume(co)
```

So the whoel exercise is intended to allow the system to boot, press a key to allow the system to enter manager and then the intention is to, once manager loads, press F12 and then Y to exit manager and enter DOS proper.

However, when it comes to the F12 keyposts, the system seems to be receiving some sort of keypress (the screen blinks both times) but the system doesn't display the expected prompt to press Y to exit manager.

If I actually press the F12 key on my keyboard, the expected prompt displays like it should. This leads me to believe that there's something off in the system emulation when it comes to using lua but it very well could be user error...

**Comment by cuavas** [comment]
`emu.keypost` sends characters to the emulated system.  `emu.keypost("F12")` will type the characters “F”, “1” and “2”.  You need to manipulate the input port state directly for special keys that don’t map to characters.
