### ISSUE TITLE
z80net input keyname for G is incorrect

### ISSUE THREAD

**Issue by mcfilmmakers** [mamedev/mame#11179]
### MAME version

0.154

### System information

Windows 11

### Emulated system/software

z80ne

### Incorrect behaviour

The input key name is the G key is incorrect. It is indicated as "c  G" in "Input settings" -> "Input Assignments (this system)".

### Expected behaviour

 The key name should be "g  G".

### Steps to reproduce

- Launch MAME using mame.exe z80net -skip_gameinfo -cass1 cannibal -console
- Navigate to "Input settings" -> "Input Assignments (this system)"
- Scroll down to the G key and notice the key name is "c  G" instead of "g  G"

**Comment by happppp** [comment]
Ok I see it, consider this fixed.
