### ISSUE TITLE
Atari 5200 Pacman not working correctly in last 2 releases

### ISSUE THREAD

**Issue by blindphoneman** [mamedev/mame#11183]
Hi:

With MAME 0.253 and 0.254, I can no longer run a5200 pacman.  I start play and I hear no sound.

Went back to MAME 0.252 and it seems to work ok there.

**Comment by angelosa** [comment]
Very likely same as https://mametesters.org/view.php?id=8597

**Comment by blindphoneman** [comment]
Here's a clue:

If I play under Atari 400, it seems to work.

mame a400 pacman

can start play with letter a or joystick button 1.

**Comment by angelosa** [comment]
Here's a clue:

Go ahead and make a [https://mametesters.org](https://mametesters.org/) account

I hate duplicates

Closing this.
