### ISSUE TITLE
capcom/cps3.cpp CPS3 Games unable to find their CD-ROMs

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#11203]
### MAME version

0.254 (mame0254-146-g442c6ba7288)

### System information

Windows 11 x64
i7-12700K at 5.2Ghz
64GB DDR5 RAM
AMD 5600XT

### INI configuration details

```INI
Use -norc
```

### Emulated system/software

capcom/cps3.cpp, jojo, sfiii, sfiii2, sfiii3

### Incorrect behaviour

Games are failing to find their CD-ROMs

### Expected behaviour

Games to find their CD-ROMs as previously.

### Steps to reproduce

1. Kill sfiii diff, cfg, nvram.  Have the sfiii roms in \roms and sfiii chd in \roms\sfiii.
2. mame sfiii -norc
3. Hit insert to fast forward to error message ' Please insert CD-ROM and push Player1 Shot1 button.'

**Comment by john-iv** [comment]
![1](https://user-images.githubusercontent.com/9202235/236985401-0e3603af-5213-4ef7-a2a5-a31a29f1ef9e.png)
![2](https://user-images.githubusercontent.com/9202235/236985405-1d015acc-aa81-4b95-b8d3-1bbbe8492ef4.png)

**Comment by john-iv** [comment]
Swapped to .254 release and it found the CD and went through the init process.  I let it go all the way through and then exited out.  Swapped back to tip of tree to try and it still didn't locate the CD-ROM again.

**Comment by john-iv** [comment]
Per the shoutbox:

[windyfairy](https://forums.bannister.org/ubbthreads.php?ubb=showprofile&User=9803): If I had to guess I'd guess that you'd need to add :image to all of the CD-ROM disk region names

[windyfairy](https://forums.bannister.org/ubbthreads.php?ubb=showprofile&User=9803): Open cps3.cpp, ctrl+f for ":cdrom" and mass replace with ":cdrom:image"

This solution appears to have worked w/ new compiled .exe.

**Comment by 987123879113** [comment]
Fixed by https://github.com/mamedev/mame/commit/187525b76a1a0319f6697315225338b88c0e349b, this can be closed now I think.

A bunch of other similar issues are being fixed in PR https://github.com/mamedev/mame/pull/11205.

**Comment by john-iv** [comment]
Will confirm and close after the merge to master.

**Comment by john-iv** [comment]
Osso got to CPS3 before Windy's pr so compiled and confirmed fix from master and they work now, closing against 0.254 (mame0254-151-g534b7d15957)
