### ISSUE TITLE
request: add MESS debuggers

### ISSUE THREAD

**Issue by retroarch-girl** [mamedev/mame#11218]
add MESS debuggers such as:

- game boy debugger (VRAM viewer etc etc)
- same for nes, snes, ...

all emulators in MESS are not feature rich and can barely be debugged

take any seirous game console emulator and look at its debugging tools

**Comment by retroarch-girl** [comment]
stop closing this, moron!
it's a good feature request!!

**Comment by retroarch-girl** [comment]
how you gonna debug your roms if you don't have a specific game console debugger?

**Comment by angelosa** [comment]
Just waiting for the ban hammer JJ ...

**Comment by cuavas** [comment]
We get by just fine with the MAME debugger and the scripting capabilities.
