### ISSUE TITLE
game boy emulation is too slow and not accurate

### ISSUE THREAD

**Issue by retroarch-girl** [mamedev/mame#11217]
game boy emulation is too slow and not accurate
compare to well know game boy emulators such as gdb, emulicious, ...

please fix it for next release

**Comment by cuavas** [comment]
There’s nothing specific in this report.  But the great thing about Game Boy emulation is you have a choice of emulators with different features/compatibility.

**Comment by retroarch-girl** [comment]
in addition it runs slower then a real game boy which I compare to my homebrew code or to existing game boy games

so it's not accurate :)

**Comment by retroarch-girl** [comment]
the specific thing is 

- it runs SLOWER then real hardware
- it runs SLOWER then other emulators

bott suggest there is a problem in MAME
