### ISSUE TITLE
Holding issue for DECLARE_WRITE_LINE_MEMBER et al

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#11253]
With the removal of `DECLARE_WRITE32_MEMBER`, `READ16_MEMBER`, et al having been removed, the presence of `(DECLARE_)[READ/WRITE]_LINE_MEMBER` sticks out like a sore thumb.

```
#define DECLARE_READ_LINE_MEMBER(name)      int  name()
#define READ_LINE_MEMBER(name)              int  name()
#define DECLARE_WRITE_LINE_MEMBER(name)     void name([[maybe_unused]] int state)
#define WRITE_LINE_MEMBER(name)             void name([[maybe_unused]] int state)
```

Particularly since the `DECLARE_` versions of the macros have identical signatures, I'd like to have a holding ticket for their eventual removal, much in the same way there was a holding ticket for unnecessary `LOG_GENERAL` redefinitions that I've now addressed.

I mainly have two questions that need answering before I look at potentially removing this legacy piece:
- Is there a specific reason that they've been kept around other than inertia, and
- Would it be alright to finally remove them in favor of explicit function signatures?

**Comment by rb6502** [comment]
I agree these should go away, I've actually done a few as bare functions already.  The only downside is losing the [[maybe_unused]] on the write versions, but I can't imagine there are that many write line handlers that ignore the incoming state.

**Comment by MooglyGuy** [comment]
There probably are a handful, as some people have used write line handlers as ways of triggering events without necessarily knowing what the actual causes are of those events.

The broader concern, and what I seem to recall to be why they weren't replaced with all of the other handler-macro removals, was an interest in eventually doing a switch from `int` to `bool` for line-based handlers. As you alluded to, though, there has been quite a bit of code introduced that uses bare functions already, and there seems to be no push-back on PRs that do the same, so I suspect that ship has long since sailed.

**Comment by happppp** [comment]
ref: https://github.com/mamedev/mame/pull/11283 https://github.com/mamedev/mame/commit/9f661e567c4528e7f7f662209e4b677f12b99875
