### ISSUE TITLE
[sms1pal] wrongly reports 3 screens in -listxml

### ISSUE THREAD

**Issue by aretrogamer** [mamedev/mame#11279]
Hi all,

If you look at xml tags in -listxml of sms1pal, there are 2 mysterious LCD screens listed.
My question: how can a master system I have 2 LCD screens, here named left_lcd and right_lcd while it's output goes to a TV which is a raster display (see first display tag)?

`<display tag="screen" type="raster" rotate="0" width="268" height="240" refresh="49.701460" pixclock="5320342" htotal="342" hbend="61" hbstart="329" vtotal="313" vbend="46" vbstart="286" />
		<display tag="left_lcd" type="lcd" rotate="0" width="268" height="240" refresh="49.701460" pixclock="5320342" htotal="342" hbend="61" hbstart="329" vtotal="313" vbend="46" vbstart="286" />
		<display tag="right_lcd" type="lcd" rotate="0" width="268" height="240" refresh="49.701460" pixclock="5320342" htotal="342" hbend="61" hbstart="329" vtotal="313" vbend="46" vbstart="286" />`

the parent rom sms does NOT have those screens;

`<display tag="screen" type="raster" rotate="0" width="268" height="224" refresh="59.922743" pixclock="5369317" htotal="342" hbend="61" hbstart="329" vtotal="262" vbend="27" vbstart="251" />`

Can somebody explain this mystery?

**Comment by FoxhackDN** [comment]
... isn't that for the Sega 3D Glasses?

**Comment by aretrogamer** [comment]
That could make sense, but i'm not familiar with that hardware.
Then the question remains; why is the parent rom sms not having those 2 LCD screens?
Are there different master system I consoles made, one supporting the Sega 3D Glasses and the other not?

**Comment by FoxhackDN** [comment]
Yeah. The Master System II had no card slot, so it didn't support the LCD glasses.

**Comment by aretrogamer** [comment]
> Yeah. The Master System II had no card slot, so it didn't support the LCD glasses.

I'm not talking about the Master System II but the Master System I (sms). If you look in the XML, there the 2 LCD screens are missing...

`<display tag="screen" type="raster" rotate="0" width="268" height="224" refresh="59.922743" pixclock="5369317" htotal="342" hbend="61" hbstart="329" vtotal="262" vbend="27" vbstart="251" />`

So my question is: why is only the clone sms1pal having those LCD screens and not the parent sms?

**Comment by aretrogamer** [comment]
Is the 3D glasses emulated in mame?
If yes, how to enable it and what games support it?
I think the game must run in 1/2 resolution in order to make the LCD shutters show a correct image for each eye

**Comment by enikland2** [comment]
The 3D glasses is represented as a secondary view with two screens side-by-side, that you select in the Video Options menu, after you have enabled it in the Machine Configuration menu.

We know that the shutter lenses doesn't work the same way as screens, but the screen device in MAME allows the "binocular hack" that you can activate in the options, that redraws the previous image when the lenses become opaque, what allows you to play on a regular monitor without flicker, or to be able to play the game using a modern 3D display or glasses device which supports 3D using the side-by-side mode.

If you start to get nitpicky and don't think this is a good solution, @happppp will come and remove the code at first glance.

I plan to try another solution using Lua to move the hack to the layout code, if the new bitmap functionality that was added allows to keep the previous screen buffer and draw it to a bitmap that could be displayed when the lenses become opaque.

**Comment by aretrogamer** [comment]
I'm happy to try both ways!

In real hardware, the game had to support the glasses and ran in 1/2 resolution switching the graphics in turn so each eye has a different view. 

Will it run in all sms games or do I need these ones?

https://segaretro.org/Category:3D_Master_System_games

**Comment by happppp** [comment]
No I wouldn't remove the 3 screens workaround because of someone elses opinion.

1/2 resolution? no, more like half refresh rate. The shutters are software controlled, so other games won't be in '3d'. Read more about them here: https://segaretro.org/3-D_Glasses

**Comment by cuavas** [comment]
Take this to discussions or a forum – the reported “screens” don’t always map to physical screens.
