### ISSUE TITLE
Extra logging now being shown on iteagle.cpp games output

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#11278]
### MAME version

mame0254-312-g997be1f7e54

### System information

Win 11 x64
i7-12700K @ 5.2Ghz
64GB DDR5
AMD 5600XT

### INI configuration details

```INI
No mame.ini needed.  Use -norc.
```

### Emulated system/software

iteagle.cpp / gtfore06

### Incorrect behaviour

Doing a benchmark run on gtfore06, instead of the single line 'quiet' performance output it is now outputting additional lines starting with below:

```
com0: Video device ID: 5121a
com0: Glide version = 2.61.00.0437
com0: Number Voodoo systems found = 1
com0: Hardware type = 0
com0: Eagle 40 MB System Boot ROM Version: 2.09
com0: (C)1999-2005 Incredible Technologies
```
...

### Expected behaviour

Single line of performance info:
Average speed: 467.10% (89 seconds)

### Steps to reproduce

`mame.exe gtfore06 -norc -bench 90`

### Additional details

Commentary from the shoutbox postulates that osd_printf_info didn't output for this driver at one point and that new behaviour has changed in the last month.  OG indicates the line to comment out to quiet it.  RB indicates that logerror and osd_printf_info shouldn't be outputting.  Trimmed for conciseness. 

----
John IV: Running a bench on gtfore06 it looks like someone has turned on some extra logging as com0: is outputting. Should this be turned off by now before freeze?
John IV: mame gtfore06 -bench 90 -norc
John IV: 0.254 (mame0254-312-g997be1f7e54)
..
Haze: it's outputting com0 to the commandpromt
Haze: https://i.postimg.cc/YqnBWgTS/gtfore06.png so yeah somebody has left a printf turned on somewhere
..
hap: if it's recent, maybe the log changes from moogly
..
R. Belmont: it really shouldn't be doing both logerror() and osd_printf_info() either.
John IV: I haven't made any changes, normally when I run the bench suite the output is quiet, it's just the performance and run time. This logging showed up in my results compilation step so it was noticeable.
John IV: It doesn't happen on 0.254 release.
Haze: it's nothing John is doing, it happens by default, and has started happening sometime in the last month.
Olivier Galibert: what do the messages look like?
Haze: https://i.postimg.cc/YqnBWgTS/gtfore06.png
Olivier Galibert: Vas Crabb 2019-09-26
Olivier Galibert: that's... now new
Olivier Galibert: I guess osd_printf_info didn't print before for some reason?
Olivier Galibert: src/mame/machine/iteagle_fpga.cpp comment line 419
..
R. Belmont: it shouldn't be doing both logerror and osd_printf_info in any case.
[Tafoid](https://forums.bannister.org/ubbthreads.php?ubb=showprofile&User=1745): Actually, it appears to be during May 23 work - likely https://github.com/mamedev/mame/pull/11250 has drawn it out.

**Comment by john-iv** [comment]
Close issue per RB.

**Comment by happppp** [comment]
Fixed with https://github.com/mamedev/mame/commit/8f84fbb708b1f38ebfaa362342be25fa0d17d262
