### ISSUE TITLE
Print screening tile viewer (F4) creates a blank clipboard image

### ISSUE THREAD

**Issue by ShadowMan44** [mamedev/mame#11297]
### MAME version

0.255

### System information

Windows 10

### INI configuration details

```INI
Mine doesn't have a general Mame.ini file in it, it has like presets and examples which don't cover it.
```

### Emulated system/software

Arcade/any

### Incorrect behaviour

I tried printscreening the mame graphics viewer, instead of getting a screenshot of the tiles I get a black box in the clipboard.

### Expected behaviour

I expected a screenshot of the game's tile viewer pasted into the image editing program.

### Steps to reproduce

Go into the tile viewer (F4), print screen it using the button on your keyboard, then paste the clipboard image into any image editing software.

**Comment by angelosa** [comment]
Cannot reproduce, I can stamp the F4 contents just fine. What romset you are running on?

**Comment by ShadowMan44** [comment]
> Cannot reproduce, I can stamp the F4 contents just fine. What romset you are running on?

I only have 2 roms in the folder ATM, they are Mario Roulette and Namco Museum vol 2. Both have the same result.

**Comment by rb6502** [comment]
Try -video gdi.  Windows can have trouble PrintScrn-screenshotting some accelerated graphics APIs.

**Comment by ShadowMan44** [comment]
> Try -video gdi. Windows can have trouble PrintScrn-screenshotting some accelerated graphics APIs.

Okay, how do I do that?

**Comment by MooglyGuy** [comment]
> > Try -video gdi. Windows can have trouble PrintScrn-screenshotting some accelerated graphics APIs.
> 
> Okay, how do I change the video setting to gdi in mame?

He literally told you how.

**Comment by ShadowMan44** [comment]
> > > Try -video gdi. Windows can have trouble PrintScrn-screenshotting some accelerated graphics APIs.
> > 
> > 
> > Okay, how do I change the video setting to gdi in mame?
> 
> He literally told you how.

...no? all he said was "try -video gdi" but didn't explain what I exactly need to do to set it like that. Do I need to open the mame.ini file and put it in there? Is there a setting in the windows registry thing I gotta set? Command prompt? I don't know.

**Comment by MooglyGuy** [comment]
https://docs.mamedev.org/usingmame/usingmame.html

**Comment by ShadowMan44** [comment]
> https://docs.mamedev.org/usingmame/usingmame.html

>go into command prompt
>type "mame.exe -video gdi"
>can't actually play any of the games now because... I don't know man I just want to change the video setting on it
