### ISSUE TITLE
Apple IIgs shows incorrect time

### ISSUE THREAD

**Issue by frankmilliron** [mamedev/mame#11298]
### MAME version

0.255

### System information

macos 12.6.6 "Monterey"

### Incorrect behaviour

The default ProDOS driver for the built-in real-time clock on an Apple IIgs system is showing the incorrect time. It is showing the current time +3 hours. I am on the West Coast of the United States, so am unsure if it's showing the correct time on the East Coast. Perhaps an incorrect time calculation from UTC? Thanks for looking into it!

### Expected behaviour

Current shown time minus three hours would be the expected behavior.

### Steps to reproduce

Start MAME using Apple II Desktop (as it includes both the standard ProDOS clock driver, as well as a graphical display of current time.
See incorrect time in the top right corner of the GUI menu bar.

**Comment by rb6502** [comment]
Hmm.  Setting my MacBook Pro running 13.5 to Pacific time changes the Mac's menu bar clock appropriately but the apple2gs shows 3 hours later in the Control Panel.  apple2e with a Thunderclock configured shows correct Pacific time in Apple II Desktop so it is specific to the IIgs/Mac clock chip emulation.  Interesting.

**Comment by rb6502** [comment]
This is fixed in ca881dd.  Thanks for the report, I appreciate it!

**Comment by frankmilliron** [comment]
Thanks for fixing it!
