### ISSUE TITLE
xml format

### ISSUE THREAD

**Issue by hiroshiyung** [mamedev/mame#11290]
Hi everyone,

For my masters thesis I'm doing statistics about arcade games.
I found out about mame, downloaded the driver xml file and created a database.

I have a problem trying to find the region of a game.
Some games have between brackets the region: world, europe, japan or US.

But I found that more then 90% of all games have nothing between brackets. Are all those games considered 'world' region?
Or how to find their region?

Thanks for your time
Hiroshi Yung

**Comment by ICEknigh7** [comment]
"World" sets usually mean "rest of the world" when regional variations of it do exist (so actually, "everywhere except Japan, US, etc"). If something was released without changes all across the globe, I'd say it doesn't need an additional clarification regarding which region it was released in, which is why they don't have a "(World)" tag.

**Comment by happppp** [comment]
Hi again, lack of knowledge of arcade game region is not an issue with the MAME application. MAME source code is a pretty good resource for detailed hardware info, not arcade release metadata since we don't even carry the release month/season or for example country of manufacture.

**Comment by cuavas** [comment]
Please use a community forum to ask questions (e.g. [here](https://github.com/orgs/mamedev/discussions)).

The release regions are included when they’re known and they’re useful for distinguishing between versions of a system.  In general, descriptions try to make it possible to unambiguously identify the system or software.  They aren’t supposed to follow a fixed schema.  That aside, we often don’t know exactly which regions systems were officially marketed in.

**Comment by hiroshiyung** [comment]
Thanks!

If a game has (Euro) , is this the same as region (Europe)?

**Comment by hiroshiyung** [comment]
What a hostile project mame is!
You just remove my question!!!

I found a better, more friendly database
Www.arcade-history.com

Goodbye

**Comment by happppp** [comment]
Yet you keep coming back. I've only tagged the last 2 months, these are all the same person: https://github.com/mamedev/mame/issues?q=label%3AJJ+is%3Aclosed

**Comment by Robbbert** [comment]
Do a search for user ghost - most of these will have been JJ. I went back 18 months and found these possibilities:
10741, 10740, 10738, 10472, 10186, 10185, 10184, 10025, 9869, 9260, 9246, 9087, 9085, 9069, 9068, 9066, 9063, 8926, 8921, 8906, 8814, 8811, 8810, 8776, 8718.
