### ISSUE TITLE
DRCs are spewing extra log information 'DRC on' when run using -bench

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#11308]
### MAME version

0.255 (mame0255-42-g69c38762335)

### System information

Windows 11 x64
i7-12700K @ 5.2Ghz
64GB DDR5
AMD 5600XT

### INI configuration details

```INI
No ini needed. -norc produces it.
```

### Emulated system/software

DRC drivers, iteagle, kinst, vegas

### Incorrect behaviour

The DRC games are now spewing 'DRC On' continuously on -bench usage and impacting speed when run normally as games.

`mame gauntleg -blitz 90 -norc > blitz.txt`

DRC on
DRC on
DRC on

Produces a 156MB text file and takes a long time to finish its 90 seconds.  This appears to be happening in any DRC enabled driver.  Seen in games blitz, gauntleg, kinst, starsldr, gtfore06 for example.

### Expected behaviour

One line output like before:

Average speed: 5841.54% (89 seconds)

### Steps to reproduce

1. From command-line launch MAME with the following parameters.
2. `mame.exe blitz -bench 90 -norc`
3. Observe 'DRC on' line continuously scrolling.

### Additional details

As mentioned the performance drops when playing the game regularly 'mame.exe kinst' as well.  Kinst goes from 1500+% to 500%.

**Comment by happppp** [comment]
Yup, looks like a printf accidentally snuck in, it's gone now.
