### ISSUE TITLE
1943, F3 restart wrong

### ISSUE THREAD

**Issue by gdicnng** [mamedev/mame#11305]
### MAME version

0.255

### System information

windows 10 64-bit 22H2 ,China 
AMD Ryzen 3 2200G with Radeon Vega Graphics       3.50 GHz
RAM 16.0 GB

### INI configuration details

```INI
rompath                   "roms;d:\EMU\roms"

cheat                     1

language                  "Chinese_Simplified"

window                    1
keepaspect                1
maximize                  1
video                     d3d
pause_brightness          1.00

skip_gameinfo             1
confirm_quit              1

plugins                   1
plugin                    autofire,inputmacro
```

### Emulated system/software

1943

### Incorrect behaviour

rom name : 1943.
If press F3 to restart the game  and  continue to play , the game will retart again shortly and repeat to restart .
( sorry ,if my English is not good enough.)

### Expected behaviour

If press F3 to restart the game  and  continue to play ,it will work normally.

### Steps to reproduce

1,start the game 1943 ( mame.exe 1943 )
2,play a while
3,press F3 ,continue to play
4,it will restart shortly and retart again and again

**Comment by MooglyGuy** [comment]
F3 triggers the `reset()` function on all relevant devices. This may or may not produce correct behavior, particularly on systems that did not have a reset button, or chips without a reset line. You probably want to use Shift+F3 to hard-reset the system. Ticket is invalid.

**Comment by BPzeBanshee** [comment]
It's producing behaviour that's a clear regression from previous builds, so I respectfully disagree and say the ticket's valid. 

Trying `1943` on 0.255 myself, the game self-reset for me after the transition to the second stage, which is well past the time I would've thought "oh, here's a startup problem, maybe I should shift-F3 instead".

**Comment by MooglyGuy** [comment]
If it's actually a regression from previous versions, then sure, it sounds like a reasonable enough ticket.

**Comment by happppp** [comment]
It's not a new regression, and I agree that soft-reset issues often aren't actual bugs.
But this time an accuracy improvement appears to have fixed it: https://github.com/mamedev/mame/commit/bfc050049618fce03aa588821a1302f07655a614

**Comment by MooglyGuy** [comment]
If it's not a new regression, I would appreciate @BPzeBanshee clarifying the following statement:

> It's producing behaviour that's a clear regression from previous builds

I hope we can all agree that lying just to get a ticket acknowledged isn't a good look.

**Comment by happppp** [comment]
Maybe a different issue. Anyway I'm not getting any reset after finishing stage 1.
What I was seeing was a consistent lockup at boot after a soft reset, same thing gdicnng described.

**Comment by BPzeBanshee** [comment]
> If it's not a new regression, I would appreciate @BPzeBanshee clarifying the following statement:

@MooglyGuy The last several dozen times I played `1943` and it's child sets they had zero troubles with F3 resets. Can't give you exact builddates but I know at least the previous builds I had from a few months ago and last year were fine. 

As to why it took a whole level for it to start behaving erraticly instead of right away, your guess is as good as mine. Getting low-key called a liar because of it doesn't make me thrilled about pursuing it further though.
