### ISSUE TITLE
[0.255] several games: missing control(s)

### ISSUE THREAD

**Issue by kingdomofdaventry** [mamedev/mame#11328]
I found several games having missing controls. Even some that don't have Player 1 controls!  Theoretically those game CAN'T run since no player 1 control...
Could it be fixed in next version?

It are the games:

- `footchmpbl`: player 2 control missing

`	<input players="4" coins="4" tilt="yes">
			<control type="joy" player="1" buttons="2" ways="8" />
			<control type="joy" player="3" buttons="2" ways="8" />
			<control type="joy" player="4" buttons="2" ways="8" />
		</input>`

- `gunmania`: player 2 and player 3 control missing

`<input players="4" coins="1" service="yes">
			<control type="lightgun" player="1" buttons="7" minimum="0" maximum="63" sensitivity="100" keydelta="15" />
			<control type="only_buttons" player="4" buttons="8" />
		</input>`

- `zelost`: player 2 control missing

`	<input players="3">
			<control type="only_buttons" player="1" buttons="4" />
			<control type="only_buttons" player="3" buttons="8" />
		</input>`

- `fi6845`: player 1 control missing (same for its clone `fi8275`). Theoretically this game CAN'T run since no player 1 control...

`	<input players="2" coins="1">
			<control type="joy" player="2" ways="2" />
		</input>`

- `sarc110`: player 1 control missing (same for its clone `sarc110a`). Theoretically this game CAN'T run since no player 1 control...

`<input players="2">
			<control type="joy" player="2" buttons="3" ways="8" />
		</input>`

- `turbosub`: player 2 control missing (same for its clones `turbosub6` and `turbosub7`)

`<input players="3" coins="2">
			<control type="stick" player="1" buttons="2" minimum="0" maximum="255" sensitivity="70" keydelta="30" />
			<control type="only_buttons" player="3" buttons="11" />
		</input>`

**Comment by angelosa** [comment]
turbosub handled in https://github.com/mamedev/mame/commit/5ebd8c61f0743bc96407a3fdb58dfe0b78f48b9c
All the others are marked MACHINE_NOT_WORKING a.k.a. we don't accept bug reports by end user for any of these.
