### ISSUE TITLE
This is not a 7400 but 7408

### ISSUE THREAD

**Issue by Franck78** [mamedev/mame#11336]
Hello,

while trying unsucessfully to build MAME on ubuntu 22.04 (first gcc11 bug, now something with LUA) I decided to take a look at something I know, the 7400 nand gate.

Surprise, its reset state is set to something impossible for a Nand. No sure how this is used but any machine using it must be wrong ?

In fact when looking the .h file, it describes a AND gate ;)
https://github.com/mamedev/mame/blob/11d3c7211b15fd37c611c69bc79f4c3cde374ce1/src/devices/machine/7400.h#L19

https://github.com/mamedev/mame/blob/11d3c7211b15fd37c611c69bc79f4c3cde374ce1/src/devices/machine/7400.cpp#LL32C3-L32C3

**Comment by rb6502** [comment]
The comment doesn't perform the operation, as you know :-)

However, the actual implementation does appear to be AND rather than NAND.  No machines appear to use it currently so no harm is done.

**Comment by cuavas** [comment]
That device should probably be removed anyway.  It’s pretty much useless.

**Comment by Franck78** [comment]
I can't tell for you what is the best solution.
You have three !
-rename the files
-delete the files
-patch the files
BTW the lua thing was 'need to be root' for it to install.

**Comment by cuavas** [comment]
Removed by 4701887d6cc48d835a2963d412052fa31825cd9f
