### ISSUE TITLE
Killer Instinct and Killer Instinct 2 do not get beyond blue startup screen.

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#11346]
### MAME version

0.255 (mame0255-157-g99917dfa206)

### System information

Win11 x64
i7-12700K @ 5.2Ghz
64GB DDR5
Radeon 5600XT
2560x1440 res. fullscreen

### INI configuration details

```INI
No ini needed, use -norc.
```

### Emulated system/software

kinst, kinst2

### Incorrect behaviour

Game won't proceed into attract mode beyond the blue screen.

### Expected behaviour

Regular attract mode.

### Steps to reproduce

1. `mame.exe kinst -norc`
2. Observe blue screen.
3. Insert/FF will eventually cause the blue screen to re-paint.

![1](https://github.com/mamedev/mame/assets/9202235/10527165-c512-49f5-94d3-1f784541884a)

### Additional details

Relatively recent regression, maybe a week or less?
Killed .cfg / .diff / .nv

**Comment by Robbbert** [comment]
It's from the last 1 or 2 days.

[:ata:0:hdd] ':maincpu' (8802D934): :ata:0:hdd dev 0 write_cs0 0002 0007 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D934): :ata:0:hdd dev 0 write_cs0 0003 0006 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D934): :ata:0:hdd dev 0 write_cs0 0004 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D934): :ata:0:hdd dev 0 write_cs0 0005 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D934): :ata:0:hdd dev 0 write_cs0 0006 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D934): :ata:0:hdd dev 0 write_cs0 0007 0020 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802E52C): :ata:0:hdd dev 0 write_cs0 0002 0007 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802E52C): :ata:0:hdd dev 0 write_cs0 0003 000d ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802E52C): :ata:0:hdd dev 0 write_cs0 0004 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802E52C): :ata:0:hdd dev 0 write_cs0 0005 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802E52C): :ata:0:hdd dev 0 write_cs0 0006 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802E52C): :ata:0:hdd dev 0 write_cs0 0007 0020 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D9B4): :ata:0:hdd dev 0 write_cs0 0002 0007 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D9B4): :ata:0:hdd dev 0 write_cs0 0003 0006 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D9B4): :ata:0:hdd dev 0 write_cs0 0004 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D9B4): :ata:0:hdd dev 0 write_cs0 0005 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D9B4): :ata:0:hdd dev 0 write_cs0 0006 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802D9BC): :ata:0:hdd dev 0 write_cs0 0007 0030 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DA58): :ata:0:hdd dev 0 write_cs0 0002 0007 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DA58): :ata:0:hdd dev 0 write_cs0 0003 0006 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DA58): :ata:0:hdd dev 0 write_cs0 0004 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DA58): :ata:0:hdd dev 0 write_cs0 0005 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DA58): :ata:0:hdd dev 0 write_cs0 0006 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DA58): :ata:0:hdd dev 0 write_cs0 0007 0030 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DAC8): :ata:0:hdd dev 0 write_cs0 0002 0007 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DAC8): :ata:0:hdd dev 0 write_cs0 0003 0006 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DAC8): :ata:0:hdd dev 0 write_cs0 0004 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DAC8): :ata:0:hdd dev 0 write_cs0 0005 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DAC8): :ata:0:hdd dev 0 write_cs0 0006 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DAD0): :ata:0:hdd dev 0 write_cs0 0007 0020 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DBC4): :ata:0:hdd dev 0 write_cs0 0002 00a8 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DBC4): :ata:0:hdd dev 0 write_cs0 0003 0015 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DBC4): :ata:0:hdd dev 0 write_cs0 0004 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DBC4): :ata:0:hdd dev 0 write_cs0 0005 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DBC4): :ata:0:hdd dev 0 write_cs0 0006 0000 ffff ignored (DRQ) command 20
[:ata:0:hdd] ':maincpu' (8802DBC4): :ata:0:hdd dev 0 write_cs0 0007 0020 ffff ignored (DRQ) command 20

**Comment by ajrhacker** [comment]
On my debug build, kinst dies with the following error:

> src/emu/devcb.h:2431: void devcb_write<int, 1>::operator()(offs_t, Input, std::make_unsigned_t<Input>) [Input = int, DefaultMask = 1]: Assertion `m_creators.empty() && !m_functions.empty()' failed.

**Comment by cuavas** [comment]
The problem is that `abstract_ata_interface_device::device_start` tries changing the signal handlers of its attached devices.  This was always a problem waiting to happen.  It should be able to send the signal straight through the slot.
