### ISSUE TITLE
Street Fighter II' CE: Awkward hit/special colors at the ending credits

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#11365]
### MAME version

0.255 (mame0255-205-g69a5b662f6e)

### System information

Windows 10 64-bit  22H2

### Emulated system/software

CPS1

### Incorrect behaviour

Wrong hit or special color.
![mame_snap_resize 00](https://github.com/mamedev/mame/assets/80734530/5ce883c3-7031-4913-953e-9e0287384af6)
![mame_snap_resize 01](https://github.com/mamedev/mame/assets/80734530/a3337717-b114-4b98-91e0-7abad0ae37d0)

It only happens at the end credits. Sometimes Ryu and Ken can't hit each other, this is totally aleatory, some times it happens, some times it doesn't.

### Expected behaviour

Correct colors.

### Steps to reproduce

1. Run mame with: `mame sf2ce -window -norc`
2. Load the attached savestate.
3. Watch as it happen.

**Savestate**: [sf2ce.zip](https://github.com/mamedev/mame/files/11853295/sf2ce.zip)

### Additional details

It might happen with other games of the series.

**Comment by DavidHaywood** [comment]
almost certainly can happen on real hardware in certain situations, timing issues might cause it to happen more often in MAME.

**Comment by cd4053** [comment]
I did a few runs with 0.254 (oficial release) and the issue never happens.
