### ISSUE TITLE
Sega C2: resolution is not 256 wide

### ISSUE THREAD

**Issue by Strugglemeat** [mamedev/mame#11366]
### MAME version

0.254

### System information

all

### Incorrect behaviour

MAME loads Sega System C2 games with width 256 pixels, or "H32" mode for 32*8 tile width
This arcade hardware is based on the Sega Genesis, which has a VDP that displays in both H32 and H40
It may be possible for the Sega C2 arcade hardware to play games in H32 mode, but I tested Puyo Puyo 2 and Columns and both are H40 games for Sega Genesis - it's less than 1% chance they are H32 on one platform and H40 on the other.

Another piece of evidence from https://segaretro.org/Sega_System_C2_hardware_notes_(2003)
" It would seem that the Sega C2 video hardware only allows a 320 pixel
 display to be used. Trying to use a 256 pixel display results in an
 unstable display. While the VDP may be putting out the right signals,
 chances are the EPM5032 is programmed to support the 320 pixel mode
 exclusively."

### Expected behaviour

320x224 display

**Comment by rb6502** [comment]
Not a bug.  C2 games still have to program the VDP for H40 mode, and doing so will cause MAME to change the screen resolution.  The mode shown at startup is temporary for any system where the software can program the resolution.
