### ISSUE TITLE
START CLEANING the MAME mess

### ISSUE THREAD

**Issue by ultimaresource** [mamedev/mame#11383]
please START CLEANING the MAME mess!!!

many games have

- years with ?
- wrong publisher
- wrong name
- ...

Download the ONE AND ONLY gaming database here https://www.arcade-history.com/index.php?page=download
AND TAKE THE DATA FROM MY FILE TO CLEAN UP YOUR MESS!!!!!!!!!! It's all wrong

And don't forget to buy many stuff from my webshop OR I DROP SUPPORT FOR MAME IN HISTORY.XML

Best regards
Gaming History

See my collection: https://www.arcade-history.com/?page=public&uid=2

**Comment by cuavas** [comment]
For the hundredth time, arcade-history is unsourced and unreliable.
