### ISSUE TITLE
shikigam can not start

### ISSUE THREAD

**Issue by gdicnng** [mamedev/mame#11381]
### MAME version

0.256

### System information

windows 10 .
cpu :  AMD Ryzen 3 2200G with Radeon Vega Graphics       3.50 GHz.

### INI configuration details

```INI
# not change anything
```

### Emulated system/software

shikigam

### Incorrect behaviour

game can not start

### Expected behaviour

it should works normally.

### Steps to reproduce

1. verifyroms
mame.exe shikigam -verifyroms

shikigam    : upd78081.655 (8192 bytes) - NOT FOUND - NO GOOD DUMP KNOWN
romset shikigam [coh3002t] is best available
1 romsets found, 1 were OK.

---------

2. try to start game 
mame.exe shikigam -window

but the game can not start .
the information show in CMD :

upd78081.655 NOT FOUND (NO GOOD DUMP KNOWN) (tried in shikigam coh3002t)
WARNING: the machine might not run correctly.

-----------------------------------------------------
Exception at EIP=00007ff751201b7c (devcb_write<int, 1u>::operator()(int)+0x000c): ACCESS VIOLATION
While attempting to read memory at 0000000000000380
-----------------------------------------------------
RAX=0000000000000000 RBX=00000192d8f04c00 RCX=0000000000000368 RDX=0000000000000001
RSI=00000012687ced88 RDI=0de0b6b3a763ffff RBP=0de0b6b3a763ffff RSP=00000012687c9810
 R8=0000000000000368  R9=0000000000000000 R10=0000002540be4000 R11=0000000000000002
R12=f21f494c589c0000 R13=000000000000003e R14=00007ff75e959160 R15=00000012687c9c80
-----------------------------------------------------
Stack crawl:
  00000012687c9880: 00007ff751201b7c (devcb_write<int, 1u>::operator()(int)+0x000c)
  00000012687c98b0: 00007ff752105d74 (ata_hle_device::set_irq(int)+0x0054)
  00000012687c98e0: 00007ff7521206c6 (ata_mass_storage_device::finished_command()+0x0096)
  00000012687c9920: 00007ff75210629e (ata_hle_device::busy_tick(int)+0x003e)
  00000012687c9990: 00007ff751366d9b (device_scheduler::timeslice()+0x014b)
  00000012687c9af0: 00007ff751363eff (running_machine::run(bool)+0x01bf)
  00000012687cf010: 00007ff754a1986b (mame_machine_manager::execute()+0x020b)
  00000012687cf3f0: 00007ff758b70aef (cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x03cf)
  00000012687cf6b0: 00007ff758b710fd (cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x004d)
  00000012687cf710: 00007ff754a13ee9 (emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x0029)
  00000012687cfad0: 00007ff75a7259a3 (luaopen_lfs+0xea6f93)
  00000012687cfba0: 00007ff74c9513b1 (__tmainCRTStartup+0x0231)
  00000012687cfbd0: 00007ff74c9514e6 (mainCRTStartup+0x0016)
  00000012687cfc00: 00007ffc8fc17614 (BaseThreadInitThunk+0x0014)
  00000012687cfc80: 00007ffc915226a1 (RtlUserThreadStart+0x0021)

### Additional details

( sorry , if my English is not good enough)

Another people talk about the problem here : https://www.ppxclub.com/forum.php?mod=viewthread&tid=722864 .

He say : TAITOGN games can not satrt in ARCADE0.256 ,like shikigam .

I test shikigam on mame 0.256 , it can not start .
I test shikigam on old mame 0.255 , it's OK to start .

**Comment by cuavas** [comment]
See 02de94f93f4d7794a3b8d35a5d569a6e6d3527ff
