### ISSUE TITLE
command line "-showusage" has a small problem

### ISSUE THREAD

**Issue by gdicnng** [mamedev/mame#11438]
### MAME version

0.256

### System information

windows 10,
cpu AMD Ryzen 3 2200G with Radeon Vega Graphics       3.50 GHz

### INI configuration details

```INI
# no need to change
```

### Emulated system/software

# not a specific system

### Incorrect behaviour

( my English is not very good .)

command line ,
mame.exe -showusage ,
it will show some help information.

for example:
-homepath            path to base folder for plugin data (read/write)
-rompath             path to ROM sets and hard disk images

there is spaces between the option and  the short description .

the problem is that some option is too long , no space  between  the option and the short description.
for example :
-joystick_contradictoryenable contradictory direction digital joystick input at the same time

after the option ( -joystick_contradictory ),there is no spaces at all .

### Expected behaviour

for the long options , it need one or more sapces between the option and the short description .

### Steps to reproduce

1.
command line 
mame.exe -showusage

2.
the information show in the CMD has a small problem.
if the option is too long , these is no space between the option and the short description.

for example:
-beam_intensity_weightset vector beam intensity weight 
-joystick_contradictoryenable contradictory direction digital joystick input at the same time
-full_screen_brightnessbrightness value in full screen mode

it need one or more spaces  between the option and the short description :
-beam_intensity_weight      set vector beam intensity weight 
-joystick_contradictory     enable contradictory direction digital joystick input at the same time
-full_screen_brightness     brightness value in full screen mode

**Comment by cuavas** [comment]
Fixed in 5ab956906bcb0e6ba41303e92ca4ba363b1ca8fd
