### ISSUE TITLE
error: PCH file uses a newer PCH format that cannot be read

### ISSUE THREAD

**Issue by MrUbun2** [mamedev/mame#11456]
### MAME version

0.257 (mame0257-76-g057f7dd38ef)

### System information

MacOS Ventura 13.5
ARM64, 16GB unified RAM, M2 10-core gpu (M2 8-core cpu)
Trying to compile MAME using the pacmantest example from the docs.

### Incorrect behaviour

I'm using the example command `emmake make SUBTARGET=pacmantest SOURCES=src/mame/pacman/pacman.cpp` from the docs and it always gives the error `error: PCH file uses a newer PCH format that cannot be read`

### Expected behaviour

It should compile for the web using emscripten.

### Steps to reproduce

1. I installed emsdk
2. I cloned the MAME repository
3. I used the example command `emmake make SUBTARGET=pacmantest SOURCES=src/mame/pacman/pacman.cpp`

**Comment by mizapf** [comment]
I get this error message often when pulling an update and not doing a _make clean_.

**Comment by MrUbun2** [comment]
Using `make clean` seems to have fixed the issue but now I'm getting another one:
`../../../../../src/emu/validity.cpp:179:2: error: static assertion failed due to requirement 'sizeof(void *) == 8': PTR64 flag enabled, but was compiled for 32-bit target`

**Comment by cuavas** [comment]
Please get help compiling for Emscripten on a discussion forum.  Issue trackers are not for general help, and we lack the resources to provide individual support.
