### ISSUE TITLE
Serial output module

### ISSUE THREAD

**Issue by stonedDiscord** [mamedev/mame#11477]
This is a feature request because I sadly can't get it to work myself, otherwise this would have been a PR.

I'd like to see an additional "serial" module in src/osd/modules/output

The reason for that being that it'd make it really easy to use USB-Serial devices like Arduinos or ESP32 boards to control LEDs and mechanical devices attached to the computer MAME is running on.

The code for that should be relatively straightforward, it's essentially a mix of console.cpp and network.cpp but instead of boost ASIO network sockets it should use the boost ASIO module for the serial port.

**Comment by rb6502** [comment]
If you have an attempt that you couldn't get to work, maybe open it as a draft PR so people can take a look?

**Comment by cuavas** [comment]
To be honest, I’d be reluctant to support this.  It would add additional complexity and be difficult for developers to test.  Some of the issues:
* Requires a computer with a serial port to sanity check with.  This is becoming rarer, particularly in notebook computers.
* Requires some device that consumes the format to test properly.
* Additional configuration that varies between platforms, as Windows and every *NIX handle serial ports differently.
* The current network output module has issues with systems that have a lot of output or update them at high rates.  This would be even worse with a serial output.
* It would be difficult to update in the future if external hardware starts depending on details of the protocol, as firmware updates are generally slower/more difficult than software updates.

I would recommend that you create a program that connects to MAME’s network output module and converts the data to whatever format it is that your serial attached device requires.

**Comment by stonedDiscord** [comment]
That makes sense.
For reference I'll list how the same thing can be achieved with the network module on Linux

```
stty -F /dev/ttyUSB0 115200
mame -output network
netcat 127.0.0.1 8000 </dev/ttyUSB0 >/dev/ttyUSB0
```
