### ISSUE TITLE
AVR timers are not optimally implemented

### ISSUE THREAD

**Issue by rb6502** [mamedev/mame#11519]
### MAME version

0.258

### System information

N/A

### INI configuration details

```INI
N/A
```

### Emulated system/software

uzebox

### Incorrect behaviour

Performance is bad even on fast systems, and a profile shows a majority of the time in timer handlers.

### Expected behaviour

Performance is better.

### Steps to reproduce

mame uzebox frogger

### Additional details

N/A

**Comment by MooglyGuy** [comment]
Interacting with this issue so that it can be assigned to me.

**Comment by rb6502** [comment]
Fixed in https://github.com/mamedev/mame/commit/b774bb28849fe2e103902bf75456d8c415312283
