### ISSUE TITLE
Gloc and Strike Fighter Access Violating

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#11535]
### MAME version

0.258 (mame0258-108-gfb41bfa099f)

### System information

Windows 11 Pro x64 22H2 OS Build 22621.2215
i7-12700K @ 5.2Ghz
64GB DDR5 RAM
3 x 2TB Samsung 980 Pro NVMe in RAID-0
AMD Radeon 5600XT 23.8.2

### INI configuration details

```INI
None necessary, can use -norc
```

### Emulated system/software

sega/segaybd.cpp, gloc and strkfgtr

### Incorrect behaviour

Launching games causes access violation and quit.

c:\O\Games\MAME>mame gloc

-----------------------------------------------------
Exception at EIP=00007ff74db7f0e4 (not found): ACCESS VIOLATION
While attempting to read memory at 000000000000002c
-----------------------------------------------------
RAX=0000000000000000 RBX=000002b6dedcf9f0 RCX=0000000000000000 RDX=000000bf066f9428
RSI=000000bf066f9440 RDI=000000bf066f9428 RBP=00007ff74db83a10 RSP=000000bf066f9400
 R8=000002b6dedcf9f0  R9=0000000000000040 R10=0000000000000000 R11=60ca0e0feffcbf01
R12=000000bf066f9650 R13=000000bf066f9648 R14=0000000000000001 R15=000000bf066f9b60
-----------------------------------------------------
Stack crawl:
  000000bf066f9490: 00007ff74db7f0e4 (not found)
  000000bf066f94d0: 00007ff74ef72b2c (not found)
  000000bf066f9610: 00007ff74ef95328 (not found)
  000000bf066f9760: 00007ff74f12b13a (not found)
  000000bf066f9880: 00007ff74f12f1d1 (not found)
  000000bf066f9a00: 00007ff74f13255c (not found)
  000000bf066fef30: 00007ff7526a191c (not found)
  000000bf066ff320: 00007ff75663be7a (not found)
  000000bf066ff630: 00007ff75663c4aa (not found)
  000000bf066ff690: 00007ff75269c6c7 (not found)
  000000bf066ffa50: 00007ff75819440a (luaopen_lfs+0xb8532a)
  000000bf066ffaa0: 00007ff74aab12ee (not found)
  000000bf066ffad0: 00007ff74aab1406 (not found)
  000000bf066ffb00: 00007ffea903257d (BaseThreadInitThunk+0x001d)
  000000bf066ffb80: 00007ffeaa7caa68 (RtlUserThreadStart+0x0028)

### Expected behaviour

No AV.

### Steps to reproduce

1. mame.exe gloc -norc
2. mame.exe strkfgtr -norc
3. Observe crash

### Additional details

Seen on multiple machines from personal nightly build.
Regression from .258
Repro'ed on CI Windows binary / Actions https://github.com/mamedev/mame/actions/runs/6116621503

**Comment by happppp** [comment]
@Osso13 this is because init_gloc sets outputs before machine_start where outputs are resolved.

**Comment by Osso13** [comment]
thanks, I'll use device_resolve_objects() instead of machine_start()
