### ISSUE TITLE
MC6847 VDG and screen rapidly drift out of sync (coco)

### ISSUE THREAD

**Issue by dave-br** [mamedev/mame#11567]
### MAME version

0.251, still occurs in my fork from around Sep 22 2023 / c92ee7270bddda658bfd165cc15520a76839f488

### System information

Windows 10 x64, Intel Core i5-4690 @ 3.5Ghz, Intel HD Graphics 4600.  English US

### INI configuration details

```INI
#
# CORE CONFIGURATION OPTIONS
#
readconfig                1
writeconfig               0

#
# CORE SEARCH PATH OPTIONS
#
homepath                  .
rompath                   roms
hashpath                  hash
samplepath                samples
artpath                   artwork
ctrlrpath                 ctrlr
inipath                   .;ini;ini/presets
fontpath                  .
cheatpath                 cheat
crosshairpath             crosshair
pluginspath               plugins
languagepath              language
swpath                    software

#
# CORE OUTPUT DIRECTORY OPTIONS
#
cfg_directory             cfg
nvram_directory           nvram
input_directory           inp
state_directory           sta
snapshot_directory        snap
diff_directory            diff
comment_directory         comments
share_directory           share

#
# CORE STATE/PLAYBACK OPTIONS
#
state                     
autosave                  0
rewind                    0
rewind_capacity           100
playback                  
record                    
exit_after_playback       0
mngwrite                  
aviwrite                  
wavwrite                  
snapname                  %g/%i
snapsize                  auto
snapview                  auto
snapbilinear              1
statename                 %g
burnin                    0

#
# CORE PERFORMANCE OPTIONS
#
autoframeskip             0
frameskip                 0
seconds_to_run            0
throttle                  1
sleep                     1
speed                     1.0
refreshspeed              0
lowlatency                0

#
# CORE RENDER OPTIONS
#
keepaspect                1
unevenstretch             1
unevenstretchx            0
unevenstretchy            0
autostretchxy             0
intoverscan               0
intscalex                 0
intscaley                 0

#
# CORE ROTATION OPTIONS
#
rotate                    1
ror                       0
rol                       0
autoror                   0
autorol                   0
flipx                     0
flipy                     0

#
# CORE ARTWORK OPTIONS
#
artwork_crop              0
fallback_artwork          
override_artwork          

#
# CORE SCREEN OPTIONS
#
brightness                1.0
contrast                  1.0
gamma                     1.0
pause_brightness          0.65
effect                    none

#
# CORE VECTOR OPTIONS
#
beam_width_min            1.0
beam_width_max            1.0
beam_dot_size             1.0
beam_intensity_weight     0
flicker                   0

#
# CORE SOUND OPTIONS
#
samplerate                48000
samples                   1
volume                    0
compressor                1
speaker_report            0

#
# CORE INPUT OPTIONS
#
coin_lockout              1
ctrlr                     
mouse                     0
joystick                  1
lightgun                  0
multikeyboard             0
multimouse                0
steadykey                 0
ui_active                 0
offscreen_reload          0
joystick_map              auto
joystick_deadzone         0.3
joystick_saturation       0.85
natural                   0
joystick_contradictory    0
coin_impulse              0

#
# CORE INPUT AUTOMATIC ENABLE OPTIONS
#
paddle_device             keyboard
adstick_device            keyboard
pedal_device              keyboard
dial_device               keyboard
trackball_device          keyboard
lightgun_device           keyboard
positional_device         keyboard
mouse_device              mouse

#
# CORE DEBUGGING OPTIONS
#
verbose                   0
log                       0
oslog                     0
debug                     0
update_in_pause           0
debugscript               
debuglog                  0

#
# CORE COMM OPTIONS
#
comm_localhost            0.0.0.0
comm_localport            15112
comm_remotehost           127.0.0.1
comm_remoteport           15112
comm_framesync            0

#
# CORE MISC OPTIONS
#
drc                       1
drc_use_c                 0
drc_log_uml               0
drc_log_native            0
bios                      
cheat                     0
skip_gameinfo             1
uifont                    default
ui                        cabinet
ramsize                   
confirm_quit              0
ui_mouse                  1
language                  
nvram_save                1

#
# SCRIPTING OPTIONS
#
autoboot_command          
autoboot_delay            0
autoboot_script           
console                   0
plugins                   1
plugin                    
noplugin                  

#
# HTTP SERVER OPTIONS
#
http                      0
http_port                 8080
http_root                 web

#
# OSD KEYBOARD MAPPING OPTIONS
#
uimodekey                 auto

#
# OSD FONT OPTIONS
#
uifontprovider            auto

#
# OSD OUTPUT OPTIONS
#
output                    auto

#
# OSD INPUT OPTIONS
#
keyboardprovider          auto
mouseprovider             auto
lightgunprovider          auto
joystickprovider          auto

#
# OSD DEBUGGING OPTIONS
#
debugger                  auto
debugger_port             23946
debugger_font             auto
debugger_font_size        0
watchdog                  0

#
# OSD PERFORMANCE OPTIONS
#
numprocessors             auto
bench                     0

#
# OSD VIDEO OPTIONS
#
video                     auto
numscreens                1
window                    1
maximize                  1
waitvsync                 0
syncrefresh               0
monitorprovider           auto

#
# OSD PER-WINDOW VIDEO OPTIONS
#
screen                    auto
aspect                    auto
resolution                auto
view                      auto
screen0                   auto
aspect0                   auto
resolution0               auto
view0                     auto
screen1                   auto
aspect1                   auto
resolution1               auto
view1                     auto
screen2                   auto
aspect2                   auto
resolution2               auto
view2                     auto
screen3                   auto
aspect3                   auto
resolution3               auto
view3                     auto

#
# OSD FULL SCREEN OPTIONS
#
switchres                 0

#
# OSD ACCELERATED VIDEO OPTIONS
#
filter                    1
prescale                  1

#
# OpenGL-SPECIFIC OPTIONS
#
gl_forcepow2texture       0
gl_notexturerect          0
gl_vbo                    1
gl_pbo                    1
gl_glsl                   0
gl_glsl_filter            1
glsl_shader_mame0         none
glsl_shader_mame1         none
glsl_shader_mame2         none
glsl_shader_mame3         none
glsl_shader_mame4         none
glsl_shader_mame5         none
glsl_shader_mame6         none
glsl_shader_mame7         none
glsl_shader_mame8         none
glsl_shader_mame9         none
glsl_shader_screen0       none
glsl_shader_screen1       none
glsl_shader_screen2       none
glsl_shader_screen3       none
glsl_shader_screen4       none
glsl_shader_screen5       none
glsl_shader_screen6       none
glsl_shader_screen7       none
glsl_shader_screen8       none
glsl_shader_screen9       none

#
# OSD SOUND OPTIONS
#
sound                     auto
audio_latency             2

#
# PORTAUDIO OPTIONS
#
pa_api                    none
pa_device                 none
pa_latency                0

#
# BGFX POST-PROCESSING OPTIONS
#
bgfx_path                 bgfx
bgfx_backend              auto
bgfx_debug                0
bgfx_screen_chains        default
bgfx_shadow_mask          slot-mask.png
bgfx_lut                  lut-default.png
bgfx_avi_name             auto

#
# WINDOWS PERFORMANCE OPTIONS
#
priority                  0
profile                   0

#
# WINDOWS VIDEO OPTIONS
#
menu                      0
attach_window             

#
# DIRECT3D POST-PROCESSING OPTIONS
#
hlslpath                  hlsl
hlsl_enable               0
hlsl_oversampling         0
hlsl_write                auto
hlsl_snap_width           2048
hlsl_snap_height          1536
shadow_mask_tile_mode     0
shadow_mask_alpha         0.0
shadow_mask_texture       shadow-mask.png
shadow_mask_x_count       6
shadow_mask_y_count       4
shadow_mask_usize         0.1875
shadow_mask_vsize         0.25
shadow_mask_uoffset       0.0
shadow_mask_voffset       0.0
distortion                0.0
cubic_distortion          0.0
distort_corner            0.0
round_corner              0.0
smooth_border             0.0
reflection                0.0
vignetting                0.0
scanline_alpha            0.0
scanline_size             1.0
scanline_height           1.0
scanline_variation        1.0
scanline_bright_scale     1.0
scanline_bright_offset    0.0
scanline_jitter           0.0
hum_bar_alpha             0.0
defocus                   0.0,0.0
converge_x                0.0,0.0,0.0
converge_y                0.0,0.0,0.0
radial_converge_x         0.0,0.0,0.0
radial_converge_y         0.0,0.0,0.0
red_ratio                 1.0,0.0,0.0
grn_ratio                 0.0,1.0,0.0
blu_ratio                 0.0,0.0,1.0
saturation                1.0
offset                    0.0,0.0,0.0
scale                     1.0,1.0,1.0
power                     1.0,1.0,1.0
floor                     0.0,0.0,0.0
phosphor_life             0.0,0.0,0.0
chroma_mode               3
chroma_conversion_gain    0.299,0.587,0.114
chroma_a                  0.64,0.33
chroma_b                  0.30,0.60
chroma_c                  0.15,0.06
chroma_y_gain             0.2126,0.7152,0.0722

#
# NTSC POST-PROCESSING OPTIONS
#
yiq_enable                0
yiq_jitter                0.0
yiq_cc                    3.57954545
yiq_a                     0.5
yiq_b                     0.5
yiq_o                     0.0
yiq_p                     1.0
yiq_n                     1.0
yiq_y                     6.0
yiq_i                     1.2
yiq_q                     0.6
yiq_scan_time             52.6
yiq_phase_count           2

#
# VECTOR POST-PROCESSING OPTIONS
#
vector_beam_smooth        0.0
vector_length_scale       0.5
vector_length_ratio       0.5

#
# BLOOM POST-PROCESSING OPTIONS
#
bloom_blend_mode          0
bloom_scale               0.0
bloom_overdrive           1.0,1.0,1.0
bloom_lvl0_weight         1.0
bloom_lvl1_weight         0.64
bloom_lvl2_weight         0.32
bloom_lvl3_weight         0.16
bloom_lvl4_weight         0.08
bloom_lvl5_weight         0.06
bloom_lvl6_weight         0.04
bloom_lvl7_weight         0.02
bloom_lvl8_weight         0.01
lut_texture               lut-default.png
lut_enable                0
ui_lut_texture            lut-default.png
ui_lut_enable             0

#
# FULL SCREEN OPTIONS
#
triplebuffer              0
full_screen_brightness    1.0
full_screen_contrast      1.0
full_screen_gamma         1.0

#
# INPUT DEVICE OPTIONS
#
global_inputs             0
dual_lightgun             0
```

### Emulated system/software

coco + MC6847 VDG

### Incorrect behaviour

The vertical position of the screen and the physical scanline of the MC6847 video display generator drift out of sync further and further every few frames.

The MAME debugger beamy therefore varies.  About every 3 frames (3 hits of F7), beamy goes up by one, through the entire range of vertical positions.

### Expected behaviour

The MAME debugger's beamy (screen's vertical position) should show approximately 243 every time.

### Steps to reproduce

Run MAME with the coco machine and the MAME debugger (6809 CPU).  
Repeatedly do "Debug > Run until Next Interrupt on this CPU" (F7) and look at beamy.
(The interrupt is the vsync / fsync on the coco.)

### Additional details

** ANOTHER SYMPTOM **

Run with the the logging line I added in the commit linked below (mc6847.cpp, bottom of mc6847_friend_device::next_scanline), which prints the screen's vpos and the MC6847's m_physical_scanline each time m_physical_scanline increments, and shows them going out of sync further and further every few frames.

** THE PROBLEM   **

The code seems to ignore horizontal blanking, which leads to round-off error.  It sets the screen width to equal the visible width (320 pixels).  As a result, there are many more m_physical_scanline values (1-262) than there are screen vpos values (0-242).  This causes the m_physical_scanline variable to increase at a faster rate than vpos, so that m_physical_scanline & vpos can kind of sync up by the end of the frame, but not enough to avoid drift.

** ATTEMPTED FIX **

Full disclosure: I am not a hardware person and don't know the MAME code base.  I'm a CoCo enthusiast with a 6847 data sheet (which I only partially understand): https://colorcomputerarchive.com/repo/Documents/Datasheets/MC6847%20MOS%20Video%20Display%20Generator%20(Motorola).pdf.

This commit does not fix the problem, but does slow the drift somewhat.  Rather than drifting one scanline per 3 frames, it now drifts 1 scanline per 6 frames:
https://github.com/dave-br/mame/commit/68dec097284f26d967f9db7a8a63649df294b992

My "fix" takes into account the horizontal blanking / retrace period.  According to the data sheet, the horizontal line has a total of 227.5 clock cycles.  The visible area consists of borders (top/bottom, left/right) plus the active area (traditional graphics / text screen).
Active + border = 185.5 clock cycles
This leaves 227.5-185.5=42 clock cycles for horizontal retracing / blanking.  Two things complicate matters.  (1) MC6847.cpp quite intentionally diverges from the data sheet to do 228 (instead of 227.5) clock cycles per horizontal line based on empirical evidence. (2) MC6847.cpp uses 320 pixels for the active area width (32 left border + 256 active area + 32 right border).  I'm not saying either of these is wrong.  But (1) makes the math a bit confusing, and (2) limits what I can do with a screen().set_raw() call from within mc6847_base_device::device_config_complete().  (256 active area pixel width is absolutely correct from a CoCo user point of view, btw.)

The reason there is still a drift with my pseudo-fix is surely round-off error.  Also, I doubt you would want to accept a change that does this bizarre scaling: (u32) (m_clock * 1.72043).

Are there better ways to scale the clock?  An entirely different direction I should try?  I'll happily try out suggestions with the hope of providing you a real pull request.

**Comment by angelosa** [comment]
I suspect there's a drift in your code because beamx/beamy are integers while the device file also sets up floating point variables thru the timer callbacks. Reading former is doable thru `screen().hpos()` / `screen().vpos()` getters, making latter to work reliably is more complicated and requires non-trivial framework mods.

**Comment by angelosa** [comment]
Having said this, if you have exact measurements of the full 6847 screen frame lifecycle (sync/visible/back and front porch) we can calculate the htotal / vtotal and have a better approximation compared to the ugly hack it currently lies in the device.

**Comment by dave-br** [comment]
Thanks for the comments.  I get that hpos/vpos are integers.  When you say "device file also sets up floating point variables thru the timer callbacks".  Are you referring to code like this in mc6847.cpp:

#define TIMER_HSYNC_ON_TIME     (TIMER_HSYNC_OFF_TIME + 16.5)
...
m_hsync_on_timer->adjust(clocks_to_attotime(TIMER_HSYNC_ON_TIME * m_divider), 1, clocks_to_attotime(TIMER_HSYNC_PERIOD * m_divider));

Are you recommending that floats should be removed entirely from the timer adjustments to ensure accuracy?

I personally don't know how to measure anything.  :-)  I have been reading through the 6847 data sheet:
https://colorcomputerarchive.com/repo/Documents/Datasheets/MC6847%20MOS%20Video%20Display%20Generator%20(Motorola).pdf

and I see:

horz sync rise delay: 740ns
horz sync fall delay: 550ns
field sync rise delay: 600ns
field sync fall delay: 520ns
horz sync rise time: 100ns
horz sync fall time: 100ns
horz blanking rise time: 100ns
horz blanking fall time: 100ns
front porch duration: 7 1/f, min 1.8 microseconds, max 2.4 microseconds
back porch duration: 17.5 1/f, min 4.5 microseconds, max 5.1 microseconds
left border duration: 29.5 1/f, min 7.5 microseconds, max 8.3 microseconds
right border duration: 28 1/f, min 7.5 microseconds, max 8.3 microseconds
active video (minus borders): 128 1/f
visible = borders + active
(I think "1/f" means clock cycles per frame?)

I'm quite out of my element, though.  I don't know exactly which numbers to combine and how, in order to get the full picture.  Also, the original authors of mc6847.cpp dispute some of these numbers: the data sheet numbers somehow add up to 227.5 for "tPHS" (which I believe is the total time for a horizontal line), whereas mc6847.cpp authors measured 228 instead.  Don't know how that should affect any recalculations.  My pseudo-fix was my best attempt at combining these numbers & reconciling with the existing code, and just wasn't good enough.

As a completely different approach, I did notice screen_device::reset_origin which seemed to be a way to repeatedly hold drift at bay if called properly each frame.  But it didn't seem like it was used much by anyone, so I don't know it using screen_device::reset_origin to solve the drift would be something you folks would frown on.  Personally, if we end up with something that completely syncs up 6847 and screen, and is "approximately" correct wrt to the 6847 hardware, I'd declare that as a success.

How best to proceed?

**Comment by rb6502** [comment]
Typically screen timings are expressed in terms of the pixel clock rate in Hz, the number of clocks per scanline (including the blanking area), and then the number of scanlines per frame.  Usually on 8-bit micros the pixel clock rate is some multiple of the CPU clock and that's how you can cycle-sync the processor and screen.  (The Apple II does exactly that in MAME and can run raster-sync demos).

**Comment by dave-br** [comment]
@rb6502 Thanks!  Your comment helped confirm for me what I suspected was true, but I wasn't certain yet.  I went back and found a more sensible multiplier for the clock.  This necessitated making a small change to the border sizes, but the screen & VDG appear permanently in sync now.  I will clean things up and come up with a pull request.
