### ISSUE TITLE
Compilation error (Gentoo, mame 0.254)

### ISSUE THREAD

**Issue by Silence-Williams** [mamedev/mame#11565]
### MAME version

0.254

### System information

Hello,
I am trying to build the latest mame 0.254 from source on Gentoo.

I tried to compile using this and I found this error where it halts at **liboptional.a**.  [This reddit post ](https://www.reddit.com/r/MAME/comments/ux6xqh/mame_0244/i9x8kqh/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)is the only mention I could find of the compiler halting on liboptional.a, except it doesn't help me because:

1. That user is compiling mame 0.244
2. I applied -U_FORTIFY_SOURCE and it did not resolve the issue
3. `#include <cstddef>` is not missing from mame 0.254's src/lib/netlist/plib/ppmf.h like it is for that user.
4. That user is using an older version of Manjaro and I am on Gentoo (Shouldn't matter)

Below is the tail end of the log where compile repeatedly crashes. You can see I am building with the options `-march=haswell -O2 -pipe -U_FORTIFY_SOURCE`.    Is `../../../../linux_gcc/bin/x64/Release/mame_mame/`  seen at the end of the error a valid path?

```                                                                                   
x86_64-pc-linux-gnu-g++ -march=haswell -O2 -pipe -U_FORTIFY_SOURCE -march=haswell -O2 -pipe -U_FORTIFY_SOURCE  -MMD -MP -MP -DPTR64=
1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DU
SE_OPENMP=1 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/lib" -I"../..
/../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../generated/emu" -I"../../../../generated/emu/layout" -I"../../../.
./../scripts"  -m64 -std=c++17 -pipe -O3 -fno-strict-aliasing -fopenmp -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings 
-Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-error=unused-result -Wno-array-bounds -Wno-error=attribute
s -Wno-stringop-truncation -Wno-stringop-overflow -Wno-nonnull -Wno-stringop-overread -Wno-error=maybe-uninitialized -Wno-error=unin
itialized -m64 -std=c++17 -Woverloaded-virtual -Wvla -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -include ../../.
./../linux_gcc/obj/x64/Release/emu.h -o "../../../../linux_gcc/obj/x64/Release/src/devices/video/voodoo_render.o" -c "../../../../..
/src/devices/video/voodoo_render.cpp"                                                                                               
Archiving liboptional.a...                                                                                                          
rm -f "../../../../linux_gcc/bin/x64/Release/mame_mame/liboptional.a"    
x86_64-pc-linux-gnu-ar  -cs ../../../../linux_gcc/bin/x64/Release/mame_mame/liboptional.a  
 * ERROR: games-emulation/sdlmame-0.258::local failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=games-emulation/sdlmame-0.258::local'`,
 * the complete build log and the output of `emerge -pqv '=games-emulation/sdlmame-0.258::local'`.
 * The complete build log is located at '/var/tmp/portage/games-emulation/sdlmame-0.258/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-emulation/sdlmame-0.258/temp/environment'.
 * Working directory: '/var/tmp/portage/games-emulation/sdlmame-0.258/work/mame-mame0258'
 * S: '/var/tmp/portage/games-emulation/sdlmame-0.258/work/mame-mame0258'

>>> Failed to emerge games-emulation/sdlmame-0.258

```
The **emake failed** at the end is not indicating a Gentoo specific problem, rather simply that a major error occurred in compilation. 

Original URL for the ebuild I am using: https://data.gpo.zugaina.org/salfter/games-emulation/sdlmame/sdlmame-0.258.ebuild

There is a common used ebuild file to provide context for building the source, but it may have other issues because the URL structure is incorrect in it.  (line 9, the URL to download the mame tar.gz from github is wrong). Besides that the build should work. If anyone has a suggestion on a different way to compile please let me know.

The ebuild is hosted from github here, with .txt appended, 
[sdlmame-0.258.ebuild.txt](https://github.com/mamedev/mame/files/12684835/sdlmame-0.258.ebuild.txt)

### Incorrect behaviour

Failure to compile from source

### Expected behaviour

One would hope the software compiles

**Comment by Silence-Williams** [comment]
Relevant /var/tmp/portage/games-emulation/sdlmame-0.258/temp/build.log
[build.log.txt](https://github.com/mamedev/mame/files/12685159/build.log.txt)

**Comment by Silence-Williams** [comment]
Relevant /var/tmp/portage/games-emulation/sdlmame-0.258/temp/environment
[environment.txt](https://github.com/mamedev/mame/files/12685180/environment.txt)

**Comment by Silence-Williams** [comment]
Attaching the last bits for support purposes even though these are Gentoo specific. 

Here is the output of `emerge --info '=games-emulation/sdlmame-0.258::local'`: [info.txt](https://github.com/mamedev/mame/files/12685255/info.txt)

The output of the output of `emerge -pqv '=games-emulation/sdlmame-0.258::local'` (do not worry about the 1st line warning about config files, it is not related to this issue)
```
 * IMPORTANT: 7 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.
[ebuild  N    ] games-emulation/sdlmame-0.258  USE="alsa opengl openmp -debug -tools" 

 * IMPORTANT: 12 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

```

**Comment by startaq** [comment]
Here's your error hiding:

```Compiling src/osd/modules/sound/pulse_sound.cpp...
x86_64-pc-linux-gnu-g++ -march=haswell -O2 -pipe -U_FORTIFY_SOURCE -march=haswell -O2 -pipe -U_FORTIFY_SOURCE  -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUSE_OPENMP=1 -DUSE_NETWORK -DOSD_NET_USE_TAPTUN -D'INI_PATH="$HOME/.sdlmame;/etc/sdlmame"' -DSDLMAME_X11 -DUSE_XINPUT=1 -DUSE_XINPUT_DEBUG=0 -DUSE_XINPUT_WII_LIGHTGUN_HACK=0 -DSDLMAME_SDL2=1 -DOSD_SDL -DSDLMAME_UNIX -DUSE_OPENGL=1 -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DBX_CONFIG_DEBUG=0 -DUSE_QTDEBUG=0 -I"../../../../../../../../../../../../usr/X11/include" -I"../../../../../../../../../../../../usr/X11R6/include" -I"../../../../../../../../../../../../usr/openwin/include" -I"../../../../../src/osd" -I"../../../../../scripts/src/osd" -I"../../../../../3rdparty/bgfx/examples/common" -I"../../../../../3rdparty/bgfx/include" -I"../../../../../3rdparty/bgfx/3rdparty" -I"../../../../../3rdparty/bgfx/3rdparty/khronos" -I"../../../../../3rdparty/bx/include" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/lib" -I"../../../../../src/lib/util" -I"../../../../../src/osd/modules/file" -I"../../../../../src/osd/modules/render" -I"../../../../../3rdparty" -I"../../../../../src/osd/sdl"  -m64 -std=c++17 -pipe -O3 -fno-strict-aliasing -fopenmp -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-error=unused-result -Wno-array-bounds -Wno-error=attributes -Wno-stringop-truncation -Wno-stringop-overflow -Wno-nonnull -Wno-stringop-overread -Wno-error=maybe-uninitialized -Wno-error=uninitialized -m64  -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/qt5 -std=c++17 -Woverloaded-virtual -Wvla -Wimplicit-fallthrough -Wno-class-memaccess -include /var/tmp/portage/games-emulation/sdlmame-0.258/work/mame-mame0258/src/osd/sdl/sdlprefix.h -o "../../../../linux_gcc/obj/x64/Release/osd_sdl/src/osd/modules/sound/pulse_sound.o" -c "../../../../../src/osd/modules/sound/pulse_sound.cpp"
../../../../../src/osd/modules/sound/pulse_sound.cpp:25:10: fatal error: pulse/pulseaudio.h: No such file or directory
   25 | #include <pulse/pulseaudio.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [osd_sdl.make:1344: ../../../../linux_gcc/obj/x64/Release/osd_sdl/src/osd/modules/sound/pulse_sound.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Looks like missing pulse audio library header.

See MAME documentation: https://docs.mamedev.org/initialsetup/compilingmame.html#arch-linux

There is no Gentoo section, but as you can see, `libpulse` is being installed.

**Comment by Silence-Williams** [comment]
> Here's your error hiding:
> 
> ```
> x86_64-pc-linux-gnu-g++ -march=haswell -O2 -pipe -U_FORTIFY_SOURCE -march=haswell -O2 -pipe -U_FORTIFY_SOURCE  -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUSE_OPENMP=1 -DUSE_NETWORK -DOSD_NET_USE_TAPTUN -D'INI_PATH="$HOME/.sdlmame;/etc/sdlmame"' -DSDLMAME_X11 -DUSE_XINPUT=1 -DUSE_XINPUT_DEBUG=0 -DUSE_XINPUT_WII_LIGHTGUN_HACK=0 -DSDLMAME_SDL2=1 -DOSD_SDL -DSDLMAME_UNIX -DUSE_OPENGL=1 -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DBX_CONFIG_DEBUG=0 -DUSE_QTDEBUG=0 -I"../../../../../../../../../../../../usr/X11/include" -I"../../../../../../../../../../../../usr/X11R6/include" -I"../../../../../../../../../../../../usr/openwin/include" -I"../../../../../src/osd" -I"../../../../../scripts/src/osd" -I"../../../../../3rdparty/bgfx/examples/common" -I"../../../../../3rdparty/bgfx/include" -I"../../../../../3rdparty/bgfx/3rdparty" -I"../../../../../3rdparty/bgfx/3rdparty/khronos" -I"../../../../../3rdparty/bx/include" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/lib" -I"../../../../../src/lib/util" -I"../../../../../src/osd/modules/file" -I"../../../../../src/osd/modules/render" -I"../../../../../3rdparty" -I"../../../../../src/osd/sdl"  -m64 -std=c++17 -pipe -O3 -fno-strict-aliasing -fopenmp -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-error=unused-result -Wno-array-bounds -Wno-error=attributes -Wno-stringop-truncation -Wno-stringop-overflow -Wno-nonnull -Wno-stringop-overread -Wno-error=maybe-uninitialized -Wno-error=uninitialized -m64  -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/qt5 -std=c++17 -Woverloaded-virtual -Wvla -Wimplicit-fallthrough -Wno-class-memaccess -include /var/tmp/portage/games-emulation/sdlmame-0.258/work/mame-mame0258/src/osd/sdl/sdlprefix.h -o "../../../../linux_gcc/obj/x64/Release/osd_sdl/src/osd/modules/sound/pulse_sound.o" -c "../../../../../src/osd/modules/sound/pulse_sound.cpp"
> ../../../../../src/osd/modules/sound/pulse_sound.cpp:25:10: fatal error: pulse/pulseaudio.h: No such file or directory
>    25 | #include <pulse/pulseaudio.h>
>       |          ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [osd_sdl.make:1344: ../../../../linux_gcc/obj/x64/Release/osd_sdl/src/osd/modules/sound/pulse_sound.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ```
> 
> Looks like missing pulse audio library header.
> 
> See MAME documentation: https://docs.mamedev.org/initialsetup/compilingmame.html#arch-linux
> 
> There is no Gentoo section, but as you can see, `libpulse` is being installed.

Thank you, @startaq !! 
Certainly, I missed that detail when I was spending all day trying to realize what caused the issues.
I am running a pulseaudio-free system, so I added to the ebuild file the following line:  `enable_feature NO_USE_PULSEAUDIO`
and it finished compiling, works fine.

Many thanks again to you.
