### ISSUE TITLE
Neo Geo CD in CHD does not work in MAME

### ISSUE THREAD

**Issue by carlosgamer23** [mamedev/mame#11579]
### MAME version

0.259

### System information

Windows 10 64 bits (I have enough to use MAME, don't worry)

### Incorrect behaviour

OFFICIAL MAME does not start ROMs in CHD on the Neo Geo CD, even though it has the bios and the entire ROM directory organized in the emulator.

### Expected behaviour

Using MAMEUI it is possible to use the Neo Geo CD in CHD, selecting the game through the bios, so the question is... the official MAME does not do what a clone does, although it is not as pleasant to have to open the bios to open the game, but at least it's something... I would also like it to be possible to access these Neo Geo CD games via command line, something that would really help those who use the frontend, and as it is necessary to access the bios to open the game, it is impossible to make this happen.

**Comment by FoxhackDN** [comment]
What version of the NeoGeo CD are you using? Cuz the only one that works is the NeoCDZ.

**Comment by carlosgamer23** [comment]
558

> What version of the NeoGeo CD are you using? Cuz the only one that works is the NeoCDZ. The original NeoGeo CD doesn't work, the bios boots but it can't play games.
> 
> For your other question, you can start the games via the command line with the following:
> 
> `mame neocdz (setname)`
> 
> So `mame neocdz aof2` would boot Art of Fighting 2.

I use the same neocdz, in MAMEUI I can also open it using neocdzj (I believe that the emulator transfers neocdz's work to neocdz when starting, but in any case I can also open it through it). I know this command line, but for those who have a list of 11 neocd games, it is not useful, as it only directs to a single game, I tested it on several frontends and was not successful with any command (at least not for open more than one game automatically)

**Comment by rb6502** [comment]
All of the Neo CDs take 1 disc, there is no such thing as multiple discs in a Neo CD the way you can have multiple cartridges in the AES.

**Comment by carlosgamer23** [comment]
> Todos os CDs Neo levam 1 disco, não existem vários discos em um CD Neo da mesma forma que você pode ter vários cartuchos no AES.

The question itself would be the possibility of the emulator switching the rom, rewriting the previous rom in the ini file, for example: I was playing ADK World and switched to Cyber ​​Lip, so the emulator rewrites the ini from the moment I open another game, inside MAMEUI this happens, but outside of it, using a frontend is totally hopeless... Honestly, if these versions of MAME came with frontends like those of PCSX2/DuckStation or PPSSPP, I wouldn't even use external frontends, but they won't change the appearance of MAME TO THIS DAY, MAME is an incredible work for those who already have knowledge, but for beginners it is VERY complicated, as the interface is not so intuitive (I say this with all the respect I have for the project, but it is time to update his appearance)

**Comment by angelosa** [comment]
I'm pretty sure you can do this with a LUA script in the same way that is possible with floppy disk swaps (or, put in another way, I never tried with CD-ROMs but pretty sure it's doable). You just need a way to call the script externally:

https://docs.mamedev.org/luascript/ref-devices.html#image-device-interface

MAME disc tray open/close handling is otherwise kinda goofy but this doesn't look the place to talk about it.

**Comment by carlosgamer23** [comment]
> Sim, isso não é problema. Típica pessoa com CAPS SUPER EXCITADOS SEM MOTIVO, agindo como se soubesse tudo sobre tudo. Feche e tranque, por favor.

If it works in MAMEUI and not in OFFICIAL, it's a problem haha, since it only changes the interface of the projects.

**Comment by angelosa** [comment]
No, it's because MAMEUI is a FRONTEND of MAME, my original point stands, locking here.
