### ISSUE TITLE
All Atari 5200 games fail to start

### ISSUE THREAD

**Issue by Ziggy57** [mamedev/mame#11589]
### MAME version

0.259

### System information

Windows 11, 64-bit, version 22H2, US English
32GB system RAM, GeForce RTX 3070ti driver version 537.34

### INI configuration details

```INI
Using default mame.ini with no modifications
```

### Emulated system/software

Atari 5200 (a5200)

### Incorrect behaviour

None of the Atari 5200 games can be started using start button (keyboard "1" or joystick button 1).

### Expected behaviour

Atari 5200 games should start when pressing start button (keyboard "1" or joystick button 1).

### Steps to reproduce

1) Run an Atari 5200 game such as Pitfall 2 using MAME 0.259. Example: "mame a5200 pitfall2".
2) Press keyboard button "1" or joystick button 1 to start game.
3) Game does not start as expected.

### Additional details

This problem started with MAME 0.253 and has been broken since then.  Everything works as expected using MAME 0.252 and older.

**Comment by ajrhacker** [comment]
e22d8e8ad6650bc54bdb62cb2e4e6becb84746eb fixes this regression. b7b114c525bd0b66cfcd78ca89b2161a746a8858 is an additional fix for some games. Many 5200 games are still crashing due to POKEY IRQ glitches.
