### ISSUE TITLE
Marble Madness reports incorrect checksum on 136032.105.l13

### ISSUE THREAD

**Issue by StarPlayrX** [mamedev/mame#11645]
### MAME version

0.259 / Master

### System information

Ubuntu Lunar running on Atari VCS Hardware.

   
  I am attempting to update the CRC and SHA1 to 
  CRC(690b37d3)
  SHA1(547372f1044a3442aa52fcd2b3546540aba59344)
  
  recompiling will see if it runs. 

### Emulated system/software

Atari System 1 / Marble Madness

### Incorrect behaviour

System media audit failed:
136032.105.l13 (16384 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(79021d3c) SHA1(85febd34bcb166fc3326b5e5e4e80e157b660a08)
   FOUND: CRC(690b37d3)

### Expected behaviour

Checksum to match, 
Game to run

### Steps to reproduce

Installed atarisy.zip from MAME .0259 bios pack on Internet Archive

Installed Marble Madness from 2016 Non-merged set.

Compiled MAME 0.259

### Additional details

Attempting to patch the checksum to see if Marble Madness will run

**Comment by StarPlayrX** [comment]
updating the checksum works and allows marble madness to run:

From:
CRC(79021d3c)
SHA1(85febd34bcb166fc3326b5e5e4e80e157b660a08)

To
CRC(690b37d3)
SHA1(547372f1044a3442aa52fcd2b3546540aba59344)

In 
src/mame/atarisy1.cpp

**Comment by Robbbert** [comment]
The correct solution is for you to search around for the correct ROM instead of hacking the source.

**Comment by rb6502** [comment]
Your "2016 Non-merged set" likely has a corrupt or outdated version of that file that overrode the one in the 0.259 BIOS set.  This is not an error in MAME.

**Comment by StarPlayrX** [comment]
Only one rom on the source was different. 

I was unable to locate an alternate rom. 

I believe the rom checksum is incorrect as all the other checksums match in the set of about a dozen files.

**Comment by rb6502** [comment]
No, I mean if 136032.105.l13 exists in the game (marble.zip) MAME won't try the one from the BIOS.

And I promise we're looking for the correct one.

Archive:  /Volumes/roms/mame/atarisy1.zip
TORRENTZIPPED-29E853E6
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     256  Defl:X       17  93% 12-24-1996 23:32 7e84972a  136032.101.e3
     256  Defl:X       20  92% 12-24-1996 23:32 ebf1e0ae  136032.102.e5
     235  Defl:X      124  47% 12-24-1996 23:32 92d6a0b4  136032.103.f7
    8192  Defl:X     4065  50% 12-24-1996 23:32 7a29dc07  136032.104.f5
   16384  Defl:X     6969  58% 12-24-1996 23:32 79021d3c  136032.105.l13
   16384  Defl:X     9125  44% 12-24-1996 23:32 76ee86c4  136032.106.l12
    8192  Defl:X     4065  50% 12-24-1996 23:32 7a29dc07  136032.107.b2
   16384  Defl:X     7088  57% 12-24-1996 23:32 195c54ad  136032.114.j11
   16384  Defl:X     8618  47% 12-24-1996 23:32 7275b4dc  136032.115.j10
   16384  Defl:X     6971  58% 12-24-1996 23:32 88d0be26  136032.205.l13
   16384  Defl:X     9135  44% 12-24-1996 23:32 3c79ef05  136032.206.l12

**Comment by StarPlayrX** [comment]
I have the exact same bios set. 

So you are saying the same was updated in a merged set.

**Comment by StarPlayrX** [comment]
Sounds me to that the bios set should be updated l. Not every pulls games from the same set. Not everyone loads merged sets on smaller systems.

**Comment by StarPlayrX** [comment]
ok. That makes more since now.

**Comment by StarPlayrX** [comment]
The only thing the ROMs that are in my Marble Madness zip folders are have exactly the same Atarisy1.zip BIOS' with the same checksums.

You may want to double check the checksum that you have for 136032.105.l13 as I think you may have incorrect information on the src. Take the BIOS you have an compare.

**Comment by cuavas** [comment]
Your ROMs are wrong. Take it to a forum if you want to discuss it.
