### ISSUE TITLE
NES APU code has an invalid license

### ISSUE THREAD

**Issue by ndiddy99** [mamedev/mame#11659]
From the NES APU file header comment (src/devices/sound/nes_apu.cpp / nes_apu.h):

>   Based on the Nofrendo/Nosefart NES RP2A03 sound emulation core written by
>   Matthew Conte (matt@conte.com) and redesigned for use in MAME/MESS by
>   Who Wants to Know? (wwtk@mail.com)
> 
>   This core is written with the advise and consent of Matthew Conte and is
>   released under the GNU Public License.  This core is freely available for
>   use in any freeware project, subject to the following terms:
> 
>   Any modifications to this code must be duly noted in the source and
>   approved by Matthew Conte and myself prior to public submission.

From the GPLv2:

>  Each time you redistribute the Program (or any work based on the Program), the recipient automatically receives a license from the original licensor to copy, distribute or modify the Program subject to these terms and conditions. **You may not impose any further restrictions on the recipients' exercise of the rights granted herein.** You are not responsible for enforcing compliance by third parties to this License. 

I can submit a PR removing the additional restriction from the header comment if you guys want.

**Comment by qeeg** [comment]
I'm pretty sure MAME usually uses the GPLv3 since that's what the whole package is released under. Could be wrong though.

**Comment by rb6502** [comment]
The whole package of MAME is released under GPLv2, not v3, and the clause noted by the OP is incompatible with any version of the GPL.

**Comment by happppp** [comment]
The note is removed: https://github.com/mamedev/mame/commit/353633aa1d3c71fa701c93d7dd174e1dc3b1edec
