### ISSUE TITLE
CHDMAN delta creation fails silently on some CHDs

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#11675]
### MAME version

0.260 release of chdman.exe

### System information

Windows 11 Pro x64 22H2 OS Build 22621.2506
Asus ROG Strix Z690-F
Intel i7-12700K @ 5.2Ghz
Corsair 64GB 5200Mhz DDR5 RAM
6TB (3x2TB) Samsung 980 Pro NVMe in RAID-0
XFX AMD Radeon RX 5600XT 6GB
2 x Samsung G5 Odyssey 32" FreeSync Enabled 2560x1440 Fullscreen

### INI configuration details

```INI
n/a
```

### Emulated system/software

chdman

### Incorrect behaviour

During the course of working with Roman on automated handling of the delta chd creation we hit on a few candidate CHDs that won't convert.  When they're attempted with CHDMAN they get to a small percentage of examining the parent and then quit out of CHDMAN, producing a very small delta chd.

The current one I am seeing is the susume CHD.  Child of lacrazyc.
Both parent and child CHD `chdman.exe verify` correctly.
The susume CHD is marked as a baddump, unknown if that should impact the delta creation.

### Expected behaviour

Full creation of delta CHD.

### Steps to reproduce

Files are stored in merged format, both CHDs in lacrazy folder.

c:\O\Games\MAME\ROMs\lacrazyc>chdman copy -i gv027j1.chd -op gv027-a1.chd -o delta.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.260 (mame0260)
Output CHD:   delta.chd
Parent CHD:   gv027-a1.chd
Input CHD:    gv027j1.chd
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
Hunk size:    9,792
Logical size: 537,091,200
Examining parent, 0.2% complete...
--
delta.chd produced is 4K
[delta.zip](https://github.com/mamedev/mame/files/13198809/delta.zip)

**Comment by sairuk** [comment]
same operation on linux also causes issues, i intentionally skipped this chd in my internal batch run tests due to the baddump status

```
$ ~/games/emulator-mame/chdman copy -i /mnt/roms/MAME/MAME\ -\ CHDs/lacrazyc/gv027j1.chd -op /mnt/roms/MAME/MAME\ -\ CHDs/lacrazyc/gv027-a1.chd -o delta.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.260 (mame0260)
Output CHD:   delta.chd
Parent CHD:   /mnt/roms/MAME/MAME - CHDs/lacrazyc/gv027-a1.chd
Input CHD:    /mnt/roms/MAME/MAME - CHDs/lacrazyc/gv027j1.chd
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
Hunk size:    9,792
Logical size: 537,091,200
free(): invalid sizemplete... (ratio=100.0%)  
Aborted (core dumped)
```

both chds are as good as they can be, although in my case the resulting delta is garbage

```
$ ~/games/emulator-mame/chdman verify -i delta.chd -ip /mnt/roms/MAME/MAME\ -\ CHDs/lacrazyc/gv027-a1.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.260 (mame0260)
No verification to be done; CHD has no checksum
Fatal error occurred: 0
```

```
00000000: 4d43 6f6d 7072 4844 0000 007c 0000 0005  MComprHD...|....
00000010: 6364 6c7a 6364 7a6c 6364 666c 0000 0000  cdlzcdzlcdfl....
00000020: 0000 0000 2003 5c80 0000 0000 0000 0000  .... .\.........
00000030: 0000 0000 0000 007c 0000 2640 0000 0990  .......|..&@....
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 8317 a135 0def b608 77a5 dc3c  .......5....w..<

--- snip ---

00000e90: 5432 0100 005a 0000 0000 0000 0000 5452  T2...Z........TR
00000ea0: 4143 4b3a 3335 2054 5950 453a 4155 4449  ACK:35 TYPE:AUDI
00000eb0: 4f20 5355 4254 5950 453a 5257 5f52 4157  O SUBTYPE:RW_RAW
00000ec0: 2046 5241 4d45 533a 3332 3139 2050 5245   FRAMES:3219 PRE
00000ed0: 4741 503a 3020 5047 5459 5045 3a4d 4f44  GAP:0 PGTYPE:MOD
00000ee0: 4531 2050 4753 5542 3a4e 4f4e 4520 504f  E1 PGSUB:NONE PO
00000ef0: 5354 4741 503a 3000                      STGAP:0.

```

**Comment by ajrhacker** [comment]
My current CHD WIP at least reports an error halfway through the "Examining parent" phase in this case, though it doesn't fix the problem yet. The problem is that it tries to read too many hunks from a parent CHD which doesn't actually have that many.

**Comment by 987123879113** [comment]
Is this still an issue? I tried it just now on MacOS and the output is large so it doesn't seem to benefit from the delta but it does verify and has a parent SHA1 included in the info.

```
> ./chdman copy -i roms/lacrazyc/gv027j1.chd  -op roms/lacrazyc/gv027-a1.chd  -o delta.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.262 (mame0252-3490-g0636e54bb60)
Output CHD:   delta.chd
Parent CHD:   /Users/owner/Downloads/MAME 0.260 CHDs (merged)/lacrazyc/gv027-a1.chd
Input CHD:    /Users/owner/Downloads/MAME 0.260 CHDs (merged)/lacrazyc/gv027j1.chd
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
Hunk size:    19,584
Logical size: 537,091,200
aCompression complete ... final ratio = 63.0%

> ./chdman verify -i delta.chd -ip roms/lacrazyc/gv027-a1.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.262 (mame0252-3490-g0636e54bb60)
Raw SHA1 verification successful!
Overall SHA1 verification successful!

> ./chdman info -i delta.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.262 (mame0252-3490-g0636e54bb60)
Input file:   delta.chd
File Version: 5
Logical size: 537,091,200 bytes
Hunk Size:    19,584 bytes
Total Hunks:  27,425
Unit Size:    2,448 bytes
Total Units:  219,400
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     338,666,937 bytes
Ratio:        63.1%
SHA1:         e7e6749ac65de7771eb8fed7d5eefaec3f902255
Data SHA1:    36676b7bd63e20ce6126280a3f7a3e3ea0a4b8c0
Parent SHA1:  840d0d4876cf1b814c9d8db975aa6c92e1fe4039
Metadata:     Tag='CHT2'  Index=0  Length=93 bytes
              TRACK:1 TYPE:MODE1_RAW SUBTYPE:RW_RAW FRAMES:8073 PREGAP:0 P
Metadata:     Tag='CHT2'  Index=1  Length=90 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:RW_RAW FRAMES:14934 PREGAP:0 PGTY
Metadata:     Tag='CHT2'  Index=2  Length=90 bytes
              TRACK:3 TYPE:AUDIO SUBTYPE:RW_RAW FRAMES:15136 PREGAP:0 PGTY
Metadata:     Tag='CHT2'  Index=3  Length=90 bytes
...

> ls -l delta.chd
-rw-r--r--  1 owner  staff  338666937 Feb 13 02:03 delta.chd
```

**Comment by john-iv** [comment]
I was able to successfully convert the CHD from the original post using today's build 0.262 (mame0262-152-g0636e54bb60) version of CHDMAN.

I'll close the issue.
