### ISSUE TITLE
Updated 0.176 tag after release?

### ISSUE THREAD

**Issue by tomyun** [mamedev/mame#1168]
It seems like `0.176` version tag has been updated shortly after its initial release on July 27th and I found two additional commits (3fc2464d7c6dd154452b45270d20154ea1a25485, 14e7367f7e1dd575754f8c59fcf74b956c91e87b) pushed after a version bump commit (4887ce18443a51fd2a861da959082ad346ff4ee2) which usually would be the last.

We'll update the broken checksum of [tar.gz archive](https://github.com/mamedev/mame/archive/mame0176.tar.gz) for OS X homebrew package if this change is officially confirmed upstream.

- Initial (Homebrew/homebrew-games#605): `ce69d65fc0431563e5617ce738a504826b73632ad261df53f16b314f67d5a48d`
- Current (Homebrew/homebrew-games#610): `e8837ae9c21ac6ca289c0214747a6d7ff7cc4683b9426377f42cda318fddcb25`

**Comment by h0tw1r3** [comment]
@mmicko handles the releases. I don't speak for the team in any way, but it looks like those two are compile bugs. Tagged releases are intended to compile error free on all supported platforms. Therefor I would assume that the moved tag was in fact intended.

**Comment by galibert** [comment]
The process is that micko creates the tag, then test-compiles the tagged
version. If it fails, he adds whatever fixes are needed until it works,
then updates the tag. Only after that he does the actual release.

  OG.

**Comment by tomyun** [comment]
It sounds like we can then safely assume the change was intended as a release process handled by @mmicko. Thanks for the answers!

**Comment by rb6502** [comment]
Yeah, he wanted to make sure the final tagged version compiled on all of our supported systems.
