### ISSUE TITLE
[ui] keyboard gamepad game list selection jump every two games

### ISSUE THREAD

**Issue by legluondunet** [mamedev/mame#1169]
Hello,

when I use the mame ui and try to select a game in the list, with the keyboard or the gamepad, one press becomes two, I can only select one game on two.

Thank you for your help.

LGDN

config:
Mame 0.176 compiled form official mame sources
Ubuntu 16.04 Xenial 64 bits
NVIDIA  GeForce GTX 770
official Ubuntu Nvidia drivers 361.42 - 1920x1080

**Comment by rb6502** [comment]
Could you please retry this with the new 0.177?  0.176 and previous SDL2 based versions had significant input problems on Linux and OS X.

**Comment by legluondunet** [comment]
Helo,

I just tested with the 0.177 version, the bug is still here.

**Comment by bradhugh** [comment]
I wondering why your experience is different than others.  Some of the fixes so far were specific to mouse input and implementing a workaround for a specific SDL bug on OSX.  I am not aware of any other folks experiencing this (other please chime in if I'm wrong).  Do you have any idea what might be unique about your configuration?

**Comment by Tafoid** [comment]
There is a report on MT which no one can duplicate either that sounds similar to this.  Same person here?
http://mametesters.org/view.php?id=6389

**Comment by legluondunet** [comment]
I feel less alone, someone somewhere has the same bug as me.

**Comment by legluondunet** [comment]
Hello,

I just tested with the 0.178 version, the bug is still here.

**Comment by legluondunet** [comment]
Hello,

I just tested with the 0.179 version, the bug is still here.

**Comment by bradhugh** [comment]
I believe I was able to reproduce this. I can make it happen as stated with the Visual Studio 32-bit SDL debug build (because it's slow to execute the decompression routines I think).  My repro is with a large snapshots file (because it attempts to load as part of the UI changing games).  When this part is super slow, it can make the auto-repeat detection for the UI keypress fire.  I can "fix" it easily by just turning of auto-repeat entirely in the UI code by changing the line:
if (exclusive_input_pressed(iptkey, IPT_UI_DOWN, 6)) // Around line 846 in selmenu.cpp

Change the 6 to 0 which disables auto-repeat entirely. This probably isn't a true fix, but I'd love confirmation from someone that this *is* in fact related to auto-repeat and that I have a true repro.

**Comment by legluondunet** [comment]
I just compiled mame after changed the line:
if (exclusive_input_pressed(iptkey, IPT_UI_DOWN, 6)) // Around line 846 in selmenu.cpp

If I press the up key, it jumps two games up (+2), bug
If I press the down key, it jumps to the next game down (+1), normal way

**Comment by bradhugh** [comment]
Awesome, this confirms I have a repro also. I'll take a look at how to fix it.

**Comment by bradhugh** [comment]
I have looked into this and don't see a reasonable way of fixing it. The only hacky solution I could readily come up with was to allow the user to specify a ui keyboard repeat speed.  Of course the easiest of all is just to tell them to extract their huge snap file to disk uncompressed and then there are no issues.

I'm tempted to just propose the latter as it's an overall better experience. Thoughts?

**Comment by bradhugh** [comment]
For the record, this isn't just an SDL issue as it can be reproduced on Windows assuming you make it slow enough.

**Comment by bradhugh** [comment]
Ok, I'm going to work on this again. UWP is hitting this badly once I experimented switching to the new file API's (they are slow).  I'll try to work out what else can be done here.

**Comment by legluondunet** [comment]
I'm still here if you need a tester.

**Comment by bradhugh** [comment]
I have submitted a pull request to fix this. You're welcome to test, but I have a very reliable repro.
