### ISSUE TITLE
Mame 0.260: Translations: Fatal Errors with Latest Additions for Turkish

### ISSUE THREAD

**Issue by mascguy** [mamedev/mame#11692]
### MAME version

0.260

### System information

Building on macOS. However, this is a platform and architecture-independent issue, in the Turkish translation string file.

### INI configuration details

```INI
Not Applicable
```

### Emulated system/software

Not Applicable

### Incorrect behaviour

The build fails during the translation phase, when generating `mame.pot`, with the following fatal errors:

```
language/Turkish/strings.po:1563: missing 'msgstr' section
language/Turkish/strings.po:1573: missing 'msgstr' section
language/Turkish/strings.po:3443:26: invalid control sequence
msgmerge: found 3 fatal errors
```

Based on a review of the lines in question, all three appear to be legitimate issues.

More details in PR comment here: https://github.com/mamedev/mame/pull/11602#issuecomment-1789108689

### Expected behaviour

The build shouldn't fail during the translation phase, of course.

### Steps to reproduce

Run the build, including all translation phases.

### Additional details

Refer to PR comment, mentioned earlier, for more details if necessary.

**Comment by cuavas** [comment]
See fccbed7657675a5e1c4c63fff08c61ab24964be2
