### ISSUE TITLE
Adding Clang arm64 compiler directives for FreeBSD

### ISSUE THREAD

**Issue by github-c999-bfa4-cc81** [mamedev/mame#11714]
### MAME version

0.260

### System information

FreeBSD-15 arm64.

### INI configuration details

```INI
N/A
```

### Emulated system/software

N/A

### Incorrect behaviour

Hello,

Current GNU Makefile directives are missing for arm64 on FreeBSD for Clang and GCC, however, only Clang has been tested, thus, MAME is not currently buildable at all on ARM64 hardware for FreeBSD.

### Expected behaviour

Not so much expected, but at least appreciated considering the project's position on platforms not formally supported; to be able to build MAME for ARM 64bit hardware on FreeBSD, thanks.

### Additional details

Patch enabling build for ARM64 on FreeBSD:

```
diff --git a/makefile b/makefile
index dcd274bbef4..a3ecc187039 100644
--- a/makefile
+++ b/makefile
@@ -1413,6 +1413,11 @@ freebsd_x86: generate $(PROJECTDIR)/$(MAKETYPE)-freebsd/Makefile
 $(PROJECTDIR)/$(MAKETYPE)-freebsd-clang/Makefile: makefile $(SCRIPTS) $(GENIE)
        $(SILENT) $(GENIE) $(PARAMS) $(TARGET_PARAMS) --gcc=freebsd-clang --gcc_version=$(CLANG_VERSION) $(MAKETYPE)

+.PHONY: freebsd_arm64_clang
+freebsd_arm64_clang: generate $(PROJECTDIR)/$(MAKETYPE)-freebsd-clang/Makefile
+>   $(SILENT) $(MAKE) -C $(PROJECTDIR)/$(MAKETYPE)-freebsd-clang config=$(CONFIG)64 precompile
+>   $(SILENT) $(MAKE) -C $(PROJECTDIR)/$(MAKETYPE)-freebsd-clang config=$(CONFIG)64
+
 .PHONY: freebsd_x64_clang
 freebsd_x64_clang: generate $(PROJECTDIR)/$(MAKETYPE)-freebsd-clang/Makefile
        $(SILENT) $(MAKE) -C $(PROJECTDIR)/$(MAKETYPE)-freebsd-clang config=$(CONFIG)64 precompile
```

**Comment by ajrhacker** [comment]
You can try submitting this patch as a pull request. I think there's a good chance that it will be accepted following review.

**Comment by github-c999-bfa4-cc81** [comment]
> You can try submitting this patch as a pull request. I think there's a good chance that it will be accepted following review.

Will do that, thanks.

**Comment by github-c999-bfa4-cc81** [comment]
Will report back here if this ever gets done.
