### ISSUE TITLE
device_ref missing?

### ISSUE THREAD

**Issue by marcsnowhill** [mamedev/mame#11723]
### MAME version

0.260

### System information

Windows 10

### Incorrect behaviour

I found a lot of devices that are not referenced by machines in the XML (using `<device_ref>`).

Since it are so many (2434 devices), I was wondering if a developer can look at them. Maybe there is a bug in the XML export code that prevents some devices not being referenced?
Or are it unused/preliminary devices and there are just a lot of them?

Attached is the device name list and device description list of the unreferenced devices I found.

All the best,
Marc Snowhill

[device name.txt](https://github.com/mamedev/mame/files/13326110/device.name.txt)

[device description.txt](https://github.com/mamedev/mame/files/13326108/device.description.txt)

### Expected behaviour

I would not expect so many devices not be referenced!

**Comment by rb6502** [comment]
Those are slot devices.  However you're determining if they're referenced is not right.

**Comment by marcsnowhill** [comment]
> Those are slot devices. Whatever method you're using to determine if they're referenced is not right.

Thanks for your explanation! I only found 1 way (in the XML) to determine if a device is referenced or not and that is looking at the `<device_ref >` tag. 

So for example the game `005` has references to the following devices.

                <device_ref name="z80"/>
		<device_ref name="gfxdecode"/>
		<device_ref name="palette"/>
		<device_ref name="screen"/>
		<device_ref name="speaker"/>
		<device_ref name="i8255"/>
		<device_ref name="samples"/>
		<device_ref name="sega005_sound"/>

Is is correct we can't see references to slot devices in the XML?
And if this is correct, why are they not using a `<device_ref >` tag there?

**Comment by angelosa** [comment]
I can see slot options just fine, cfr. `mame pc9801rs -listxml`
```xml
		<slot name="cbus0">
			<slotoption name="otomichan_kai" devname="pc98_otomichan_kai"/>
[...]
	<machine name="pc98_otomichan_kai" sourcefile="devices/bus/cbus/pc9801_86.cpp" isdevice="yes" runnable="no">
		<description>MAD Factory Otomi-chan Kai</description>
```
device_ref is what it says, a reference to a device. 
Like "JJ" is a reference to AI generated content, you know the door.

**Comment by marcsnowhill** [comment]
> I can see slot options just fine, cfr. `mame pc9801rs -listxml`
> 
> ```
> 		<slot name="cbus0">
> 			<slotoption name="otomichan_kai" devname="pc98_otomichan_kai"/>
> [...]
> 	<machine name="pc98_otomichan_kai" sourcefile="devices/bus/cbus/pc9801_86.cpp" isdevice="yes" runnable="no">
> 		<description>MAD Factory Otomi-chan Kai</description>
> ```
> 
> device_ref is what it says, a reference to a device. Like "JJ" is a reference to AI generated content, you know the door.

Thank you, I was looking at the wrong place.
Closed.
