### ISSUE TITLE
-listsoftware typos

### ISSUE THREAD

**Issue by thecookie-monster** [mamedev/mame#11721]
### MAME version

.260

### System information

Windows 7

### Incorrect behaviour

I found 2 games who have duplicate years in -listsoftware

- Software list: `apple2_flop_clcracked`: game `pfsg8301`

![afbeelding](https://github.com/mamedev/mame/assets/150374721/4e12b363-e77c-4ec0-9ae0-f9b5a49a7384)

- Software list: `apple2_flop_clcracked`: game `pfsg8401`

![afbeelding](https://github.com/mamedev/mame/assets/150374721/489a9628-e7d1-4242-b5db-5dd519714fe1)

Thanks

### Expected behaviour

Correct year

**Comment by angelosa** [comment]
Report lists two entries that (I think) eventually got moved to `pfsgraph830112` and `pfsgraph840131` with correct year release.
Your hash files are outdated, update them, closing here.

**Comment by thecookie-monster** [comment]
The entries `pfsgraph830112` and `pfsgraph840131` do NOT exist in the software list `apple2_flop_clcracked` of MAME .260 ...

I attached the software list file of MAME downloaded from here https://github.com/mamedev/mame/releases/download/mame0260/mame0260b_64bit.exe

The 2 entries are still present in there, with wrong year, exactly as I wrote above.

Please re-open and correct.

[apple2_flop_clcracked.zip](https://github.com/mamedev/mame/files/13310997/apple2_flop_clcracked.zip)

**Comment by philipjbennett** [comment]
The mistakes were corrected and new entries made after the release of 0.260. This is the current file:

https://raw.githubusercontent.com/mamedev/mame/master/hash/apple2_flop_clcracked.xml

There's nothing actionable here.

**Comment by thecookie-monster** [comment]
Thanks
