### ISSUE TITLE
6x09/Konami disassembler mentions a commercial restriction

### ISSUE THREAD

**Issue by invertego** [mamedev/mame#11746]
The license header says "BSD-3-Clause", but the comment block describes an additional commercial restriction. If the original author(s) agreed to relicense under BSD-3, presumably the extra clause should no longer apply.

https://github.com/mamedev/mame/blob/a083d5a8da05ce2cdf9d30668e3cd423d865cfb2/src/devices/cpu/m6809/6x09dasm.h#L20-L22
https://github.com/mamedev/mame/blob/a083d5a8da05ce2cdf9d30668e3cd423d865cfb2/src/devices/cpu/m6809/6x09dasm.cpp#L19-L21

**Comment by happppp** [comment]
It's removed now https://github.com/mamedev/mame/commit/555ba8e767551b663c39dc3ff4297f2b228cede1

**Comment by cuavas** [comment]
That could be interpreted as an additional grant in addition to the BSD license for that specific file (i.e. you can distribute it without the BSD disclaimer included provided you charge no more than $7 for the media).  Not sure how useful that would be to anyone.
