### ISSUE TITLE
psr540: ROM name and checksum/hash issue

### ISSUE THREAD

**Issue by Shoegzer** [mamedev/mame#11800]
### MAME version

0.261

### System information

* OS: Linux Mint 21.2 / kernel 6.2
* CPU: Intel i7-10860H

### INI configuration details

```INI
N/A
```

### Emulated system/software

psr540

### Incorrect behaviour

This current driver requires the same-named rom three times, each with a different checksum/hash.  This can be seen using `mame -listroms`, as follows: 

```
./mame -listroms psr540
ROMs required for driver "psr540".
Name                                   Size Checksum
xw25320.ic310                       4194304 CRC(e8d29e49) SHA1(079e0ccf6cf5d5bd2d2d82076b09dd702fcd1421)
xw25320.ic310                       4194304 CRC(c7c4736d) SHA1(ff1052eb076557071ed8652e6c2fc0925144fbd5)
xw25320.ic310                       2097152 CRC(9ef56c4e) SHA1(f26b588f9bcfd7bdbf1c0b38e4a1ea57e2f29f10)
```

### Expected behaviour

Each rom should be named differently, or split into different sets, or unnecessary duplicates removed.

### Steps to reproduce

Use `mame -verifyroms psr540` to check this set.

### Additional details

N/A

**Comment by cuavas** [comment]
The SWX00 ROMs are IC210 and IC220 – see d28ac53f5f7d93157d9fb921ed1701e4bf70a7eb.
