### ISSUE TITLE
.261: incorrectly emulated TTL logic of breakout

### ISSUE THREAD

**Issue by ghost** [mamedev/mame#11813]
### MAME version

.261

### System information

Win 10

### Incorrect behaviour

Game breakout has incorrectly emulated TTL logic which is visually seen on the screen.
It appears in each video output mode: opengl , direct3d, bgfx, ... so it's not related to the renderer.

Zoomed in image: you see the green color appear on the yellow bricks

![afbeelding](https://github.com/mamedev/mame/assets/152745130/8b40c622-fb7c-4ce4-8665-3e78520aa4fe)

Real PCB: notice the green color doesn't overlap the yellow bricks

https://www.youtube.com/watch?v=AMUv8KvVt08

### Expected behaviour

I would expect the colors to match the real PCB gameplay footage

**Comment by happppp** [comment]
It's the color overlay, and sure, it looks like a small misalignment.

**Comment by stonedDiscord** [comment]
![grafik](https://github.com/mamedev/mame/assets/10584181/f1b10226-9f4d-42f1-9e83-560e1afe603b)
this is already fixed on master
