### ISSUE TITLE
nuon.xml: Closing quote on new line

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#11832]
Can you please merge these two lines so the " is on the same line as the last digit of the sha1?

https://github.com/mamedev/mame/blob/9dba0050e66581690f19590e8b7d024071370aae/hash/nuon.xml#L52-L53

If you prefer I can send a pull request instead, let me know.

**Comment by cuavas** [comment]
You can open a PR if no-one gets to it - it wouldn't be rejected. But reference implementations strip leading and trailing whitespace from those attributes, so it doesn't cause a problem for most applications that use the software lists.
