### ISSUE TITLE
current image category remembering in GUI

### ISSUE THREAD

**Issue by stilett0** [mamedev/mame#1184]
Thought this was worth quoting:
< @Robbbert > I just started up MAME, and snapshot was already selected, then i switched to control panel, exit, restart, it's back to snapshot - can't see where (or if) it saves which panel was in use. Would be nice if it remembered though, like MAMEUI does

**Comment by cuavas** [comment]
Addressed by bd561abff012dc4b6e638c407d0ec279d7e23538.
