### ISSUE TITLE
H16 disassembler produces opposite instructions

### ISSUE THREAD

**Issue by marijnvdwerf** [mamedev/mame#11887]
Using the h15 disassembler, `94 20 ad` gets disassmbled as `SMOV` when it should be `SSTR` and vice versa.

https://github.com/mamedev/mame/blob/c7b3993e5704e2f4cdd82ecc0cf777fbc3992a87/src/devices/cpu/h16/h16dasm.cpp#L803

From the CPU manual:

<img width="339" alt="image" src="https://github.com/mamedev/mame/assets/737603/63359242-03e1-4049-82aa-f22be2866b85">

if `TYP` is `010` or `101`, it's `SMOV`.
If `TYP` is `000` or `100` it's `SSTR`.

**Comment by ajrhacker** [comment]
Corrected in 9948864f1484806c83a25c6a60d9cd91a2875d09.
