### ISSUE TITLE
Imperfect Graphics and Sound For Hyper NeoGeo 64 Games

### ISSUE THREAD

**Issue by chris8900000** [mamedev/mame#11941]
[hng64.zip](https://github.com/mamedev/mame/files/13957803/hng64.zip)
src/mame/snk/hng64.cpp

**Comment by chris8900000** [comment]
https://github.com/mamedev/mame/blob/master/src/mame/snk/hng64.cpp

**Comment by chris8900000** [comment]
hng64.cpp

**Comment by chris8900000** [comment]
fix it

**Comment by galibert** [comment]
Nah.
