### ISSUE TITLE
Build: Upcase to include downcase filename

### ISSUE THREAD

**Issue by SvenMichaelKlose** [mamedev/mame#11948]
### MAME version

latest master

### System information

Linux Mint 21.3

### Incorrect behaviour

src/devices/bus/pci/rtl8139_pci.cpp cannot find include file "RTL8139_PCI.h" as it's "rtl8139_pci.h"

### Expected behaviour

To not complain.

### Steps to reproduce

Build on non-Windows.

**Comment by stonedDiscord** [comment]
fixed by 67534fc4b959d48a2aa1203815cb182e9dffbeec
