### ISSUE TITLE
megadriv.xml: The rom ferias.zip from the software list is a chinese hack rom

### ISSUE THREAD

**Issue by arthurthekidboy** [mamedev/mame#11950]
### MAME version

0.261

### System information

Windows 10
Radeon Vega 3
Athlon 3000G
8GB Ram

### Emulated system/software

megadriv

### Incorrect behaviour

The rom of the software list of genesis have a chinese hack rom from the game ferias frustadas do pica pau (ferias.zip).the rom of the software list have a glitched intro.
The original rom (that has dumped from no intro database in 2021) have a original sega logo, tectoy logo (with a character woody woodpecker appears in the logo) and the trademark in the intro.
This rom was discovered by a Brazilian YouTube channel called ucollecionador who dumped the rom and he tells the story of this rom

### Expected behaviour

redump the rom to the original from 2021

### Steps to reproduce

1. Start the MAME
2. Open the Genesis rom
3. In The Software List runs ferias.zip

**Comment by arthurthekidboy** [comment]
Theres a comparison from the roms

The Chinese Hacked Rom

![image](https://github.com/mamedev/mame/assets/102826358/d08ae26b-8bd3-4943-8dac-1207f24c2cab)

**Comment by ICEknigh7** [comment]
Just replaced that bad dump for the good one, thanks for reporting it.

**Comment by mamehaze** [comment]
The old dump should be marked as a bootleg / pirate rather than removed, it clearly came from a cart, just not the original Brazilian cart.
(I haven't seen your PR for it yet, so maybe that's what you did)

**Comment by ICEknigh7** [comment]
Right, hadn't thought of that. It's now back in the softlist as a clone.

**Comment by bootmii** [comment]
Can we close this issue? It looks resolved to me.

**Comment by ICEknigh7** [comment]
I wouldn't mark it as resolved until the Pull Request is actually merged, since the wrong version will still be showing up until then.

**Comment by ICEknigh7** [comment]
PR has been merged, so this can be closed.

**Comment by arthurthekidboy** [comment]
Thanks a lot
