### ISSUE TITLE
makefile:1138: *** MINGW32 is not set.  Stop.

### ISSUE THREAD

**Issue by kv29xrb** [mamedev/mame#12005]
### MAME version

0.262

### System information

HP 2570p Laptop environment details are:
- operating system, Windows 11 22H 64bite, 16 GB ram
- processor architecture: Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz, cores 4
- system locale: French
- MSYS2 display language: English
- video hardware (GPU), Intel(R) HD Graphics 4000, driver version 10.18.10.4252, date 07/10/2015,
- the MAME video output module: none currently

### INI configuration details

```INI
I don't have any mame.ini file, I don't know, it's not written in the procedure
```

### Incorrect behaviour

Good morning,
The compilation stops with the following message:

ORDY@ORDY-PC MSYS ~/mame
$ make
GCC 13.2.0 detected
makefile:1138: *** MINGW32 is not set.  Stop.

### Expected behaviour

This is the first compilation I've done.
I don't have an example of correct operation.
the installation is I emulation is a 64bit

### Steps to reproduce

I followed the installation: https://www.mamedev.org/tools/
I downloaded msys64-2022-01-12.exe, unzipped and installed it on disk D:\msys64
after unzipping, double-click : autorebase.bat and config64.bat
I installed GCC > $ pacman -S gcc
I installed MAKE > $ pacman -S make
I installed PYTHON > $ pacman -S python3
I entered the command for update > $ pacman -Syu
I restarted msys2.exe
I entered the command again for update >
     $pacman-Sy
     $ pacman -S bash pacman msys2-runtime --noconfirm --needed
I downloaded the MAME source > $ git clone https://github.com/mamedev/mame.git
I am positioned on the mame MSYS ~/mame folder
I ran the compliation > $make

### Additional details

I don't know, it's not written in the procedure

**Comment by cuavas** [comment]
It actually is documented that you need to set the `MING32` and MINGW64` environment variables: https://docs.mamedev.org/initialsetup/compilingmame.html#using-a-standard-msys2-installation

> For 64-bit builds, open **MSYS2 MinGW 64-bit** from the start menu, and set up the environment variables `MINGW64` to `/mingw64` and `MINGW32` to an empty string (e.g. using the command **export MINGW64=/mingw64 MINGW32=** in the Bash shell).

**Comment by cuavas** [comment]
If you need more guidance compiling MAME, please ask for help on a discussion forum.
