### ISSUE TITLE
megadriv/cavestory missing ja, zh, ko characters

### ISSUE THREAD

**Issue by soundsnow** [mamedev/mame#12008]
### MAME version

0.262

### System information

Google Android 12
Qualcomm Snapdragon 750G

### Incorrect behaviour

Open these three files and start a new game. It shows "???????"
Cave Story - Doukutsu Monogatari
Chinese, Japanese, Korean
megadriv/cavestory_zh.zip/doukutsu-zh.bin
megadriv/cavestory_ja.zip/doukutsu-ja.bin
megadriv/cavestory_ko.zip/doukutsu-ko.bin
![Screenshot_20240204-133033_MAME4droid 2024](https://github.com/mamedev/mame/assets/109885044/6b820707-acfa-45b3-8c55-242d6c58e009)

They're green, but I think they should be orange.

### Expected behaviour

Chinese
数？你在吗？是我。
English
Sue? You there? It's me.
![Screenshot_20240204-133124_MAME4droid 2024](https://github.com/mamedev/mame/assets/109885044/153920e3-74ff-49f5-ac2e-34fcb2c2cd5e)

### Additional details

another question, how to switch between NTSC-J, NTSC-U and PAL? Some Mega Drive games include English and Japanese, but it can only change languages ​​by detecting the region. There is no option to change the language in the game
Streets of Rage II (Japan, Europe) (En,Ja)

what's snap and software folders?
how to use?
snap is snapshot? or it's screenshot?

**Comment by angelosa** [comment]
Probably just requires to be mounted thru `megadrij` instead of `genesis` (NTSC-U) / `megadriv` (PAL).

**Comment by FoxhackDN** [comment]
... okay, they got a point. Something's up.

If you load cavestory_zh from the software list or the command line, and start a game, your "Load Save Data" screen (where you select where to save your game) starts up in English, and then the game text only shows question marks.

![0001](https://github.com/mamedev/mame/assets/71686027/9fa55937-35a9-40da-85e4-67037af4d8f1)

![0005](https://github.com/mamedev/mame/assets/71686027/4a2468f6-0173-466d-b1fc-b3cf71d24bd3)

BUT. If you go into the game options in the menu *first*, back out, then start a game? The text shows up correctly.

![0002](https://github.com/mamedev/mame/assets/71686027/8181a76c-d4e1-41e8-ba64-8903cf22baa8)

![0006](https://github.com/mamedev/mame/assets/71686027/4b2a5420-d62e-4c9e-ab8a-e9044b867589)

**Comment by angelosa** [comment]
Found a workaround: if you enter options and apply then the text fixes itself.
I'm not sure if the bug is [upstream](https://github.com/andwn/cave-story-md) or a MAME bug (pending real HW check), IF latter then this is a side effect of https://github.com/mamedev/mame/issues/7403

> Another choice Genesis Plus GX

BlastEm, MAME core is unmaintained by the original author and basically deprecated for all I care.

**Comment by angelosa** [comment]
> I'm not sure if the bug is [upstream](https://github.com/andwn/cave-story-md) or a MAME bug (pending real HW check), IF latter then this is a side effect of https://github.com/mamedev/mame/issues/7403

Errata: I forgot that `rom_sram` also needs a default length set in XML.

**Comment by angelosa** [comment]
> Yes, it's a MAME bug. 

It _was_, you see that purple button that says _Closed_? Means something that is fixed already, and my original point was right all along -> missing SRAM hookup.

> They tested for real hardware and high compatibility Mega Drive emulators

So how do you explain [this](https://github.com/andwn/cave-story-md/issues/380)? It technically tries to write to the SRAM, it fails, it starts up the game in the wrong language path, it fixes itself if you go to the options and back, all symptoms that smells like a bug/issue _in the software_ if it flags itself about being unable to save.

**Comment by rb6502** [comment]
MAME preserves all versions of software.  Same as we do for arcades.

**Comment by ICEknigh7** [comment]
> They tested for real hardware and high compatibility Mega Drive emulators

Looks like there's some more testing left to do on real hardware:
![image](https://github.com/mamedev/mame/assets/47050710/2a6b2a28-21bb-4c83-b8eb-ed4bdda7b61b)
