### ISSUE TITLE
snk/hng64.cpp fix imperfect sound and sony/zn.cpp and src/mame/sony/taitogn.cpp fix imperfect graphics and sound for all games 

### ISSUE THREAD

**Issue by Christian7600000** [mamedev/mame#12021]
src/mame/snk/hng64.cpp and src/mame/sony/zn.cpp and src/mame/sony/taitogn.cpp first hyper neogeo 64 needs to fix the imperfect sound emulation on the Hyper NeoGeo 64 BIOS second fix the imperfect graphics and sound for all games please pretty please

**Comment by Christian7600000** [comment]
src/mame/sony/taitogn.cpp

**Comment by Christian7600000** [comment]
Taito GNET

**Comment by Christian7600000** [comment]
ZN1 and ZN2

**Comment by Christian7600000** [comment]
TPS

**Comment by angelosa** [comment]
>>> You're missing the point, and besides: HNG64 needs Akai MPC3000 synth being fixed, for very obvious reasons.
Now, how many MPC floppy dumps there are in the wild?
By quick glance ZERO -> users don't care enough.
