### ISSUE TITLE
arcade color palette colors possible to extract?

### ISSUE THREAD

**Issue by ROMmonkey** [mamedev/mame#12048]
### MAME version

0.262

### System information

Win 10

### Incorrect behaviour

N/A

### Expected behaviour

I'm making INI folder files for MAME and I wanted to quickly ask here if there is a way the MAME developers can extract the number of different colors in the color palette of an arcade game and present it in the XML file of MAME (for each arcade machine)? (maybe new tag "color_palette")
I have no idea if this is a possible and even logical question since I have no knowledge of the color palettes and I also don't know how they are used in the source code.
I just know they are in the ROM stored.

If this would be available, I could make INI folder files based on the number of color palette colors, giving me a cool filter which is not possible right now.

So to be clear: I'm talking about the number of _different_ colors in the color palette, example arcade game **ddcrew**

![2hceslz](https://github.com/mamedev/mame/assets/156975202/2f5c5ccc-65ed-47e9-8b7a-ea9ce04329bf)

PS: I know this is not a forum but I hope somebody can tell me if this is possible or not (and planned or not).

**Comment by cuavas** [comment]
You know this isn’t a forum.  Why are you trying to use it as one?

**Comment by arcadegirl** [comment]
that guy is right!
please help him
