### ISSUE TITLE
gticlub2 And gticlub2ea Controls Not Working, Also, After Select A Car And Race Course, It Ocurs Network Error.

### ISSUE THREAD

**Issue by ultrabub575** [mamedev/mame#12066]
![0001](https://github.com/mamedev/mame/assets/126421840/76e227f8-9b28-46b1-8de1-1c451039dff5)

**Comment by 987123879113** [comment]
The game is marked as NOT_WORKING in the driver and the network error is also documented.
https://github.com/mamedev/mame/blob/1463ddf8012b65b5bcef6f0c20de14405c15f13d/src/mame/konami/viper.cpp#L90
https://github.com/mamedev/mame/blob/1463ddf8012b65b5bcef6f0c20de14405c15f13d/src/mame/konami/viper.cpp#L123

**Comment by angelosa** [comment]
Technically should be marked with `MACHINE_NODEVICE_LAN` and `MACHINE_UNEMULATED_PROTECTION`, but given Pup definitely missed the big red screen then I'm convinced it will miss those as well.

Did I tried to fix the network? Yes, multiple times, it stays stuck in service mode with no frame errors no matter what, doesn't help my poor proficiency with PowerPC, and opening issues with nothing of value won't suddenly make me a PowerPC virtuoso.
