### ISSUE TITLE
SM510 Processor Different to data sheet

### ISSUE THREAD

**Issue by Android78** [mamedev/mame#12063]
https://github.com/mamedev/mame/blame/5c84856b508ed72c89579da7ce61486da45e59f9/src/devices/cpu/sm510/sm510op.cpp#L58
Is it possible that this should be, as per the datasheet?
According to the datasheet, the LB xy is:
- BL1,BL0<=x(I3,I2)
- BM1,BM0<=y(I**2**,I0)

This would be 
`m_bm = (m_bm & 4) | ((m_op >>1) & 2)| (m_op & 1);`
Rather than the current:
`m_bm = (m_bm & 4) | (m_op & 3);`

Also, shouldn't the following:
`m_bl = (m_op >> 2 & 3) | ((m_op & 0xc) ? 0xc : 0);`
be
`m_bl = (m_bl & 0xc) | (m_op >> 2 & 3);`

The BL code as it currently is will set the upper two bits to 0 if the upper two bits of the operand are set, else they remain unchanged... that seems weird to me.

Then again, it could be an error in the datasheet I have access to... or a hardware bug

**Comment by happppp** [comment]
Yes, it's an error in the datasheet. IIRC the Soviet clone CPU documentation describes it better.

**Comment by happppp** [comment]
![lb](https://github.com/mamedev/mame/assets/9270613/bf43b4af-6bb9-4cde-b34e-ffe6583b8ca5)
Top description for SM5A, bottom description for SM510.
