### ISSUE TITLE
pool10e: Incorrect length reported by -verifyroms

### ISSUE THREAD

**Issue by Shoegzer** [mamedev/mame#12082]
### MAME version

0.263

### System information

N/A

### INI configuration details

```INI
N/A
```

### Emulated system/software

pool10e

### Incorrect behaviour

Running MAME -verifyroms produces:
```
mame -verifyroms pool10e
pool10e     : palce16v8h.u5 (279 bytes) - INCORRECT LENGTH: 2194 bytes
pool10e     : palce20v8h.u22 (343 bytes) - INCORRECT LENGTH: 2706 bytes
pool10e     : palce20v8h.u23 (343 bytes) - INCORRECT LENGTH: 2706 bytes
romset pool10e [pool10] is bad
1 romsets found, 0 were OK.
```

### Expected behaviour

Set should verify properly.

### Steps to reproduce

1. Run mame with -verifyroms on the set as shown above

### Additional details

@happppp I noticed a related fix in the whatsnew, could that have triggered this?

`-pool10e: remove empty read-protected pld baddumps [hap]
`

**Comment by happppp** [comment]
Yes that's what triggered that error message. Just remove those files.

ROM_REGION( 0x0600, "plds", 0 ) // all read protected
ROM_LOAD( "palce16v8h.u5",  0x0000, 0x0117, NO_DUMP )
ROM_LOAD( "palce20v8h.u22", 0x0200, 0x0157, NO_DUMP )
ROM_LOAD( "palce20v8h.u23", 0x0400, 0x0157, NO_DUMP )

**Comment by Shoegzer** [comment]
Ah, got it!  Thanks, closing.
