### ISSUE TITLE
Graphics viewer's background removes font sprite shadows

### ISSUE THREAD

**Issue by aretrogamer** [mamedev/mame#12097]
### MAME version

0.263

### System information

Win

### Incorrect behaviour

N/A

### Expected behaviour

The Graphics viewer (F4) can display font sprites but the background of each sprite is always black in MAME.
The shadow of a font sprite in a game is often black, and so is the background of each tile in MAME's graphics viewer (it can't be changed), which means the shadow is completely lost (the black shadow dissappears in the black tile background).

I therefore want to ask a small feature to cycle between (a small) number of colors for the background in the graphics viewer (a key can be assigned to this that only works in the graphics viewer, as there are already keys defined (+/-, etc) . If the color is non-black, that's enough to see the black shadow of the sprite font.

This feature is specific for being able to take a screenshot of the actual font sprites including shadows.
That's currently not possible, because black shadows are gone.

**Comment by cuavas** [comment]
> The shadow of a font sprite in a game is often black, and so is the background of each tile in MAME's graphics viewer (it can't be changed), which means the shadow is completely lost (the black shadow dissappears in the black tile background).

Your premise is wrong.  The graphics viewer background colour is configurable.  Start without selecting a system, choose “General Settings”, choose “Colors”,  choose “Graphics viewer background” (or alternatively, edit your ui.ini file).

**Comment by cuavas** [comment]
You can’t get that result.  The background colour is the background colour for the graphics viewer “window”.  Transparency isn’t an attribute of the tiles itself, it’s something that happens during mixing.  As such, the graphics viewer doesn’t know which pixels will be transparent when the tiles are drawn.  It just draws the tiles using whatever colours are in the palette.
