### ISSUE TITLE
graphics viewer: font sprites compressed in 1 direction

### ISSUE THREAD

**Issue by ghost** [mamedev/mame#12101]
### MAME version

0.263

### System information

win

### Incorrect behaviour

N/A

### Expected behaviour

The graphics viewer compresses the font sprites in 1 axis.
Font sprites are a matrix of 8x8 pixels, square. Not rectangle as below

See yellow lines and their distance to each other

![afbeelding](https://github.com/mamedev/mame/assets/162057536/667c60bb-e11a-4d65-b836-0b7d40f84d7a)

**Comment by holub** [comment]
You can try +/-, if that doesn't satisfy your needs then photoshop.
There is no point to reopen closed "issues" - you can still can put comments on the old one.

**Comment by RobertoFresca** [comment]
> I asked to reopen since the comments there are not an answer what the original person asked. How to get 1:1 pixel perfect sprites? The answer was not given. (and SHIFT doesn't help) Photoshop is useless. I can't make pixel perfect sprites when my source image is completely wrong (see above).

You CAN.
Given the aspect, just multiply X * Y and Y * X, and will get perfect squared chars.
