### ISSUE TITLE
graphics viewer: font sprites wrong orientation

### ISSUE THREAD

**Issue by aretrogamer** [mamedev/mame#12102]
### MAME version

0.263

### System information

win

### Emulated system/software

**bagman**
Graphics viewer

### Incorrect behaviour

N/A

### Expected behaviour

The graphics viewer displays for some games the font sprites in wrong orientation (seems to be rare cases).
I don't know if this is a bug but I can't image they are stored like this in ROM with this orientation?
Why would somebody do that?

example is game **bagman**

![a](https://github.com/mamedev/mame/assets/162057536/76f36b4e-0e4b-431a-867c-f1f1e2072d81)

### Steps to reproduce

- Run **bagman** and enable the graphics viewer
- note the font sprites in wrong orientation

**Comment by rb6502** [comment]
The font is stored that way by the game.  You seem to be under the misconception that MAME's viewer is some kind of all-purpose ripping tool.  It's not, it allows devs to debug graphics drawing issues in games.
