### ISSUE TITLE
some software item cannot be load when use commandline

### ISSUE THREAD

**Issue by aldag** [mamedev/mame#12119]
### MAME version

0.263

### System information

windows 7

### Emulated system/software

apple2_flop_misc, Akalabeth - World of Doom

### Incorrect behaviour

in softwarelist apple2_flop_misc, there is a software with shortname "aklabeth", and in softwarelist apple2_flop_orig ,there is also a software with same shortname "aklabeth".
so when you load the game with the command "mame apple2p aklabeth", mame will always try to load the one in apple2_flop_orig. but there should be a way to load the one in apple2_flop_misc.
![image](https://github.com/mamedev/mame/assets/7386239/763e1f14-9d0e-49ea-bab2-793bc58633db)

### Expected behaviour

add a parameter in commandline to specify softwarelist

**Comment by sairuk** [comment]
Load it with the software list name

```
./mame apple2p apple2_flop_misc:aklabeth
```

**Comment by aldag** [comment]
It's worked. Thanks.
