### ISSUE TITLE
chdman 0.263 issue Bad CHD-file for PSP games

### ISSUE THREAD

**Issue by CorvuzSoli** [mamedev/mame#12143]
### MAME version

0.263

### System information

Windows 10

### Incorrect behaviour

Creating the CHD file with chdman 0.263 and testing it with the PPSSPP emulator gives the message "Bad CHD-file" and changes the file size as well.

The command used for compression was:
`for /r %%i in (*.cue, *.gdi, *.iso) do chdman createdvd -i "%%i" -o "%%~ni.chd"`

![001](https://github.com/mamedev/mame/assets/161652427/51f2c549-d560-406d-bc03-7a2c9ae97a1e)

### Expected behaviour

When creating the CHD file with chdman 0.262 the PPSSPP emulator does not give any message and the file size is different with this version.

![002](https://github.com/mamedev/mame/assets/161652427/6fdddc2a-a46c-445f-8fff-fbc17198595b)

### Additional details

I don't know if the new build of the emulator corrected it but since Buildbot is down I can't download the latest build.

**Comment by sairuk** [comment]
Suggest you follow up here https://github.com/hrydgard/ppsspp/issues/18925

**Comment by cuavas** [comment]
PPSSPP doesn’t support hunk sizes larger than one sector.  Tell them to fix their own issues.
