### ISSUE TITLE
MAME 0.257 and later: IRIX 5.3 is stuck with a default of 16MB RAM, cmdline options are ignored

### ISSUE THREAD

**Issue by blappm** [mamedev/mame#12156]
### MAME version

0.263

### System information

Windows 11, 64bit

### Emulated system/software

SGI IRIX 5.3

### Incorrect behaviour

Up to MAME version 0.256 more memory than 16MB was possible, infact 128MB RAM was hardcoded. But in version 0.257 a change has been introduced, which removed the hardcoded limits. But this particular change seems to be incomplete, so any cmdline options to specify the ram/ramsize are ignored. The result is a new limit of 16MB, which really too low.

### Expected behaviour

That parameters -ramsize XXX / -ramsize XXXM are not ignored and properly set.

### Steps to reproduce

Use MAME 0.257 or later with IRIX 5.3

**Comment by happppp** [comment]
See comments here: https://github.com/mamedev/mame/pull/12142
(press TAB -> Machine Configuration)

The -ramsize commandline option is only for emulated systems that use the (quite limited) RAM device.
Perhaps the default RAM size can be increased for this driver, but it's not up to me to decide, it's not a system I'm familiar with, at all.

**Comment by blappm** [comment]
> de.

I haven't found a method to specify it trough the menu nor the cmdline. All things I've tried failed. If you tell me how to specify it, i would be happy ...

**Comment by sairuk** [comment]
@happppp mentioned it was available under `Machine Configuration` in the `Tab` in-machine menu, you will need to activate the UI to configure (`Scroll-Lock` or `-ui_active` cli). There are 3 ram slots(?) for the `indigo` machine that can take different ram modules for example. Reset the machine to pickup the changes, this will then be saved to the machine `cfg` file.

I do wonder more generally why ram slots are not treated as slot devices instead being under machine config? if it was we could address them on the cli ignoring `-ramsize`. Although that is probably more of a discussion point than should be dealt with in an issue.

**Comment by blappm** [comment]
> @happppp mentioned it was available under `Machine Configuration` in the `Tab` in-machine menu, you will need to activate the UI to configure (`Scroll-Lock` or `-ui_active` cli). There are 3 ram slots(?) for the `indigo` machine that can take different ram modules for example. Reset the machine to pickup the changes, this will then be saved to the machine `cfg` file.
> 
> I do wonder more generally why ram slots are not treated as slot devices instead being under machine config? if it was we could address them on the cli ignoring `-ramsize`. Although that is probably more of a discussion point than should be dealt with in an issue.

Ok, found it now and was able to change it. I think this issue can now be closed.
