### ISSUE TITLE
Wrong bios names in -listxml

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#1216]
All bios names in -listxml are now wrong. See 18wheelr:

<rom name="epr-21576g.ic27" merge="epr-21576g.ic27" bios="bios0" ...
<rom name="epr-21576e.ic27" merge="epr-21576e.ic27" bios="bios0" ...
<rom name="epr-21576d.ic27" merge="epr-21576d.ic27" bios="bios0" ...

must be

<rom name="epr-21576g.ic27" merge="epr-21576g.ic27" bios="bios1" ...
<rom name="epr-21576e.ic27" merge="epr-21576e.ic27" bios="bios2" ...
<rom name="epr-21576d.ic27" merge="epr-21576d.ic27" bios="bios3" ...

In src\frontend\mame\info.cpp (MAME 0.176) this:

for (const rom_entry *brom = rom - 1; brom != m_drivlist.driver().rom; brom--)

was changed to this now

auto entries = rom_build_entries(m_drivlist.driver().rom);
for (const rom_entry *brom = entries.data(); !ROMENTRY_ISEND(brom); brom++)

If you changed:
for (const rom_entry *brom = entries.data(); !ROMENTRY_ISEND(brom); brom++)
to
for (const rom_entry *brom = rom - 1; !ROMENTRY_ISEND(brom); brom--)

-listxml worked again!

mame -listxml sometimes crashed/stops at games roadblstcg and roadblstgu (atarisy1.cpp),
but if you exclude this games src\mame\mame.lst it creates a complete listxml.
The ROM_STARTs and BIOS entries in roadblstcg and roadblstgu must be wrong.

**Comment by happppp** [comment]
probably related: I saw Pernod mention that BIOS selection is broken and
now lists every device.
ref: http://imgur.com/a/1sEIQ

**Comment by Pernod70** [comment]
BIOS selection in bus devices is also broken, it crashes debug builds in miscmenu.cpp.

**Comment by Tafoid** [comment]
GIT as of https://github.com/mamedev/mame/commit/9705b0ccb150ce04ada0fce8cd07b02badcef77a (9 hours ago) seems ok before starting when I start mame64 and select metal slug X from menu, it shows me all the neogeo bioses as expected.  Tested both 5.4.0 and 6.1.0 toolchains, full mame build in 64-bit.  32-bit from 6.1.0 also looks ok.  5.4.0 of 32-bit untested.

The BIOS listing as mentioned above via -listxml does seem to be an issue, though.

**Comment by happppp** [comment]
It's the one from the TAB menu. (press TAB in the middle of the game,
select BIOS Selection)

**Comment by npwoods** [comment]
Did you see pull request #1208?

**Comment by happppp** [comment]
It's merged in now.
The BIOS Selection problem I described still persists.

**Comment by Pernod70** [comment]
Retested today as of https://github.com/mamedev/mame/commit/88779c9b105dae73dfd098269e3a70540da88fcc and Bios Selection menu still contains all devices related to machine, should only contain devices with a rom region.

**Comment by startaq** [comment]
This works now and was probably fixed by one of @cuavas changes.
