### ISSUE TITLE
Please add the Game Street Fighter II' - Hyper Fighting Sr. SF Champion Edition, in the official romset of MAME

### ISSUE THREAD

**Issue by luizaoooobr** [mamedev/mame#12164]
### MAME version

0.264

### System information

all plataforms

### INI configuration details

```INI
No have Details
```

### Emulated system/software

capcom cps1

### Incorrect behaviour

The Brazilian Mr Street Fighter created a version of Street Fighter Especial Champion edition but for the arcade.

Add the following Rom to the emulator with the following CRCs

Game name : sf2hfsce.zip

Sf2hfsceRomDesc[] = {
	{ "s2tsce_23.8f",   0x080000, 0xee74bae8, BRF_ESS | BRF_PRG | CPS1_68K_PROGRAM_NO_BYTESWAP },
	{ "s2tsce_22.7f",   0x080000, 0xeea9b9c0, BRF_ESS | BRF_PRG | CPS1_68K_PROGRAM_NO_BYTESWAP },
	{ "s2tsce_21.6f",   0x080000, 0xd6246802, BRF_ESS | BRF_PRG | CPS1_68K_PROGRAM_NO_BYTESWAP },

	{ "s92-1m.3a",       0x080000, 0x03b0d852, BRF_GRA | CPS1_TILES },
	{ "s92-3m.5a",       0x080000, 0x840289ec, BRF_GRA | CPS1_TILES },
	{ "s92-2m.4a",       0x080000, 0xcdb5f027, BRF_GRA | CPS1_TILES },
	{ "s92-4m.6a",       0x080000, 0xe2799472, BRF_GRA | CPS1_TILES },
	{ "s92sce-5m.7a",    0x080000, 0x75e20f8c, BRF_GRA | CPS1_TILES },
	{ "s92sce-7m.9a",    0x080000, 0xee803831, BRF_GRA | CPS1_TILES },
	{ "s92sce-6m.8a",    0x080000, 0x779c37ed, BRF_GRA | CPS1_TILES },
	{ "s92sce-8m.10a",   0x080000, 0x005867b6, BRF_GRA | CPS1_TILES },
	{ "s92sce-10m.3c",   0x080000, 0xd374589b, BRF_GRA | CPS1_TILES },
	{ "s92sce-12m.5c",   0x080000, 0xd43d5f31, BRF_GRA | CPS1_TILES },
	{ "s92sce-11m.4c",   0x080000, 0x09e7ea4b, BRF_GRA | CPS1_TILES },
	{ "s92sce-13m.6c",   0x080000, 0x136d9999, BRF_GRA | CPS1_TILES },

	{ "s92_09.11a",      0x010000, 0x08f6b60e, BRF_PRG | CPS1_Z80_PROGRAM },

	{ "s92_18.11c",      0x020000, 0x7f162009, BRF_SND | CPS1_OKIM6295_SAMPLES },
	{ "s92_19.12c",      0x020000, 0xbeade53f, BRF_SND | CPS1_OKIM6295_SAMPLES },
	
	A_BOARD_PLDS
	
	{ "s9263b.1a",       0x000117, 0x0a7ecfe0, BRF_OPT },	// b-board PLDs
	{ "iob1.12d",        0x000117, 0x3abc0700, BRF_OPT },
	{ "bprg1.11d",       0x000117, 0x31793da7, BRF_OPT },
	{ "ioc1.ic7",        0x000104, 0xa399772d, BRF_OPT },	// c-board PLDs
	{ "c632.ic1",        0x000117, 0x0fbd9270, BRF_OPT },

Street fighter 2 Special version Champion Edition Arcade created by Mr Street Fighter, mixes the speed of street fighter 2 champion edition with the moves and corrections made in street fighter 2 hyper fighter.

The changes in this version were:
SF2CE speed;
New colors for the characters;
Now when playing against each other, both players can always choose characters;
Adjusted the stun of Ken and Ryu's low kick, which made them dizzy very easily;
When doing hadouken with Ryu and holding a strong punch, the fire hadouken comes out and the character burns like Bison's torpedo;
Ken Got a fake hadouken with high recovery for a counterattack.
The start screen shows the version number of the current game v.1.4.

Game video :
https://github.com/mamedev/mame/assets/56891889/ee696aa7-512c-4836-8595-3fbb8aac2669

Fotos : 
![capa](https://github.com/mamedev/mame/assets/56891889/1a80679b-8b18-4014-80a4-54221ff3a2ea)
![escolha](https://github.com/mamedev/mame/assets/56891889/ce51ef61-714c-4f0b-b22d-78773d2e2010)
![ryueguile](https://github.com/mamedev/mame/assets/56891889/cb646860-3026-4a2f-8ab5-b422e53c5ddd)
![srsf](https://github.com/mamedev/mame/assets/56891889/628d6ab9-8643-417f-99e3-b70d3353df25)

### Expected behaviour

The Game will be added to the official romset of the next version of Mame.

### Steps to reproduce

N/A

### Additional details

All Plataforms.

**Comment by ICEknigh7** [comment]
I think random mods of games go in HBMAME instead.

**Comment by Robbbert** [comment]
Might be an idea to remove attached copyright roms.

**Comment by Robbbert** [comment]
Added to HBMAME as "sf2ce58".

**Comment by Spazmoid1981** [comment]
I have searched everywhere for this and cannot find the specific set - can anyone help me find this?

**Comment by Robbbert** [comment]
ROM requests are not allowed here.

**Comment by Spazmoid1981** [comment]
Fair enough - I actually own several sf2 cps 1 and 2 boards already so I reckon I'm safe to ask but understand the rules are there for all - take care
