### ISSUE TITLE
request: logical AND for custom filter

### ISSUE THREAD

**Issue by customfilter** [mamedev/mame#12173]
### MAME version

0.263

### System information

freeBSD

### Incorrect behaviour

n/a

### Expected behaviour

I would like to request the logical AND operator for custom filters in the MAME GUI.
Current version is using logical OR for custom filters which is quite useless because it adds the filters to a list and not intersects the filters (which is a AND).

We want typically: filter 1 AND filter 2 AND ... so we can make intersection of the filters we want and in this case find the games we want.
Example: give me all games of manufacturer Sega and working state. This needs a AND.

An option AND/OR could be implemented to let the user choose.

**Comment by cuavas** [comment]
Have you even tried it?  It does implement a logical AND between different filter types.

**Comment by customfilter** [comment]
> Have you even tried it? It does implement a logical AND between different filter types.

I suggest you read the difference between AND and OR.
If I add 2 filters for example year 1982 and 1983: the logical AND would be 0 games since a game only has 1 year.
MAME adds them both to the list, so it's using a OR...

**Comment by cuavas** [comment]
I suggest you read carefully – “ It does implement a logical AND **between different filter types**.”

If you add “Available” and “Working” filters, it does a logical AND.  Same for your example of “Working” and manufacturer “Sega”.

Your screenshot shows *two of the same kind* of filter, where as you noted, a logical AND would give an empty intersection, and hence be useless.
