### ISSUE TITLE
pdrift: Power Drift freeze while loading track

### ISSUE THREAD

**Issue by trundeg** [mamedev/mame#12225]
### MAME version

0.264

### System information

Windows 10 64bits, 22H2, Intel(R) Core(TM) i5-4200U CPU, 4Gb RAM. Default video output.

### Emulated system/software

pdrift

### Incorrect behaviour

Power Drift does freeze after some time. Apparently it happens just before loading a new track. One can start the game and not touch it, the demo mode will load regularly a new track, and the game will eventually freeze on a black screen.
I have conducted that test on a vanilla Mame 0264b just extracted, without touching a single configuration line.

### Expected behaviour

No freeze.

### Steps to reproduce

1. extract vanilla Mame 0264b
2. install the game in roms/prdift.zip
3. start the game: mame.exe pdrift
4. wait that the demo mode eventually freezes

**Comment by happppp** [comment]
Yup, known regression. It's already reported over at MAMETesters: https://mametesters.org/view.php?id=8783

**Comment by trundeg** [comment]
My bad, did not looked at the right place...

**Comment by trundeg** [comment]
Hi @happppp. I see the MameTester bug report is quite old now, there is something to do to raise the priority of this issue?
BR

**Comment by angelosa** [comment]
It's already at `critical (emulation)`, just one step below `critical (emulator)`, and iirc you can sort by priority levels at MT ...

**Comment by happppp** [comment]
Severity: Critical (emulation)
There is no higher priority than that. I've poked @galibert several times about it, and with that @ I'm reminding him again.
One might ask, why doesn't anyone else fix it then? I did have a look, but the cause of the bug is outside my expertise (something with multi-threading and TAS opcode)
