### ISSUE TITLE
Nba play by play (nbapbp.zip) became unplayable after the 2D fixes that came with mame 0.233.

### ISSUE THREAD

**Issue by luckysluckys** [mamedev/mame#12241]
### MAME version

0.264

### System information

Windows 10 Pro, 22H2, Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, 16,0 GB

### Incorrect behaviour

While in the gameplay after version 0.233 the game runs very slow under 50% of the correct speed. Previous versions of mame while there where some 2D graphical issues used to play the game almost perfectly. 

### Expected behaviour

The game used to run perfectly

**Comment by Hydreigon223** [comment]
It's because nbapbp has the SHARC dynamic recompiler disabled. We could enable it but I'm not sure if it's a rational decision.

**Comment by luckysluckys** [comment]
Thank you. That would be awesome. Why did it get disabled. Does it break something else? Is there a tutorial of how this could be done?

**Comment by rb6502** [comment]
Usually that happens due to bugs.  Whoever did it would need to comment.

**Comment by luckysluckys** [comment]
Any progress? Could you enable dynamic in the new version? Or give me some direction to do it myself from the source.

**Comment by Osso13** [comment]
The Shark DRC was disabled by Ville Linde here: https://git.redump.net/mame/commit/src/mame/drivers/hornet.cpp?id=5211a003a57a9ca5bb4b117499f313fd8fca4d32
For a local patch you can just uncomment the '//m_dsp[0]->enable_recompiler()' line in init_hornet()

**Comment by ICEknigh7** [comment]
Perhaps DynaRec could be made a global option in mame.ini (disabled by default)?

**Comment by cuavas** [comment]
> Perhaps DynaRec could be made a global option in mame.ini (disabled by default)?

That’s what `-nodrc` is for, but we don’t enable recompilers that are broken.  Working slowly is better than not working fast.

At any rate the question has been addressed.  Begging is just going to annoy people.
