### ISSUE TITLE
Turbo Sub doesn't start

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#1226]
Compiled newest version <a href="https://github.com/mamedev/mame/commit/eda3bb105fa183548759e9ca56e8ca3b9c37ef4c" class="commit-link"><tt>eda3bb1</tt></a>
and only Turbo Sub doesn't start. Worked in MAME 0.176.
Can not figure out why?
Hold down keypad '*' to skip Turbo Sub hw tests on game start or reset.

**Comment by Tafoid** [comment]
This appears to be a regression in how "ROM_COPY" functions.   For example, the driver has:

> ROM_COPY( "main_code", 0x18000 + 0x2000, 0xe000, 0x2000 )

Before August 1st, this was handled and the expression was valid.  Now, it doesn't appear to be working as when I change the 0x18000 + 0x2000 to 0x1a000, the game works once again.  I believe we had a similar issue with ROM_FILL also malfunctioning so there may be a relation.
The push here seems to be the culprit:   https://github.com/mamedev/mame/commit/871656c98caca81aa501c3dbdc8d0a581e2b0178
NOTE:  There were 2 ROM_FILL fixes
https://github.com/mamedev/mame/commit/062017977dbbaae000e8e5ecbeef5a9662e85b9c and https://github.com/mamedev/mame/commit/a475f61dd8e9b22a07c3b9f021b31c5095b4c387 which both may need reexamination/reverting.
Attention @npwoods

**Comment by MASHinfo** [comment]
Fixed by Nathan Woods
http://git.redump.net/mame/commit/?id=b64b470c3266835d3a0e6a7c7cc20f8b88f48d8b
