### ISSUE TITLE
bgfx bug , MAME crash

### ISSUE THREAD

**Issue by gdicnng** [mamedev/mame#12334]
### MAME version

0.265

### System information

windows 10

### INI configuration details

```INI
# test on new MAME , not change configuration
```

### Emulated system/software

not a specific system 

### Incorrect behaviour

Change different type of  BGFX in Tab menu , MAME crash .

### Expected behaviour

I hope it will work the right way.

### Steps to reproduce

1. run a game ,command line : mame knights -video bgfx -window
2. the game start
3. press Tab , show Tab menu
4. choose "Slider Controls"
5. choose "Windows 0 , Screen 0 Effect    default" , press left arrow key or right arrow key to change BGFX type. When change to "Windows 0 , Screen 0 Effect    crt-geom" , press right arrow key  again , MAME crash.

### Additional details

( I speak Chinese , my English is not so good . I'm sorry if my English makes any problem . )

People found this problem here :  https://www.ppxclub.com/forum.php?mod=viewthread&tid=732003

**Comment by happppp** [comment]
Hi, it's already fixed here https://github.com/mamedev/mame/commit/64834145ae2b4b0ad0ed499a7b059792310de276
rel: https://mametesters.org/view.php?id=8857

**Comment by elisimpson** [comment]
Possibly related issue is when the bgfx chain is changed with the slider controls, and the game is quit, the selected chain is saved to the game's cfg file (as expected). If you then restart the game with the bgfx chain set in the cfg the game will crash. The only way to stop the crash is to remove the line from the config with the bgfx chain, or delete the file complete so it recreates without the offending line. Basically, if the bgfx chain is defined in the cfg file the game will always crash.

**Comment by angelosa** [comment]
> Possibly related issue is when the bgfx chain is changed with the slider controls, and the game is quit, the selected chain is saved to the game's cfg file (as expected).

That's not really expected: if MAME crash out of a BGFX shader fumble then it's _not_ supposed to save any kind of configuration file.

**Comment by elisimpson** [comment]
> > Possibly related issue is when the bgfx chain is changed with the slider controls, and the game is quit, the selected chain is saved to the game's cfg file (as expected).
> 
> That's not really expected: if MAME crash out of a BGFX shader fumble then it's _not_ supposed to save any kind of configuration file.

It doesn't crash right when you change to another chain (except in v265). It crashes when you restart the game *after* it has saved the bgfx chain to the cfg. I'm seeing this issue going back many versions, perhaps all the way back to when saving the bgfx chain to the config was first added.
