### ISSUE TITLE
sxevious keeps booting up over and over again 

### ISSUE THREAD

**Issue by phqmourao** [mamedev/mame#12483]
### MAME version

0.266

### System information

Windows 11

### Incorrect behaviour

The game Super Xevious (sxevious) restarts instants after reaching the title screen.

### Expected behaviour

After booting up, the game should remain on the title screen.

**Comment by Osso13** [comment]
Confirmed, regression version seems to be 0.254

**Comment by angelosa** [comment]
Reset isn't caused by watchdog, but rather an intentional snippet where it expects:
```
3C80: cp   $95 ; from $8063 RAM buffer
3C82: jp   nz,$0000
0000: ld   a,$10
0002: ld   ($7100),a
```
Game eventually boots anyway (at least by speeding emu up here), but somehow this is 0x05 the first time around.

**Comment by Robbbert** [comment]
This report has been replicated in Mametesters: https://mametesters.org/view.php?id=8920

Please close this issue and allow continued work to occur at MT.
