### ISSUE TITLE
DECTalk PC ISA Card on PC Hardware

### ISSUE THREAD

**Issue by dnl-nash** [mamedev/mame#12501]
### MAME version

0.266 (mame0266-dirty)

### System information

Arch Linux, 8GB RAM, Core i5-1035G1

### Emulated system/software

ct486, msdos6.22

### Incorrect behaviour

When attempting to run ct486 using the dectalk_isa module, the software for the card cannot be loaded, leading to no speech output. I am running mame on arch linux, although this exact behavior happens with a clean compile from the latest git as well.

### Expected behaviour

Software is loaded on to module, module speaks startup message, can be used with DOS Screen reader

### Steps to reproduce

I am running mame like this:
mame -rompath roms -nvram_directory nvram -samplepath samples -cfg_directory cfg -window -skip_gameinfo ct486 -ramsize 64M -board1:fdcsmc:fdc:0 35hd -board1:fdcsmc:fdc:1 35hd -board2:comat:serport0 null_modem -bitb socket.localhost:1234 -board3:ide:ide:0 hdd -board3:ide:ide:1 cdrom -isa2 sblaster_16 -isa3 dectalk -hard1 dos1.img
Whenever the dectalk module is present, it causes audio distortion, hopefully this is temporary and will not be present should the software be loaded correctly. I am running MSDOS 6.22 inside CT486 with a 256MB HDD. The software for the card can be found here: 
https://winworldpc.com/product/dectalk-pc/4x
The module, according to the manual, contains DIP Switches to set its parameters such as I/O Addresses and IRQ, but since these are not yet emulated, I have been recompiling mame to try to change I/O addresses to rule that out as a potential source of issues, with no success, although the software does see the change of address, it still fails to load the microcode on to the module at and after boot. Here is a verbose log of the attempted load:
C:\DECTALK>dt_conf -i
Attempting to initialize and install DECtalk PC modules.
The system may hang during this test if the modules are
improperly installed.  Wait atleast 1 minute and remove
the DECtalk PC module if this happens
Complete ... installing DECtalk PC modules ...
  Adding module at base 250
One module initialized.
C:\DECTALK>dt_driv -c -l -v
DECtalk PC ... please wait ...
Found DECtalk PC module at base 250
Total of 1 modules installed ...
Serial port traping enabled on COM4:
Parallel port traping enabled on LPT3:
C:\DECTALK>dt_load kernel.sys dtpc.dic lts.exe ph.exe cmd.exe -v
DECtalk PC file loader ... please wait ...
  Loading kernel file kernel.sys
    Loading kernel of 13292 bytes (65 relocs)
      cs:ip == 0040:0010   ss:sp == 047f:0200
Starting load of module at base: 250
Module at 250 (8000) ready to be loaded
Error loading kernel : can not load image.

**Comment by cracyc** [comment]
https://github.com/mamedev/mame/commit/88ddada87a945c4424bd275f190463e8cabc601c restores the way it used to be.
>can be used with DOS Screen reader

It doesn't (and never did) sound good enough for any real use.

**Comment by dnl-nash** [comment]
Thank you so much! I haven't heard this thing boot for over 20 years! Now I can enjoy the old accessible DOS games  that basically got me into technology as a child! Since I kind of suck at c++, what needed to be changed/where was the issue? To improve the accuracy of the emulation/iron out the remaining audio distortion, would swapping out the DSP rom with a ROM from another unit which used the same model DSP have any effect? Once again, thank you!

**Comment by cracyc** [comment]
The problem is the way the 80186 and tms32015 are connected.  The 80186 dma is set up properly but I can't figure out exactly how the tms triggers the transfers.

**Comment by dnl-nash** [comment]
Is it possible that the dt_driv DOS TSR facilitates the transfer somehow? In the install directory c:\dectalk, there's a dt_util command with the -d switch to do a peek/poak operation, although mame's debugger must be miles ahead in terms of capabilities. Although it's m68k based, are there any similarities to the dsp communication in the dtc01 emulated in src/mame/dec/dectalk.cpp

**Comment by cracyc** [comment]
The dtc01 is totally different from the dtc07.  The dtc03 is similar in that it also has an 80186 and a tms320 but that emulation is also broken.

**Comment by Lord-Nightmare** [comment]
the dtc-01 communication between the mc68k CPU and tms32010 DSP is done using a hardware FIFO and some semaphore flags and interrupts, not DMA.
the dtc-07 (and dtc-03?) 80186 CPU<->tms32015 DSP communications are done using the 80186's built in DMA functions, with feedback provided through a means that hasn't been reverse engineered fully yet. There isn't a FIFO, but there might(?) be a 16-bit latch.

**Comment by dnl-nash** [comment]
Thank you for letting me know. I'm sorry for asking all these really stupid questions, but I have absolutely no experience analyzing hardware. Someone had sent me an old dump of what appears to be DEC source, which has references to the two variants of this board in case this would be of any help, the file 'Ad 2/hardware/src/misc/pcboot.c' in the linked archive contains what appears to be DSP RAM tests, plus functions such as read_dsp_ram, and write_dsp_ram, which look like they're touching GPIO pins. I've put the entire source archive on my web server. The link is:
https://nashcentral.duckdns.org/decsrc.zip

**Comment by datajake1999** [comment]
I believe the file named pcboot.c is part of the source for the DECtalk PC boot and diagnostic ROM (the other part of this is bootup.asm). Another thing worth checking out is the source for the operating system that the DECtalk PC runs, and this can be found in dapi/src/kernel.
