### ISSUE TITLE
Mame DEBUG build crashes on startup: "Fatal error: Error: bad downcast<> or device<>.  Tried to convert a 11emu_options to a 11osd_options, which are incompatible."

### ISSUE THREAD

**Issue by FlykeSpice** [mamedev/mame#12557]
### MAME version

41a7b0e04950f33d8906fceb9962812d4865254c

### System information

Android

### Incorrect behaviour

I'm trying to debug my mame android build which is causing odd graphical glitches when I run a namcos22 game, so I rebuilt with DEBUG=1.

I tried launching it on my phone but it didn't even open, instead logging an exception on ADB: ``Fatal error: Error: bad downcast<> or device<>.  Tried to convert a 11emu_options to a 11osd_options, which are incompatible.``

### Expected behaviour

Not throw an exception at startup??

### Steps to reproduce

1. Build a DEBUG=1 build
2. Try to boot it
3. profit

### Additional details

Mame4droid's OSD doesn't use ``downcast<>`` nor ``device<>`` so I'm assured must be originating from somewhere else in mame codebase.

**Comment by holub** [comment]
MAME doesn't officially support Android builds. A better place for discussing such issues is community forum.

**Comment by FlykeSpice** [comment]
I'm opening this issue because it most likely is a upstream one. I'm fine compiling to Android on my own.

Just to confirm I'm rebuilding to linux x64 but it has been stuck in compiling ``luaengine.cpp`` for half a hour now..

**Comment by rb6502** [comment]
That issue does not occur on Windows, Linux, macOS, or *BSD.  And Android is a self-service platform.  We won't deliberately stop it from working, but we don't maintain it either.

**Comment by FlykeSpice** [comment]
Oh so I guess Android NDK's clang is being the oddball here and the downcast is supposed to pass on DEBUG build? I guess I'll close then.

Sorry for wasting your times, next I'm try to rebuild mame to a supported platform before opening an issue.

**Comment by galibert** [comment]
Looks like a bug in the android osd to be precise.

**Comment by galibert** [comment]
In any case, if you want any help on debugging, you'll need to tell us where the exception in happening, e.g. which downcast we're talking about there.  Then maybe we can guess what's going on, but right now it's impossible.

**Comment by rb6502** [comment]
I didn't mean to sound like we don't care earlier; if the bug is *not* in the OSD I'd be glad to see a PR to fix it.  We would like MAME to work better on Android out of the box, but we lack the hardware and manpower to do it.
