### ISSUE TITLE
F1en segas32 scroll text

### ISSUE THREAD

**Issue by mahoneyt944** [mamedev/mame#12573]
https://github.com/mamedev/mame/blob/74b0ef1a99deff5161fa5024acb4cf8f9f85156e/src/mame/sega/segas32_v.cpp#L6-L8

This seems to be related to irqs firing from the interrupt controller.

**Comment by mahoneyt944** [comment]
Update, fixing the vblank timing corrects this jittery text.

**Comment by angelosa** [comment]
I don't see updates to [segas32.cpp](https://github.com/mamedev/mame/blob/master/src/mame/sega/segas32.cpp) / [segas32_v.cpp](https://github.com/mamedev/mame/blob/master/src/mame/sega/segas32_v.cpp) / [segas32_m.cpp](https://github.com/mamedev/mame/blob/master/src/mame/sega/segas32_m.cpp) in more than one year, and text scroll is still glitchy, how this is "fixed"?

**Comment by Robbbert** [comment]
He's fixed it in his own build.

**Comment by mahoneyt944** [comment]
I don't work on current mame, so I'm not familiar with how devs here would like to structure the fix in this code base....However, while working in mame2003+, where we are using comparable video code, I found that the jittery text is caused by the vblank timing. The issue has been corrected and tested to work here. https://github.com/libretro/mame2003-plus-libretro/commit/765f054e027e4dcfe3d166f112d2a9b03310d700

I know there are many differences to count between these code bases but current mame should be able to adjust the vblank to achieve the same result

**Comment by angelosa** [comment]
Well the full story is that the driver is pretending several things here:
1. screen has no timings set (not even `set_vblank_time`), and pretends that vblank-out irq happens at an arbitrary vpos 0
2. does CRTC overrides in `screen_update`. It's already ugly on its own, being s32 essentially a Sega Saturn prototype I also expect that 320 / 416 modes have their own (undocumented afaik) sync frequencies + desync/suspend the video beams during a mode switch.
3. the priority encoder device should be modernized, and while at it find out if anything reads the timer count on the fly.

I'm legit surprised this doesn't cause more issues than ought to be ...
