### ISSUE TITLE
Lua console crashes upon access to screen.orientation(), screen.pixels() , others

### ISSUE THREAD

**Issue by mode80** [mamedev/mame#12635]
### MAME version

0.268

### System information

Is not system specific. Behavior occurs across Windows, Ubuntu and MacOS builds on separate computers. 

### INI configuration details

```INI
Occurs with default mame.ini generated by "mame -cc"
```

### Emulated system/software

Tested while running MAME joust, but also other ROMs

### Incorrect behaviour

segfaults upon access to manager.machine.screens[':screen'].orientation() in the Lua console. also .pixels(), others. 

### Expected behaviour

expected it not to crash

### Steps to reproduce

1. Build latest version fresh from source
2. run "mame -cc" to generate the mame.in then drop joust.zip in the roms folder (have not found other roms to work either)
3. run "mame -console -window joust" to launch the game and the lua console
4. at the console, type "s = manager.machine.screens[':screen']" , followed by "print( s.orientation() )"
5. observe segfault

**Comment by cracyc** [comment]
orientation is a function not a property so use need to use s:orientation().

**Comment by mode80** [comment]
Oh wow. You're right it fails to crash when I access orientation() with a colon instead a period. 

I'd leave this open to say it shouldn't crash either way, but this gets me going. Thanks!

**Comment by cuavas** [comment]
It does more checks in debug builds, but release builds have fewer checks enabled for performance reasons.

Member function call syntax is a pretty basic Lua concept.  It isn’t unreasonable to expect people to understand this.

**Comment by mode80** [comment]
I respect that choice but would offer the following feedback:

Users of scripting languages like Lua do not expect segfaults due to a syntax error. They are explicitly opting for ease-of-use over performance. (Otherwise, they could just customize their build in C++.) Lua is already slow, so I suspect it'd be the right place to favor ease-of-use and safety over speed.
