### ISSUE TITLE
emulating a Pentium III

### ISSUE THREAD

**Issue by kev5688** [mamedev/mame#12637]
I love the way that mame has floppy sounds, beeps, etc. I have been toying around with running Windows 95/98. The best I can run it on is a 486, which is pretty painful. Would it be possible to emulate a Pentium III, which is what my physical hardware that I happen to have that is running Windows 98 is on?

**Comment by jriwanek** [comment]
I'd say (as a non mame developer) almost certainly, but, as you're not able to run anything more than a 486, it's not going to be much use to you.

Whether they'd be interested in doing it however is a seperate issue.

**Comment by angelosa** [comment]
The current state, in order:
- Windows 95 is known to be installable on `ct486` at very least, provided that you give a decent amount of RAM in the CLI/.ini options. If the need is playing games you also need to install a sound card such as the `sblaster_16` and a better video card than the (OEM?) default `svga_et4k`;
- `pcipc` can install and run Windows 98. Notice that requirements are pretty high (has a Pentium MMX), and if the main target is gaming then you better stick with `ct486` instead (anything beyond '97 is a big no, particularly if they also requires an HW renderer);
- `shutms11` emulates to some extent a Pentium III. Best it can do so far is install and run a BeOS 5.0 standalone (cfr. https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=123106#Post123106  ), other OSes installs will fail one way or another for a shopping list of things to implement;

**Comment by wwark** [comment]
Sorry if we change a bit of subject, what is the best for pc 286 and pc 386 ?

**Comment by MooglyGuy** [comment]
Ask on a MAME-related forum. This is not a support forum.

**Comment by angelosa** [comment]
I thought this was a discussion thread, oh well.
