### ISSUE TITLE
Problems with the simulator running

### ISSUE THREAD

**Issue by mxsymeg** [mamedev/mame#12653]
### MAME version

0.268

### System information

Windows 10，64，22H2

### Incorrect behaviour

kaillera and retroarch, running pgm2 system games, the online screen is out of sync!

### Expected behaviour

I'm not sure if it's a problem with the game or the emulator or the online plugin that causes the online failure

**Comment by rb6502** [comment]
We do not support the retroarch cores as they are heavily modified from what we ship, and we absolutely do not support online plugins.
