### ISSUE TITLE
[alpinerd] unexpected control "joy"

### ISSUE THREAD

**Issue by sakura-gamer** [mamedev/mame#12687]
### MAME version

0.268

### System information

N/A

### Incorrect behaviour

The game alpinerd has in its XML a strange "joy" control for P1.
The game has a stick for each player as you can see here:

 https://www.gameandsportworld.com/products/alpine-racer-arcade-game

Why does P1 has a non-existing joystick while P2 does not have this mysterious joystick?

According to me both P1 and P2 should only have a stick and this line `<control type="joy" player="1" ways="2" />` is not needed

Quote from XML:

`<input players="2" coins="1">
			<control type="joy" player="1" ways="2" />
			<control type="stick" player="1" minimum="128" maximum="896" sensitivity="100" keydelta="16" />
			<control type="stick" player="2" minimum="128" maximum="896" sensitivity="100" keydelta="16" />
		</input>`

![afbeelding](https://github.com/user-attachments/assets/207e86d9-5a3b-4171-8afb-87630aa4c0e5)

### Expected behaviour

I would expect to find the same controls in the XML as the original game has.

**Comment by happppp** [comment]
It's the left/right buttons, I sometimes (ab)use IPT_JOYSTICK for direction buttons.
```
	PORT_BIT( 0x0020, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT ) PORT_16WAY // L Selection
	PORT_BIT( 0x0040, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT) PORT_16WAY // R Selection
```

**Comment by happppp** [comment]
Ah, you mean the analog ski controller, yes MAME uses the analog stick input for those. Ignore the player="2", it's just because MAME does not have IPT_AD_STICK_X2, there is no bug.

**Comment by cuavas** [comment]
Please use discussion forums to ask questions like this.
