### ISSUE TITLE
[bparty, magimask, partygrs] unexpected control "lightgun" 

### ISSUE THREAD

**Issue by ghost** [mamedev/mame#12688]
### MAME version

0.268

### System information

N/A

### Incorrect behaviour

The _video slot machines_ **bparty**, **magimask** and **partygrs** have for Player 2 a "lightgun" control, which seems to me impossible for a video slot machine :)
For player 1 they have a correct "gambling" control.

Quote from XML:

`<input players="2" coins="1" service="yes">
			<control type="gambling" player="1" buttons="18" />
			<control type="lightgun" player="2" buttons="1" minimum="0" maximum="16383" sensitivity="45" keydelta="15" />
		</input>`

### Expected behaviour

I would expect not to find a lightgun in any video slot machine. I'm interested to know the reason the lightgun is used here or did I find a bug?

**Comment by ajrhacker** [comment]
These games use touchscreen inputs, which are emulated as the "lightgun" here.

**Comment by ajrhacker** [comment]
The touchscreen controller is a separate device, so MAME automatically adds one to the player count for it. This is admittedly not quite correct for this case, but it's needed for things like multitaps.

**Comment by cuavas** [comment]
Once again, this is not appropriate use of issues.  Please use discussions to ask questions: https://github.com/orgs/mamedev/discussions
