### ISSUE TITLE
Tutankham is unplayable

### ISSUE THREAD

**Issue by MarioMario456** [mamedev/mame#12710]
### MAME version

0.268 (mame0268)

### System information

Linux x86-64

### Emulated system/software

Tutankham (tutankhm)

### Incorrect behaviour

The "shoot left" and "shoot right" buttons, which are required to play the game, aren't emulated.

### Expected behaviour

The "shoot left" and "shoot right" buttons, which are required to play the game, should be available.

### Steps to reproduce

Just run Tutankham. If you open the menu with Tab and select **Input Settings > Input Assignments (this system)**, you'll notice the "shoot left" and "shoot right" buttons are missing.

**Comment by einstein95** [comment]
They are called "Right Stick/Left" and "Right Stick/Right" (and mapped to J/L), as they are not separate buttons but a control stick.
