### ISSUE TITLE
wwfsstar: sprites not drawn at screen border

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#12715]
### MAME version

0.264

### System information

Linux

### INI configuration details

```INI
N/A
```

### Emulated system/software

wwfsstar

### Incorrect behaviour

The sprite on the right side of the screen is not drawn entirely. It appears correctly on the [PCB](https://youtu.be/ccAhtXsKM3k?si=rQxi6k8zpbOesJET&t=161). The bug is also present in the latest commit 1fed8407104.

![0004](https://github.com/user-attachments/assets/fd51a9f5-002d-4c43-a062-370dd30b3e65)

### Expected behaviour

The sprite should be completely visible

### Steps to reproduce

`mame wwfsstar` and wait a few seconds through the demo

**Comment by happppp** [comment]
In the first half of attract mode, it draws black bars at the edges, and sprites looks fine (same on MAME). At the part where it shows The Ultimate Warrior, the screen becomes wider and sprites get cut off. I see the exact same in the video you linked.

**Comment by jotego** [comment]
Indeed. It harder to notice it on that recording but it does happen. Sorry for the red herring.
