### ISSUE TITLE
Mame forget BIOS selection for Neo Geo

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#12724]
### MAME version

0.269

### System information

Debian 12

### Emulated system/software

neogeo

### Incorrect behaviour

Mame forget the selected bios after a second boot from the mame UI.

### Expected behaviour

Mame should keep using the selected bios.

### Steps to reproduce

- Boot mame with `./mame -norc -window -rompath your_rom_path -bios unibios40`
- From mame UI select **Source file > neogeo/neogeo.cpp**.
- Select a game from the list, it boots unibios, press ESC.
- Select a second game from the list, now it boots the **Europe MVS (Ver.2)** instead of **unibios4**.

**Comment by Immersion95** [comment]
Already opened : 
https://github.com/mamedev/mame/issues/11313 
https://github.com/mamedev/mame/issues/11314

It unfortunately is there for more than a year :(
