### ISSUE TITLE
ui.ini read/write is inconsistent 

### ISSUE THREAD

**Issue by ChoccyHobNob** [mamedev/mame#1274]
When loading MAME the ui.ini is read from the ini path, when the configuration is saved it will write it to the first location in the inipath not the same location it was read from. 

e.g.
./mame64 -cc Creates a mame.ini, plugin.ini and ui.ini in the mame directory

in mame.ini the default inipath is 
`inipath                   "$HOME/Library/Application Support/mame;$HOME/.mame;.;ini"`

if you run ./mame64, edit the ui and save the configuration, it doesn't update ui.ini in the mame directory, it saves a new one to "$HOME/Library/Application Support/mame" instead.

**Comment by ChoccyHobNob** [comment]
I would suggest that either 

1. The current directory ( '.' ) should be the first location in the inipath by default
2. That mame should create the ini files in whatever the default first location is instead of the current dir

Option 1 would be my choice.

**Comment by OzFalcon** [comment]
Logged in Mame Testers
http://mametesters.org/view.php?id=6289
http://mametesters.org/view.php?id=6290

**Comment by Bavarese** [comment]
The same happens in MESS. If i load disk images, subsequent CFG and NVRAM writes go to the new folder, instead of the initial / startup folder.
This is especially bad for machines which depend on valid NVRAM values.

**Comment by Robbbert** [comment]
Please add any more comments to one of the above mametesters bug reports.
