### ISSUE TITLE
Mixed regions changes error (only with LUA plugin)

### ISSUE THREAD

**Issue by fedekrum** [mamedev/mame#12757]
### MAME version

0.229 (mame0229)

### System information

MacOS

### INI configuration details

```INI
no mame ini
```

### Emulated system/software

frogger.zip (arcade)

### Incorrect behaviour

Why cheats "rom test", "audio test" and "pixels test " below work using the LUA plugin but the mix of all of them in "mixed test" do not?

Can a cheat have mixed region changes on the same cheat under LUA plugin?

"mixed test" cheat works if mame is started "./mame -cheat" but it does not if started "./mame -plugin cheat"
```
<mamecheat version="1">
<!--  Frogger ROM frogger.zip  -->
 
  <cheat desc="rom test">
    <script state="run">
      <!--  Frogger ROM Patch - frsm3.7  -->
      <action>maincpu.mb@2FFF=00</action>
    </script>
  </cheat>

  <cheat desc="audio test">
    <script state="run">
      <!--  Frogger ROM Patch - frogger.609  -->
      <action>audiocpu.mb@88C=00</action>
    </script>
  </cheat>

  <cheat desc="pixels test">
    <script state="run">
      <!--  Frogger ROM Patch - frogger.606  -->
      <action>gfx1.mb@A63=0</action>
    </script>
  </cheat>
  
  <cheat desc="mixed test">
    <script state="run">
      <action>maincpu.mb@2FFD=C9</action>
      <action>audiocpu.mb@88C=00</action>
      <action>gfx1.mb@A63=0</action>
    </script>
  </cheat>

</mamecheat>
```

### Expected behaviour

To run as it does with the legacy "-cheat" option.

### Steps to reproduce

just activate the "mixed test" cheat using LUA plugin

### Additional details

This behaviour has been reported at [https://www.mamecheat.co.uk/forums/viewtopic.php?p=28031#p28031](url)

**Comment by cracyc** [comment]
m refers to memory regions not mixed.  Anyway this works in .269, it was probably fixed by https://github.com/mamedev/mame/commit/85b9bcd6704f1d265aa8bce4b6e02d656d9d8d9a in .231.  If for some reason use need .229 you can replace cheat_xml.lua with the current version.
