### ISSUE TITLE
ddragon   renamed from Japan to world set 1 ?

### ISSUE THREAD

**Issue by aderumier** [mamedev/mame#12803]
### MAME version

last git version

### System information

/

### Incorrect behaviour

Hi,
since this commit,  ddragon set has rename to "World set 1" ,   instead "Japan)
https://github.com/mamedev/mame/commit/57473cabc124c3b1c772c2d6b7c4fb50c60ad9a9#diff-efc3a7ec3056c1f0ee4c76c5c95e63d40f29801135f06d4ad8f0b772981851aeL2213

![image](https://github.com/user-attachments/assets/70bb7c19-de77-43b4-90ec-7f926187ded5)

(The commit was about to add new clones)

I don't think than the roms content have changed, Currently with my set, I got the Japan message

![image](https://github.com/user-attachments/assets/2a384f74-ce28-406c-888b-23ca69b44f2e)

### Expected behaviour

keep japan as version

**Comment by cuavas** [comment]
@Osso13 can you please fix this, and remember to check patches that shuffle ROM definitions before pushing them?

**Comment by happppp** [comment]
Yes, the parent set is now the World version. No issue here: I don't get the "Japan only" warning on ddragon or ddragona, only on ddragonj and ddragonja.
Either you inadvertedly tested an older version of MAME, or the romset is not up-to-date (MAME should be complaining about checksums).

**Comment by Osso13** [comment]
Thanks hap, just got around to trying to verify this report but I just can't reproduce.
