### ISSUE TITLE
Touch drag gestures that leave the window behave badly

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#12817]
### MAME version

0.269 (mame0269-324-g698e1d89856)

### System information

Windows 10 Pro 22H2 x86-64

### INI configuration details

```INI
window 1
enable_touch 1
```

### Emulated system/software

vgmplay

### Incorrect behaviour

Touch drag gestures that leave the window do not behave correctly.  The menu jumps to an unexpected position when the touch point is outside the window.

### Expected behaviour

The menu should track drag distance intuitively when the touch point is outside the window, either to:
* The touch point itself
* The nearest point to the touch point on an edge of the window

### Steps to reproduce

1. Start MAME in windowed mode on a touchscreen
2. Make the window less than the full height of the screen
3. Bring up a menu that’s too tall for the screen (e.g. the “VGM logs” software list for `vgmplay` via the file manager)
4. Scroll to somewhere in the middle of the menu, so overflow arrows appear at the top and bottom
5. Use a vertical touch drag gesture to scroll the menu, and drag outside the window without lifting your finger
6. The menu will jump to an unexpected point when your finger is outside the window

### Additional details

This won’t be fixed for MAME 0.270, but I’m leaving it here so I don’t forget.  I haven’t heard any user complaints about this, probably because the main use case for touch screen support is full-screen on Android devices.

**Comment by jalopa** [comment]
> This won’t be fixed for MAME 0.270, but I’m leaving it here so I don’t forget. I haven’t heard any user complaints about this, probably because the main use case for touch screen support is full-screen on Android devices.

what are you talking about? There is not even an android build for MAME available....
Only retroarch provides good Android builds.

**Comment by rb6502** [comment]
Of course there's an Android build for MAME available.

https://github.com/seleuco/MAME4droid-2024/releases

**Comment by jalopa** [comment]
Unofficial crap yeah
So take your head out of your ass, you bast.

**Comment by rb6502** [comment]
It's significantly more official than RetroArch, it's the Android build MAMEdev recommends.

**Comment by jalopa** [comment]
Sure, that's why EVERYBODY uses it and retroarch is not used by anybody

**Comment by cuavas** [comment]
Fixed in 0125087cbe3ce69cbd99fb4f65c8ece580e0dd8b
