### ISSUE TITLE
MAME hangs when a controller is disconnected

### ISSUE THREAD

**Issue by chungy** [mamedev/mame#12825]
### MAME version

0.270

### System information

Arch Linux x86_64

### Incorrect behaviour

When a controller is disconnected while MAME is running, the emulator completely locks up and stops responding to anything. Only a `kill -9` can end the process.

### Expected behaviour

MAME to not lock up, as 0.269 did not do this. This is a regression.

### Steps to reproduce

1. Start MAME with a controller plugged in.
2. Disconnect controller.
3. MAME freezes.

### Additional details

`git bisect` shows that commit ed86b07bd56b86a2fe2c090070d7811855e16ea8 introduced the problem. The contents of the commit suggest it might be an SDL problem.

**Comment by happppp** [comment]
Thanks for bisecting it. While I can't reproduce the lockup on Windows SDLMAME, I do see a potential issue. The SDL joystick handler calls reset() during process_event() while the mutex is locked.

Could you try again after this commit? https://github.com/mamedev/mame/commit/59363d3d3f3fe9c1fe8f53ed4b3ca79f8fb6065d

**Comment by happppp** [comment]
Ah, mame.ini joystickprovider auto = xinput here. I can reproduce the lockup with -joystickprovider sdljoy, and can also confirm that the commit I did fixes it.
