### ISSUE TITLE
mame -listsoftware output does not capture all sets in the hash directory

### ISSUE THREAD

**Issue by Shoegzer** [mamedev/mame#12835]
### MAME version

0.270

### System information

N/A

### INI configuration details

```INI
N/A
```

### Emulated system/software

N/A

### Incorrect behaviour

In running `mame -listsoftware`, specific sets found in the mame `hash` directory are not listed.  At the time of 0.270's release, those sets are:

```
3do_m2
advantage
carbeena
gba_ereader
gtfore
ique
lisa2
pippin_flop
sat_vccart
snes_vkun
tandy6k
```

### Expected behaviour

Output of `mame -listsofware` captures all software sets as listed in the `hash` directory.  Ideally, a method of automatically catching sync issues prior to a given point release would prevent this from happening again.

### Steps to reproduce

1. Run `mame -listsofware` and redirect output to a file for analysis
2. Compare sets listed in the output with the contents of the mame `hash` directory and observe that the sets noted above are not in that output

**Comment by cuavas** [comment]
Those software lists are orphaned (not attached to any systems/devices).  `-listsoftware` only picks up software lists attached to a system/device.  Unless you’re volunteering to emulate these things, there’s not much we can do.  The minimaws script does put them in its database, though.
