### ISSUE TITLE
KSYS573: Punch Mania - Sound not working

### ISSUE THREAD

**Issue by Sukotto-1999** [mamedev/mame#12837]
### MAME version

0.270

### System information

Windows 11
GFX: Nvidia GeForce 1650

### Emulated system/software

ksys573, fghtmn, fghtmna, fghtmnk, fghtmnu, pnchmn

### Incorrect behaviour

While the game "Punch Mania 2" works as expected the sound does not work in the previous game Punch Mania even in the English version Fighting Mania

### Expected behaviour

The game should work as expected

### Steps to reproduce

1. Start game

### Additional details

Konami System 573 BIOS with Standard/DSEuromix 2 modes

Someone got the sound working in Punch Mania (either it is a custom build) (described here: https://www.youtube.com/watch?v=t_N_-cDyDKE)

Even though there is a similar issue, i think it must be related to the RTC clock or the registers itself.

**Comment by cuavas** [comment]
These games are marked not working.  They aren’t expected to work.

**Comment by angelosa** [comment]
Pretty positive sound not working is a regression.

**Comment by Sukotto-1999** [comment]
Sorry.
