### ISSUE TITLE
[sega/model3.cpp] request: update driver sega/model3.cpp

### ISSUE THREAD

**Issue by thevirtualarcade** [mamedev/mame#12861]
### MAME version

0.270

### System information

N/A

### Incorrect behaviour

Dear MAME developers,

The driver sega/model3.cpp in MAME is in preliminary state and because of this reason no Sega Model 3 game is working correctly in MAME.

However I found a GPLv3 implementation that's fully working (on the same ROMs as MAME uses): Supermodel

Website:

https://www.supermodel3.com/

Source code:

https://github.com/trzy/Supermodel

Is there anybody interested to update the driver sega/model3.cpp in MAME by using the source code of Supermodel?
The license GPLv3 is fully compatible with MAME!
There are very little issues with the emulation and the games are fully playable. Also the project is in active development.

Best Regards

### Expected behaviour

N/A

**Comment by cuavas** [comment]
Feel free to use SuperModel while you wait for emulation to be improved in MAME.  Also, MAME doesn’t accept GPLv3 code.

**Comment by galibert** [comment]
Because right now there's nobody who feels like doing the work.  We do have the technical capability of doing it, just not the bandwidth.
