### ISSUE TITLE
720: service mode missing in XML

### ISSUE THREAD

**Issue by the-virtual-arcade** [mamedev/mame#12912]
### MAME version

0.270

### System information

N/A

### Emulated system/software

driver: atari/atarisy2.cpp

### Incorrect behaviour

Hi

I'm making a website with INI files for MAME.
One of them is reading "Free Play" dipswitch and "Service Mode" in the XML.

Download the INI file "PCB Properties" here:

https://the-virtual-arcade.github.io/

I found a game, 720, which has the service mode (using F2) but does NOT have it written in the XML.

The following tag is present in the XML for game 720

`<input players="1" coins="3">`

it should be

`<input players="1" coins="3" service="yes">`

Is it possible to add it?

Regards
Harry, Virtual Arcade website

### Expected behaviour

I expect all games with  service mode having a `service="yes"`

**Comment by ajrhacker** [comment]
The ``service="yes"`` XML attribute indicates the presence of non-toggle "Service" inputs (which are usually called "Test" switches on JAMMA boards), not "Service Mode" DIP switches (which are listed separately in the XML).

**Comment by happppp** [comment]
JJ, you already asked here: https://github.com/mamedev/mame/issues/12782
Yes pressing F2 will normally toggle service mode DIP switch if it has one.
