### ISSUE TITLE
Apple CD-ROM "AudioStatus" always returns "playing" (0)

### ISSUE THREAD

**Issue by inexorabletash** [mamedev/mame#12925]
### MAME version

0.270 (ample-270-u2)

### System information

macOS 14.5, Apple M1 chip

### Emulated system/software

Apple II w/ SCSI CD-ROM

### Incorrect behaviour

Per comment in src/devices/bus/nscsi/cd.cpp by the author:
```
// TODO: When you pause, both 7.1's CD Remote and 7.6+'s more modern player still see the
// status as "playing" even though it's definitely returning "paused".  I've tried returning
// every code and nothing works.
```
I am indeed observing this when debugging an Apple II CD-ROM player. 

### Expected behaviour

Expect to see values e.g. 5 when stopped, 1 when paused, 3 when end-of-track reached, etc.

### Additional details

Note this line: https://github.com/mamedev/mame/blob/f290e3bae9e89d858e0f7a8ddfc5c3fbe82dd121/src/devices/bus/nscsi/cd.cpp#L1154 

i.e. despite previous logic, it is always returning 0. If this line is removed, I would expect the correct status to be returned. @rb6502 can you comment on whether this line is intentional?

**Comment by rb6502** [comment]
Ha!  Yeah, removing that line seems to work great.

**Comment by rb6502** [comment]
This and a lot of other things are addressed in https://github.com/mamedev/mame/commit/5346ef0c652890b3efcb23b4ab322fbf662cd313

**Comment by inexorabletash** [comment]
Awesome, thanks for this and the other fixes, @rb6502 !

I noticed this when I was playing with rewriting A2D's CD Remote accessory based on the IIgs NDA, which as you noted worked _better_ with MAME prior to your fixes, but still had issues. Hopefully that's all moot now!

(FWIW, ProDOS-8 player on the Apple CD-ROM Explorer was the basis for the A2D remote; it maintains its own state machine and assumes the drive is doing exactly as it is told when transport commands are issued, with the result that it becomes very confused if the state machines get out of sync. The IIgs NDA works more like I assume a real CD player UI from the 1980s does and (1) issues transport requests to the drive, then (2) polls the drive for its actual state, which makes it more resilient to unexpected behavior.)

**Comment by rb6502** [comment]
Hopefully this works near correct, @inexorabletash !  The A2D CD Remote getting confused when the drive state wasn't what it was expecting was actually helpful in a few  instances (for instance, it got confused that issuing Play while paused didn't unpause, while the Mac OS player simply saw the drive was paused and went with it).  I wouldn't be surprised if there were still a few corner cases around but I hammered it pretty hard and it behaves how I'd expect both in A2D and Mac OS now.

One thing that surprised me a bit is that neither A2Desktop nor the Apple II CD Setup player (which I think is partially Applesoft?  but haven't checked) nor the Mac OS CD Audio desk accessory remove non-audio tracks from the list of playable tracks.  After jump-scaring myself a few times doing late night debugging with headphones I made MAME's CD audio engine ignore the disc data and play silence for data tracks.

**Comment by inexorabletash** [comment]
I know that jump-scare feeling! If it helps, apparently the IIgs NDA remote _does_ skip non-audio tracks; it loads the full TOC (length of each track) to enable display of "time remaining", and it records the state of the control data's bit 4 for later use to skip data tracks.

**Comment by rb6502** [comment]
An update here.  Antoine / Brutal Deluxe found and scanned the actual SCSI command set documentation for the drive, and that resolved a lot of questions.  I've just overhauled the emulation based on that in https://github.com/mamedev/mame/commit/b6f4b47ccc48c60d6fb65fbaeddd7e389c93b05f .

**Comment by inexorabletash** [comment]
I was finally able to verify this in a recent MAME build. Working great now!
