### ISSUE TITLE
[MAMEUI] Ugly font rendering in folder list

### ISSUE THREAD

**Issue by patrickhlauke** [mamedev/mame#12921]
### MAME version

0.270.0

### System information

Windows 11

### Incorrect behaviour

With apologies for posting this here - it seems https://github.com/Robbbert/mameui does not allow issues to be filed, and registration on https://www.1emulation.com/forums/forum/125-mameui/ doesn't seem to be working (initial emails to confirm email address don't seem to send). Please pass this on to @Robbbert

When setting a font other than the default, the folder list appears ugly/janky - seems related to antialiasing.

![interface using the default MS Sans Serif font looks correct](https://github.com/user-attachments/assets/34494473-cb13-448c-927d-4abe09a1cd5e)
![changing the font used to Roboto makes the folder list appear ugly, with each letter showing a strong halo/antialiasing](https://github.com/user-attachments/assets/19e1b650-b2f8-46c5-8c4f-77cb7e01767f)

### Expected behaviour

Setting a different font should still render correctly in the folder list.

### Steps to reproduce

1. Change the font for MAMEUI to a different font

**Comment by happppp** [comment]
Hi, yes you're posting this at the wrong github, and this issue will be closed.
@Robbbert please let him know where to go, but don't handle the issue report here.

**Comment by Robbbert** [comment]
@happppp Thanks for handling it. Posting it here is probably the worst thing he could have done - there's plenty of alternatives.

**Comment by patrickhlauke** [comment]
> there's plenty of alternatives

as said

> https://github.com/Robbbert/mameui does not allow issues to be filed, and registration on https://www.1emulation.com/forums/forum/125-mameui/ doesn't seem to be working (initial emails to confirm email address don't seem to send)

if there are any more of these "plenty" of options, they're well hidden. regardless...wanted to make sure this bug was filed somewhere. peace out.
