### ISSUE TITLE
Can't compile a TinyMAME version of Heathkit H89

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#12930]
### MAME version

0.272

### System information

WIndows 10 64 Bit
GCC 11.2.0 (Official)

### INI configuration details

```INI
make -j5 TARGET=mame SUBTARGET=tinymame SOURCES=src/mame/heathzenith/h89.cpp
```

### Emulated system/software

src/mame/heathzenith/h89.cpp

### Incorrect behaviour

I can't compile a TinyMAME version of Heathkit H89 (heathzenith/h89.cpp) or a SUBTARGET version with mess.flt and 'heathzenith/h89.cpp'.
The compiler did not compile the bus files (src\devices\bus\heathzenith\*). Only in a full MAME version the compiler compiles
all 'heathzenith' files.

### Expected behaviour

A working TinyMAME version or a full MESS version.

### Steps to reproduce

TinyMAME:
make -j5 TARGET=mame SUBTARGET=tinymame SOURCES=src/mame/heathzenith/h89.cpp

SUBTARGET with mess.flt:
make -j5 SUBTARGET=mess

### Additional details

Heathkit changes (heathzenith/h89.cpp):
https://github.com/mamedev/mame/commit/8353b2bd9383eff880497ece1a447db87fa65016
https://github.com/mamedev/mame/commit/b5ee6d82d2cc298ba0d4f1752747761446925dc5

**Comment by happppp** [comment]
Try again after https://github.com/mamedev/mame/commit/51fe1dc2cce2f997000eab37fb51b67ae4770839

**Comment by MASHinfo** [comment]
Works again! Many thanks!
