### ISSUE TITLE
Maybe somebody can activate my mamedev forum account

### ISSUE THREAD

**Issue by kosuodhmwa** [mamedev/mame#13007]
Hi there

i don't get the activation since one week - maybe somebody can forward my info to mamedev forum admin.

username is: edslkajewq

(maybe it looks like spam, the random generated username and because of that it will not be activated?)

thanks in advance

best regards jan

**Comment by Robbbert** [comment]
I've been informed that your account has been approved.

**Comment by kosuodhmwa** [comment]
thx, got mail :-)
