### ISSUE TITLE
[Linux] MAME 0.272 fails to build

### ISSUE THREAD

**Issue by Shoegzer** [mamedev/mame#13034]
### MAME version

0.272

### System information

* OS: Linux Mint 22 / kernel 6.8
* CPU: Intel i7-10870H
* Compiler: gcc-14.2.0

### INI configuration details

```INI
N/A
```

### Incorrect behaviour

MAME 0.272 fails to compile, with the following in the build log:

```
<command-line>: fatal error: /home/testing/Desktop/mame/mame0272/src/osd/sdl/sdlprefix.h: No such file or directory
compilation terminated.
make[2]: *** [osd_sdl.make:966: ../../../../linux_gcc/obj/x64/Release/osd_sdl/src/osd/interface/inputseq.o] Error 1
make[1]: *** [Makefile:19: osd_sdl] Error 2
make[1]: *** Waiting for unfinished jobs....
...
Archiving liboptional.a...
make: *** [makefile:1290: linux_x64] Error 2
```

### Expected behaviour

MAME compiles.  

### Steps to reproduce

Attempt to build MAME 0.272 with `make -j9 TOOLS=1 NOWERROR=1`

### Additional details

MAME 0.271 compiles successfully.

Failed build log: [build.log](https://github.com/user-attachments/files/17967560/build.log)

**Comment by mgarlanger** [comment]
Have you tried doing a `make clean`, followed by a `make REGENIE=1`?

**Comment by Shoegzer** [comment]
Thanks, this is a clean build environment with fresh build directories.  I haven't tried REGENIE=1 but I'm doing that now.

I also updated my post above with more information from the build log regarding the build issue (seems to be SDL2 related?)

**Comment by Shoegzer** [comment]
@mgarlanger Okay it builds with REGENIE=1 so I suppose I'll close this issue, though I wasn't aware that's now a build requirement - do you know if it's been stated somewhere that I missed?

**Comment by galibert** [comment]
It tends to be required when mame.lst changes and you're not in a SOURCES= build.
