### ISSUE TITLE
Region of games 

### ISSUE THREAD

**Issue by mitch03** [mamedev/mame#13081]
I wanted to ask if games that are listed as USA could also maybe listed as Europe as its the same rom (i think) such as Donkey Kong - it seems strange that only US Set 1 and US Set 2 is available and none for World or Europe
http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=dkong&search_id=1

any help would be great

**Comment by MooglyGuy** [comment]
No

**Comment by mitch03** [comment]
> No

thank you for that great insight of respectable knowledge

**Comment by arcadehistory** [comment]
Import a game from USA in Europe don't means it was "released" in Europe as an European version. It was just imported... It still an US version (Nintendo of America copyright in the case of DK).

**Comment by cuavas** [comment]
Use forums to ask questions.

**Comment by mitch03** [comment]
> Import a game from USA in Europe don't means it was "released" in Europe as an European version. It was just imported... It still an US version (Nintendo of America copyright in the case of DK). Also, if I remember well, most of the DK boards in the early times in Europe were imported from Japan instead (Nintendo Co. copyright). Quickly, there were replaced by Crazy Kong versions (lowest cost).

so arcade releases in regions are different to console releases in regions?
