### ISSUE TITLE
Joystick - Ubuntu - Same joystick detected multiple times

### ISSUE THREAD

**Issue by gabrielklein** [mamedev/mame#1334]
One of my joystick is configured as "joy0", the other one as "joy1".
When I start a game, my first joystick is configured as "joy0", "joy1", "joy2"
(I can control the 2 players with one joystick).
My second joystick is configured as "joy3".

Operating System: Ubuntu 16.04
Configuration: 2 joysticks (digital, 4 axis)
Configured as /dev/input/js1 and /dev/input/js2 (js0 is the )

I did the test on two different computers.

Version of mame: 0.176

I have compiled the git version "fe5a6b5" (46102 commits)
I have the same issue.

---------

In the logs I see:

> Joystick: Start initialization
> Input: Adding Joy #0: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 1
> Input: Adding Joy #1: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 1 mapped to logical id 2
> Joystick: End initialization

Later

> Joystick: Start initialization
> Input: Adding Joy #0: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 1
> Input: Adding Joy #1: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 2
> Input: Adding Joy #2: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 1 mapped to logical id 3
> Joystick: End initialization

and Later

> Joystick: Start initialization
> Input: Adding Joy #0: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 1
> Input: Adding Joy #1: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 2
> Input: Adding Joy #2: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 3
> Input: Adding Joy #3: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 1 mapped to logical id 4
> Joystick: End initialization

**Comment by gabrielklein** [comment]
In input_sdl.cpp

Just after
		osd_printf_verbose("Joystick: Start initialization\n");

I add
		osd_printf_verbose("Joystick: Number Joystick %d\n", SDL_NumJoysticks());

And I see the correct number of joystick
>> Joystick: Number Joystick 2

> Joystick: Number Joystick 2
> Input: Adding Joy #0: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 1
> Input: Adding Joy #1: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 2
> Input: Adding Joy #2: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 0 mapped to logical id 3
> Input: Adding Joy #3: DragonRiseInc.GenericUSBJoystick
> Joystick: DragonRise Inc.   Generic   USB  Joystick  
> Joystick:   ...  5 axes, 12 buttons 1 hats 0 balls
> Joystick:   ...  Physical id 1 mapped to logical id 4
> Joystick: End initialization
>

**Comment by gabrielklein** [comment]
This function seams to be problematic.
static void devmap_register(device_map_t *devmap, int physical_idx, const std::string &name)

I fixed it by adding a break

> 	for (i = 0; i < MAX_DEVMAP_ENTRIES; i++)
> 	{
> 		osd_printf_verbose("Joystick: Found %s / %s /  %d\n", name.c_str(), devmap->map[i].name.c_str(), i);
> 		if (strcmp(name.c_str(), devmap->map[i].name.c_str()) == 0 && devmap->map[i].physical < 0)
> 		{
> 			devmap->map[i].physical = physical_idx;
> 			found = 1;
> 			devmap->logical[physical_idx] = i;
> 			// >>>>>>>>>>>> here
> 			break;
>                         // <<<<<<<<<<<<
> 		}
> 	}
> 

It works with my joysticks.
I haven't commited any code (and don't expect to commit any).

**Comment by bradhugh** [comment]
I'll work on this.

**Comment by bradhugh** [comment]
I have a fix I'll push after the release. After this fix, SDL joysticks with the same name will no longer collapse onto a single input. However since SDL gives no way to uniquely identify joysticks so we can persist them across initializations, if they are enumerated in a different order in subsequent initializations by SDL, they will get swapped (player 1 vs player 2), etc. In other words, you and your buddy might have to switch controllers after starting the game.
