### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lcrjeff** [mamedev/mame#1372]
<img width="490" alt="48d86b8c-f9f8-48a9-8cd8-f7955d1fd34b" src="https://cloud.githubusercontent.com/assets/2390203/18299842/ccf52ba0-74f6-11e6-84fe-6d83a926a395.png">

**Comment by rb6502** [comment]
What are your OS X and Xcode versions?

**Comment by lcrjeff** [comment]
sorry, To deal with some housework thess days.
I upgraded the Xcode,7.3.1 OS X10.11.4
make error：
<img width="490" alt="7d2c077f-d43a-4263-abc4-bd9fcf9063f8" src="https://cloud.githubusercontent.com/assets/2390203/18458769/783c2380-7996-11e6-9a11-4beeafd6f9da.png">

**Comment by lcrjeff** [comment]
make success .
how to run android-projert
<img width="490" alt="aec97509-9bd8-4224-8012-c34ab69befd0" src="https://cloud.githubusercontent.com/assets/2390203/18460559/2144f6c4-79a5-11e6-85a8-a5a9d941b69c.png">

**Comment by bradhugh** [comment]
@lcrjeff I'm assuming you're saying this is working for you now? Closing. Please reopen if I'm mistaken.
