### ISSUE TITLE
dragon32/dragon64 problem with DSK/VDK floppy images

### ISSUE THREAD

**Issue by milliluk** [mamedev/mame#1383]
Works in 0.152. On IRC a dev mentioned that it worked after the new FDC floppy code.

Mounting a .DSK or .VDK seems to have no effect. Type "DIR" and you get a "?NR Error" (Not Ready).

Verified on dragon32 and dragon64. Likely affects the whole family.

**Comment by startaq** [comment]
Do you have specific disk image that can be used to demonstrate the issue?

**Comment by Pernod70** [comment]
Looks like motor control (bit 2) is missing in dragon_fdc_device::dskreg_w.
This machine would really appreciate a softlist from someone that knows it.

**Comment by npwoods** [comment]
Second startaq's comment - this is likely easy to fix we could get a specific test case

**Comment by milliluk** [comment]
@npwoods Thank you for all your work on the 8 bit micros over the years. It was your recent changes to the 6883 that got some people excited about this again.

Here are some test disk images. Just mount and type "DIR".

https://github.com/milliluk/emulator-test-disks/tree/master/dragon64

**Comment by npwoods** [comment]
Looking into this, just a note - DISK.DSK and DISK.VDK seem to be identical.

> It was your recent changes to the 6883 that got some people excited about this again.

Wow, I'm amazed that anybody noticed :-)

**Comment by npwoods** [comment]
Took a quick look at this, it isn't obvious to me what is happening, but I'm less familiar with the Dragon and its been a while since I've looked at the FDC code.  I'll keep people posted.

**Comment by milliluk** [comment]
I added additional test images:
https://github.com/milliluk/emulator-test-disks/tree/master/dragon64

    dfe6e36c4911b0190b7751377614e212 D1.DSK
    4c9f328e2028d01a595dc5fbf839196d D1.VDK
    38ce4b341e663a9c833d8b92500cac7c D2.DSK
    846e9846abb57088b9a165ec9e7394e8 D2.VDK

**Comment by npwoods** [comment]
Hey quick question - has this ever worked?  I went and tried this on a bunch of MESS versions, all of the way back to 0.101.  Also, is this issue on Mametesters?

**Comment by npwoods** [comment]
Also, I'm assuming that nobody out there has disassembled the Dragon ROMs, in the spirt of the "CoCo Unravelled" series?

**Comment by npwoods** [comment]
Noticed that the INTRQ and DRQ callbacks are null on the FDC.  I'm guessing this can't be right.

**Comment by galibert** [comment]
It can, but it's rare.  You can get the information by polling.  I think
einstein does it?

  OG.

**Comment by milliluk** [comment]
Testing with the D1.VDK image "DIR" works in mess0153b but not mess0154b.

**Comment by npwoods** [comment]
So my findings:
- In MAME 0.153, a non-maskable interrupt is fired in response to one of the FDC interrupts (INTRQ I believe).  This doesn't happen in the TIP
- Between MAME 0.153 and MAME 0.154, the CoCo/Dragon FDC code got updated (src/emu/bus/coco/coco_fdc.c), and configuration that was shared between the Dragon and the CoCo got made CoCo only

**Comment by npwoods** [comment]
I tried changing the dragon_fdc declaration to the below


`static MACHINE_CONFIG_FRAGMENT(dragon_fdc)`
` 	MCFG_WD2797_ADD(WD2797_TAG, XTAL_1MHz)`
`	MCFG_WD_FDC_INTRQ_CALLBACK(WRITELINE(coco_fdc_device, fdc_intrq_w))`
`	MCFG_WD_FDC_DRQ_CALLBACK(WRITELINE(coco_fdc_device, fdc_drq_w))`

While this seems to get closer - the NMI interrupt kicks in - I now get an ?RT ERROR.  I'm not even sure what that error is.

Next step is to reverse engineer the working Dragon emulation in MAME 0.153, so I can later compare it with the present to see what went wrong.

**Comment by milliluk** [comment]
RT is "Record Type" -- probably a geometry problem

See page 60: http://dragondata.worldofdragon.org/Publications/IntroDOS/Intro-DragDOS-v1.pdf

**Comment by npwoods** [comment]
Here is what I've been able to figure out so far, and hack around.
- At PC=$C2DF, the Dragon ROM invokes FDC command $88.  $8x is read sector, and the device was not registering as ready.  I hacked around this problem by making wd_fdc_t::is_ready() always return 'true'.
- At PC=$C2E1, the Dragon ROM gets into a loop where it is querying the PIA, which ultimately seems to be hooked up to the DRQ line on the FDC.
- The FDC seems to go through some state transitions (SPINUP_DONE ==> SETTLE_DONE ==> SCAN_ID), but seems to get hung up on wd_fdc_t::live_run(), in a clause where floppy->time_next_index() returns attotime::never.  According to the comments, this happens when there is no disk loaded, but that isn't the case.

I'm not quite sure what is going on - this seems related to the FDC rewrite (hence the hack and what I saw in live_run), but I have not figured everything out yet.

**Comment by npwoods** [comment]
Ok I've figured it out.  Pernod70 was right - the motor was not being properly turned on, whereas it was for the CoCo FDC.  I came up with a quick and dirty hack to turn on the motor and got the DIR command to work (yay!)

Calling it a night for now - as far as I am concerned, the hard part is done and I want to spend a little bit more time cleaning up this code.

**Comment by npwoods** [comment]
Still looking at this - one of the things that I've concluded after some effort of disentangling the code is that the codebases for the CoCo and Dragon FDCs should really be separated out from each other.

**Comment by milliluk** [comment]
It is unnecessarily fragile. Also, there's some real time clock stuff in there that doesn't belong. That is all aftermarket hardware and, while it sometimes shipped as part of a disk cartridge, probably should live in a separate file.

There's also the issue of disk ROMs. Many existed commercially and even these were commonly modified by users to set disk parameters. If you specify the ROM it as a -cart it conflicts with the Multi-Pak. If you specify it as a -slot it conflicts with the FDC. They don't save/restore correctly. And there's no way to turn off the ROM checksum warning from the command line any more (?). Also at least one "machine" (coco3dw1) exists just to enable someone's pet ROM -- and even that ROM is no longer in common use.

**Comment by npwoods** [comment]
#1413

**Comment by startaq** [comment]
Closing this since a fix has been committed.
