### ISSUE TITLE
LEGACY_FLOPPY_OPTIONS still lingering in drivers--tons of broken disk images as a result

### ISSUE THREAD

**Issue by milliluk** [mamedev/mame#1386]
Among others, Atari, NES, Apple2, PC and CoCo still have LEGACY_FLOPPY_OPTIONS_START blocks in their drivers. This breaks an enormous number of existing disk images that rely on file extensions and other internal structure to set disk geometry.

I actually maintain a fork where you can swap between the old and new floppy code. I set breakpoints and verified that the "identify" and "construct" handlers are called by the legacy floppy driver but not the new one.

**Comment by Tafoid** [comment]
Please checkout and test current GIT.  There was a push this morning that dealt with file extensions which had been broken in 0.176 #1290

**Comment by milliluk** [comment]
Thanks for the pointer to that thread. The specific extensions I'm having problems with (see coco_fdc.cpp) require opening the file to determine the geometry. It can't be handled just by extension. I'm against that merge in its current state.

**Comment by rb6502** [comment]
The Apple II switched to using a newer FDC based on the newer code by default a while ago; the legacy code is still available for certain advanced use cases.

**Comment by milliluk** [comment]
@rb6502 You might want to dig into this a little bit deeper. Yes, last year all the Western Digital floppy code was replaced across tons of drivers with a more accurate emulation. The previous code was deleted from the project.

The previous code had hooks to allow disk images to be opened first in order to determine the geometry. The new code does not call these hooks. As a result, tens of thousands of disk images for platforms from NES to PC no longer work.

I maintained a fork for a while but gave up when whats-his-name went on six consecutive mass rename binges for no reason.

**Comment by drencorxeen** [comment]
Is it possible the new WD FDC code base that was changed could also be causing the issues I have been having in the issue I reported and the data corruption problem that was bug ticketed on mametesters with the coco12.cpp and coco3.cpp drivers that use WD FDC chips?

**Comment by rb6502** [comment]
The correct fix is for systems using the new WD FDC and the LEGACY_FLOPPY_OPTIONS to add a correct system-specific format handler using the new C++ format in src/lib/formats.

Apple II and /// now use new format routines with the new FDC code (WozFDC, not WDFDC) and ultimately lost no compatibility.

**Comment by rb6502** [comment]
@drencorxeen No, your problem is related to the Color Computers not properly addressing multiple drives, so you end up with sectors written to the wrong disks and stuff.

**Comment by startaq** [comment]
@milliluk: What are you talking about? Lot of disk formats open floppy disk images to determine the geometry. For example, see `src/lib/formats/jvc_dsk.cpp`, specifically `jvc_format::parse_header`.

**Comment by milliluk** [comment]
@startaq The old floppy code had geometry hooks. Somebody replaced the floppy code but ignored the hooks in many drivers. The hooks are still there -- grep for LEGACY_FLOPPY_OPTIONS to find them. Note the functionality they provide. Now set breakpoints and note they are not called. In September 2016 someone tried to fix it by adding a simple file extension mapping. However that wasn't really a fix because some file extensions (as you note) require that the file be opened to determine geometry.

**Comment by startaq** [comment]
`LEGACY_FLOPPY_OPTIONS` is still there because some minor parts of MAME still use the legacy floppy system. I'm going to close this issue unless you can provide a concrete example of something that no longer works.

**Comment by rb6502** [comment]
In particular, the CoCo *isn't using* any LEGACY formats at all now - the NitrOS-9 problem was an issue with jvc_dsk.cpp, which isn't a legacy format at all.  With that fixed, I can't find any images for any of the cited systems that don't work.

**Comment by Robbbert** [comment]
> I'm going to close this issue unless you can provide a concrete example of something that no longer works.

Nothing further heard, so closing.
