### ISSUE TITLE
这个就是拳皇模拟器的最新版本代码吗？

### ISSUE THREAD

**Issue by luxiaoming** [mamedev/mame#1422]
如题

**Comment by angelosa** [comment]
Only English please.

**Comment by a65090482** [comment]
Is this the latest version of kof's simulator code?

> Only English please.

Software translation: Is this the latest version of kof's simulator code?

It's the same as the title.

**Comment by lowtrucks** [comment]
lol.

**Comment by galibert** [comment]
Yes, github.com/mamedev/mame has the latest version of mame, including the
neogeo/kof code.

Regards,

  OG.

**Comment by a65090482** [comment]
F: Why did Kof translate into 拳皇?
Q: The King Of Fighters literally means 格斗之王 in Chinese. However, if translated in this way, it is not "domptuous" enough for Chinese people, so the translation of "拳皇" appears.
