### ISSUE TITLE
src/devices/bus/ti99x/gpromport.h should be modified for override compiling warning

### ISSUE THREAD

**Issue by meesokim** [mamedev/mame#1426]
$ make
GCC 5.3.0 detected
Compiling src/mame/drivers/ti99_4x.cpp...
In file included from ../../../../../src/devices/bus/ti99x/datamux.h:19:0,
                 from ../../../../../src/mame/drivers/ti99_4x.cpp:50:
../../../../../src/devices/bus/ti99x/gromport.h:190:15: error: 'virtual bool single_conn_device::is_grom_idle()' can be marked override [-Werror=suggest-override]
  virtual bool is_grom_idle();
               ^
../../../../../src/devices/bus/ti99x/gromport.h:227:7: error: 'virtual bool multi_conn_device::is_grom_idle()' can be marked override [-Werror=suggest-override]
  bool is_grom_idle();
       ^
../../../../../src/devices/bus/ti99x/gromport.h:267:7: error: 'virtual bool gkracker_device::is_grom_idle()' can be marked override [-Werror=suggest-override]
  bool is_grom_idle();
       ^
cc1plus.exe: all warnings being treated as errors

bool is_grom_idle(); --> bool is_grom_idle() override;
It will be resolved if you add override keyword for each line.

**Comment by mizapf** [comment]
Hmm ... you're also using gcc ... why does my 5.3.1 not complain?

**Comment by happppp** [comment]
Because they added that later?
The MINGW package(updated with 'pacman' tool) is at gcc 6.1.0

**Comment by happppp** [comment]
Oh, Miso Kim is using GCC 5.3.0, hmm yeah then it's weird it's not detected
in 5.3.1 :|

**Comment by meesokim** [comment]
It's done. Thank you.
