### ISSUE TITLE
New patch for sms.cpp: fix Out Run sound in FM mode

### ISSUE THREAD

**Issue by enikland2** [mamedev/mame#1496]
Micko asked me to post a diff here as an alternative for patch submission.
It fixes a bug present for a long time that I haven't noticed until recently.

Changelog:

- sms.cpp: fix Out Run sound in FM mode

--
Enik
[mame_sms_outrun_fm.txt](https://github.com/mamedev/mame/files/518784/mame_sms_outrun_fm.txt)

**Comment by p1pkin** [comment]
pushed, thanks.

**Comment by enikland2** [comment]
Hi MetalliC!

 

Thank you for having pushed my patches!

Could you make a little adjustment for me?

In this last patch, I used "set_output_gain(0, ..." but would be better if had used "set_output_gain(ALL_OUTPUTS, ...".

I did the former based on an example found in Mameworld Programming forum, but the latter would be more appropriate for  my patch.
The function is used in files src/mame/machine/sms.cpp and src/devices/bus/sg1000_exp/fm_unit.cpp.


I want to avoid open another issue just for this adjustment. I would be glad if you or someone else could do this change for me!


--

Enik

 

Sent: Monday, October 10, 2016 at 10:58 PM

**Comment by p1pkin** [comment]
all occurrences have to be replaced ?

**Comment by enikland2** [comment]
I think so, the 4 occurrences of each file. It's really necessary for YM2413, because has two outputs, Melody (MO) and Rhythm (RO), that are joined together in the circuit line that can be switched on and off, according to Enri's schematics (http://www43.tok2.com/home/cmpslv/Mark3/Fm70.htm). About the SN6489 chip, it have only one output line, but the chip doesn't have internal connection to the FM Unit. The unit connects with the audio out line of the Mark III, that hypothetically could be merged output of more than one line. The change at least will match what is declared by the MCFG_SOUND_ROUTE macro in machine config.

**Comment by p1pkin** [comment]
ok, done
