### ISSUE TITLE
compile error plz help me

### ISSUE THREAD

**Issue by wpdnjs87** [mamedev/mame#1529]
i see

/Users/hongjewon/Library/Android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../../../../../android-project/app/src/main/libs/armeabi-v7a/libSDL2.so: unsupported ELF file type 2
../../../../../3rdparty/SDL2/src/main/android/SDL_android_main.c:27: error: undefined reference to 'SDL_Android_Init'
../../../../../3rdparty/SDL2/src/main/android/SDL_android_main.c:29: error: undefined reference to 'SDL_SetMainReady_REAL'
../../../../../3rdparty/SDL2/src/main/android/SDL_android_main.c:39: error: undefined reference to 'SDL_strdup_REAL'
../../../../../3rdparty/SDL2/src/main/android/SDL_android_main.c:47: error: undefined reference to 'SDL_strdup_REAL'
../../../../../3rdparty/SDL2/src/main/android/SDL_android_main.c:53: error: undefined reference to 'SDL_strdup_REAL'
../../../../../3rdparty/SDL2/src/main/android/SDL_android_main.c:67: error: undefined reference to 'SDL_free_REAL'

please help me

**Comment by zx70** [comment]
This seems to be a similar situation, hope it brings you on the right track:
https://github.com/eliben/pyelftools/issues/86

**Comment by startaq** [comment]
Android isn't really a supported configuration right now.
