### ISSUE TITLE
 mame/hash/segacd.xml: duplicate entry

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#1532]
There are two games that have the same chd file:
ecco2a (ecco - the tides of time (usa, alt).chd) and eternalc (eternal champions - challenge from the dark side (usa, alt)) both have sha 9fb665727fdc629df195ef315eef17eae9661f4d.
I don't believe in such coincidences, this looks like a copy'n'paste problem.

**Comment by Tafoid** [comment]
I'd like to get this fixed ASAP if someone could please provide the right SHA1 hash for each image I will apply the changes needed.  We release next week and I don't want a software list in MAME that can never be completed.

**Comment by 0-wiz-0** [comment]
Fixed in https://github.com/mamedev/mame/commit/a74e7b041e5d3231c10b244894e298aba710689d, thanks!
