### ISSUE TITLE
popen not supported

### ISSUE THREAD

**Issue by lab313ru** [mamedev/mame#1538]
```
[string "function os.executef(cmd, ...)..."]:167: 'popen' not supported
stack traceback:
        [C]: in function 'io.popen'
        [string "function os.executef(cmd, ...)..."]:167: in function 'os.outputof'
        C:/msys64/home/Uladzimir/mame/scripts/genie.lua:1294: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:84: in function 'dofile'
        [string "_WORKING_DIR        = os.getcwd()..."]:41: in function '_premake_main'
make: *** [makefile:997: vs2015] Ошибка 1
```

Trying to compile in Msys64.
Cmd line is:  `make SOURCES=src/mame/drivers/megadriv.cpp vs2015 PYTHON_EXECUTABLE=c:/Python27/python SUBTARGET=megadrive REGENIE=1`

**Comment by bradhugh** [comment]
@lab313ru Given the abundance of forward-slashes, I'm assuming you're trying to build inside the conemu shell provided by msys64?  Can you try just building by running the win32env.bat file from a cmd.exe prompt?  Does that work fine?

**Comment by Robbbert** [comment]
User never got back to us, and it's been over a year. Closing.
