### ISSUE TITLE
New patch for sms: Document the Sports Pad modes (and change the default) used by Sports Pad Soccer (Jpn)

### ISSUE THREAD

**Issue by enikland2** [mamedev/mame#1644]
I did another test to verify if everything was working well with the sms devices and found a new issue related with the Japanese cartridge Sports Pad Soccer that was introduced with the improved emulation of the audio control port ($F2) of the Japanese SMS, based on Charles' findings. This new patch documents the controller modes used by the cartridge and change the default to run correctly on the Japanese SMS. The previous default was set to run on the Sega Mark III, but there's a bug in player 2 input handling code of the ROM when that mode is used, and I think the smsj driver will be more used to run Japanese games anyway.

Maybe this will be the last patch from me. Everything seems to work as expected and I don't have the skills to implement the link need for Gear-to-Gear and the keyboard link used by F-16 Fighting Falcon.

--
Enik

[mame_sms_sportssc.txt](https://github.com/mamedev/mame/files/574392/mame_sms_sportssc.txt)

**Comment by p1pkin** [comment]
pushed, thank you.
