### ISSUE TITLE
Driver SOURCES and missing parents

### ISSUE THREAD

**Issue by Tafoid** [mamedev/mame#1654]
Here is a list (as of 11-11-2016) of driver specific SUBTARGET builds which created binaries referencing a parent or clone of the driver:

8080bw.cpp
adam.cpp
apple2e.cpp
apple2gs.cpp
at.cpp
cps2.cpp
galaxian.cpp
hec2hrp.cpp
multfish_boot.cpp
pacman.cpp
segas16b.cpp
whitestar.cpp

All of these will trigger validation and will printf spam all sets each time an emulation is run listing all non-existing parents or clones.  Most of these are merely ceremonial in that they don't actually share roms between parent and clones and are simply there to note that the game is basically the same despite bring on hardware which is different.  A minor annoyance, maybe, but something that should be addressed as there are times where actual parts of the missing romset are shared from a driver not bring compiled, as in the following cases, and will not function if your sets are stored in the most popular "split" format where each setname only holds what is unique to that machine:

tst_invd - 8080bw.cpp (parent: invaders)
spceking - 8080bw.cpp (parent: invaders)
All sets in multfish_boot.cpp (many parents)
pinguinos - pacman.cpp (parent: pengo)
pengojpm - pacman.cpp (parent: pengo)
pengopac - pacman.cpp (parent: pengo)
tetris1 - segas16b.cpp (parent: tetris)
tetris1d - segas16b.cpp (parent: tetris)

How can we approach this and allow these parent machine setnames to be compiled with the single driver?  Do we simply ignore the issue and chalk it up to the cost of doing business?

**Comment by cuavas** [comment]
It's not worth adding hacks for this stuff, just tell people to include the parent set's sourcefile as well.

**Comment by angelosa** [comment]
As @cuavas stated, closing.
