### ISSUE TITLE
Minimum Android version no longer matches what's expected in the toolchain

### ISSUE THREAD

**Issue by RQWorldblender** [mamedev/mame#1753]
Since this commit 6a21f6dd, I've guessed that this means that MAME can no longer be built for or even run on Android 4.x. When I saw the next release 0.179 came out, I saw that the AndroidManifest.xml has not changed much, except for the version. I still saw that the minSdkVersion is still 14, which equals Android 4.0. However, now that the toolchain requirements changed, I would've gotten confused about whether I can still run MAME on at least Android 4.4.x, and I decided to assume that this would not be the case. The minSdkVersion has to be changed to at least 21, which equals Android 5.0, so that it is made clear that MAME cannot be installed on Android 4.x. I also suggest looking at targetSdkVersion and see if that needs to change as well.
If 0.178 is truly the last version that supports Android 4.x, I might consider porting this version to MAME4Droid when I find enough time to do this, as I'm getting impatient for a version of MAME4Droid that's completely open source (by allowing commercial use), but without giving up support for any Android versions that its 0.139 version supports.
By the way, do the toolchain changes imply that only ARM 64-bit is supported, or is ARM 32-bit still supported (this applies to Android and any modern ARM-based computer that has a different primary operating system, including single-board computers [such as the Raspberry Pi family])?

**Comment by galibert** [comment]
Mame is still 32-bits clean, no matter the cpu or OS.

  OG.

**Comment by mmicko** [comment]
@RQWorldblender you are right, manifest was marked to be 4.0 compatible, fixed it now. 
Thanks for this.

Please note that SDK is moved up to make 32bit and 64bit requirements unique.
Our goal is to support mostly Andorid based devices with controller for start (like NVidia Shield and TV) 
and then see how it goes. 32bit android will be supported till they support it by NDK so no worries there.

**Comment by RQWorldblender** [comment]
Good! It's finally been made made clear that I really need Android 5.0 or greater to run the latest MAME version.
So when I can find enough time, I'll look into porting MAME 0.178 (last version that supports Android 4.x) for MAME4Droid.

**Comment by mmicko** [comment]
To be clear we are not using anything API specific so you can use latest
code and it would work on 4.0 API, it is more to prevent future problems
since x64 was introduced in 5.0 API and then should be easier to maintain
supporting just one API.
