### ISSUE TITLE
Garbage in debugger history at startup

### ISSUE THREAD

**Issue by JoakimLarsson** [mamedev/mame#1802]
When entering the debugger and press up arrow, as for stepping back in command history, garbage is put in the command text box and it is not possible to do down arrow to get rid of it. Not critical but probably something uninitialized that needs to be fixed at some point.

**Comment by andrew-gardner** [comment]
Which debugger are you using?  Input history is managed by each debugger module individually.

**Comment by JoakimLarsson** [comment]
Ahh, the mingw on win-7

**Comment by zx70** [comment]
I think the question was: which CPU type were you debugging when you saw the garbage ?   ..6502? Z80?

**Comment by andrew-gardner** [comment]
He answered the question as I would have liked, actually.  I don't know anything about the windows debugger though, so someone who does will have to fix it up.

**Comment by cuavas** [comment]
WTF github parsed my commit message and auto-closed this issue.  That's pretty dodgy - it should leave it open to allow the fix to be verified.  Anyway, it's fixed for me in 44eb44996aa4c67c455751c8f3ff291f11680f4f
