### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by anikom15** [mamedev/mame#1811]
Compiler error on msys64

> $ make
> GCC 6.2.0 detected
> Compiling src/emu/rendfont.cpp...
> In file included from ../../../../../src/emu/rendfont.cpp:17:0:
> ../../../../generated/emu/uismall.fh:1:14: error: 'UINT8' does not name a type
>  extern const UINT8 font_uismall[];
>               ^~~~~
> ../../../../generated/emu/uismall.fh:2:7: error: 'UINT8' does not name a type
>  const UINT8 font_uismall[] =
>        ^~~~~
> In file included from ../../../../../src/emu/ui/cmdrender.h:11:0,
>                  from ../../../../../src/emu/rendfont.cpp:19:
> ../../../../generated/emu/ui/uicmd14.fh:1:14: error: 'UINT8' does not name a type
>  extern const UINT8 font_uicmd14[];
>               ^~~~~
> ../../../../generated/emu/ui/uicmd14.fh:2:7: error: 'UINT8' does not name a type
>  const UINT8 font_uicmd14[] =
>        ^~~~~
> In file included from ../../../../../src/emu/rendfont.cpp:19:0:
> ../../../../../src/emu/ui/cmdrender.h: In member function 'void render_font::render_font_command_glyph()':
> ../../../../../src/emu/ui/cmdrender.h:89:23: error: 'font_uicmd14' was not declared in this scope
>   if (ramfile.open_ram(font_uicmd14, sizeof(font_uicmd14)) == osd_file::error::NONE)
>                        ^~~~~~~~~~~~
> ../../../../../src/emu/rendfont.cpp: In constructor 'render_font::render_font(render_manager&, const char*)':
> ../../../../../src/emu/rendfont.cpp:174:44: error: 'font_uismall' was not declared in this scope
>   osd_file::error filerr = ramfile.open_ram(font_uismall, sizeof(font_uismall));
>                                             ^~~~~~~~~~~~
> make[2]: *** [emu.make:1114: ../../../../mingw-gcc/obj/x64/Release/src/emu/rendfont.o] Error 1
> make[1]: *** [Makefile:70: emu] Error 2
> make: *** [makefile:983: windows_x64] Error 2
>

**Comment by Robbbert** [comment]
Do a clean build.

**Comment by anikom15** [comment]
Fix'd with 'make clean'.
