### ISSUE TITLE
visible space in dat infos

### ISSUE THREAD

**Issue by legluondunet** [mamedev/mame#1813]
Hello,

dat infos does not appear clearly, all space are visible, is it a known bug?
[image 1](
https://lh3.googleusercontent.com/mRcEm5uRBColBGYu2BpExuVIl0JUCOVZxqmCTlbYopJYEM_ArmzgLWU5rKZ-C_pDVnU0bbX_7hKlzQ=w1920-h1080-no)
[image 2](https://lh3.googleusercontent.com/rXcYb0ps7s4bzbPpcBOK_KKfWU1WxPxvDAHSdeHW1DUnGxNipo2WuCQxUBJqA2vIfxNwxo3oU9_niQ=w1920-h1080-no)

Thank you for your help.

LGDN

config:
Mame 0.180 compiled from official mame sources
Ubuntu 17.04 Zesty Zapus 64 bits
NVIDIA GeForce GTX 770
official Ubuntu Nvidia drivers 367.57 - 1920x1080

**Comment by cracyc** [comment]
Fedora has the same problem with Liberation Sans as uifont (even though the copy of the font that ships with Libreoffice on Windows work fine).  If you use -uifont "Dejavu sans" then it displays properly.

**Comment by legluondunet** [comment]
I can reproduce this bug with most of my installed fonts (default fonts in Ubuntu distribution).
With "Dejavu sans" I have some visible space, not in "general info", but in the others tabs "Mameinfo", "Mamescore"
"Courier" is the only font I haven't any visible space but it's ugly.

**Comment by cuavas** [comment]
The UI code attempts to align text using the Unicode "Hair Space" character.  Using a font that lacks this character will result in visible substitute characters as your seeing.  I don't think this is really a bug.

**Comment by legluondunet** [comment]
Please could you reopened this issue, it is a bug in the way that MAME does not show correctly infos text on Ubuntu with all fonts installed.

**Comment by legluondunet** [comment]
@cuavas does that mean that all Linux fonts lack Unicode "Hair Space" character ?

**Comment by legluondunet** [comment]
You don't let me another choice than reopen another issue for this problem.

**Comment by cuavas** [comment]
What do you think opening another issue will achieve?  You're just going to have to install a font that includes typographical space characters or put up with it.

**Comment by legluondunet** [comment]
There is a bug here, I don't know if it is a Mame bug or a Linux/Ubuntu bug. But here we have a result that is not expected:  text info does not show correctly on Linux/Ubuntu. Did you try the last Mame version on Ubuntu? Did you install a font to resolve the problem? If yes wich font did you use?
Why all the fonts on Ubuntu does not have the Unicode "Hair Space" character"?
We should answer to this questions to better understand why MAME does run as expected on Linux/Ubuntu.
Please reopen this bug, this discussion should be open to everyone, or I will open a new issue.

**Comment by JoakimLarsson** [comment]
I think the "bug" is in the debian package for Linux, it should depend on that font package which will cause the font to be installed automatically. Please file the bug report with the maintainers of the MAME debian package, they are not here.

**Comment by legluondunet** [comment]
Hello Joachim, I don't use a debian package, I always compile Mame from source.

**Comment by JoakimLarsson** [comment]
Then you have to install the font the same way you need to install a compiler to compile the source, it is a prerequisite.

**Comment by cuavas** [comment]
MAME can load fonts from arbitrary TTF files on Linux.  Just download some font with wide coverage like Adobe Source or Google Noto Sans, drop it in your working directory, and run `mame -uifont NotoSans-Regular.ttf` substituting the filename of the font you chose.

MAME also has support for BDF bitmap fonts and includes a small pixel size BDF font that covers most European languages as well as "7-bit katakana".  You can use it with "-uifont uismall.bdf" but a bug in the current versions of MAME means that could crash (it's fixed for the next release).

**Comment by legluondunet** [comment]
@JoakimLarsson I already installed a lot of fonts on Ubuntu from official Ubuntu repo. Mame always shows a white square instead a space with all of them.  @cuavas Do you use MS Windows OS? If so, could you try some of this official fonts from Ubuntu repo: https://www.dropbox.com/s/1bpeyvwafysq2nu/UbuntuPolices.zip?dl=0 . When you use them, does Mame show infos text with empty white square instead of space?
I tested with Google fonts, Mame shows correctly infos text with them.
I need to know if I have to open a bug on Ubuntu.

**Comment by galibert** [comment]
We're going to fix the problem (eventually).  Using spaces for right flush
is insane.  It's just fragile code, so we have to be cautious.

  OG.
