### ISSUE TITLE
Fixing the PowerPC emulation for Power Macintosh 6100

### ISSUE THREAD

**Issue by maximumspatium** [mamedev/mame#1853]
I'd like to provide some details of how to fix the pmac6100 issue described in mac.cpp/NOTES.

In short, the pmac6100 target doesn't work due to an MMU fault when accessing the CPU ID register at 0x5FFFFFFC from the 68k emulator. An attempt to read from this address causes a DSI exception that cannot be handled properly and finally results in kernel panic.

The Nanokernel's VM is unable to resolve this address because the DSISR register doesn't contain a valid value when the DSI exception is thrown. DSISR should contain proper flags describing the cause of the DSI exception (either hash table miss or protection violation or something else). MAME's implementation just places the faulty address into the DSISR register instead of setting the required bits.

Interestingly, ppc_device::ppccom_translate_address_internal() seems to return the proper flags in the last statement. At the time being, anything but success seems to be simply ignored by the caller of this method.

I'd like to fix this issue but I don't fully understand how the PowerPC DRC emulation works. IIUC, ppc_device::static_generate_memory_accessor() would be the right place to start.

Could anyone provide me with useful hints and advices on how to proceed?

Thank you in advance!
Best regards
Max

**Comment by rb6502** [comment]
Hi!

I'm the maintainer of the Mac emulations, and I also wrote the 601-specific portions of the PowerPC emulator.  As my notes say, I suspected a problem with the MMU, but not that it would be the DSISR register value.  Let me buzz the original PPC author, Aaron Giles, and see if he remembers anything useful.

Regards,
-RB

**Comment by maximumspatium** [comment]
> As my notes say, I suspected a problem with the MMU, but not that it would be the DSISR register value.

Strictly speaking, this issue is directly related to the MMU so you've made the right prediction! The DSISR register is used to describe the MMU failure so the exception handler could take the appropriate action. If DSISR contains garbage the exception handler will fail as well. It should be surely fixed ASAP because it may impact other PowerPC targets...

**Comment by cuavas** [comment]
It's actually unlikely to affect other PowerPC targets in MAME because the 601 wasn't a widely-used chip. It's actually rather unusual, having a POWER MMU, MQ register and saturating integer instructions as well as PowerPC multiply/divide instructions. All subsequent PowerPC chips lack the MQ register and saturating inductions, and have a PowerPC MMU.

**Comment by rb6502** [comment]
Actually, the portion of the MMU in question *is* shared with other PowerPC chips.  The 601 is a one-off, but not *that* much of a one-off.

**Comment by rb6502** [comment]
This commit: https://github.com/mamedev/mame/commit/795eaa2f631af317bd332d4cdc11f2f504e76fb8

...attempts to fix the issue.  I can't tell if it's improved or not because the pmac6100 won't boot if the debugger is active.  Need to track that down.

**Comment by maximumspatium** [comment]
> I can't tell if it's improved or not because the pmac6100 won't boot if the debugger is active.

Yes, debugging pmac6100 with `mess64 pmac6100 -debug` doesn't work since [mame0173](https://github.com/mamedev/mame/releases/tag/mame0173). Issuing the 'g' command, either with or without an address, will cause the debugger to loop forever.
We need to fix the internal debugger first. I'll open another issue...

Meanwhile, I'll try to back port your fix to an earlier MAME release and look whether it works. We shouldn't hope too much though - Power Macintosh 6100 will likely not work due to lack of the proper hardware like PRAM. I'll plan to roll out several patches fixing the CPU first and then adding the required emulation. It's a step-by-step process and we'll finally make it working!

**Comment by maximumspatium** [comment]
> The fix should backport cleanly; I don't think anything's changed in the PowerPC core for a while.

The backport went fine but the fix doesn't work because the DSISR bits (DSISR_XXX in ppccom.h) are in the wrong order (PowerPC counts its bits from left to right as opposite to Intel chips). Can these bits be reversed without breaking the whole PowerPC EMU stuff?

> Cuda may in turn need a 6522VIA fix I got from the linux-m68k guys to communicate properly with the main CPU.

For the time being, PDM's HWInit fails to identify CUDA PRAM. The boot chime volume will be therefore set to a conservative value which, in turn, is ignored by the AWAC hardware emulation so everything is okay for now but I'd like to see it fixed when all other roadblocks are removed.

**Comment by maximumspatium** [comment]
> This commit: 795eaa2 attempts to fix the issue.

I'm happy to confirm that your fix (backported to [mame0169](https://github.com/mamedev/mame/releases/tag/mame0169)) does work as expected with all DSISR_XXX bits reversed like that:

```
DSISR_DIRECT    0x00000001 ---> DSISR_DIRECT    0x80000000
DSISR_NOT_FOUND 0x00000002 ---> DSISR_NOT_FOUND 0x40000000
```

and so on. We'd need another small patch to correct these values and eventually a test to ensure that nothing is broken.

Thank you very much!

**Comment by cuavas** [comment]
Applied the fix for the DSISR bits on data storage exceptions.  Alignment exceptions don't appear to be implemented yet.

**Comment by rb6502** [comment]
Terrific!  Now we need to track down the problem with the debugger.

**Comment by maximumspatium** [comment]
> Now we need to track down the problem with the debugger.

Here we go: https://github.com/mamedev/mame/issues/1867

**Comment by maximumspatium** [comment]
Closing the issue because everything is working now.
