### ISSUE TITLE
Debugging PowerPC targets is broken since MAME0173

### ISSUE THREAD

**Issue by maximumspatium** [mamedev/mame#1867]
As the title says, debugging PowerPC targets is broken since [mame0173](https://github.com/mamedev/mame/releases/tag/mame0173). Steps to reproduce:

`./mess64 pmac6100 -debug`

Then go to the debugger window and issue the following command:

`g 68090090`

The debugger will loop forever.

After a long and heavy `git bisect` session I finally was able to isolate the commit that introduced the regression: https://github.com/mamedev/mame/commit/c6144ee9b15118224d4813041b763b11749e5e0a

This commit changes some PowerPC DRC internals in the way they don't work properly on my 2,53 GHz Intel Core i5 MacBook Pro.

I have no clue how to fix it. Moreover, it would be a good idea to test whether it works on other Intel CPUs as well.

Best regards
Max

**Comment by villedevs** [comment]
I suspect this is caused by the fact that XMM registers are volatile on Linux/Mac.
I'd try #ifdef X64_WINDOWS_ABI on float_register_map.

**Comment by rb6502** [comment]
Commit 822c3b4232b0a66ce92bba7a24084678004af444 should fix this in trunk; it works for me on my MacBook Air Core i7.

**Comment by maximumspatium** [comment]
> Commit 822c3b4 should fix this in trunk

Yes, it works now. The issue can be closed...

**Comment by maximumspatium** [comment]
Thank you very much!
