### ISSUE TITLE
Adding a hopper device as an alias of the ticket dispenser

### ISSUE THREAD

**Issue by james-wallace-ghub** [mamedev/mame#1915]
Having looked into building something that resembles a coin/medal hopper for the many titles that could do with it (casino titles etc), I realised that it's basically a ticket machine with a few extras. My temptation is to just fork ticket.cpp and add more hopper components, but my issue is how accurately we want to do this, since I'm reluctant to do anything that will make it possible for people to use MAME as a practical gambling device by giving them hooks to work with. For that reason, I'm putting this out as an issue before I write anything, to try to get some wider discussion form the userbase.

**Comment by angelosa** [comment]
On top of my head, improve statistics for internal Bookeeping Info Menu, so i.e. the Coin Outs count from the hopper.
Other than that an inherited object of ticket_dispenser_device should be fine.

**Comment by ajrhacker** [comment]
None of the coin/medal hoppers I've added require any actual extras. Those on amusco and big10 may be dumber (but faster) than most, since the code doesn't check for any feedback.

**Comment by james-wallace-ghub** [comment]
In most cases I'd reckon hoppers are dumb, in that there's an output sensor, but they don't usually count themselves. Adding to the coinout is probably all that would be needed, or maybe that's something for the mechanical meters that are often fitted to these things. Anyway, I'll start with forking the ticket for now and see what happens

**Comment by angelosa** [comment]
Not a fan about how `hopper_device' does things under the hood, but not enough to leave this issue open anyway.
