### ISSUE TITLE
Debugging MAME with GDB/LLDB doesn't work properly on Mac

### ISSUE THREAD

**Issue by maximumspatium** [mamedev/mame#1941]
As the title says, I'm trying to debug MAME/MESS with a debugger on the Macintosh. I've tried both GDB and LLDB. Unfortunately, none of them works properly. Although I can step through the code, I can examine neither variables nor arguments nor class members.

`frame variable` in LLDB returns nothing. GDBs `print [some var]` returns garbage. I compile MAME using the following options:

`make SUBTARGET=mess DEBUG=1 SYMBOLS=1 OPTIMIZE=0`

I suspect a problem with compiler options. Can someone of the maintainers of the build system comment on this issue?

My compiler:

```
clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
```

And the debuggers:

```
gdb --version
GNU gdb (GDB) 7.9.1
```

```
lldb --version
lldb-360.1.70
```

I'm using Mac OS X 10.11.6 (El Capitan)

Thank you in advance!
Best regards
Max

**Comment by balr0g** [comment]
You need to also specify ```SYMLEVEL=2``` or ```SYMLEVEL=3```. However, this will cause binary sizes to increase, in some cases greatly. ```DEBUG=1``` is not always a good idea since it enables debug asserts and can change the behavior of emulation.
To reduce binary size it is possible to do a single-driver build with the following syntax:
```make SUBTARGET=mac SOURCES=src/mame/drivers/mac.cpp SYMBOLS=1 OPTIMIZE=0 SYMLEVEL=3 -j5```
(change the -j parameter to number of cores plus one.)

**Comment by maximumspatium** [comment]
Thank you, balr0g! `SYMLEVEL=3` solves my problem. It looks like `DEBUG=1` is required though. Omitting this causes LLDB to display raw ASM instead of C++ code.

I suggest to add a detailed description of how to do the debug build to the MAME documentation. Otherwise, it's rather difficult to find any information on this in the web.
