### ISSUE TITLE
Crediting when using mame's code

### ISSUE THREAD

**Issue by ocornut** [mamedev/mame#1948]
Hello MAME/MESS team!,

I am using @pullmoll Z80 emulator+disassembler in a project, which is BSD-3 clause license. And would like to add credits for it in a spot that's easy to notice (aside from including the actual BSD-3 license). Since I recall the MAME word is trademark I was wondering if I can/should refer to MAME in the credits and generally how to refer to that piece of code. for "user friendly" crediting.

e.g
```
This software uses MAME's Z80 Emulator by Juergen Buchmueller.
```

Would that be ok?
Or would you prefer,
```
This software uses Portable Z80 Emulator by Juergen Buchmueller.
```
etc.
Thank you!

(PS: That is aside from including the full license along with the binary)

**Comment by pullmoll** [comment]
It's true that I started this core many years ago. Meanwhile a lot of people have contributed essential improvements to the code. I doubt that mentioning MAME touches the trademark issue, but other devs may want to chime in on that part. For me it's perfectly fine, if anyone using the code under the license they choose mention me or do not. For a project being itself 3-clause-BSD licensed I see no problem at all.

**Comment by cuavas** [comment]
Hi @ocornut,

The MAME trademark restrictions mainly apply to the naming and marketing of your derivative work, not acknowledgements.  You can use the MAME name when acknowledging copyright, etc.  MAME's Z80 core is distributed under the terms of the [3-Clause BSD license](https://opensource.org/licenses/BSD-3-Clause).  This requires you to reproduce the copyright notice in the documentation distributed with source and/or binary forms of the derived work.  In the licensing section of your documentation, you should include this text:

>Portable Z80 Emulator Copyright 1997-2017 Juergen Buchmueller and the MAME team
>
>Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
>
>1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>
>2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
>
>3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
>
>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by ocornut** [comment]
Thank you for your answer! I'll use this blurb.

Do you think I can merge both Emulator and Disassembler this way?
```
Portable Z80 Emulator Copyright 1997-2017 Juergen Buchmueller and the MAME team
Portable Z80 Disassembler Copyright 1997-2017 Juergen Buchmueller and the MAME team

[full bsd-3 clause text]
```

My credits are already quite long and creating an issue with Music playback =) so if I can't merge them I may just have to compile the disassembler out of the executable and omit crediting disassembler in binary, but I'd prefer crediting.

**Comment by cuavas** [comment]
The full license text doesn't have to be in the be in the executable itself, you can put it in an accompanying text file or PDF if that makes it easier.  As for coalescing credits for related parts of MAME, that would be fine.  You could make it minimal like:

>Portable Z80 Emulator and Disassembler Copyright 1997-2017 Juergen Buchmueller and the MAME team
>
>Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
>
>[remaining license text]

If you've got credits in the executable itself and limited space, just put the first line there ("Portable Z80 Emulator and Disassembler Copyright 1997-2017 Juergen Buchmueller and the MAME team") and put the full license in an accompanying text file along with full licenses for the rest of the stuff you use (file would typically be called "COPYING", "LICENSE", "LEGAL" or similar).

**Comment by ocornut** [comment]
Executable nor disk space are issues, but embedded platforms (such as iOS, also consoles) don't have an easy way to include text file that the user can access so I presume it has to be accessible within the software. 

For now what I did is that I kept the first line big and made the other lines small (but still readable) and my Credits don't feel too visually spammy for the casual end user. My plan B is to add a separate menu aside from the "nice" Credits roll, will just the Licensing stuff. 

Thanks again for your answers and all of MAME teams for your work and licensing some of the core stuff as BSD. Aside from the obvious impact of MAME, the new licensing I think is having a great impact on game preservation and game tech exploration projects (I didn't need to think twice and could use your Z80 emulator instead of using a clunky old attempt at mine).

(PS: I am the author of dear imgui which is used by one of your debugger implementation and it is super cool to think that pieces of my code are used in mame somehow)

**Comment by ocornut** [comment]
Our game is out for various consoles (Steam June), with MAME bits in the credits.
https://twitter.com/lizardcube/status/855112712229138433
(That screenshot is cut out but the full link/licence are in the credits roll)

Trailer:
https://twitter.com/lizardcube/status/853984668928139264

We created quite a novel hybrid beast.. part emulation, part high level systems, lots of low-level hack (1989 engine upgraded to increase framerate, widescreen). It is hard to describe but I will be writing a tech blog post soon. We could have used any Z80 emulator because what we need isn't very demanding in term of accuracy, but it was nice to use what's probably the best one. Thanks all.

**Comment by mmicko** [comment]
Omar thanks a lot for news. Great to see team and Juergen got credits.

Congrats on release
