### ISSUE TITLE
Screen color wrong with BGFX

### ISSUE THREAD

**Issue by startaq** [mamedev/mame#1953]
Using the BGFX backend the screen color of monochrome systems is wrong. Example:

`mame apricot -video bgfx` -- displays in black and white
`mame apricot -video opengl` -- displays in black and green

**Comment by B2K24** [comment]
Confirmed here as well.

**Comment by cuavas** [comment]
Should be fixed in 5671484fc87fc11b536a0b0f6cb0efb1e680d489 (PR #10858)
