### ISSUE TITLE
Gauntlet tiles mapped incorrectly in graphics viewer

### ISSUE THREAD

**Issue by alinsavix** [mamedev/mame#1957]
When using the graphics viewer (:gfxdecode page 0) to view tiles for Gauntlet and Gauntlet II, the tiles do not map correctly into the numbering that the game itself uses for the tiles. For example, the viewer shows the first 9 tiles, starting at tile 0, to be a ghost -- but the game itself considers those tiles to be starting at tile 0x800 rather than tile 0.

This mismatch has been verified with both the tile viewer in the game's self test, and in the game's code itself.

The ROMs themselves are obviously mapped correctly as far as the game is concerned (because the games work), so this is almost certainly a problem specific to the graphics viewer.

The specific banks that are swapped are:

  0x0  <-> 0x800
  0x1000 <-> 0x1800

The tiles starting at 0x2000 are fine

**Comment by cuavas** [comment]
The gfx viewer is really just a developer convenience.  It isn't guaranteed to map directly to anything.  In many drivers the decoded gfx aren't actually used by the graphics code (e.g. see laserbat, catnmous and osborne1 where the gfxdecode is only used by the F4 viewer and the emulation code accesses RAM/ROM directly).  If there are no emulation issues it isn't a bug.

**Comment by alinsavix** [comment]
Pity. It'd be much more useful for reverse engineering work if the tile numbers lined up.
