### ISSUE TITLE
Did the single driver build break recently?

### ISSUE THREAD

**Issue by JoakimLarsson** [mamedev/mame#1962]
$ make OVERRIDE_CC=clang OVERRIDE_CXX=clang++ SUBTARGET=fccpu20 SOURCES=src/mame/drivers/fccpu20.cpp
Clang 3.9.0 detected
C:/Users/jolar/work/mame/scripts/genie.lua:1328: attempt to call a nil value
stack traceback:
        C:/Users/jolar/work/mame/scripts/genie.lua:1328: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:84: in function 'dofile'
        [string "_WORKING_DIR        = os.getcwd()..."]:41: in function '_premake_main'
makefile:1012: recipe for target 'build/projects/windows/mamefccpu20/gmake-mingw-clang/Makefile' failed
make: *** [build/projects/windows/mamefccpu20/gmake-mingw-clang/Makefile] Error 1

**Comment by rb6502** [comment]
Works for me, but as always I never specify SUBTARGET= because that's *always* broken the build for me.

**Comment by cuavas** [comment]
Single-driver builds are working for me, and I _always_ specify `SUBTARGET=` because I get bizarre issues if I don't use it.  It's probably something about your specific source file upsetting the dependency generator.

**Comment by JoakimLarsson** [comment]
ok, my setup is not 100% as it should so you are most propably right, I close this issue
