### ISSUE TITLE
Graphics became blur after enabling hlsl，how to make it clearly？

### ISSUE THREAD

**Issue by Aniark** [mamedev/mame#1969]
I have capture those image to compare them

![4](https://cloud.githubusercontent.com/assets/10991795/21954311/437c6206-da88-11e6-862f-083d5fc2d850.PNG)

enable hlsl

![6](https://cloud.githubusercontent.com/assets/10991795/21954312/438cfd96-da88-11e6-86e8-58fce392aef6.PNG)

disable hlsl

![5](https://cloud.githubusercontent.com/assets/10991795/21954328/a03e0ef4-da88-11e6-984d-d79744c93d10.PNG)

enable hlsl

![7](https://cloud.githubusercontent.com/assets/10991795/21954354/3e1b4fce-da89-11e6-8c1f-3c07935140dd.PNG)

disable hlsl

By the way, I have maked sure the following options are set correctly:

video d3d
filter 0

and here is my setting for hlsl:

# DIRECT3D POST-PROCESSING OPTIONS
#
hlslpath                  hlsl
hlsl_enable               1
hlsl_oversampling         0
hlsl_write                auto
hlsl_snap_width           2048
hlsl_snap_height          1536
shadow_mask_tile_mode     0
shadow_mask_alpha         0.0
shadow_mask_texture       shadow-mask.png
shadow_mask_x_count       6
shadow_mask_y_count       4
shadow_mask_usize         0.1875
shadow_mask_vsize         0.25
shadow_mask_uoffset       0.0
shadow_mask_voffset       0.0
distortion                0.0
cubic_distortion          0.0
distort_corner            0.0
round_corner              0.0
smooth_border             0.0
reflection                0.0
vignetting                0.0
scanline_alpha            0.0
scanline_size             1.0
scanline_height           1.0
scanline_variation        1.0
scanline_bright_scale     1.0
scanline_bright_offset    0.0
scanline_jitter           0.0
hum_bar_alpha             0.0
defocus                   0.0,0.0
converge_x                0.0,0.0,0.0
converge_y                0.0,0.0,0.0
radial_converge_x         0.0,0.0,0.0
radial_converge_y         0.0,0.0,0.0
red_ratio                 1.0,0.0,0.0
grn_ratio                 0.0,1.0,0.0
blu_ratio                 0.0,0.0,1.0
saturation                1.0
offset                    0.0,0.0,0.0
scale                     1.0,1.0,1.0
power                     1.0,1.0,1.0
floor                     0.0,0.0,0.0
phosphor_life             0.0,0.0,0.0

every thing default except hlsl_enable               1

**Comment by rb6502** [comment]
That's intended; HLSL simulates an arcade CRT, and arcade CRTs are not as crisp as modern computer monitors.  It offers a sort of fake anti-aliasing to pixel art that most people find appealing.  If you don't, then leave HLSL off.

**Comment by Aniark** [comment]
@rb6502  Excuse me, I do not understand what you mean by "prescale"

**Comment by Aniark** [comment]
You must be misunderstand. 
What I want to say is when I play game, graphics became blur while the character in the game moving of acting, but I can see many gays using hlsl not like me, so I think blur is not a normal sence.





At 2017-01-14 22:47:44, "R. Belmont" <notifications@github.com> wrote:


That's intended; HLSL simulates an arcade CRT, and arcade CRTs are not as crisp as modern computer monitors. It offers a sort of fake anti-aliasing to pixel art that most people find appealing. If you don't, then leave HLSL off.

**Comment by B2K24** [comment]
By default when using HLSL with -video d3d there's different values in raster.ini that will override what's in mame.ini. Check location MAME\ini\presets

Alternately, you can set video to bgfx and try out hlsl shader chain (hlsl.json)

**Comment by anikom15** [comment]
That motion blur is normal if your phosphor_life parameters are not 0.

But B2K24 is correct. You need to put your HLSL options in ini files in the ini directory. Most games are covered by a raster.ini file, which corresponds to games that use a raster display. You can use <shortname>.ini for specific games.

You can play with the values in-game by hitting the ` (grave accent) key and using the arrow keys to choose options and adjust.

**Comment by Aniark** [comment]
@anikom15 @B2K24 Thanks for tips, now I can play without blur
