### ISSUE TITLE
option_resolution::get_default() is a no-op after c++-ification

### ISSUE THREAD

**Issue by shattered** [mamedev/mame#1976]
commit b60879e595edc98fb12b7990bd3b45188191bbf1 made get_default() a no-op in src/lib/util/opresolv.cpp -- this breaks loading of basicdsk floppy images (src/lib/formats/basicdsk.cpp).

**Comment by cuavas** [comment]
@npwoods please work with @shattered to resolve this.

**Comment by npwoods** [comment]
@shattered Can you be more specific?  I was able to launch Oregon Trail on 'apple2c0' which uses src/lib/formats/basicdsk.cpp

While I'm sure that the regression occurred in the commit you identify, I strongly suspect the consumer needs to be fixed.

**Comment by shattered** [comment]
My specific use case is not yet in MAME source tree -- it's a rewrite of src/mame/machine/rx01.cpp; I think the key part is that ap2_dsk has custom FLOPPY_IDENTIFY function and rx01 uses default one.

**Comment by npwoods** [comment]
Is this something that ends up going through 'basicdsk_identify_default'?  If so, this is essentially dead code.  As far as I can tell, the only driver that used this in an "off the shelf" fashion is src/mame/drivers/thomson.cpp, and that is now going to RB and Olivier's floppy system.

I do have a long term (hopefully not quixotic) objective to reunify these floppy implementations.  RB and Olivier's system seems to be a much more faithful emulation of the hardware, but the (admittedly clumsy) way the older system supported alternative formats was lost.

Are you able to reproduce this problem with something actually in the MAME tree?

**Comment by shattered** [comment]
No, I cannot.   So I guess I should submit my rewrite then...

**Comment by shattered** [comment]
I've added a rx01_dsk format and get_default() is no longer a problem.
