### ISSUE TITLE
emu.wait() is missing after sol2 migration

### ISSUE THREAD

**Issue by shattered** [mamedev/mame#1977]
Commit e5bb85da5beee650a9ec2454874e06a521760eb8 removed emu.wait(), I've been using that in regression tests along with emu.keypost().   Please bring it back.

**Comment by cracyc** [comment]
Wait uses lua_yield which has issues with sol2 https://github.com/ThePhD/sol2/issues/272 .
Could you use a frame callback to track time or maybe another callback that is called when the timer expires?

**Comment by shattered** [comment]
I certainly will try...

**Comment by galibert** [comment]
The fuck?  That's a reason for an immediate revert of sol2 in my book.

  OG.

**Comment by cracyc** [comment]
Okay, wait should work again but only from within a coroutine.  Close the issue if it works for you.

**Comment by cracyc** [comment]
Have you tried this yet?  Let me know if something is still wrong/missing.

**Comment by shattered** [comment]
Haven't but will...

**Comment by shattered** [comment]
wait() does work from coroutine, but there's a side effect wrt manager:machine().screens -- I'll open an issue about that.
