### ISSUE TITLE
ymmu100.cpp does not build on Linux/gcc 5.4.0

### ISSUE THREAD

**Issue by valgrind** [mamedev/mame#2005]
Todays git as of da169d7fe01c123ddc232415d19faff08196f2fc does not build on Ubuntu 16.04/gcc 5.4.0 :

../../../../generated/mame/layout/../drivers/ymmu100.hxx:1:14: error: UINT8 does not name a type

This will make it compile:

diff --git a/src/mame/drivers/ymmu100.cpp b/src/mame/drivers/ymmu100.cpp
index ccd0873..7610b19 100644
--- a/src/mame/drivers/ymmu100.cpp
+++ b/src/mame/drivers/ymmu100.cpp
@@ -122,6 +122,10 @@
 #include "bus/midi/midiinport.h"
 #include "bus/midi/midioutport.h"

+// begin zino kludge
+#define UINT8 uint8_t
+// end zino kludge
+
 static INPUT_PORTS_START( mu100 )
        PORT_START("P7")
        PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_OTHER) PORT_NAME("Enter")     PORT_CODE(KEYCODE_ENTER)

**Comment by startaq** [comment]
Delete the file `ymmu100.hxx` from the build folder, then try again (without your kludge).

**Comment by valgrind** [comment]
That's the correct answer. Thanks!
