### ISSUE TITLE
No such file or directory of GL/gl.h 

### ISSUE THREAD

**Issue by hamam99** [mamedev/mame#2027]
In file included from ../../../../../3rdparty/bgfx/src/glcontext_egl.cpp:9:0:
../../../../../3rdparty/bgfx/src/renderer_gl.h:43:22: fatal error: GL/gl.h: No such file or directory
compilation terminated.

**Comment by couriersud** [comment]
Can you please provide: 
- operating system and version
- compiler and compiler version
- are you doing a clean build
- the command line used to invoke the build

**Comment by hamam99** [comment]
I am sorry  I forget to close this issues ,  I had fixed it  with some trick . Thanks
