### ISSUE TITLE
font_uismall and font_uicmd14 was not declared in this scope on  file rendfont.cpp

### ISSUE THREAD

**Issue by hamam99** [mamedev/mame#2038]
../../../../../src/emu/rendfont.cpp: In constructor ‘render_font::render_font(render_manager&, const char*)’:
../../../../../src/emu/rendfont.cpp:601:48: error: ‘font_uismall’ was not declared in this scope
  osd_file::error const filerr(ramfile.open_ram(font_uismall, sizeof(font_uismal
                                                ^
../../../../../src/emu/rendfont.cpp: In member function ‘void render_font::render_font_command_glyph()’:
../../../../../src/emu/rendfont.cpp:1607:20: error: ‘font_uicmd14’ was not declared in this scope
  if (file.open_ram(font_uicmd14, sizeof(font_uicmd14)) == osd_file::error::NONE

**Comment by startaq** [comment]
This seems to be a local issue on your system since nobody can reproduce it. Possibly all that's needed is a clean build.
