### ISSUE TITLE
devices\cpu\z180\z180.cpp: Z180_DMODE_MMOD wrong value

### ISSUE THREAD

**Issue by BartmanAbyss** [mamedev/mame#2039]
line 632: `#define Z180_DMODE_MMOD 0x04` is wrong
`#define Z180_DMODE_MMOD 0x02` is correct
(see [Z180 datasheet](http://www.zilog.com/appnotes_download.php?FromPage=DirectLink&dn=PS0140&ft=Product%20Specification%20(Data%20Sheet)%20%20&f=YUhSMGNEb3ZMM2QzZHk1NmFXeHZaeTVqYjIwdlpHOWpjeTk2TVRnd0wzQnpNREUwTUM1d1pHWT0=) page 64)

**Comment by startaq** [comment]
Fixed in commit ea734065.
