### ISSUE TITLE
Compilation error under GCC 5.4.0

### ISSUE THREAD

**Issue by h3xx** [mamedev/mame#2048]
Spawned from #2047.

    ../../../../../src/devices/machine/netlist.cpp: In member function 'virtual void nld_analog_callback::update()':
    ../../../../../src/devices/machine/netlist.cpp:101:7: error: 'fabs' is not a member of 'std'
       if (std::fabs(cur - m_last) > 1e-6)
           ^
    ../../../../../src/devices/machine/netlist.cpp:101:7: note: suggested alternative:
    In file included from /usr/include/features.h:368:0,
                     from /usr/include/c++/5.4.0/x86_64-slackware-linux/bits/os_defines.h:39,
                     from /usr/include/c++/5.4.0/x86_64-slackware-linux/bits/c++config.h:482,
                     from /usr/include/c++/5.4.0/bits/stl_algobase.h:59,
                     from /usr/include/c++/5.4.0/list:60,
                     from ../../../../../src/emu/emu.h:21:
    /usr/include/bits/mathcalls.h:181:1: note:   'fabs'
     __MATHCALLX (fabs,, (_Mdouble_ __x), (__const__));
     ^
    ../../../../../src/devices/machine/netlist.cpp: In member function 'virtual void nld_sound_out::update()':
    ../../../../../src/devices/machine/netlist.cpp:208:19: error: call of overloaded 'abs(nl_double&)' is ambiguous
       if (std::abs(val) < 32767.0)
                       ^
    In file included from /usr/include/c++/5.4.0/cstdlib:72:0,
                     from /usr/include/c++/5.4.0/ext/string_conversions.h:41,
                     from /usr/include/c++/5.4.0/bits/basic_string.h:5249,
                     from /usr/include/c++/5.4.0/string:52,
                     from /usr/include/c++/5.4.0/stdexcept:39,
                     from /usr/include/c++/5.4.0/array:38,
                     from /usr/include/c++/5.4.0/tuple:39,
                     from /usr/include/c++/5.4.0/functional:55,
                     from /usr/include/c++/5.4.0/memory:79,
                     from ../../../../../src/emu/emu.h:23:
    /usr/include/stdlib.h:735:12: note: candidate: int abs(int)
     extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
                ^
    In file included from /usr/include/c++/5.4.0/ext/string_conversions.h:41:0,
                     from /usr/include/c++/5.4.0/bits/basic_string.h:5249,
                     from /usr/include/c++/5.4.0/string:52,
                     from /usr/include/c++/5.4.0/stdexcept:39,
                     from /usr/include/c++/5.4.0/array:38,
                     from /usr/include/c++/5.4.0/tuple:39,
                     from /usr/include/c++/5.4.0/functional:55,
                     from /usr/include/c++/5.4.0/memory:79,
                     from ../../../../../src/emu/emu.h:23:
    /usr/include/c++/5.4.0/cstdlib:166:3: note: candidate: long int std::abs(long int)
       abs(long __i) { return __builtin_labs(__i); }
       ^
    /usr/include/c++/5.4.0/cstdlib:174:3: note: candidate: long long int std::abs(long long int)
       Eabs(long long __x) { return __builtin_llabs (__x); }
       ^

Other information:

Slackware x86_64 current (kernel 4.4.14).

Make(1) arguments used to generate this error:

		-k
		OPTIMIZE=3
		OSD='sdl'
		TOOLS=1
		BUILD_{ZLIB,FLAC,EXPAT,JPEGLIB}=0
		{FLAC,JPEG}_LIB=''
		NOWERROR=1
		USE_QTDEBUG=0

**Comment by cuavas** [comment]
Add `-k` to your make options so you can find all the files that fail to compile, don't open one PR/issue per file.

**Comment by couriersud** [comment]
just add a #include <cmath> to netlist.cpp. That will fix those errors. Interesting enough, I run these files through 5 compilers (linux g++, linux clang, OSX clang, mingw and VC2015) without errors. 
Thanks for pointing this out.

**Comment by h3xx** [comment]
@couriersud Evidently adding local #includes isn't the correct way to do this (see #2047), so I'm reluctant to make another merge request only to have it rejected again.

@cuavas Doing that now. Will update this issue if any other errors are found, which I will then let you fix in your own way.

**Comment by h3xx** [comment]
@cuavas The error listed in the issue was the only one seen during compilation using `-k` flag.

**Comment by cuavas** [comment]
@couriersud it isn't so much the compiler as the runtime library.  There are a huge number of small variations, making it very hard to cover all of them.  This is one of the reasons I'm toying with the idea of raising funding for dedicated hardware to do CI on multiple Windows/Linux/BSD configurations.

@h3xx the errors in src/devices/machine/netlist.cpp should be fixed in a5aaaa047c9dc2d65af24cc0c8351ef9b1b95977 - please try again.

**Comment by h3xx** [comment]
@cuavas The build passes on my setup. Thanks for the help!

I'll let you decide when to close this issue, since there's potentially still discussion going on.

**Comment by cuavas** [comment]
I'll close it since it builds now.  People can still comment on a closed issue.
