### ISSUE TITLE
Two MAME instances can no longer talk via TCP socket (again)

### ISSUE THREAD

**Issue by shattered** [mamedev/mame#2061]
Breaking commit is 17af0f9c661e0855607703faf66c1e807e888d82 (likely the last hunk, i.e. change to mame_options::update_slot_options)

How to demo:
* start first instance -- `mame dvk_ksm -bitb socket.localhost:9999 -noskip_gameinfo`.  Do not close the game info box.
* start second instance -- `mame dvk_ksm -bitb socket.localhost:9999`
* close the info box on first instance and type something into MAME.  second instance should echo the input.

**Comment by ajrhacker** [comment]
I don't think I can test this, since running multiple instances of MAME under SDL on OS X doesn't seem to work in the first place.

**Comment by cuavas** [comment]
It does work - I manage to do it regularly. Also you could run one instance in a VM and make it talk to an instance on the host if there's really an issue. In any case, this is a critical issue and I'm reverting that commit before release if it isn't fixed.

**Comment by cracyc** [comment]
It looks like the emulator is opening the socket then immediately closing it which causes the listener to close.  It's then being reopened as a listen socket because the other side is gone.  You can test with only one mame instance by using netcat -l.

**Comment by ajrhacker** [comment]
I've opened #2065 as an attempted fix for this problem. I still haven't been able to verify it, but cracyc's description seems helpful.

**Comment by shattered** [comment]
17af0f9c661e0855607703faf66c1e807e888d82 was reverted for now

**Comment by JoakimLarsson** [comment]
So this  issue can be closed then?
