### ISSUE TITLE
Button assignments are inconsistent

### ISSUE THREAD

**Issue by rsn8887** [mamedev/mame#2064]
The button assignments in various drivers are inconsistent with each other on a game by game basis. It seems there is no standard how buttons are assigned, so each driver developer did their own thing.

I think all button assignments should follow their layout on the control panels. E.g. if the left button is jump in one game, and shoot in another, then that button should be assigned to the same control.

Right now, compared to other emulators like FBA, Mame buttons are inconsistently and seemingly randomly assigned between drivers. Most annoyingly, button 1 is shoot when it should be jump for many games such as Bubble Bobble and Rainbow Islands.

And all the mappings should also be consistent with a SF2 style 6 button layout, and other layouts, too so that one mapping is at least as "sensible" as possible in an arcade cab layout, that has, say, eight buttons in two rows per player. Somehow Finalburn does it.

Also, a descriptive button assignment would be extremely helpful if it is displayed in the Mame on screen menu such as "Button 1 (Jab)," "(Jump)," or "(Shoot)" depending on the game. This should be taken from the game flyer, control panel  picture or other sources, or from the dat files that are floating around like mameinfo.dat and/or mamehistory.dat

**Comment by Tafoid** [comment]
Not arguing about port names and expanded button descriptions, your claim that Rainbow Islands and Bubble Bobble having incorrect button function is incorrect.  Where is the proof that Button 1 doesn't function as a shoot/bubble/rainbow button or Button 2 doesn't function as jump?

The manual for Bubble Bobble details Stick, Button 1, Button 2
![bublbobl_manual](https://cloud.githubusercontent.com/assets/9075896/22902720/fd9ce1d2-f203-11e6-8a4b-25db6035b747.png)
An actual control panel made shows Button 1 (Bubble) and Button 2 (Jump)
![bublbobl](https://cloud.githubusercontent.com/assets/9075896/22902319/aeeba0e2-f202-11e6-9daa-2d3d0a026a46.png)

In the Japanese Rainbow Island manual, it draws the symbols:
Button 1 = 虹 = rainbow, Button 2 =  ジャンプ = jump
![rbisland_manual](https://cloud.githubusercontent.com/assets/9075896/22904524/cd218236-f20a-11e6-8230-7fc1f7baa11a.png)

**Comment by rsn8887** [comment]
I honestly didn't know that. But is the button assignment really consistent with the arcade cab layouts for all games? It seems as if it switches around from game to game still.

**Comment by galibert** [comment]
We try to assign buttons as they're assigned in the test mode, which itself
follows the button numbers on the jamma/jvs/other connector.  What comes
after the connector is not an information really present in mame at that
point.  Vas iirc suggests an external file would do the job best.

My muscle memory is with shoot on 1 and jump on 2, not sure where you get
yours from...

  OG.

**Comment by angelosa** [comment]
We map button layout to whatever the service mode default gives us if manual/official control panel isn't available, as a result a game that maps jump as b1 and shot to b2 is Sparkman, the convention is the other way around most often than not (Bubble Bobble and Rainbow Islands).
If you don't like this you can always reverse the order in the _(general)_ / _(this machine)_ menus for the time being. 
afaik arguably N generic button layout is something you can't do with current MAME i.e. having a:

1. OG NeoGeo `A-B-C-D` 
2. 3-3b Capcom style 
```
A-B-C 
D-E-F
```

... that defaults to preset without user intervention, unless it's doable with ctrlr files somehow.
Finally label mapping is something that [portnames](https://github.com/cracyc/mame-portnames) plugin currently do.

**Comment by cuavas** [comment]
There isn’t even an isn’t even an issue here.  If there are specific issues with particular systems, they can be brought up individually.  This is just a misunderstanding of how things work.
