### ISSUE TITLE
Clone not running if main in a folder

### ISSUE THREAD

**Issue by EricBF** [mamedev/mame#2071]
I have two folders: damakair\ and ghouls\ with all roms. (damakair is a clone of ghouls)
I tried to run damakair from command line : mame64.exe daimakair -rp "E:\Roms\cps1" and I get an error: 

> dam_01.3a NOT FOUND (tried in daimakair ghouls daimakair)
> dam_02.4a NOT FOUND (tried in daimakair ghouls daimakair)
> dam_03.5a NOT FOUND (tried in daimakair ghouls daimakair)
> dam_04.6a NOT FOUND (tried in daimakair ghouls daimakair)
> Fatal error: Required files are missing, the machine cannot be run.

These roms are the merged roms and should be used from ghouls\.
Now if I zip ghouls\, it works as expected.

**Comment by cuavas** [comment]
MAME will only load by CRC from zip/7z archives because the archive directory stores CRCs for archive members.  In a folder, MAME only loads files by name.  The files in `ghouls` have different names to what `daimakair` looks for, so MAME won't load them from a folder.
