### ISSUE TITLE
Lua -console is gone

### ISSUE THREAD

**Issue by shattered** [mamedev/mame#2082]
commit 709c330a1f2f2deb095967f865d2c638b63cc497 broke `-console` switch -- Lua console no longer starts.

**Comment by JoakimLarsson** [comment]
I use -plugins but have an older baseline, is that also not working anymore?

**Comment by npwoods** [comment]
On 2/23/2017 8:22 AM, Joakim Larsson Edström wrote:
>
> I use -plugins but have an older baseline, is that also not working 
> anymore?
>
https://github.com/mamedev/mame/pull/2083

-N
