### ISSUE TITLE
S1C33209 cpu emulation needed

### ISSUE THREAD

**Issue by nitrofurano** [mamedev/mame#2084]
there is a popular japanese handheld named P/ECE - would be great having it emulated on Mame/Mess, but it needs S1C33209 emulation - thanks! :)

**Comment by happppp** [comment]
Ok, good luck with your emulation wish :)

**Comment by rb6502** [comment]
Less bluntly, if you're going to wishlist an entire driver, you'd best come correct with CPU manuals, programming / hardware manuals for the device, ROMs, and software (if it has any).  PCB photos help too, of course.
