### ISSUE TITLE
aristocrat mk5 game freezing

### ISSUE THREAD

**Issue by pottzman** [mamedev/mame#2087]
it appears as though the NSW/ACT aristocrat mk5 games lockup/freeze after 50 spins. Exiting game and re starting allows the game to continue for another 50 spins and then it freezes again. Using Mame v0.183

**Comment by Tafoid** [comment]
In the case of Aristocrat MK5 games, while recently work has been done to make many of them properly boot and some play after some rather involved set up procedures, they are still not expected to run and are plainly flagged as "MACHINE NOT WORKING".   There is nothing you can do on your end to improve the situation and things will not improve until someone who has interest in the driver is able to apply said improvements.  Reason for that behavior could range from missing protection emulation, incorrect setup/startup strings or some (yet unknown) emulation shortcoming.  Sadly, the driver is not a state where bug reports are generally considered or required (which would need comparison with actual hardware/machines).
