### ISSUE TITLE
rx78.cpp missing better commented information

### ISSUE THREAD

**Issue by nitrofurano** [mamedev/mame#2090]
would be excellent if rx78.cpp could have more information about how the display works (like how can we draw stuff in the display area), how can we run cartridges, etc. - i’m also struggling to find documentation about how can we develop homebrews to this machine - thanks! :)

**Comment by cuavas** [comment]
The code is the documentation - if the emulation runs you can infer from that how the hardware works.  Someone can add additional comments if they want, but the purpose of MAME isn't to be a how-to-write-homebrew tutorial.
