### ISSUE TITLE
Empty slot device name (f.e. -isa "") no longer empties the slot

### ISSUE THREAD

**Issue by shattered** [mamedev/mame#2097]
After 8c53c1438eb893ee9291c73e2ee26d34b5f8f2d7, passing empty string as slot device name no longer removes a device from that slot.    I am using this to speed up bootup of certain drivers in automated tests.  Workaround is to pass a single space instead.

How to demo:

`mame ibm5150 -isa4 "" -isa3 "" -isa2 "" -isa1 "" -kbd "" -ld`

Expected output:

```Driver ibm5150 (IBM PC 5150):
   <root>                         IBM PC 5150
     cass_list                    Software list
     disk_list                    Software list
     isa1                         ISA8_SLOT
     isa2                         ISA8_SLOT
     isa3                         ISA8_SLOT
     isa4                         ISA8_SLOT
     isa5                         ISA8_SLOT
     kbd                          PC_KBDC_SLOT
     maincpu                      I8088 @ 4.77 MHz
     mb                           IBM5160_MOTHERBOARD
       cassette                   Cassette
       dma8237                    AM9517A @ 4.77 MHz
       isa                        ISA8
       mono                       Speaker
       pc_kbdc                    PC_KBDC
       pic8259                    8259 PIC
       pit8253                    8253 PIT
       ppi8255                    8255 PPI
       speaker                    Filtered 1-bit DAC
     ram                          RAM
```

**Comment by cuavas** [comment]
That's supposed to be fixed by 239dcd44490c467c31c7d0c51da5fefdfec8d9f6 (#2093).  Have you re-tested since then?

**Comment by galibert** [comment]
commit 239dcd44490c467c31c7d0c51da5fefdfec8d9f6
Author: Nathan Woods <npwoods@mess.org>
Date:   Sun Feb 26 09:08:20 2017 -0500


On Sun, Feb 26, 2017 at 10:41 PM, Sergey Svishchev <notifications@github.com

**Comment by shattered** [comment]
Indeed, it's fixed.  Sorry for the noise.
