### ISSUE TITLE
is Bally Astrocade palette accurate enough?

### ISSUE THREAD

**Issue by nitrofurano** [mamedev/mame#2120]
i found this now, i don’t know how far can this document be confirmed as valid evidence to be considered - http://glankonian.com/~lance/astrocade_palette.html - thanks in advance

**Comment by cuavas** [comment]
Please don't use github issues to spam us.  This is not a discussion forum.  I don't like banning people, but if you keep abusing the issues system I'll have no choice, as it causes noise that gets in the way of development.
