### ISSUE TITLE
MAME doesn't build in my msys2

### ISSUE THREAD

**Issue by htjywf2008** [mamedev/mame#2121]
Hello,

I'm using my msys2 and I tried to build MAME with gcc, But when I type "make", It says "MINGW32 is not set."
I also tried build MAME with clang, but another error was occurred:
`../../../../../src/emu/emu.h:21:10: fatal error: 'list' file not found

#include <list>
         ^
1 error generated.
`
So what's caused problem?

My system is WIndows 10 Build 15048 (64-bit).

Regards

-htjywf2008

**Comment by htjywf2008** [comment]
It seems only 2016-02-16 buildtools work.

**Comment by htjywf2008** [comment]
I'm solved! I'm using 2016-02-16 buildtools, It works!

**Comment by htjywf2008** [comment]
The issues will keep open utill the problem was fixed.

**Comment by htjywf2008** [comment]
Since the 2017-02-05 buildtools Problem never get fixed. I'm Closing the issues.

**Comment by runvnc** [comment]
I'm not sure whats going on but I followed the directions here https://github.com/mamedev/buildtools/ for MSYS2 closely and they always result in `MINGW32 is not set. Stop.`

So I think something happened with MSYS2 so the makefile doesn't quite work now.  Maybe it only works with older versions?  Can someone give me a hint about what to set in the Makefile or my Windows environemnt or anything, I tried just setting MINGW32=1.. I am actually trying to build 64 bit but would settle for getting 32 bit to work.  I tried both.. I have downloaded the MINGW/MSYS2 stuff like three times.

Thanks so much for any time you have for this anyone :)

**Comment by Robbbert** [comment]
You can see from earlier comments that an old version will work. The MINGW32 variable is required for 32-bit builds. It will be typically something like this:

set MINGW32=E:\mingw\6-3-0\mingw32 (or wherever your 32-bit tools are located)

I cannot help with the current version of msys2 as I'm using an old version.

**Comment by runvnc** [comment]
Thanks Robbbert

**Comment by stilett0** [comment]
I suppose it's possible there's something wrong with the new tools package, they were made quickly. We will investigate.

In the meantime you can get the equivalent of the most current tools package by downloading the older package, and then continuously running the update process explained here: http://mamedev.org/tools/
until there is nothing more new to get.

**Comment by runvnc** [comment]
Thanks @stilett0

**Comment by runvnc** [comment]
When I use mingw64.exe or mingw32.exe I still get the `MINGW32 is not set` even when I use the older build tools specified.   Then I tried to set it to the location that I found the files, but it seems like maybe some parts of some make script(s) assume a different structure.

BUT, I figured something else out.  You can also run it in a normal windows command prompt if you first run the win32env.bat.  I had previously skimmed over that and assumed I needed to use the `posix` mingw64.exe shell.

When I ran `make` inside of a regular Windows 10 command prompt (after running win32env.bat) I had no problem with the build at all.

**Comment by mmicko** [comment]
Please note that if you are using mingw from bash shell, you need to alter your personal settings  in order to make it work.
There is file c:\msys64\home\[your username here]\.bashrc  that is created on first start.
adding:
export MINGW32=/mingw32
export MINGW64=/mingw64

should solve your problem.
Note that most of people using mingw from windows shell so that is how we configured it and using it while developing.
