### ISSUE TITLE
SNES Emulator Doesn really work

### ISSUE THREAD

**Issue by aperfeito** [mamedev/mame#2123]
I Try Hard , even the last compile right now in mess this is results  
command line:

$#mess snes -cart "/home/user/.mess/roms/SNES/RRCUSA.sfc" -pluginspath /home/user/.mame/plugins
The machine load but the screen is BLACK
________________________________________________________________
The other way
$#mess snes **rnrracin** -pluginspath /home/aperfeito/.mame/plugins 
________/* With the game file rnrracin.zip in rom folder*/______________________________________

Give this error of license of the game or any game SNES
[MAME]> spal-rn-0.u1 NOT FOUND (tried in snes snes/rnrracin rnrracin)

The plugin in both cases not only SNES for every case this the message of error

    _/      _/    _/_/    _/      _/  _/_/_/_/
   _/_/  _/_/  _/    _/  _/_/  _/_/  _/       
  _/  _/  _/  _/_/_/_/  _/  _/  _/  _/_/_/    
 _/      _/  _/    _/  _/      _/  _/         
_/      _/  _/    _/  _/      _/  _/_/_/_/    

mess 0.183	
Copyright (C) Nicola Salmoria and the MAME team

Lua 5.3	
Copyright (C) Lua.org, PUC-Rio

**[LUA ERROR] in run: /home/aperfeito/.mame/plugins/boot.lua:30: attempt to index a nil value (local 'f')**

**Comment by rb6502** [comment]
I just verified that Rock and Roll Racing runs fine on MAME 0.183 if you use the correct dump with the CRC32 b02daf39.

If you are still using an older version that identifies as "MESS", you are at least 3 years behind our latest development.

**Comment by stilett0** [comment]
@rb6502 , it's probably http://messui.1emulation.com/ . @Robbbert provides standard subtarget=mess command-line builds in addition to MESSUI.

**Comment by Robbbert** [comment]
@rb6502 when MAME is built with the mess subtarget, it calls itself MESS.

You can see from the command-line given by @aperfeito  that he's not using a Windows build, so it isn't one of mine. Maybe @aperfeito can tell us where he got it from.

**Comment by stilett0** [comment]
Oh, damn, @Robbbert is right. 😄 Sorry, man!

Given the structure of the directory paths in the original post, it's clearly a Linux or Mac build. Don't know how I missed that. Pretty sure no one is packaging MESS for those platforms any more, so it's probably self-compiled with a "subtarget=mess".

**Comment by aperfeito** [comment]
Hi Robert ,


         I compile using Linux alarm 3.10.18-18-ARCH #5 SMP Mon Feb 20 14:21:15 PST 2017 armv7l GNU/Linux,

            The SNES Emulation  when you use  subtarget =mess . Give this no work at all like you see.

             The same thing to Nitendo Super System .

             Mame is affect too with same errors.




________________________________
De: Stiletto <notifications@github.com>
Enviado: quinta-feira, 9 de março de 2017 05:12:54
Para: mamedev/mame
Cc: Alexander Nunes Perfeito; Mention
Assunto: Re: [mamedev/mame] SNES Emulator Doesn really work (#2123)


Oh, damn, @Robbbert<https://github.com/Robbbert> is right. 😄 Sorry, man!

Given the structure of the directory paths in the original post, it's clearly a Linux or Mac build. Don't know how I missed that. Pretty sure no one is packaging MESS for those platforms any more, so it's probably self-compiled with a "subtarget=mess".

**Comment by rb6502** [comment]
Wait, you're compiling for a non-x64/x64 platform?  That's important to tell us :)

**Comment by MooglyGuy** [comment]
I suggest closing this issue unless the user can provide more relevant information about his or her operating environment.

**Comment by Robbbert** [comment]
Yeah I agree, it's been a month with no user input. Closed.

**Comment by aperfeito** [comment]
Hi Moogly guy,


      My operating environment. Linux alarm v3.10.18-19-ARCH processor armv7l GNU / Linux using NVIDIA Tegra TK1 processor and GPU graphics.
      I'm using hardware Chromebook 14" brand HP and a month ago I have been making updates by Git pull in the official development repository and no update solved the problem of running SNES games using mame so far and has not been solved yet !!!


Regards

________________________________
De: MooglyGuy <notifications@github.com>
Enviado: sexta-feira, 21 de abril de 2017 08:58:10
Para: mamedev/mame
Cc: Alexander Nunes Perfeito; Mention
Assunto: Re: [mamedev/mame] SNES Emulator Doesn really work (#2123)


I suggest closing this issue unless the user can provide more relevant information about his or her operating environment.

**Comment by aperfeito** [comment]
Robert ,


     Hi


      My operating environment. Linux alarm v3.10.18-19-ARCH processor armv7l GNU / Linux using NVIDIA Tegra TK1 processor and GPU graphics.
      I'm using hardware Chromebook 14" brand HP and a month ago I have been making updates by Git pull in the official development repository and no update solved the problem of running SNES games using mame so far and has not been solved yet !!!

________________________________
De: Robert <notifications@github.com>
Enviado: sexta-feira, 21 de abril de 2017 09:03:42
Para: mamedev/mame
Cc: Alexander Nunes Perfeito; Mention
Assunto: Re: [mamedev/mame] SNES Emulator Doesn really work (#2123)


Closed #2123<https://github.com/mamedev/mame/issues/2123>.

**Comment by aperfeito** [comment]
Robert , Which kind of input you expect man !!!!  FIY !!!!






      My operating environment. Linux alarm v3.10.18-19-ARCH processor armv7l GNU / Linux using NVIDIA Tegra TK1 processor and GPU graphics.
      I'm using hardware Chromebook 14" brand HP and a month ago I have been making updates by Git pull in the official development repository and no update solved the problem of running SNES games using mame so far and has not been solved yet !!!

________________________________
De: Robert <notifications@github.com>
Enviado: sexta-feira, 21 de abril de 2017 09:03:42
Para: mamedev/mame
Cc: Alexander Nunes Perfeito; Mention
Assunto: Re: [mamedev/mame] SNES Emulator Doesn really work (#2123)


Yeah I agree, it's been a month with no user input. Closed.
