### ISSUE TITLE
[Feature Request] VT (NES) Support

### ISSUE THREAD

**Issue by dkl3** [mamedev/mame#2151]
Hello,

I assume this is the right place to post about this; so there are these 8-bit plug'n'plays, and they're all basically based on the VT chip, which is based on NES graphics but often with better quality graphics. Th manufacturer site is here: http://vrt.com.tw/ .

Okay, so while they do have an emulator that supports VT-chip ROMs (known as EmuVT), the compatibility is incomplete and is mostly for testing purposes. They don't have support for chips like VT09, which is used on mid-2000s Jungletac handhelds.

Here is a mirror of all their development tools: https://archive.org/details/VRTfiles-nesdev . This could help with understanding the technology behind the VT chips. There's no info on VT09 but I figure that info on like VT03 can be applied to VT09, and thus figuring out the system itself.

This is my first time submitting a feature request, so I may not have done it all that well. Hopefully some of you can help me along the way.

- DKL3

**Comment by MooglyGuy** [comment]
Generally, the team doesn't take major feature requests like adding support for chips that are not currently emulated. Being a hobby project, people tend to work on whatever interests them most.

That having been said, this is a great feature request and full of great info should any contributor decide to actively work on adding support for this line of CPUs, which I suspect is why it's been left open, so I'll leave it open too. Thanks for the archive.org link, too, it's great that someone has thought ahead and made sure that the development tools don't get lost.

**Comment by DavidHaywood** [comment]
Fwiw, I've been looking at this and should have the basics of VT03 to submit fairly soon.

Might need some work before it gets accepted, hammering out the best way to do things considering how they hacked up the NES by adding extra registers and making use of previously unused bits etc. and how they double up the APU but then force one channel from the first APU to actually output on the 2nd if it's set to PCM mode which is ugly.

by the time you get to VT1682 it isn't really even NES based tho, even if EmuVT runs it, aside from the main CPU nothing is the same, it even has it's own sound CPU core running at 4x the main one with an option for internal ROM, completely different video system, completely different sound system etc.

**Comment by etabeta78** [comment]
Yeah it's clearly derivative hw with not much in common with NES,
especially later revisions.


 f

On Thursday, May 18, 2017, DavidHaywood <notifications@github.com> wrote:
> Fwiw, I've been looking at this and should have the basics of VT03 to
submit fairly soon.
>
> Might need some work before it gets accepted, hammering out the best way
to do things considering how they hacked up the NES by adding extra
registers and making use of previously unused bits etc. and how they double
up the APU but then force one channel from the first APU to actually output
on the 2nd if it's set to PCM mode which is ugly.
>
> by the time you get to VT1682 it isn't really even NES based tho, even if
EmuVT runs it, aside from the main CPU nothing is the same, it even has
it's own sound CPU core running at 4x the main one with an option for
internal ROM, completely different video system, completely different sound
system etc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/l8Tqtxv94tJ43aUuBw0knCzrRQIQz411m-JIlEU0t_UC52QiqY4aM6LqeKy8mBVFcwkQ4zXh0Se5j3bceBJp2vnsEKHRojm-qdVCxdeS4rXyuTf8a94UD9ov2yXKhwkyKt9m8AMk-MwFyhk2gcl29wDCNKYVsQ=s0-d-e1-ft#https://github.com/notifications/beacon/AI0qvH4YX3YHx0uDCN3rT2Z0RPFXCHlvks5r7DkfgaJpZM4Mes_Y.gif>

**Comment by dkl3** [comment]
http://s4.zetaboards.com/PGC_Forums/topic/30164956/

I don't know how relevant this is but somebody finally made a working VT03/09 emulator, and I think plans to release the source to NESdev sometime

**Comment by cuavas** [comment]
MAME has at least preliminary support for various V.R. Technology consoles.  There's no reason to leave this non-specific issue open.
