### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by jacek007** [mamedev/mame#2169]
Hello,
0.182 is ok, but in 0.183 I have error like bellow. Could you help?
gcc 5.4.0, openmp enabled in both.

../../../../../src/lib/netlist/solver/nld_solver.cpp: In member function ‘virtual void netlist::devices::nld_solver::update()’:
../../../../../src/lib/netlist/solver/nld_solver.cpp:124:5: error: ‘solver’ was not declared in this scope
     solver->update_inputs();

**Comment by couriersud** [comment]
Thanks for highlighting this. Fixed in master.
