### ISSUE TITLE
bgfx_path with $HOME: assets not found

### ISSUE THREAD

**Issue by duganchen** [mamedev/mame#2201]
On Linux with MAME 0.184:

If I have a bgfx tree in my home directory, /home/dugan/.mame/bgfx, then the following happens.

If I set the bgfx_path in mame.ini to:

    /home/dugan/.mame/bgfx

Then MAME works great.

If I set bgfx_path in mame.ini to:

    $HOME/.mame/bgfx

Then MAME crashes:

    Unable to open effect file $HOME/.mame/bgfx/effects/gui_opaque.json
    Unable to open effect file $HOME/.mame/bgfx/effects/gui_blend.json
    Unable to open effect file $HOME/.mame/bgfx/effects/gui_multiply.json
    Unable to open effect file $HOME/.mame/bgfx/effects/gui_add.json
    Unable to open effect file $HOME/.mame/bgfx/effects/screen_opaque.json
    Unable to open effect file $HOME/.mame/bgfx/effects/screen_blend.json
    Unable to open effect file $HOME/.mame/bgfx/effects/screen_multiply.json
    Unable to open effect file $HOME/.mame/bgfx/effects/screen_add.json
    MAME exception: BGFX: Unable to load required shaders. Please check and reinstall the 
    $HOME/.mame/bgfx folder

It looks like the $HOME variable in bgfx_path isn't being expanded?

If I set bgfx_path to the following:

    /usr/share/games/mame/bgfx

Then it works

If I set it to:

    $HOME/.mame/bgfx;/usr/share/games/mame/bgfx

Then I get a similar crash:

    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/gui_opaque.json
    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/gui_blend.json
    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/gui_multiply.json
    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/gui_add.json
    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/screen_opaque.json
    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/screen_blend.json
    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/screen_multiply.json
    Unable to open effect file $HOME/.mame/bgfx:/usr/share/games/mame/bgfx/effects/screen_add.json
    MAME exception: BGFX: Unable to load required shaders. Please check and reinstall the $HOME/.mame/bgfx:/usr/share/games/mame/bgfx folder

**Comment by cuavas** [comment]
MAME's `osd_subst_env` function does tilde expansion and `${var}` substitution on *NIX-like systems and calls `ExpandEnvironmentStrings` on Win32 to expand `%var` expressions.  It's used by emufile at some point when handling paths.  I'm not sure exactly where this needs to be used in the BGFX module to expand variables in paths for its assets.

**Comment by MooglyGuy** [comment]
I can't promise that I'll be able to fix this anytime soon, Vas, but if you want to look into it yourself, just do a grep in the codebase for m_options.bgfx_path() and fix up the relevant usages. The affected files would be drawbgfx.cpp (maybe), chainmanager.cpp, effectmanager.cpp, and shadermanager.cpp.

**Comment by cuavas** [comment]
I think I fixed it in master, can you rebuild and give it another go @duganchen?

**Comment by duganchen** [comment]
I just got around to testing it. Works great now.

**Comment by serginhofogo** [comment]
just open a console go to the mame location and type ./mame64 the right click open doesn't work it only works by terminal
