### ISSUE TITLE
BCD issues within musashi m68k core

### ISSUE THREAD

**Issue by kazblox** [mamedev/mame#2209]
https://drive.google.com/file/d/0B652vbap-rpecVptNjE2TzFVTmM/view

Within the new version of flamewing's BCD Test ROM that correctly passes on real Megadrive hardware, errors from all the three bcd instructions spurt from the test results. This ROM has been tested with 'genesis', and the same results appear on other related sets.

The correct result should be a blank screen with all "values" and "flags" fields displaying $00000, although that is not the case in MAME, or any emulator other than the latest BlastEm nightly that I have tried so far.

http://i.imgur.com/BJdeOPg.png

Can anyone else confirm these errors?

**Comment by rb6502** [comment]
This is known, but none of the tens of thousands of 680x0 programs we've run in MAME actually has a problem as a result of this.  So it's the dreaded combination of" extremely challenging to fix" and "doesn't fix anything meaningful".

**Comment by kazblox** [comment]
Fixed as of a recent pull by notaz, thanks to O. Galibert.
