### ISSUE TITLE
Device ROM not found by "mame" or "mame -verifyroms" yet location known by verifyroms

### ISSUE THREAD

**Issue by worthlesscog** [mamedev/mame#2210]
MAME 0.183, Ubuntu 16.04

Device ROMs are not located by either "mame" or "mame -verifyroms" despite verify knowing where the file should be.

```
/mame/roms$ mame -listroms bbcb_us

ROMs required for driver "bbcb_us".
Name                                   Size Checksum
usmos10.rom                           16384 CRC(c8e946a9) SHA1(83d91d089dca092d2c8b7c3650ff8143c9069b89)
usbasic3.rom                          16384 CRC(161b9539) SHA1(b39014610a968789afd7695aa04d1277d874405c)
viewa210.rom                          16384 CRC(4345359f) SHA1(88c93df1854f5fbe6cd6e5f0e29a8bf4ea3b5614)
usdnfs10.rom                          16384 CRC(7e367e8c) SHA1(161f585dc45665ea77433c84afd2f95049f7f5a0)
phrom_us.bin                          16384 CRC(bf4b3b64) SHA1(66876702d1d95eecc034d20f25047f893a27cde5)
saa5050                                 960 BAD CRC(6298fc0b) SHA1(ae38e7f51dd33733bacfa896425ca105682b31d6) BAD_DUMP

/mame/roms$ unzip -v bbcb_us.zip 

Archive:  bbcb_us.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
   16384  Defl:N    15765   4% 2017-04-05 10:15 bf4b3b64  phrom_us.bin
   16384  Defl:N    12214  26% 2017-04-05 10:15 161b9539  usbasic3.rom
   16384  Defl:N    13128  20% 2017-04-05 10:15 c8e946a9  usmos10.rom
   16384  Defl:N     8985  45% 2017-04-05 10:15 4345359f  viewa210.rom
--------          -------  ---                            -------
   65536            50092  24%                            4 files

/mame/roms$ unzip -v bbc_acorn8271.zip 

Archive:  bbc_acorn8271.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
   16384  Defl:N    12621  23% 2017-04-05 10:15 7e367e8c  usdnfs10.rom
--------          -------  ---                            -------
   16384            12621  23%                            1 file

/mame/roms$ unzip -v saa5050.zip 

Archive:  saa5050.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     960  Defl:N      382  60% 2017-04-05 10:15 6298fc0b  saa5050
--------          -------  ---                            -------
     960              382  60%                            1 file

/mame/roms$ mame bbcb_us

usdnfs10.rom NOT FOUND (tried in bbcb_us bbcb bbcb_us)
saa5050 ROM NEEDS REDUMP
Fatal error: Required files are missing, the machine cannot be run.

/mame/roms$ mame -verifyroms bbcb_us

bbcb_us     : usdnfs10.rom (16384 bytes) - NOT FOUND (bbc_acorn8271)
bbcb_us     : saa5050 (960 bytes) - NEEDS REDUMP
romset bbcb_us [bbcb] is bad
1 romsets found, 0 were OK.
```
"mame" tried to find the ROM in bbcb_us, bbcb and bbcb_us again?
"mame -verifyroms" seems to know where the file should be (bbc_acorn8271) but fails to find it.

Moving the ROM (usdnfs10.rom) into either bbcb or bbcb_us resolves this but results in duplication.

**Comment by worthlesscog** [comment]
This is effectively a split set. Apologies if my terminology is shaky - I'm a bit new to ROM sets etc. By split set I mean device files in device zips, clone specifics in clone zips and parent zips containing the common parent files. In this case, bbcb.zip doesn't even exist.

Whilst bbcb_us does not directly use bbc_acorn8271 via device_ref, it uses a ROM from that device. Is it explicitly specified because the offset is different?
```
<rom name="usdnfs10.rom" size="16384" crc="7e367e8c" sha1="161f585dc45665ea77433c84afd2f95049f7f5a0" region="option" offset="34000"/>
<rom name="dnfs100.rom" bios="dnfs100" size="16384" crc="7e367e8c" sha1="161f585dc45665ea77433c84afd2f95049f7f5a0" region="dfs_rom" offset="0"/>
```
Does a merged set also include in all the device ROM files too?

If verifyroms knows the ROM can be found in bbc_acorn8271, why isn't it resolved from there?

**Comment by Pernod70** [comment]
Have you used a rom manager to verify your sets? If using split sets I would expect usdnfs10.rom to exist in bbcb_us.zip, which is what -verifyroms is telling you. The fact that it also exists in bbc_acorn8271 is irrelevant. You should also have a bbcb.zip.

**Comment by worthlesscog** [comment]
No, I don't use a manager. I'm rolling my own and was confused why the above sets don't work. In theory that's the minimal set for bbcb_us to work it's just that the dnfs rom is in the wrong zip file.

I think I see why they don't work now. Set bbcb set pulls it in by device_ref so bbcb_us finds it, presumably by hash, from there because of cloneof/romof. It's confusing that "mame" lists bbcb twice and verifyroms lists the correct device zip name.

I'm still not clear why if verifyroms knows the correct zip name, it couldn't be resolved from that archive.

**Comment by worthlesscog** [comment]
Closing this - it's easier to resolve over relay.
