### ISSUE TITLE
Softlist names with spaces no longer working

### ISSUE THREAD

**Issue by ssjbrollyus** [mamedev/mame#2229]
It's no longer possible to load softlist entries with spaces on their names.

For instance, this works fine under 0.172:
mame64.exe scv "Doraemon (Japan)" -window -hashpath "K:\Emulators\MAME\_Config\hash_custom"

With 0.184 MAME won't start with this error:
Fatal error: Device SCV Cartridge Slot load (scv:Doraemon (Japan):cart) failed: File not found

If I rename "Doraemon (Japan)" to something without spaces it works so it seems support for it got broken somewhere between 172 and 184.
@npwoods

**Comment by npwoods** [comment]
I don't see how this was ever supposed to work

The only entry for "Doraemon" in scv.xml looks like this:
> 
	<software name="doraemon">
		<description>Doraemon</description>
		<year>1985</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<feature name="slot" value="rom64k" />
			<dataarea name="rom" size="65536">
				<rom name="doraemon.0" size="32768" crc="ee0b874d" sha1="425eb6ed31faa2afdecc216145616f577f72db9a" offset="0" />
				<rom name="doraemon.1" size="32768" crc="d2de91a6" sha1="6aba5ee3d08afad222bec9a176c2607829fa5cc6" offset="0x8000" />
			</dataarea>
		</part>
	</software>

Even if descriptions were looked up, the text "Doraemon (Japan)" simply doesn't exist in scv.xml.  Either this worked by accident or I'm missing something (which is a very real possibility)

**Comment by happppp** [comment]
See -hashpath "K:\Emulators\MAME_Config\hash_custom".
I think what ssj did here was to change <software name="doraemon"> to <software name="Doraemon (Japan)">. MAME is strict about setnames and won't allow spaces. But the least we should do is detect setname string errors and give a more meaningful error message.

**Comment by npwoods** [comment]
Good catch.  IMHO MAME should be strict about software identifiers; there is quite a bit of code that needs to parse text that could either be a filename or a software "identifier" (which might be the name of a software entry, or a part)

**Comment by ssjbrollyus** [comment]
Yeah, I'm using a custom hash file, what do you mean with "MAME is strict about setnames and won't allow spaces" hap? This is the point here, MAME used to allow spaces on softlist setnames as I state on the issue, it just got broken somewhere after 0.172. I can try to find out exactly which release caused the regression if that helps.

**Comment by Robbbert** [comment]
Firstly do this:
**mame -valid**

This will point out the fact that your set name fails validation.

This was a change done a few versions ago to enforce the proper allowed characters in a set name. It is not a regression, it's a change.

**Comment by ssjbrollyus** [comment]
Ah that sucks, is there any real reason for space not being allowed? What are the proper allowed characters? Why not expand it to the whole ASCII set?

I don't think forcing users to stick with the naming schema from the 80's for all systems is a good thing (16 characters max?), I could live with it if there was a way to define mappers and other settings that can only be set in softlists through command line, but there isn't so I have to use softlists in some cases.

**Comment by npwoods** [comment]
The issue is that there is a great deal of code that needs to parse software list identifiers.  The calculus involved becomes much simpler if one lays down the law and sets rules for these identifiers.

If you're building something that is end user facing, use the "description" field, which is completely freeform.

**Comment by cuavas** [comment]
Set names are supposed to be a unique identifier that's easy enough to type on any keyboard layout and won't be mangled by any common shell or filesystem. Even underscores are sketchy here because you can't type them on e.g. a Japanese system with an ANSI keyboard plugged in (necessary key not present). The description or full name field allows any valid Unicode and unlimited length. It's there for human-readable friendly names.
