### ISSUE TITLE
Should Create or Rewrite Any Namco devices to unify implementations in various drivers

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#2230]
According to various Main PCB, I shared implementations are found in:
Namco C300, C304 (Spot) chips use for Namco System 22 , Namco Super System 22 and Namco Gorgon games.
Namco C374 (Spite), C379, C381, C399 (Spot), C400, C401, C406, C407 chips use for Namco Super System 22 and Namco Gorgon games.
Namco C361 (Text), C404 (gamma/palette) chips use for Namco Super System 22, Namco Gorgon, Namco System 23, Namco Super System 23, Namco System 23 Evolution 2 games.
Namco C403 Chip is controller, it use for Namco Gorgon, Namco System 23 games.
Namco C413 (DMA/MCU enable), C416 (Communication RAM), C417 Chips use for Namco Gorgon, Namco System 23, Namco Super System 23 games.
Namco C435 Chip is Polygon, it use for Namco Gorgon, Namco System 23,  Namco Super System 23, Namco System 23 Evolution 2 games.
Namco C444 (controller), C447 (SDRAM) Chips use for Namco Super System 23, Namco System 23 Evolution 2 games.
Namco C450, C451, C452 Chips use for Namco System 23 Evolution 2 games.
Should Create or Rewrite them that Fix some Problems for Namco System 22 , Namco Super System 22, Namco Gorgon, Namco System 23, Namco Super System 23, Namco System 23 Evolution 2 games.

**Comment by galibert** [comment]
Get a clue
