### ISSUE TITLE
konami 68k Game bugs

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#2247]
O. Galibert updated Konami 68k, Improve text layer in Mystwarr set, Fixed Title Screen not faded in mystwarr sets, But has game Problems:
Errors: 053246/055673 Sprite Generator Combo device 'sprites': Required memory region 'sprites' not found.
metamrph doesn't boot.
mystwarr has Graphics Problem in attract mode.
Missing Graphics in Lethal Enforcer II.
Scroll, text not set up correctly. 
https://github.com/mamedev/mame/tree/konami

**Comment by MooglyGuy** [comment]
This issue has been submitted by a well-known spammer who has constantly e-mailed several of our developers, continues to evade bans set on MAME-related forums, and does nothing but repost already-known information under the presumably unfortunate impression that he is being helpful. Accordingly, this issue has been closed.
