### ISSUE TITLE
pcecd games don't load from built in interface.

### ISSUE THREAD

**Issue by damopinn** [mamedev/mame#2271]
When i try to load a pcecd game from the built in interface it stop on a screen which tells me i must load the images but it seems to be correct. trying to select any software always cause a crash.
![screenshot from 2017-05-03 11-07-11](https://cloud.githubusercontent.com/assets/26623617/25654261/b6d0f074-2ff0-11e7-8b04-d7f83da71ba9.png)
if i run "./mame64 pce draculax" or "./mame64 pce -cart pce:scdsys -cdrm pcecd:draculax" it loads fine.
running "./mame64 pce -cdrm pcecd:draculax" doesnt work it give the same screen.

**Comment by npwoods** [comment]
Given that I've been refactoring the softlist greatly in recent times, this is almost certainly related to my work.  I will say that one of the biggest challenges in what I've been doing has been trying to understand "How softlists are supposed to work"

The specific command line you've identified seems to have worked in MAME 0.182, but stopped working in MAME 0.183.

**Comment by Tafoid** [comment]
This has been known for a while.  A related MT bug is [HERE](http://mametesters.org/view.php?id=6557)

**Comment by Robbbert** [comment]
According to that MT bug report, the issue has been fixed. Closing.
