### ISSUE TITLE
Missing information on the "Image Information" menu

### ISSUE THREAD

**Issue by dankan1890** [mamedev/mame#2286]
Follow the picture below, you may notice that some information (year, manufacturer, and full name) are missing.

![mame 2017-05-07 00-59-21-83](https://cloud.githubusercontent.com/assets/7107228/25776567/c1cfb0b8-32c1-11e7-8a1c-ecad761288fc.png)

**Comment by ajrhacker** [comment]
This looks like the result of an inadvertent change made during @npwoods's extensive refactoring in 81c8de57ca596c2bf186d79636ec3c7d8fc56b69.

Removing the `if` wrapper seems to fix this; it was probably only intended for the make_readonly call that isn't there now.

**Comment by Robbbert** [comment]
This seems to be fixed now. In the case of the software above, it now says
A.E.
Broderbund, 1982
