### ISSUE TITLE
docs/CONTRIBUTING.md is empty

### ISSUE THREAD

**Issue by stilett0** [mamedev/mame#2294]
Import from @ChoccyHobNob (on Aug 16, 2016)
"CONTRIBUTING.md does not provide any information on what (if any) contributions are wanted for the documentation. Reviewing the guidelines for contributing to this repository is a pretty zen experience!"

**Comment by stilett0** [comment]
Noted. We'll see what we can do.

**Comment by Firehawke** [comment]
Well, we could use translations in various languages and better instructions on use of the PC/Console drivers, Those are the first two things that come to mind.

I'm working on getting the command-line stuff updated now.

**Comment by ChoccyHobNob** [comment]
I thought this issue was closed! I swear I saw someone say the docs had moved to the main repo now!

**Comment by stilett0** [comment]
You're right, @ChoccyHobNob. I copied the issue over to the main repo because it was unresolved.

The docs HAD moved to the main repo... but the actual issue you had reported @ChoccyHobNob had not been reported there and was still unresolved.

The old github.com/mamedev/docs is going to either be deleted or locked Real Soon Now to prevent future accidental issues created there, so I wanted the issue to be noted in the main repo.

**Comment by stilett0** [comment]
You're right, @ChoccyHobNob. I copied the issue over to the main repo because it was unresolved.

The docs HAD moved to the main repo... but the actual issue you had reported @ChoccyHobNob had not been reported there and was still unresolved.

The old github.com/mamedev/docs is going to either be deleted or locked Real Soon Now to prevent future accidental issues created there, so I wanted the issue to be noted in the main repo.

Sorry for the confusion.

**Comment by mnaberez** [comment]
> The old github.com/mamedev/docs is going to either be deleted or locked

This is a good idea.  Even mamedev committers have made accidental commits to the old repo since the docs moved here.

**Comment by Robbbert** [comment]
File still empty.

**Comment by EarBiteR** [comment]
Updating that file with a LINK to https://docs.mamedev.org/contributing/index.html is all thats needed.

**Comment by cuavas** [comment]
There’s already a CONTRIBUTING.md file in the repository root: https://github.com/mamedev/mame/blob/master/CONTRIBUTING.md

**Comment by EarBiteR** [comment]
I saw that, but when mame is built and available for download - the file is
2 bytes ie: empty. Either remove the file from the build or populate it
with whats in the repo so the ticket can be closed :-)

**Comment by cuavas** [comment]
I just checked a binary release, and no CONTRIBUTING.md file is included in the binary archive.  The PDF version of the manual is included as docs/MAME.pdf including the contribution guidelines section.

The source archive includes the CONTRIBUTING.md file at the top level, but it contains the link to the documentation on the web.

I don’t see any 2-byte CONTRIBUTING.md file in current MAME source, or in release distribution archives.

**Comment by EarBiteR** [comment]
I DL the latest 2.61 win exe and verified what you said.  Obviously this has been fixed so the ticket can be closed.
