### ISSUE TITLE
Search bar broken after changing ROM list view mode

### ISSUE THREAD

**Issue by anewuser** [mamedev/mame#2295]
- Launch mame64.exe 
- Search for a ROM in the `All` view. For example, type in "1942".
- Click on `Available`.

Result:  the search bar is erased, and I can't start any other search. I need to run a ROM then close it, or restart MAME for it to work again.

mame64.exe 0.185
Windows 10

**Comment by ajrhacker** [comment]
Reproduced and fixed in dccefed038b63d718deb0d6046d8a72b3d1151f5.

**Comment by anewuser** [comment]
@ajrhacker Thank you for working on this. Are you using both this repository and mametesters.org to track issues separately?

**Comment by stilett0** [comment]
To answer generally and quote @Tafoid :

"For the most part, github.com/mamedev/mame/issues is more of an immediate need thing.. mametesters.org only tracks from release to release so WIP bugs are not appropriate there. (At least how it was originally designed.) Remember, back when MAMETesters was set up, MAME didn't even have a publically pullable SVN and sources were only released by us at release time."

Not to mention mametesters.org is more "gamer/user friendly" and github.com is more "developer friendly"
