### ISSUE TITLE
Drivers saved to favorites UI are run without showing software list

### ISSUE THREAD

**Issue by anewuser** [mamedev/mame#2297]
* Launch mame64.exe 
* Select a driver such as the "Nintendo Entertainment System / Famicom" and press enter, or double click on it

As expected, the list of software related to it is shown if you've set the paths properly. 

* Press <kbd>Esc</kbd> to go back to your complete list of machines
* Save "Nintendo Entertainment System / Famicom" to your favorites
* Select it from your favorites and press enter, or double click on it

Result: MAME attempts to "boot up" the ROM and tells you to insert a cartridge.

Expected result: MAME should show the software list associated to this favorited driver, as in the first step.

mame64.exe 0.185
Windows 10

**Comment by Tafoid** [comment]
I believe every machine that is saved in Favorites is run as if you are running "mame64 (setname)" from command line fresh as it starts a fresh instance to run it to avoid any leftover corruption (I assume?).  Given the way the UI is set up, I'm not certain if there is a way this can be avoided within the current design.

**Comment by anewuser** [comment]
This has been fixed on 0.186.
