### ISSUE TITLE
sensitivity to discontinuous time change

### ISSUE THREAD

**Issue by 057a3dd61f99517a3afea0051a49cb27994f94d** [mamedev/mame#2309]
Hi mamedev, I'm using mame0185 under linux. I encountered this problem when stop mame, i.e.(pkill -stop mame, or Ctrl+Z under the shell that launched mame), and then go do something else, and then continue mame(pkill -cont mame or fg under shell), CPU usage will suddenly jump to 100 percent on a single core, and mame will become very unstable, sometimes it's still working fine, sometimes the audio is distorted, and sometimes it will crash.(It seems that arcade games are not affected, but occurred on gba and nes subsystems.)
However, by using [libfaketime](https://github.com/wolfcw/libfaketime), I can reproduce this very reliably, even on arcade games, by running:
`FAKETIME_START_AFTER_SECONDS=30 faketime -f '+1y' mame64 dino`
Which means suddenly change the system time to next year after 30 seconds, this will always cause the 100 percent CPU usage.
And by running:
`FAKETIME_START_AFTER_SECONDS=30 FAKETIME_STOP_AFTER_SECONDS=35 faketime -f '+1y' mame64 dino`
Which means change the system time to next year after 30 seconds, and change it back after another 5 seconds, this will cause mame to completely freeze, unresponsive to any keystroke.
Is this the expected behavior or a bug? It would be really convenient for me if I could stop mame and do something else and then continue it. Thanks!

**Comment by rb6502** [comment]
In general you're intended to pause MAME (the "P" key by default), which should release any CPU usage, if you need to suspend it temporarily.  For longer-term suspend-and-resume, the -autosave feature works for most drivers.

The problem you're seeing is likely in the SDL library, but without backtraces or a profile of the problem that's just a guess.

**Comment by galibert** [comment]
Hmmm, P does not release CPU usage since we render in a loop to help in
debugging...

  OG.

**Comment by 057a3dd61f99517a3afea0051a49cb27994f94d** [comment]
Thanks for your quick reply, rb6502, galibert.

So I rebuild mame with gprof support by:
`make PROFILE=1 SOURCES=src/mame/drivers/gba.cpp`.
And created two gprof profiles, the first one by running:
`FAKETIME_START_AFTER_SECONDS=5 faketime -f '+1y' ./mame64p gba`,
the second one by:
`./mame64p gba`,
I didn't launch any game, and let both instance run for 20 seconds.

The most obvious difference between those two profiles is that the first instance, i.e. the one with discontinuous jumps in the system time, spend most of its time in the function `video_manager::throttle_until_ticks(unsigned long)`.

[I uploaded the gprof output for your review](https://gist.github.com/057a3dd61f99517a3afea0051a49cb27994f94d/9ea35d20a77c60027b7165b23fa16470).

**Comment by 057a3dd61f99517a3afea0051a49cb27994f94d** [comment]
After some more digging, I think I have found the (partial?) problem, here's what I found out:

The 100 percent CPU usage is indeed caused by the busy loop inside the function `video_manager::throttle_until_ticks`(src/emu/video.cpp), typically it's not a busy loop since most of the time it's sleeping using the `osd_sleep` function, however, this class keeps a variable called `m_average_oversleep`, it's updated whenever `osd_sleep` overslept, and is supposed to be the average number of milliseconds that will be overslept if you request to sleep one second. When this variable is positive, the throttling procedure will actually try to sleep less, so that the actual sleeping time will be accurate.

However, if the system time suddenly jumps forward, `m_average_oversleep` will be updated to a very large value, which will cause a very small `delta`, and as you can see in the code, the procedure will not try to sleep if `delta` is less than one millisecond, finally makes this loop a busy one.

A partial solution I thought is to not update the `m_average_oversleep` variable when the actual slept time is way beyond the time we requested, say, larger than twice the value of `delta`, which is very likely resulted by a system time change, instead of inaccuracy of sleep. I tried this and seems to work fine so far.

It's still a problem if the system time suddenly jumps backward, which will cause this procedure to potentially sleep a very long time, cause the entire process freeze. And when I try to detect this and break out the loop, mame seems to working fine after some distorted audio, but it's completely unresponsive to any keystroke. I haven't investigated this situation more.

**Comment by rb6502** [comment]
Oh, interesting!  Nice catch.  If you wanna submit that as a pull request I'll be happy to approve it.
