### ISSUE TITLE
Lua engine: drawing methods do not display anything 

### ISSUE THREAD

**Issue by DanAmador** [mamedev/mame#2327]
I'm currently testing out features and trying to draw a simple HUD using the lua engine

The 	manager:machine().screens[":screen"] namespace does print out useful information whenever you please the drawing methods seem to be useless.

My code testing out the features is the following:

```
function draw_hud()
	s:draw_text(40, 40, "foo"); -- (x0, y0, msg)
	s:draw_box(20, 20, 80, 80, 0, 0xff00ff); -- (x0, y0, x1, y1, fill-color, line-color)
	s:draw_line(20, 20, 80, 80, 0xff00ff); -- (x0, y0, x1, y1, line-color)


	manager:machine().screens[":screen"]:draw_text(40, 40, "foo") -- (x0, y0, msg)
	manager:machine().screens[":screen"]:draw_box(20, 20, 80, 80, 0, 0xff00ff) -- (x0, y0, x1, y1, fill-color, line-color)
	manager:machine().screens[":screen"]:draw_line(200, 20, 20, 80, 80, 0xff00ff) -- (x0, y0, x1, y1, line-color)
end
s = manager:machine().screens[":screen"]

emu.register_frame(draw_hud, "frame")


```

**Comment by cracyc** [comment]
emu.register_frame is called at the end of the emulated frame but before it's displayed. Use emu.register_frame_done which is called after it's drawn (but isn't called when a frame is skipped),

**Comment by DanAmador** [comment]
That worked perfectly, thanks a lot! 

Is there a way for me to update the documentation for future reference?

**Comment by DanAmador** [comment]
Thanks a lot! 

I'll be sure to update the docs for future reference.

**Comment by cracyc** [comment]
Let me know if you have any more questions or suggestions.
