### ISSUE TITLE
MAME exception: Unknown slot option 'game' in slot 'cassette'

### ISSUE THREAD

**Issue by Enverex** [mamedev/mame#2348]
Just noticed this error pop up when trying to query the XML for some games, e.g. "sdlmame -lx hyperbbc" (ignore the name sdlmame, it's normal mame with a legacy name). The output is...

```
(some perfectly normal stuff, then...)
                <!ELEMENT softwarelist EMPTY>
                        <!ATTLIST softwarelist name CDATA #REQUIRED>
                        <!ATTLIST softwarelist status (original|compatible) #REQUIRED>
                        <!ATTLIST softwarelist filter CDATA #IMPLIED>
                <!ELEMENT ramoption (#PCDATA)>
                        <!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.185 (unknown)" debug="no" mameconfig="10">
        <machine name="hyperbbc" sourcefile="ksys573.cpp" romof="sys573">
                <description>Hyper Bishi Bashi Champ (GQ876 VER. EAA)</description>
                <year>1998</year>
                <manufacturer>Konami</manufacturer>
                <biosset name="std" description="Standard"/>
                <biosset name="gchgchmp" description="Found on Gachagachamp"/>
                <biosset name="dsem2" description="Found on Dancing Stage Euro Mix 2"/>
MAME exception: Unknown slot option 'game' in slot 'cassette'
Attempting to fall into debugger
/usr/bin/sdlmame: line 56: 26831 Trace/breakpoint trap   (core dumped) ./sdlmame "$@"
```

**Comment by Tafoid** [comment]
There were some WIP regressions related to slot handling which have all been fixed.  Your **<mame build=** isn't listing the proper commit hash so we can't tell when precisely when your source is from (but, based on my tests I'd roughly estimate is end of April, beginning of May).  That particular error was fixed on or about May 5th and hasn't shown up again AFAIK in my testing.  You may want to pull some newly updated source.

**Comment by Enverex** [comment]
It's the official Arch Linux package which apparently uses the official release (https://github.com/mamedev/mame/releases/tag/mame0185 / Apr 26th) source bundle, so if it was fixed on May 5th it would make sense.

I'll build from GIT now to double check that it's fixed since then and report back.

**Comment by Tafoid** [comment]
Yes.  The 0.185 source package did go out where if you choose a number of ksys573.cpp games and individually used -listxml on those machines, the output was unable to complete... giving your exception above.  Full project -listxml outputs still worked fine so this was, sadly, not detected as quickly as the bug was detected when a game was run starting April 16th  The per-game loading bug was fixed within a few days but the specific machine -listxml output was not fixed until May 5th,

**Comment by Enverex** [comment]
Yup, just tried GIT and that worked fine. Thanks for the info @Tafoid.

**Comment by Tafoid** [comment]
For clarification, I entered and resolved a bug on MameTesters so that it is properly logged and can be referenced:     http://mametesters.org/view.php?id=6591
