### ISSUE TITLE
a2600 parent ROM bobhome isn't recognized

### ISSUE THREAD

**Issue by anewuser** [mamedev/mame#2353]
These four a2600 ROMs have bobhome as their parent: bobhomej, bobhomec, bobhomessc, bobhomer.

However, bobhome itself isn't listed in the GUI. Trying to run it from the command line gives the error that it isn't compatible with the a2600 system.

This is the only such case I've found on MAME so far. If support for bobhome  was removed for some reason, shouldn't one of the functional clones be picked to replace it as the "parent"?

mame64.exe 0.186
Windows 10

**Comment by etabeta78** [comment]
The parent in expected to be run on the PAL console.
If you launch the game with the full syntax -cart bobhome you will be able
to launch emulation  in a2600 but you will probably get only an empty
screen (which is the reason why PAL carts are disabled by default with
shortcut launch)





On Thursday, June 1, 2017, anewuser <notifications@github.com> wrote:
> These four a2600 ROMs have bobhome as their parent: bobhomej, bobhomec,
bobhomessc, bobhomer.
>
> However, bobhome itself isn't listed in the GUI. Trying to run it from
the command line gives the error that it isn't compatible with the a2600
system.
>
> This is the only such case I've found on MAME so far. If support for
bobhome was removed for some reason, shouldn't one of the functional clones
be picked to replace it as the "parent"?
>
> mame64.exe 0.186
> Windows 10
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/qqts87VmkyORG3emMgy0wHaxr1leSAJg_ES7NSMnxaNA59q7BOLQj-4SM9gA4jpF_iIrSP5Ku1Xa5h3ky-9FnCDpignHHBaAcQ3hAIRrZiZrH0WBsRXVobDTCQoWDyAXm1ribNIgeG5MN6L5tKb-GmTmS9X8RQ=s0-d-e1-ft#https://github.com/notifications/beacon/AI0qvGAxyOmbm3cOnAXKB5b7pHgT0W_Zks5r_jM2gaJpZM4NsdQx.gif>

**Comment by anewuser** [comment]
Thank you for the reply. I thought all console games were grouped together because megadriv (for example) shows sonic3u (related: #2354).

**Comment by etabeta78** [comment]
The filter-games-based-on-region has (so far) been added only to some
systems and not all, and in some consoles (Megadrive and SNES, for
instance) games have been filtered only when they only display a black
screen if booted on a different region

**Comment by anewuser** [comment]
I see. I'll start posting on the official forum before opening new issues. Sorry for the noise.
