### ISSUE TITLE
Guardian Force not working in 0.186

### ISSUE THREAD

**Issue by ssfsx17** [mamedev/mame#2360]
It functions up to the point of inserting a coin, but after pressing start, the game hangs.

Tested that other STV games are working, just not Guardian Force.

See this VOD at around the 5-minute mark: https://www.twitch.tv/videos/149608472

**Comment by p1pkin** [comment]
I see this game wait forever for ODD bit, likely caused by one of below changes
28e287458e5000b7f9ea833251605526e40ab33e
c1f721a2504383df297017bfac622a97e3b1c7f7

@angelosa any ideas ?

**Comment by angelosa** [comment]
Needs to be tested on real HW, that's my idea.

**Comment by Osso13** [comment]
This has been working again since 0.191. Closing.
