### ISSUE TITLE
Mame crashes when exiting back to the system menu from either coco12 or coco3.

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#2365]
If you run Mame without selecting a system so you get the SDL system menu and then run any of the coco emulations from the SDL system menu, when you exit the emulation Mame crashes rather than returning you to the menu.

**Comment by startaq** [comment]
I can't reproduce this here on Linux. Please try again with the current version.

**Comment by abcbarryn** [comment]
This bug occurs when launching from the favorites menu and was fixed some time ago.

https://github.com/mamedev/mame/pull/2372
