### ISSUE TITLE
Software loading menu always appears.

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#2366]
When launching coco12 or coco3 and probably others the software menu always appears. There should be a setting to bypass this and default to running with the last saved configuration.

**Comment by angelosa** [comment]
If by that you mean using the internal UI then yes, that's by design.
If you need finer grained control over your execution defaults then I suggest you to learn how to use the [CLI](https://docs.mamedev.org/commandline/commandline-all.html#), closing.

**Comment by npwoods** [comment]
Or use BletchMAME if you don't like the normal MAME UI
