### ISSUE TITLE
Rock'n Rage: sprite vs. bg priority bug at final boss

### ISSUE THREAD

**Issue by koitsu** [mamedev/mame#2375]
A friend of mine who plays Rock'n Rage quite a lot on MAME came across a recording of the actual JAMMA PCB being played.  During the final boss (Monster Kids) of the game, She-na can be seen struggling "within" the crystal ball in background; in MAME she isn't visible at all.  I'm left thinking this is some sort of sprite vs. bg priority aspect that isn't being emulated.  Also note that in the below MAME recording, when John dies near the crystal ball, it looks like he's being clipped, like there's a priority or maybe IRQ scanline effect where She-na should be.

JAMMA PCB recording: https://www.youtube.com/watch?v=Y2oAEMSPlag&t=19m32s
MAME recording: https://www.twitch.tv/videos/147701451?t=51m12s

This is for MAME 0.186.

Edit: seems GitHub won't allow .zip files with .sta save states.  Here is a save state that's immediately prior to the final boss, to help with debugging/narrowing this down: https://www.dropbox.com/s/36hzzvm4iaqwov9/z.zip?dl=0

Thank you!

**Comment by angelosa** [comment]
Processed, thanks.

**Comment by koitsu** [comment]
Thank you!  Looks like commit 9a3eed81491bfc3e7aaad65f9f443bc7dcec4801 should fix this.

And sorry, going forward I'll report these type of issues on mametesters.org.
