### ISSUE TITLE
Save states to an ostream rather than straight to a file

### ISSUE THREAD

**Issue by vadosnaprimer** [mamedev/mame#2398]
This opens a whole new path and allows lots of savestate juggling, especially if wired up in lua. The basic functions would be:
- create - allocates the buffer to be used
- save - writes a savestate to the provided buffer
- load - loads it from the provided buffer
- flush - record to disk, with a specific name, or with a name that can then be used from gui state/load functions

An essential feature would be variable compression level, if we need speed for mass-saving, or minimal size for transferring.

Application examples:
- sending states over the network (i. e. lua sockets)
- creating a rewind buffer of arbitrary size (for every frame, or for every hit of Step Into, with lua it's equally easy)
- brute force bots (whenever tas features are incorporated)
- letting a frontend control the savestates

Here's my preliminary draft on this feature. I tested it from bizhawk as a frontend.
[buffer_states.zip](https://github.com/mamedev/mame/files/1092771/buffer_states.zip)

**Comment by rb6502** [comment]
This is now completed with PR 6345 accepted.
