### ISSUE TITLE
Save state UI issues

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#2411]
There seem to be multiple issues with the save state menus:

* If you input to bring up the load or save menu and there are no save states present, hitting the UI Cancel input will dismiss the menu but won't resume emulation, you'll be left paused.  The behaviour is different if one or more save states exist.
* Navigate to an in-game menu, e.g. bookkeeping, then dismiss it with the Tab key, then hit the button to load a save state, and hit a key to load an existing state.  Rather than dismissing the menu, it will jump back to the menu you previously dismissed.

**Comment by cuavas** [comment]
@angelosa has experienced the second issue, too.

**Comment by Robbbert** [comment]
These appear to be fixed.
