### ISSUE TITLE
ROM path not honoured in mame.ini

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#2412]
On an OSX machine, I have a `mame.ini` in working directory containing a `rompath` with two semicolon-separated oaths (I also have a `~/Library/Application Support/mame/ui.ini` but it contains no `rompath`).  The `rompath` in `mame.ini` is not honoured - ROMs are not found.  Passing the exact same path on the command line works.  @einstein95 has experienced the same issue.

**Comment by einstein95** [comment]
In mine, my rompath is `/data/roms/MAME;$HOME/.mame/roms;/data/roms/neogeo;/data/roms`.

**Comment by cuavas** [comment]
Oh, just in case anyone wonders, it's definitely reading the `mame.ini` because it's picking up `window 0` from it properly.  My `rompath` has one absolute and one relative path in it.

**Comment by rb6502** [comment]
I have a multi-part ROM path in my mame.ini on OS X Sierra and it's working fine; CHDs would not work if it didn't.

**Comment by npwoods** [comment]
I'm unable to reproduce this error, but I don't have an OS X box.

**Comment by rb6502** [comment]
I actually have the reverse problem, multi-part rompaths on the command line ignore everything after the first path, only ones in mame.ini work.

**Comment by cuavas** [comment]
@einstein95 is using Linux, so it's not specific to OSX.  There's definitely something weird going on with path handling - have you run under valgrind or something to check for memory errors?

**Comment by startaq** [comment]
It looks like there is an issue if you are using a full path. On my system, a relative rompath like "roms" works fine, but if you change it to the full path "/home/user/mame/roms" it stops working.

**Comment by bmunger** [comment]
I have not been able to reproduce this issue on Ubuntu 16.04 64bit.  I have a build of mame from Jul 2 08:52:17 with commit 54763b6e0f322e7c3f2abce18c2bafece930a777.

I have a copy of ui.ini under ~/.mame/ui.ini with no rompath set.  I copied mame64 to a new directory and created a new mame.ini and set rompath to roms;/path/to/roms.  There are no roms directory in the mame working directory, however the path was set to it in the rompath.  Running mame64 with a driver name as its argument, it  was able to find the required roms.

**Comment by npwoods** [comment]
I would love it if someone that could reproduce the problem could add the following debugging code to path_iterator::next() in src/emu/fileio.cpp:

`bool result;`
`...`
`printf("path_iterator::next(): buffer=%s name=%s result=%s", buffer.c_str(), name, result ? "true" : "false");`

...and send me the output after reproducing the problem.

**Comment by cuavas** [comment]
It's not happening any more.  I ran it under valgrind and didn't catch any new issues in options.

**Comment by motoschifo** [comment]
Starting from release 0.187 I had this error during playback of inp files. I have the same error with latest 0.190, the rompath is not working if double quotes are used from command line.
I use a Linux build, roms and bioses are in separate folders.
Did you found a fix for that?
