### ISSUE TITLE
Cannot use File Manager to load ROMs

### ISSUE THREAD

**Issue by Tauwasser** [mamedev/mame#2414]
Using File Manager to load games does nothing when the machine was started empty. Steps to reproduce:

1. start a machine, e.g. GameBoy
2. select "[Start empty]"
3. select any BIOS if applicable (e.g. DMG_vX)
4. Press TAB
5. Select "File Manager"
6. Select any valid file

The machine will now be reset, but the game won't be loaded.

**Comment by Tafoid** [comment]
Can confirm.  Again, sourced in #2341, My binaries made of this PR from June 4 and June 16 load the game chosen properly per the instructions indicated.  The June 17 binary, however, shows this error (game slot empty) and it seems to be this last moment bugfix which causes it: https://github.com/mamedev/mame/pull/2341/commits/a02673d36a10ba3f6791e7e466f229ac9bd507b6

**Comment by Tauwasser** [comment]
Can confirm this is fixed in master (030ab611937bbaafb9d3f7144b2ab031add9d3c6)
