### ISSUE TITLE
Mac devices need raw 1.44MB floppy image support

### ISSUE THREAD

**Issue by eschaton** [mamedev/mame#2419]
I can’t seem to mount a raw 1.44MB floppy image using the Mac IIci device, only raw 400KB or 800KB floppy images.

Attempting to mount a raw 1.44MB floppy image just gets an alert in the emulated Mac that the disk is damaged and asking whether to initialize it as one-sided or two-sided, which indicates that the emulated system is seeing it as an 800KB disk.

Passing a raw 1.44MB floppy image as `-flop1` is simply not recognized at all, with no output from `mame64`.

**Comment by rb6502** [comment]
1.44MB disks are not supported because they use a completely different disk controller chip and drive architecture than 400/800k Macs.

**Comment by eschaton** [comment]
Thanks! I started trying to trace through the `apple_fdc` code and it wasn’t clear why things were going wrong, this explains it. Is there a page I can read on how to attach an `image` device in a slot, and then attach images to it?

**Comment by rb6502** [comment]
From the command line, "mame systemname -listslots" will indicate all the possible slots in the system and what can go in them.  For the IIci, you'll see NuBus slots "nbc", "nbd", and "nbe" and a list of available cards.  The image card is called "image" and has the description "NuBus Disk Image Pseudo-Card" ("pseudo" because it doesn't correspond to real hardware, it was created for emulation).

So to put the image card in slot C, you'd do "mame maciici -nbc image" and then add "-disk whatever.img".  Finder will auto-mount the image once it comes up.

**Comment by rb6502** [comment]
Oh, and I should note that just like in real life, each NuBus card has a declaration ROM that MAME will need to load when you add that card.  Most of them I dumped myself, but the image card's ROM was hand-written in MPW for me by Rob Braun.

**Comment by eschaton** [comment]
Thanks for the tips! It looks like the `image` device will only work for images less than 256MB though, since it looks like since they need to fit entirely in NuBus slot space. Wonder how hard it’d be to hack it to window…

**Comment by rb6502** [comment]
The major thing is that the driver in the card's ROM would need to be modified.  It'd be fairly simple to put an offset register in the appropriate slot space and page through the file otherwise.

**Comment by rakslice** [comment]
Perhaps there should be an error message when selecting a floppy image that is too large, similar to the one that is currently shown when selecting an `image` that is too large?

**Comment by rb6502** [comment]
This is now in progress and SuperDrive support should start appearing as early as the end-of-August 2019 release, hopefully including support for protected originals imaged with the AppleSauce peripheral.

**Comment by rb6502** [comment]
Well, I was wrong on the timing on that one, but MAME 0.230 was just released with full SuperDrive support and new cycle-accurate emulation of the IWM, SWIM, SWIM2, and SWIM3 controller chips.  Both 800K and 1.44M disks are supported on models with SuperDrives.
