### ISSUE TITLE
AppCrash when saving the configuration via GUI

### ISSUE THREAD

**Issue by Tauwasser** [mamedev/mame#2420]
Using

1. "Configure Options"
2. "Video Options"
3. Change "Window Mode" to "On" (or anything else)
4. go back to Previous Menu
5. "Save Configuration"

Now I get an AppCrash

> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	mess64.exe
>   Application Version:	0.186.0.0
>   Application Timestamp:	59529ff4
>   Fault Module Name:	mess64.exe
>   Fault Module Version:	0.186.0.0
>   Fault Module Timestamp:	59529ff4
>   Exception Code:	c0000005
>   Exception Offset:	0000000001d018c9
>   OS Version:	6.1.7601.2.1.0.256.48
>   Locale ID:	1033
>   Additional Information 1:	3cfd
>   Additional Information 2:	3cfda27a3b788a50438654d73e859de3
>   Additional Information 3:	d13a
>   Additional Information 4:	d13a4134252cebaa4b0a4ddf266195c5

**Comment by Tafoid** [comment]
Confirmed.  Related to changes made in #2341.  Baseline release works for 0.186, not in current master after the previously mentioned PR was applied.

**Comment by Tafoid** [comment]
-----------------------------------------------------
Exception at EIP=0000000003495a88 (core_options::value(char const*) const+0x0078): ACCESS VIOLATION
While attempting to read memory at 0000000000000000
-----------------------------------------------------
Stack crawl:
  0000000000227a00: 0000000003495a88 (core_options::value(char const*) const+0x0078)
  0000000000227f90: 0000000001c2afa3 (mame_ui_manager::save_main_option()+0x0183)
  00000000002280c0: 0000000001d09652 (ui::menu_game_options::handle()+0x01a2)
  0000000000228120: 0000000001cfc8db (ui::menu::ui_handler(render_container&, mame_ui_manager&)+0x00db)
  0000000000228150: 0000000004c96f57 (std::_Function_handler<unsigned int (render_container&), std::_Bind<unsigned int (*(std::_Placeholder<1>, std::reference_wrapper<mame_ui_manager>))(render_container&, mame_ui_manager&)> >::_M_invoke(std::_Any_data const&render_container&)+0x0017)
  0000000000228250: 0000000001c22252 (mame_ui_manager::update_and_render(render_container&)+0x0152)
  0000000000228280: 0000000001beec40 (emulator_info::draw_user_interface(running_machine&)+0x0020)
  0000000000228310: 000000000327991d (video_manager::frame_update(bool)+0x003d)
  0000000000228410: 0000000003205679 (running_machine::run(bool)+0x03e9)
  000000000022f1d0: 0000000001bf0aa3 (mame_machine_manager::execute()+0x01e3)
  000000000022f490: 0000000001c4b286 (cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>,std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x0416)
  000000000022f600: 0000000001c4b735 (cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x0045)
  000000000022f660: 0000000001beebea (emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x002a)
  000000000022fdb0: 0000000001b42402 (utf8_main(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x0122)
  000000000022fe50: 00000000037779e9 (wmain+0x0169)
  000000000022ff20: 0000000000401410 (__tmainCRTStartup+0x0260)
  000000000022ff50: 000000000040153b (mainCRTStartup+0x001b)
  000000000022ff80: 00000000771b59cd (BaseThreadInitThunk+0x000d)
  000000000022ffd0: 00000000773ea561 (RtlUserThreadStart+0x0021)

**Comment by Tauwasser** [comment]
I can confirm this is gone with HEAD 229959ee7d.
