### ISSUE TITLE
Fatal Error when leaving full screen mode using Windows key

### ISSUE THREAD

**Issue by Tauwasser** [mamedev/mame#2421]
When leaving fullscreen mode using the Windows key, Mess crashes with the following message:

> ---------------------------
> MESS
> ---------------------------
> Fatal error: Fatal error: Too many live texture instances! (../../../../../src/emu/render.cpp:490)
> 
> ---------------------------
> OK   
> ---------------------------

EDIT: Alt+Enter works.

**Comment by Tafoid** [comment]
This is already at MAMETesters:
http://mametesters.org/view.php?id=6264

**Comment by Robbbert** [comment]
Please add any further comments to the above Mametesters report. Closing.
