### ISSUE TITLE
Error compile from the source MAME Broke Urgent !

### ISSUE THREAD

**Issue by aperfeito** [mamedev/mame#2426]
Hi , 
Thu Jun 29 15:28:58 PDT 2017

My system is : 
Linux version Kernel 3.10.18-19-ARCH armv7l GNU/Linux --> 32 Bits Tegra TK1 Processor + GTK20A GPU
compiling using gcc : 
gcc (GCC) 7.1.1 20170516
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
After i did this command::

make TARGET=mame REGENIE=1 TOOLS=1 SUBTARGET=mame -j5

Error in compile

In file included from ../../../../../src/devices/cpu/saturn/saturn.cpp:72:0:
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_exchange(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_exchange(int left, int begin, int count, int right)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_copy(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_copy(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_or(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_or(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_and(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_and(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
cc1plus: all warnings being treated as errors
make[2]: *** [optional.make:15402: obj/Release/src/devices/cpu/saturn/saturn.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:88: optional] Error 2
make: *** [makefile:1253: linux] Error 2
[aperfeito@alarm mame]$ 

Waiting for fix code  about this files

**Comment by rb6502** [comment]
ARM targets are not officially supported yet; you may find that including NOWERROR=1 as part of the make command helps.

**Comment by happppp** [comment]
In src/devices/cpu/saturn/saturn.h

starting from line 181:
inline uint32_t saturn_pop();

to line 275:
inline void saturn_shift_right(int reg, int begin, int count);

Could you remove the "inline" and tell us if it compiles? IMO these inlines
aren't needed anyway.

**Comment by aperfeito** [comment]
Hi happppp,

Thank for you replay in the way positive I am here to help  though this go well in ARM too.

Folow the status after I change the file as you indicate:

Compiling src/devices/cpu/saturn/saturn.cpp...
Compiling src/devices/cpu/sh2/sh2comn.cpp...
In file included from ../../../../../src/devices/cpu/saturn/saturn.cpp:72:0:
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_exchange(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_exchange(int left, int begin, int count, int right)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_copy(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_copy(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_or(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_or(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_and(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_and(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
Compiling src/devices/cpu/sh2/sh2fe.cpp...
Compiling src/devices/cpu/sh2/sh7604_bus.cpp...
cc1plus: all warnings being treated as errors
make[2]: *** [optional.make:15402: obj/Release/src/devices/cpu/saturn/saturn.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:88: optional] Error 2
make: *** [makefile:1253: linux] Error 2

**Comment by happppp** [comment]
Sorry, I don't know what else could cause this warning. And I don't have the newest GCC to test it. For now just use NOWERROR=1 as rb6502 suggested :)

**Comment by peterferrie** [comment]
It looks like in this line:

	saturn_assert(begin>=0 && count>0 && begin+count<=16);

+...< is being evaluated before the > checks.
Perhaps this instead would fix it:

	saturn_assert(begin>=0 && count>0);
	saturn_assert(begin+count<=16);

**Comment by peterferrie** [comment]
> It looks like in this line:
>
> 	saturn_assert(begin>=0 && count>0 && begin+count<=16);

Actually, this is absolutely correct.  if begin and count were
0x40000000, for example, the resulting sum would be <= 16 and yet
overflow badly.
The compiler wants to see an upper limit check on both variables.

**Comment by aperfeito** [comment]
Ok... Next time when I pull git again the rep I will you check if the that line was fix
Thanks

**Comment by aperfeito** [comment]
Hi happp its not a promisse but next time i will not using NOWERROR=1 and give to you information about because is pass without problems when you use this parameter comment above . Right now I use mame V193

**Comment by zx70** [comment]
the suggested fix on the assertion doesnt seem to work
