### ISSUE TITLE
aliensyn

### ISSUE THREAD

**Issue by zombiesbyte** [mamedev/mame#2458]
`<control type="joy" player="1" buttons="3" ways="8"/>`

According to CP photo this only has 1 button per player.

**Comment by motoschifo** [comment]
Is the information about the 3 buttons correct?
If so, what is the function of buttons 2 and 3?
I see no source code changes about this.

Latest Mame 0.270 says this:
```
<input players="2" coins="2" service="yes">
     <control type="joy" player="1" buttons="3" ways="8"/>
     <control type="joy" player="2" buttons="3" ways="8"/>
</input>
```
