### ISSUE TITLE
Media options broken with custom instance names

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#2468]
Custom instance names and slot devices don't work properly with the current MAME options code.

Consider the following:
```
% ./mame64d intlc440 -listmedia
SYSTEM           MEDIA NAME       (brief)    IMAGE FILE EXTENSIONS SUPPORTED
---------------- --------------------------- -------------------------------
intlc440         promimage        (prom)     .rom  .bin  
                 punchtape        (ptap)     .bnpf .hex  .lst  .txt  
                 romimage2        (rom2)     .rom  .bin
```

The `prom` option comes from an onboard `imm6_76` device (src/mame/machine/imm6_76.{h,cpp}), while the `rom2` option comes from an `intlc4_imm6_26` (src/devices/bus/intellec4/prommemory.{h,cpp}) device that's in slot `j8` by default.

Both of these devices report `IO_ROM` as the image type as they use loose ROM chips (front-panel ZIF socket in the case of `imm6_76`, DIP sockets on card in the case of `intlc4_imm6_26`).

The `imm6_76` reports custom instance name `promimage`/`prom` because it's a PROM writer and supports creating/writing to PROM images as well as reading them.  Using the default `romimage`/`rom` would be misleading.

The `intlc4_imm6_26` device can't write to PROMs, it only reads from them.  It could equally well use `romimage`/`rom` or `promimage`/`prom` options.

The trouble is, when the options count all `IO_PROM` devices for the purpose of appending a numeric constant, and no numeric constant is appended if a custom name is used.

If you apply this diff:

```
diff --git a/src/devices/bus/intellec4/prommemory.h b/src/devices/bus/intellec4/prommemory.h
index 60a69f2..7760510 100644
--- a/src/devices/bus/intellec4/prommemory.h
+++ b/src/devices/bus/intellec4/prommemory.h
@@ -106,6 +106,8 @@ public:
 	virtual bool        must_be_loaded()                const override { return false; }
 	virtual bool        is_reset_on_load()              const override { return false; }
 	virtual char const *file_extensions()               const override { return "rom,bin"; }
+	virtual char const *custom_instance_name()          const override { return "promimage"; }
+	virtual char const *custom_brief_instance_name()    const override { return "prom"; }
 
 protected:
 	virtual void device_start() override;
```

Then you get this situation:
```
% ./mame64d intlc440 -listmedia
SYSTEM           MEDIA NAME       (brief)    IMAGE FILE EXTENSIONS SUPPORTED
---------------- --------------------------- -------------------------------
intlc440         promimage        (prom)     .rom  .bin  
                 punchtape        (ptap)     .bnpf .hex  .lst  .txt  
                 promimage        (prom)     .rom  .bin
```

Now you have two image devices with the same conflicting `prom`/`promimage` option.

I think there are two possible solutions:
* Count option names rather than image types for the purpose of appending numeric suffixes to options.  Then we'd get either `prom` and `rom` or `prom1` and `prom2` media options with the above examples.
* Count image types as we do right now but apply them to custom instance names.  Then we'd get either `prom1` and `rom2` or `prom1` and `prom2` media options with the above examples.

I can't hard-code the numeric suffixes in the devices, as I don't know how many of them there are or where they appear in machine configuration.

This is a release blocker.

**Comment by galibert** [comment]
Fixed by 9f614cdf442a93329f0992b4b7971b15e1edbae0.

That naming code is crap, and iodevice_t should die.
