### ISSUE TITLE
Netlist library fails to build in Visual Studio 2015

### ISSUE THREAD

**Issue by wiired24** [mamedev/mame#2476]
When building MAME in Visual Studio 2015 (With Update 3), for some strange reason the Netlist library is failing to build with Visual Studios compiler. It specifically complains about "Identifiers not being found" for two functions, "Loadlibrary" and "GetModuleHandle". Of course since the Netlist library fails to build the end result is a Linker Error. 

12>..\..\..\..\..\src\lib\netlist\plib\pdynlib.cpp(68): error C3861: 'LoadLibrary': identifier not found
12>..\..\..\..\..\src\lib\netlist\plib\pdynlib.cpp(70): error C3861: 'GetModuleHandle': identifier not found
12>..\..\..\..\..\src\lib\netlist\plib\pdynlib.cpp(96): error C3861: 'LoadLibrary': identifier not found
12>..\..\..\..\..\src\lib\netlist\plib\pdynlib.cpp(98): error C3861: 'GetModuleHandle': identifier not found

This error happens when building for both 32 bit and 64 bit

Any help on resolving this issue would be much appreciated.

**Comment by cuavas** [comment]
I believe UWP intentionally disallows loading DLLs dynamically like this.  You'll have to disable the netlist libarary's support for dynamically loading optimised solvers.

**Comment by wiired24** [comment]
Okay cool, Thanks for the tip. How would I go about disabling netlist support for loading optimized solvers dynamically?

**Comment by cuavas** [comment]
That's for you to work out.  UWP is not a fully-supported target.

**Comment by wiired24** [comment]
Then what's the point in it being there at all if it isn't fully supported? Shouldn't it just be deprecated since it's not gonna be fully supported? Makes little sense to me honestly

**Comment by cuavas** [comment]
Like the ARM and Android targets, we provide UWP targets in the build system to make it easier for interested people to maintain ports/forks that run on these platforms.  If we were to remove the support from the build system altogether, it would make life a lot harder for maintainers of these ports/forks.  We simply don't have enough people with the skills, motivation and time available to support these targets ourselves.

We tend to accept patches that improve support for non-mainstream platforms if they don't have a detrimental effect on the codebase (e.g. see recently-merged #2470 which improves behaviour under Emscripten).  If you can make a pull request improving support for UWP we'll likely accept it.  However we're not going to be able to help you implement that - if we had the time we'd have done it ourselves.

**Comment by wiired24** [comment]
I understand, well thanks for clearing it up for me. I'll see what I can do with regards to improving support for UWP.

**Comment by stilett0** [comment]
Crossposting is not cool, in this case.
http://forum.mamedev.org/viewtopic.php?f=14&t=217

**Comment by wiired24** [comment]
Yeah and I'm not the one who posted on the forums so dont blame me. There are several others in the community who are working on this as well. @stillett0

**Comment by stilett0** [comment]
Fine @wiired24 I apologize.

**Comment by wiired24** [comment]
It's fine man.
