### ISSUE TITLE
default / fallback Artwork

### ISSUE THREAD

**Issue by NJDave71** [mamedev/mame#2492]
it would be nice to be able to have fallback zip artwork file for horizontal and vertical orientation when there is no artwork present.

**Comment by cuavas** [comment]
Yeah, it would also be nice to be able to specify a layout directly on the command line or through an ini file.  Definitely shortcomings in this area.

**Comment by phulshof** [comment]
Well, with the help of cuavas it should be coming in 0.194. :)

**Comment by Robbbert** [comment]
It's been done. Closing.
