### ISSUE TITLE
Solar Assault Random crashed??

### ISSUE THREAD

**Issue by dragon2snow** [mamedev/mame#2558]
mame 0.188 64bit, OS windows10 .
Random crashed

**Comment by happppp** [comment]
Post these kind of bug reports on Mametesters.
I think it's already known: http://mametesters.org/view.php?id=5692

**Comment by dragon2snow** [comment]
Stage 3 crashes ?
Random crashes, stage 3,5,7

**Comment by happppp** [comment]
yeah, sounds like the same bug to me

**Comment by sjy96525** [comment]
I don't crash without DRC enabled.
