### ISSUE TITLE
The order of screen effects applied

### ISSUE THREAD

**Issue by anikom15** [mamedev/mame#2567]
I just noticed that the screen effects, e.g. screen brightness, contrast, gamma, &c. are applied before post-processing. Shouldn't these be applied after post-processing (and effect artwork as well)? At least I always thought these were for monitor corrections as a last resort. It doesn't make sense to me why they would be done before post-processing.

**Comment by cuavas** [comment]
Brightness (black level) and contrast (white level) are applied to the video signals in the front end of the monitor's circuitry.  It wouldn't make sense to apply them after phosphor effects etc.

**Comment by anikom15** [comment]
Okay. I thought that the shaders were supposed to implement all the signal modifications 'from system output to screen' on their own. I think some of the shaders in BGFX already do this. I think having these effects outside of the shader system can lead to some confusion (it did for me), but also I do see the value in having them separate. I think of them as 'post-processing fundamentals'. I think the NTSC processor and the color convolution in HLSL have a similar gravitas.

That said, if the status quo is good for everyone you can go ahead and close this.

**Comment by u-man74** [comment]
While i understand why screen brightness, contrast, gamma etc. are separated from the shader systems (i assume that way they can always work), i agree with anikom15 that they lead to confusion and even worse, they can lead to inconsistence by the way how they are treated (saved in .cfg file **and** .ini file) and as a result to unpredictable screen output.

Regarding this, I already opened a bug-thread at MAME-Testers a while ago:
http://mametesters.org/view.php?id=6068
