### ISSUE TITLE
SDLMAME segfaults when entering Video Options

### ISSUE THREAD

**Issue by salvadorp2001** [mamedev/mame#2617]
OS: Arch Linux Rolling Release
This happens both on git master and on Arch Linux's package of 0.188
Basically it just segfaults if I go to "Configure Machine" and then go to "Video Options"
Terminal log:
```
darkfm@arch-bedroom ~ % LANG=C sdlmame
/usr/bin/sdlmame: line 56: 13284 Segmentation fault      (core dumped) ./sdlmame "$@"
LANG=C sdlmame  19,40s user 2,98s system 35% cpu 1:02,92 total
139 darkfm@arch-bedroom ~ %      
```

**Comment by Tafoid** [comment]
Already reported and logged.  The posted release announcement this release suggested using 0.187 if your use case crashes - or you could hand-editing your mame.ini in the interm.
http://mametesters.org/view.php?id=6656

**Comment by Robbbert** [comment]
Since this is covered by the above-mentioned Mame Testers bug, I'm closing this.
