### ISSUE TITLE
chdman rfe: include a binary patcher in the program, in order to be able to upgrade fan hacks.

### ISSUE THREAD

**Issue by i30817** [mamedev/mame#2634]
The .chd format is starting to be used for iso based games, and it's being incorporated into other emulators, so i've been thinking of requesting a old feature i tried to get on maxcso: having the option of applying a patch during compression and keeping the reversal patch as a footer or header in the container.

One thing i noticed about file compression formats is that they interact spectacularly poorly with softpatching (because file modifications influence the compressed bytes after, which makes the patch much larger), which has a terrible reputation for iso formats anyway, because most emulators draw a very firm line of softpatching size limits. Encrypted data is another reason why binary patches become huge in recent games, but that has other workarounds (having decrypted romsets) that don't apply to this.

The solution is obviously hardpatching, but i'm very against this, because of course, i want to upgrade the patches, or remove them and apply others without redumping. Thus i normally keep a 'reversal' patch, from 'hardpatched iso' -> 'original iso'.

Taken on the context of a compression format this could be streamlined as applying the hardpatching on the _uncompressed_ file, creating the 'reversal' patch and only them compressing. To make this more seamless, the 'reversal' patch can be appended as a header, if the format and the tool allows it, since this would allow 'upgrading' the patch (decompress, apply reversal patch, apply new patch, create new reversal patch, compressing, append new reversal patch). 

The maxcso guys didn't want to do this, because they don't control the file format, but i think it doesn't hurt to suggest it here.

Obviously, if you accept the rfe, the binary patching format you choose should be at your criterion (probably something that interacts well with your compression). I use xdelta, but you may want to make a new format or use another. Any that is chosen is actually likely to become popular because this is a big usability obstacle.

Let me stress from experience that the operations of applying and upgrading a xdelta (for example) patch to a compressed game are extremely tedious without this kind of automation, and needs to keep a 'extra file' that can be lost from user error, so this is a big usability win for users. The commonly used alternative, keep the original game iso is much larger than a reversal patch (least optimal being those bad romsets with native encryption/compression like the psp when modifying just a single thing modifies the  rest), so even if this option obviously increases sizes of the final file, it's less than that alternative (original patches often have less size than a reversal patch, however, no emulator i know accepts softpatching for isos, so it's moot).

**Comment by cuavas** [comment]
MAME does support reading from a compressed CHD and applying a diff to it live.  This is how arcade games that write settings, scores, etc. to their hard disks are handled.  For example see Killer Instinct - modified data is written out to a diff file leaving the CHD unmodified, and MAME applies the differences to emulated reads.  Is it not possible to use this functionality for soft patching?

**Comment by i30817** [comment]
Also, i've noticed that the chd format keeps a checksum for the original compressed data. It could be pretty useful to also keep a checksum of the *unpatched original compressed data* if the 'hardpatching on creation' and 'upgrade hardpatch' features that i'm requesting happens. This is because recognizing the original checksums is useful to get the right metadata if the patch metadata doesn't exist, which is something that is commonly lost (in Retroarch for example).

**Comment by i30817** [comment]
>  Is it not possible to use this functionality for soft patching?

Notice that the suggestion is not exactly softpatching because i've kind of given up on that ever working on emulators. They're terrible at actually implementing it. A hardpatch that the compression tool can seamlessly remove however, doesn't have anything to do with dozens of sloppily coded emulators.

**Comment by i30817** [comment]
It also comes to my mind that on the your use of softpatching is more for 'temporary' runtime things (i actually approve of this, because i use a copyonwrite filesystem for hd images before using Retroarch). Adding a 'hardpatch' system on top for 'permanent' hacks seems to complement this. Or maybe i'm just seeing patterns where there aren't any and two softpatches, one of which you remove for the 'temporary' things would work better for you, even for large isos (though i still think that *other* emulators that want to use chd would just leave the feature unimplemented more often than not, if the history of softpatching emulators in the last decade is any guide. Not even dolphin does it).

**Comment by p1pkin** [comment]
I'm not sure if I correctly understood what you asking for, but I think chdman and chd core already supports it, you may look at it like "automatical patch creation".

here is example scenario:
we have 2 inputs - original.iso and patched iso
lets compress them to CHD using parent/clone system:
chdman createcd -i original.iso -o original.chd
chdman createcd -i patched.iso -op original.chd -o patched.chd
during patched file compression it's content will be compared with original image, and will be compressed only different sectors, so resulting patched.chd will be quite small (if there was not much difference).

if you want to get back your patched image in iso form you have to use:
chdmad extractcd -i patched.chd -ip original.chd -o somepatchedname.iso
same thing supported by CHD-core during real-time decompression as well, but require specific support from emulator (because both clone and parent CHD images have to be opened at once).

**Comment by i30817** [comment]
Doubt that works outside of mame. But i suppose i can try. The reason i prefer methods which do not depend on runtime patching is like i said, that isn't actually supported in the least common denominator implementations. For example, i really really doubt that the latest round of 'implementations' of chd in retroarch psx actually support parent/clones.

**Comment by p1pkin** [comment]
yes, 3rd party emulators not supports this (yet).
however its pretty easy to implement if was used original MAME's chd core code, in such case there need to add just few lines of code.
most pita - in clone chd case emulator have to know and provide to chd core both names of clone and parent.

**Comment by p1pkin** [comment]
well, it is theirs choice or decision.
but, as was said, chd core and chdman already have parent/clone compression features, so it is not MAMEdev's problem.

**Comment by i30817** [comment]
Eh, worth a try. Guess i'm in usability hell still.
