### ISSUE TITLE
Error while compiling with Clang

### ISSUE THREAD

**Issue by BoisterousSleet75** [mamedev/mame#2661]
Hi.

I'm trying compile MESS with my MSYS2 and Clang, but it gave me an error:
`../../../../../src/emu/http.cpp:275:20: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
        m_server->on_get([this, root](auto response, auto request) {
                          ^
In file included from ../../../../../src/emu/http.cpp:12:
../../../../../src/lib/util\server_ws_impl.hpp:496:45: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
                                                send_close(connection, 1002, reason, [this, connection](const std::error_code& /*ec*/) {});
                                                                                      ^
../../../../../src/lib/util\server_ws_impl.hpp:448:9: note: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::read_message' requested here
                                                                read_message(connection, read_buffer, regex_endpoint.second);
                                                                ^
../../../../../src/lib/util\server_ws_impl.hpp:395:6: note: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::write_handshake' requested here
                                        write_handshake(connection, read_buffer);
                                        ^
../../../../../src/lib/util\server_ws_impl.hpp:706:6: Compiling src/emu/ioport.cpp...note
: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::read_handshake' requested here
                                        read_handshake(connection);
                                        ^
../../../../../src/lib/util\server_ws_impl.hpp:589:47: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
                                                send_close(connection, status, reason, [this, connection](const std::error_code& /*ec*/) {});
                                                                                        ^
../../../../../src/lib/util\server_ws_impl.hpp:520:9: note: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::read_message_content' requested here
                                                                read_message_content(connection, read_buffer, length, endpoint, fin_rsv...
                                                                ^
../../../../../src/lib/util\server_ws_impl.hpp:448:9: note: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::read_message' requested here
                                                                read_message(connection, read_buffer, regex_endpoint.second);
                                                                ^
../../../../../src/lib/util\server_ws_impl.hpp:395:6: note: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::write_handshake' requested here
                                        write_handshake(connection, read_buffer);
                                        ^
../../../../../src/lib/util\server_ws_impl.hpp:706:6: note: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::read_handshake' requested here
                                        read_handshake(connection);
                                        ^
In file included from ../../../../../src/emu/http.cpp:13:
../../../../../src/lib/util\server_http_impl.hpp:223:67: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
                        asio::async_write(*response->socket(), response->m_streambuf, [this, response, callback](const std::error_code...
                                                                                       ^
../../../../../src/lib/util\server_http_impl.hpp:399:5: note: in instantiation of member function
      'webpp::ServerBase<asio::basic_stream_socket<asio::ip::tcp> >::send' requested here
                                send(response, [this, response, request, timer](const std::error_code& ec) {
                                ^
../../../../../src/lib/util\server_http_impl.hpp:382:8: note: in instantiation of member function
      'webpp::ServerBase<asio::basic_stream_socket<asio::ip::tcp> >::write_response' requested here
                                                        write_response(socket, request, std::get<1>(it->second));
                                                        ^
../../../../../src/lib/util\server_http_impl.hpp:303:10: note: in instantiation of member function
      'webpp::ServerBase<asio::basic_stream_socket<asio::ip::tcp> >::find_resource' requested here
                                                                        find_resource(socket, request);
                                                                        ^
../../../../../src/lib/util\server_http_impl.hpp:470:6: note: in instantiation of member function
      'webpp::ServerBase<asio::basic_stream_socket<asio::ip::tcp> >::read_request_and_content' requested here
                                        read_request_and_content(socket);
                                        ^
In file included from ../../../../../src/emu/http.cpp:12:
../../../../../src/lib/util\server_ws_impl.hpp:285:29: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
                        connection->strand.post([this, connection, header_stream, message_stream, callback]() {
                                                 ^
../../../../../src/emu/http.cpp:251:16: note: in instantiation of member function
      'webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::send' requested here
                        m_wsserver->send(connection, message_stream, nullptr, opcode | 0x80);
                                    ^
5 errors generated.
make[2]: *** [emu.make:1074: ../../../../mingw-clang/obj/x64/Release/src/emu/http.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Archiving libdasm.a...
make[1]: *** [Makefile:82: emu] Error 2
make: *** [makefile:1027: windows_x64_clang] Error 2`

Is this bug or something else?

Thanks.

**Comment by BoisterousSleet75** [comment]
Alternate: [https://pastebin.com/70PbVZEJ](https://pastebin.com/70PbVZEJ)

**Comment by BoisterousSleet75** [comment]
Forgot add this:
`../../../../../src/frontend/mame/info.cpp:226:37: error: lambda capture 'drivlist' is not used [-Werror,-Wunused-lambda-capture]
        auto const included = [&patterns, &drivlist, &matched, &exact_matches] (char const *const name) -> bool`

**Comment by cuavas** [comment]
It's a warning produced by newer versions of clang than MAME developers are using.  You can add `NOWERROR=1` to your make options or you can submit a pull request to address it.  It will eventually be addressed as MAME developers migrate to newer versions of clang.

**Comment by BoisterousSleet75** [comment]
> It's a warning produced by newer versions of clang than MAME developers are using. You can add NOWERROR=1 to your make options or you can submit a pull request to address it. It will eventually be addressed as MAME developers migrate to newer versions of clang.

I'm not a MAME developer, but thanks for you reply.

**Comment by cuavas** [comment]
The unused lambda capture warnings were addressed in bcb4be3a5d00b3407874d580c962a964f77cbe52, and the problematic throw was replaced with an abort in 20d1c78b615c2e7082b18b46e2de755be31cb0a9, both by @smf-

**Comment by BoisterousSleet75** [comment]
> The unused lambda capture warnings were addressed in bcb4be3, and the problematic throw was replaced with an abort in 20d1c78, both by @smf-

I know.
