### ISSUE TITLE
huc6270 changes cause flickering

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#2694]
Graphics now flickering in paclandp = Pac-Land (United Amusements PC Engine).

Regression appears: https://github.com/mamedev/mame/commit/e38550a3a3caf2c2c44323c68e4e02ba28402629
Reply Angelo, but no answer!

Other arcade drivers using the HuC6270 video:
battlera.cpp
ggconnie.cpp
paranoia.cpp
tourvis.cpp
uapce.cpp

**Comment by Robbbert** [comment]
Already logged as https://mametesters.org/view.php?id=6758
