### ISSUE TITLE
emscripten cant compile

### ISSUE THREAD

**Issue by summerock** [mamedev/mame#2717]
On ubuntu with all necessary tools installed and following the doc at "http://docs.mamedev.org/initialsetup/compilingmame.html" 

when i run

`emmake make SUBTARGET=pacmantest SOURCES=src/mame/drivers/pacman.cpp`

I get this error:

![untitled-1](https://user-images.githubusercontent.com/8827347/31532846-73deaa34-afa4-11e7-99a5-bb2eaeca934c.jpg)

Can anyone help me?

Thanks

**Comment by DopefishJustin** [comment]
I don't get these errors. What is the output of ```emcc --version```?

**Comment by summerock** [comment]
You are correct my emscripten was out of date. Thanks.

I have another question, why the emscripten compiled js for CPS2 doesn't work with emularity? but other like CPS1 does? Am i missing something?

**Comment by DopefishJustin** [comment]
CPS2 works fine for me with ssf2. Note that CPS2 games require qsound.zip as an additional ROM file. (Check the browser console for error messages.)
