### ISSUE TITLE
Compilation fails with FASTDEBUG=1

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#2738]
**Windows**
```
Compiling src/devices/cpu/uml.cpp...
../../../../../src/devices/cpu/uml.cpp: In member function ‘void uml::instruction::validate()’:
../../../../../src/devices/cpu/uml.cpp:777:20: error: unused variable ‘param’ [-Werror=unused-variable]
   const parameter &param = m_param[pnum];
                    ^~~~~
cc1plus: all warnings being treated as errors
optional.make:7234: recipe for target '../../../../mingw-gcc/obj/x64/Debug/src/devices/cpu/uml.o' failed
make[2]: *** [../../../../mingw-gcc/obj/x64/Debug/src/devices/cpu/uml.o] Error 1
Makefile:88: recipe for target 'optional' failed
make[1]: *** [optional] Error 2
makefile:994: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2
```
Without FASTDEBUG=1 the error doesn't happen.
`make DEBUG=1 PTR64=1 OPTIMIZE=3 SUBTARGET=arcade TARGETOS=windows CROSS_BUILD=1`
...
Compiling generated/version.cpp...
Compiling src/mame/mame.cpp...
Building driver list...
Emitting mamevers.rc...
1366 source file(s) found
Compiling resources scripts/resources/windows/mame/mame.rc...
31922 driver(s) found
Compiling generated/mame/arcade/drivlist.cpp...
Linking mamearcade64d.exe...

**Linux**
```
Compiling src/devices/cpu/uml.cpp...
../../../../../src/devices/cpu/uml.cpp: In member function ‘void uml::instruction::validate()’:
../../../../../src/devices/cpu/uml.cpp:777:20: error: unused variable ‘param’ [-Werror=unused-variable]
   const parameter &param = m_param[pnum];
                    ^~~~~
cc1plus: all warnings being treated as errors
optional.make:7234: recipe for target '../../../../linux_gcc/obj/x64/Debug/src/devices/cpu/uml.o' failed
make[2]: *** [../../../../linux_gcc/obj/x64/Debug/src/devices/cpu/uml.o] Error 1
Makefile:88: recipe for target 'optional' failed
make[1]: *** [optional] Error 2
makefile:1243: recipe for target 'linux_x64' failed
make: *** [linux_x64] Error 2
```
`make DEBUG=1 PTR64=1 OPTIMIZE=3 SUBTARGET=arcade`
Compiling generated/version.cpp...
Compiling src/mame/mame.cpp...
Building driver list...
1366 source file(s) found
31922 driver(s) found
Compiling generated/mame/arcade/drivlist.cpp...
Linking mamearcade64d...

Debian 9 "Stretch"
gcc version 6.3.0 20170516 (Debian 6.3.0-18)

**Comment by happppp** [comment]
resolved in https://github.com/mamedev/mame/commit/7a42e11ed3a4b06718bbd173b386c48fc842ce8f
