### ISSUE TITLE
32k CoCo3 cartridges such as Arkanoid do not run under CoCo 3 emulation

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#2746]
Arkanoid does not run on MAME CoCo 3 emulation, but the same rom image runs on a real CoCo 3 if the banks are swapped back and burned into an eprom/flash rom or if you use the actual original cartridge.
The existing format for most 32k rom dumps has the 16k bank at $C000 first, followed by the bank at $8000. I have tried swapping the banks for MAME and that also dis not work. I did not see any support in the code for this type of rom.

*edit* link to arkanoid.ccc.gz removed

**Comment by JoakimLarsson** [comment]
MAME should emulate how the actual original cartridge works. There have been some work recently about  how the banking works, what version of MAME are you using? If you do not build your own binary I think the next release is the first with the new code.

**Comment by happppp** [comment]
Please do not attach copyrighted software on github

**Comment by abcbarryn** [comment]
JoakimLarsson, what "new code" are you referring to? If it enables 32k cartridge support can you link to the commit here? This is different from banked 16k cartridges, by the way, which actually be much larger, 32k cartridges only contain 2 16k banks, and both can be mapped in at the same time, one at $8000, and one at $C000. Initially they start up with only $C000-$FDFF mapped and they start executing at $C000, then the cartridge code sets bit 0 of $FF90 to 1 to enable 32k external roms. The code to do this in the Arkanoid cartridge appears to be at $FC03.

`0000fc00: b7 ff 98 86 7f b7 ff 90`

**Comment by JoakimLarsson** [comment]
It was a month ago and it addressed banking of larger carts, see [this issue](https://github.com/mamedev/mame/issues/2673), if you  you build the latest from our master repo you'll get it, it will be available in the next release, MAME 0191, I am not sure it made into 0190.

**Comment by abcbarryn** [comment]
The Predator and Robocop cartridges use a different banking scheme than Arkanoid. Are you sure it fixed Arkanoid and the other 32k cartridges as well?

**Comment by JoakimLarsson** [comment]
No I am not sure about that

**Comment by DavidHaywood** [comment]
is this just another case where unless you use the software list MAME really can't know what kind of banking scheme to enable without a boatload of 'detection' hacks?

**Comment by JoakimLarsson** [comment]
There is no detection that I am aware of and I have just recently read through the code, the softlist provides the info about the cart type for each game but I can't recall see any variants of the banking schemes being implemented. My project implemented its own cart and banking scheme and didn't do the softlist thing. So chances are that someone has to write the Arkanoid cart banking as as new cart type and put it in the softlist or extend the current one with a feature based variant.

**Comment by abcbarryn** [comment]
There are two schemes for banked cartridges that exist for the Color Computer 3, The one used by commercial 64k and 128k cartridges like Robo Cop and Predator, and the banking scheme used by 32k cartridges such as Arkanoid, Rad Warrior, and Rampage. The 32k scheme isn't really "banking" since the entire 32k ends up mapped at $8000-$FDFF, so all 32k end up mapped in all at once.

**Comment by JoakimLarsson** [comment]
In that case, shouldn't the cart just program the SAM correctly and it would work out of the box? I think someone with deeper knowledge of the SAM and Coco3 than I have should have a look, meanwhile thx for the report.

**Comment by abcbarryn** [comment]
Any updates on this. Last I checked Robo Cop and Predator work, but Arkanoid and GFL Football II do not. Arkanoid and GFL Football II both use the CoCo 3 only register at $FF90 and set the lower two bits to 1, This enables the cartridge port to map 32k of rom from $8000 to $FEFF ($FF00 - $FFFF being I/O space).
Questions:

Are the lower two bits in $FF90 implemented on the CoCo 3?
What format/layout should be used for a 32k rom? Most existing dumps have the 16k region from $C000 to $FEFF first, followed by $8000 to $BFFF.

I have a pretty deep knowledge of the SAM and the GIME on the CoCo 3 and I have a real CoCo 3 running to compare against, but I get lost in the MAME code, although when I can find the relevant code I have submitted some patches myself.

**Comment by milliluk** [comment]
@abcbarryn check out https://github.com/mamedev/mame/blob/4263a71e64377db11392c458b580c5ae83556bc7/src/mame/video/gime.cpp#L779 and https://github.com/mamedev/mame/blob/4263a71e64377db11392c458b580c5ae83556bc7/src/mame/video/gime.cpp#L504

**Comment by abcbarryn** [comment]
I wonder if this has something to do with it…


		// look up the block in the ROM map
		block = rom_map[m_gime_registers[0] & 3][(block & 0x3F) - 0x3C];

		// are we in onboard ROM or cart ROM?
		if (BIT(block, 2) && m_cart_rom != nullptr)
		{
			// perform the look up
			memory = &m_cart_rom[((block & 3) * 0x2000) % m_cart_size];
		}

It looks like it only thinks it’s in cart rom if the block is 0x3E or 0x3F (C000 and E000) and should be checking if cartridge rom is present and enabled by the GIME at block 0x3C and 0x3D (8000 and A000)?

**Comment by tlindner** [comment]
I'll have a pull request to fix this in a day or two.

**Comment by abcbarryn** [comment]
Wonderful. I wish I could have been more help fixing it rather than just finding it. What about the default setting that was causing two screens to appear? I haven’t seen that issue myself yet, but I was reading about it. Maybe after this update I’ll try doing a new Mac binary build and bundle it into an app bundle.

**Comment by tlindner** [comment]
I've opened a new issue (#4047) for the screen problem.

**Comment by cuavas** [comment]
Should be fixed now.
