### ISSUE TITLE
Apple II nib files

### ISSUE THREAD

**Issue by Phanatical** [mamedev/mame#2758]
Does MAME not support these?  When using command line to run the following test, the console window shows the error I'll paste below:

mame64 apple2ep -flop1 "c:/Adventure in Time (USA).nib"

**Fatal error: Device 5.25" single density floppy drive load failed: Unable to identify the image format.**

I have all the bios files required and dsk games run fine. The nib games work in AppleWin emulator so it's not the rom dumps. I could've sworn I read that MESS supported this file type so I'm not sure what the problem is.

**Comment by Phanatical** [comment]
Okay this is strange. If I change "apple2ep" to "apple2gs" then nib files work for some reason. Except this game is part of the Apple II set. AppleWin plays it as a regular Apple II game as well. I guess I don't understand this system well enough.

**Comment by rb6502** [comment]
.nib files work with the older HLE Disk II controller (slot option "diskii").  They don't work with the otherwise-more-accurate next-gen card (slot option "diskiing").  CC @galibert

**Comment by Phanatical** [comment]
Thanks! I'm completely clueless about this kind of stuff, first time even trying Apple II a few days ago. I'm a RocketLauncher user and we've been trying to figure this out, funny how it was a simple slot parameter that fixed it.
