### ISSUE TITLE
Z80SIO not safe with attached RS232 port

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#2759]
MAME can crash if a device sets the initial state of the input lines for a `z80sio_device` at `device_start` time.  The immediate cause is the use of `required_device` members in write line handlers, e.g. this:
```
    DECLARE_WRITE_LINE_MEMBER( rxa_w ) { m_chanA->write_rx(state); }
```

This is not safe because the object finders like `m_chanA` will not be resolved until the `z80_sio_device` is started, but a device with callbacks connected to its write line handlers (e.g. an `rs232_port_device`) may be started before it.  There's no way for a device to check that whatever's on the other side of a delagate has been started (in fact it may not even be a device), and having to do so would cause a lot of cyclic dependencies anyway.

I'm not sure what to do about this - perhaps we really do need to separate the step where object finders are resolved from `device_start`, introducing another step between configuration complete and start.

**Comment by cuavas** [comment]
Should be fixed in d5ac7c11cfda69fb48cb30daa841992ce8f97d47 - there are probably a bunch of workarounds in `device_start` members that can be retired now.

**Comment by ajrhacker** [comment]
Creating `device_resolve_objects` and converting just one device to it isn't an instant fix for the general problem of unresolved objects and callbacks in devices. I've tried to work around it with synchronization in cases where `device_reset` isn't applicable. (MAME's core assumption that devices can be reset practically instantaneously is ludicrously inaccurate, by the way.)

**Comment by cuavas** [comment]
Yeah, sure.  It addresses it for this one device, and for the general case where a write handler calls a member of a `required_device`/`optional_device` or needs to reference a `required_ioport` or `optional_ioport`.  If a write handler needs to reference a callback, `output_finder`, etc. that require manual resolution, then the device should have the `resolve`/`resolve_safe` calls moved to `device_resolve_objects`.  I don't have time to scan all the devices today though.

**Comment by shattered** [comment]
Looks like this is the same as http://mametesters.org/view.php?id=6551 and it can be closed too?
