### ISSUE TITLE
Cannot build on i386

### ISSUE THREAD

**Issue by athornton** [mamedev/mame#2770]
Master as of 1 Nov. 2017.  I've configured a ridiculous amount of swap, which ought to be pretty near the total 64GB that PAE can access, so this is pretty clearly exhaustion of a process's 3GB address space and not system memory.  I don't have any ulimits set that would get in the way.

```
adam@mamecabinet:~$ cd src/mame
adam@mamecabinet:~/src/mame$ free -m
              total        used        free      shared  buff/cache   available
Mem:           2010         161        1598          10         250        1630
Swap:         72036         294       71742
adam@mamecabinet:~/src/mame$ uname -a
Linux mamecabinet 4.9.0-4-686-pae #1 SMP Debian 4.9.51-1 (2017-09-28) i686 GNU/Linux
adam@mamecabinet:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15936
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15936
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
adam@mamecabinet:~/src/mame$ make -k
GCC 6.3.0 detected
Compiling src/mame/drivers/mpu4sw.cpp...
virtual memory exhausted: Cannot allocate memory
barcrest.make:472: recipe for target '../../../../linux_gcc/obj/x32/Release/src/mame/drivers/mpu4sw.o' failed
make[2]: *** [../../../../linux_gcc/obj/x32/Release/src/mame/drivers/mpu4sw.o] Error 1
make[2]: Target 'all' not remade because of errors.
Makefile:124: recipe for target 'barcrest' failed
make[1]: *** [barcrest] Error 2
Compiling src/mame/drivers/bfm_sc4.cpp...
virtual memory exhausted: Cannot allocate memory
bfm.make:421: recipe for target '../../../../linux_gcc/obj/x32/Release/src/mame/drivers/bfm_sc4.o' failed
make[2]: *** [../../../../linux_gcc/obj/x32/Release/src/mame/drivers/bfm_sc4.o] Error 1
Compiling src/mame/drivers/bfm_sc5.cpp...
virtual memory exhausted: Cannot allocate memory
bfm.make:425: recipe for target '../../../../linux_gcc/obj/x32/Release/src/mame/drivers/bfm_sc5.o' failed
make[2]: *** [../../../../linux_gcc/obj/x32/Release/src/mame/drivers/bfm_sc5.o] Error 1
make[2]: Target 'all' not remade because of errors.
Makefile:127: recipe for target 'bfm' failed
make[1]: *** [bfm] Error 2
make[1]: Target 'all' not remade because of errors.
makefile:1248: recipe for target 'linux_x86' failed
make: *** [linux_x86] Error 2
make: Target 'all' not remade because of errors.
```

Fairly typical `top` output:
```
top - 12:59:50 up 14:45,  5 users,  load average: 1.48, 0.70, 0.28
Tasks: 154 total,   2 running, 152 sleeping,   0 stopped,   0 zombie
%Cpu(s): 20.1 us,  7.0 sy,  0.0 ni, 18.8 id, 54.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :  2058536 total,   104560 free,  1930048 used,    23928 buff/cache
KiB Swap: 73765876 total, 72528532 free,  1237344 used.    60920 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
13805 adam      20   0 2802076 1.684g    544 D  41.9 85.8   3:27.39 cc1plus
```

So I'm pretty sure these compilations are hitting the 3GB userspace process limit, and the fundamental problem is that those three particular targets are too large to compile in 3GB.

**Comment by DavidHaywood** [comment]
yeah, I noticed this a couple of days ago when I synced to check out the Hyperstone improvement, some file (not sure which) is taking 5-6GB to compile.

**Comment by DavidHaywood** [comment]
interestingly, while the error you're looking at points at the bfm_sc4/5 files, which are rather large, I only noticed this started happening a few days ago when I synced to check out the hyperstone improvements, with RAM use of 5-6GB when compiling some of the files.

the actual drivers in question haven't actually changed recently tho

**Comment by athornton** [comment]
I crossgraded to amd64 and was, as expected, able to build after configuring more swap space.  It feels like it should not be terribly hard to split large files into smaller chunks for compilation, but I'm new to MAME development and everything looks like a maze of twisty little macros all alike.

I don't know that there's much reason to care about i386 anymore, but I would think 32-bit Raspberry Pi and similar systems are going to continue being a major use case for MAME.  I don't know what per-process address space looks like on 32-bit ARM, but if it is 4GB or less, that's a concern.

**Comment by galibert** [comment]
It's harder than you think.

And frankly, if you're not cross-compiling on a real computer for your pi,
you're in for a world of pain.  These toys are way too slow for something
that big...

  OG.

**Comment by athornton** [comment]
Well, if the official answer is "32-bit targets must be cross-compiled on a 64-bit machine," or, perhaps, more accurately, "Compilation of MAME requires approximately 6GB of per-process address space, so your compiler must have access to a process address space at least that big," then that needs to make it into the documentation.

If that is the position of the MAME project I'm happy to take a crack at a PR for the compilation instructions.  Is it?  How are project-level decisions like that made?

**Comment by galibert** [comment]
Well, that depends on the compiler, and we don't notice because, heh, 32
bits is severely obsolete on development machines...  So it's not so much a
decision, it's more a case of it happened, and we have better things to do
that doing something about it.  And I'm the only one having split bc*
lately incidentally, to make it a little less insane.

  OG.

**Comment by jfdelnero** [comment]
FYI i have recently compiled Mame on a Raspberry Pi 3 without any "big" issue. You just need to add a 1 or 2 GB of swap since GCC need up to 1.2GB of RAM with some files and you must be very patient since the system is swapping all the time (the whole process take severals hours...).
I also recommend to put the swap on an external hard disk to avoid to wear out the SDCard memory flash ;)
