### ISSUE TITLE
ps2sony.cpp - fake ROM

### ISSUE THREAD

**Issue by f205v** [mamedev/mame#2780]
Hi, the following:
ROM_LOAD( "scph-50004_bios_v9_eur_190.nvm", 0x000000, 0x000400, CRC(efb5af2e) SHA1(60cacbf3d72e1e7834203da608037b1bf83b40e8) )
Is not a real ROM. It is just a fake file full of 0x00.

**Comment by happppp** [comment]
It's gone now.
