### ISSUE TITLE
Timex Sinclair 1000 screen is the wrong color.

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#2781]
The screen on the Timex Sinclair 1000 displays black on cyan and should be black on white. The display circuitry for this machine is identical to the ZX81 and displays in black and white just like that machine does. I know for sure because I own a Timex Sinclair 1000 and have hooked it up to color TVs.

To correct this, in src/mame/drivers/zx.cpp
change
palette.set_pen_color(0, rgb_t(64, 244, 244)); /* cyan */
to
palette.set_pen_color(0, rgb_t::white());

**Comment by happppp** [comment]
OK, it's fixed https://github.com/mamedev/mame/commit/412a9b47830c5091e0ab876d9e03229dae641609

**Comment by abcbarryn** [comment]
Thanks. Can you look at issue 2782?

**Comment by happppp** [comment]
Sure, will do
