### ISSUE TITLE
Many valid ram size options for the Timex Sinclair 1000 are missing.

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#2782]
I noticed that the Timex Sinclair 1000 emulation only has the option of having 2k of ram, even though the actual machine can use all the same ram expansion options as the ZX81, 16K, 32K, and 48K. I also suggest adding the option to emulate a unit with only a 1K chip installed, since although this is not the default it is possible with the actual machine as well.

To fix this add this code below to the ram configuration section for the Timex Sinclair 1000 in src/mame/drivers/zx.cpp right below the line that reads MCFG_RAM_DEFAULT_SIZE("2K")

MCFG_RAM_EXTRA_OPTIONS("1K,16K,32K,48K")

**Comment by happppp** [comment]
Added in https://github.com/mamedev/mame/commit/8e13c4a31aedceef1c0f9273d6624461c7e6cbaf

**Comment by abcbarryn** [comment]
Thanks. :)
