### ISSUE TITLE
apple2c3/apple2c4/apple2cp:  Apple //c expansion RAM I/O space ($C0C0-$C0CF) should have floating bus when RAM card is not present.

### ISSUE THREAD

**Issue by mgcaret** [mamedev/mame#2787]
On the memory-expandable Apple //c emulations in MAME, when no additional memory is specified, the values in $C0C0-$C0CF are fixed at $FF.  This triggers a firmware bug that causes the machine to hang when the firmware attempts to determine the size of the memory card.

When the card is not present, $C0C0-$C0CF should read floating bus.

**Comment by rb6502** [comment]
Fixed by https://github.com/mamedev/mame/commit/bdcb98307822e79c242782ee67bef966bf4c25de
