### ISSUE TITLE
Cross-Compilation

### ISSUE THREAD

**Issue by jfdelnero** [mamedev/mame#2811]
Hi,

I am trying/planning to setup a cross-compilation of Mame for a Linux ARM64 machine on a Linux PC.
I have already build all the cross compiler and tools (GCC 6.4.0).

Can Mame already be cross-compiled on such environment ?

If not, Is there something planned ? Do you think that some "simples" Makefiles modifications are enough, or is there something i am missing that need more in-depth work ?

For example I know that some build tools are compiled for the host machine, but is there possible endianness/word size/padding issues between the host tools and the target machine binary ?

Let me known if you think that this something doable without rewriting the whole build process/makefiles.

Best Regards,
Jean-François DEL NERO

**Comment by mmicko** [comment]
Hi,

Well MAME build system is quite ready for such a thing. Please take a look at steamlink target that one is cross-compile only, so that works. 
Thing is you would need to add new target for cross compilation where you would specify compiler, and different location of libraries.
Thing is that you would need to specify such target since auto detection would always find host system and setup according to that.

Think it could be quite generic. If you can mail me instructions for building your specific cross compile tools and other details I could need, I can work on such extension for cross-compilation.

Think you already have my email, but anyway it is public on my github page as well.

Thanks,
Miodrag

**Comment by jfdelnero** [comment]
The cross compiler i am using is "just" a GCC 6.4.0 cross compiler on a Linux PC (aarch64-linux-gcc). I can send you my sh script to build all this environment (aarch64 gcc, glibc and others libs, kernel, busybox...) but before annoying you with this, i will have a look to the steamlink target.

**Comment by mmicko** [comment]
Sure, it is all about setting proper parameters for compiling for specific target. Specially for compiler. That you can even set from outside by using CC,CCX, LD parameters of makefile, but then you would also need force it to generate for aarch64, for start using it as separate target is easier.

Feel free to drop me info, so I can help on this.

**Comment by jfdelnero** [comment]
Unless i have missed something, this appears to me a little more complex since some sources are compiled for the build time (genie, some 68k stuff...), so the host compiler or the cross compiler must be used for each file/subproject depending if it is used/needed during the build time. I don't know if these "two worlds" are currently separated into the makefiles.

**Comment by mmicko** [comment]
Right. Makefile needs to compile genie with host tools (that it does by
default), so yeah steamlink target is more appropriate for you to start
looking at.

Micko

**Comment by jfdelnero** [comment]
Just to follow up, i have successfully cross compiled Mame using my custom gcc aarch64. i have just modified the steamlink target settings/lua.

**Comment by mmicko** [comment]
Great. Glad that you have made it.

**Comment by tracewong** [comment]
@jfdelnero can you share the compiler command to me？

**Comment by jfdelnero** [comment]
Just :

make steamlink REGENIE=1 SOURCES=src/mame/drivers/squale.cpp

(change squale.cpp by any machine you want...)

But you need to modify the toolchain.lua scripts to use the right cross-compiler.

In mame-master\3rdparty\bx\scripts\toolchain.lua :

`		elseif "linux-steamlink" == _OPTIONS["gcc"] then
			if not os.getenv("MARVELL_SDK_PATH") then
				print("Set MARVELL_SDK_PATH enviroment variable.")
			end

			premake.gcc.cc  = "$(MARVELL_SDK_PATH)/toolchain/bin/armv7a-cros-linux-gnueabi-gcc"
			premake.gcc.cxx = "$(MARVELL_SDK_PATH)/toolchain/bin/armv7a-cros-linux-gnueabi-g++"
			premake.gcc.ar  = "$(MARVELL_SDK_PATH)/toolchain/bin/armv7a-cros-linux-gnueabi-ar"
			location (path.join(_buildDir, "projects", _ACTION .. "-linux-steamlink"))
`
And change the compilation options if needed in the other linux-steamlink section in this file.

Same principle in mame-master\scripts\toolchain.lua :

`		if "steamlink" == _OPTIONS["gcc"] then
			if not os.getenv("MARVELL_SDK_PATH") then
				print("Set MARVELL_SDK_PATH envrionment variable.")
			end
			premake.gcc.cc  = "$(MARVELL_SDK_PATH)/toolchain/bin/armv7a-cros-linux-gnueabi-gcc"
			premake.gcc.cxx = "$(MARVELL_SDK_PATH)/toolchain/bin/armv7a-cros-linux-gnueabi-g++"
			premake.gcc.ar  = "$(MARVELL_SDK_PATH)/toolchain/bin/armv7a-cros-linux-gnueabi-ar"
			location (_buildDir .. "projects/" .. _subDir .. "/".. _ACTION .. "-steamlink")
		end
`
You may also need to change the graphical stack setting in genie.lua too : 

`configuration { "steamlink" }
	links {
		"dl",
		"EGL",
		"GLESv2",
		"SDL2",
	}
	defines {
		"EGL_API_FB",
	}` 

This depend on the target architecture...
