### ISSUE TITLE
Compilation is broken after Imagetek i4100 / i4220 / i4300 patch

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#2826]
https://github.com/mamedev/mame/commit/56828c244673af85150a934696fa07a8d005fc07

`../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0xedbf): undefined reference to `imagetek_i4100_device::static_set_gfxdecode_tag(device_t&, char const*)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0xf38c): undefined reference to `imagetek_i4100_device::static_set_tmap_xoffsets(device_t&, int, int, int)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0xfa95): undefined reference to `imagetek_i4100_device::static_set_gfxdecode_tag(device_t&, char const*)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0x10f1f): undefined reference to `imagetek_i4100_device::static_set_gfxdecode_tag(device_t&, char const*)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0x11bb1): undefined reference to `imagetek_i4100_device::static_set_tmap_xoffsets(device_t&, int, int, int)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0x11edd): undefined reference to `imagetek_i4100_device::static_set_tmap_xoffsets(device_t&, int, int, int)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0x130dc): undefined reference to `imagetek_i4100_device::static_set_tmap_xoffsets(device_t&, int, int, int)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text.unlikely+0x13328): undefined reference to `imagetek_i4100_device::static_set_gfxdecode_tag(device_t&, char const*)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr._ZTV13device_finderI21imagetek_i4300_deviceLb0EE[.refptr._ZTV13device_finderI21imagetek_i4300_deviceLb0EE]+0x0): undefined reference to `vtable for device_finder<imagetek_i4300_device, false>'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr._ZTV13device_finderI21imagetek_i4220_deviceLb0EE[.refptr._ZTV13device_finderI21imagetek_i4220_deviceLb0EE]+0x0): undefined reference to `vtable for device_finder<imagetek_i4220_device, false>'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr._ZTV13device_finderI21imagetek_i4100_deviceLb0EE[.refptr._ZTV13device_finderI21imagetek_i4100_deviceLb0EE]+0x0): undefined reference to `vtable for device_finder<imagetek_i4100_device, false>'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr.I4300[.refptr.I4300]+0x0): undefined reference to `I4300'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr._ZN21imagetek_i4100_device13screen_updateER13screen_deviceR12bitmap_ind16RK9rectangle[.refptr._ZN21imagetek_i4100_device13screen_updateER13screen_deviceR12bitmap_ind16RK9rectangle]+0x0): undefined reference to `imagetek_i4100_device::screen_update(screen_device&, bitmap_ind16&, rectangle const&)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr.I4100[.refptr.I4100]+0x0): undefined reference to `I4100'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr.I4220[.refptr.I4220]+0x0): undefined reference to `I4220'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr._ZN21imagetek_i4220_device6v2_mapER11address_map[.refptr._ZN21imagetek_i4220_device6v2_mapER11address_map]+0x0): undefined reference to `imagetek_i4220_device::v2_map(address_map&)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr._ZN21imagetek_i4100_device3mapER11address_map[.refptr._ZN21imagetek_i4100_device3mapER11address_map]+0x0): undefined reference to `imagetek_i4100_device::map(address_map&)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.rdata$.refptr._ZN21imagetek_i4300_device6v3_mapER11address_map[.refptr._ZN21imagetek_i4300_device6v3_mapER11address_map]+0x0): undefined reference to `imagetek_i4300_device::v3_map(address_map&)'
../../../../mingw-gcc/bin/x64/Debug/mame_mame/libmetro.a(metro.o):metro.cpp:(.text+0x32f): undefined reference to `imagetek_i4100_device::screen_update(screen_device&, bitmap_ind16&, rectangle const&)'
collect2: error: ld returned 1 exit status
`

**Comment by startaq** [comment]
This should be fixed now.
