### ISSUE TITLE
compile error on clear linux

### ISSUE THREAD

**Issue by tuxutku** [mamedev/mame#2848]
qt 5.9.3 installed to /usr/local/Qt-5.9.3/
at the main directory i have runned:
export PKG_CONFIG_PATH=/usr/local/Qt-5.9.3/lib/pkgconfig
export PATH=/usr/lib64/ccache/bin:/usr/local/bin:/usr/bin:/usr/local/Qt-5.9.3/bin
make -j2

output of the terminal:
[terminal_output.txt](https://github.com/mamedev/mame/files/1503885/terminal_output.txt)

Downloaded mame from this link:
https://github.com/mamedev/mame/releases/download/mame0191/mame0191s.zip

uname -a:
Linux clr-449e9b2a44f8458bb4885604dc172a1c 4.13.16-460.native #2 SMP Fri Nov 24 16:27:00 UTC 2017 x86_64 GNU/Linux

<pre>
GCC 7.2.1 detected
Compiling 3rdparty/libflac/src/libFLAC/bitmath.c...
Compiling 3rdparty/libflac/src/libFLAC/bitreader.c...
In file included from /usr/include/inttypes.h:25:0,
                 from ../../../../../3rdparty/libflac/include/FLAC/ordinals.h:36,
                 from ../../../../../3rdparty/libflac/src/libFLAC/include/private/bitmath.h:35,
                 from ../../../../../3rdparty/libflac/src/libFLAC/bitmath.c:36:
/usr/include/features.h:376:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [flac.make:362: ../../../../linux_gcc/obj/x64/Release/3rdparty/libflac/src/libFLAC/bitmath.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Compiling src/mame/drivers/fccpu20.cpp...
In file included from /usr/include/bits/libc-header-start.h:33:0,
                 from /usr/include/stdlib.h:25,
                 from ../../../../../3rdparty/libflac/src/libFLAC/bitreader.c:36:
/usr/include/features.h:376:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [flac.make:366: ../../../../linux_gcc/obj/x64/Release/3rdparty/libflac/src/libFLAC/bitreader.o] Error 1
make[1]: *** [Makefile:46: flac] Error 2
make[1]: *** Waiting for unfinished jobs....
Compiling src/mame/drivers/fccpu30.cpp...
Compiling src/mame/drivers/force68k.cpp...
Compiling src/mame/drivers/miniforce.cpp...
Archiving libforce.a...
make: *** [makefile:1244: linux_x64] Error 2
</pre>

**Comment by tuxutku** [comment]
i can't seem to compile libflac, i can compile libflac 1.3.2 source code but not libflac 1.2.1

**Comment by katananja** [comment]
I have no problem here with Debian.
Did you install de "dev" files?

Have you read this?
http://docs.mamedev.org/initialsetup/compilingmame.html

**Comment by tuxutku** [comment]
there is no package manager on my system.
installed qt from source  because intel didn't provide  compatible qt version for my processor.
all depencies seem to me complete and its like a compile error.

my processor does not have aes. thats the why its not compatible with the qt that intel provide

**Comment by tuxutku** [comment]
if i install libflac 1.3.2 , can i pass the libflac that mame builds?

as i think intel uses more aggressive compiler options,

**Comment by tuxutku** [comment]
with:
export CFLAGS=''
then when it compiled the flac i interrupted then set CFLAGS to its default value:
[CFLAGS](https://github.com/mamedev/mame/files/1511048/myflags.txt)
then it stuck at Compiling src/frontend/mame/luaengine.cpp... for 2two hours wtih filling 4 gb of ram (only 500mb was used at the beginning and 3gb of swap was free)
i could compile flac but i don't know if its good to do

**Comment by tuxutku** [comment]
I have  referenced this issue to https://github.com/mamedev/mame/issues/2866, after days without response i am closing thios issue

**Comment by cuavas** [comment]
> my processor does not have aes. thats the why its not compatible with the qt that intel provide

You really shouldn't be using Clear Linux on anything but a very recent Intel processor/motherboard.  It's heavily tuned to perform on Intel's latest microarchitecture, and will likely perform poorly on anything else.
