### ISSUE TITLE
Reset feature in Heathkit ET-3400?

### ISSUE THREAD

**Issue by mjklopfer** [mamedev/mame#2860]
For the Heathkit ET-3400 Trainer driver, has the reset functionality been enabled?  

Using the board, you must use the reset regularly after using the "Auto" feature to update the memory locations.  A "." is mapped to that key position, but it looks not to be functional (bottom of the second column of keys).  Is there a suggested workaround or is another method used to reset the processor while leaving the memory intact?

![image](https://user-images.githubusercontent.com/25714274/33276375-43265292-d34a-11e7-9a33-1f4fa706ac0e.png)

https://github.com/mamedev/mame/blob/master/src/mame/drivers/et3400.cpp @Robbbert

**Comment by ajrhacker** [comment]
I've emulated this reset button in 26017a2c253dc2aabd34706e91cc4b17359b940c.

**Comment by mjklopfer** [comment]
Looks great, thank you!  Teaching students with this emulation.  great work!

--
Michael J. Klopfer, PhD
Technical Director
CalPlug - California Plug Load Research Center
California Institute for Telecommunications and Information Technology
(Calit2)
University of California, Irvine

Office Ph: +1-949-824-7866 <(949)%20824-7866>
Mobile Ph/SMS: +1-310-502-1971 <(310)%20502-1971>
http://www.calit2.uci.edu/
http://www.calplug.org/
----------------------------------------------------------
CONFIDENTIALITY NOTICE This e-mail, and any attachments thereto, is
intended only for use by the addressee(s) named herein and may contain
confidential information.  Please delete this message if this is not you.
