### ISSUE TITLE
Super street fighter II turbo and clones of cammy ending issue bug

### ISSUE THREAD

**Issue by jmodlin210** [mamedev/mame#2863]
There is a ending quote bug for Cammy's Ending of missing says is true, after wait! if what he and it is suppose to be Wait! if what he says is true for super street fighter ii turbo and clones.
![0003](https://user-images.githubusercontent.com/22105571/33304953-c3400e48-d3d9-11e7-8db0-47f9d660c46c.png)

**Comment by Osso13** [comment]
Curiously the same image is logged at MameTesters, but for the gfx glitch on top of the screen. Maybe you could add a note to the bug: MAME Testers - 01495: ssf2tu: Graphics garbage appears on the top of the screen during Cammy's ending.

  
|  
|   |  
MAME Testers - 01495: ssf2tu: Graphics garbage appears on the top of the screen during Cammy's ending.
   |  |

  |

**Comment by jmodlin210** [comment]
Tried to add a note at mametrsters and wouldn't let me. Can you please add a note for a ending quote bug for Cammy's Ending of missing says is true, after wait! if what he and it is suppose to be Wait! if what he says is true for super street fighter ii turbo and clones at http://mametesters.org/view.php?id=1495

**Comment by Robbbert** [comment]
I've added the note for you.

**Comment by jmodlin210** [comment]
Super Street Fighter II Turbo and clones of Cammy ending quote bug needs to be fixed in the next MAME update of IF WHAT HE SAYS IS TRUE. Can you please fix the Cammy ending quote bug of "IF WHAT HE SAYS IS TRUE for Super Street Fighter II Turbo and clones so that I can enjoy seeing the full ending quote for Cammy's ending for Super Street Fighter II Turbo and clones?

http://mametesters.org/view.php?id=1495

**Comment by jmodlin210** [comment]
http://mametesters.org/view.php?id=1495 to edit the summary of ssf2t and clones of Graphics garbage appears on the top of the screen during Cammy's ending and text should say "IF WHAT HE SAYS IS TRUE" for cammy's ending.

**Comment by Robbbert** [comment]
Since you won't shut up, and you've been banned elsewhere, I'm closing this.
