### ISSUE TITLE
compile error on clear linux (memcpy error with decent gcc)

### ISSUE THREAD

**Issue by tuxutku** [mamedev/mame#2866]
This is another error and not duplicate of: https://github.com/mamedev/mame/issues/2848
Things changed after that error:
I set the both CFLAGS and CXXFLAGS to: -O2 -pipe -march=native
Set PATH variable to: '/usr/lib64/ccache/bin:/usr/local/bin:/usr/bin:/usr/local/Qt-5.9.3/bin' for include moc binary
Set PKG_CONFIG_PATH to: '/usr/local/Qt-5.9.3/lib/pkgconfig' for include *.pc files required
What am i doing wrong?

Here is the terminal output:
<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mame $ make
GCC 7.2.1 detected
Compiling 3rdparty/sqlite3/sqlite3.c...
In function ‘vdbePmaReadBlob.part.314’,
    inlined from ‘vdbePmaReadBlob’,
    inlined from ‘vdbePmaReadVarint.part.315’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85435:12,
    inlined from ‘vdbePmaReadVarint’,
    inlined from ‘vdbePmaReaderInit.constprop’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85583:8,
    inlined from ‘vdbeSorterMergeTreeBuild’ at ../../../../../3rdparty/sqlite3/sqlite3.c:87159:8,
    inlined from ‘vdbeSorterSetupMerge’ at ../../../../../3rdparty/sqlite3/sqlite3.c:87347:6,
    inlined from ‘sqlite3VdbeSorterRewind.isra.339’ at ../../../../../3rdparty/sqlite3/sqlite3.c:87453:8,
    inlined from ‘sqlite3VdbeExec’ at ../../../../../3rdparty/sqlite3/sqlite3.c:82191:8:
../../../../../3rdparty/sqlite3/sqlite3.c:85392:5: error: ‘memcpy’: specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
     memcpy(p->aAlloc, &p->aBuffer[iBuf], nAvail);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [sqlite3.make:278: ../../../../linux_gcc/obj/x64/Release/3rdparty/sqlite3/sqlite3.o] Error 1
make[1]: *** [Makefile:58: sqlite3] Error 2
make: *** [makefile:1244: linux_x64] Error 2
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mame $ echo $CC
gcc
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mame $ echo $CFLAGS
-O2 -pipe -march=native
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mame $ echo $CXXFLAGS
-O2 -pipe -march=native
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mame $ echo $PATH
/usr/lib64/ccache/bin:/usr/local/bin:/usr/bin:/usr/local/Qt-5.9.3/bin
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mame $ echo $PKG_CONFIG_PATH
/usr/local/Qt-5.9.3/lib/pkgconfig
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mame $ uname -a
Linux clr-449e9b2a44f8458bb4885604dc172a1c 4.13.16-460.native #2 SMP Fri Nov 24 16:27:00 UTC 2017 x86_64 GNU/Linux
</pre>

**Comment by tuxutku** [comment]
compiled succesfully with these commands:
export CFLAGS="-O2 -pipe -march=native -Wno-error=stringop-overflow"
export CXXFLAGS="${CFLAGS}"
export PKG_CONFIG_PATH=/usr/local/Qt-5.9.3/lib/pkgconfig
export PATH=/usr/lib64/ccache/bin:/usr/local/bin:/usr/bin:/usr/local/Qt-5.9.3/bin
make -j3

it turns out that i have compiled qt5 with aes enabled (it was some how set), but my processor does not support aes, so i will try to compile it with:
export CFLAGS="-O2 -pipe -march=native -Wno-error=stringop-overflow -mno-aes"
export CXXFLAGS="${CFLAGS}"
and see if i can succeed finaly

**Comment by startaq** [comment]
Closing this since the described problems are specific to your enviroment and nothing we can fix.
