### ISSUE TITLE
Need help from a admin to deal with a prejudice person inside mame dev

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#2868]
MAME team ask for help in a post back in Aug 22,  2017.
http://mamedev.org/?p=446

We, the Brazilian Portuguese translator are having issues with @cuavas that doesn't push our patch through since October, he doesn't return contact, people are asking him to push the patch through but he does a blind eye to it.

I had a discussion back and forth with him trying to explain that Brazilian Portuguese NEED A CONTEXT, it sounds wrong and broken TO OUR LANGUAGE if we translate the way @cuavas want it.

For example, MAME uses "OK" to define if the ROM works or not, if good or bad. "OK" in Brazilian Portuguese it means "MEDIOCRE", I believe it has the same meaning in English also. Each and every country has a correct the right to use the correct meaning for "OK".

Japanese use "正常" (SEIJO) witch are the correct meaning for "OK" to then, witch literally means "normal", why can't we do the same for our Language? WHY, @cuavas has to disrespect our Language to force his own??

As the Japanese and other Languages we have our way to say if something is GOOD (BOM or BOA) or BAD (RUIM), even if this make "terminology inconsistent" as @cuavas put it, inconsistent to him but CORRECT to us.

This is one of the MANY issues @cuavas is picking up with, he had pushed other translations through and our is two releases behind and to this day @cuavas has this prejudice against us, why?

The nature of open source is collaboration, if some one doesn't agree with the last translation (https://github.com/mamedev/mame/pull/2705) some one else if free to come and fix it and we move on with our lives. But please, doesn't disrespect a peoples work, that did a translation top top to bottom ALL DAY, FOR FREE!!!

I'm sorry to post this out here but since @cuavas doesn't return any contact, I need a help from some high level admin to sort this out.

Thank you.

**Comment by rb6502** [comment]
@cuavas is the project coordinator, and he speaks about 8 languages, so I tend to defer to him on this stuff.  I have put through your pull request on the basis that @felipesanches whom I trust has also reviewed it and made some corrections.

**Comment by felipesanches** [comment]
Thanks, @rb6502 !

**Comment by katananja** [comment]
I'll update the translation to fill @felipesanches requests and hope that we ALL can work together as a team.

Thank you!

**Comment by felipesanches** [comment]
@Ashura-X,

 @katananja told me that he is trying to contact you.

**Comment by Ashura-X** [comment]
Sure my mail ashurax@gmail.com

Em qui, 30 de nov de 2017 às 11:09, Felipe Corrêa da Silva Sanches <
notifications@github.com> escreveu:
