### ISSUE TITLE
TMNT2 bug for gaps in explosion sprites

### ISSUE THREAD

**Issue by jmodlin210** [mamedev/mame#2870]
http://mametesters.org/view.php?id=6017 that of tmnt2 bug for gaps in explosion sprites still not fixed and it is suppose to be normal explosion sprites for enemies to be fixed in the next update.

**Comment by cuavas** [comment]
The bug is recorded at MAME Testers, so we know about it.  Creating a duplicate here is pointless spam.  If you continue to do this, you will be banned from the project.
