### ISSUE TITLE
gticlub, hornet: Sound is broken 

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#2882]
I Play the GTI Club, Operation Thunder Hurricane, Solar Assault, Hang Pilot, Gradius IV, NBA Play By Play has Sound Broken.

Caused by https://github.com/mamedev/mame/commit/0fe9e1defe81bcc45e249daa3a3197213513d2e3

**Comment by Tafoid** [comment]
Yes, there appears to be an issue with audio in regression, but please do not keep repeating and/or creating new ISSUE numbers when you've already commented on the offending commit!
