### ISSUE TITLE
mGBA memory tests fail due to bugs in LDMIA or STMIA

### ISSUE THREAD

**Issue by MoochMcGee** [mamedev/mame#2888]
So far only 780/1552 of these tests pass, and most of the fails appear to be due to ARM7 CPU bugs or GBA driver bugs.

The test binaries can be found here: https://forums.mgba.io/showthread.php?tid=18

The tests focused on in this issue are related to swi 0xB, which is basically either a memcpy or a memset, using LDMIA/STMIA on unaligned addresses. The fact that the result is wrong points to a bug in those instructions. This is according to GBATEK; the relevant text can be found here: http://problemkaputt.de/gbatek.htm#biosmemorycopy

A working implementation can be found here: https://gitlab.com/higan/higan/blob/master/higan/processor/arm7tdmi/instructions-arm.cpp#L181

**Comment by rb6502** [comment]
Thanks, this is great.  I'll fix it ASAP.

**Comment by rb6502** [comment]
Passes have been increased to 1136.  LDMIA/STMIA are fixed according to endrift's instructions; the remaining fails are a collection of other problems so I'm closing this specific bug.
