### ISSUE TITLE
fm-towns load failed

### ISSUE THREAD

**Issue by zjwkof** [mamedev/mame#2894]
Fatal error: Device 3.5” high density floppy drive load failed:
Unable to identify the image format

**Comment by rb6502** [comment]
This report is literally useless without at least a pointer to the disk image you're attempting to load.

**Comment by zjwkof** [comment]
Origin: Neo Kobe Collection
		<rom name="Samurai Spirits.bin" size="524020896" crc="f48ab264" sha1="bbb99a5209d5513a3dbee8f9a6730545aa7718fd"/>
		<rom name="Samurai Spirits.cue" size="1414" crc="68d636f8" sha1="a92650884363dd1b6c8252ac0ae9ed8ba3a1bc11"/>
		-->
		<description>Samurai Spirits</description>
		<year>1995</year>
		<publisher>JHV</publisher>
		<info name="release" value="199509xx" />
		<part name="flop1" interface="floppy_3_5">
			<feature name="part_id" value="Boot Disk" />
			<dataarea name="flop" size="1281280">
				<rom name="samurai spirits (boot disk).bin" size="1281280" crc="2f1793ac" sha1="bd0f7f5f3fc4b0bd58d04812449cae853b58b5a8" offset="000000" />
			</dataarea>

**Comment by mahlemiut** [comment]
This disk image seems slightly larger than normal, I have one that certainly used to work, I'll try to retrieve that and see if it works.

**Comment by mahlemiut** [comment]
Ok, I think I see what's happened here,  I saw in my old collection that the CD bin was exactly that size, it's likely that the wrong file was used.  I have a working boot disk, so I'll update the list, although probably not until tomorrow.

**Comment by mahlemiut** [comment]
I've updated the softlist to use the floppy that I have working.  Upon looking at the content of the old file, it looks like it just adds some empty sectors (all 0xe5).  Just truncating the empty sectors should work, but no guarantees on that.
