### ISSUE TITLE
Crash compile MAME on ARMV7 processor OS LiNUX 3.10.18

### ISSUE THREAD

**Issue by aperfeito** [mamedev/mame#2925]
SYSTEM:

Linux alarm 3.10.18-24-ARCH #1 SMP Wed Nov 29 16:27:21 PST 2017 armv7l GNU/Linux

COMMAND:
make TARGET=mame REGENIE=1 TOOLS=1 SUBTARGET=mame -j5

GCC:

[aperfeito@alarm mame]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/armv7l-unknown-linux-gnueabihf/7.2.1/lto-wrapper
Target: armv7l-unknown-linux-gnueabihf
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --host=armv7l-unknown-linux-gnueabihf --build=armv7l-unknown-linux-gnueabihf --with-arch=armv7-a --with-float=hard --with-fpu=vfpv3-d16
Thread model: posix
gcc version 7.2.1 20171128 (GCC) 

RESULTS:

**Archiving libchrysler.a...
Compiling src/lib/formats/thom_cas.cpp...
Linking chdman...
/usr/bin/ld: ../../../../../scripts/src/libutils.a(strformat.o): relocation R_ARM_MOVW_ABS_NC against `_ZNKSt5ctypeIcE8do_widenEc' can not be used when making a shared object; recompile with -fPIC
../../../../../scripts/src/libutils.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [chdman.make:250: ../../../../../chdman] Error 1
make[1]: *** [Makefile:1036: chdman] Error 2
make[1]: *** Waiting for unfinished jobs....**

**Comment by aperfeito** [comment]
Update : 12/12/2017 -- With git pull and :
        Same Problems !!
Compiling src/mame/video/bfm_adr2.cpp...
Linking chdman...
/usr/bin/ld: ../../../../../scripts/src/libutils.a(strformat.o): relocation R_ARM_MOVW_ABS_NC against `_ZNKSt5ctypeIcE8do_widenEc' can not be used when making a shared object; recompile with -fPIC
../../../../../scripts/src/libutils.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [chdman.make:250: ../../../../../chdman] Error 1
make[1]: *** [Makefile:1036: chdman] Error 2
make[1]: *** Waiting for unfinished jobs....
Compiling src/mame/video/bfm_dm01.cpp...
Compiling src/lib/formats/pasti_dsk.cpp...
Compiling src/lib/formats/ti99_dsk.cpp...
Compiling src/lib/formats/tzx_cas.cpp...
Compiling src/lib/formats/upd765_dsk.cpp...
Compiling src/lib/formats/vdk_dsk.cpp...
Compiling src/lib/formats/victor9k_dsk.cpp...
Compiling src/lib/formats/wd177x_dsk.cpp...
Archiving libformats.a...
Archiving libbfm.a...
Archiving libbarcrest.a...
make: *** [makefile:1254: linux] Error 2
[aperfeito@alarm mame]$

**Comment by rb6502** [comment]
Sorry, but that's a compiler bug, not something we can address.
