### ISSUE TITLE
saturn: kof95 cartridge load fail

### ISSUE THREAD

**Issue by zjwkof** [mamedev/mame#2935]
mess 0.148u1  load ok

**Comment by firewave** [comment]
I tried the official 0.148 and 0.149 MESS binaries as well as 0.193 and none of them seem to load the cartridge. I am using
```
mame64 saturn -cart kof95
```
But even if this were a regression - all saturn.cpp sets are marked MACHINE_NOT_WORKING and the kof95 cart is also flagged as unsupported. So this should be closed.
