### ISSUE TITLE
Plugin needed to handle lto object if LTO=1

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#2942]
gcc version 6.3.0 20170516, Debian 9.
49b83056b1..cc03217ca0

genie.lua has some descriptions about it but it doesn't seem to work.
Looking else where maybe it's the case to use ggc-ar instead of ar?
https://github.com/monero-project/monero/pull/1065#issuecomment-247148712

```
...
ar: pcml_qdisk.o: plugin needed to handle lto object
ar: qubide.o: plugin needed to handle lto object
ar: rom.o: plugin needed to handle lto object
...
```

**Comment by Robbbert** [comment]
Unsupported feature.
