### ISSUE TITLE
Attempt to access non-existent slot option

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#2945]
mame0192-462-gcc03217ca0-dirty
In relation with http://mametesters.org/view.php?id=6675

mame psu -> TAB -> BIOS Selection -> psxcd (try selecting left or right on that entry)

Now it doesn't crash anymore and return.
```
Assertion failed!

Program: D:\Mame\mame64d.exe
File: ../../../../../src/emu/emuopts.cpp, Line 1021

Expression: opt && "Attempt to access non-existent slot option"

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by Robbbert** [comment]
Note added to the mametesters bug report.

Please add anything else to that report, thanks.
