### ISSUE TITLE
Many games not working despite entries present in hiscore.dat

### ISSUE THREAD

**Issue by stargoonman** [mamedev/mame#2949]
High scores are not being saved on many games that are present in hiscore.dat.

Using mame 0.192, latest rom set and official hiscore.dat and the lua plugin.

Some games work, but some (still in hiscore.dat) don't.

Examples not working: tengai, mslug2t

**Comment by cracyc** [comment]
Tengai at least works for me.  If you run mame from the command line with -verbose it'll show you when the scores are loaded and saved.

**Comment by stargoonman** [comment]
Sorry, but for some reason I had to reset the machine for it to work. -verbose helped me track down the caue. Thank you @cracyc.
