### ISSUE TITLE
San Francisco Rush 2049 Problem

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#2951]
I play the San Francisco Rush 2049 has a freeze and resert system in attract mode and start the race, see the picture, can you help?
https://i.imgur.com/fUbXEl1.png
https://i.imgur.com/7s1Ovjm.png

**Comment by DavidHaywood** [comment]
MACHINE_NOT_WORKING

**Comment by p1pkin** [comment]
@sjy96525 no need to open issues for machines with MACHINE_NOT_WORKING status
