### ISSUE TITLE
One Must Fall 2097 in ct486 latches the VGA start address at the wrong time

### ISSUE THREAD

**Issue by MoochMcGee** [mamedev/mame#2954]
Problematic code is in src/devices/video/pc_vga.cpp, and m_vblank_timer seems to have the wrong time given to it.

The VGA start address latches a value of 0xA4, when it seemingly should latch 0.

**Comment by MooglyGuy** [comment]
Discussing on IRC.

**Comment by MooglyGuy** [comment]
A suggestion which I mentioned on IRC: There are three calls to m_vblank_timer->adjust in pc_vga.cpp, have you tried to narrow down which one is feeding in the wrong time?

Ultimately there would be way more problems in MAME if the timer system were inherently broken, so something must be setting up the timer to fire at the wrong time. So put some debug prints in and around the areas of code that set up the incorrect timer, and you might end up finding some enlightening results. :-)
