### ISSUE TITLE
About OSD UI  issue.

### ISSUE THREAD

**Issue by JLSliuyang** [mamedev/mame#2970]
I downloaded messui it already include mame. In minggw I use command to build it. It's OK. It can show messui. But I want to try to use vs2015 to build this project. It only show like dos mode. Look's like no OSD messui running. I want to know how to use command to build a sln file it can building messui.

**Comment by Robbbert** [comment]
MESSUI is not a part of the MAME project. MESSUI issues should be reported in the MAMEUI project.

However, to save you wasting your time doing that, there's totally no support for VS with MESSUI, and there are no fixes available.
