### ISSUE TITLE
chdman rfe: append and extract a custom header / footer.

### ISSUE THREAD

**Issue by i30817** [mamedev/mame#2973]
I was thinking of the recently closed  #2634. It's fair enough that you don't want to support this considering you already have softpatching (for mame). And yet, i'd much prefer using hardpatching for other emulator support, because other emulators won't ever support mame style softpatching.

Rereading  #2634 it came to my mind that i don't *need* MAME to support this function. It's actually very simple; *except* the part where the reverse patch is kept attached to the file so it doesn't get lost (the optional idea for keeping a checksum of the unpatched iso is also good).

Then i read about

       addmeta -i filename -t  tag  [-ix  index]  [-vt  text]  [-vf  filename]
       [-nocs]
              Add metadata to the chd.

       delmeta -i filename -t tag [-ix index]
              Remove metadata from the chd.

       dumpmeta -i filename [-o filename] [-f] -t tag [-ix index]
              Dump metadata from the chd to standard output or to a file.

on the man page. Can these be used by a external tool to attach large amounts of 'metadata' (ie: a patch and a 'original-checksum(s)' tag??). All of the manipulation of upgrading a patch can be done externally if the reversal patch can just get attached.

Also, what's '-nocs'?

edit: thinking about this, this won't work because there is no guarantee that the extraction of a chd gets back the same file structure as goes in unfortunately. 

It does for dreamcast images, but when i tested no-intro dumps with separate tracks and a cue they become a cdrecord style toc+single bin (or something like that, forgot what it was in my test long ago).... so upgrading the patch becomes dubious if you can't actually apply the upgrade or even the reverse because the structure required changed.

**Comment by i30817** [comment]
I'm going to close this because it's more of a question than a issue. I opened a new issue for the compression/extraction roundtrip issue.

**Comment by Ferk** [comment]
If the reserve patch is meant to be handled by an external tool, and not really used by the emulator, you could have it as a separate file, you don't need it included in the same chd file, don't you?

Though I can imagine the "original-checksum" tag could be useful for the emulator to identify the game using its database, if it had support to use that custom metadata tag.

**Comment by i30817** [comment]
I'd honestly prefer it as a single file. Separate files can be lost or 'lost' on purpose. As it is not softpatching, it would be much better if it was prevented from this happening.

**Comment by i30817** [comment]
Maybe it can be done if the algorithm is different:

on creation:
take a original and a patch
apply the patch to the original and make a patched file
compress and uncompress the patched file
make a patch from the uncompressed patched file to the original (how? when the original is multitrack and the new file can or can not be?)
add that patch to the footer of the transformed.

then on update:
extract patched file, apply patch in footer recovering original
apply new patch creating new patched file.
steps from creation here

I rather doubt that there is a patch file format permissive enough to turn a single file into multiple files (well i [created one using xdelta](https://pypi.python.org/pypi/zxd3/), but it's just for zips to zip patches and i'm having trouble getting the upstream python binding library i use to get it working on windows).
