### ISSUE TITLE
Quarth music tempo / game rate is too slow

### ISSUE THREAD

**Issue by Mikejmoffitt** [mamedev/mame#2983]
Quarth's music is at the correct pitch, but the tempo is slower than the actual PCB. The crystal for the YM2151 seems to be correct (with the pitch not being a problem), so it is likely the game ticks the sound engine via the vblank interrupt.

I will have to do a proper comparison with a frequency counter to determine if the game's refresh rate is different than how it is marked presently.

**Comment by Mikejmoffitt** [comment]
In this video you can hear the music at its intended rate: https://www.youtube.com/watch?v=i9SArNFYgS0

**Comment by Robbbert** [comment]
Transferred to Mame Testers: https://mametesters.org/view.php?id=7853
