### ISSUE TITLE
mame crashes with hidnctch

### ISSUE THREAD

**Issue by stargoonman** [mamedev/mame#2988]
When you press button 1 after the round starts, it crashes.

Happens with the build from the latest commit

**Comment by stargoonman** [comment]
outputs:

"Unimplemented: generate_subs (40008218)
Fatal error:"

**Comment by katananja** [comment]
Can't reproduce.
Copile with:
`DEBUG=1 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1`

And use -verbose and -log from command prompt.

**Comment by MooglyGuy** [comment]
Confirmed, working on a fix.

**Comment by MooglyGuy** [comment]
@stargoonman the issue should now be fixed with the latest code in the repository. Please do let me know if you run into any other fatalerrors in Hyperstone-based games.

**Comment by stargoonman** [comment]
Tested for 30 mins and it seems to be working fine now!

**Comment by MooglyGuy** [comment]
Excellent, thanks!
