### ISSUE TITLE
Lua help generation

### ISSUE THREAD

**Issue by vadosnaprimer** [mamedev/mame#3000]
Right now everything is just in code comments. If instead all the text describing lua functions is moved to strings, like in debugger help, they can then be used to print lua help to the console and to the file.

There's probably some smart way to register such strings in a less manual way too.

**Comment by Jakobud** [comment]
Is there any sort of documented API for how to use the lua scripting? I see the basic one page walkthrough here:

http://docs.mamedev.org/techspecs/luaengine.html

But there has got to be more API commands. Is there no help documentation for any of it? Where in the source would I find it? For example, that walkthrough shows how to pause the emulator. But it doesn't say anything about how to unpause it...

**Comment by vadosnaprimer** [comment]
Right now everything is only available as comments in luaengine.cpp, and some stuff is not even commented. The goal is to turn those comments into proper docs that show up like in the debugger when you type `help`.

@cuavas suggested to use some native feature of lua to print these future docs, but lua doesn't have it. So I searched for a lib that'd provide it, and here are the 2 libs I found, for the reference (when someone, probably me, finds time to work on this):
https://github.com/vadosnaprimer/lua-annotate
https://github.com/vadosnaprimer/lua-docstring

**Comment by Jakobud** [comment]
Also found this:

https://github.com/stevedonovan/LDoc

Similar to JSDoc.

**Comment by vadosnaprimer** [comment]
@cracyc would you want one of the above, or a manual table inside luaengine, with entries for each lua function as strings? The manual table approach is flexible, it can reflect the tree structure of lua functions and fields, with descriptions and examples, and a separate lua function to print any given help. I have something in mind, might try a PR.

**Comment by cracyc** [comment]
I'd rather do it outside of luaengine, as you say it's more flexable and relinking the whole binary just to change doc strings is a PITA.

**Comment by vadosnaprimer** [comment]
The way I see it, there's just a single luaengine function that prints needed help, and instead of comments, we'd use the same text to add to the table. Little to no overhead code-wise. That way, help string can always be nearby its related function. In debugger they are separated, but when they're close, it's instantly visible what belongs to what, and it's hard to forget to add a help string when you add a new lua function (or modify it). This removes the need for comments too.

**Comment by vadosnaprimer** [comment]
Since luaengine docs have been incorporated into main docs, closing.
