### ISSUE TITLE
Xbrz not working in BGFX since 0.193

### ISSUE THREAD

**Issue by LuismaSP89** [mamedev/mame#3003]
Since 0.193 version, external xbrz (for example 6xbrz.json files in bgfx\chains) doesn´t work anymore. It was working in previous versions.

I know that currently the BGFX backend has some issues in 0.193, but i don´t know if the devs know this specific problem.

**Comment by cuavas** [comment]
MAME 0.193 is built against an updated version of bgfx.  Have you recompiled your external shaders with the new version of bgfx?  Mismatched shader versions are unlikely to work.

**Comment by LuismaSP89** [comment]
@cuavas I don´t know how to compile it, sorry, i´m not good at programming :S

I downloaded it from here:

http://www.mameworld.info/ubbthreads/showflat.php?Cat=&Number=355102&page=0&view=expanded&sb=5&o=&vc=1

**Comment by MooglyGuy** [comment]
This is not an issue with MAME, this is an issue with an external, unsupported shader. Ask whoever wrote the shader to recompile the shaders using the latest MAME build tools.
