### ISSUE TITLE
ibm5170_cdrom set list problem

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#3018]
The ibm5170_cdrom set contains two files called `moon.chd`, which is a problem when you do not use subdirectories for the games. Please fix this (one could be called `moondrg.chd`, for example).

**Comment by cuavas** [comment]
Leaving CHD files loose in the ROM/software directory is not a recommended setup.  Put them in directories for each software item.

**Comment by 0-wiz-0** [comment]
This is the only set list that has this problem. Please fix it anyway.
