### ISSUE TITLE
Solar Assault, Teraburst: Vertical rowscroll is not hook up

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#3028]
I play the Solar Assault has Vertical rowscroll is not hook up in Fighter Select Screen and ending screen:
https://i.imgur.com/tYXU69O.png
https://i.imgur.com/W1g6UJV.png
https://i.imgur.com/qVStkYw.png
https://i.imgur.com/EDagezl.png
https://i.imgur.com/B1iOVu7.png

Also Teraburst rowscroll is not hook up in ending screen, see Youtube video from MAME 191 - KONAMI 3D - TERABURST ARCADE - FULL GAMEPLAY PLAYABLE 1-5 (1:09:36s):
https://www.youtube.com/watch?v=3rayEV_2aKo

In according PCB Video:

See Youtube video from SOLAR ASSAULT REVISED ALL MZR LORD BRITISH 2013.03.30, in 1:13s as select screen, in 37:22s as Ending screen:
https://www.youtube.com/watch?v=R3rhgc2mVes

See Youtube video from SOLAR ASSAULT Stage:10～ENDING (3:09s) as Ending screen:
https://www.youtube.com/watch?v=Y9V4Nyk6Yio&list=PLFFC87C482327F4D0&index=4

**Comment by rb6502** [comment]
That's not row scroll missing, that's just plain vertical scrolling I think.

**Comment by sjy96525** [comment]
Hook up rowscroll for Solar Assault
https://github.com/mamedev/mame/commit/f1497bb1599544be8a9af3b495297edec59dd1cf

But Teraburst Vertical rowscroll is not hook up yet, because the game is used Konami 0000037122 chip.

**Comment by angelosa** [comment]
This is not the right place to submit driver related bug reports. Head over at [MAMEtesters](http://mametesters.org) with details concerning this issue.
