### ISSUE TITLE
Debugger Register Signed Value Display Issue

### ISSUE THREAD

**Issue by Abystus** [mamedev/mame#3037]
**0.184**

![plsycit](https://user-images.githubusercontent.com/1529049/34785535-11c39faa-f5f7-11e7-9acf-bb2824f37c72.png)

**0.193**

![zd3kqiy](https://user-images.githubusercontent.com/1529049/34785552-1b975fb2-f5f7-11e7-8a67-f1c1dd290400.png)

You'll notice in the 0.184 screenshot that the register addresses display starting with FF (which is correct), but in later builds of MAME up-to and including 0.193, they are starting with 7F instead. From we've found, this has to do with how the debugger is displaying signed register variables, as changing them manually to unsigned fixes the issue.

**Comment by ajrhacker** [comment]
I may have a fix for this soon.

**Comment by ajrhacker** [comment]
f8adca0dd0e219a613a6340db1c3f15071a1717a has been tested on the example given above and works.
