### ISSUE TITLE
New Versions of Mame not compile in ARM Processors Its WHY ? V0183 Working like a Charm

### ISSUE THREAD

**Issue by aperfeito** [mamedev/mame#3046]
Environment:
    ChromeBook Tegra TK1 Processor 4G Memory
     OS: 3.10.18-24 ArchLinux Flavor #1 SMP Wed Nov 29 16:27:21 PST 2017 armv7l GNU/Linux
     gcc version 7.2.1 20171128 (GCC)
     Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/armv7l-unknown-linux-gnueabihf/7.2.1/lto-wrapper
Target: armv7l-unknown-linux-gnueabihf
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --host=armv7l-unknown-linux-gnueabihf --build=armv7l-unknown-linux-gnueabihf --with-arch=armv7-a --with-float=hard --with-fpu=vfpv3-d16
Thread model: posix
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
   warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Paramaters to compile : 
make TARGET=mame REGENIE=1 TOOLS=1 SUBTARGET=mame -j5 -fPIC NOWERROR=1

First attempt and crash like a BIG BUG:

Linking chdman...
Compiling src/mame/drivers/adam.cpp...
Compiling src/mame/drivers/funybubl.cpp...
Compiling src/mame/drivers/comx35.cpp...
Compiling src/mame/drivers/pwrview.cpp...
/usr/bin/ld: ../../../../../scripts/src/libutils.a(strformat.o): relocation R_ARM_MOVW_ABS_NC against `_ZNKSt5ctypeIcE8do_widenEc' can not be used when making a shared object; **recompile with -fPIC**
../../../../../scripts/src/libutils.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [chdman.make:250: ../../../../../chdman] Error 1
make[1]: *** [Makefile:1045: chdman] Error 2
make[1]: *** Waiting for unfinished jobs....

O Now Tried to compile wiht -fPIC

2o. Attempt: Crash even better

make TARGET=mame REGENIE=1 TOOLS=1 SUBTARGET=mame -j5 -fPIC NOWERROR=1 LDOPTS=-fPIC OPT_FLAGS=-fPIC 

Results:
Generating ../build/projects/sdl/mame/gmake-linux/imgtool.make...
Done. Generated 359/359 projects.
Linking chdman...
Compiling src/mame/drivers/adam.cpp...
Compiling src/mame/drivers/funybubl.cpp...
Compiling src/mame/drivers/comx35.cpp...
Compiling src/mame/drivers/pwrview.cpp...
/usr/bin/ld: ../../../../../scripts/src/libutils.a(strformat.o): relocation R_ARM_MOVW_ABS_NC against `_ZNKSt5ctypeIcE8do_widenEc' can not be used when making a shared object; recompile with -fPIC
../../../../../scripts/src/libutils.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [chdman.make:250: ../../../../../chdman] Error 1
make[1]: *** [Makefile:1045: chdman] Error 2
make[1]: *** Waiting for unfinished jobs....
Compiling src/mame/video/comx35.cpp...
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
make[2]: *** [comx.make:315: obj/Release/src/mame/drivers/comx35.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [coleco.make:321: obj/Release/src/mame/drivers/adam.o] Error 1
make[1]: *** [Makefile:514: coleco] Error 2
make[2]: *** [compugraphic.make:308: obj/Release/src/mame/drivers/pwrview.o] Error 1
make[1]: *** [Makefile:517: compugraphic] Error 2
Compiling src/mame/drivers/galspnbl.cpp...
Compiling src/mame/drivers/zerozone.cpp...
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
Compiling src/mame/video/funybubl.cpp...
make[2]: *** [comad.make:339: obj/Release/src/mame/drivers/funybubl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
make[2]: *** [comx.make:319: obj/Release/src/mame/video/comx35.o] Error 1
make[1]: *** [Makefile:523: comx] Error 2
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
make[2]: *** [comad.make:347: obj/Release/src/mame/drivers/zerozone.o] Error 1
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
make[2]: *** [comad.make:343: obj/Release/src/mame/drivers/galspnbl.o] Error 1
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: obj/Release/emu.h: No such file or directory
compilation terminated.
make[2]: *** [comad.make:351: obj/Release/src/mame/video/funybubl.o] Error 1
make[1]: *** [Makefile:148: comad] Error 2
make: *** [makefile:1254: linux] Error 2

mame Version V0183 compiled running in the same environment new version 0193 Broken in ARM processor

**Comment by DavidHaywood** [comment]
you already reported this once
https://github.com/mamedev/mame/issues/2925

**Comment by katananja** [comment]
This is an error at you side, I've passed for something similar while trying to compile using Clang, specially this "recompile with -fPIC".

Try with
`make clean && make VERBOSE=1 SUBTARGET=tiny -j5`

And see what it returns.

**Comment by aperfeito** [comment]
make clean 
GCC 7.2.1 detected
Cleaning genie
Cleaning...
make[1]: Entering directory '/home/aperfeito/Downloads/mame/src/devices/cpu/m68000'
Cleaning...
make[1]: Leaving directory '/home/aperfeito/Downloads/mame/src/devices/cpu/m68000'

**Comment by aperfeito** [comment]
make VERBOSE=1 SUBTARGET=tiny -j5
After 10 minutos compiling like before this happends:

rm -f  ../../../../../scripts/src/osd/mame_tiny/libosd_sdl.a
ar  -rcs ../../../../../scripts/src/osd/mame_tiny/libosd_sdl.a obj/Release/osd_sdl/src/osd/modules/debugger/debugimgui.o obj/Release/osd_sdl/src/osd/modules/debugger/debugwin.o obj/Release/osd_sdl/src/osd/modules/debugger/none.o obj/Release/osd_sdl/src/osd/modules/diagnostics/diagnostics_win32.o obj/Release/osd_sdl/src/osd/modules/diagnostics/none.o obj/Release/osd_sdl/src/osd/modules/font/font_dwrite.o obj/Release/osd_sdl/src/osd/modules/font/font_none.o obj/Release/osd_sdl/src/osd/modules/font/font_osx.o obj/Release/osd_sdl/src/osd/modules/font/font_sdl.o obj/Release/osd_sdl/src/osd/modules/font/font_windows.o obj/Release/osd_sdl/src/osd/modules/input/input_common.o obj/Release/osd_sdl/src/osd/modules/input/input_dinput.o obj/Release/osd_sdl/src/osd/modules/input/input_none.o obj/Release/osd_sdl/src/osd/modules/input/input_rawinput.o obj/Release/osd_sdl/src/osd/modules/input/input_sdl.o obj/Release/osd_sdl/src/osd/modules/input/input_sdlcommon.o obj/Release/osd_sdl/src/osd/modules/input/input_uwp.o obj/Release/osd_sdl/src/osd/modules/input/input_win32.o obj/Release/osd_sdl/src/osd/modules/input/input_windows.o obj/Release/osd_sdl/src/osd/modules/input/input_winhybrid.o obj/Release/osd_sdl/src/osd/modules/input/input_x11.o obj/Release/osd_sdl/src/osd/modules/input/input_xinput.o obj/Release/osd_sdl/src/osd/modules/lib/osdobj_common.o obj/Release/osd_sdl/src/osd/modules/midi/none.o obj/Release/osd_sdl/src/osd/modules/midi/portmidi.o obj/Release/osd_sdl/src/osd/modules/monitor/monitor_common.o obj/Release/osd_sdl/src/osd/modules/monitor/monitor_dxgi.o obj/Release/osd_sdl/src/osd/modules/monitor/monitor_sdl.o obj/Release/osd_sdl/src/osd/modules/monitor/monitor_win32.o obj/Release/osd_sdl/src/osd/modules/netdev/none.o obj/Release/osd_sdl/src/osd/modules/netdev/pcap.o obj/Release/osd_sdl/src/osd/modules/netdev/taptun.o obj/Release/osd_sdl/src/osd/modules/opengl/gl_shader_mgr.o obj/Release/osd_sdl/src/osd/modules/opengl/gl_shader_tool.o obj/Release/osd_sdl/src/osd/modules/osdwindow.o obj/Release/osd_sdl/src/osd/modules/output/console.o obj/Release/osd_sdl/src/osd/modules/output/network.o obj/Release/osd_sdl/src/osd/modules/output/none.o obj/Release/osd_sdl/src/osd/modules/output/win32_output.o obj/Release/osd_sdl/src/osd/modules/render/aviwrite.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/blendreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/chain.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/chainentry.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/chainentryreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/chainmanager.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/chainreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/clear.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/clearreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/cullreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/depthreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/effect.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/effectmanager.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/effectreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/entryuniformreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/frameparameter.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/inputpair.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/paramreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/paramuniform.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/paramuniformreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/shadermanager.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/slider.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/sliderreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/slideruniform.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/slideruniformreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/statereader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/suppressor.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/suppressorreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/target.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/targetmanager.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/targetreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/texture.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/texturemanager.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/timeparameter.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/uniform.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/uniformreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/valueuniform.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/valueuniformreader.o obj/Release/osd_sdl/src/osd/modules/render/bgfx/writereader.o obj/Release/osd_sdl/src/osd/modules/render/bgfxutil.o obj/Release/osd_sdl/src/osd/modules/render/binpacker.o obj/Release/osd_sdl/src/osd/modules/render/draw13.o obj/Release/osd_sdl/src/osd/modules/render/drawbgfx.o obj/Release/osd_sdl/src/osd/modules/render/drawogl.o obj/Release/osd_sdl/src/osd/modules/render/drawsdl.o obj/Release/osd_sdl/src/osd/modules/sound/coreaudio_sound.o obj/Release/osd_sdl/src/osd/modules/sound/direct_sound.o obj/Release/osd_sdl/src/osd/modules/sound/js_sound.o obj/Release/osd_sdl/src/osd/modules/sound/none.o obj/Release/osd_sdl/src/osd/modules/sound/pa_sound.o obj/Release/osd_sdl/src/osd/modules/sound/sdl_sound.o obj/Release/osd_sdl/src/osd/modules/sound/xaudio2_sound.o obj/Release/osd_sdl/src/osd/osdnet.o obj/Release/osd_sdl/src/osd/sdl/sdlmain.o obj/Release/osd_sdl/src/osd/sdl/video.o obj/Release/osd_sdl/src/osd/sdl/window.o obj/Release/osd_sdl/src/osd/watchdog.o 
make[1]: Leaving directory '/home/aperfeito/Downloads/mame/build/projects/sdl/mametiny/gmake-linux'
make: *** [makefile:1254: linux] Error 2

I am available to give more info to resolve this Problem

**Comment by katananja** [comment]
`Error 2` means something went wrong, use:
`make VERBOSE=1 SUBTARGET=tiny`

And nothing else!

**Comment by aperfeito** [comment]
Hi contributors for awesome mame,

    Sorry for delay answer because here in USA was Holyday !


       Now Back to business:


  Hi did was you told me look what's happend:


[aperfeito@alarm mame]$ make VERBOSE=1 SUBTARGET=tiny
GCC 7.2.1 detected
make -R verbose=1 -C build/projects/sdl/mametiny/gmake-linux config=release precompile
make[1]: Entering directory '/home/aperfeito/Downloads/mame/build/projects/sdl/mametiny/gmake-linux'
make[1]: Leaving directory '/home/aperfeito/Downloads/mame/build/projects/sdl/mametiny/gmake-linux'
make -R verbose=1 -C build/projects/sdl/mametiny/gmake-linux config=release
make[1]: Entering directory '/home/aperfeito/Downloads/mame/build/projects/sdl/mametiny/gmake-linux'
Compiling 3rdparty/sqlite3/sqlite3.c...
gcc   -MMD -MP -MP -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2    -pipe -Wno-deprecated-declarations -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-unused-result -Wno-array-bounds -Wno-cast-align -std=gnu99 -Wpointer-arith -Wstrict-prototypes -Wbad-function-cast -Wno-discarded-qualifiers -Wno-unused-but-set-variable -Wno-bad-function-cast -Wno-undef  -o "obj/Release/3rdparty/sqlite3/sqlite3.o" -c "../../../../../3rdparty/sqlite3/sqlite3.c"
In function ‘vdbePmaReadBlob.part.323’,
    inlined from ‘vdbePmaReadBlob’,
    inlined from ‘vdbePmaReadVarint.part.324’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85435:12,
    inlined from ‘vdbePmaReadVarint’,
    inlined from ‘vdbePmaReaderNext’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85546:8:
../../../../../3rdparty/sqlite3/sqlite3.c:85392:5: error: ‘memcpy’: specified size between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]
     memcpy(p->aAlloc, &p->aBuffer[iBuf], nAvail);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘vdbePmaReadBlob.part.323’,
    inlined from ‘vdbePmaReadBlob’,
    inlined from ‘vdbePmaReadVarint.part.324’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85435:12,
    inlined from ‘vdbePmaReadVarint’,
    inlined from ‘vdbePmaReaderInit.constprop’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85583:8,
    inlined from ‘vdbeMergeEngineLevel0’ at ../../../../../3rdparty/sqlite3/sqlite3.c:87159:8:
../../../../../3rdparty/sqlite3/sqlite3.c:85392:5: error: ‘memcpy’: specified size between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]
     memcpy(p->aAlloc, &p->aBuffer[iBuf], nAvail);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [sqlite3.make:278: obj/Release/3rdparty/sqlite3/sqlite3.o] Error 1
make[1]: *** [Makefile:55: sqlite3] Error 2
make[1]: Leaving directory '/home/aperfeito/Downloads/mame/build/projects/sdl/mametiny/gmake-linux'
make: *** [makefile:1254: linux] Error 2
[aperfeito@alarm mame]$ 

PS: I am available to give more info to resolve this Problem

Cheers

**Comment by cracyc** [comment]
Just use NOWERROR=1, that warning is bogus.

**Comment by cracyc** [comment]
Add REGENIE=1 to regenerate the makefiles.

**Comment by aperfeito** [comment]
Now compile Ok, But doesn't work:
Below the complete procedure crash procedure
https://pastebin.com/W57n65LE
PS: I am available to give more info to resolve this Problem

Cheers

**Comment by galibert** [comment]
Your /etc/ld.so.conf or your /etc/ld.so.conf.d/* files fail to indicate the
directory where the qt shared libs are.

  OG.

**Comment by aperfeito** [comment]
Nope !
[aperfeito@alarm ld.so.conf.d]$ ldconfig -v 2>/dev/null | grep -v ^$'\t'
/usr/lib/libfakeroot:
/usr/lib:
[aperfeito@alarm ld.so.conf.d]$ cd /
[aperfeito@alarm /]$ sudo find -name "libQt5Core.so.5"
./usr/lib/libQt5Core.so.5
Its Ok
[aperfeito@alarm mame]$ ls
3rdparty         artwork     bgfx   cfg    dist.mak  doxygen  hlsl  keymaps   LICENSE.md  mametiny     plugins   README.md  roms     scripts  tests        web
android-project  benchmarks  build  ctrlr  docs      hash     ini   language  makefile    nl_examples  projects  regtests   samples  src      uismall.bdf
[aperfeito@alarm mame]$ sudo ./mametiny
Now Running..Without sudo gave thats errors before 

Problem Solve in **Tiny verison** runnng like a charm
Thanks 

Now How this not compile in like 
make TARGET=mame REGENIE=1 TOOLS=1 SUBTARGET=mame NOWERROR=1 -j5

**Comment by aperfeito** [comment]
Its Work now.
   Now its compile normaly. The proble is solved .
   Cause : User Permition
