### ISSUE TITLE
citycon, citycona and cruisin sound issues with YM2203

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#3062]
mame0193-504-g7ad91043f6-dirty, Windows 10 x64.

The sound of one of the channels, maybe `MCFG_SOUND_ROUTE 3` (FM channel?) , is using a wrong tone, too metallic or maybe clipping. High notes are not clear, too muffled or cut it down, some notes sustain too much, it keep ringing almost like a bell, takes too long to die.

This can be noticed at the stage 4 (German).
I'm attaching a sample from the [M1](http://rbelmont.mameworld.info/?page_id=223) tool from @rb6502 playing with [BridgeM1](http://www.e2j.net/downloads.html) and using the exact same c1 audiocpu file.
**M1**
[004 City Connection (set 1) (citycon) [#243] Stage 4 (German).zip](https://github.com/mamedev/mame/files/1628873/004.City.Connection.set.1.citycon.243.Stage.4.German.zip)
**MAME**
[MAME City Connection (set 1) (citycon).zip](https://github.com/mamedev/mame/files/1628874/MAME.City.Connection.set.1.citycon.zip)

Arcade recording, start at 2:15
https://youtu.be/r-6Hv6LQ5II?t=2m15s

Another recording, unknown source
https://youtu.be/l2BgtNNVKVg?t=2m11s

Arcade?
![credit-arcade](https://user-images.githubusercontent.com/9029191/34911515-52bd7698-f8b3-11e7-88a6-6bcce8708b56.jpg)
https://www.youtube.com/watch?v=l2BgtNNVKVg
[credit-arcade.zip](https://github.com/mamedev/mame/files/1628903/credit-arcade.zip)

MAME
Insert coin tone is off or cut?
![credit-mame](https://user-images.githubusercontent.com/9029191/34911513-499af52c-f8b3-11e7-9d69-d4988669843e.jpg)
[credit-mame.zip](https://github.com/mamedev/mame/files/1628904/credit-mame.zip)

`citycon.lst` for Bridge
```
$name=citycon
$version=1
$default=240
$songmax=$178
$main

#240 Stage 1 (America)
#241 Stage 2 (London)
#242 Stage 3 (Paris)
#243 Stage 4 (German)
#244 Stage 5 (Holland)
#245 Stage 6 (Egypt)
#246 Stage 7 (India)
#247 Stage 8 (China)
#248 Stage 9 (Japan)
#249 Stage 10 (Australia)
#250 Stage 11 (Easter Islands)
#251 Stage 12 (South America & London Stage 2)
#236 Hit The Cat
#237 Game Over
#238 Fanfare
#239 Stage Clear

// List contribution by Katananja.
$end
```

**Comment by cuavas** [comment]
Comparison to M1 is not valid, it's a relatively old emulator based on different sound cores.

**Comment by katananja** [comment]
Nothing is valid to you @cuavas, the sql issue was fixed by the way.
Never mind the arcade recordings and mame recording comparison showing **CLEARLY**, that something is of...

But, never mind to you...
This kind o stuff is something you don't care about, right?

**Comment by katananja** [comment]
Hey @cuavas !
What took you so long?
I use images this time!

Remember the other ticket you close like this one? #3022
Is fixed! Yeah!!!

There is also audio recording from arcades that you should listen too.
Have a good one!

**Comment by katananja** [comment]
Does the developers has access to a full `YM2203` datasheet??
The code has a lot of "??" like this:
```
/* Initialize FM emurator */
	int rate = clock()/72; /* ??? */
```
The japanese datasheet say it has 3 timers.


**タイマAの周期** (Timer A Cycle/Period)
```
TA = 72 * (1024 - NA) / φM
TA: タイマAの周期
φM: マスタークロック <- MASTER CLOCK
NA = (@24h[7:0] << 2) + @25h[1:0]
```

**タイマBの周期**(Timer B Cycle/Period)
```
TB = 1152 * (256 - NB) / φM
TB: タイマBの周期
φM: マスタークロック <- MASTER CLOCK
NB = @26h[7:0]
```
**タイマの制御** (The thing that govern or control the timer)
```
@27h[0]: タイマAのスタート(1) / ストップ(0)
@27h[1]: タイマBのスタート(1) / ストップ(0)
@27h[2]: タイマAのオーバーフローでの割り込みを 有効(1) / 無効(0) にする。
@27h[3]: タイマBのオーバーフローでの割り込みを 有効(1) / 無効(0) にする。
@27h[4]: 1を書くとタイマAの割り込みフラグがクリアされる。(このビットは即座に0に戻る。)
@27h[5]: 1を書くとタイマBの割り込みフラグがクリアされる。(このビットは即座に0に戻る。)
```
Or
```
@27h[0]: Timer A Start(1) / Stop(0)
@27h[1]: Timer B Start(1) / Stop(0)
@27h[2]: Use Overflow Timer A to set interruption valid (1) / invalid (0)
@27h[3]: Use Overflow Timer B to set interruption valid (1) / invalid (0)
@27h[4]: If 1 is written to timer A the interruption flag is clear (Otherwise this flag is back to 0 automatically)
@27h[5]: If 1 is written to timer A the interruption flag is clear (Otherwise this flag is back to 0 automatically)
```

**マスタークロックのプリスケーラ** Master Clock Prescalers

```
アドレス | FM音源の分周比 | PSG音源の分周比
-- | -- | --
2Dh | 1/6 | 1/4
2Dh, 2Eh | 1/3 | 1/2
2Fh | 1/2 | 1/1
```
Or
Address 2Dh, 1/6 proportion of the FM input audio source and 1/4 of PSG
Address 2Dh, 2Eh 1/3 and 1/2
Address 2Fh, 1/2 and 1/2

So on and so forth, the datasheet has a lot of data, numbers, addresses and algorithms.
http://d.hatena.ne.jp/licheng/20131112/p1

I believe that with all that information is possible to fill in the blanks left behind and to create a better YM2203 emulation fixing the audio that is way off. The site also has a lot of juicy stuff for developers.

Looking forward to see how that data will be translated in to c++ code. ;)

Thank you!

**Comment by katananja** [comment]
`fm.cpp`
**タイマAの周期**
```
TA = 72 * (1024 - NA) / φM
TA: タイマAの周期
φM: マスタークロック <- MASTER CLOCK
NA = (@24h[7:0] << 2) + @25h[1:0]
```
```
/* Timer A Overflow */
static inline void TimerAOver(FM_ST *ST)
{
	/* set status (if enabled) */
	if(ST->mode & 0x04) FM_STATUS_SET(ST,0x01);
	/* clear or reload the counter */
	ST->TAC = (1024-ST->TA);
	if (ST->timer_handler) (ST->timer_handler)(ST->device,0,ST->TAC * ST->timer_prescaler,ST->clock);
}
```
This `ST->TAC = (1024-ST->TA);` shouldn't be something like `ST->TAC = 72*(1024-ST->TA)/clock;` or something?

**Comment by katananja** [comment]
This is more like it.
```
// ---------------------------------------------------------------------------
//	タイマーA 周期設定
//
void Timer::SetTimerA(uint addr, uint data)
{
	uint tmp;
	regta[addr & 1] = uint8(data);
	tmp = (regta[0] << 2) + (regta[1] & 3);
	timera = (1024-tmp) * timer_step;
}
```

Looks like MAME had a FM generator before.
`FM sound generator for M.A.M.E., written by Tatsuyuki Satoh.`

His source looks more align with the datasheet, the decay and sustain looks right, his FM Sound Emulator sound like FM.

Looks like this is not a datasheet issue, is something else.

**Comment by rb6502** [comment]
A couple of additional comments:

- I made M1.  It is NOT usable as a comparison source for correctness, only recordings from real arcade PCBs are.
- Yamaha's FM documentation is somewhere between misleading and actively wrong in many instances.  People on a Genesis/Megadrive forum ran years of tests on real hardware YM2612s to determine how to get proper sound, and more recently the YM3812 for correct AdLib/SoundBlaster emulation had be decapped and turned into a schematic because simply following the manual results in incorrect sound.

**Comment by cuavas** [comment]
@katananja you're effectively spamming us with unhelpful reports and comments.  You're not bringing new insights, you're just cluttering up the project.  If you don't stop, I really will ban you from opening issues.

In the case of the issue in SQLite 3, your report was not helpful without showing that the API was being abused.  Anyone can run an instrumented build and get stack traces.  Spamming issues based on that is not helpful if you're not providing any additional value.

By your own admission, you're trying to learn about development.  What you're doing is antagonistic, and it's not going to help you.  You need to learn how to work with a project team and what is and isn't helpful before you can learn about development.  However, it looks like you're completely unwilling to learn.

**Comment by katananja** [comment]
Hi.
M1 was used as a sample, nothing more. Even with an old engine, the tone is correct, the FM sound right, the notes sound correct, the notes sustain right, decay right, etc. 

I've also posted youtube videos from supposed arcade recordings, and if we discard that as well, is impossible not to notice that the sound is off, specially with the YM2203 channel on stage 4, the channel has a very bad distortion on it, the high notes sound very harsh and broken, the whole game sound sound muffled, the mame output was recorded with `-wavwrite`.

I agree that the datasheet not always reflect the true information about a chip, I've worked as a Sony Hardware designer for 5 years in Japan, there are some shadow areas inside this chips that has trade secrets on it, the emulation will never get perfect, but can get very close, too bad a decap will not show  all it's secrets. To this day, people still didn't find out that you can switch some registers in some pages inside Playstation 1 and 2 (cameras, PSP, VITA, etc) with LANC protocol using a simple RM95 modded control and a jig for example.

I'll not prolong this anymore, there is a FM sound Emulator interface made by a Japanese, it may worth to take a look. I don't know if it is a perfect emulation but it sound really, really good.
https://github.com/katahiromz/fmgon

Thank you.
