### ISSUE TITLE
MAME no longer compiles on windows x64 (mingw-gcc)

### ISSUE THREAD

**Issue by stargoonman** [mamedev/mame#3079]
`[MINGW64] D:\Development\Repos\Mamedev\mame\msys64\src>make
GCC 7.2.0 detected
Compiling generated/mame/mame/drivlist.cpp...
Compiling generated/version.cpp...
Emitting mamevers.rc...
Compiling resources scripts/resources/windows/mame/mame.rc...
Linking mame64.exe...
../../../../mingw-gcc/obj/x64/Release/generated/mame/mame/drivlist.o:drivlist.cpp:(.rdata+0x40a40): undefined reference to `driver_tourvis'
collect2.exe: error: ld returned 1 exit status
mame.make:252: recipe for target '../../../../../mame64.exe' failed
make[2]: *** [../../../../../mame64.exe] Error 1
makefile:1039: recipe for target 'mame' failed
make[1]: *** [mame] Error 2
makefile:998: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2`

**../../../../mingw-gcc/obj/x64/Release/generated/mame/mame/drivlist.o:drivlist.cpp:(.rdata+0x40a40): undefined reference to `driver_tourvis'**

Latest commit (https://github.com/mamedev/mame/commit/b6450aa0ae3a8d8c09df01aa641c024bf14a9b43)

I don't remember tourvis being touched recently?

**Comment by DavidHaywood** [comment]
you might just have a corrupt file, try just opening up the tourvis driver and saving it again to force a recompile

**Comment by stargoonman** [comment]
@DavidHaywood lol you were right. Never knew this could happen. Could you tell me why this happens?

Closing this. Thanks!

**Comment by DavidHaywood** [comment]
sometimes it just does

it can easily happen if the compile is aborted midway through writing a file, but I've also seen it happen from time to time in Windows anyway, like there's some kind of access conflict at the very moment it writes the file and you end up with a 0 byte file instead.

just one of those things..
