### ISSUE TITLE
Building: Use "thin" archives for intermediate static libraries

### ISSUE THREAD

**Issue by StefanBruens** [mamedev/mame#3085]
From the GNU binutils ar manpage:
> 
GNU ar can optionally create a thin archive, which contains a symbol index and references to the original copies of the member files of the archive.  This is useful for building libraries for use within a local build tree, where the relocatable objects are expected to remain available, and copying the contents of each object would only waste time and space.

Thin archives are created with the "T" modifier.

**Comment by cuavas** [comment]
We don't depend on the user having GNU ar.  This flag is incompatible with BSD ar (used on macOS and the BSDs), which uses T to use only the first fifteen characters of archive member names.  If you want to pursue this further, you'd be better off looking at upstream GENie to see whether it can detect that GNU ar is being used and provide an option to use thin archives.
