### ISSUE TITLE
Latest mame driver API change error? (raycris)

### ISSUE THREAD

**Issue by stargoonman** [mamedev/mame#3096]
>mame64 raycris
upd78081.655 NO GOOD DUMP KNOWN
WARNING: the machine might not run correctly.
**Fatal error: devcb_read: Error performing a late bind of type 17taito_zoom_device to 13taitogn_state (name=taitogn_state::zsg2_ext_r)**

Is this an expected behavior (for now)?

**Comment by Tafoid** [comment]
All taitogn.cpp machines are not functioning at the moment due to this commit:  https://github.com/mamedev/mame/commit/d469cc04bcace0f601802301caeddc5b473b75f2
I'd expect it to be fixed as soon as possible and surely before release of MAME 0.194 at the end of the month.

**Comment by stargoonman** [comment]
Ah, I see. Glad to know it's not an expected behavior.
