### ISSUE TITLE
Inconsistency in software entry for abc80_flop

### ISSUE THREAD

**Issue by krozett** [mamedev/mame#3138]
When doing `mame64 -verifysoftlist abc80_flop` all my software checks out except for one item:

```
abc80_flop:abcdemo: genesisproject_abcdemo.dsk (163840 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(667459a0) SHA1(ade6420c75a27840f5308fb588ba381ec5f527ea)
   FOUND: CRC(29059d3c)
romset abc80_flop:abcdemo is bad
```

Okay, fair enough. I extracted the dsk file and checked its CRC and SHA-1 sum, which were `29059d3c` and `55b38436a2d3cfe1caf8e35e44775402a1511eec`. So the verification seems to be doing its job.

Except when you look at https://github.com/mamedev/mame/blob/master/hash/abc80_flop.xml, they match what my file has and not what -verifysoftlist claims to be the correct ones. I'm not even sure where those checksums are coming from if not the XML file.

Digging a little deeper, I saw the last two changes to those checksums:
https://github.com/mamedev/mame/commit/89c46e3d8ffdbc6ca6a2b52fa77b12bb9e089047#diff-200ac22f0bc6ae1c7b1ea01e1e727485 says it's de-interleaving the file in question.
https://github.com/mamedev/mame/commit/f20f71a3bf1c753f9da7b798af22acd8a178e533#diff-200ac22f0bc6ae1c7b1ea01e1e727485 added a new piece of software but then also reverted the checksums for `abcdemo`. Could this have been a merge error?

**Comment by Robbbert** [comment]
Checked just now, no errors reported. Is it still an issue for you?

**Comment by Robbbert** [comment]
No reply -closed.
