### ISSUE TITLE
Compilation Error - setLabel() not found

### ISSUE THREAD

**Issue by MatthewWolff** [mamedev/mame#3152]
Compiling on Mac OSX El Capitan, 10.11.6

In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.mm:10:
../../../../../3rdparty/bgfx/src/renderer_mtl.h:334:12: error: instance method '-setLabel:' not found (return type defaults to 'id') [-Werror,-Wobjc-method-access]
                                [m_obj setLabel:@(_label)];
                                       ^~~~~~~~

Installed the SDL framework as per instructions, couldn't find anything meaningful on google to help fix this.

**Comment by cuavas** [comment]
That's in the upstream bgfx code, from bkaradzic/bgfx - you might want to see if you can build from upstream, otherwise raise an issue there.

**Comment by Robbbert** [comment]
Answer from bgfx git: I see no issue, bgfx doesn't support anything below 10.12 OSX.

10.11.6 is therefore unsupported. Closing.
