### ISSUE TITLE
0.194 does not compile on ppc64/ppc64le linux

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#3157]
Hi all,
mame-0.194 Fedora package has failed to build [1][2] on ppc64 and ppc64le Fedora:
```g++    -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/mame" -I"../../../../../src/lib" -I"../../../../../src/lib/util" -I"../../../../../src/lib/netlist" -I"../../../../../3rdparty" -I"../../../../generated/mess/layout" -I"../../../../generated/mame/layout" -I"../../../../../scripts"   -m64 -pipe -Wno-deprecated-declarations -O2 -fno-strict-aliasing -O2 -g1 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power8 -mtune=power8 -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-unused-result -Wno-array-bounds -m64 -x c++ -std=c++14 -Woverloaded-virtual -Wsuggest-override -flifetime-dse=1 -include ../../../../linux_gcc/obj/x64/Release/emu.h -o "../../../../linux_gcc/obj/x64/Release/src/mame/drivers/fp200.o" -c "../../../../../src/mame/drivers/fp200.cpp"
In file included from ../../../../../src/emu/emu.h:31:0:
../../../../../src/mame/drivers/fp200.cpp:28:36:   in constexpr expansion of 'operator""_MHz_XTAL(6.14399999999999999999999999999999e+0l)'
../../../../../src/emu/xtal.h:85:83: error: '(6.14399999999999999999999999999999e+0l * 1.0e+6l)' is not a constant expression
 constexpr XTAL operator ""_MHz_XTAL(long double clock) { return XTAL(double(clock * 1e6)); }
                                                                             ~~~~~~^~~~~
make[2]: *** [casio.make:362: ../../../../linux_gcc/obj/x64/Release/src/mame/drivers/fp200.o] Error 1
make[1]: *** [Makefile:463: casio] Error 2
```
The builds on s390x, i686, x86_64, aarch64 and armv7hl have completed successfully.
Best regards,
Julian
[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=24590264
[2] https://koji.fedoraproject.org/koji/taskinfo?taskID=24590275

**Comment by felipesanches** [comment]
I guess you mean **0.194** ?

**Comment by belegdol** [comment]
Indeed, sorry - comment and title corrected

**Comment by felipesanches** [comment]
I guess you mean **0.194** on the issue description as well ? ;-D

**Comment by galibert** [comment]
That compiler is drunk.  Find a sober one.

  OG.

**Comment by belegdol** [comment]
The drunk compiler is gcc-7.2.1 on both Fedora releases.

**Comment by galibert** [comment]
That's also what I use, but obviously not on ppc.  But seriously, that
error message is insane.

  OG.

**Comment by cuavas** [comment]
The `long double` type is a bit weird on PPC - it's a pair of `double` added together effectively, so you get an increase in precision but not range.  You can also get strange effects if the two parts of the double don't line up neatly end-to-end.  I suspect what's happening is that it's implicitly relying on a library function to multiply long double values, and the library function isn't `constexpr` qualified.  I don't know what to do about it though - user-defined literal suffixes work on a very limited set of types.

**Comment by ajrhacker** [comment]
It appears that constant expressions of the PPC `long double` type have been basically broken for over a decade in GCC, with no fix projected.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=26374

**Comment by galibert** [comment]
Are we using --with-long-double-128 on ppc, and if yes why?  There's a
clear lack of "long" in the compiled code.

  OG.

**Comment by ajrhacker** [comment]
@galibert: As the OP shows, there are in fact `long double` overloads in our code now. These were Vas's doing, not yours.

**Comment by cuavas** [comment]
Floating point user-defined literals need to use `long double`, so there's no way of avoiding it.  I think `--with-long-double-128` is default on ppc64/ppc64le so there's not much we can do about it on that side.

**Comment by belegdol** [comment]
I added ExcludeArch for ppc64 and ppc64le for now, we may be able to get some help from Fedora's ppc team.

**Comment by classilla** [comment]
The miscompile can be worked around by adding -mlong-double-64 to the compiler flags. This isn't ideal but appears to fix this specific problem. This gets the build further but there is another compilation issue at least on my ppc64le machine which I will try to spin up a PR for.

**Comment by classilla** [comment]
(obviously `-mlong-double-64` is only necessary for ppc64/ppc64le, it could be written into the platform code in the `makefile`)

**Comment by belegdol** [comment]
Looks like in Fedora 30 at keast ppc64le might start working again:
https://fedoraproject.org/wiki/Changes/PPC64LE_Float128_Transition

**Comment by StefanBruens** [comment]
> The "fix" throws away LSBs - double doesn't have enough mantissa bits.

Honestly?
Doing the multiplication first and the casting to double will differ from the other ordering in at most **THE** LSB, nothing more.
The 53bit double mantissa is enough for a precision of 1.1*10^-16 -- 1ppb is 10^-9, the NIST atomic clock is at about 10^-16.

**Comment by cuavas** [comment]
The fact is it produces different results when using the XTAL(...) vs ..._MHz_XTAL syntax.  That's not acceptable.

**Comment by runlevel5** [comment]
> Looks like in Fedora 30 at least ppc64le might start working again:
https://fedoraproject.org/wiki/Changes/PPC64LE_Float128_Transition

@belegdol fingercross Fedora 33 would deliver that proposal

**Comment by belegdol** [comment]
@cuavas, continuing the discussion from bannister.org shoutbox: it appears we are not good to go for ppc64le after all unfortunately. Full build on Fedora rawhide still fails:
```
Compiling src/mame/drivers/akkaarrh.cpp...
g++    -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/mame" -I"../../../../../src/lib" -I"../../../../../src/lib/util" -I"../../../../../src/lib/netlist" -I"../../../../../3rdparty" -I"../../../../generated/mame/layout" -I"../../../../../scripts"  -m64 -pipe -O2 -fno-strict-aliasing -O2 -fexceptions -g1 -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64 -std=c++14 -Woverloaded-virtual -Wno-class-memaccess -Wsuggest-override -flifetime-dse=1 -include ../../../../linux_gcc/obj/x64/Release/emu.h -o "../../../../linux_gcc/obj/x64/Release/src/mame/drivers/akkaarrh.o" -c "../../../../../src/mame/drivers/akkaarrh.cpp"
In file included from ../../../../../src/emu/emu.h:32:
../../../../../src/mame/drivers/akkaarrh.cpp:81:38:   in 'constexpr' expansion of 'operator""_MHz_XTAL(1.20959999999999999999999999999999e+1l)'
../../../../../src/emu/xtal.h:85:83: error: '(1.20959999999999999999999999999999e+1l * 1.0e+6l)' is not a constant expression
   85 | constexpr XTAL operator ""_MHz_XTAL(long double clock) { return XTAL(double(clock * 1e6)); }
      |                                                                             ~~~~~~^~~~~
make[2]: *** [atari.make:1783: ../../../../linux_gcc/obj/x64/Release/src/mame/drivers/akkaarrh.o] Error 1
```
Travis build working must be either due to vertigo.cpp not triggering the problem, or due to Ubuntu 18.04 using a different set of default CXXFLAGS (-mfloat128 is on by default if VSX is enabled as per man gcc). I will see if I can find the time to add akkaarrh to the ci build over the weekend so that we can have a definitive answer.

**Comment by belegdol** [comment]
It is the former, akkaarrh fails to build in Travis too:
https://travis-ci.com/github/belegdol/mame/jobs/376058845

**Comment by runlevel5** [comment]
> https://fedoraproject.org/wiki/Changes/PPC64LE_Float128_Transition
This work has postponed till Fedora 34. oh well..

**Comment by belegdol** [comment]
Fedora 36 is finally going to have the long double change implemented, looking forward to checking whether 0.240 builds on ppc64le again.

**Comment by runlevel5** [comment]
@belegdol where do you get that info from? AFAIK that proposal has been postponed indefinitely

**Comment by sharkcz** [comment]
From the gcc changelog, "- default to -mabi=ieeelongdouble on ppc64le" specifically in gcc-12.0.1-0.2.fc36. You are right the wiki page hasn't been updated for some time.

**Comment by belegdol** [comment]
ppc64le build has succeeded: https://koji.fedoraproject.org/koji/buildinfo?buildID=1910854

**Comment by belegdol** [comment]
> Did you run `-validate`? 
I did now, it passed: https://koji.fedoraproject.org/koji/taskinfo?taskID=82247543

> Do you want to see if the on-the-fly vtable generation works?
How would I do that? Can this be done as an automated test? I do not have access to ppc64le system other than the builder.

**Comment by cuavas** [comment]
It requires manual interpretation of output.

**Comment by belegdol** [comment]
It will have to wait for someone with full access to ppc64le machine then, sorry.

**Comment by runlevel5** [comment]
> It requires manual interpretation of output.

Could you please elaborate on this?

**Comment by cuavas** [comment]
I have a program that exercises the code in src/lib/util/dynamicclass.{h,cpp} but it prints output to stdout that needs to be interpreted by a human to test whether it actually works (assuming it doesn’t simply crash or cause error that can be detected by a memory analyser like valgrind).  Only particularly bad bugs would be detected by valgrind or cause it to crash outright.

**Comment by runlevel5** [comment]
@cuavas I could help if you could provide further instructions
