### ISSUE TITLE
Small bug in src/devices/sound/fm.cpp

### ISSUE THREAD

**Issue by vampirefrog** [mamedev/mame#3160]
There is a small bug in src/devices/sound/fm.cpp:3307, when using YM2610B. It has to do with the warning issued when trying to write to channels 0 and 3. Normally you use ym2610b_update_one(), but because the functions for ym2610b are the same as the functions for ym2610, when calling ym2610_write and you write to the registers that correspond to the above mentioned channels, because it internally calls ym2610_device::update_request() which in turn calls ym2610_update_one, it ends up complaining about those channels, thinking it is a YM2610.

I suppose the correct fix would be to add a ym2610b_write() function, which eventually calls ym2610b_update_one(), or perhaps some extra checking to see if it is a 2610 or a 2610B. Either way, it's a dumb bit of code IMO.

**Comment by katananja** [comment]
It was pointed out that the engine has issues and is not small, too bad I don't have access to a real hardware. There is a machine name citycon that sound is wrong for over 10 years, but receive a pass anyway.

Go figure.

**Comment by vampirefrog** [comment]
I don't think this affects the sound, it merely prints out warnings.

**Comment by katananja** [comment]
Sound has issues, along the one you pointed out, I was talking about the YM2203 and the FM engine. We need to have access to a original board to get that one fixed.

**Comment by aaronsgiles** [comment]
This issue is irrelevant with the rewritten FM cores. Closing.
