### ISSUE TITLE
cdi.cpp: quizard, quizard2 and quizard3 hang

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#3250]
The CDI games shows the Philips menu, but after pressing "PLAY CD-I" they hang!
Possible address map problem i can't find!

**Comment by Tafoid** [comment]
https://github.com/mamedev/mame/commit/127cd08d4d8a7ebbd5e0cbe8239fa17c8dc9b20e is the likely culprit.  Matches up to the day/reason for selecting it (cdi.cpp) driver for testing.

**Comment by ajrhacker** [comment]
Fixed in bfc4ccd18a1c9171791cc19cd1492692f22a0f22.
