### ISSUE TITLE
Musashi/M68k: Bitfield mask for 5th byte is wrong

### ISSUE THREAD

**Issue by harbaum** [mamedev/mame#327]
The instruction
bfset mem{1:32}

writes 32 bits 0x7fffffff and then 8 bits of a fifth byte with 0xff while it should be writing 0x80 (only the last missing bit from the first 32 bit write).

The problem is the fact that the offset isn't take into account at all at several places in m68k_in.c:

```
    mask_base = MASK_OUT_ABOVE_32(0xffffffff << (32 - width));
  ...
    if((width + offset) > 32)
    {
        mask_byte = MASK_OUT_ABOVE_8(mask_base);
   ...
        m68ki_write_8((mc68kcpu), ea+4, data_byte | mask_byte);
    }
```

The mask_byte imho needs to be generated like this:

```
mask_byte = MASK_OUT_ABOVE_8(mask_base) << (8-offset);
```

This fix is not tested as i am actually not working on Musashi but instead tried to use Musashi to verify another core.

**Comment by rb6502** [comment]
Hi!  Do you have any kind of test binary, or even a few raw opcodes?  Also, has this been checked against a real hardware m68k?

**Comment by peterferrie** [comment]
> Hi!  Do you have any kind of test binary, or even a few raw opcodes?  Also,
> has this been checked against a real hardware m68k?

Is this it?
EE D0 01 00    bfset   (a0){1:32}

If so, then the Interactive Disassembler has a bug, too.

**Comment by harbaum** [comment]
In my testcase it's
  ee f9 00 40 55 aa 00 04
which is
  bfset   $55aa0004{1:32}

as 55aa0000 is where ram is in my test setup. 

This has been assembled using vasm_mot

I don't have complete examples. But it seems i need to reconsider my entire test setup and might have complete test programs, soon. I'll also try to compile them into Atari ST or Amiga programs to be able to test against real hardware.

**Comment by rb6502** [comment]
Great, thanks.  And the h/w writes 7fffffff and then 80?

**Comment by rb6502** [comment]
Also, needless to say, we'd be interested in any complete test programs you come up with.  We pass Gwenole's old 68K tester, but that only tests original 68000 instructions, not the '020 bitfield stuff like this.

**Comment by balr0g** [comment]
We had someone test this on hardware and the behavior @harbaum describes is observed.

**Comment by harbaum** [comment]
The fix:
			mask_byte = MASK_OUT_ABOVE_8(mask_base) << (8-offset);
fixes all of own my own cases. This fix is needed in all bitfield instructions.

**Comment by rb6502** [comment]
Thanks.  I've applied the analogous fix to all the bitfield instructions and verified that your test case works.  Once some build system issues are resolved in MAME I'll apply the fixes to trunk.

**Comment by rb6502** [comment]
Fix has been applied to master.  Thanks again, and let us know if you find any other m68k issues!
