### ISSUE TITLE
Solar Assault Revised (ver JAA), game title screen displayed incorrectly.

### ISSUE THREAD

**Issue by hotgraphics** [mamedev/mame#3293]
![0000](https://user-images.githubusercontent.com/37032118/36941716-1429bdea-1fb6-11e8-84aa-1440db04a187.png)
Mame 0.195 and previous versions as well, not sure how far back. The spaceship is covering the games name. See attached pic.

**Comment by angelosa** [comment]
This is not the right place to submit driver related bug reports. Head over at [MAMEtesters](http://mametesters.org) with details concerning this issue.
