### ISSUE TITLE
Exception in many drivers (bsktball.cpp, starshp1.cpp,tank8.cpp...)

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#3297]
Exception in many drivers like
bsktball.cpp
cosmic.cpp
decocass.cpp
madalien.cpp
sprint2.cpp
sprint4.cpp
sprint8.cpp
starshp1.cpp
tank8.cpp
tunhunt.cpp
ultratnk.cpp
wolfpack.cpp

Did a clean compile up to https://github.com/mamedev/mame/commit/8bd924ccd2c21bb0546209cd26635b0548108159

mame bsktball
-------------------------------------------------------------------------------------------------------------------
Exception at EIP=024ea2db (not found): ACCESS VIOLATION
While attempting to read memory at 00000000
-----------------------------------------------------
EAX=00000000 EBX=00000000 ECX=0ac56e04 EDX=0022be08
ESI=00000000 EDI=0ac56e04 EBP=ff000000 ESP=0022be00
-----------------------------------------------------
Stack crawl:
  ff000000: 024ea2db (not found)
-------------------------------------------------------------------------------------------------------------------

mame tank8
-------------------------------------------------------------------------------------------------------------------
Exception at EIP=024ea2db (not found): ACCESS VIOLATION
While attempting to read memory at 00000020
-----------------------------------------------------
EAX=00000020 EBX=00000000 ECX=0ac56b14 EDX=0022be08
ESI=00000008 EDI=00000001 EBP=ff000000 ESP=0022be00
-----------------------------------------------------
Stack crawl:
  ff000000: 024ea2db (not found)
-------------------------------------------------------------------------------------------------------------------

**Comment by ajrhacker** [comment]
Regression almost certainly occurred with 3b923d59ccb8d2d8e386392518450006f8e644fe, which thoughtlessly broke MCFG_PALETTE_INDIRECT_ENTRIES.

**Comment by MASHinfo** [comment]
Test all drivers from 1971-1981
Regression fixed: https://github.com/mamedev/mame/commit/7ede8f952d5799992977739b12051d571e443074

Thx for fixing it
