### ISSUE TITLE
How do I tell the build system to use dynamic linking for project source files?

### ISSUE THREAD

**Issue by edom** [mamedev/mame#3313]
How do I configure the build system so that it makes libjaleco.so, libtaito.so, etc. instead of libjaleco.a, libtaito.a, etc.?

Thanks.

**Comment by cuavas** [comment]
Dynamically linked driver libraries are not a supported configuration.  You may be able to get it to work in some situations by modifying the lua scripts, but we don't recommend or provide support for it.

**Comment by galibert** [comment]
It doesn't work, there's a massive rpath issue.  Fuck genie.

  OG.
