### ISSUE TITLE
Ensoniq ES5505 + ES5510 Lower volume for gunbustr.cpp, taito_f3.cpp, taitojc.cpp

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#3314]
I play the gunbustr.cpp, taito_f3.cpp, taitojc.cpp has lower sound for gunbustr.cpp, taito_f3.cpp, taitojc.cpp games happened in 0.195, and Riding Fight, Ring Rage has crashes after TAITO Logo.

Happened in:
https://github.com/mamedev/mame/commit/4aa6f2a3429868945510181c1415885d97852ca8

**Comment by angelosa** [comment]
This is not the right place to submit driver related bug reports. Head over at [http://mametesters.org/](MAMEtesters)
