### ISSUE TITLE
War The Final Assault Graphics Corruption

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#3315]
I play the War The Final Assault has Graphics Corruption since 0.193.

0.192 Good
https://i.imgur.com/65z3VEQ.png
https://i.imgur.com/oBZv1UU.png

0.193 Bad
https://i.imgur.com/zCAhAD0.png
https://i.imgur.com/fqmaTq0.png

**Comment by angelosa** [comment]
This is not the right place to submit driver related bug reports. Head over at [MAMEtesters](http://mametesters.org) with details concerning this issue.
