### ISSUE TITLE
CARS 2 Laptop - incorrect software list?

### ISSUE THREAD

**Issue by VedsaGolfer** [mamedev/mame#3316]
cars2lap (aka CARS 2 Laptop) was made in 2012, but it lists cartridges from before the year 2000. Why are these cartridges listed? Additionally, from reading user experiences, I don't even think this device supports cartridges at all. Please look into this and let me know if this system does, in fact, support the cartridges listed in the software list (such as Allgemeinwissen II, Fantasie-Trivia, etc.)

**Comment by Osso13** [comment]
cars2lap doesn't have any software list attached anymore. It probably only had one because it used to share the same machine config as the prestige.
Anyway this can be considered fixed, closing.
