### ISSUE TITLE
Dragon World 2, Dragon World 3 Bugs

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#3326]
Dragon World 2 has a random hangs for Select screen and after fail stage.
i.imgur.com/6qBKzZw.png
i.imgur.com/b9kqhj5.png

Save State as Select screen and fail stage:
https://mega.nz/#!X1VG0ABD!j8MSxjJrpMt3SRkP97gEPNXtq0nq-1SVkmUNaQ0SThg

Also Dragon World 3 has a hang after continue and has black screen After Stage 24 for Dragon World 3 / Chuugokuryuu 3 Special (ver. 106), Dragon World 3 / Chuugokuryuu 3 Special (ver. 105) sets.
https://i.imgur.com/EzALcTO.png
https://i.imgur.com/xw8wgz5.png

Save State as Stage 24 Completed:
https://mega.nz/#!nlFzUZaC!p3WVs66yNelwOddIpkOnLHKp-lafWud5hFb77b4j0iA

**Comment by DavidHaywood** [comment]
this is not Mametesters.

**Comment by MooglyGuy** [comment]
Haze is correct, emulation issues should be submitted to MAMETesters, not here.

**Comment by rb6502** [comment]
I keep seeing Haze claim that, but that ain't actual MAME policy.  Also, this is probably the best-written bug report you will ever get in your life.
