### ISSUE TITLE
smary - parent, or clone?

### ISSUE THREAD

**Issue by VedsaGolfer** [mamedev/mame#3327]
Is there a reason why Super Mary (smary) is a parent and not a clone? From what I can tell, it's a simple hack of Super Mario Bros, meaning it should probably be marked as a clone of SMB. Is there a reason why this is marked as a parent in the NES software list?

**Comment by DavidHaywood** [comment]
should almost certainly be set as a clone, likely just an oversight.

**Comment by DavidHaywood** [comment]
this has been set as a clone
