### ISSUE TITLE
dc: duplicate disc name "dreamkey (euro)"

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#3328]
Both `dreamkey` and `dreamkey` have the same disc name `dreamkey (euro)`. Please change one of them. Thanks.

**Comment by cuavas** [comment]
We don't support storing CHDs loose in the top-level folder - place the CHDs in folders named for the software items.  MAME searches there for backwards compatibility, but it's not guaranteed to produce useful results.
