### ISSUE TITLE
San Francisco Rush The Rock, Vapor TRX freezes

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#3335]
Vapor TRX has random freezes at Waiting for Other Players after select vehicle.
http://i.imgur.com/oVYeO2d.png
San Francisco Rush The Rock has random freezes at Waiting for Other to choose after select transmission.
http://i.imgur.com/hBjdABa.png

Save State as Waiting for Other Players after select vehicle screen and Waiting for Other to choose after select transmission screen :
https://mega.nz/#!2wdHWYyQ!ntt5VGbeJqqrkAVS_wWqi-HfYwXcTeiR0feNZOm4SQc
https://mega.nz/#!ztkigDRb!hxcMuQ0ycMbVD-17wiMDBMRnRhuVYI8hVPRCg4jtBi4

**Comment by tedgreen99** [comment]
I believe that this issue has been fixed. Closing.
