### ISSUE TITLE
Add new Lagless VSYNC ON Algorithm developed by Blur Busters

### ISSUE THREAD

**Issue by mdrejhon** [mamedev/mame#3344]
An algorithm for a [tearingless VSYNC OFF that creates a lagless VSYNC ON](https://www.blurbusters.com/blur-busters-lagless-raster-follower-algorithm-for-emulator-developers/
).

An approximate synchronization of the real-world raster to the emulated raster, with a forgiving jitter margin (<1ms).

Essentially, a defacto rolling-window scanline buffer achieved via high-buffer-swap-rate VSYNC OFF (redundant buffer swaps) -- with the emulator raster scanning ahead of the realworld raster, with a sufficient padding margin for performance-jittering making scanline-exact unnecessary -- just approximate raster sync (within ~0.1ms to ~0.2ms pratical with C/C++/asm programming).

There are raster-polling functions on some platforms (e.g. [RasterStatus.ScanLine](https://msdn.microsoft.com/en-us/library/windows/desktop/bb295964(v=vs.85).aspx) as well as [D3DKMTGetScanLine()](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmthk/nf-d3dkmthk-d3dkmtgetscanline) ...) to let you know of the real-world raster.  (Other platforms may need to extrapolate based on time intervals between VSYNC heartbeats).  This can be used to synchronize to the emulator's raster within a rolling-window margin.  

Simplified diagram:
![Lagless VSYNC ON](https://www.blurbusters.com/wp-content/uploads/2018/03/EmulatorRasterFollowerAlgorithm.png)

Long Explanation:
https://www.blurbusters.com/blur-busters-lagless-raster-follower-algorithm-for-emulator-developers/

This is a 1/5th frame version, but in reality, frame slices can be as tiny as 1 or 2 scanlines tall - or a few scanlines tall, computer-performance-permitting.

Tests show that I successfully can do roughly 7,000 redundant buffer swaps per second (2 NTSC scanlines) in high level garbage-collected C# programming language of 2560x1440 framebuffers on a GTX 1080 Ti.

With proper programming technique, darn near 1:1 sync of real raster to virtual raster is possible now.  But exact sync is unnecessary due to the jitter margin and can be computed (to within ~0.5-1ms margin) from an extrapolation between VSYNC timings if the platform has no raster-scanline register available.

* Only ~10% overhead added to CPU.
* Tearing-less VSYNC OFF: Lagless VSYNC ON
* As long as emulated raster stays ahead of real raster, the black part of frame never appears 
(or just use previous frame in place of black, to reduce artifact risk)
* Same number of pixels per second.
* Still emulating 1:1 emulated CPU.
* Still emulating the same number of emulator rasters
* Still emulating the same number of emulator frames per second (60 fps).
* Performance can jitter safely in the frame-slice height area, so perfect raster sync not essential.
* Lagless VSYNC ON achieved via ultra-high-buffer-swap-rate VSYNC OFF
* It’s only extra buffer swaps mid-raster (simulating a rolling-window buffer)

Even C# programming was able to do this within a ~0.2-0.3ms jitter margin, except during garbage-collection events (which causes brief momentary surge of tearing artifact).

But C++ or C or assembler would have no problem, and probably can do it within <0.1ms -- permitting within +/- 1 scanline of NTSC (15.6 KHz scan rate).  Input lag will be roughly equivalent to ~2x the chosen jitter margin you choose -- but if your performance is good enough for 1-emulated-scanline sync, that's literally 2/15625 second input lag (less than 0.2ms input lag) -- all successfully achieved with standard Direct3D or OpenGL APIs during VSYNC OFF operation for platforms that gives you access to polling the graphic's card current-raster register.    The jitter margin can be automatic-adaptive or in a configuration file.

Can be made compatible with HLSL (but larger jitter margin will essential, e.g. 1ms granlarity rather than 0.1ms granularity) since you're forcing the GPU to continually reprocess HLSL.  A performance optimization is that one could modify the HLSL to only process frameslice-by-frameslice worth), but this would be a difficult rearchitecturing, I'd imagine.

Most MAME emulators emulate graphics in a raster-based fashion, and would be compatible with this lagless VSYNC ON workflow, with some minor (eventual, long-term) architectural changes to provide the necessary hooks for mid-frame busywaiting on realworld raster + mid-frame buffer swaps.

To read more about this algorithm and its programming considerations, see https://www.blurbusters.com/blur-busters-lagless-raster-follower-algorithm-for-emulator-developers/

**Comment by mdrejhon** [comment]
This is also called "beam racing".

It's currently used in some applications like VR:
https://www.imgtec.com/blog/reducing-latency-in-vr-by-using-single-buffered-strip-rendering/

That article has some neat animated graphics at low granularity (4 frameslices) that will help make it easier to understand the concept of beam-racing technique of using ultra-high-flip-rate VSYNC OFF to achieve a darn-near-lagless VSYNC ON with as little as two-scanline raceahead (single-scanline frameslices) of virtual raster versus real raster.

**Comment by rb6502** [comment]
This would dramatically degrade the performance of post-processing shaders, it would break GSync and FreeSync, and it's completely incompatible with our goal of eventually rasterizing polygonal games on the GPU.  So it's an easy "no".

**Comment by mdrejhon** [comment]
Good points raised, but:

**It's already implemented as an optional mod to MAME**

An experimental implementation for MAME:
https://forums.blurbusters.com/viewtopic.php?f=10&p=31750#p31750

**It's more portable than you think: Scanline Polling does not need real scanline register**

Use **Linux** Modeline or **Windows** QueryDisplayConfig() to get the exact horizontal scan rate AND the Vertical Total and subtract vertical resolution from it to get the size of VBI in number of scanlines. With these two numbers (VBI size divided by horizontal scan rate), you can get the exact VBI time to the sub-microsecond on any graphics card. By knowing your computer's exact VBI size to the microsecond (and fortunately using standard Windows API -- it works!) it is possible to begin beam racing only a few scanlines ahead of a real raster. Incidentially, for platforms that don't give you a raster but give you a VBI heartbeat -- this can successfully extrapolate the predicted raster value (to single-NTSC-scanline accuracy) from just knowing (A) Vertical Total, (B) Vertical Resolution, and (C) VSYNC heartbeat.

**Compositing performance**

Some graphics cards have incredibly high compositing performance now, when running uncapped, some MAME games composite HLSL effects at 600+ frames per second!  Compositing performance will still work with a lower granularity (e.g. 10 tiles or 20 tiles per refresh cycle).  

Remember, today's iPhones are blitting insane number of pixels and the graphics bandwidth is continually increasing. Compositing performance would eventually not be an issue, especially if you subdivide the screen by only tenths.

I recall that MAME once refused HLSL.  Now, it's part of HLSL.  The same may happen to realtime beam chasing.  MAME doesn't necessarily need a GPU to run, but a GPU is now recommended.

**It can be an optional feature**

Real time beam chasing can be an optional feature, and only a feature available to raster-based game modules.  You have modules that only enable themselves for certain games -- e.g. the 6502 module.   The raster-chaser module could be an optional module.

I have the programming concept in mind and it's much simpler than you think. :D

**Comment by MooglyGuy** [comment]
What RB is saying, albeit cryptically and a little bit too bluntly, is that the one graphics programmer on the team - me - has no desire to implement this feature request, as he's got quite a lot of non-graphics-related things on his plate already.

If you code with the same level of alacrity with which you pitch this technology, then we all eagerly await your pull request. But no level of salesmanship is going to interest me in spending the rather considerable amount of time necessary to implement this in an appropriately OS-agnostic, platform-agnostic, and efficient way.

**Comment by rb6502** [comment]
But that's not all I'm saying.  Calamity has implemented this for GroovyMAME and it breaks every driver that doesn't support partial updating, which is most of them.

**Comment by mdrejhon** [comment]
MooglyGuy

> What RB is saying, albeit cryptically and a little bit too bluntly, is that the one graphics programmer on the team - me - has no desire to implement this feature request, as he's got quite a lot of non-graphics-related things on his plate already.

Fair enough!  I'm talking to a few (eager ones) about the possibility of a small open-source cross-platform beam chasing library for any "VSYNC OFF" compatible API to hide all the mess.  There is some code in Blur Busters Strobe Utility I'm donating to the cause.  In a couple years, hopefully it will gradually lower the complexity bar for VR/emu/etc devs.  

> (Also, Calamity told this guy to stop bothering us and you see how well that worked).

Sorry, mail crossed each other.  Calamity posted that message after my last post (timestamps are in different timezones).   I won't bother you anymore; apologies.  You do a great job!

**Comment by mdrejhon** [comment]
Just to update everyone, the ghost is me.

I converted my account from personal to business, and it ghosted my previous username.  Ouch.  Oh well.  But I'm the original creator of this thread.
