### ISSUE TITLE
Build errors on src/devices/cpu/saturn/saturn.hxx...

### ISSUE THREAD

**Issue by zx70** [mamedev/mame#3345]
Compiling src/devices/cpu/saturn/saturn.cpp...
In file included from ../../../../../src/devices/cpu/saturn/saturn.cpp:84:0:
../../../../../src/devices/cpu/saturn/satops.hxx: In member function 'void saturn_device::saturn_exchange(int, int, int, int)':
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_exchange(int left, int begin, int count, int right)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function 'void saturn_device::saturn_copy(int, int, int, int)':
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_copy(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function 'void saturn_device::saturn_or(int, int, int, int)':
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_or(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function 'void saturn_device::saturn_and(int, int, int, int)':
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_and(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
cc1plus.exe: all warnings being treated as errors
make[2]: *** [optional.make:16483: ../../../../mingw-gcc/obj/x32/Release/src/devices/cpu/saturn/saturn.o] Error 1
make[1]: *** [Makefile:94: optional] Error 2
make: *** [makefile:1020: windows_x86] Error 2

**Comment by zx70** [comment]
On my personal build I used a workaround to skip the problem:

#pragma GCC diagnostic ignored "-Wstrict-overflow"

**Comment by happppp** [comment]
https://github.com/mamedev/mame/issues/2426
