### ISSUE TITLE
Build errors on 3rdparty/sqlite3/sqlite3.c

### ISSUE THREAD

**Issue by zx70** [mamedev/mame#3349]
Compiling 3rdparty/sqlite3/sqlite3.c...
In function 'vdbePmaReadBlob.part.307',
    inlined from 'vdbePmaReadBlob',
    inlined from 'vdbePmaReadVarint.part.308' at ../../../../../3rdparty/sqlite3/sqlite3.c:85435:12,
    inlined from 'vdbePmaReadVarint',
    inlined from 'vdbePmaReaderNext' at ../../../../../3rdparty/sqlite3/sqlite3.c:85546:8:
../../../../../3rdparty/sqlite3/sqlite3.c:85392:5: error: 'memcpy': specified size between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]
     memcpy(p->aAlloc, &p->aBuffer[iBuf], nAvail);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'vdbePmaReadBlob.part.307',
    inlined from 'vdbePmaReadBlob',
    inlined from 'vdbePmaReadVarint.part.308' at ../../../../../3rdparty/sqlite3/sqlite3.c:85435:12,
    inlined from 'vdbePmaReadVarint',
    inlined from 'vdbePmaReaderInit.constprop' at ../../../../../3rdparty/sqlite3/sqlite3.c:85583:8,
    inlined from 'vdbeMergeEngineLevel0' at ../../../../../3rdparty/sqlite3/sqlite3.c:87159:8:
../../../../../3rdparty/sqlite3/sqlite3.c:85392:5: error: 'memcpy': specified size between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]
     memcpy(p->aAlloc, &p->aBuffer[iBuf], nAvail);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[2]: *** [sqlite3.make:278: ../../../../mingw-gcc/obj/x32/Release/3rdparty/sqlite3/sqlite3.o] Error 1
make[1]: *** [Makefile:61: sqlite3] Error 2
make: *** [makefile:1020: windows_x86] Error 2

**Comment by zx70** [comment]
On my local build I used the following workaround:
#pragma GCC diagnostic ignored "-Wstringop-overflow"

**Comment by zx70** [comment]
On my local build I used the following workaround:

#pragma GCC diagnostic ignored "-Wstringop-overflow="

**Comment by zx70** [comment]
The workaround I used on my local build:

#pragma GCC diagnostic ignored "-Wstringop-overflow="

**Comment by zx70** [comment]
I see something similar was already inserted for Visual C:
#if defined(_MSC_VER)
#pragma warning(disable : 4054)
#pragma warning(disable : 4055)
#pragma warning(disable : 4100)
#pragma warning(disable : 4127)
#pragma warning(disable : 4130)
#pragma warning(disable : 4152)
#pragma warning(disable : 4189)
#pragma warning(disable : 4206)
#pragma warning(disable : 4210)
#pragma warning(disable : 4232)
#pragma warning(disable : 4244)
#pragma warning(disable : 4305)
#pragma warning(disable : 4306)
#pragma warning(disable : 4702)
#pragma warning(disable : 4706)
#endif /* defined(_MSC_VER) */

**Comment by rb6502** [comment]
We are not mind readers.  You don't say what compiler, OS, or anything you're using.

**Comment by zx70** [comment]
:)    I'm on Windows,  I picked the pre - built msys package,  compiler is gcc 7.2.0

**Comment by zx70** [comment]
My suggestion:

#ifndef SQLITE_MSVC_H
#define SQLITE_MSVC_H

**#if defined(__GNUC__) && (__GNUC__ > 6)
#pragma GCC diagnostic ignored "-Wstringop-overflow="
#endif**

#if defined(_MSC_VER)
(...)

**Comment by zx70** [comment]
My suggestion:

#ifndef SQLITE_MSVC_H
#define SQLITE_MSVC_H

**#if defined(\_\_GNUC__) && (\_\_GNUC__ > 6)
#pragma GCC diagnostic ignored "-Wstringop-overflow="
#endif**

#if defined(_MSC_VER)

**Comment by cuavas** [comment]
It's a third-party library and the problem seems to be a compiler bug (i.e. not in the code being compiled). Please try to find a minimal test case and report it to the msys64 team. Suppressing the warning doesn't fix anything.
