### ISSUE TITLE
mame -validate hangs on s390x and arm64

### ISSUE THREAD

**Issue by jmallach** [mamedev/mame#3371]
0.195, built on Debian sid (gcc 7.3)

MAME builds correctly, but our check target tries to run mame -validate. This has stopped working, and on at least these two architectures, it now just sucks CPU until killed. strace shows nothing. Both architectures use the C fallback code instead of native assembler.

Attached is a backtrace and a disassembly of a generated core file on s390x.

[disassembly.txt](https://github.com/mamedev/mame/files/1833616/disassembly.txt)

**Comment by ajrhacker** [comment]
Have you tried adding the -verbose flag? If a particular driver is causing -validate to hang, that should show output stopping just before it.

**Comment by cuavas** [comment]
It's not in a particular driver, it's in `validity_checker::validate_inlines()` - it's probably a bug in our relatively poorly-tested C++ fallback code, since we have intrinsics/assembly for our main supported platforms.  For s390x it's actually compiled something to an infinite loop:

```
   0x0000000124d8d4c0 <+2208>:  je      0x124d8d4d0 <_ZN16validity_checker16validate_inlinesEv+2224>
   0x0000000124d8d4c4 <+2212>:  larl    %r2,0x126f2cdb2
   0x0000000124d8d4ca <+2218>:  brasl   %r14,0x1252aa3a8 <_Z16osd_printf_errorPKcz>
=> 0x0000000124d8d4d0 <+2224>:  j       0x124d8d4d0 <_ZN16validity_checker16validate_inlinesEv+2224>
   0x0000000124d8d4d4 <+2228>:  ltr     %r1,%r1
   0x0000000124d8d4d6 <+2230>:  jhe     0x124d8cd38 <_ZN16validity_checker16validate_inlinesEv+280>
```

That's not going to ever complete.  I'll try to find some time to see if I can work out what it's trying to do there.

**Comment by cuavas** [comment]
According to @DopefishJustin, the asm.js build (which uses the C fallbacks) hangs on `-validate` as well.  After a bit of reading, it seems the compiler has optimised the C fallback for `count_leading_zeros` to an infinite loop with no side-effects.  There's no function epilogue or anything.

**Comment by cuavas** [comment]
Should be fixed in 418bc70cfa3b293cdfdcdefcbd6ea6aed60cd69a

**Comment by DopefishJustin** [comment]
That fixes the asm.js hang.

**Comment by cuavas** [comment]
Closing since it should be fixed across all platforms - @jmallach please reopen if it's not fixed on S/390, ARM, or AArch64.

**Comment by jmallach** [comment]
dpkg-deb: building package 'mame' in '../mame_0.195+dfsg.1-1_s390x.deb'. :tada: 

Thanks for the prompt fix. A build has also finished for mips, and it failed in the same way as expected.
