### ISSUE TITLE
Xerox 820 disk format

### ISSUE THREAD

**Issue by zx70** [mamedev/mame#3375]
I recently tested the X820 implementation and I noticed that in the base configuration the Shugart SA-400 disk is configured to support 35 tracks only:

static SLOT_INTERFACE_START( xerox820_floppies )
	SLOT_INTERFACE( "sa400", FLOPPY_525_SSSD_35T ) // Shugart SA-400
        (...)

The odd thing is that all the SSSD disk images I could find online are for 40 tracks drives, and make MAME crash.
Then I found "Servicing your Personal Computer" book:
"The first mini-floppy disk drive to gain popularity was the SA400 from Shugart Associates.  This 35 (or 40) track drive provides an unformatted capacity of 125K bytes in single density (...)

I tried to rebuild MAME by changing the "sa400" configuration to FLOPPY_525_SSSD, and the disk images I could find work perfectly..    should it be an extra interface variant, an odd coincidence on all the disk images dumps, or simply a bug requiring to be fixed ?    Feeding the wrong disk format at the moment crashes MAME horribly..

**Comment by zx70** [comment]
http://www.vcfed.org/forum/archive/index.php/t-45699.html
just to add one more reference:   '90K image: Xerox 820 (40 tracks total, 3 sys-tracks, 1K block size, 1 directory block)'

**Comment by rb6502** [comment]
Go ahead and add an "sa400_40" or similar with 40 tracks for applications that need it.

**Comment by zx70** [comment]
I think I found extra docs about the earlier Xerox 820 (page 10-36):
http://www.bitsavers.org/pdf/xerox/820/9R80240_820_Information_Processor_CPM_2.2_Manual_Aug81.pdf

DISK FORMAT 
The XEROX 820 is equipped with two (2) compatible Shugart SA400L (5~") drives, 
or two (8") Shugart SA800 drives. 
The disks for the SA400L (5~") drives are initialized in a CROMEMCO format, 
and the disks for the SA800 (8") disks are initialized in an IBM 3740 format. 
A format is divided into three (3) parts, field A, field B, and field C. 
Field A is written at the start of each track known as the preamble. 
Field B is written once for each sector which consists of a gap between sectors, 
ID fields, and a data field. 
Field C is written at the end of each track and is known as a  postamble. 

SYSTEM COMPONENTS 
The XEROX 820 disks are initialized in the following formats: 
Parameter                             8"           5-1/4"
Tracks                                   77          40 
Sectors                                  26          18 
Bytes/Sector                          128        128 
# of Reserved Track for OS     2            3 
Disk Capacity                         241K      81K 

So the HW differences on the Shugart floppy drives are identified by the model number, SA400 (35 tracks),  SA400L (40 tracks).
I read somewhere else that the SA400L models were supposed to be double sided, but the 820 manual states otherwise.   I guess that both the variants existed, since tha SA400 was a long living components (since 1976).

**Comment by kossow** [comment]
On 3/23/18 2:09 AM, Stefano wrote:
> I think I found extra docs about the earlier Xerox 820 (page 10-36):
> http://www.bitsavers.org/pdf/xerox/820/9R80240_820_Information_Processor_CPM_2.2_Manual_Aug81.pdf

there were several versions of the 820 with either 8" or 5" drives

if you're getting into CP/M floppy formats, there are a couple of very long format lists out there.

**Comment by zx70** [comment]
yes, I already ran into a bug with the 8 inches formats,  I'm trying to figure out what's going on. . atm I noticed that the td0 format support is surprisingly simplified,  I'm impressed that it can do already so much.  If my improvements will help booting something more,  then I'll dare to propose another pull

**Comment by zx70** [comment]
btw this issue as I opened it is solved
