### ISSUE TITLE
Musashi/M68k: Pack/unpk memory byte order is wrong

### ISSUE THREAD

**Issue by harbaum** [mamedev/mame#338]
Pack/unpk have the wrong byte order for the uncompressed word being read/written from/to memory.

The following code runs through on uae, but fails on Musashi

	move.l  #testword3+2,a0
	move.l  #testword4+1,a1	
	move.w	#$0102,testword3       ; input test word
        pack    -(a0),-(a1),#$0000
	
	cmp.b	#$12,testword4             ; musashi has stored $21, so this comparison fails
	bne	fail
	
	move.l  #testword4+1,a0
	move.l  #testword3+2,a1
	unpk    -(a0),-(a1),#$0000

	cmp	#$0102,testword3                ; this word is correct again, so unpk "reverts" the error again
	bne     fail

The pack/unpk versions operating on registers have been verified to be ok.

A real life test for this is the "LED display" in the Amiga AGA game "SlamTilt". The pinball led display is messed up if pack/unpk is broken.

**Comment by rb6502** [comment]
Thanks again!  Would it be possible to list the hex opcodes for the setup (just the 3 MOVEs and the PACK)?  I don't have a 68k assembler handy :)

**Comment by harbaum** [comment]
This time ram is at $10100++, hence:

00000156   207c00010102                 MOVEA.L #65794,A0
0000015c   227c00010105                 MOVEA.L #65797,A1
00000162   33fc010200010100             MOVE.W  #258,$00010100.L
0000016a   83480000                     PACK    -(A0),-(A1),#0
0000016e   207c00010105                 MOVEA.L #65797,A0
00000174   227c00010102                 MOVEA.L #65794,A1
0000017a   83880000                     UNPK    -(A0),-(A1),#0

**Comment by rb6502** [comment]
Thanks, fixes have been applied to MAME trunk.  My understanding is that this issue reporter may be repurposed soon for other uses, so please email me directly at messdrivers [at] gmail [dot] com with any further m68k problems you discover.
