### ISSUE TITLE
3 MAME Errors

### ISSUE THREAD

**Issue by jimdeprado** [mamedev/mame#3504]
Hello, I am getting an intermittant error while running MAME.  The errors, I get are below:

- Unable to create the Direct3D device (8876086C)
- Unable to initialize Direct3D 9
- Fatal error: Unable to complete window creation

I have tried updating my video drivers and Direct3D drivers, but nothing has changed.  The problem went away for a few weeks, but has returned.  I was playing MAME on Saturday, but when I went to load a game on Monday, I got the errors again.
I have a Surface Pro 4 with an Intel i5, with 8GB of RAM.  I am running Windows 10 Pro, 64 Bit, version 1709, OS Build 16299.371.  I have an Intel Graphic HD 520 card with 4 MB of memory.  I have included the first two screens from dxdiag.
Any help would be greatly appreciated.
Thanks, 
Jim 
![image](https://user-images.githubusercontent.com/38884572/39474501-5222e240-4d22-11e8-8d2e-af30b4caccc9.png)
![image](https://user-images.githubusercontent.com/38884572/39474529-6c6cebf0-4d22-11e8-909d-d2816c85ac2f.png)

**Comment by rb6502** [comment]
Have you installed the DirectX 9 end-user runtime?

**Comment by jimdeprado** [comment]
I've installed a bunch of things.  Let me try that and I'll let you know.  Thanks!
Jim

**Comment by jimdeprado** [comment]
I am having trouble installing DirectX 9 end-user runtime.  I found the file on Microsoft.com, but when I download it, it gives me a generic runtime installer.  When I run the installer, it says I have the most recent version.  Is there a way to download and install DirectX 9 only?
Thanks, 

Jim

**Comment by Tafoid** [comment]
In particular, you'll want the non-web based installer version, the one you can install offline:
https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by Robbbert** [comment]
Nothing fiurther heard, assumed ok. Closing.
