### ISSUE TITLE
New version not compile

### ISSUE THREAD

**Issue by lhm12520** [mamedev/mame#3539]
Environment：
OS: mac os high sierra, 10.13.4
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0

I want to build in android,
Paramaters to compile :
mark android-arm64

then attempt and crash a BUG:

/Users/liuhongmin/Public/Android/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: error in ../../../../../android-project/app/src/main/libs/arm64-v8a/libSDL2.so(.eh_frame); no .eh_frame_hdr table will be created.
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../../../../android-project/app/src/main/libs/arm64-v8a/libmain.so] Error 1
make[1]: *** [mame] Error 2
make: *** [android-arm64] Error 2
Macintosh:mame liuhongmin$ gcc version
clang: error: no such file or directory: 'version'
clang: error: no input files

**Comment by Robbbert** [comment]
Is this still a problem?

**Comment by Robbbert** [comment]
Nothing heard; closing.
