### ISSUE TITLE
Moving files has obscured the MESS project commit history

### ISSUE THREAD

**Issue by felipesanches** [mamedev/mame#354]
We just lost a whole bunch of the project's history with the recent commit pushed by @mmicko  (https://github.com/mamedev/mame/commit/1fc48ce120a376c288daeeed98daccecf1b60d7b). It seems to me that this bulk change should have been performed with the git-mv command to that the history of commits of each file would be preserved.

This can be seen by looking at the commit history of any of the older mess drivers and noticing that now we only see a single commit there. Look at this one as an example: 
https://github.com/mamedev/mame/commits/master/src/mame/drivers/ibmpc.c

Previously there used to be a much richer development history as we can see here:
https://github.com/mamedev/mame/commits/5d1376e27ebadb5ced8a6879c3e15bf2006ba871/src/mess/drivers/ibmpc.c

History is still there (it is not ***really*** lost) but it is certainly hidden, which is not optimal. Isn't there a way for file moves in git to carry the commit history of a renamed file?

**Comment by felipesanches** [comment]
@mmicko just told me that git can still access such commit history with a command like this:
git log --follow src/mame/drivers/ibmpc.c

But GitHub does not seem to use it when building their commit history webinterface, which is a shame. They should definitely change this behaviour.

**Comment by mnaberez** [comment]
I sent an email to [GitHub support](https://github.com/support) with a link to this issue and asked if GitHub could show the full file history like `git log --follow` does.  This is the reply I received:

> From: James Dennes (GitHub Staff)
> Date: Thu, 01 Oct 2015 01:56:14 -0700
> Subject: Re: Web interface doesn't show file history with --follow
> 
> Hi,
> 
> I'll add a note to this suggestion on our internal Feature Request List. We don't make promises about if/when we may add features, but we appreciate the feedback.
> 
> Thanks,
> James

Since there's nothing else we can do about this for now, I'll close this issue.
