### ISSUE TITLE
DCS2 is broken

### ISSUE THREAD

**Issue by Risugami** [mamedev/mame#3571]
Some commit after 0.197 released has caused all machines using DCS2_AUDIO_2115 to fail audio initialization.

Tested machines with DCS2_AUDIO_DSIO and DCS2_AUDIO_DENVER as well and they also fail. Suspect all of DCS is broken.

**Comment by cuavas** [comment]
Which exact revision are you using?

**Comment by Risugami** [comment]
I've already fallen back to mame0197 tag where everything is working but at the time was using HEAD.

**Comment by Risugami** [comment]
Okay just checked out master at a8b6d4cd95f856f4dc178e1c99ea4e1446236035, the current HEAD. Running MSYS with gcc 5.3.0 I ran "make SOURCES=src/mame/drivers/seattle.cpp REGENIE=1 -j5" and it ran fine so either a recent commit fixed it or just running "make" breaks it. Here's what it was doing https://i.imgur.com/MaZ1g0m.png

**Comment by Osso13** [comment]
Nice, thanks for confirming.
Probably fixed by: https://github.com/mamedev/mame/commit/b9cc6cc8939a7bfb9169e127ccf45b4485f648db

**Comment by cuavas** [comment]
>I've already fallen back to mame0197 tag where everything is working but at the time was using HEAD.

Reports without a revision hash are pretty much useless when things are moving as fast as they are.  `HEAD` is not a revision hash, it just means it's was tip of branch when you fetched, which could be any time.
