### ISSUE TITLE
Build errors in sqlite3.c

### ISSUE THREAD

**Issue by drencorxeen** [mamedev/mame#3606]
I am currently getting build errors in sqlite3.c when trying to build the current bleeding edge repo on Raspbian Stretch on a Raspberry Pi 3 B+.
`In function ‘vdbePmaReadBlob.part.323’,
    inlined from ‘vdbePmaReadBlob’,
    inlined from ‘vdbePmaReadVarint.part.324’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85435:12,
    inlined from ‘vdbePmaReadVarint’,
    inlined from ‘vdbePmaReaderNext’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85546:8:
../../../../../3rdparty/sqlite3/sqlite3.c:85392:5: error: ‘memcpy’: specified size between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]
     memcpy(p->aAlloc, &p->aBuffer[iBuf], nAvail);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘vdbePmaReadBlob.part.323’,
    inlined from ‘vdbePmaReadBlob’,
    inlined from ‘vdbePmaReadVarint.part.324’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85435:12,
    inlined from ‘vdbePmaReadVarint’,
    inlined from ‘vdbePmaReaderInit.constprop’ at ../../../../../3rdparty/sqlite3/sqlite3.c:85583:8,
    inlined from ‘vdbeMergeEngineLevel0’ at ../../../../../3rdparty/sqlite3/sqlite3.c:87159:8:
../../../../../3rdparty/sqlite3/sqlite3.c:85392:5: error: ‘memcpy’: specified size between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]
     memcpy(p->aAlloc, &p->aBuffer[iBuf], nAvail);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`

**Comment by Tafoid** [comment]
Try using **NOWERROR=1** and **REGENIE=1** added to your make to attempt to build through those parts.  Of course, be sure to add **-k** which continues your compile until nothing else can compile, if you don't already have this in your make.

**Comment by rb6502** [comment]
What GCC version is this?  We build clean with 8.1.1 on Fedora bleeding-edge.

**Comment by drencorxeen** [comment]
Tried with GCC 4.9, 6.3, and 7.3

**Comment by Robbbert** [comment]
Try GCC 5.3.0 ... I can't say anything about your Pi, but it works with 32-bit on Windows.

**Comment by cuavas** [comment]
I consistently get these errors with MinGW GCC 7 and later but only for i386, the warnings don't appear for x86_64.  It's been happening for months, it's not new.  I've examined the code it's warning about, and can only conclude that it's a compiler bug affecting targets with 32-bit `size_t`.  The same issue has been reported upstream in sqlite3 and they don't have a workaround either.

**Comment by drencorxeen** [comment]
@cuavas ,
Yes but right now I have tried GCC 4.9, 5.3, 6.2, 6.3, 7.3 and with the current git repo is the only place I am getting there errors and didn't use to get the issue.  

The official release sources build fine. I have test built mame0197s, mame0196s, mame0195s, mame0194s, and mame0193s all without problems.

Until a lot of the changes started going on after the release of mame0197 is when on Raspbian Stretch and Jessie the git repo no longer builds or links correctly with those versions of GCC.  I could understand a bug in maybe one version of GCC, but all of them?

**Comment by cuavas** [comment]
The issue occurs with MinGW GCC 7 on i386 for any version of MAME, not just post-0.197, so there's definitely something weird going on there.  We haven't changed sqlite3 since MAME 0.197.   The only change that could affect it is that we're not compiling `.c` files in C++ mode nay more, so it's likely exposing a different path in the compiler.  And given my experiences with GCC over the past two decades, I'm not going to give the compiler the benefit of the doubt here.

Please show me what's actually wrong with that particular piece of code if you think this is a legitimate warning.  So far no-one has managed to do that for either MAME or upstream sqlite3.

**Comment by AnselmD** [comment]
I am compiling at windows 32 BIT 
gcc.exe (Rev1, Built by MSYS2 project) 7.4.0

Can anyone confirm, this error appears only with OPTIMIZE=3 (-O3) ?

**Comment by nexus652** [comment]
> I am compiling at windows 32 BIT
> gcc.exe (Rev1, Built by MSYS2 project) 7.4.0
> 
> Can anyone confirm, this error appears only with OPTIMIZE=3 (-O3) ?

Man, that is exactly how I solve my problem. You are a genius.

**Comment by AnselmD** [comment]
> 
> 
> > I am compiling at windows 32 BIT
> > gcc.exe (Rev1, Built by MSYS2 project) 7.4.0
> > Can anyone confirm, this error appears only with OPTIMIZE=3 (-O3) ?
> 
> Man, that is exactly how I solve my problem. You are a genius.
Hi Nexus,

maybe also this can help? I found this later and did not try:

Compiling MAME — MAME Documentation 0.205 documentation
https://docs.mamedev.org/initialsetup/compilingmame.html#known-issues

MinGW GCC 7 for Windows i386 produces spurious out-of-bounds access warnings. Adding **NOWERROR=1** to your build options works around this by not treating warnings as errors.

**Comment by nexus652** [comment]
Thanks AnselmD! Adding NOWERROR=1 works too.
