### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [mamedev/mame#3633]

**Comment by cuavas** [comment]
This isn't really something we're interested in doing as a team.  We leave packaging/distribution for the various Linux flavours to people involved with those projects.  If someone wants to build Flatpak packages for MAME, that's fine, but we're not placing any priority on doing this ourselves.

**Comment by rb6502** [comment]
I'm going to have to disagree.  Flatpak explicitly is not distro-specific and allows us to take control of some of the more annoying things that distro packagers currently do to MAME.  That said, I think it's about 6 months too early to be looking at it seriously.

**Comment by pdureau** [comment]
Hi @rb6502 We are more than 6 months later. Do you still have the same opinion about flatpak packaging? Is it time to reopen this issue?

**Comment by Firehawke** [comment]
I'm going to comment that I think this is actually something important that we SHOULD do-- some of the stuff I've seen distro packages of MAME do is incomprehensible from the user perspective and goes against things the official docs say about configuration files.

Having a baseline flatpak that works just about anywhere while following our rules on file placement would make life SO MUCH easier for both us and users.
