### ISSUE TITLE
Legendary Wings NES issues

### ISSUE THREAD

**Issue by undeadindustries** [mamedev/mame#3653]
I'm not sure this is the correct place to put bugs like this.

This issue exists on all versions of MAME I've used. on ARM and x86.

Legendary Wings, the side scrolling stages:

Somehow, the timing is off.

On real hardware, you can run into walls all you want.

On MAME, often, if you run into a wall, you will go into it a little bit, get trapped and die.

It's like the refresh or collision timing is different and screwing it up?

Thank you!

**Comment by Robbbert** [comment]
Transferred to Mame Testers: https://mametesters.org/view.php?id=7854
