### ISSUE TITLE
5000026.u18 from ibm5160 no longer needs redump

### ISSUE THREAD

**Issue by PeladoFeo** [mamedev/mame#3669]
Very special thanks to MicroCoreLabs from Vintage Computer Forum for supplying the redump!

**Comment by Robbbert** [comment]
Fantastic news. Closing.

**Comment by felipesanches** [comment]
@Robbbert, I think the issue here is that the driver still lists this ROM as a BAD_DUMP. The good dump checksums should be listed there and the BAD_DUMP should be removed.

https://github.com/mamedev/mame/blame/10e33516c853bcc4f72d15a5af36159bb0fc5fe8/src/mame/drivers/ibmpc.cpp#L472

**Comment by felipesanches** [comment]
@PeladoFeo what are the CRC and SHA1 values for the good dump?

**Comment by Lord-Nightmare** [comment]
The hashes are on minuszerodegrees' site.

**Comment by Lord-Nightmare** [comment]
fixed in 14a94c1c9075478d8acceef5d50511c689e6d7f1
