### ISSUE TITLE
[Request] Named buttons in configuration menu

### ISSUE THREAD

**Issue by CyberTacoX** [mamedev/mame#3699]
It would be **extremely** helpful to be able to have buttons & other controls in the configuration menu be labeled related to the game that's loaded. For instance, instead of "P1 Button 0", something like "P1 High Kick" instead of  would save a lot of time and experimenting when trying to set up a new control scheme. (Especially when you're doing it for multiple buttons in multiple games!)

This would also remove a hurdle for who are new to MAME.

Perhaps this could be relegated to an external database file to make it easier for the community to contribute, like cheats are?

**Comment by DavidHaywood** [comment]
this is what the 'portname' lua plugin that ships with MAME is for

although the set of example files I submitted for inclusion were rejected

**Comment by cracyc** [comment]
There's a whole bunch done at https://github.com/RalfVB/mame-portnames

**Comment by Robbbert** [comment]
Looks like this is sorted. Closing.
