### ISSUE TITLE
Crash when ini contains <UNADORNED0>

### ISSUE THREAD

**Issue by orgads** [mamedev/mame#3703]
Mame version 0.195 on debian sid.

Trying to execute kinst when my ini file contains `<UNADORNED0>` crashes due to an assertion.

This only happens if I execute mame without the game argument, and choose the game from the UI menu.

What seems to happen is that after the system is already initialized, the ini is being parsed, and calls `set_system_name("")`. This clears the system, and calls `emu_options::add_and_remove_slot_options()`, which removes all options. Then `rom_load_manager` ctor tries to find `slot_option("ata:0")`, which returns a null pointer (or asserts, if debug is enabled).

Is the parsing order different when executing a game from command-line VS from the menu?

**Comment by cuavas** [comment]
Why do you have `<UNADORNED0>` in your INI file?  This key is a "magic value" used for the first positional command-line argument.  If MAME is somehow adding it, could you give a test case to reproduce this behaviour?  If you've added it by hand, just don't do that.

**Comment by orgads** [comment]
I didn't add it myself. This ini file was probably created (or copied?) by some ancient version of mame (I have a copy of this ini file, which was created on 2011).

Now that I'm aware of the problem, I know I can just remove these lines, but it took me several hours to discover it, and it possibly affects other users.

**Comment by Robbbert** [comment]
Workaround was provided. Closing.
