### ISSUE TITLE
MIPS 3: DMULTU math bug.

### ISSUE THREAD

**Issue by bryanperris** [mamedev/mame#3718]
There have been a lot of testing against this instruction.  In the links below contain the test dumps and my working C# solution for both DMULTU and DMULT.  So far this is only a solution for any kind of interpreter, and its not the most optimized solution either.

https://github.com/PeterLemon/N64/issues/11
https://github.com/project64/project64/issues/1468

I hope this helpful for anyone working with MIPS and its 64-bit ALU.

**Comment by MooglyGuy** [comment]
Thanks for the report, Bryan! I'll have a look at it this weekend and I'll see what I can do.

**Comment by bryanperris** [comment]
Here is my improved / simplified solution: https://pastebin.com/NndY9MrJ

**Comment by tedgreen99** [comment]
Should work correctly now with latest patch.
