### ISSUE TITLE
Securing MAME for high level playing tournament sites

### ISSUE THREAD

**Issue by angelosa** [mamedev/mame#3732]
Assuming we can't add a closed source method inside the emulator itself but since it's 2018 and everyone (hopefully) is on a cabled connection we can resolve this by adding some lightweight client-server communication. 

So, the basic idea is:
1. Estabilish a connection with a remote connection, via a common secure protocol (TLS aka HTTPS for example).
2. Write ourself down an API library that gives some control over what the user is currently doing. 
This means calculating common stuff like timestamps or emulator speed but also ensuring that the player is using the expected emulator and not hampering it along the way.
3. The methods are common but the server isn't obligated to disclose its anti-cheat checks via our API. 
It is its responsibility to call our common functions during the recording process and make whatever is needed to eventually catch frauds (for example defining some specific checks for a given user after the standard ones).

This of course leads to few compromises for the end user but I guess this is the price to pay to avoid cheaters hampering the tournament sites (which gives harm to the project as well in the long run since high level players are an invaluable resource for testing and feedback).

**Comment by DavidHaywood** [comment]
I'm not sure you can secure an Open Source project in this way, eg. how is it going to ensure that the MAME build is an unmodified one? send a checksum? That needs to be in the MAME code, that can be faked in a heartbeat.

The tournament sites in question need to take a big share of the responsibility for this.  By not getting rid of known, and obvious cheaters, and by not even trying to enforce any kind of policy to use recent versions they're doing their own reputation more harm than all the Twin Galaxies scandals put together.  I'm not sure another layer of false security would achieve anything unless the actual sites attempt to clean up their acts.

In most cases it's already obvious who the cheats are.

**Comment by angelosa** [comment]
The idea is not to achieve a _perfect_ security system (that would be utopical) but making it enoughly complex that will be impratical to actually execute the most common cheating methods.

The alternative is that we can use something similar to what RZX does, or even port it altogether starting from the Spectrum driver itself then add the necessary mods for extending it
http://www.worldofspectrum.org/RZXformat.html

> For example, any emulator can correctly replay an RZX file where the Kempston mouse and the lightgun have been used - no matter if it doesn't emulate these devices at all! 

Would also be a good test for the Speccy driver itself (I don't expect these to playback correctly at current stage for obvious reasons concerning driver emulator itself).

The non-Windows binaries is yet another issue, no idea about that yet.

**Comment by angelosa** [comment]
Closing this, roughly because it doesn't belong to application layer to begin with (hint).
