### ISSUE TITLE
Kill direct_update from every driver

### ISSUE THREAD

**Issue by galibert** [mamedev/mame#383]
zx8\* is almost done.

**Comment by ajrhacker** [comment]
Not driver-specific (though the esb driver uses something very similar), but the slapstic direct-update handler in mame/machine/atarigen.cpp is one of the ugliest bits of legacy code wedged into that source file. This looks like a job for a setoffset delegate.

**Comment by startaq** [comment]
There has been some steady progress here. Things left are:

- [ ] src/devices/bus/cpc/mface2.cpp
- [ ] src/devices/bus/vcs/dpc.cpp
- [ ] src/devices/bus/vcs/rom.cpp
- [ ] src/devices/bus/vcs/vcs_slot.cpp
- [ ] src/devices/cpu/tms32031/tms32031.cpp
- [ ] src/mame/drivers/abc80x.cpp
- [ ] src/mame/drivers/atm.cpp
- [ ] src/mame/drivers/mpf1.cpp
- [ ] src/mame/drivers/mpz80.cpp
- [ ] src/mame/drivers/pentagon.cpp
- [ ] src/mame/drivers/sage2.cpp
- [ ] src/mame/drivers/scorpion.cpp
- [ ] src/mame/machine/bbc.cpp
- [ ] src/mame/machine/lisa.cpp
- [ ] src/mame/machine/ti85.cpp

**Comment by Robbbert** [comment]
This would seem to be completed?

**Comment by rb6502** [comment]
Yup, it's done.
