### ISSUE TITLE
Memorex VIS  controls missing button options.

### ISSUE THREAD

**Issue by flood404** [mamedev/mame#3832]
When trying to play secrets of Hosea Freeman on the VIS.  We need 2 more buttons to be mapped so the player can move around to different areas.   I remember the VIS has 6 buttons and it seems only the A and B buttons are working.  But nothing in options to map buttons  1,2,3 and 4 which is used in some games and software for this system.

**Comment by cracyc** [comment]
Added 1 and 2 in 2dcb1e978e520a05a2c283be97fc4dae46213cd5 .  I couldn't find 3 and 4 yet.

**Comment by flood404** [comment]
I think the buttons 3 and 4 were hardly ever used anyway.  Looking forward testing in next MAME release thanks!
