### ISSUE TITLE
gaelco3d.cpp regression, black screen.

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#3848]
MAME v0.200 (mame0200-379-ga632b01217)

During a bench run, saw that Radikal Bikers jumped 177%, turns out it's a black screen on it and the other games in the driver.  Worked in .200 release.

**Comment by ajrhacker** [comment]
This bug was introduced in a recent refactoring spree. I fixed it in e413bd767b1b63ede8079c2c3ad667342d0943a7.
