### ISSUE TITLE
[Request] Use $XDG_CONFIG_HOME and $XDG_DATA_HOME for configuration and data files

### ISSUE THREAD

**Issue by livingsilver94** [mamedev/mame#3853]
Hello!
Given how much attention [this discussion](https://www.reddit.com/r/linux/comments/971m0z/im_tired_of_folders_littering_my_home_directory) received, I'd like to bring the issue to you too.
Could you please use standard Freedesktop variables to store configuration and data files, instead of using the `.mame` directory? I'm 100% many users, including me, will benefit from a cleaner home directory.
Of course I'm talking about a Linux installation.

**Comment by rb6502** [comment]
If you create a small bash script to launch MAME with the -inipath switch you can put mame.ini anywhere on the filesystem.  MAME has always been deliberately very flexible in that regard.

Also, my Fedora 28 system does not have $XDG_CONFIG_HOME or $XDG_DATA_HOME defined.

**Comment by livingsilver94** [comment]
Yes, I know MAME is flexible about this, but in my opinion compliance to standards should come from applications, not the final user.

It's perfectly fine not to have them defined: if not set, those path must be set to the paths you [read here](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html)

**Comment by cuavas** [comment]
The trouble with standards is that there are so many to choose from.  Literally none of my systems have those variables defined, and it's not the behaviour I'd expect to see.  It also doesn't really solve anything, just moving the clutter one level deeper.

Also, I'm 100% sure a large proportion of users don't want to have to dig through hidden dotfolders in their home directory to find the configuration files for MAME.  The default behaviour of looking in the working directory and allowing override via command-line options is the least bad choice we've found over the years.
