### ISSUE TITLE
32-bit Compile Fails on Windows

### ISSUE THREAD

**Issue by Tafoid** [mamedev/mame#3867]
Windows 7 - 16GB RAM - 500+GB hard drive space remaining:

-----

make -j5 -k OPTIMIZE=3 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1 PTR64=0 NOWERROR=1 DEPRECATED=0 REGENIE=0 ARCHOPTS="-msse2 -mfpmath=sse"

-----

Compiling src/devices/cpu/tms57002/tms57002.cpp...

cc1plus.exe: out of memory allocating 29130056 bytes
optional.make:17436: recipe for target '../../../../mingw-gcc/obj/x32/Release/src/devices/cpu/tms57002/tms57002.o' failed
make[2]: *** [../../../../mingw-gcc/obj/x32/Release/src/devices/cpu/tms57002/tms57002.o] Error 1
make[2]: Target 'all' not remade because of errors.
makefile:94: recipe for target 'optional' failed
make[1]: *** [optional] Error 2
make[1]: Target 'all' not remade because of errors.
makefile:1052: recipe for target 'windows_x86' failed
make: *** [windows_x86] Error 2
make: Target 'all' not remade because of errors.

-----

I make daily binaries and this morning I could no longer create a 32-bit build (64-bit compiled without issue).  This compile string has all markers of what is needed to make it functionally the same as the release builds available at mamedev.org

**Comment by Tafoid** [comment]
It is worth noting my compile environment.  It is the 32/64-bit combo package, allowing both 64-bit and 32-bit compiling.

-----

[MINGW32] c:\mamegit\mame>gcc --version
gcc (Rev2, Built by MSYS2 project) 7.3.0

[MINGW32] c:\mamegit\mame>make --version
GNU Make 4.1
Built for x86_64-w64-mingw32

**Comment by Robbbert** [comment]
Works for me  *shrug*

 

Windows 7 – 8GB RAM – 335GB space remaining on 500GB SSD – CPU is a rather ancient i7-2600 – paging file managed by Windows and is 8173MB

 

%MINGW32%\bin\make PTR64=0 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1 DEPRECATED=0 –j4

 

GCC 5.3.0 combo package

 

Link time 3 minutes.

**Comment by Tafoid** [comment]
Fixed in 6e0bf6736a939210b75777ef9097ed778f85e4eb
