### ISSUE TITLE
MAME 0.201 issues

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#3910]
atarisy4.cpp is craching

Exception at EIP=031ea584 (not found): ACCESS VIOLATION
While attempting to read memory at 12a38020
EAX=0000c600 EBX=10200020 ECX=12a38020 EDX=0d9c1af8
ESI=0eb60020 EDI=00000340 EBP=00000001 ESP=0022c4d0
Stack crawl:
  00000001: 031ea584 (not found)

**Comment by cuavas** [comment]
Reports are useless without a revision hash.

**Comment by cuavas** [comment]
Just tested tip of release branch and it doesn't crash.

**Comment by MASHinfo** [comment]
Found the problem in the src/devices/video/poly.h change:
https://github.com/mamedev/mame/commit/99bc44a5ae588420eed6431d7f2746b6e8e322aa

Last Starfighter and Air Race (atarisy4.cpp) are craching with SCANLINES #32.
When i changed SCANLINES back to #8 the games working!

**Comment by cuavas** [comment]
It isn't crashing for me - that polygon manager change works fine for all the drivers I tested.  Either it's a local problem on your system or you're not supplying enough information.
