### ISSUE TITLE
Fix/split isa_cga, improve composite decoder

### ISSUE THREAD

**Issue by ghost** [mamedev/mame#393]
The current CGA bus emulation is a hacky driver from the days of legacy MESS, with improper coding (For example, CGA chipsets are controlled via options, when they should be seperate cards or internal non-changeable hardcoded chips), etc.

(Note: Should the video code be split from the bus driver aswell?)

The composite decoder in isa_cga also needs a complete refactor as well due to problems (colors are completely wrong and colorburst nor text artifacting is emulated right), and better decoder solutions, documentation, including schematics out there.

**Comment by Robbbert** [comment]
Account has been deleted. Closed.
