### ISSUE TITLE
[Download] [Linux] Impossible to download from the official site

### ISSUE THREAD

**Issue by Giancarmine** [mamedev/mame#3945]
The linux build download button on the official site is a 404 error

Thanks
Giancarmine

**Comment by Robbbert** [comment]
Need more information.
All the buttons I tried worked.

**Comment by LuismaSP89** [comment]
Same here, all works ok. What browser you are using? Try to use a different one.

**Comment by Giancarmine** [comment]
Resolved, only a temporary problem (i think)

Thanks for the support

**Comment by LuismaSP89** [comment]
Please, close the issue if it´s solved. (You can see the closing button in the bottom of the page, near the comment box)
