### ISSUE TITLE
svision.cpp, wrong timing

### ISSUE THREAD

**Issue by infval** [mamedev/mame#3960]
Some games have a problem with the speed of objects.
Video:
Bubble World MESS 0.152 https://youtu.be/pREEPyT2EEM?t=0
Bubble World MAME 0.201 https://youtu.be/pREEPyT2EEM?t=28
Eagle Plan MESS 0.152 https://youtu.be/pREEPyT2EEM?t=61
Eagle Plan MAME 0.201 https://youtu.be/pREEPyT2EEM?t=126

The bug is here: https://github.com/mamedev/mame/commit/2cdb153103fa94d13a53dd747985ef56ec723e7a#diff-ce212c2688966534e4eafe90ab9f47b1L153

Correct code:
```
		case 0x23: /* delta hero irq routine write */
			if (!data)
			{
				data = 0x100;
			}
			m_svision.timer1->enable(true);
			if (BIT(m_reg[BANK], 4))
				m_svision.timer1->reset(m_maincpu->cycles_to_attotime(data * 0x4000));
			else
				m_svision.timer1->reset(m_maincpu->cycles_to_attotime(data * 0x100));
			break;
```

**Comment by happppp** [comment]
Thank you, it looks like a good fix. But for source code contributions like this, please make a Pull Request.

**Comment by happppp** [comment]
here we go https://github.com/mamedev/mame/commit/f20a2a5c6dd10ef45417de5d294748ea5f819cae
