### ISSUE TITLE
Manchester Small-Scale Experimental Machine can't load snp or asm rom

### ISSUE THREAD

**Issue by yyhhrr** [mamedev/mame#3965]
The device quickload dose't work.If you load snp or asm rom like diffeqt.asm、Baby9.snp.There is no reaction.But use MESS,it works.So I think there is something wrong,may be.Sorry for poor English.

**Comment by Tafoid** [comment]
Seems like it loads and does something here (diffeqt.asm , at least my copy).
The one I like to use to test the machine is noodletimer.snp
That image loads into MAME when chosen.
[noodletimer.zip](https://github.com/mamedev/mame/files/2355364/noodletimer.zip)
mame64 ssem -quik noodletimer.snp

![noodletimer](https://user-images.githubusercontent.com/9075896/45133848-78205c00-b165-11e8-8293-05e3a01173d8.png)

**Comment by yyhhrr** [comment]
I used MAME 0.201 64-bit Windows command-line binaries from official site : https://www.mamedev.org/release.html ,and your rom noodletimer.snp ,input in command line with  mame64 ssem -quik noodletimer.snp.   still nothing happen.

**Comment by yyhhrr** [comment]
![7f3dd33cxccf6730442d8 690](https://user-images.githubusercontent.com/3608322/45140856-bca00c00-b1e6-11e8-8a32-2dcc21d6d972.png)

**Comment by Robbbert** [comment]
Works for me. Try deleting cfg\ssem.cfg and ini\ssem.ini, if they exist.

**Comment by yyhhrr** [comment]
I found after MAME 0.170,ssem didn't work.MAME0.170 works for me,my os is win 10 x64.

**Comment by Tafoid** [comment]
Multiple people have tested it and it works as expected.  I'm unsure what your situation is but I'd suggest try clearing your CFG/ssem.cfg file (if it exists) and try again.   Closing

Be sure if you are loading the image, load the example above noodletimer as it stands:  .snp if it is unzipped or .zip if it is in a ZIP container.
