### ISSUE TITLE
tstrike and darktowr crashes

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#3970]
tstrike and darktowr crashes after exit. Possible MC68705 MCU problem!

Details:
Some gfx are black in tstrike and game crash after exit:

D:\MAME>mame tstrike
Average speed: 100.58% (3 seconds)

-----------------------------------------------------
Exception at EIP=7c921e58 (not found): ACCESS VIOLATION
While attempting to read memory at 00000000
-----------------------------------------------------
EAX=0dec69c8 EBX=003e0000 ECX=00000000 EDX=00000000
ESI=0dec69c0 EDI=0dec6fd0 EBP=0022c6dc ESP=0022c6d0
-----------------------------------------------------
Stack crawl:
  0022c6dc: 7c921e58 (RtlInitializeCriticalSection+0x032b)
  0022c7b0: 7c920d5c (wcsncpy+0x02cd)
  0022c7f8: 77bfc2de (free+0x00c3)
  0c749d78: 037d0b10 (not found)

darktowr crash after exit:

D:\MAME>mame darktowr

-----------------------------------------------------
Exception at EIP=7c9211de (not found): ACCESS VIOLATION
While attempting to read memory at 00000000
-----------------------------------------------------
EAX=00000000 EBX=003e0000 ECX=0c742f90 EDX=003e0178
ESI=0c742f88 EDI=ff000000 EBP=0022c33c ESP=0022c11c
-----------------------------------------------------
Stack crawl:
  0022c33c: 7c9211de (wcsncpy+0x074f)
  0022c37c: 77bfc3c9 (free+0x01ae)
  0022c388: 77bfc3e7 (free+0x01cc)
  0022c398: 77bfc42e (malloc+0x0027)
  0000000d: 04db3f6a (not found)

------------------
Compiled MAME 0.202: https://github.com/mamedev/mame/commit/b5f4d9169441c499d8fcece95bf25dd7ed3cfda7

**Comment by DavidHaywood** [comment]
I'm going to take a stab in the dark
https://github.com/mamedev/mame/commit/d6a53357a56f1e2d1249b9e29e0ff117967b0a8b#diff-a37d0ebef312b173c5115ae873c9a20a

**Comment by Tafoid** [comment]
Wrong.  At least the crash is related to this: bb32d72c7e68d4b34a94e1250f1440394d473f7d
It messes with the palette and causes the mentioned assert in debug build for both sets.
As far as I am aware, it is known and being worked on.

**Comment by MooglyGuy** [comment]
How can a crash on *exit* possibly be related to that change, Tafoid? The black graphics I could believe as being due to it, and it will be looked into this evening, but the crash on exit I'm highly doubtful of.

**Comment by happppp** [comment]
because a non-debug build will ignore the assert?

**Comment by MooglyGuy** [comment]
@happppp So in that case, we're in agreement: It should be crashing when it tries to access the out-of-bounds palette entry, not *on exit*.

**Comment by DavidHaywood** [comment]
MAME often crashes on exit, even if the actual error is elsewhere.

So yeah, in this case, it's the palette code, corrupting memory, and that only crashing on exit.

**Comment by MASHinfo** [comment]
Test tstrike and darktowr. All working again!
https://github.com/mamedev/mame/commit/50fab6c310dc754d775d02c3f5c9da62189678b6

Report can be closed!

**Comment by MooglyGuy** [comment]
Great to hear, thanks for the report!
