### ISSUE TITLE
Brown bar in Splatterhouse attract mode.

### ISSUE THREAD

**Issue by Bullsquiddy** [mamedev/mame#3989]
![0000](https://user-images.githubusercontent.com/42082450/45389072-7aa90880-b5e0-11e8-96e7-04e86babab2d.png)

Using MAME (32 or 64-bit), the Demo/Attract mode intro to Splatterhouse produces this strange brown bar during the pictured scene. This happens regardless of renderer, and seems to have been an issue in previous versions (judging by youtube gameplay videos, and a friend of mine using .198). Occurs in every version of the game (SH1-3, World or Japan).

**Comment by DavidHaywood** [comment]
this kind of thing is normal, the brown is so dark it would be barely visible on a CRT

very unlikely to be a bug

**Comment by sreuter** [comment]
Happens on my original board, too :)

**Comment by angelosa** [comment]
Splatter House is pretty known to have all kinds of pseudo-artifacts like this, which are mitigated by the CRT gamma.
Closing.
