### ISSUE TITLE
How do you connect emulated RS232 port to COM port?

### ISSUE THREAD

**Issue by TedThompson** [mamedev/mame#4002]
What few references I see on the net show -null modem and -bitb socket.xxx.xxx.xxx.xxx:pppp but even this does not work and produces a file in the root directory of my mame install (windows 10). Where are the docs? Was this removed? Seems a shame that an emulated bidirectional port only dumps to a file.

**Comment by TedThompson** [comment]
Ok, I've done a bunch of headbanging and it seems it's quite simply a matter of placing 

`-bitb COM8` to connect to COM8 which was what I was after.  If anyone ever can shed more light on this feature I'd love to hear from you.  Meanwhile I've added 

`-sl2 ssc -sl2:ssc:ssc_rs232 null_modem -bitb COM8` to my command line for launching an Apple ][e emulation and I can see my typing being transmitted to COM8.

**Comment by anikom15** [comment]
Do you still have any issue? Seems like this can be closed.

**Comment by TedThompson** [comment]
I'd like some verification that I've got it right and any additional parameters that might apply if I have the devs ear (eyes)
