### ISSUE TITLE
megadrive: nvram not working for Wonder Boy in Monster World

### ISSUE THREAD

**Issue by killamegagiga** [mamedev/mame#4006]
Saving within the game does not work apparently for this game.  Sadly I found this out after 2-3 hours of playing :(

My configuration is mame 0.199 (I haven't had time to update to the latest mame, but I didn't see any changes related to this issue), machine: genesis, game: wboymw.  Browsing the megadriv.xml file I see that all the clones of this game have the same "rom_eeprom" slot so I'm guessing they all suffer the same problem.  Mame does save a 128-byte file within the nvram directory for the game but it's all 0xFF bytes.

**Comment by Osso13** [comment]
Hi,
unfortunately it is a known bug: https://mametesters.org/view.php?id=5191

**Comment by killamegagiga** [comment]
Thanks for the reply.  I wasn't aware of mametesters.org.  Now I see it buried deep in the FAQ on mamedev.org, but it would be nice if it had a more prominent place on the main site.  I suppose the double-edged sword there is all the spurious bug reports from clueless newbs like me :)

**Comment by angelosa** [comment]
Please use mametesters.org for game/system related bugs. Github issues are for structural changes/proposal in the emulator itself.
