### ISSUE TITLE
SDL numbers mouse buttons differently to Windows

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#4010]
Apparently SDL numbers mouse buttons differently in MAME to Windows.  Windows numbers the three “standard” mouse buttons 0, 2, 1 (left to right).  However, SDL numbers them 1, 2, 3 (left to right).  This results in the default right/middle mouse button mappings being reversed on OS X/Linux compared to other platforms.

This isn't necessarily a bad thing for game buttons, as the left and right mouse buttons end up on P1 button 1/2 by default, and Mac input devices are somewhat less likely to have a middle mouse button.  However it's problematic for multi-button mouse devices, as the middle and right buttons are reversed by default on OS X/Linux.

**Comment by kiall** [comment]
Oh! This could explain why the offscreen reload feature for Lightguns on Linux was so awkward to get working - I had to hack out some code to get it to work with my Aimtrak (which already internally does the 0,MAX aim for offscreen, so removing that whole piece allowed the gun to work as expected).

**Comment by cuavas** [comment]
Bit the bullet and flipped the button numbers in 68472d3d72ea4bbc545c0669348172b4e96c7b41.
