### ISSUE TITLE
Antialias, unknown option

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4022]
Linux Debian 9.5, last git build.
From the [official documentation](https://github.com/mamedev/mame/blob/master/docs/source/commandline/commandline-all.rst)

```
./mame64 -antialias
Error: unknown option: -antialias

./mame64 -noantialias
Error: unknown option: -noantialias

./mame64 -aa
Error: unknown option: -aa

./mame64 -noaa
Error: unknown option: -noaa
```

**Comment by katananja** [comment]
Looks like `-beam` also doesn't work

**Comment by cuavas** [comment]
Yeah, it's outdated.  Current core vector options are `beam_width_min`, `beam_width_max`, beam_intensity_weight`, and `flicker`.  Someone who understands the vector monitor simulation better than me would need to update this section.

**Comment by u-man74** [comment]
AFAIK, antialias is always turned on and as a option removed. It would make sense, because why you would turn it off?

**Comment by Tafoid** [comment]
Those mentioned as missing in current source have been fixed in documentation https://github.com/mamedev/mame/commit/fdb070c61d292798719e16f0b44c2f69628bde28 | https://github.com/mamedev/mame/commit/3e94624a08c7074355576021f07ef02b64d08d47
Closing
