### ISSUE TITLE
Provide a way to capture screen pixels at every frame rendering?

### ISSUE THREAD

**Issue by NaniteFactory** [mamedev/mame#4039]
Does MAME support a way (interface) to "read" all the pixel data of a frame whenever that frame draws?

I'm trying to make something like, an AI that can "see" the game through an emulator screen then do some whatever behavior,

and so I want to be able to make a callback like this pseudo-code below:

```
func onFrameAdvanced(frame) {
	// ...
	frame.getPixels();
	// ...
}
```

I know that I can hook each frame draw function call with external debuggers other than MAME, which I've been trying,

or I can simply run

`emu.register_frame_done(some_func, "frame")`

in lua console. But I just can't find a way to get those screen pixels.

I've read the docs on [luaengine](https://docs.mamedev.org/techspecs/luaengine.html), but it seems like that the document doesn't actually cover not all the API commands in lua scripting.

Could anyone kindly give me an idea on how I might be able to get that data at runtime?

Any assistance would be appreciated. Thanks in advance.

**Comment by cracyc** [comment]
Currently you can only save a shot to disk with the video:snapshot() function unless you know where the system you are looking at has it's video data in emulated ram.

**Comment by NaniteFactory** [comment]
Thanks for the comment. xD Through some debugging I eventually found where in memory the VRAM is stored and which instruction draws each pixel. I'm going to hook there for now. I think it could be even better if MAME itself provided an interface to do so. I'll leave this issue as a feature request. 😋

**Comment by rb6502** [comment]
The way MAME works there isn't necessarily a framebuffer for you to see, and for games that have them it's much more efficient to look at the tilemap and sprite VRAM.

**Comment by vadosnaprimer** [comment]
You seem to need MAME to dump the screenshot to a lua buffer instead of disk. But won't reading memory be more efficient?

**Comment by NaniteFactory** [comment]
@vadosnaprimer 

If you're working on this, thank you. 😊 For me, saving the screenshot to a buffer would also be a good solution to this issue, if it is possible, and as long as it doesn't hurt the framerate of a game emulated too much.

Currently I can directly access the process memory of MAME. Since a newbie like me don't know how things are really going on inside MAME, I had to open a process, and find out where it has its VRAM stored, then again look for where it has the game frame, sprites, etc. all that manually. Man that's a lot of code just to get one game state. xD This works fine like most of the time, but there happens to be probability that I may hit an invalid address, and I don't have an idea on how to verify whether an address of memory is valid or not.

So what I was asking for, I wish I could have a reliable (proper) method to get the frame pixels of MAME at runtime. If the lua engine could do that, it's nice.

**Comment by vadosnaprimer** [comment]
I'm not working on it. I mean [reading internal memory](https://docs.mamedev.org/techspecs/luaengine.html) of the emulated machine, like this:
```
local memory = manager:machine().devices[":maincpu"].spaces["program"]
local screenx = memory:read_u16(0x4790)
```
You'll have to use some memory search tool to find the address you want, but once you have it, you don't even need the framebuffer, let alone cases when it's corrupted. To search for an address you can use [cheatfind plugin](https://github.com/mamedev/mame/blob/master/plugins/cheatfind/init.lua) (`mame your_rom -plugin cheatfind`, then go to plugin options), debugger's [cheat search](https://docs.mamedev.org/debugger/cheats.html) (`mame your_rom -d` to open debugger), or [mame-rr](https://github.com/TASVideos/mame-rr/releases)'s ram search (Ctrl+F) that has a nice UI, but is windows-only.

**Comment by NaniteFactory** [comment]
@vadosnaprimer 

Cool, thanks a lot! I wasn't much aware of those features until now. I'll give it a try...

**Comment by vadosnaprimer** [comment]
The entire bitmap has also been available for a while, so maybe this can be closed?

```lua
manager:machine():video():pixels()
manager:machine().screens[screen_tag]:pixel(x, y)
manager:machine().screens[screen_tag]:pixels()
```
