### ISSUE TITLE
macOS: Don't force use of discrete GPU

### ISSUE THREAD

**Issue by mrpippy** [mamedev/mame#4054]
15" MacBook Pros with discrete GPUs will switch to the discrete GPU (increasing power consumption and heat) when an app creates an OpenGL context but doesn't have an `NSSupportsAutomaticGraphicsSwitching` key in the Info.plist. I was able to add this to the MAME `Info.plist` with a patch to `verinfo.py`, and it no longer switches to the discrete GPU on launch.

Are there any cases where MAME would actually want to run on the discrete GPU though? I can create a pull request for the `verinfo.py` patch, just wouldn't want to cause performance regressions for any situations where the discrete GPU performance is actually needed.

My setup: 15" MBP Late 2013 w/GT 750m, 10.13.6, SDL 2.0.7

More info on SDL and GPU switching:
https://discourse.libsdl.org/t/question-is-it-possible-to-set-sdl2-to-use-integrated-graphics-only/23929/3

**Comment by cuavas** [comment]
Using any of the popular GLSL chains (e.g. crt-geom and friends) benefits from using the discrete GPU as well.
