### ISSUE TITLE
MAME just crashes upon loading a game using "video d3d"

### ISSUE THREAD

**Issue by klaritan** [mamedev/mame#4057]
It doesn't happen when I run MAME64 (the menu), but it crashes as soon as I launch a game.

Happens on the latest release of MAME (202).

`Unable to initialize Direct3D 9
Fatal error: Unable to complete window creation
-----------------------------------------------------
Exception at EIP=00000000025f5d0c (not found): ACCESS VIOLATION
While attempting to read memory at 0000000000000000
-----------------------------------------------------
RAX=0000000000000001 RBX=0000000012145220 RCX=0000000000000000 RDX=000000000ef40000
RSI=0000000012117f50 RDI=000000000de0c6d0 RBP=000000000edd8c00 RSP=000000000edd8b80
 R8=000000000ede1500  R9=0000000000008000 R10=0000000000004970 R11=000000000edd8a50
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
-----------------------------------------------------
Stack crawl:
  000000000edd8b50: 00000000025f5d0c (not found)
  000000000edd8c30: 00000000025ac455 (not found)
  000000000edd8c90: 00000000025ac53c (not found)
  000000000edd8ce0: 00000000025ac747 (not found)
  000000000edd8dc0: 000000000257a7a7 (not found)
  000000000edd8df0: 000000000257b03d (not found)
  000000000edd8f80: 00007ffd5d4f6cc1 (CallWindowProcW+0x04c1)
  000000000edd8fd0: 00007ffd5d4f688b (CallWindowProcW+0x008b)
  000000000edd9070: 00007ffd53971b87 (Direct3DCreate9Ex+0x06a7)
  000000000edd9200: 00007ffd5d4f6cc1 (CallWindowProcW+0x04c1)
  000000000edd9260: 00007ffd5d4f699c (CallWindowProcW+0x019c)
  000000000edd92c0: 00007ffd5d500453 (IsWindowVisible+0x01a3)
  000000000edd9348: 00007ffd5feddc04 (KiUserCallbackDispatcher+0x0024)
  000000000edd9350: 00007ffd5c4023c4 (NtUserDestroyWindow+0x0014)
  000000000edd93d0: 0000000002575bdf (not found)
  000000000edd9410: 00000000025767c8 (not found)
  000000000edd9440: 0000000002574541 (not found)
  000000000edd9480: 0000000002567855 (not found)
  000000000edd94c0: 0000000002561f89 (not found)
  000000000edd9560: 0000000003e97c76 (not found)
  000000000eddf210: 0000000002613a8a (not found)
  000000000eddf4c0: 00000000026819e4 (not found)
  000000000eddf630: 0000000002681ea5 (not found)
  000000000eddf690: 0000000002611a2a (not found)
  000000000eddfe50: 0000000008c0132d (not found)
  000000000eddff20: 00000000004013f7 (not found)
  000000000eddff50: 000000000040152b (not found)
  000000000eddff80: 00007ffd5f7d3034 (BaseThreadInitThunk+0x0014)
  000000000eddffd0: 00007ffd5feb1461 (RtlUserThreadStart+0x0021)`

Using Windows 10 64bit.

**Comment by MooglyGuy** [comment]
Windows 10 does not ship with the DirectX 9 redistributable installed by default. Does installing the DirectX 9.0c redist from this link help? https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by klaritan** [comment]
> 
> 
> Windows 10 does not ship with the DirectX 9 redistributable installed by default. Does installing the DirectX 9.0c redist from this link help? https://www.microsoft.com/en-us/download/details.aspx?id=8109

Hey, that's actually what I tried immediately after seeing that error from the command prompt. It doesn't seem like it helped at all.
I've been using MAME with the exact same settings just fine since I installed Windows 10 2 years ago, though. I think some change after .201 broke it.

**Comment by klaritan** [comment]
Also important to note that I have not installed any Windows Update after the last known working condition.

**Comment by MooglyGuy** [comment]
Alright, good info, thanks. Next question, when you updated MAME, how did you go about updating it? Did you extract the full contents of the release, or just the executable?

**Comment by klaritan** [comment]
> Alright, good info, thanks. Next question, when you updated MAME, how did you go about updating it? Did you extract the full contents of the release, or just the executable?

Oh my goodness. I only just copied the executable and the plugins folder.
I copied the rest of non-config folders and it worked. I'm so sorry about this. 

Thanks a lot!

**Comment by MooglyGuy** [comment]
No worries at all, I'm glad that that's all it was! 😄
