### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by mmicko** [mamedev/mame#406]
Create ability in core to start LUA scripts using internal menu in case there are scripts assigned to all machines (GLOBAL), machine type or specific machine. 

Plugins would be stored inside addons/plugins/  there is need for addon.xml that will define visibility of plugin and some brief description, and also name of startup LUA script.

inside addons/scripts/ there will be LUA libraries that can be used by any other plugin or script, note that in addon.xml there will be need to define dependencies.

**Comment by DrMefistO** [comment]
It would be great to have such functionality. But... LUA scripts... They don't allow to use some GUI subsystem. So, if I want to show some dialog, or use some shared library it won't be able.

**Comment by rb6502** [comment]
LUA scripts can draw arbitrary  primitives and text overlaying the game screen; there is one already that shows hitboxes in one game.  More advanced GUI functionality can be added if necessary.
