### ISSUE TITLE
BGFX stops working when using artwork

### ISSUE THREAD

**Issue by SaucySarah** [mamedev/mame#4068]
Don't really know much about this but I use all default settings and only change 'Video Mode' to BGFX and 'BGFX screen chains' to crt-geom-deluxe. This works fine. If I enable artwork then BGFX stops working. I had to delete the mame.ini to get it to work again. (I'm using MAME 0.202).

**Comment by MooglyGuy** [comment]
Thanks for the report!

If it's not too much trouble, could I have some clarification on what "BGFX stops working" means? Does MAME crash? Does it simply revert to not using any shaders at all? Would you be willing to run MAME using the -verbose flag and paste the resulting output to Gist?

The more detailed the information you can give, the better.

**Comment by SaucySarah** [comment]
Currently at work at the moment. When I say 'BGFX' stops working, I mean it doesn't use it when I enable artwork and I think just uses the default video mode. If I turn off the artwork I couldn't get BGFX to work again, tried turning it off and on (I use a GUI 'Arcade64'). I ended up deleting the mame.ini and set the option again.

**Comment by Robbbert** [comment]
Arcade64 is not a valid platform for problem reports. You will need to attempt to replicate the issue with standard MAME that has been downloaded from mamedev.org, and with it follow the suggestions given by MooglyGuy.

**Comment by SaucySarah** [comment]
OK, I just checked regular MAME and it works fine. It only happens with Arcade64.
