### ISSUE TITLE
Improve build performance

### ISSUE THREAD

**Issue by curt-coder** [mamedev/mame#408]
Essentially make it build as fast (or faster) as it used to before changing to Genie.

**Comment by FlykeSpice** [comment]
Is Genie itself being a bottleneck or can the scripts be potentially be faster ? If there is potential for genie's scripts improved I believe there isn't much can be done. In fact, I don't know much about this exotic build system they chose.

**Comment by curt-coder** [comment]
This is no longer an issue for me since a full build takes only 11 minutes on an MBP M2 Max.
