### ISSUE TITLE
Build failure on macOS Mojave: ld: library not found for -lgcc_s.10.4

### ISSUE THREAD

**Issue by ryandesign** [mamedev/mame#4086]
Building mame fails on macOS Mojave 10.14:

https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/2374/steps/install-port/logs/stdio

```
ld: library not found for -lgcc_s.10.4
```

Support for ancient deployment targets has been removed in macOS Mojave. My preference would be that you not specify a deployment target in your build scripts at all (i.e. don't use the `-mmacosx-version-min=...` compile flag nor the `MACOSX_DEPLOYMENT_TARGET=...` environment variable). If the person building your code wants to target an earlier macOS version, they should be the one to set those flags or variables, and if you want to build official binaries that way, that's fine too.

**Comment by rb6502** [comment]
Mojave is supported in Github top-of-tree so this bug is invalid.

**Comment by ryandesign** [comment]
My apologies! I should have checked.

**Comment by rb6502** [comment]
No problem.  Fair warning: you'll need the SDL 2.0.9 pre-release from 
http://www.libsdl.org/tmp/download-2.0.php or else you'll just get a blank window with game sounds on Mojave.
