### ISSUE TITLE
Compile error on mac os x.(MAME in webassemly version)

### ISSUE THREAD

**Issue by Nightaway** [mamedev/mame#4187]
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: glDisableClientState
error: undefined symbol: glEnableClientState
error: undefined symbol: glEnd
error: undefined symbol: glGetTexLevelParameteriv
error: undefined symbol: glOrtho
error: undefined symbol: glPointSize
error: undefined symbol: glPopAttrib
error: undefined symbol: glPushAttrib
error: undefined symbol: glShadeModel
error: undefined symbol: glTexCoordPointer
error: undefined symbol: glVertex2f
Error: Aborting compilation due to previous errors
ERROR:root:'/Users/mac/Desktop/emsdk/node/8.9.1_64bit/bin/node /Users/mac/Desktop/emsdk/emscripten/1.38.14/src/compiler.js /tmp/tmpGfSfNa.txt /Users/mac/Desktop/emsdk/emscripten/1.38.14/src/library_pthread_stub.js' failed (1)
make[2]: *** [../../../../../1943test.bc] Error 1
make[1]: *** [1943test] Error 2
make: *** [asmjs] Error 2

**Comment by Nightaway** [comment]
I copy SDL2.framework to /Library/Frameworks already.

**Comment by MooglyGuy** [comment]
Sorry, but Webassembly is not an officially-supported build target. You will have to take this up with the JSMAME team.

**Comment by DopefishJustin** [comment]
It is supported. It looks like the latest Emscripten release has changed the default value of ERROR_ON_UNDEFINED_SYMBOLS so I'll have to address that. (The gl errors can be ignored.)

**Comment by DopefishJustin** [comment]
Please try again with bcb672ce32cbd74c0ccd5dc4fa2138cb3f54a9bb.
