### ISSUE TITLE
Request for approval, doc translation to Brazilian Portuguese, some doc issues

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4195]
Mame documentation has been translated to Brazilian Portuguese, some dev's are aware of this work and is now done.

I believe that many Brazilians MAME lovers would enjoy this work and rediscover MAME as I did.

I couldn't found any MAME document rules, standards of any sort to follow, there for, I'm using our own country available standards for books and documentation:
* ABNT NBR 6029 (ISO 1086:1991 and related)
* ISO 2384:1977 and related
* Normas técnicas para redação acadêmica da Universidade Federal do Rio de Janeiro (UFRJ)

This is the format adopted, used in books and other documents written in Brazilian Portuguese:

Title: Bold, all uppercase
Sub title: "Something like this" and "Not Like This"
Bold: commands, points that need the reader attention
Italic: International names, direct reference, specifics. Do not italic symbols like <>, [], {}.
Translator notes: Added by the translator to provide additional information pertaining the limits of  translation, cultural background or any other explanations necessary.

A page brake was used to avoid chapter leakage, only needed with latex and PDF:
```
.. raw:: latex

	\clearpage
```

The original doc invite people to contribute, so I did a chapter about cross compiling.

The original MAME documentation has **some issues** , this is my professional observation, it has nothing to do with been "picky" about anything or to disrespect anyone. I'm aware that this document was done by different people, from different places in the world. Many of this issues are fixed in the translated document.

All this are generic and done not to hurt anybody feelings.

* About 90% of the document was written using passive voice instead of active. Rule of thumb for books, documents, flyer's (etc) is to use active voice, we use passive voice very sparingly. Active voice is direct, precise, uses less words to describe the same thing. Portuguese speakers are well aware of agente da passiva, objeto direito e indireto, sujeito da frase, sujeito e predicado, etc.
So and so was created by MAME (passive)
MAME created so and so (active)

* Avoid unnecessary prepositional phrases.
An example of the working config ...
The working config example ...

* Try to use expletive constructions sparingly (there are, there is, it is, etc).
It was MAME last version that created in the so and so
MAME last version created so and so

* Try to avoid wordy verbs.
Is compressing = Compress
Are indications = Indicate
Is taking = Takes
has knowledge of = Knows
etc.

* Set action sentence in the verbs.
An **emulation** of the process **need to be done**.
The process **need to be emulated**.
We **need to emulate** the process.

* Try to keep sentences plain, clear and well structured:
Avoid making your point starting here (then go over there) then go back here (then go there again).

* Use simple language, avoid slangs

* Paragraph.
Try to keep one point per paragraph; in general, use the last sentence to transition to the next.

* Avoid using commas to set off restrictive modifiers.
Non restrictive: John doe, the programmer, did so and so.
Restrictive: The programmer John Doe did so and so.

* Avoid been too redundant.
Don't try to describe something over and over again across paragraphs.

There are other small issues not listed.

The document source code is available, any one can change it or fix it when necessary. I don't have permission to push it by git, hope some one do it for me.
Thank you.
[MAME_DOC-pt_BR-10282018.tar.gz](https://github.com/mamedev/mame/files/2518924/MAME_DOC-pt_BR-10282018.tar.gz)
[MAME-pt_BR.pdf](https://github.com/mamedev/mame/files/2518925/MAME-pt_BR.pdf)

**Comment by Firehawke** [comment]
In almost EVERY case, we pulled directly from the original docs. In fact, the project was FIRST to convert the original docs to the new system, THEN to update it. So... yeah, there are problems with the voice changing, because there's been roughly a dozen people writing two dozen docs that needed to be condensed.

I'm definitely aware of the issue, but I've got significant other problems I need to deal with before I can go back and do major surgery on the English documentation.

**Comment by katananja** [comment]
I've been doing professional translations for the past 25 years. The issues MAME has with his own documents I've seen before, it's not about one person to blame.

* A person responsible for it, is overloaded.
* No procedures, no standards, no specific rules set, no organization.
* People dump text on it and hope some one, some day, deal with it and all make sense, somehow.

Again, all this issues I've pointed out, are my professional observations, not intended to blame or disrespect anyone. If there isn't a TODO list, you got one right here.

Everybody has problems to deal with Firehawke, I'm not blaming you for it. I'm sorry if I could not help you out more, dealing with text and documents is a pain in the ass, specially when is someone else's work.

The important thing is, the job is done with the most care for the MAME project, Brazilian people or any Portuguese speak person now can have access to all this information, for free.

**Comment by cuavas** [comment]
I have two major issues with importing a translation:
* We have no team members qualified to review it properly.
* We won't be able to keep it in sync, or even track which parts of it have got out of sync.

Anything on mamedev.org is implicitly endorsed by the team, and I think it's an unacceptable risk to publish a translation that none of us have the skills to properly review.  We're already having issues keeping the documentation in sync with MAME.  We don't have the resources to also keep translations in sync.  Misleading documentation is worse than no documentation.

The documentation is licensed permissively.  You can publish the translation on your own site, and I'd be happy to add a link to it as an unofficial translation.  But at this point, we lack the resources to publish translations ourselves.

**Comment by katananja** [comment]
No problem @cuavas, I agree with you.

I don't agree however with the term, "_unacceptable risk_" and "_misleading_" there's no such a thing. MAME is an open source and a collaborative project, if there are such a "risk" or "misleading" info, any one will come, edit it, change it or complain about it.

I'll push it over my account and share the link latter.
If there is any "_misleading_" information, please, don't hesitate to contact me or to fill up a issue report. It will be fixed as soon as possible.

Thank you.

**Comment by katananja** [comment]
@cuavas @Firehawke here is the first release.
https://github.com/wtuemura/mamedoc/releases/tag/1.0

All source code is available and released with the same creative common license as MAME official doc.

Thank you.
