### ISSUE TITLE
Save State Menu saves too quickly

### ISSUE THREAD

**Issue by illando** [mamedev/mame#4201]
If you map a joystick button to be used for save state, the dialog window (used to let you choose a save slot) appears for just one moment selecting that shortcut button as slot position, and overwriting the previous one (in case it was present).
Second time you press the same button the window wait letting you chose the slot. So the problem is only related to the first time you want to save.

**Comment by illando** [comment]
Any developer interested in solve this one, please??
I understand using save states is considered blasphemy from the hardcore retrogamers, but is this bug so hard to fix?

I also reported on Mame Testers:
[https://mametesters.org/view.php?id=7140#bugnotes](https://mametesters.org/view.php?id=7140#bugnotes)

I don't know if it's only related to SDLMame or if also in Windows version is affected.

**Comment by cuavas** [comment]
People work on things that they're interested in.  If a usability issue doesn't break a common use case, there's no way to get developers to prioritise it over other things they want to work on.  You'll have to either wait for a developer to fix it, or fix it yourself.

**Comment by illando** [comment]
@cuavas Apologize for my last reply!
It was not my intention to say I'm pretending that somebody **must** do something. I am very grateful to all the MAME developers.
I was only assuming that this bug is actually something that break a common use case, but maybe I'm wrong.
Thanks anyway for your reply.

**Comment by angelosa** [comment]
> I don't know if it's only related to SDLMame or if also in Windows version is affected.

I cannot repro in Windows. 
Also if this has been posted to MT I don't see why this should be left open tbh.

**Comment by cuavas** [comment]
This is fixed by f5fb44a9dbd6f74d2015cc095e5a92199e2345e9 anyway.
