### ISSUE TITLE
Lua screen:draw_text() ignores the BG color

### ISSUE THREAD

**Issue by vadosnaprimer** [mamedev/mame#4236]
Luaengine's call to `mame_ui_manager::draw_text_full()` is sending `UI_TEXT_BG_COLOR` for text drawing, but it's also sending `mame_ui_manager::NORMAL draw_mode` which is hardcoded to pick `rgb_t::transparent()` (0x0 color). So it's impossible to have any color behind the text.

Of course the best solution would be allowing to send a custom color, but having at least the default one would also help a lot (and it's intended to be there).

Also, you don't need `nullptr`s in this call, since the prototype defaults to `nullptr`s.

**Comment by cracyc** [comment]
https://github.com/mamedev/mame/commit/b311dfeaf82251dc6915edbc4e421c698427f9ab adds optional background color

**Comment by vadosnaprimer** [comment]
Fixed.
