### ISSUE TITLE
It allways asks for files...

### ISSUE THREAD

**Issue by marcusViniciusMP** [mamedev/mame#4243]
where do i find theses files it always asks for ? is there any version with those files in it ? it just a waste of time searching for these files spend more time than using mame. why dont you release it whith theses files ?

**Comment by marcusViniciusMP** [comment]
> MAME is an emulator. As such, it emulates games which you must provide, dumped off of your own legally-owned boards. Do not file an issue like this again or you will find your access to the project curtailed.

so curtailed as your moods.

**Comment by marcusViniciusMP** [comment]
> By files, I assume you mean the machine romsets needed to run an emulation? We cannot do that.
> Well, that statement is not entirely true, there are a few machines MAMEDEV has the right to host roms for a user to download located at the link below.
> 
> https://www.mamedev.org/roms/

seems to me that older versions was more compatible with games of capcom, i dont understand what files are these , is there some version of mame that legally can hold all these files inside ? like a different distribution ? thanks !

**Comment by Robbbert** [comment]
Sorry it's illegal for us to even discuss this. You'll need to find the files yourself.
