### ISSUE TITLE
Sound issue with games that use snk6502.cpp

### ISSUE THREAD

**Issue by Flobeamer1922** [mamedev/mame#4249]
In games that use this driver such as Fantasy, Pioneer Balloon, and Vanguard, the SNK6502 Custom Sound channel is bugged. What usually happens is that it will hang on a note and sustain it, as can be heard in the zipped video file below. Sometimes, such as in the case of Fantasy, it will get itself unstuck during the first section of a loop, only to end up out of sync with the rest of the music. In the case of Pioneer Balloon, it can drop out entirely during the first two sections of a loop.
[Fantasy Glitched Sound.zip](https://github.com/mamedev/mame/files/2546636/Fantasy.Glitched.Sound.zip)

**Comment by cuavas** [comment]
There were two changes to this device since this issue was opened: 24248c8ca80f65823122cd2d737046ef7b1b5206 and 35496174d0d98bef0860ca7643c18c0ce9a40568

Does the issue still exist as described?  Does this duplicate a MAME Testers issue?

**Comment by Osso13** [comment]
This has been fixed.
