### ISSUE TITLE
Using Lua to modulate a dial control

### ISSUE THREAD

**Issue by syaffers** [mamedev/mame#4281]
I'm trying to find a way to modulate a `:DIAL0` port but I can't seem to do much via the Lua script. I've tried the following for the game `carpolo`:

    [MAME]> iop = manager:machine():ioport()
    [MAME]> iop.ports[":DIAL0"].fields["Dial"]:set_value(1)

This, however, resulted in the player one car *not* turning. Is there a way to modulate the dial via the Lua script?

**Comment by cracyc** [comment]
Analog fields are overwritten every frame so there is no way to set them from lua currently.
