### ISSUE TITLE
"DSP56k core" is misnamed

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#4287]
Just putting this here so that I don't forget about it:

There's purported to be a Motorola DSP56k emulation core in src/devices/cpu/dsp56k/*.

The problem with this nomenclature is that it isn't a general-purpose DSP56k emulator, it's a DSP561xx-series emulator, only. There's a significant number of enums, members, and files that should be renamed to some form of DSP561xx instead of DSP56k, particularly because the DSP561xx series is not at all compatible with the DSP560xx series.

The DSP561xx series is a set of 16-bit DSPs. By contrast, the DSP560xx series is a set of 24-bit DSPs. The two have broadly similar architecture in terms of general-purpose registers, but have entirely different instruction encodings, and also differ in terms of accumulator and index register widths.

Having this directory named DSP56k gives the false impression that the DSP560xx series is supported, when the only supported device at this time is the DSP56156.

**Comment by andrew-gardner** [comment]
I agree.  It’s current naming has confused a number of different people
(interested in the core for a number of different reasons) in the past.

Especially since official documentation for those cpus is so sparse, mame
would benefit from being as pedantic and accurate as possible.

/Andrew

**Comment by MooglyGuy** [comment]
Hi! I'm one of those people. :smiley:

I was originally looking at it because since I'm back on an SGI kick, I was hoping that I could finally wire up the Indigo's audio DSP, which according to documentation is a DSP56001.

Looks like I'll just have to bite that bullet myself at some point. The instructions themselves seem largely the same other than encoding and ALU register widths, so I'm hoping that the switch to C++ will make the addition of DSP560xx support go more smoothly it would have back in the bad old days. Plus, I imagine that getting the core to play a boot chime will be less taxing than most other things that use the DSP560xx.

**Comment by JayFoxRox** [comment]
Unrelated to MAME, but those looking for a DSP56k emulator:

- [DSP56001 is in Hatari (Atari Falcon emulation)](https://github.com/hatari/hatari/blob/master/src/falcon/dsp_cpu.c).
- [DSP563xx fork of the Hatari code is in XQEMU (Original Xbox emulation)](https://github.com/xqemu/xqemu/tree/master/hw/xbox/dsp); it's very incomplete.

An open-source assembler for DSP56k would be a56. The Xbox community maintains [an open-source fork on GitHub](https://github.com/xboxdev/a56). There are plans to add more DSP563xx support to a56, or to write new tools altogether.
The Xbox community also has a lot of unit tests to work with the DSPs in the Xbox, so some bugs inherited from Hatari have been fixed already. It's not certain if all DSP56001 fixes will find their way upstream.

With MAME supporting Chihiro (based on original Xbox), I assume that there'll be eventually DSP563xx emulation (and considering it has 2x DSP563xx running at 160MHz, it will likely need more optimized code for performance).

**Comment by Osso13** [comment]
This has been addressed by https://git.redump.net/mame/commit/?id=450a57568e16822d625c3e0cd390e9c9e6a08718 .
Closing.
