### ISSUE TITLE
gluck2.cpp probably payment error

### ISSUE THREAD

**Issue by Cristiano-MDQ** [mamedev/mame#4293]
This game only makes the payment of multiples of 10, for example: If I have 101 credits and hit the payment button, only 100 credits are paid and 1 continues in the game. From what I noticed the 3rd bit is not read when paying the credits leaving broken values ​​outstanding. My question is whether this is natural of this game or it was a failure of emulation.

**Comment by Tafoid** [comment]
Logged also at https://mametesters.org/view.php?id=7150
Please avoid using Git Issues to report valid bugs with integer releases when mametesters.org is there for that reason.  Closing
