### ISSUE TITLE
Eagle Shot Golf Word Glitch

### ISSUE THREAD

**Issue by TradeDraft** [mamedev/mame#4311]
As seen in this Video when you get a Birdie or Par the Word is Glitched Out.

Video Shows it here:

https://www.youtube.com/watch?v=chHKrWgjR3Y

How can this be Fixed?

**Comment by MooglyGuy** [comment]
It can be fixed by a developer who is interested in that hardware stepping up and fixing it. Sorry, we don't really operate on definite time-tables here. This is a hobby project for everyone involved.

**Comment by TradeDraft** [comment]
Okay @MooglyGuy would it be worth looking for someone who would work with that Hardware?

**Comment by MooglyGuy** [comment]
Are you volunteering to try fixing it? If not, it will be fixed when it gets fixed, whenever that is.

**Comment by TradeDraft** [comment]
IF I had the Skills I would love to try and Fix it sadly I don't.

Okay. So not worth trying to find who worked on this Game and ask IF it can be Fixed or not

**Comment by DavidHaywood** [comment]
as it happens I'm looking at this driver anyway, as it's been in my plans for a long time.  My main focus is on the missing line effects (Sammy logo in this game, Dynagears logo, Ultra X title screen, Survival Arts floor on some stages etc.) but I can add this bug to the list of things to look at, I have a few ideas as to what it might be.

**Comment by TradeDraft** [comment]
Thank you Very Much @DavidHaywood for adding this Glitch to your list for things to Fix in this Driver.

Wish you Luck. How can I follow how you go with it Mate?

**Comment by DavidHaywood** [comment]
https://mamedev.emulab.it/haze/2018/11/26/ssv-improvements-part-2/
https://mamedev.emulab.it/haze/2018/11/25/ssv-improvements/

https://github.com/mamedev/mame/pull/4341

**Comment by TradeDraft** [comment]
Thank you very Much for Fixing That @DavidHaywood.

Now just wait for End of December to get the the Fixed in MAME

**Comment by DavidHaywood** [comment]
it should be possible to close this now
