### ISSUE TITLE
bug in f8 cpu core

### ISSUE THREAD

**Issue by utz82** [mamedev/mame#4371]
The attached Fairchild Channel F ROM should produce some music. It works in MAME 0.191 (and on real hardware), but is broken in 0.204. I suspect it may have been broken by https://github.com/mamedev/mame/commit/e473764e0445aa1017e0f57cbe04273e9b489740 .

To verify the bug, set a breakpoint at 0x8c6. Run through the bp 25 times. On the 26th iteration, C flag should be set after executing the AS HU opcode, but that doesn't happen.

[channelf-f8-bug.zip](https://github.com/mamedev/mame/files/2641542/channelf-f8-bug.zip)

Edit: Actually, what is line 275 in [f8.cpp](../blob/master/src/devices/cpu/f8/f8.cpp) supposed to do? ORing with 0 will not do anything if I'm not mistaken.

**Comment by DavidHaywood** [comment]
> Edit: Actually, what is line 275 in f8.cpp supposed to do? ORing with 0 will not do anything if I'm not mistaken.

that's a O not a 0, but yeah @happppp  is still active, so will probably look into why it broke if his change broke it

**Comment by ajrhacker** [comment]
I've fixed this in a4b24c24a2230e73e077ffd307bdb2a932c8325e. The bug was not in the emulation of the AS HU instruction, but in the LNK instruction immediately preceding it.

**Comment by utz82** [comment]
Excellent, thanks for the quick fix!

**Comment by happppp** [comment]
Thanks AJR =)
