### ISSUE TITLE
3rdparty/bgfx/3rdparty/khronos/glx/glxext.h:39: error

### ISSUE THREAD

**Issue by leiptrstormr** [mamedev/mame#4375]
```
Compiling 3rdparty/bgfx/src/glcontext_glx.cpp...
In file included from ../../../../../3rdparty/bgfx/src/glcontext_glx.cpp:13:
../../../../../3rdparty/bgfx/3rdparty/khronos/glx/glxext.h:39: error: "GLX_GLXEXT_VERSION" redefined [-Werror]
 #define GLX_GLXEXT_VERSION 20131028
 
In file included from /usr/include/GL/glx.h:333,
                 from ../../../../../3rdparty/bgfx/src/glcontext_glx.h:12,
                 from ../../../../../3rdparty/bgfx/src/renderer_gl.h:960,
                 from ../../../../../3rdparty/bgfx/src/glcontext_glx.cpp:9:
/usr/include/GL/glxext.h:37: note: this is the location of the previous definition
 #define GLX_GLXEXT_VERSION 20180525
 
cc1plus: all warnings being treated as errors
make[2]: *** [bgfx.make:469: ../../../../linux_gcc/obj/x64/Release/3rdparty/bgfx/src/glcontext_glx.o] Error 1
make[1]: *** [Makefile:73: bgfx] Error 2
make: *** [makefile:1301: linux_x64] Error 2
```
Linux debian 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-11-02) x86_64 GNU/Linux
gcc version 8.2.0 (Debian 8.2.0-9) 

make NOWERROR=1 works for now

**Comment by MooglyGuy** [comment]
Please sync up to the branch entitled "3rdparty_update" and kindly let me know if this resolves the issue you are encountering.

**Comment by leiptrstormr** [comment]
git branch
* 3rdparty_update

It looks like the issue is still there.

**Comment by katananja** [comment]
Working fine here with default Debian.
`Linux Dragon 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`
`gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)`
`clang version 5.0.2-svn328729-1~exp1~20180509123438.100 (branches/release_50)`
`OpenGL version string: 3.0 Mesa 13.0.6`

Make sure all the changes you made in your Debian it's not causing this.

**Comment by galibert** [comment]
That's because I hacked it in a0f1fb2698ad3b584e2f698cecb260216b29c7ae

  OG.

**Comment by leiptrstormr** [comment]
It built without issue this time. Thanks!
