### ISSUE TITLE
.203 forward d3d hlsl issues

### ISSUE THREAD

**Issue by NJDave71** [mamedev/mame#4432]
Every since .203 has been released mame will crash under d3d enabled with hlsl.   I went back to .202 and all is fine.   what has changed so I can investigate this further.

thanks

**Comment by cuavas** [comment]
Did you update the external support files when you upgraded MAME, or did you just replace the executable?  The support files must match the executable for many features to work correctly.

**Comment by NJDave71** [comment]
Thank you..... Merry Christmas. was missing the extra files.   Merry Christmas and Happy New Year.
