### ISSUE TITLE
SPU RAM error

### ISSUE THREAD

**Issue by theoouy** [mamedev/mame#4450]
This is for the Firebeat stuff they use to run Pop'n Music.  I managed to get my hands on the files needed to run the game, there's even a CD-ROM and DVD-ROM to use in the game.  I loaded them all and everything came to a quick HALT.  I found that there's nothing related to SPU RAM when it comes to MAME, and I'm pretty sure that's sound related and I don't think that's a big issue to emulate as Pop'n(s) 1 - 3 work fine with no issues.  The error I get is [https://puu.sh/CpToW/8a9ae7ce61.png](url) And was wondering if there's anyone who knows anything about this so I can continue my Firebeat research.

**Comment by rb6502** [comment]
Those games are not supported; you should have gotten a large red screen immediately on startup stating that emulation is not complete for those games and that non-technical end users cannot make them work.
