### ISSUE TITLE
'mame.exe snes' causes access violation

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#4459]
MAME v0.205 (mame0205-186-g4215166070) / 11:43 PM PST 1/2/19
Win10 x64

Typing 'mame.exe snes' causes an access violation.
Would expect to be able to get to the tab / file manager to select from the softlist.  Pretty sure I was able to do this previously.

**Comment by Tafoid** [comment]
Suspect breakage here:
https://github.com/mamedev/mame/commit/62af3e0b1c1a4ad03cb394eba7d24416bf762c33

**Comment by Osso13** [comment]
yes, it seems to me that the patch assumes m_cart must always be != nullptr, which isn't the case.

**Comment by ajrhacker** [comment]
Fixed in 1c11b78524935e26c5a46b9ea23834d75abd7cf0.
