### ISSUE TITLE
CPS3 checkin breaks games.

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#4468]
MAME v0.205 (mame0205-221-g76effa7a28) / Win10 Pro x64

New CPS3 checkin seems to break the games. 
When launched they now show that 'The CD ROM is not properly connected.  Please turn the power off and properly correctly' (sfiii, sfiii2, for example.)  Killed cfgs and nvram.

Hitting F3 at this point yields:
Fatal error: wd33c93a: Unhandled command phase during Select-and-Transfer disconnect.

**Comment by katananja** [comment]
sfiii, sfiii2
![0000](https://user-images.githubusercontent.com/9029191/50674507-28945480-0fce-11e9-9c74-d1bb1fecb0f6.png)

sfiii3
![0000](https://user-images.githubusercontent.com/9029191/50674511-3518ad00-0fce-11e9-9434-9cd80abb4918.png)

**Comment by MooglyGuy** [comment]
This driver is currently being worked on. The breakage is known and expected.
