### ISSUE TITLE
CPS3 CD-Rom error

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4469]
Debian 9.6 x64
latest git

sfiiii and sfiii2 show a CD-Rom error screen, sfiii3 stuck in a infinite CD-Rom loading screen.
![0000](https://user-images.githubusercontent.com/9029191/50674446-78bee700-0fcd-11e9-8d04-d2b3fd6f346d.png)
![0000](https://user-images.githubusercontent.com/9029191/50674469-bde31900-0fcd-11e9-813b-f9a160834ae2.png)

This are the only ones I have to test.

**Comment by katananja** [comment]
duplicate:
https://github.com/mamedev/mame/issues/4468

**Comment by cuavas** [comment]
"Latest git" means nothing - you must supply a revision hash if you're not testing a tagged release.  Also this is a duplicate off #4468.

**Comment by katananja** [comment]
Does it make sense to make a report about a version from one year ago? From last weak, from yesterday?
**NO!**
Even if I use such old version people will tell to use the latest, if this is not obvious to you it's because you are so damn stupid to figure it out by yourself.

Don't be such a dick @cuavas because the post was already closed by me.

**Comment by MooglyGuy** [comment]
Do not engage in abusive language towards team members or you will find your access to the project curtailed. This is your first and only warning.

**Comment by cuavas** [comment]
@katananja "latest" is a different thing every time someone commits.  In the time between when you compile, when you open the issue, and when someone reads it, "latest" will have changed.  You've been around long enough to understand this.  Without a revision hash, we don't know what "latest" is.  Note that on #4468 an abbreviated revision hash is included in the issue description.  You're being banned from MAMEdev repositories for one week for counter-productive behaviour.
