### ISSUE TITLE
Fail to compile at 26412cd8292a30ce81d4db3685c4e204a8996d1a (netlist?)

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#4483]
Trying to compile tip of trunk, Win10 x64.
1 parent cd48a8d commit 26412cd8292a30ce81d4db3685c4e204a8996d1a
make -j9 -Werror

Compiling src/lib/netlist/plib/putil.cpp...
../../../../../src/lib/netlist/nl_setup.cpp: In member function 'int netlist::setup_t::get_initial_param_val(const ps
tring&, int)':
../../../../../src/lib/netlist/nl_setup.cpp:177:19: error: 'floor' is not a member of 'std'
   if (vald - std::floor(vald) != 0.0)
                   ^~~~~
Compiling src/lib/netlist/solver/nld_matrix_solver.cpp...
netlist.make:1009: recipe for target '../../../../mingw-gcc/obj/x64/Release/src/lib/netlist/nl_setup.o' failed
make[2]: *** [../../../../mingw-gcc/obj/x64/Release/src/lib/netlist/nl_setup.o] Error 1
make[2]: *** Waiting for unfinished jobs....
makefile:28: recipe for target 'netlist' failed
make[1]: *** [netlist] Error 2
makefile:1051: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

**Comment by Robbbert** [comment]
From commit https://github.com/mamedev/mame/commit/3c6d9ac9a02d721a3245c1725b29dd6c10ce3ea7

What compiler, version, and platform are you using? It compiles for me.

**Comment by john-iv** [comment]
I just ran 'pacman -Syu' on the mamedev compile package tonight so everything is the newest as of 11:41 PM PST.

**Comment by Robbbert** [comment]
As you know, I still use GCC 5.3.0 - std::floor has been around for quite a while, so I can only guess that some compiler versions require the specific math library be included. This is something for the C++ experts to consider.

**Comment by cuavas** [comment]
Some standard library headers weren't included where they should be - try ae6185e5f660531ae47545b9c80f6c7056f6ecbc
