### ISSUE TITLE
sdlmame requesting missing dll's

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4507]
``mame0205-411-g23a624e783-dirty``
Win10 x64
Build Tools ``msys64-2017-12-26.exe``

The updated MAME document:
https://docs.mamedev.org/initialsetup/compilingmame.html#microsoft-windows

It say that if ``OSD=sdl`` it will generate a ``sdlmame64.exe``, if you run it, it complains about this missing dll's:
``SDL2.dll``
``libgomp-1.dll``
``libwinpthread-1.dll``
``libgcc_s_seh-1.dll``

Command used to compile it:
``make clean && make OSD=sdl -j5``

Is sdlmame been compiled as "shared" instead of "static"?

**Comment by Firehawke** [comment]
In the future, please open docs issues as a separate issue so I can close the case when appropriately fixed.

**Comment by cuavas** [comment]
@smf- changed it to link dynamically in b0223ac413ccfb0907be9741168b4cf43fb67fb9 to work around an issue with clang on Windows.  You can add the MSYS2 MinGW directories to your path or copy the required DLLs to System32 and/or SysWOW64.
