### ISSUE TITLE
[neogeo] Infinite reset loop

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4531]
``mame0205-530-ge22568da38-dirty``
Debian 9.6 X64
Build options ``make clean && make SOURCES=src/mame/drivers/neogeo.cpp OPTIMIZE=0 -j9``

1. ``./mame64 kof2001``
2. After the attract mode start TAB > Select New Machine > kof2002
3. The machine get in to an infinite reset loop.
https://www.youtube.com/watch?v=wERqyFeOTMg

This doesn't happen to other machines tested so far, only with neogeo.

**Comment by cuavas** [comment]
Why are you testing with dirty builds (i.e. locally modified source)?  What are you modifying?

**Comment by katananja** [comment]
I'm using git versions.

**Comment by cuavas** [comment]
The version string `mame0205-530-ge22568da38-dirty` has "dirty" in it, indicating that your source is locally modified.  What are you modifying?

**Comment by katananja** [comment]
My source is not modified, it is a git clone.

**Comment by cuavas** [comment]
If you haven't modified anything, it won't show `-dirty` in the version string.  Check an official build from mamedev.org or similar.  I will close this if you don't give a straight answer.

**Comment by katananja** [comment]
I'll compile the official and return, but I'm telling you the truth, I didn't change anything.

**Comment by Tafoid** [comment]
In my experience dirty shows up in any compile which has been made using leftover BIN/OBJ files.   Your best chance (and next step) would be to "make clean" then recompile anew.

**Comment by Tafoid** [comment]
Anyway, using my daily build mame0205-525-g76b5bcd1f7 , I can confirm the behavior where upon choosing kof2002, it attempts booting but hangs up somewhere and the machines forces a non-watchdog related restart..  over and over.

**Comment by Tafoid** [comment]
Happens as well with 0.205 from MAMEDEV.org, both 32 and 64-bits.  It is a valid multisession bug, I reckon.  I'll get it logged on MT.

**Comment by katananja** [comment]
> In my experience dirty shows up in any compile which has been made using leftover BIN/OBJ files. Your best chance (and next step) would be to "make clean" then recompile anew.

I use @cuavas command he gave me 2 years ago ``for f in $(find . -name *.[oa]); do rm -f $f; done`` it might be it, because I don't have the skills to change any part of the MAME source code.

Here is the git: ``mame0205-530-ge22568da38``
This is the official: ``MAME v0.205 (unknown)``

> Happens as well with 0.205 from MAMEDEV.org, both 32 and 64-bits. It is a valid multisession bug, I reckon. I'll get it logged on MT.

Thank you, I'll add your information at my MAME Documentation explaining this ``-dirty`` issue.

**Comment by Robbbert** [comment]
This issue was logged as https://mametesters.org/view.php?id=7208

Further correspondence can be done there.
