### ISSUE TITLE
[Suggestion] Lexibook Zeus

### ISSUE THREAD

**Issue by dkl3** [mamedev/mame#4570]
Hi, I don't know where else to post this, so I decided on here. 

There's a device being sold on Amazon known as the Lexibook Zeus. It appears to be, of all things, a GBA-on-a-Chip. It's usually NES or VTxx on a chip but looks like this one is an actual GBA on a chip--the games on there are the same as some Jungletac GBA games that happened to be dumped.

Not all of them were dumped, for instance, Deep Storm. There's a start button that functions the same on the menu and the games--it just dims the display. I wonder if anyone (presumably Haze) might be interested?

External links:
https://www.youtube.com/watch?v=cano_wQFCrw - YouTube video
https://www.amazon.com/gp/offer-listing/B000HZTNJM/ - Amazon listing

I wont link to Jungletac GBA games

**Comment by DavidHaywood** [comment]
If somebody does a complete dump of the system I'm sure it could be looked at.

Could also just be running a GBA emulator of course.

**Comment by dkl3** [comment]
It would definitely be interesting to find out

**Comment by DavidHaywood** [comment]
We've picked one up for a bit of probing.

**Comment by dkl3** [comment]
awesome

**Comment by dkl3** [comment]
there's another undumped handheld called 220 in 1 dreamgear gamer go portable. has miwi games and appears to run on sunplus technology. david

**Comment by DavidHaywood** [comment]
The Zeus was just a SunPlus thing
https://www.youtube.com/watch?v=rPR0aWTJZcU

**Comment by dkl3** [comment]
weird, then i wonder where the jungle tac gba games come in?

**Comment by dkl3** [comment]
also for the pausing, it's probably hardware-handled. It only dims the display when you attempt to pause--that's all it does. i have a lexibook zeus of my own, so

**Comment by DavidHaywood** [comment]
pausing with the screen dim is a software feature, there's a button that does it.

the random pausing and corruption in the game is something else.  we're pretty sure the ROM is correct now, so that's a bit of a mystery, maybe some extra security.  the same game works fine in 'zone60'

**Comment by dkl3** [comment]
why would a simple sunplus game have security attached to it?

**Comment by DavidHaywood** [comment]
well it already had the rom under a block of epoxy, and, unlike many other SunPlus games, was encrypted, so another layer of security wouldn't be out of the question.

**Comment by cuavas** [comment]
This has been dumped and added to MAME, so I'm closing the issue.  The issue tracker is not a place for general discussion - consider moving the chat to a community forum.
