### ISSUE TITLE
.206 HLSL Setting

### ISSUE THREAD

**Issue by NJDave71** [mamedev/mame#4572]
I am not sure if i am missing something.   HLSL effects are not being applied at game launch, I have to go in to slider options and change it there.  Here is some of the my mame.ini settings.  
....
#
# DIRECT3D POST-PROCESSING OPTIONS
#
hlslpath                  hlsl
hlsl_enable               1
......
#
# OSD VIDEO OPTIONS
#
video                     d3d
.....

This is been present since .203.   if you have a suggestion I would greatly appreciate it.

**Comment by angelosa** [comment]
It's:
`mame.exe <romname> -video bgfx -bgfx_screen_chains hlsl -bgfx_backend <d3d11/d312/opengl/etc.>`
At present you can't enable HLSL on a non-BGFX video options.

**Comment by cuavas** [comment]
These options currently work.
