### ISSUE TITLE
Most roms do not work

### ISSUE THREAD

**Issue by Jkhemili** [mamedev/mame#462]
Almost every rom I get, It says I need CHD files or something. Please fix this and make more games compatible. Most arcade games like racing and fighting games are my preferences.

**Comment by felipesanches** [comment]
@Jkhemili The MAME developers and contributors are surely working hard to get the emulator working in the best way we can while documenting in a faithful way the technical details of the electronic boards of these devices.

While I can understand your complaint, I must note that this kind of request is not appropriate here in the GitHub issues tracker, as it does not actually present any specific technical issue other than a very generic concern. So this issue must be closed.

**Comment by happppp** [comment]
I think you ate a trollbait there Felipe. This guy did the same thing 2
weeks ago and still pretends to be clueless?
see: https://github.com/mamedev/mame/issues/435

**Comment by mnaberez** [comment]
I'm going to close this issue since there isn't anything specific to address here.  Efforts are always being made to improve emulation generally.

**Comment by Jkhemili** [comment]
you guys are jerks

**Comment by ryantheleach** [comment]
@Jkhemili on the off chance you arn't trolling, CHD's are larger chunks of data, where as rom's are generally small. When you see an error saying you need a CHD, it means that you havn't installed the CHD files correctly and are missing most of the game you are trying to emulate.
