### ISSUE TITLE
Fujitsu FM-7

### ISSUE THREAD

**Issue by Sterophonick** [mamedev/mame#4644]
The Fujitsu FM-7 Emu is unable to load cassette tapes, but loading disks is just fine.

**Comment by Tafoid** [comment]
No issue that I can see and it works fine in my test, loading the software list entry "chackn"

>  mame64 fm7 chackn
>  type: "load"
>  start tape  (goto partial keyboard control with Scroll Lock and TAB ->Tape Control -> Play or use F2)
Loading will start and stop at prompt once basic loader has loaded
>  type "run" to load the tape.

After a long while (tape is nearly 8minutes long) and waiting some time after loading at a black screen, the title screen will show.

In your last issue posted #4633, I urged you to report problems to mametesters.org.  Please do not continue posting regular bug reports here unless they are regression from the last release!
