### ISSUE TITLE
MAME internal UI has priority over keyboard map

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4651]
`0.206 (mame0206-125-gd607efb5d2)`
Debian 9.6 X64
Build options `make clean && make -j9`

Using MAME testkeys to map the TILDE key it returns:
```
ITEM_ID_XY SDL_SCANCODE_APOSTROPHE 0x34 0x40000000 
ITEM_ID_XY SDL_SCANCODE_APOSTROPHE 0x34 0x40000000 ~
```
Using the template map files and the input.cpp for reference to create a test.map:
`ITEM_ID_TILDE     SDLK_APOSTROPHE 0x34 0x40000000 ~`

Load with:
```
./mame64 -v -keymap -keymap_file keymaps/test.map pacman
...
Keymap: Start reading keymap_file keymaps/test.map
Keymap: Processed 3 lines
Keyboard: Start initialization
Input: Adding keyboard #0: System keyboard (device id: System keyboard)
Keyboard: Registered System keyboard
Keyboard: End initialization
...
```
The mapped key fail to call the OSD, mapping the TILDE key to something else doesn't work either, like mapping the "b" key:
`ITEM_ID_TILDE      SDLK_B 0x5 0x62 B`

This happen with any other key you try to map like PAUSE to "c" key, it fails the same.
`ITEM_ID_PAUSE     SDLK_C 0x6 0x63 C`

The only way to map this keys is by setting it manually over UI settings, if this is the case, it makes the keymap option and the map files not very useful.

Attached a ABNT2 keyboard layout for easy reference.
![abnt2_keyboard_map](https://user-images.githubusercontent.com/9029191/52892441-99a45b80-3179-11e9-8c08-9708268e6e3b.png)

**Comment by couriersud** [comment]
Actually everything is working - but the documentation is bad and the keymaps provided with the mame source are completely outdated. These were SDL1.X.Y keymaps and the entries are ignored. Here is an example that would work. Unfortunately there is still a bug in the underlying code which needs to be corrected.

```
[SDL2]
ITEM_ID_TILDE      SDL_SCANCODE_O    0x12 0x00 O
ITEM_ID_O      	   SDL_SCANCODE_MENU    0x12 0x00 O
```
This maps ITEM_ID_TILDE to "O". Now ITEM_ID_O is mapped by default to "O" so you have to map it to something else.

**Comment by katananja** [comment]
Thank you @couriersud!
Your example didn't work over here neither using the values I get from testkeys:
```
[SDL2]
ITEM_ID_TILDE      SDL_SCANCODE_O           0x12 0x6f O
ITEM_ID_O             SDL_SCANCODE_MENU    0x12 0x6f O

```
Maybe they can develop a tool to make an universal keyboard map generator so all systems can benefit from it and catalog different keyboard mappings.

Thank you again for the information, hope they find a way to get it fixed.

**Comment by couriersud** [comment]
As indicated in my comment, there is still a bug in MAME which prevents the example from working.
I however have other changes in the pipeline ... so please have some patience.

**Comment by katananja** [comment]
I'll.
Thank you.

**Comment by couriersud** [comment]
Keymap format has changed now. New working example:

```
[SDL2]
ITEM_ID_TILDE      SDL_SCANCODE_O     O
```
Closing this issue.

**Comment by katananja** [comment]
Hey @couriersud just saw the fix, it's working like a charm!
I'll get a fix for the Brazilian keymap.

**THANK YOU!**
