### ISSUE TITLE
Grand Champion Collision detection

### ISSUE THREAD

**Issue by buverman** [mamedev/mame#4674]
Known issue opened for bounty source. Collision detection is a bit iffy at the moment.

**Comment by happppp** [comment]
Thanks for your concern. This bug is already known and your message is has no added value This isn't the place to advertise your bounties.

**Comment by buverman** [comment]
Thats ok, I am new to bountysource and I thought it was mandatory to have an open issue on github, I didnt mean it as advertisement at all. Cheers.
