### ISSUE TITLE
MAME SDL fails to detect screen boundaries.

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4685]
`mame0206-481-g03493a0405`
Windows 10 x64 1803 (17134.590)
GCC 8.2.1
Build options: `make clean && make OSD=sdl -j5`
Run command: `sdlmame64 -window -maximize`

Non SDL MAME find the screen boundaries just fine, the SDL MAME however overpass the top screen and behind the Windows taskbar.

**MAME**
![mame](https://user-images.githubusercontent.com/9029191/53301989-1ef1d500-3838-11e9-8a9d-bb3ecd6388ae.jpg)

**SDL MAME**
![sdl_mame](https://user-images.githubusercontent.com/9029191/53301991-2d3ff100-3838-11e9-9214-70b977a6709d.jpg)

**Comment by rb6502** [comment]
This is a known issue with SDL; it has no way to determine the "true" desktop size minus menu bars.
