### ISSUE TITLE
Display floating point values in debugger memory window

### ISSUE THREAD

**Issue by yz70s** [mamedev/mame#476]
Currently the debugger memory window lets you view data as 1 2 4 and 8 byte chunks.

Since some of the processors that are emulated in mame support floating point operations natively, it would be useful to show memory contents as floating point values.

A first implementation could show only values in the ieee754 32bit format, but then it colud be expanded with other formats.

**Comment by rb6502** [comment]
Agreed, this would be greatly useful for debugging FPUs and the like.  32 and 64-bit ("float" and "double" on x86) and 80-bit extended (used by x87 and 680x0, at least) would all be interesting formats to support.

**Comment by Lord-Nightmare** [comment]
On 11/22/2015 3:43 PM, R. Belmont wrote:
>
> Agreed, this would be greatly useful for debugging FPUs and the like. 
> 32 and 64-bit ("float" and "double" on x86) and 80-bit extended (used 
> by x87 and 680x0, at least) would all be interesting formats to support.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mamedev/mame/issues/476#issuecomment-158798223>.
>
We might also consider the 16 bit 'half' value, but only newer nvidia 
cards (newer than the one in xbox?) do that, so it may be totally useless.
The 24 bit floats in the namco stuff could also be handy. maybe.

-- 
Jonathan Gevaryahu
jgevaryahu@gmail.com
jgevaryahu@hotmail.com

**Comment by Lord-Nightmare** [comment]
We might also consider the 16 bit 'half' value, but only newer nvidia cards (newer than the one in xbox?) do that, so it may be totally useless. The 24 bit floats in the namco stuff could also be handy, unless they never appear in registers directly?

**Comment by rb6502** [comment]
They appear in registers, it's do they appear in memory that's pertinent here.  This is for the memory viewer, not the CPU register viewer.  (Don't worry, I thought it was the other way around at first too).
