### ISSUE TITLE
MAME fail to link when compiled with clang 7.0.1

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4764]
Windows 10 x64 1803 (17134.590)
Clang 7.0.1
Python 2.7.16
Installed with: `pacman -S mingw-w64-x86_64-clang mingw-w64-x86_64-clang-analyzer mingw-w64-x86_64-clang-tools-extra`

Environment setup:
```
CONFIG_ARCHITECTURE=x64
MINGW=D:\msys64\mingw64
MINGW64=D:\msys64\mingw64
MINGW_PATH=D:\msys64\mingw64\bin
MSYS2_ROOT=D:\msys64
```
Build options: `make clean && make OVERRIDE_CC=/mingw64/bin/clang OVERRIDE_CXX=/mingw64/bin/clang++ PYTHON_EXECUTABLE=/usr/bin/python SOURCES=src/mame/drivers/pacman.cpp SUBTARGET=pacman SYMBOLS=1 SYMLEVEL=1 OPTIMIZE=0 -j5`
Latest commit tested 93ee1e9e2c530068d04a7b5a694cc80338c52696

Clang compile the source all the way through, the problem start at the end linking the final binary. It return a huge output full of this:
```
D:\msys64\mingw64\bin\ld: ../../../../mingw-clang/bin/x64/Release/libfrontend.a(luaengine.o): warning: COMDAT symbol '.text$_ZN3sol8propertyIM12ioport_fieldKFhvEMS1_FvhEEEDcOT_OT0_' does not match section name '//AAmpNr'
D:\msys64\mingw64\bin\ld: ../../../../mingw-clang/bin/x64/Release/libfrontend.a(luaengine.o): warning: COMDAT symbol '.xdata$_ZN3sol8propertyIM12ioport_fieldKFhvEMS1_FvhEEEDcOT_OT0_' does not match section name '//AAmpOq'
D:\msys64\mingw64\bin\ld: ../../../../mingw-clang/bin/x64/Release/libfrontend.a(luaengine.o): warning: COMDAT symbol '.text$_ZN3sol8propertyIM12ioport_fieldKFdvEMS1_FvdEEEDcOT_OT0_' does not match section name '//AAmpWu'
```
[make-output.zip](https://github.com/mamedev/mame/files/2973745/make-output.zip)

**Comment by katananja** [comment]
Fixed 1a66b2ff1e782447f3c7e7713e85d7532522b2fa
```
MAME v0.207 (mame0207-364-g1a66b2ff1e)
Copyright Nicola Salmoria and the MAME team
```
Thank you @ajrhacker

**Comment by ajrhacker** [comment]
I don't think that this linking problem was fixed by my commit. I think a more likely cause would be dirty build conditions which coincidentally resolved themselves when emu.h was touched.

**Comment by katananja** [comment]
It can be, I really don't know.
Your commit fix the issue so, it's all good.
