### ISSUE TITLE
208 Entry point not found error on windows xp - refuses to launch

### ISSUE THREAD

**Issue by minipretzel** [mamedev/mame#4818]
I can't run MAME 208 on windows xp sp3.

You get dialog popup with the following information:

Entry point not found error
GetTickCount64 could not be located in the dynamic link library KERNEL32.dll.

**Comment by DavidHaywood** [comment]
Probably due to the toolchain switchover.

This I guess officially means that XP is now not supported.  The OS is 18 years old, it can't be supported forever.

**Comment by Robbbert** [comment]
GetTickCount64 is a 64-bit only entry-point. Did you download the 64-bit build by mistake?

**Comment by minipretzel** [comment]
No.

**Comment by cuavas** [comment]
It isn't a 64-bit only function. It's available in 32-bit and 64-bit versions of Windows from Vista onwards. I guess this means that it's no longer possible to support XP and Server 2003 with reasonably up-to-date build tools, as the runtime libraries are starting to depend on functions introduced with Vista. You'll be able to build MAME for Windows XP for a while if you can obtain an older version of MinGW GCC 7 and its runtime libraries.

**Comment by Robbbert** [comment]
We may as well make it official (now that we know) - XP is no longer supported.

I've created a XP version for you on my site, and I'll continue to do so each release while it is viable. This one (0.208) is a bit of a rush job, but it should still do what you want. It uses mameui's icon to distinguish it from the official release.

**Comment by minipretzel** [comment]
What site might that be?

**Comment by Robbbert** [comment]
The site is http://messui.1emulation.com/
