### ISSUE TITLE
gaelco3d.cpp regression, black screen pt. 2

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#4874]
MAME v0.208 (mame0208-380-g9a53f84837)

Found during benchmark run in radikalb, confirmed on the other games in the driver.
Win x64 version

Launch any of them and they sit at a black screen.  Looks like I reported a similar issue last year #3848. :)

**Comment by Osso13** [comment]
For me, radikalb seems to work fine with 0.208 and with current GIT (Win X64 version).

**Comment by john-iv** [comment]
Purged cfg/nvram.
I compile w/ a tip of trunk toolchain based on the dist package; doing a pacman -Syu every week or so.  Just updated the toolchain again and did a make, same problem.  I'll check a full clean build tomorrow morning after the chron job at 6am PST.

**Comment by Robbbert** [comment]
I get the black screen with current git (WIN 32 bit)

**Comment by Tafoid** [comment]
This is likely more emumem regression from changes on April 6, 2019:
https://github.com/mamedev/mame/commit/8e551e167c5f4fda3fcff4393fbdcce49711dcbd

Since the driver itself hadn't seen adjustment, the driver hasn't been tested after this change yet.

**Comment by Osso13** [comment]
My apologies, it seems the build I was trying wasn't really current. I can confirm the issue and I can confirm that adjusting the right shift of the latches' hook up, like AJR suggested for equites.cpp in the comments of the commit Tafoid links, gets around the issue.
Specifically gaelco3d.cpp seems happy with offset >> 3 for the mainlatch and offset >> 4 for the outlatch (both for main_map and main020_map).

**Comment by couriersud** [comment]
Fixed. Thanks to Osso13 for the hints.
