### ISSUE TITLE
Attempt to register save state entry (error)

### ISSUE THREAD

**Issue by lab313ru** [mamedev/mame#491]
"Attempt to register save state entry after state registration is closed!
Module M68000 tag :maincpu name REG_D(this)"

Visual Studio 2015, debug mode. **genesis** platform. save.cpp:
```c++
// check for invalid timing
	if (!m_reg_allowed)
	{
		machine().logerror("Attempt to register save state entry after state registration is closed!\nModule %s tag %s name %s\n", module, tag, name);
		if (machine().system().flags & MACHINE_SUPPORTS_SAVE)
			fatalerror("Attempt to register save state entry after state registration is closed!\nModule %s tag %s name %s\n", module, tag, name);
		m_illegal_regs++;
		return;
	}
```

**Comment by lab313ru** [comment]
Please, delete. My code mistake.

**Comment by lab313ru** [comment]
I'm trying to read memory after this:
```c++
// disallow save state registrations starting here.
// Don't do it earlier, config load can create network
// devices with timers.
m_save.allow_registration(false);
```
And it gives me this error.

**Comment by galibert** [comment]
You're not trying to read memory, you're calling save_item or something
else of that family...

**Comment by lab313ru** [comment]
I'm not calling save_item function directly. It callable by device_start(). By some strange thing, read_byte() calls device initialization. I can't understand that.

**Comment by galibert** [comment]
I don't think you can reasonably call read_byte before device reset, let
alone initialization, and even then is iffy.

  OG.

**Comment by startaq** [comment]
Closing this since it doesn't seem to be an actual issue in MAME.
