### ISSUE TITLE
Mac emulations not working.

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#4924]
Due to various issues with the 6522 VIA chip, all Macintosh emulations are either failing completely to boot, or have serious bugs. I am creating this issue to:

1) Track changes and discussion of 6522 code updates.
2) When this is marked resolved it will serve as a notice that most if not all of these Mac emulation issues are resolved.
3) Give visibility to this problem, especially to developers of other system which also use the 6522 VIA chip, so they can be more aware that any updates they make also impacts the Mac emulation.

**Comment by abcbarryn** [comment]
Much of this appears to be a regression, as many Mac emulations were working as of release 0.186. I am current checking release 0.192, and will report back what I find.

**Comment by rb6502** [comment]
Yeah, no, we don't do open bugs for systems marked as NOT_WORKING.  That's the entire reason I marked them as NOT_WORKING.  You may open new bugs on mametesters.org system-by-system if and when they are marked as working again.
