### ISSUE TITLE
MESS: Game Boy Color sound is inaccurate

### ISSUE THREAD

**Issue by wescopeland** [mamedev/mame#499]
Hi,

I'm currently playing zeldaldxja (Link's Awakening DX, Japanese Revision A). Many pitches in the audio sound a quarter-step off key. I couldn't find any issue listed like this, so I just wanted to make sure it was known.

**Comment by DopefishJustin** [comment]
http://mametesters.org/view.php?id=4949

**Comment by wescopeland** [comment]
Gotcha, sorry about that.
