### ISSUE TITLE
NeoGeo CD Not Work in MAME 0.209

### ISSUE THREAD

**Issue by ToniBC** [mamedev/mame#4996]
Hello, it turns out that the latest version of MAME, the 209, the NeoGeo CD games stopped working, in the 208 they work without problems, but in the 209 it remains in the CD menu of the NeoGeo CD waiting for the insertion of the CD.

Everything is correct, the image is loaded, but something changed that does not start any game.

**Comment by ajrhacker** [comment]
This has already been reported at MAMETesters (the preferred place for reporting these kinds of bugs) and fixed:

https://mametesters.org/view.php?id=7296

**Comment by ToniBC** [comment]
Thanks, I did not know that place.
