### ISSUE TITLE
MAME 0.209 on RetroArch Game Music Issues

### ISSUE THREAD

**Issue by detectorcaleta1** [mamedev/mame#5018]
Hello,

I was testing several games on MAME 0.209 on RetroArch and I noticed issues on the Game Music, if you compared the Standalone Emulator and the Core on RetroArch, the music sounds different. Previous versions had the same exact issues such as MAME 0.206, 0.203, etc.

You can hear the music in different tone or modulation, game music is not accurate, the music on MAME 2003-Plus Core on RetroArch sounds very accurate, like Standalone Emulators. 

You can test and compare the game Gunlock or Rayforce on MAME 0.209 Standalone and on RetroArch. Listen to the music carefully before gameplay on both emulators, also you can test the game Rohga Armor Force or Wolf Fang.

Thank you in advance.

**Comment by DavidHaywood** [comment]
This is not RetroArch support.

Using MAME in RetroArch is not recommended at all, in any form.
