### ISSUE TITLE
This is not RetroArch support.

### ISSUE THREAD

**Issue by detectorcaleta1** [mamedev/mame#5023]
This is not RetroArch support.

Using MAME in RetroArch is not recommended at all, in any form.

_Originally posted by @DavidHaywood in https://github.com/mamedev/mame/issues/5018#issuecomment-490837887_

Explain me, why you there is a MAME port on RetroArch?

If you don't want to fix it, is not my problem, I am going to keep posting this issue until somebody else notice it an does his job.

**Comment by happppp** [comment]
You're posting it on the wrong github repository, we don't maintain the retroarch fork. Try here: https://github.com/libretro/mame/issues

**Comment by Tafoid** [comment]
Simply put, RetroArch/Libretro and all projects associated are taking specific MAME core versions from different eras and modifying them to fit their needs for their front-end project.  So, if an issue cannot be duplicated with the latest release of MAME for Windows available for download from https://www.mamedev.org/release.php or even one of many direct/unmodified ports to other Linux/Unix based Operating Systems available at https://wiki.mamedev.org/index.php/SDL_Supported_Platforms - there is nothing for the MAME project to do.  We don't package and specific MAME emulations or version for RetroArch/Libretro and they keep all the pieces is something goes wrong.

**Comment by Tafoid** [comment]
As @happppp suggested above, the best place for your help would be to use their repository linked earlier.  Closing.

**Comment by DavidHaywood** [comment]
Oh, nice, another toxic RetroArch user, @detectorcaleta1 I suggest you consider your attitude.
If you keep opening issues about this you'll just end up banned from doing so.

MAME has nothing to do with RetroArch, there is not a shred of RetroArch support code in this repository.

The abomination that is MAME in RetroArch is maintained entirely elsewhere and is full of code mods that have nothing to do with us and are generally harmful when it comes to the quality of emulation.  Honestly, we wish they'd just drop it entirely and that nobody at all used MAME in RetroArch.

**Comment by detectorcaleta1** [comment]
Thank you so much for explaining me how to proceed @happppp @Tafoid, if you explain it like this I going to understand it, when I read this stupid answer from @DavidHaywood I said, what? I was polite with you pendejo, I am not toxic, I was just reporting the issue. If you don't want to help, go away, you are such a pusillanimous. You began all of this with your attitude, I am not going to let an ignorant, lazy, treat me like that.

**Comment by DavidHaywood** [comment]
You opened a 2nd issue, after your original issue was closed, specifically tagged me in it, and threatened to keep opening more issues.

That's toxic behaviour.

**Comment by detectorcaleta1** [comment]
@DavidHaywood I am learning here how to post issues here, I am new, but next time be polite, be a gentleman and explain how to post issues, I am sorry if I tagged you. How is toxic now? Me? Why? Be kind and polite, choose your words carefully.

**Comment by DavidHaywood** [comment]
Ok, well for the future, please note, if somebody closes your issue, reopening it, or creating another issue is considered rude and isn't going to result in a positive response.

**Comment by detectorcaleta1** [comment]
Ok man, don't cry, as I said above, I am learning, when I saw the post closed I was wondering why? Why your attitude? That's why I opened it another one. Well, I don't want to continue with this discussion, I have to go to work, but please, next time, BE GENTLE, EXPLAIN, BE POLITE, OK? Bye now.

**Comment by detectorcaleta1** [comment]
Regarding MAME on RetroArch, we need other options, there are a lot of cores that work better than standalones.
