### ISSUE TITLE
mame starWars does not support custom controls  (except v.106)

### ISSUE THREAD

**Issue by swars-xwing** [mamedev/mame#5103]
I built my own flight controller with potentiometers on the x and y axis hooked up to a u-hid board. No version of mame except v.106 works properly with it (its dinput ). I would like to use the newer version of mame but am prevented from doing so. I suspect this is also a problem with the nintendo switch but I prefer my control.

I love this game and playing on  v .106 is not esp a burden, but I would like this documented (i found this on emu paradise forums from ngios as I was prepared to throw my control out). I would also like someone to look at extending a special driver if required to work with this awesome old school game!

**Comment by rb6502** [comment]
Set this line like so in your mame.ini:

joystickprovider          xinput

And MAME will work with any Xinput-compliant device.

**Comment by swars-xwing** [comment]
Ok little egg on my face .. its not xinput .. its the hid dinput interface. I know after I looked it up and  
-joystickprovider xinput failed to work. I do appreciate the reach out I really do. Also I did try it i even tried -joystickprovider dinput which did not help (but the control was recognized).

This is something I put about 10 hours into over several weeks (honest). Also I chased so many things like settings, and command line options .. I never dreamt it was the mame version till I read it, tried it and it was the only thing that worked.

So to be a little clearer any other version of mame does not fail outright to work with the control. There is a choppy digitized tracking of the movements. But v.106 is the ONLY version without any special settings that works properly. Its such a wonderful game when it works, and I would like to upgrade beyond 2006 ... Also it appears this is isolated to star wars. 

If anyone would like I can provide my command line setting and a small video of what constitutes a working control (v .106) and the chopped up version  which == failure.

**Comment by swars-xwing** [comment]
Ok you can close this out. The issue had nothing to wi  v.106 as a workaround at all.
Alan-1 (Atari Star Wars Yoke Controller Reproduction) has an excellent document on this
May the force be with you:

'''
The Deadzone:
The original MAME settings aren't ideal for the yoke. The "dead zone" (range of motion that doesn't register as movement) is way too high. I ended up setting mine to zero, but anything closer to zero will be much better than the original settings. In addition to the deadzone in MAME, Linux by default also adds in a deadzone, this is currently being looked into.
'''

**Comment by rb6502** [comment]
Thanks for letting us know what the resolution is!
