### ISSUE TITLE
6809/6809E clock divider issue ?

### ISSUE THREAD

**Issue by jfdelnero** [mamedev/mame#513]
Hi,

There is something strange with the clock setting into the 6809 emulation : 

The MC6809 chip have an on chip oscillator to generate the E & Q clocks. E & Q frequency = Crystal Freq / 4 (Into the MC6809 / EF6809 datasheet : " On-chip Oscillator (Crystal Frequency = 4 \* E) "

The MC6809E doesn't have this on-chip oscillator and the E & Q clocks need to be provided from an external circuit. There is no internal clock divider in this case.

The problem is that the clock divider is set to 4 for the MC6809E and to 1 for the MC6809 into m6809.cpp (see the m6809_device and m6809e_device constructors). For me the MC6809 divider should be set to 4 and the MC6809E divider to 1.

To have the correct software speed execution into the Squale driver, i have to choose the MC6809E CPU. But the Squale use a 6809 CPU with an internal oscillator (EF6809P). The 3.5Mhz clock input was checked on the pcb.

What do you think about this ? Am i missing something ?

Best Regards,
Jean-François DEL NERO

**Comment by Cowering** [comment]
Seeing this reminded me of something I saw while playing with GCC flags 
before we switched to 5.2.   I am looking at my (gasp) paper copy of the 
6809 user manual I used in college and there is no ASL16 (among others) 
in the manual. ASL16 is in 6809 baseops file though.  It is the reason 
the GCC pragma override is in those files. Shouldn't the extra opcodes 
be broken out into whatever CPU variation has them (konami?)?

Cow

**Comment by milliluk** [comment]
@Cowering The base file is base6x09.ops (note the 'x') and is shared by the family (6809, 6309, Konami). m6809.ops does not have a mapping for ASL16. The Hitachi 6309 and Konami variants do. Looks right.

**Comment by startaq** [comment]
Pinging @npwoods. Do we need to do something here?

**Comment by npwoods** [comment]
This is related to some questions that @tlindner was asking earlier (about why the CoCo clock is at ~3.57MHz).  The short story is that the way that the 6809E clock emulation works is hokey.

The M6809E is driven by external E/Q clock inputs, and there is no internal divider.  Something external is driving those E/Q clock inputs; on the CoCo 1/2 that is a 6883 SAM chip and on the CoCo 3, its the GIME chip.  On those machines, the crystal driving those is actually 16 or 8 times faster than the CPU clock (depending on the how those chips are configured).

It isn't clear to me where the 4 divider in the current code came from.  I'm guessing that it is nonsense.

Also, looking through much of the MAME source, I see sketchy comments regarding how 6809E's are actually clocked:

```
pegasus.cpp(482):	MCFG_CPU_ADD("maincpu", M6809E, XTAL_4MHz)  // actually a 6809C - 4MHZ clock coming in, 1MHZ internally
rd100.cpp(91):	MCFG_CPU_ADD("maincpu",M6809E, XTAL_4MHz)  // freq unknown
squale.cpp(782):	MCFG_CPU_ADD("maincpu",M6809E, CPU_CLOCK) // 12/2015 : Should be set to M6809 but it actually have the wrong clock divisor (1 instead of 4) and working 4 times too fast...
esq1.cpp(588):	MCFG_CPU_ADD("maincpu", M6809E, 4000000)    // how fast is it?
```

I'm guessing the 4 divider is nonsense.

**Comment by tlindner** [comment]
"The Q clock leads the E clock by approximately one half of the E clock time", Page 1-7, MC6809 Microprocessor Programming Manual.

I think a case could be made that two clock signals 180° out of phase could be considered a single 4x clock.

But nobody I know in the 6809 community thinks like this.

**Comment by ajrhacker** [comment]
"The crystal or the external timing source is four times the resulting bus frequency," according to the description of the EXTAL and XTAL pins in the _MC6809-MC6809E 8-Bit Microprocessor Programming Manual_ (Motorola Inc., 1981), 1-6.

**Comment by tlindner** [comment]
Yup. The [datasheet](http://www.gbgmv.se/dl/doc/md09/MC6809_DataSheet.pdf) for the 6809 (non-E version) lists the crystal frequency = 4 × E. So on a non-E 6809 the E and Q *output* clocks are divided by 4.

But on the 6809E the E and Q *input* clocks are used as is. There are no pins for a crystal connection.

**Comment by kazblox** [comment]
Just going to provide a little example tidbit for why such a PR is necessary...

City Connection schematics specify an 8MHz crystal input for a 6809, which seems completely illogical. The datasheet quote from AJR would make sense for a real 6809, given that the internal frequency is probably and very sensible, at 2MHz.

**Comment by Robbbert** [comment]
The mc6809 issue has been solved by AJR. Closing.
