### ISSUE TITLE
Black screen in primal rage [regression]

### ISSUE THREAD

**Issue by GeraBlackHnd** [mamedev/mame#5153]
MAME 0.210 primal rage don´t render anything, only black screen.

**Comment by Osso13** [comment]
works fine here, can you provide more context? Have you tried deleting nvram and cfg files?

**Comment by GeraBlackHnd** [comment]
You got it! The was nvram. Works now. Thanks.

**Comment by MooglyGuy** [comment]
Good to hear. Closing as it is resolved. :)
