### ISSUE TITLE
Compile Size

### ISSUE THREAD

**Issue by NJDave71** [mamedev/mame#5161]
I like to compile MAME for windows and I have notice the the size is often larger the official windows binary.   Is there a switch i can add to make it the same size?

**Comment by Tafoid** [comment]
The make switches for what I use to make a release-type build are below.  You can add the **-j** command depending on your computer/setup.  I'd suspect your are simply not stripping the binary of symbols which is making it larger.

**32-BIT**
> PTR64=0 OPTIMIZE=3 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1 ARCHOPTS="-msse2 -mfpmath=sse"

**64-BIT**
> PTR64=1 OPTIMIZE=3 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1
