### ISSUE TITLE
Lua Engine: Only one screen in machine().screens enumeration

### ISSUE THREAD

**Issue by charbonnierm** [mamedev/mame#5174]
Windows 10, MAME 64bits 0.209

Two screens are enabled in MAME (Screen 0 and Screen 1)
```
#
# OSD VIDEO OPTIONS
#
numscreens                2
```
But when I enumerate available screens, it displays only one

```
PS Z:\mamedev> .\mame64.exe ssf2xjr1r -console
    _/      _/    _/_/    _/      _/  _/_/_/_/
   _/_/  _/_/  _/    _/  _/_/  _/_/  _/
  _/  _/  _/  _/_/_/_/  _/  _/  _/  _/_/_/
 _/      _/  _/    _/  _/      _/  _/
_/      _/  _/    _/  _/      _/  _/_/_/_/

mame 0.209
Copyright (C) Nicola Salmoria and the MAME team

Lua 5.3
Copyright (C) Lua.org, PUC-Rio

[MAME]> for i,v in pairs(manager:machine().screens) do print(i) end
:screen
[MAME]>
```

**Comment by MooglyGuy** [comment]
machine().screens enumerates the number of screens that the emulated machine has. The "numscreens" INI option is used to specify how many physical screens that the host machine has. ssf2xjr1r has only one screen. MAME is working as intended.
