### ISSUE TITLE
psikyosh.cpp games are crashing after exit

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#519]
psikyosh.cpp games are crashing when you exit MAME.

**Comment by rb6502** [comment]
This issues list does not replace MAMETesters for bug reports.

**Comment by Tafoid** [comment]
It is a valid current GIT tree issue with all game Using DRC.  It is being looked into

**Comment by Robbbert** [comment]
if the issue existed at the last release then it should have been reported at MT. But if it's new, then this is the correct place.

Unfortunately the reporter did not supply any details, no crash dump, or regression version.
Please try again.

**Comment by MASHinfo** [comment]
Issue has been fixed by Miodrag Milanovic:
https://github.com/mamedev/mame/commit/c66ddfc1db547521e62d49edb6fba70a3861b718
