### ISSUE TITLE
Improve debugging support for address spaces

### ISSUE THREAD

**Issue by ajrhacker** [mamedev/mame#5212]
MAME originally only allowed CPUs to have address maps, and the number of address spaces was strictly limited until not so long ago. The architecture of MAME's debugger still incorporates these restrictions in some frustrating ways:

- Debugger commands and expressions can only reference the standard four spaces, each identified by a single letter. Extending this syntax may not be convenient, though.
- Watchpoints can only be set on CPU spaces, and only on the standard four spaces. The `wpset` command could be extended, but ideally one should be able to create a new watchpoint on any space through the memory view window or watchpoint view window.

There seem to be long-term plans to replace the functionality of MAME's debug console with one that uses Lua expressions instead, but no work appears to have been done towards this end in the past few years.

**Comment by Happy-yappH** [comment]
Is there also a limitation that you cannot issue a command for a CPU until that CPU becomes actively selected by the emulation?  (i.e. the emulation will not stay paused but will run until that CPU gets a timeslice)  I realize that it may not be possible to reliably alter CPU state if that CPU is not running, but perhaps a breakpoint can be set for that CPU without the emulation being unpaused?  Would it be possible to extend the syntax such that there is no ambiguity in specifying which device the command is for?

**Comment by ajrhacker** [comment]
Breakpoints can actually be set through the disassembler view window now.

**Comment by cuavas** [comment]
Debugger support for extended address spaces is addressed as of 2327c5e785fe6be28e515ea7103f6be720362ab5.
