### ISSUE TITLE
Compiling and Running Mame on Debian minimal > Freeze when a joystick is connected

### ISSUE THREAD

**Issue by makotoworkshop** [mamedev/mame#5215]
Hello all !

I've successfully build _Mame 0.208_ from sources on _Debian Stretch_ (9.9.0) **minimal install**, like this : https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.9.0-amd64-netinst.iso
So there is **no Desktop** environment like _Gnome_, _Kde_ or something else, Just _**Xorg**_, that's all.
`apt install -y xserver-xorg-video-all xfonts-base xinit x11-xserver-utils alsa-base alsa-utils  firmware-linux-nonfree`
To execute _Mame_, therefore i start graphical environment by « **StartX** ».

- With my old _Mame 0.161_ compiled in year 2016 with _SDL1_, no problems, all works very well, Joysticks, Keyboard…
- With this _Mame 0.208_ compiled with _SDL2_ (no choice now), all works very well, if no USB Joystick is connected, playing and navigation in menus with Keyboard is ok.
--> But ! **Execute Mame when a USB Joystick is connect, cause the Keyboard and Joystick take's no action, all seems frozen** :(

I've spend a lot of time to find a solution, and i've resolved this problem by installing a Desktop environment like _Gnome_.
For any reason, it might have a package that's fill the missing element to get Joystick work properly.

--> I've tried to know what packages can be concerned, but with no results…

So my question is : 
- What's component is missing to have joystick work properly with the lasts mame SDL2 and NO Desktop ?

Thank's for reading this,
Regards, 
Makoto

If you want tried to reproduce this issue, you can download the preinstalled iso i've build here : 
https://burogu.makotoworkshop.org/index.php?post/2018/05/08/makotonoakedo2

**Comment by makotoworkshop** [comment]
Anyone have an explanation ?
An idea about this issue ?
Some tracks i can follow to research solution for launching Mame with no desktop environment installed ?

**Comment by Tafoid** [comment]
I've heard of problems with the very latest SDL2 2.0.9 or later (assuming you are using most recent avaialble).  If you can, try using 2.0.8 instead.

**Comment by makotoworkshop** [comment]
The issue i described have made under _debian 9.9 « stretch »_, the package version is : _libsdl2-dev (2.0.5+dfsg1-2)_ https://packages.debian.org/stretch/libsdl2-dev

The lastest recent _debian 10 « buster »_ come with version _Paquet : libsdl2-dev (2.0.9+dfsg1-1)_  https://packages.debian.org/fr/buster/libsdl2-dev
So i can't test with version 2.0.8, and i hope the problems you think about are not linked with the issue i described, but i keep the idea to test another new version, since i detect the issue last year, i've not think to do that…

-> I'll install Debian 10 and compiling with SDL 2.0.9.
Thanks !

**Comment by makotoworkshop** [comment]
I'm back with tests résults :
_**Debian 10**_ fresh install ( by default for now come with _libsdl2-2.0-0:amd64 > 2.0.9+dfsg1-1_) with :  
`apt install -y xserver-xorg-video-all xfonts-base xinit x11-xserver-utils alsa-utils`
and for compiling _mame0208s_ with :
`apt install git build-essential python libsdl2-dev libsdl2-ttf-dev libfontconfig-dev qt5-default`
and simple :  
`make -j3`
Executing the resulting _mame64_ :
- mouse ok in menu.
- keaboard is frozen.
- Joystick is frozen.

I can just navigate in the Mame menus with the mouse, try to attribute some keys to inputs functions, but when i press somes keys, nothing happen…

I'll search how to install older SDL2 version…
But, i'm pretty sure that will not working, and installing gnome desktop will resolve the problem,
cause that's not responding to my firts question :

- What's component is missing to have joystick work properly with the lasts mame SDL2 and NO Desktop ?

**Comment by makotoworkshop** [comment]
Ok, i just install minimal mate desktop : 
`apt install mate-core`

Annnnnnd magic !
All input device are working, USB Keyboard and Joystick Ok !

The desktop come with a package that resolve the problem, but which is it ?
So the question still be : 
- What's component is missing to have USB Joystick work properly with the _Mame SDL2_ and NO Desktop ?

**Comment by makotoworkshop** [comment]
For more informations, here the list of all the packages installed by the « mate-core »

```
Les NOUVEAUX paquets suivants seront installés :
  accountsservice albatross-gtk-theme blackbird-gtk-theme bluebird-gtk-theme
  caja caja-common dbus-x11 debian-mate-default-settings desktop-file-utils
  dosfstools enchant exfat-fuse exfat-utils fonts-cantarell fonts-dejavu
  fonts-dejavu-extra fuse gcr gdisk gnome-keyring gnome-keyring-pkcs11
  greybird-gtk-theme gstreamer1.0-gl gstreamer1.0-plugins-base
  gstreamer1.0-plugins-good gstreamer1.0-pulseaudio gstreamer1.0-x
  gtk2-engines gtk2-engines-murrine gtk2-engines-pixbuf gvfs gvfs-backends
  gvfs-common gvfs-daemons gvfs-libs hunspell-en-us libaa1 libaacs0
  libaccountsservice0 libarchive13 libatasmart4 libavahi-glib1 libavc1394-0
  libayatana-appindicator3-1 libayatana-ido3-0.4-0 libayatana-indicator3-7
  libbdplus0 libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2
  libblockdev-part-err2 libblockdev-part2 libblockdev-swap2 libblockdev-utils2
  libblockdev2 libbluray2 libbrotli1 libcaca0 libcaja-extension1
  libcanberra-gtk3-0 libcanberra-gtk3-module libcanberra0 libcdio-cdda2
  libcdio-paranoia2 libcdio18 libcdparanoia0 libdbus-glib-1-2
  libdbusmenu-glib4 libdbusmenu-gtk3-4 libdv4 libenchant1c2a libexempi8
  libexif12 libgail-3-0 libgail-common libgail18 libgck-1-0 libgcr-base-3-1
  libgcr-ui-3-1 libgd3 libgdata-common libgdata22 libgoa-1.0-0b
  libgoa-1.0-common libgpgme11 libgphoto2-6 libgphoto2-l10n libgphoto2-port12
  libgpm2 libgraphene-1.0-0 libgstreamer-gl1.0-0
  libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libgtop-2.0-11 libgtop2-common libharfbuzz-icu0
  libhunspell-1.7-0 libhyphen0 libiec61883-0 libimobiledevice6
  libjack-jackd2-0 libjansson4 libjavascriptcoregtk-4.0-18 libldb1 libltdl7
  libmarco-private1 libmate-desktop-2-17 libmate-menu2
  libmate-panel-applet-4-1 libmate-slab0 libmate-window-settings1
  libmatekbd-common libmatekbd4 libmatemixer-common libmatemixer0
  libmateweather-common libmateweather1 libmp3lame0 libmpg123-0 libmtp-common
  libmtp-runtime libmtp9 libnfs12 libnotify4 libnspr4 libnss3 libntfs-3g883
  liboauth0 libopenjp2-7 libopus0 liborc-0.4-0 libpam-gnome-keyring
  libparted-fs-resize0 libparted2 libplist3 libpolkit-agent-1-0
  libpolkit-backend-1-0 libpolkit-gobject-1-0 libpython2.7 libraw1394-11
  librda-common librda0 libsecret-1-0 libsecret-common libshout3 libsmbclient
  libspeex1 libstartup-notification0 libtag1v5 libtag1v5-vanilla libtalloc2
  libtdb1 libtevent0 libtheora0 libtwolame0 libudisks2-0 libusbmuxd4 libv4l-0
  libv4lconvert0 libvisual-0.4-0 libvolume-key1 libvorbisfile3 libvpx5
  libvte-2.91-0 libvte-2.91-common libwavpack1 libwbclient0
  libwebkit2gtk-4.0-37 libwebpdemux2 libwnck-3-0 libwnck-3-common libwoff1
  libxklavier16 libxpresent1 libxres1 libxslt1.1 libyelp0 marco marco-common
  mate-control-center mate-control-center-common mate-core mate-desktop
  mate-desktop-common mate-desktop-environment-core mate-icon-theme mate-menus
  mate-panel mate-panel-common mate-polkit mate-polkit-common
  mate-session-manager mate-settings-daemon mate-settings-daemon-common
  mate-terminal mate-terminal-common mate-themes mate-user-guide menu menu-xdg
  murrine-themes notification-daemon ntfs-3g p11-kit p11-kit-modules parted
  pinentry-gnome3 policykit-1 psmisc python-mate-menu python-talloc
  python3-distro samba-libs sound-theme-freedesktop udisks2 usbmuxd yelp
  yelp-xsl zenity zenity-common
0 mis à jour, 223 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 127 Mo dans les archives.
Après cette opération, 560 Mo d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] 
```

**Comment by rb6502** [comment]
This seems like a mis-packaging of SDL2 by Debian if some library it relies on to function isn't automatically installed with it.  I'd open a bug with them, because this is clearly not MAME's fault.

**Comment by makotoworkshop** [comment]
Okay, thank you for your explanation, it sound logic !
Please feel free to forward here the link to the bug you'll open, i wanted to follow this carefully, it must be interesting.
So this library problem might be exist since a long time, cause i've found it the first time on compilation of Mame0.161 on April 2016, under  Ubuntu 14.04LTS et Debian 8.

**Comment by MooglyGuy** [comment]
We are not going to open any bug. It is your responsibility to open the bug with the Debian maintainers.
