### ISSUE TITLE
TMS7000 TIMER1 clock divider seems incorrect

### ISSUE THREAD

**Issue by tlindner** [mamedev/mame#5236]
https://github.com/mamedev/mame/blob/651c467df4d03259a2c22217bb5671574eb5469b/src/devices/cpu/tms7000/tms7000.cpp#L441

The clock divider was changed a few years ago from 16 to 8. But my investigation with MAME Tester Bug 7361 <https://mametesters.org/view.php?id=7361>, seems to indicate that a value of 16 is correct for the TMS7000.

**Comment by happppp** [comment]
The comment says /16. So maybe someone moved the clock divider from driver side to cpu core side and forgot to update the timer divider. Anyway, why not do a PR instead of issue?

**Comment by tlindner** [comment]
Because I wanted to discuss this change before the PR. It affects drivers I have no personal knowledge of.

**Comment by happppp** [comment]
I checked the history and it looks like I'm the cause of the bug, insert slowclap. I'll go ahead and apply your fix. My cc40 and ti74 drivers appear to be working fine with it.

**Comment by ajrhacker** [comment]
The TMS70Cx2 uses fOSC/4 rather than fOSC/16 as the timer base. Fortunately MAME doesn't have to worry about that at the moment.

I was slightly worried about possibly breaking the M24 keyboard, but it doesn't seem to have been harmed.
