### ISSUE TITLE
Debugger 'save' command is broken for CPUs with shifted address maps

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#5309]
Steps to Reproduce:
1. Start MAME using the following command: mame64 nbajam -debug
2. Close the debugger window and allow the game to run.
3. After proceeding to the title screen, press the tilde key to break into the debugger.
4. Open a memory window and go to address 1800000, which corresponds to the machine's palette.
5. Observe that the data looks like valid 16bpp palette data.
6. In the main debugger window, invoke the following command: "save palette.bin,1800000,80000"
7. Open the resulting file in a hex editor.
8. Observe that the file is only 64kbytes in size, not 512kbytes, and additionally does not contain anything resembling the data shown in the memory window.

**Comment by Tafoid** [comment]
Just to follow up regression testing - breakage happened surrounding the big emumem rewrites.  This dates it back to November 29, 2017:  https://github.com/mamedev/mame/commit/c46e1007a8c0b42b7c50dce9b8bc9dff0db328e5

**Comment by ajrhacker** [comment]
I just corrected this bug and a similar one in the save command. It was specific to memory spaces with an address shift of +3 (i.e. TMS34010/020).
