### ISSUE TITLE
unpleasant opengl performance

### ISSUE THREAD

**Issue by Askmewho** [mamedev/mame#5310]
Hi!
I've compiled version 0.201 to test opengl 2.1 full profile on rpi3. mesa 19 give me a boost on any
emulator Ive tried so far... but here, its awful, performance doesnt change neither if I select software or opengl. opengl output only benefits the GUI performance, but inside the games its jus the same. Dont know if it using gles or GL, could someone give me any advice of how to understand whats happening or what parameter I should set to use correctly opengl??

right now I am on an rpi3 with mesa 19.1 and sdl2 2.0.9 with full opengl profile.  thanks on advance

**Comment by MooglyGuy** [comment]
Sounds like it's the Pi3's anemic CPU that's the problem, and nothing to do with OpenGL. You said it yourself, OpenGL output benefits the GUI performance.

You haven't even specified what games you're trying to run, so for all any of us know you're trying to run Daytona USA 2 or something crazy like that. But at the end of the day, we don't support MAME on the Raspberry Pi and are unlikely ever to. Best of luck.
