### ISSUE TITLE
Burning Force (burnforc, burnforco) - Graphical Error

### ISSUE THREAD

**Issue by PixelCrusader** [mamedev/mame#5331]
When playing Burning Force on recent versions of MAME, a graphical error can be veiwed on the horizon line; a strip of color along the middle and right side of the screen which unbalances the horizon. This error gets worse when jumping off a ramp or playing the flying stages, in which it clearly separates from the rest of the ground textures:

![burnforc-190711-174841](https://user-images.githubusercontent.com/40935002/61089221-6bfdce80-a408-11e9-9874-ac7a1e2f7e6e.png)

![burnforc-190711-174906](https://user-images.githubusercontent.com/40935002/61089225-6f915580-a408-11e9-852f-0f3274aab0f7.png)

![burnforc-190711-175006](https://user-images.githubusercontent.com/40935002/61089231-728c4600-a408-11e9-9b55-0ec261266711.png)

It looks like this behavior begins at version 0.146 and continues on to the current version 0.211. Older versions don't display this behavior:

![burnforc-190711-175127](https://user-images.githubusercontent.com/40935002/61089273-92bc0500-a408-11e9-903c-6e0d01e3a753.png)

![burnforc-190711-175217](https://user-images.githubusercontent.com/40935002/61089280-96e82280-a408-11e9-9dd5-542d2c1f9018.png)

![burnforc-190711-175315](https://user-images.githubusercontent.com/40935002/61089288-9a7ba980-a408-11e9-957f-cd0cbbaa6523.png)

**Comment by Tafoid** [comment]
Already logged and known:
https://mametesters.org/view.php?id=6944

No need to have this open.
