### ISSUE TITLE
duplicate disk image name

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#5366]
Both `mtchxlgldo` and `mtchxlti` have a disk called `r00`.
Please rename one of the two.

**Comment by rb6502** [comment]
Different sets are allowed to have the same CHD names.

**Comment by 0-wiz-0** [comment]
I got that told last time I reported this for a different chd as well, but this is currently the only one that actually does have the same name as another one, and I think it's easy to fix.

**Comment by rb6502** [comment]
Yeah, no.  We don't formally support CHDs in a flat file structure, only with the subdirectories.
