### ISSUE TITLE
libSDL2.so not found

### ISSUE THREAD

**Issue by mudi256** [mamedev/mame#5374]
Hello, libSDL2.so not found ,please share libSDl.so file

**Comment by MooglyGuy** [comment]
SDL is a third-party library, you need to install the correct package. This is not a MAME issue.

**Comment by rb6502** [comment]
Specifically, on Fedora the package names are SDL2-devel and SDL2_ttf-devel.   On Debian/Ubuntu it's libsdl2-dev libsdl2-ttf-dev.  Arch is sdl2 and sdl2_ttf.
