### ISSUE TITLE
Suppress white box initializing...

### ISSUE THREAD

**Issue by NJDave71** [mamedev/mame#5419]
When launching games from a command line is there a way to suppress "initializing..." text and white box?   this also displays when loading the UI before populating the ROM list?

**Comment by happppp** [comment]
It is intentional, no issue. The only way to get rid of them is compiling your own version. The init text is in frontend/mame/mame.cpp line 313. The stupid white box is in emu/render.cpp line 1366.

**Comment by cuavas** [comment]
I object to the characterisation of the white box as "stupid" - it's very useful for monitor adjustment if you've configured MAME to switch video modes.
