### ISSUE TITLE
Can't Compile Windows 64 Error

### ISSUE THREAD

**Issue by NJDave71** [mamedev/mame#5447]
I have been compiling MAME since 0192 and not I experiencing issues.

After 4 unsuccessful tries to compile MAME0212 
**make -j5 PTR64=1 OPTIMIZE=3 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1**

Compiling src/lib/formats/x07_cas.cpp...
Compiling src/emu/romload.cpp...
Compiling src/lib/formats/x1_tap.cpp...
Compiling src/emu/save.cpp...
Compiling src/emu/schedule.cpp...
Compiling src/lib/formats/xdf_dsk.cpp...
Compiling src/lib/formats/zx81_p.cpp...
Compiling src/emu/screen.cpp...
Compiling src/emu/softlist.cpp...
Archiving libformats.a...
Compiling src/emu/softlist_dev.cpp...
Compiling src/emu/sound.cpp...
Compiling src/emu/speaker.cpp...
Compiling src/emu/tilemap.cpp...
Compiling src/emu/uiinput.cpp...
Compiling src/emu/validity.cpp...
Compiling src/emu/video.cpp...
Compiling src/emu/video/generic.cpp...
Compiling src/emu/video/resnet.cpp...
Compiling src/emu/video/rgbgen.cpp...
Compiling src/emu/video/rgbsse.cpp...
Compiling src/emu/video/rgbvmx.cpp...
Compiling src/emu/xtal.cpp...
Compiling src/emu/rendfont.cpp...
Compiling src/emu/rendlay.cpp...
Archiving libemu.a...
makefile:1062: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

Does anyone have any suggestions?

**Comment by Robbbert** [comment]
You haven't included the error.

**Comment by NJDave71** [comment]
That's were it stops and returns back to the mingw64 command line prompt

**Comment by MooglyGuy** [comment]
That's great, but you still haven't included the actual error itself. You're doing a multi-core build, the compile error could be multiple hundreds of lines further up from what you've actually posted.

**Comment by NJDave71** [comment]
Unless their is a log that is generated this is all i can provide.   I have never encounter this error

**Comment by MooglyGuy** [comment]
Yes, there is literally a log of the compilation sitting right now in your command-line window. You only need to scroll up to see what the actual error is. If you are incapable of doing this, then perhaps it is ill-advised for you to be compiling your own versions of MAME, and you should stick with the versions that are shipped monthly.

**Comment by NJDave71** [comment]
Thanks I will attempt again and let you know.

**Comment by NJDave71** [comment]
After another attempt I went through the output and the only error messages i am seeing are
makefile:1062: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

This didn't happen with .0211.  
I am going to try to use the zip source instead of the windows only version

**Comment by NJDave71** [comment]
[MINGW64] G:\msys64\src\mame0212>make -j5 PTR64=1 OPTIMIZE=3 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1

GCC 7.2.0 detected
Compiling generated/version.cpp...
Emitting mamevers.rc...
Compiling resources scripts/resources/windows/mame/mame.rc...
Linking mame64.exe...

I have a working mame64.exe build but its 1.7GB.    it never finished the linking step and it has been 24 hours.

**Comment by MooglyGuy** [comment]
If you have a working mame64.exe build, then obviously it did finish the linking step. Otherwise, how do you know that the EXE is working?

If you're compiling your own version of MAME, you're expected to have the ability to do at least some basic diagnostics on your own build setup. Why exactly are you compiling your own version anyway, rather than just going with the stock binaries, if you clearly have so much trouble compiling MAME when so many other people have no issues?

**Comment by NJDave71** [comment]
This is the first time I have ran into this issues and I usually build an arcade only version.  I have received positive help in the past.

**Comment by NJDave71** [comment]
Compiling resources scripts/resources/windows/mame/mame.rc...
Linking mame64.exe...
Running post-build commands [had to press enter]
Dumping symbols.
Stripping symbols.

All good thank you.

**Comment by p1pkin** [comment]
> it never finished the linking step and it has been 24 hours.

try to disable your anti-virus software, some them is known cause of significantly increase linking time.
