### ISSUE TITLE
Win64 compile fails on MSYS2 GCC 9.2.0

### ISSUE THREAD

**Issue by Flupper** [mamedev/mame#5484]
Ever since I updated GCC 9.1.0 to 9.2.0 on my MSYS2/Mingw64 install, MAME keeps failing to compile.
$ gcc -v
Using built-in specs.
COLLECT_GCC=F:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=F:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-9.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --enable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 9.2.0 (Rev1, Built by MSYS2 project)

It always stops here:
$ make -j5 OPTIMIZE=3 ARCHOPTS="-march=core2 -msse4.2" TOOLS=1
[snip]
Generating ../build/projects/windows/mame/gmake-mingw64-gcc/imgtool.make...
Done. Generated 376/376 projects.
Creating ../../../../mingw-gcc/bin/x64/Release
Precompiling src/emu/emu.h...
Compiling src/emu/drivers/empty.cpp...
cc1plus.exe: error: one or more PCH files were found, but they were invalid
cc1plus.exe: error: use -Winvalid-pch for more information
cc1plus.exe: fatal error: ../../../../mingw-gcc/obj/x64/Release/emu.h: No such file or directory
compilation terminated.
precompile.make:307: recipe for target '../../../../mingw-gcc/obj/x64/Release/src/emu/drivers/empty.o' failed
make[2]: *** [../../../../mingw-gcc/obj/x64/Release/src/emu/drivers/empty.o] Error 1
makefile:91: recipe for target 'precompile' failed
make[1]: *** [precompile] Error 2
makefile:1062: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

**Comment by yz70s** [comment]
It is a known problem, try this:
```
To roll back to gcc 9.1.0-3, execute at the msys prompt:

pacman -U
/var/cache/pacman/pkg/mingw-w64-i686-gcc-9.1.0-3-any.pkg.tar.xz
/var/cache/pacman/pkg/mingw-w64-i686-gcc-libgfortran-9.1.0-3-any.pkg.tar.xz
/var/cache/pacman/pkg/mingw-w64-i686-gcc-libs-9.1.0-3-any.pkg.tar.xz
/var/cache/pacman/pkg/mingw-w64-x86_64-gcc-9.1.0-3-any.pkg.tar.xz
/var/cache/pacman/pkg/mingw-w64-x86_64-gcc-libgfortran-9.1.0-3-any.pkg.tar.xz
/var/cache/pacman/pkg/mingw-w64-x86_64-gcc-libs-9.1.0-3-any.pkg.tar.xz

and that should roll everything back.

```

**Comment by rb6502** [comment]
You must "make clean" first to delete the old PCH files.  Then 9.2 will work.

**Comment by Flupper** [comment]
I already tried that and even did a fresh git clone, neither worked for me.
Rolling back to 9.1.0 seems to do the trick, so thanks for the suggestion **yz70s**.

That being said, GCC 9.2.0 also threw some cc1plus.exe warnings when I compiled SDL2/GTK3VICE from SVN, it did compile though.

**Comment by Lord-Nightmare** [comment]
9.2.0-1 on windows even if you do make clean and manually delete the entire build folder, will die due to creating garbage pch files.

**Comment by Flupper** [comment]
Yeah, all is good now I'm back in MSYS2 GCC 9.1.0.
I'll close this as it isn't an issue with MAME.
Thanks to all for replies and have a great day.
