### ISSUE TITLE
All games to 60Hz

### ISSUE THREAD

**Issue by jmmontalba** [mamedev/mame#5515]
Hi, I wanted to ask you if there is a way to compile MAME so that all games or drivers work at 60Hz (such as midtunit, neogeo, cps1, stvbios, etc.), since in the monitors with this frequency, the image is stuttered .
I thank you in advance.

**Comment by rb6502** [comment]
No.  The correct solution to this issue is to buy a GSync or FreeSync variable-refresh-rate monitor.   I've been told both work well with MAME and can adapt to any non-60 Hz refresh rate.

**Comment by jmmontalba** [comment]
Ok, Other answer?
