### ISSUE TITLE
apple2 lores pageflipping has glitchy results

### ISSUE THREAD

**Issue by deater** [mamedev/mame#5595]
On Apple II, when page-flipping between PAGE1 and PAGE2 in LORES graphics mode, the screen glitches in an odd way, almost as if the screen is shifted down by a few lines before settling.  This behavior is not seen on real hardware, or on AppleWin.

I don't have an easy reproduce case, but it reliably happens if you run my "another world" demo and pick any of levels.  You can find the disk image here:
http://www.deater.net/weave/vmwprod/ootw/ootw.dsk

**Comment by rb6502** [comment]
I'm sorry about the long time to get this fixed, it took forever to wrap my brain around what was going on and of course now it seems obvious.  It's been corrected in 9f5a9d11d46055ce7145a50129ee2c0cb713c2d1 as have the corresponding problems with text and double-lo-res.

**Comment by rb6502** [comment]
PS: f53eb6022eac11db43c36462e3dc84714800cde9 fixes the vertical split position in your vapor lock demos.  There's still an issue with hi-res when switching pages or modes mid-screen that causes some of the first line to be glitchy and horizontal raster splits pretty much don't work at all, but things are definitely improved.
