### ISSUE TITLE
please sync genie with latest upstream

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#5597]
With vs2019 due to be able to build mame again, I was fiddling around with fixing appveyor CI. The problem I found is that appveyor's vs2019 image does not contain windows 8.1 sdk [1], and mame's genie copy does not contain vs2019 target yet. Upstream genie does contain vs2019 support, so it seems like syncing genie with upstream would be the easiest solution to get mame in shape for vs2019 16.3 release.

[1] https://www.appveyor.com/docs/windows-images-software/#windows-sdks

**Comment by vadosnaprimer** [comment]
You can close this now.
