### ISSUE TITLE
apple3 issue booting from disk

### ISSUE THREAD

**Issue by frankmilliron** [mamedev/mame#5618]
This Prodos 8 2.5 alpha 4 disk boots normally on a real Apple III. When booting up from MAME however, it crashes just after the bootloader takes control. Attached are disk image to replicate, as well as a screenshot of the hang.
[Apple3boot.zip](https://github.com/mamedev/mame/files/3597539/Apple3boot.zip)

**Comment by rb6502** [comment]
Have you personally tried it on hardware?  I just talked with John Brooks and it sounded like it won't actually do anything on hardware either yet.

**Comment by JohnMBrooks** [comment]
On Apple ///, alpha versions of ProDOS 2.5 do the following:

1) copies the block 0 boot loader code from $A000 to $0800 & jumps to $0801 like Apple II
2) loads block 1 boot loader code to $0a00
3) prints "PRODOS". Also prints a loading-bar with one period for every block loaded
4) finds PRODOS in root dir by reading block 2 and following 'next block' links as needed
5) loads the index block for PRODOS
6) loads the data blocks for PRODOS using the index block entries

MAME prints PRODOS and a single period for block 2, then hangs. So it appears to succeed at steps 1-4, but hangs around step 5.

One possibility is that the new boot loader code steps the head via 1/4 tracks and reads the 16-sector disk using a custom RWTS. The PRODOS index block and data blocks in steps #5 & #6 require seeking the head to another track which may expose a MAME incompatibility.

The RWTS, and almost all of the boot loader code is shared between AppleII and Apple///. If the ProDOS 2.5a disks do not work on MAME in AppleII emulation then the incompatibility may be DiskII related and not specific to Apple/// emulation.

**Comment by frankmilliron** [comment]
Here's a shot of it booted on real hardware...
[IMG_0084.JPG.zip](https://github.com/mamedev/mame/files/3601600/IMG_0084.JPG.zip)

**Comment by frankmilliron** [comment]
OK. Now it works. I converted the DSK to a WOZ file using the Applesauce software and it does expected behavior. Ironically I was just having problems with Applesauce and the A3 because of .po/.do differences. The author just added code there to detect the track/sector order. I was writing disks that wouldn't boot, but worked fine in MAME. The images ended up having the wrong extension and applesauce wasn't adjusting for that before writing back to a real disk.
