### ISSUE TITLE
Project relicensing effort

### ISSUE THREAD

**Issue by mmicko** [mamedev/mame#562]
We (meaning the MAME team) want to place MAME under a standard free and open source software licensing scheme. The current license which prohibits commercial use is custom-written and nonstandard, making attempts at enforcement difficult; it prevents desired commercial use by the owners of game IP since they cannot even negotiate a license from us (they would have to reach out to and obtain agreement from all code contributors who contributed nontrivial changes, and rewrite the code that anyone who refuses the license). It also discourages code reusability between MAME and other emulators, the vast majority of which are under a Free and Open Source Software license, typically, a permissive BSD license, the GNU GPL or a GPL-compatible license in between those.

The definitions of Free Software (http://www.gnu.org/philosophy/free-sw.en.html) and Open Source Software (https://opensource.org/osd-annotated) do not allow restrictions on persons or groups, or field of endeavour — and unfortunately, that is what a non-commercial clause does.

The relicensing plan has been to place the core of MAME under the 3-clause BSD license, which is very permissive, to allow for reuse where a generic emulation framework is needed. The drivers and driver-specific supporting files have been placed under a license chosen by the authors, one of the 3-clause BSD license, the GNU LGPL, or the GNU GPL. The entire MAME binary, as a whole, will be shipped under the GNU GPL — this requires anyone redistributing it to release source code for MAME, and not  change the license so that others would be allowed to also redistribute their changes.

The MAME trademark is separate — and should prevent misuse of the trade name "MAME" in situations which the team has not approved.
We are not planning to derive revenue of any sort by doing this, and MAME will remain open source — the GPL portions should guarantee this.

Using this issue to contact : @StefanJokisch @notaz

**Comment by mmicko** [comment]
@StefanJokisch @notaz Sorry to contact you like this, but idea is to get response from you about setting license to drivers you are copyright owner or share ownership with someone at MAME project.
Most of files are now BSD3, but we respect wish of all developers, and we allow GPL-2.0+ and LGPL-2.1+

**Comment by StefanJokisch** [comment]
Miodrag, I'm fine with changing the license for my MAME contributions to 
BSD3.

Best wishes

**Comment by mmicko** [comment]
Thanks a lot

**Comment by meesokim** [comment]
I strongly support MAME team's decision.

**Comment by vgturtle127** [comment]
:+1: 

This is a great idea, and I think this will make it more comfortable for people to contribute to MAME, and to write frontends and GUI's for MAME.

Exciting times to be a part of the emulation community. :smile:

**Comment by cracyc** [comment]
Don't see any reason to leave this open now that it's complete.
