### ISSUE TITLE
-lx crashing on sd1 output at 0.214 (mame0214-47-g6f0e4362e6)

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#5685]
0.214 (mame0214-47-g6f0e4362e6)

mame -lx

        <machine name="sd1" sourcefile="esq5505.cpp">
                <description>SD-1 (21 voice)</description>
                <year>1990</year>
                <manufacturer>Ensoniq</manufacturer>
                <rom name="sd1_21_300b_lower.bin" size="131072" crc="a1358a0c" sha1="64ac5358aa46da37ca4195002cf35
8554e00878a" region="osrom" offset="0"/>
                <rom name="sd1_21_300b_upper.bin" size="65536" crc="465ba463" sha1="899b0e83d0788c8d49c7b09ccf0b4a
92b528c6e9" region="osrom" offset="1"/>
                <rom name="u34.bin" size="524288" crc="85592299" sha1="1aa7cf612f91972baeba15991d9686ccde01599c" r
egion="waverom" offset="1"/>
                <rom name="u35.bin" size="524288" crc="c0055975" sha1="5a22f1d5e437c6277eb0cfb1ff1b3f8dcdea1cc6" r
egion="waverom" offset="100001"/>
                <rom name="u38.bin" size="1048576" crc="a904190e" sha1="e4fd4e1130906086fb4182dcb8b51269969e2836"
region="waverom2" offset="0"/>
                <rom name="u37.bin" size="1048576" crc="d706cef3" sha1="24ba35248509e9ca45110e2402b8085006ea0cfc"
region="waverom2" offset="100000"/>
                <rom name="u36.bin" size="524288" crc="c3ddaf95" sha1="44a7bd89cd7e82952cc5100479e110c385246559" r
egion="nibbles" offset="0"/>
                <device_ref name="m68000"/>
                <device_ref name="es5510"/>
                <device_ref name="esqpanel240_vfx"/>
                <device_ref name="esq2x40"/>
                <device_ref name="mc68681"/>
                <device_ref name="duart_channel"/>
                <device_ref name="duart_channel"/>
                <device_ref name="midi_port"/>
                <device_ref name="midiin_port"/>
                <device_ref name="midiin"/>
                <device_ref name="midi_port"/>
                <device_ref name="midiout_port"/>
                <device_ref name="midiout"/>
                <device_ref name="speaker"/>
                <device_ref name="speaker"/>
                <device_ref name="esq_5505_5510_pump"/>
                <device_ref name="es5505"/>
                <device_ref name="wd1772"/>
                <device_ref name="floppy_connector"/>
                <device_ref name="floppy_35_dd"/>
                <device_ref name="speaker"/>
                <device_ref name="flopsnd"/>
                <chip type="cpu" tag="maincpu" name="Motorola MC68000" clock="10000000"/>
                <chip type="cpu" tag="esp" name="ES5510" clock="10000000"/>
                <chip type="audio" tag="lspeaker" name="Speaker"/>
                <chip type="audio" tag="rspeaker" name="Speaker"/>
                <chip type="audio" tag="pump" name="Ensoniq 5505/5506 to 5510 interface" clock="29761"/>
                <chip type="audio" tag="otis" name="Ensoniq ES5505" clock="10000000"/>
                <chip type="audio" tag="wd1772:0:35dd:flopsndout" name="Speaker"/>
                <chip type="audio" tag="wd1772:0:35dd:floppysound" name="Floppy sound" clock="44100"/>
                <sound channels="3"/>
                <input players="1">
                        <control type="keyboard" buttons="35"/>
                </input>
                <port tag=":KEY0">
                </port>
                <port tag=":KEY1">
                </port>
                <port tag=":KEY2">
                </port>
                <driver status="preliminary" emulation="preliminary" savestate="unsupported"/>
                <feature type="sound" overall="imperfect"/>
                <device type="midiin" tag="mdin:midiin:midiinimg">
                        <instance name="midiin" briefname="min"/>
                        <extension name="mid"/>
                </device>
                <device type="midiout" tag="mdout:midiout:midioutimg">
                        <instance name="midiout" briefname="mout"/>
                        <extension name="mid"/>
                </device>
                <device type="floppydisk" tag="wd1772:0:35dd" interface="floppy_3_5">
                        <instance name="floppydisk" briefname="flop"/>
                        <extension name="img"/>
                        <extension name="d77"/>
                        <extension name="d88"/>
                        <extension name="1dd"/>
                        <extension name="dfi"/>
                        <extension name="hfe"/>
                        <extension name="imd"/>
                        <extension name="ipf"/>
                        <extension name="mfi"/>
                        <extension name="mfm"/>
                        <extension name="td0"/>
                        <extension name="cqm"/>
                        <extension name="cqi"/>
                        <extension name="dsk"/>
                </device>
                <slot name="mdin">
                        <slotoption name="midiin" devname="midiin_port" default="yes"/>
                </slot>
                <slot name="mdout">
                        <slotoption name="midiout" devname="midiout_port" default="yes"/>
                </slot>
                <slot name="wd1772:0">
                        <slotoption name="35dd" devname="floppy_35_dd" default="yes"/>
                </slot>
        </machine>
Unknown crystal value 30476100.  Did you mean 30209800 or 30476180? Context: Instantiating device maincpu

**Comment by Tafoid** [comment]
I just pulled source and made a clean 32bit build and I encounter none of these issues.
MAME v0.214 (mame0214-49-g081f592c54)

Verify all your files are correctly updated from Git and make sure you are making a clean build.
Unless it is a 64-bit only issue, I'm not seeing anything making my Windows binary.

**Comment by john-iv** [comment]
It was a clean x64 build, my chron job to build happens at 6pm and 6am PST.  I'll see how it goes in 5 hours w/ a new pull.

**Comment by cuavas** [comment]
Please give people a chance to fix obvious validation issues before opening issues. You know we don't do QA on every git revision and make no representations about whether anything other than tagged releases will even compile across all supported targets.
