### ISSUE TITLE
toolchain.lua lacks entries for alternative vs2019 builds

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#5695]
https://github.com/mamedev/mame/blob/fcbc60c1836ae7cc895a9f302606b67a900e000a/makefile#L1205

I have just realised that my PR adding VS2019 support missed toolchain.lua entries for alternative VS2019 builds (Intel compiler, UWP, etc.) which were added when support for vs2017 was introduced:
https://github.com/mamedev/mame/commit/8e61a7d3d37d0ceaf2f6af0a460d2f9c692e5252#diff-cd5dbf3629c558b0104ba8f0937d6816
Having said that, I am not sure if the vs2017 entries are correct either:
- the UWP targets in makefile reference vs2015 for vs2017 and vs2019 (copy-paste error of 2nd degree:
https://github.com/mamedev/mame/blob/fcbc60c1836ae7cc895a9f302606b67a900e000a/makefile#L1182
https://github.com/mamedev/mame/blob/fcbc60c1836ae7cc895a9f302606b67a900e000a/makefile#L1214
- code for intel compiler version 14 is present but this is never called from the makefile
- code for windows phone and windows store 8.1 is never called from the makefile either
- the newest intel compiler referenced is version 15 while the latest release is version 19

I have limited capabilities of testing the alternative targets, but I could aim to resolve most blatant errors. Before I begin, however, it would be good to align which targets are actually worth keeping.

**Comment by cuavas** [comment]
Windows Phone is dead - it's not worth keeping.  The guy adding UWP support effectively disappeared, so it's been unmaintained for a while.  There doesn't seem to be much interest in using the Intel compiler any more, either.
