### ISSUE TITLE
Musashi/M68k: bfins data for 5th byte is wrong

### ISSUE THREAD

**Issue by harbaum** [mamedev/mame#573]
This bug is related to the previous 
https://github.com/mamedev/mame/issues/327
which fixed shifting for the mask of the fifth byte.

The data has a similar problem. Example:
test:	dc.l	$ffffffff, $ffffffff
	move.l		#$12345678,d0
	bfins		d0,test{4:32}

In musashi the result is f1234567 7fffffff but it should be f1234567 8fffffff. Furthermore the zreo flag is not properly set as it needs to be derived from the value to be inserted and not from the previous contents. The code dealing with the previous 4 bytes does this correctly.

The reason is that for bfins the data to be inserted has to be shifted like the mask:

		if((width + offset) > 32)
		{
			mask_byte = MASK_OUT_ABOVE_8(mask_base) << (8-offset);
			// insert_byte = MASK_OUT_ABOVE_8(insert_base);  // broken!!!
			insert_byte = MASK_OUT_ABOVE_8(insert_base) << (8-offset);  // fixed
			data_byte = m68ki_read_8(ea+4);
  			// FLAG_Z |= (data_byte & mask_byte);   // broken!!
  			FLAG_Z |= (insert_byte & mask_byte);   // fixed
			m68ki_write_8(ea+4, (data_byte & ~mask_byte) | insert_byte);
		}

**Comment by rb6502** [comment]
Thanks!  I'll take a look.

**Comment by rb6502** [comment]
Thanks!  The fix is applied to MAME trunk, and it fixes a long-standing bug where the MacOS Jigsaw Puzzle applet would freak out and create impossible puzzles.

**Comment by galibert** [comment]
Way cool :-)

  OG.

**Comment by DopefishJustin** [comment]
http://mametesters.org/view.php?id=5411

**Comment by harbaum** [comment]
Cool! Thanks for the feedback.
