### ISSUE TITLE
interpro (Clipper) Driver: Keyboard stuck keys significant problems

### ISSUE THREAD

**Issue by cube1us** [mamedev/mame#5749]
MAME version 0214b

The Intergraph Interpro (Clipper) driver page at https://wiki.mamedev.org/index.php/Driver:InterPro says: 

"One last known bug relates to the keyboard emulation; occasionally some keys can get "stuck", and endlessly repeat, and in other cases require several repeated presses before a character is generated."

On my Windows 10 X64 i7-8700K 3.70Ghz system, this issue is making the Clipper emulation essentially unusable.  It is far from "occasionally".  It is more like 20% of the keystrokes.  It looks to me as though it sees the keypress event, but not the release - and then it sees a release on the next keystroke.

(As an aside, I went looking for a way to essentially turn off typematic, but in looking through the XML config files and the like, I was unable to find a way.)

(Update:  This problem seems unaffected by win32 vs. win64 executables.  This problem does not seem to be affected much by the speed of the host machine.  This problem is noticeably worse if one is running with the speed set to >100%. )

**Comment by pmackinlay** [comment]
While this driver is still marked as "not working", I'm happy to accept your bug reports on mametesters regardless; I appreciate the feedback. Can you please reopen this issue there instead (I haven't found a solution to the problem yet, but turning off the keyboard auto-repeat setting in the shell window settings helps)?
