### ISSUE TITLE
No functioning bgfx backend available on Linux

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#5768]
I am filing this here so that the issue does not fall off the radar and to provide one stop shop for anyone encountering this.
Since https://github.com/mamedev/mame/commit/61b2a8afaf012e28ef14ad946ee0bb8319232aa6 there is no working bgfx backend available on Linux. OpenGL and OpenGL ES fail with

```
 ../../../../../3rdparty/bgfx/src/renderer_gl.cpp (5908): BGFX 0x00000001: Failed to compile shader.
```

while Vulkan displays no video at all. @couriersud has found some workarounds (see https://github.com/mamedev/mame/commit/697dfa9fac769726c136c9c487bb3d47b7d07f56) but I don't know if either of these are proper fixes.

**Comment by cuavas** [comment]
We've got less than a week until freeze, so this is pretty high priority right now.

**Comment by algestam** [comment]
The changes done in https://github.com/mamedev/mame/commit/c24d44ec62e6a293fbe9c69da2e35563304ddb5e resolves this issue. Both OpenGL and OpenGL ES has been confirmed to work on Linux after that change.

**Comment by couriersud** [comment]
I confirm that opengl backend is working now. The vulkan backend still needs the modification/hack in https://github.com/mamedev/mame/commit/c24d44ec62e6a293fbe9c69da2e35563304ddb5e

**Comment by belegdol** [comment]
@couriersud, have you tested ec4bee1371353b2767a1260637ab5317646970ca or later? Vulkan backend is working for me on both linux and windows with since that commit.

**Comment by rb6502** [comment]
Vulkan works for me on Linux as well with latest.

**Comment by couriersud** [comment]
No, still need to comment out lines 3938 and 3939 in renderer_vk.cpp after update to https://github.com/mamedev/mame/commit/cb231a5e921b668fbef5a753cbe92e91fb64b1c3

mame will display the ui. But as soon as you start a game, it will crash without these modifications.
Games that will crash: kidniki, pongf, pong, mario, ldrun2.

Ubuntu 16.04
Nvidia 418.87.01
libvulkan 1.1.73+dfsg-1~gpu16.04.1

**Comment by belegdol** [comment]
On Fedora 31 the versions are a bit newer: driver is 435.21 while vulkan is 1.1.114. Maybe it is an issue with older versions?

**Comment by algestam** [comment]
Did some testing on Ubuntu 18.04 and the Vulkan issue seems to be related to the driver version.

Using the Nvidia 390 driver, the UI shows up but MAME crashes as soon as a game is started. Commenting out the lines suggested by @couriersud in `renderer_vk.cpp` allows games to be started.

Changing the Nvidia driver version to 430.26 allows MAME to start games without any modification to the source files.

Games tested: outrun, ridgerac
Command-line: `./mame64 -window -video bgfx -bgfx_backend vulkan -bgfx_screen_chains hlsl -bgfx_debug [game]`

**Comment by couriersud** [comment]
I confirm this is a driver issue. I installed nvidia-430 and now the vulkan backend works.

On Ubuntu 16.04 the nvidia-430 package has a bug which will prevent proper booting. 
To fix that, the following script has to be run:

```
#!/bin/sh

# https://devtalk.nvidia.com/default/topic/1061656/linux/gtx1650-notebook-not-working-on-ubuntu16-04-black-screen-amp-login-loop-/post/5376983/#5376983

cd /usr/lib/nvidia-430
sudo rm libGL.so.1
sudo ln -s libGL.so.1.7.0 libGL.so.1

echo please reboot now

```
