### ISSUE TITLE
Consolidate MOS 6530 implementations

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#5798]
There are currently two MOS 6530/6532 MIOT/RIOT implementations.  There seems to have been no effort to consolidate the implementations in years.  At the very least, the issues preventing consolidation need to be identified.  When issues are identified, we can decide which implementation is superior and migrate devices/machines to the chosen implementation.

**Comment by cuavas** [comment]
Devices/machines using the "new" 6530 implementation (from [here](https://arcade.vastheman.com/minimaws/machine/mos6530_new)):

| Short name    | Descrtiption                         | Source file                       |
| ------------- | ------------------------------------ | --------------------------------- |
| b128          | B128                                 | cbm2.cpp                          |
| b128hp        | B128-80HP                            | cbm2.cpp                          |
| b256          | B256                                 | cbm2.cpp                          |
| b256hp        | B256-80HP                            | cbm2.cpp                          |
| b500          | B500                                 | cbm2.cpp                          |
| bx256hp       | BX256-80HP                           | cbm2.cpp                          |
| cbm3008       | CBM 3008                             | pet.cpp                           |
| cbm3016       | CBM 3016                             | pet.cpp                           |
| cbm3032       | CBM 3032                             | pet.cpp                           |
| cbm3032b      | CBM 3032B                            | pet.cpp                           |
| cbm4016       | CBM 4016                             | pet.cpp                           |
| cbm4032       | CBM 4032                             | pet.cpp                           |
| cbm4032b      | CBM 4032B                            | pet.cpp                           |
| cbm4032f      | CBM 4032 (Fat 40)                    | pet.cpp                           |
| cbm610        | CBM 610                              | cbm2.cpp                          |
| cbm620        | CBM 620                              | cbm2.cpp                          |
| cbm620_hu     | CBM 620 (Hungary)                    | cbm2.cpp                          |
| cbm710        | CBM 710                              | cbm2.cpp                          |
| cbm720        | CBM 720                              | cbm2.cpp                          |
| cbm720_de     | CBM 720 (Germany)                    | cbm2.cpp                          |
| cbm720_se     | CBM 720 (Sweden/Finland)             | cbm2.cpp                          |
| cbm730        | CBM 730                              | cbm2.cpp                          |
| cbm8032       | CBM 8032                             | pet.cpp                           |
| cbm8032_de    | CBM 8032 (Germany)                   | pet.cpp                           |
| cbm8032_fr    | CBM 8032 (France)                    | pet.cpp                           |
| cbm8032_se    | CBM 8032 (Sweden/Finland)            | pet.cpp                           |
| cbm8096       | CBM 8096                             | pet.cpp                           |
| cbm8296       | CBM 8296                             | pet.cpp                           |
| cbm8296d      | CBM 8296-D                           | pet.cpp                           |
| cbm8296d_de   | CBM 8296-D (Germany)                 | pet.cpp                           |
| cbm8296dgv_de | CBM 8296-D GV? (Germany)             | pet.cpp                           |
| cbm8296ed     | CBM 8296 ExecuDesk                   | pet.cpp                           |
| cbm8296gd     | CBM 8296GD                           | pet.cpp                           |
| mmf9000       | MicroMainFrame 9000                  | pet.cpp                           |
| mmf9000_se    | MicroMainFrame 9000 (Sweden/Finland) | pet.cpp                           |
| p500          | P500 (NTSC)                          | cbm2.cpp                          |
| p500p         | P500 (PAL)                           | cbm2.cpp                          |
| pet2001       | PET 2001-4                           | pet.cpp                           |
| pet20018      | PET 2001-8                           | pet.cpp                           |
| pet2001b      | PET 2001-B8                          | pet.cpp                           |
| pet2001b16    | PET 2001-B16                         | pet.cpp                           |
| pet2001b32    | PET 2001-B32                         | pet.cpp                           |
| pet2001n      | PET 2001-N8                          | pet.cpp                           |
| pet2001n16    | PET 2001-N16                         | pet.cpp                           |
| pet2001n32    | PET 2001-N32                         | pet.cpp                           |
| pet4016       | PET 4016                             | pet.cpp                           |
| pet4032       | PET 4032                             | pet.cpp                           |
| pet4032b      | PET 4032B                            | pet.cpp                           |
| pet4032f      | PET 4032 (Fat 40)                    | pet.cpp                           |
| pet8032       | PET 8032                             | pet.cpp                           |
| softbox       | SoftBox                              | softbox.cpp                       |
| superpet      | SuperPET SP-9000                     | pet.cpp                           |
| c2040         | Commodore 2040                       | src/devices/bus/ieee488/c2040.cpp |
| c3040         | Commodore 3040                       | src/devices/bus/ieee488/c2040.cpp |
| c4040         | Commodore 4040                       | src/devices/bus/ieee488/c2040.cpp |
| c8050         | Commodore 8050                       | src/devices/bus/ieee488/c8050.cpp |
| c8250         | Commodore 8250                       | src/devices/bus/ieee488/c8050.cpp |
| c8250lp       | Commodore 8250LP                     | src/devices/bus/ieee488/c8050.cpp |
| sfd10001      | Commodore SFD-1001                   | src/devices/bus/ieee488/c8050.cpp |

**Comment by cuavas** [comment]
Devices/machines using the “new” 6532 implementation (from [here](https://arcade.vastheman.com/minimaws/machine/mos6532_new)):

| Short name    | Description                          | Source file                         |
| ------------- | ------------------------------------ | ----------------------------------- |
| a7800         | Atari 7800 (NTSC)                    | a7800.cpp                           |
| a7800p        | Atari 7800 (PAL)                     | a7800.cpp                           |
| aim65         | AIM 65                               | aim65.cpp                           |
| b128          | B128                                 | cbm2.cpp                            |
| b128hp        | B128-80HP                            | cbm2.cpp                            |
| b256          | B256                                 | cbm2.cpp                            |
| b256hp        | B256-80HP                            | cbm2.cpp                            |
| b500          | B500                                 | cbm2.cpp                            |
| beta          | Beta                                 | beta.cpp                            |
| bx256hp       | BX256-80HP                           | cbm2.cpp                            |
| cbm3008       | CBM 3008                             | pet.cpp                             |
| cbm3016       | CBM 3016                             | pet.cpp                             |
| cbm3032       | CBM 3032                             | pet.cpp                             |
| cbm3032b      | CBM 3032B                            | pet.cpp                             |
| cbm4016       | CBM 4016                             | pet.cpp                             |
| cbm4032       | CBM 4032                             | pet.cpp                             |
| cbm4032b      | CBM 4032B                            | pet.cpp                             |
| cbm4032f      | CBM 4032 (Fat 40)                    | pet.cpp                             |
| cbm610        | CBM 610                              | cbm2.cpp                            |
| cbm620        | CBM 620                              | cbm2.cpp                            |
| cbm620_hu     | CBM 620 (Hungary)                    | cbm2.cpp                            |
| cbm710        | CBM 710                              | cbm2.cpp                            |
| cbm720        | CBM 720                              | cbm2.cpp                            |
| cbm720_de     | CBM 720 (Germany)                    | cbm2.cpp                            |
| cbm720_se     | CBM 720 (Sweden/Finland)             | cbm2.cpp                            |
| cbm730        | CBM 730                              | cbm2.cpp                            |
| cbm8032       | CBM 8032                             | pet.cpp                             |
| cbm8032_de    | CBM 8032 (Germany)                   | pet.cpp                             |
| cbm8032_fr    | CBM 8032 (France)                    | pet.cpp                             |
| cbm8032_se    | CBM 8032 (Sweden/Finland)            | pet.cpp                             |
| cbm8096       | CBM 8096                             | pet.cpp                             |
| cbm8296       | CBM 8296                             | pet.cpp                             |
| cbm8296d      | CBM 8296-D                           | pet.cpp                             |
| cbm8296d_de   | CBM 8296-D (Germany)                 | pet.cpp                             |
| cbm8296dgv_de | CBM 8296-D GV? (Germany)             | pet.cpp                             |
| cbm8296ed     | CBM 8296 ExecuDesk                   | pet.cpp                             |
| cbm8296gd     | CBM 8296GD                           | pet.cpp                             |
| junior        | Junior Computer                      | junior.cpp                          |
| mmf9000       | MicroMainFrame 9000                  | pet.cpp                             |
| mmf9000_se    | MicroMainFrame 9000 (Sweden/Finland) | pet.cpp                             |
| p500          | P500 (NTSC)                          | cbm2.cpp                            |
| p500p         | P500 (PAL)                           | cbm2.cpp                            |
| pet2001       | PET 2001-4                           | pet.cpp                             |
| pet20018      | PET 2001-8                           | pet.cpp                             |
| pet2001b      | PET 2001-B8                          | pet.cpp                             |
| pet2001b16    | PET 2001-B16                         | pet.cpp                             |
| pet2001b32    | PET 2001-B32                         | pet.cpp                             |
| pet2001n      | PET 2001-N8                          | pet.cpp                             |
| pet2001n16    | PET 2001-N16                         | pet.cpp                             |
| pet2001n32    | PET 2001-N32                         | pet.cpp                             |
| pet4016       | PET 4016                             | pet.cpp                             |
| pet4032       | PET 4032                             | pet.cpp                             |
| pet4032b      | PET 4032B                            | pet.cpp                             |
| pet4032f      | PET 4032 (Fat 40)                    | pet.cpp                             |
| pet8032       | PET 8032                             | pet.cpp                             |
| softbox       | SoftBox                              | softbox.cpp                         |
| superpet      | SuperPET SP-9000                     | pet.cpp                             |
| sym1          | SYM-1/SY-VIM-1                       | sym1.cpp                            |
| d9060         | Commodore D9060                      | src/devices/bus/ieee488/d9060.cpp   |
| d9090         | Commodore D9090                      | src/devices/bus/ieee488/d9060.cpp   |
| c8280         | Commodore 8280                       | src/devices/bus/ieee488/c8280.cpp   |
| c2040         | Commodore 2040                       | src/devices/bus/ieee488/c2040.cpp   |
| c3040         | Commodore 3040                       | src/devices/bus/ieee488/c2040.cpp   |
| c4040         | Commodore 4040                       | src/devices/bus/ieee488/c2040.cpp   |
| c8050         | Commodore 8050                       | src/devices/bus/ieee488/c8050.cpp   |
| c8250lp       | Commodore 8250LP                     | src/devices/bus/ieee488/c8050.cpp   |
| sfd10001      | Commodore SFD-1001                   | src/devices/bus/ieee488/c8050.cpp   |
| interpod      | Interpod                             | src/devices/bus/cbmiec/interpod.cpp |
| atari810      | Atari 810 Disk Drive                 | src/devices/bus/a800/atari810.cpp   |
| atari1050     | Atari 1050 Dual Density Disk Drive   | src/devices/bus/a800/atari1050.cpp  |

**Comment by cuavas** [comment]
Devices/machines using the “old” 6530 implementation (from [here](https://arcade.vastheman.com/minimaws/machine/mos6530)):

| Short name | Description                               | Source file                          |
| ---------- | ----------------------------------------- | ------------------------------------ |
| alienstr   | Alien Star                                | gts80a.cpp                           |
| allied     | Allied System                             | allied.cpp                           |
| blckhols   | Black Hole (Sound Only)                   | gts80.cpp                            |
| bountyh    | Bounty Hunter                             | gts80b.cpp                           |
| bountyhg   | Bounty Hunter (German)                    | gts80b.cpp                           |
| ccmk2      | Chess Champion: MK II (ver. 1)            | chessmate.cpp                        |
| ccmk2a     | Chess Champion: MK II (ver. 2)            | chessmate.cpp                        |
| chmate     | Chessmate                                 | chessmate.cpp                        |
| circa33    | Circa 1933                                | allied.cpp                           |
| circusp    | Circus                                    | gts80.cpp                            |
| cntforce   | Counterforce                              | gts80.cpp                            |
| disco79    | Disco '79                                 | allied.cpp                           |
| dvlsdre2   | Devil's Dare (Sound Only)                 | gts80a.cpp                           |
| eclipse    | Eclipse                                   | gts80.cpp                            |
| eldorado   | El Dorado City of Gold                    | gts80a.cpp                           |
| erosone    | Eros One                                  | allied.cpp                           |
| foathens   | Flame of Athens                           | allied.cpp                           |
| forceii    | Force II                                  | gts80.cpp                            |
| heartspd   | Hearts & Spades                           | allied.cpp                           |
| hoedown    | Hoe Down                                  | allied.cpp                           |
| icefever   | Ice Fever                                 | gts80a.cpp                           |
| jack2opn   | Jacks to Open                             | gts80a.cpp                           |
| jamesb     | James Bond (Timed Play)                   | gts80.cpp                            |
| jamesb2    | James Bond (3/5-Ball)                     | gts80.cpp                            |
| kim1       | KIM-1                                     | kim1.cpp                             |
| panthera   | Panthera                                  | gts80.cpp                            |
| pnkpnthr   | Pink Panther                              | gts80.cpp                            |
| rackempp   | Rack 'em Up! (Pinball)                    | gts80a.cpp                           |
| raimfire   | Ready...Aim...Fire!                       | gts80a.cpp                           |
| royclark   | Roy Clark - The Entertainer               | allied.cpp                           |
| spidermn   | The Amazing Spider-Man                    | gts80.cpp                            |
| starrace   | Star Race                                 | gts80.cpp                            |
| starshot   | Star Shooter                              | allied.cpp                           |
| suprpick   | Super Picker                              | allied.cpp                           |
| tagteamp   | Tag-Team Wrestling                        | gts80b.cpp                           |
| tagteamp2  | Tag-Team Wrestling (rev.2)                | gts80b.cpp                           |
| tagteampg  | Tag-Team Wrestling (German)               | gts80b.cpp                           |
| takefive   | Take Five                                 | allied.cpp                           |
| thegames   | The Games                                 | gts80a.cpp                           |
| thndbolt   | Thunderbolt                               | allied.cpp                           |
| timeline   | Time Line                                 | gts80.cpp                            |
| touchdn    | Touchdown                                 | gts80a.cpp                           |
| triplay    | Chicago Cubs' Triple Play                 | gts80b.cpp                           |
| triplaya   | Chicago Cubs' Triple Play (alternate set) | gts80b.cpp                           |
| vlcno_1a   | Volcano (Sound Only set 3)                | gts80.cpp                            |
| vlcno_1b   | Volcano (Sound Only set 2)                | gts80.cpp                            |
| vlcno_1c   | Volcano (Sound Only set 1)                | gts80.cpp                            |
| gotsndr0   | Gottlieb Sound rev. 0                     | src/mame/audio/gottlieb.cpp          |

**Comment by cuavas** [comment]
Devices/machines using the “old” 6532 implementation (from [here](https://arcade.vastheman.com/minimaws/machine/riot6532)):

| Short name    | Description                                         | Source file                      |
| ------------- | --------------------------------------------------- | -------------------------------- |
| a2600         | Atari 2600 (NTSC)                                   | a2600.cpp                        |
| a2600p        | Atari 2600 (PAL)                                    | a2600.cpp                        |
| alienstr      | Alien Star                                          | gts80a.cpp                       |
| amazonh       | Amazon Hunt                                         | gts80a.cpp                       |
| amazonh2      | Amazon Hunt II (French)                             | gts80b.cpp                       |
| amazonh3      | Amazon Hunt III (French)                            | gts80b.cpp                       |
| amazonh3a     | Amazon Hunt III (rev. 1, French)                    | gts80b.cpp                       |
| amazonha      | Amazon Hunt (alternate set)                         | gts80a.cpp                       |
| arena         | Arena                                               | gts80b.cpp                       |
| arenaa        | Arena (alternate set)                               | gts80b.cpp                       |
| arenaf        | Arena (French)                                      | gts80b.cpp                       |
| arenag        | Arena (German)                                      | gts80b.cpp                       |
| argusg        | Argus (Gottlieb, prototype)                         | gottlieb.cpp                     |
| badgirls      | Bad Girls                                           | gts80b.cpp                       |
| badgirlsf     | Bad Girls (French)                                  | gts80b.cpp                       |
| badgirlsg     | Bad Girls (German)                                  | gts80b.cpp                       |
| bighouse      | Big House                                           | gts80b.cpp                       |
| bighousef     | Big House (French)                                  | gts80b.cpp                       |
| bighouseg     | Big House (German)                                  | gts80b.cpp                       |
| blckhole      | Black Hole (Rev. 4)                                 | gts80.cpp                        |
| blckhole2     | Black Hole (Rev. 2)                                 | gts80.cpp                        |
| blckhols      | Black Hole (Sound Only)                             | gts80.cpp                        |
| bonebstr      | Bone Busters Inc.                                   | gts80b.cpp                       |
| bonebstrf     | Bone Busters Inc. (French)                          | gts80b.cpp                       |
| bonebstrg     | Bone Busters Inc. (German)                          | gts80b.cpp                       |
| bountyh       | Bounty Hunter                                       | gts80b.cpp                       |
| bountyhg      | Bounty Hunter (German)                              | gts80b.cpp                       |
| caveman       | Caveman (Pinball/Video Combo, set 1)                | gts80a.cpp                       |
| cavemana      | Caveman (Pinball/Video Combo, set 2)                | gts80a.cpp                       |
| challeng      | Challenger                                          | gameplan.cpp                     |
| circusp       | Circus                                              | gts80.cpp                        |
| cntforce      | Counterforce                                        | gts80.cpp                        |
| curvebal      | Curve Ball                                          | gottlieb.cpp                     |
| diamondp      | Diamond Lady                                        | gts80b.cpp                       |
| diamondpf     | Diamond Lady (French)                               | gts80b.cpp                       |
| diamondpg     | Diamond Lady (German)                               | gts80b.cpp                       |
| dvlsdre       | Devil's Dare                                        | gts80a.cpp                       |
| dvlsdre2      | Devil's Dare (Sound Only)                           | gts80a.cpp                       |
| eclipse       | Eclipse                                             | gts80.cpp                        |
| eldorado      | El Dorado City of Gold                              | gts80a.cpp                       |
| esb           | The Empire Strikes Back                             | starwars.cpp                     |
| excalibr      | Excalibur                                           | gts80b.cpp                       |
| excalibrf     | Excalibur (French)                                  | gts80b.cpp                       |
| excalibrg     | Excalibur (German)                                  | gts80b.cpp                       |
| fax           | FAX                                                 | exidy.cpp                        |
| fax2          | FAX 2                                               | exidy.cpp                        |
| firefox       | Fire Fox (set 1)                                    | firefox.cpp                      |
| firefoxa      | Fire Fox (set 2)                                    | firefox.cpp                      |
| forceii       | Force II                                            | gts80.cpp                        |
| genesisp      | Genesis                                             | gts80b.cpp                       |
| genesispf     | Genesis (French)                                    | gts80b.cpp                       |
| genesispg     | Genesis (German)                                    | gts80b.cpp                       |
| goinnuts      | Goin' Nuts                                          | gts80a.cpp                       |
| goldwing      | Gold Wings                                          | gts80b.cpp                       |
| goldwingf     | Gold Wings (French)                                 | gts80b.cpp                       |
| goldwingg     | Gold Wings (German)                                 | gts80b.cpp                       |
| hardhat       | Hard Hat                                            | exidy.cpp                        |
| hh            | Haunted House (Rev. 2)                              | gts80.cpp                        |
| hh_1          | Haunted House (Rev. 1)                              | gts80.cpp                        |
| hlywoodh      | Hollywood Heat                                      | gts80b.cpp                       |
| hlywoodhf     | Hollywood Heat (French)                             | gts80b.cpp                       |
| hlywoodhg     | Hollywood Heat (German)                             | gts80b.cpp                       |
| hotshots      | Hot Shots                                           | gts80b.cpp                       |
| hotshotsf     | Hot Shots (French)                                  | gts80b.cpp                       |
| hotshotsg     | Hot Shots (German)                                  | gts80b.cpp                       |
| icefever      | Ice Fever                                           | gts80a.cpp                       |
| insector      | Insector (prototype)                                | gottlieb.cpp                     |
| jack2opn      | Jacks to Open                                       | gts80a.cpp                       |
| jamesb        | James Bond (Timed Play)                             | gts80.cpp                        |
| jamesb2       | James Bond (3/5-Ball)                               | gts80.cpp                        |
| kaos          | Kaos                                                | gameplan.cpp                     |
| killcom       | Killer Comet                                        | gameplan.cpp                     |
| kngtmare      | Knightmare (prototype)                              | gottlieb.cpp                     |
| krull         | Krull                                               | gottlieb.cpp                     |
| krullp        | Krull (Pinball)                                     | gts80a.cpp                       |
| leprechn      | Leprechaun                                          | gameplan.cpp                     |
| leprechp      | Leprechaun (Pacific)                                | gameplan.cpp                     |
| marsp         | Mars - God of War                                   | gts80.cpp                        |
| marspf        | Mars - God of War (French speech)                   | gts80.cpp                        |
| marspp        | Mars - God of War (Prototype)                       | gts80.cpp                        |
| megatack      | Megatack (set 1)                                    | gameplan.cpp                     |
| megatacka     | Megatack (set 2)                                    | gameplan.cpp                     |
| mmmaster      | Master                                              | gts80b.cpp                       |
| mntecrlo      | Monte Carlo (Pinball)                               | gts80b.cpp                       |
| mntecrlo2     | Monte Carlo (Pinball, rev. 2)                       | gts80b.cpp                       |
| mntecrloa     | Monte Carlo (Pinball, alternate set)                | gts80b.cpp                       |
| mntecrlof     | Monte Carlo (Pinball, French)                       | gts80b.cpp                       |
| mntecrlog     | Monte Carlo (Pinball, German)                       | gts80b.cpp                       |
| mplanets      | Mad Planets                                         | gottlieb.cpp                     |
| mplanetsuk    | Mad Planets (UK)                                    | gottlieb.cpp                     |
| mtrap         | Mouse Trap (version 5)                              | exidy.cpp                        |
| mtrap2        | Mouse Trap (version 2)                              | exidy.cpp                        |
| mtrap3        | Mouse Trap (version 3)                              | exidy.cpp                        |
| mtrap4        | Mouse Trap (version 4)                              | exidy.cpp                        |
| mtrapb        | Mouse Trap (bootleg)                                | exidy.cpp                        |
| mtrapb2       | Mouse Trap (version 4, bootleg)                     | exidy.cpp                        |
| myqbert       | Mello Yello Q*bert                                  | gottlieb.cpp                     |
| nmoves        | Night Moves                                         | gts80b.cpp                       |
| panthera      | Panthera                                            | gts80.cpp                        |
| pepper2       | Pepper II (version 8)                               | exidy.cpp                        |
| pepper27      | Pepper II (version 7)                               | exidy.cpp                        |
| piratetr      | Pirate Treasure                                     | gameplan.cpp                     |
| pnkpnthr      | Pink Panther                                        | gts80.cpp                        |
| potogold      | Pot of Gold                                         | gameplan.cpp                     |
| punk          | Punk!                                               | gts80a.cpp                       |
| qbert         | Q*bert (US set 1)                                   | gottlieb.cpp                     |
| qberta        | Q*bert (US set 2)                                   | gottlieb.cpp                     |
| qbertj        | Q*bert (Japan)                                      | gottlieb.cpp                     |
| qbertqub      | Q*bert's Qubes                                      | gottlieb.cpp                     |
| qberttst      | Q*bert (early test version)                         | gottlieb.cpp                     |
| qbquest       | Q*Bert's Quest                                      | gts80a.cpp                       |
| qbtrktst      | Q*bert Board Input Test Rom                         | gottlieb.cpp                     |
| rackempp      | Rack 'em Up! (Pinball)                              | gts80a.cpp                       |
| raimfire      | Ready...Aim...Fire!                                 | gts80a.cpp                       |
| raven         | Raven                                               | gts80b.cpp                       |
| ravena        | Raven (alternate set)                               | gts80b.cpp                       |
| raveng        | Raven (German)                                      | gts80b.cpp                       |
| reactor       | Reactor                                             | gottlieb.cpp                     |
| rflshdlx      | Royal Flush Deluxe                                  | gts80a.cpp                       |
| robowars      | Robo-War                                            | gts80b.cpp                       |
| robowarsf     | Robo-War (French)                                   | gts80b.cpp                       |
| rock          | Rock                                                | gts80b.cpp                       |
| rock_enc      | Rock Encore                                         | gts80b.cpp                       |
| rock_encg     | Rock Encore (German)                                | gts80b.cpp                       |
| rockg         | Rock (German)                                       | gts80b.cpp                       |
| rocky         | Rocky                                               | gts80a.cpp                       |
| rockyf        | Rocky (French speech)                               | gts80a.cpp                       |
| s80btest      | System 80B Test                                     | gts80b.cpp                       |
| s80tst        | System 80 Test                                      | gts80.cpp                        |
| sorbit        | Super Orbit                                         | gts80a.cpp                       |
| spectra       | Spectra IV                                          | spectra.cpp                      |
| spidermn      | The Amazing Spider-Man                              | gts80.cpp                        |
| spirit        | Spirit                                              | gts80a.cpp                       |
| sprbreak      | Spring Break                                        | gts80b.cpp                       |
| sprbreaka     | Spring Break (alternate set)                        | gts80b.cpp                       |
| sprbreakf     | Spring Break (French)                               | gts80b.cpp                       |
| sprbreakg     | Spring Break (German)                               | gts80b.cpp                       |
| sprbreaks     | Spring Break (single ball game)                     | gts80b.cpp                       |
| sqbert        | Faster, Harder, More Challenging Q*bert (prototype) | gottlieb.cpp                     |
| starrace      | Star Race                                           | gts80.cpp                        |
| starwars      | Star Wars (set 1)                                   | starwars.cpp                     |
| starwars1     | Star Wars (set 2)                                   | starwars.cpp                     |
| starwarso     | Star Wars (set 3)                                   | starwars.cpp                     |
| striker       | Striker                                             | gts80a.cpp                       |
| stvboy        | Super TV Boy (PAL)                                  | tvboy.cpp                        |
| tagteamp      | Tag-Team Wrestling                                  | gts80b.cpp                       |
| tagteamp2     | Tag-Team Wrestling (rev.2)                          | gts80b.cpp                       |
| tagteampg     | Tag-Team Wrestling (German)                         | gts80b.cpp                       |
| teetert       | Teeter Torture (prototype)                          | exidy.cpp                        |
| thegames      | The Games                                           | gts80a.cpp                       |
| timeline      | Time Line                                           | gts80.cpp                        |
| tomcat        | TomCat (prototype)                                  | tomcat.cpp                       |
| tomcatsw      | TomCat (Star Wars hardware, prototype)              | starwars.cpp                     |
| touchdn       | Touchdown                                           | gts80a.cpp                       |
| tourtab2      | Tournament Table (set 2)                            | tourtabl.cpp                     |
| tourtabl      | Tournament Table (set 1)                            | tourtabl.cpp                     |
| triplay       | Chicago Cubs' Triple Play                           | gts80b.cpp                       |
| triplaya      | Chicago Cubs' Triple Play (alternate set)           | gts80b.cpp                       |
| tvboyii       | TV Boy II (PAL)                                     | tvboy.cpp                        |
| txsector      | TX-Sector                                           | gts80b.cpp                       |
| txsectorf     | TX-Sector (French)                                  | gts80b.cpp                       |
| txsectorg     | TX-Sector (German)                                  | gts80b.cpp                       |
| tylz          | Tylz (prototype)                                    | gottlieb.cpp                     |
| venture       | Venture (version 5 set 1)                           | exidy.cpp                        |
| venture2      | Venture (version 5 set 2)                           | exidy.cpp                        |
| venture2b     | Venture (version 5 set 2, bootleg)                  | exidy.cpp                        |
| venture4      | Venture (version 4)                                 | exidy.cpp                        |
| victorba      | Victor Banana                                       | victory.cpp                      |
| victory       | Victory                                             | victory.cpp                      |
| victoryp      | Victory (Pinball)                                   | gts80b.cpp                       |
| victorypf     | Victory (Pinball, French)                           | gts80b.cpp                       |
| victorypg     | Victory (Pinball, German)                           | gts80b.cpp                       |
| vlcno_1a      | Volcano (Sound Only set 3)                          | gts80.cpp                        |
| vlcno_1b      | Volcano (Sound Only set 2)                          | gts80.cpp                        |
| vlcno_1c      | Volcano (Sound Only set 1)                          | gts80.cpp                        |
| vlcno_ax      | Volcano                                             | gts80.cpp                        |
| c64_buscard2  | C64 BusCard II cartridge                            | src/devices/bus/c64/buscard2.cpp |
| venture_sound | Exidy SFX+PSG                                       | src/mame/audio/exidy.cpp         |
| mtrap_sound   | Exidy SFX+PSG+CVSD                                  | src/mame/audio/exidy.cpp         |
| victory_sound | Exidy SFX+PSG+Speech                                | src/mame/audio/exidy.cpp         |
| gotsndr1      | Gottlieb Sound rev. 1                               | src/mame/audio/gottlieb.cpp      |
| gotsndr1vt    | Gottlieb Sound rev. 1 with Votrax                   | src/mame/audio/gottlieb.cpp      |

**Comment by ajrhacker** [comment]
In a SB discussion two years ago, @DavidHaywood noted that the new 6532 device broke a2600 and wondered exactly what possessed @curt-coder to add "time travel" support to it.

**Comment by Tafoid** [comment]
From what I remember, at least, there was Supercharger Cassette loading (you need to mount scharger cart to access cassette) which didn't work with the "new" implementation for a2600.  AFAIK there is a bug on MT that mentioned it and some problems with using "new" with a7800 and  also has some test programs for each machine, I believe.
https://mametesters.org/view.php?id=6629

**Comment by colinhowell** [comment]
The old 6530/6532 implementation might be considered two different implementations, as it is split up into two separate pairs of files with different authors and a different naming scheme: mos6530.{cpp,h} for the 6530, by Curt Coder, and 6532riot.{cpp,h} for the 6532, by Aaron Giles. Both only implement the I/O and timer portions of the devices, unlike the new 6530/6532 implemention in mos6530n.{cpp,h} which also handles the ROM and RAM portions.

**Comment by ajrhacker** [comment]
Since 5a84d5568e758d2000f1730b1aa32e4494b27fb5, there is now only one 6530/6532 device implementation.
