### ISSUE TITLE
Eliminate the need to zero device class memory

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#5799]
For historical reasons, MAME zeroes memory where a device structure will be constructed.  This is a problem for two reasons:
* It’s depending on non-standard behaviour.  On construction, you must assume that memory is uninitialised.  We also have to disable lifetime dead store elimination optimisations to stop GCC from optimising away the memory fill.
* It hurts performance.  Many device members (e.g. object finders, callbacks, delegates and smart pointers) have constructors that initialise their members to safe values.  Well-behaved devices initialise state members at construction or start time.  The extra initialisation makes validation, XML generation, and session start take longer.

Coverity identifies members that aren’t initialised on construction.  For the most part, if something isn't initialised on construction or start, it’s probably a bug.  Modern C++ conveniently allows member initialisation to be specified at declaration, so for simple things you don’t even need an extra initialiser list line in your constructor.  For example you can do something like this:

```
class my_device : public device_t
{
...
    int m_something = 0;
    u8 *m_ptr = nullptr;
};
```

The plan is to bite the bullet and change the `make_unique_clear` for general devices to `make_unique` in January, then at some point after that change the `make_unique_clear` for driver devices to `make_unique`.  These are the most problematic uses of `make_unique_clear` – most of the other cases of `make_unique_clear` are initialising POD.

**Comment by ajrhacker** [comment]
The problem also includes the legacy functions `global_alloc_clear`, `global_alloc_array_clear`, `auto_alloc_clear` and `auto_alloc_array_clear`.

**Comment by claydonkey** [comment]
Just porting some legacy stuff - what do you recommend to use to replace: auto_alloc_array_clear?

**Comment by smf-** [comment]
https://github.com/mamedev/mame/commit/42adde9fd5658c8bdf1f24f1970072b8a7db0a54

**Comment by claydonkey** [comment]
wonderful thanks

**Comment by cuavas** [comment]
The `make_unique_clear` template for arrays of trivially constructible types is still present and can be used for this.  (If the type isn’t trivially constructible, update its constructor or member initialisers.)

**Comment by cuavas** [comment]
As of c4f9ff9790382c1c5b99a2ffbb2a14e04d4c7cea, the problematic functions have been removed.
