### ISSUE TITLE
Remove built-in autofire functionality

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#5802]
We now have an autofire plugin contributed by @jackrjli with more functionality than the equivalent internal feature.  The code supporting the internal autofire feature should be removed as it complicates the input system.

**Comment by ajrhacker** [comment]
A feature complicating the input system in a similar way is `PORT_IMPULSE`. There's no adequate generic substitute for that yet, but it too ought to go away sooner or later.

**Comment by cuavas** [comment]
Addressed in 90fe1e649a7bc9ea667de249736062d5dea21f7a
