### ISSUE TITLE
Deploy a pythonic solution for Software List XMLs

### ISSUE THREAD

**Issue by angelosa** [mamedev/mame#5809]
List of things that can help developers and testers alike on analysis and validation. Feel free to suggest additional features that are pragmatically doable over how SW XMLs works out:

1. Convert structures into a [pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) DataFrame. Goal is having something that's easy to look at, filter and even expose to a visualization service;
2. Make basic statistical analysis, for example convert the current flags like supported and bad_dump into percentages, eventually getting factual utility over declaring if a given HW actually works or not;
3. Convert testing notes like [archimdes.xml](https://github.com/mamedev/mame/blob/master/hash/archimedes.xml) and [psx.xml](https://raw.githubusercontent.com/mamedev/mame/psx_metafix/hash/psx.xml) and aggregate to DF. Notice that I'm using a multi-line comment pattern before each individual entry which *seemed* the most logical solution being proven on the field and failing to be concise. We can resolve this by declaring a per-HW ruleset and test on field if this approach can work out for everyone.
4. Setup a Machine Learning classification, extracting information from testing notes into a broader range of topics, i.e. retrieving information on semantics and how many issues in the graphics/sounds/miscellanea depts. there are. Objective of this is to have a TDD-like approach on device health and again get factual utility over declaring status flags for those.

**Comment by cuavas** [comment]
Pandas likely isn't the right tool for the job.  It's designed for time series analysis where you've got lots of sample points.  You use it for things like stock prices where you have an update every second, not stuff that's updated a few times a month.  I do agree that it would be nice to have more analytics on machine/software data though.

**Comment by angelosa** [comment]
Thought of pandas because it has trivial data visualization to debug via [jupyter notebooks](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) and externally via the file conversions we can unanimously care about in the `to_*` functions (HTML, Excel, LaTeX to name a few top tiers here).

**Comment by etabeta78** [comment]
That's true for Pandas Series, but Pandas DataFrames have a lot of
statistical stuff for general structured data that go beyond time series
and they can be fed to machine learning algorithms in scikit-learn.
Same goes for R language data.frames or data.tables.

I had been using R & Python(3) to manage some XML softlists in the past,
but this usually gives a lot of headaches with very large structured
softlists, like saturn or snes, where you would like to preserve non-alpha
order (related to regions or particular bunch of entries) or where you have
lots of large comments spanning before / after / in-between of entries...

    f.

**Comment by etabeta78** [comment]
The point I was making is that in general is not that difficult to import
and analyze softlist data from XML into Pandas DataFrame (or R data
structures), but things can become a bit more challenging if you want to
restore the (possibly modified content) into the XML while not completely
changing the file structure :-)

    f.

**Comment by mariomadproductions** [comment]
I think it would be useful to have a few more fields, like language and region for the software, md5 and sha256 for the file, and also, some way to represent the dump itself would be useful, e.g. date it was made, who made it, how, plus a way to record raw serials from and photographs of the hardware. That would bring it more in-line with No-Intro and Redump (etc).

**Comment by angelosa** [comment]
I can close this off, I have plans about making a back/frontend that includes XML handling which potentially goes outside MAME scope in the short/medium term.
