### ISSUE TITLE
VS 2019 compilation broken

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#5812]
Hello,

VS 2019 does not seem to like this line:
https://github.com/mamedev/mame/blob/09ac3ebfc3ece16c7e9a88157f4919ba939e3b7f/src/emu/emumem.cpp#L229
https://ci.appveyor.com/project/startaq/mame/builds/28394598/job/l8fx38o5lj70v0sr?fullLog=true

**Comment by cuavas** [comment]
I really don't see how that makes sense at all.  It's complaining that the default is being redefined on the line where it's first defined.  That said, the `handler_width` template doesn't actually depend on anything in the `address_space_specific` so I can try lifting it to an anonymous namespace and fully specialising it.  That might marginally reduce compile times, too.

**Comment by cuavas** [comment]
If 9ce4a078e0707dfbcace92abf4dc1375d811d0f8 doesn't fix it, just suppress the warning.

**Comment by belegdol** [comment]
Local tiny compile of 236c87c has succeeded, appveyor should be good to go too. Thanks for fixing!
