### ISSUE TITLE
severe error when compile mame on big endian hw

### ISSUE THREAD

**Issue by tlosm** [mamedev/mame#5831]
../../../../../src/mame/drivers/akkaarrh.cpp:81:38:   in ‘constexpr’ expansion of ‘operator""_MHz_XTAL(1.20959999999999999999999999999999e+1l)’
../../../../../src/emu/xtal.h:85:83: error: ‘(1.20959999999999999999999999999999e+1l * 1.0e+6l)’ is not a constant expression
   85 | constexpr XTAL operator ""_MHz_XTAL(long double clock) { return XTAL(double(clock * 1e6)); }
      |                                                                             ~~~~~~^~~~~
make[2]: *** [atari.make:1687: ../../../../linux_gcc/obj/x64/Release/src/mame/drivers/akkaarrh.o] Error 1

Machine 970MP  OS Debian 10 bullseye  gcc 9

make SUBTARGET=arcade OS=linux PLATFORM=powerpc -j4

**Comment by cuavas** [comment]
This isn't endian-related.  It's because libgmp (GNU multi-precision library) doesn't support the `long double` format used on PowerPC, so GCC can't compile `constexpr` expressions involving `long double` on GCC.  It's a GCC issue.  Please apply more pressure to the GCC maintainers fix it.

**Comment by tlosm** [comment]
Thanks for the info
