### ISSUE TITLE
-AVIWRITE video problems

### ISSUE THREAD

**Issue by drencorxeen** [mamedev/mame#5836]
Dear Support/Dev team,

So I was trying out a feature I found in the command line list called "-aviwrite" and tried to use it, but the output video is black.  The audio output part of the AVI seems fine.

I did a "mame64.exe coco3h -aviwrite test.avi"
Then did a few things in the emulation and then exited MAME.  After MAME exited I watched the video and the video was black and the audio was fine. (*shrug*) so not sure if it is something I am doing wrong or if something else has to be installed on Windows 10 to make the "-aviwrite" feature work correctly?

**Comment by vadosnaprimer** [comment]
Works for me on the latest release.
![test avi_snapshot_00 02_ 2019 10 31_22 30 54](https://user-images.githubusercontent.com/7092625/67979828-24f14e80-fc2e-11e9-874d-3404d50cc980.png)

**Comment by Tafoid** [comment]
Not sure why, but if you use the default view of **Composite**, it will record.  Tested both -aviwrite and -mngwrite.   If you instead have **RGB** as the output selected, the recording is blank outside of part of the analog cursor that shows up when first booting coco3.

**Comment by drencorxeen** [comment]
Ah that explains it, I only use RGB.  Is there a way to fix the video recording for the RGB side?

**Comment by Tafoid** [comment]
Something in the driver seems to be preventing even a snapshot to be made when RGB is chosen as the output video.  That is pretty odd.  I know there was an issues with displaying the screens lately that was worked around via a .lay file so there may be something do that...

**Comment by Tafoid** [comment]
I was reminded that in order to proper record/snap non-standard views, in some cases, you need to explicitly set "snapview" in .ini (or -snapview) to "RGB" in this case.  Doing so allows snapshots and video to be recorded with the non-standard view you chose.

**Comment by cuavas** [comment]
I'm still not happy with the way that driver always has both screens present but defaults to a view hiding one.  At any rate, `-aviwrite` is working correctly and recording the raw image from the first screen.

**Comment by drencorxeen** [comment]
> 
> 
> I'm still not happy with the way that driver always has both screens present but defaults to a view hiding one. At any rate, `-aviwrite` is working correctly and recording the raw image from the first screen.

I am not happy that there are two screens either.  Why is there two?  Can't it be done with just one switching between composite and RGB on that one display?

**Comment by angelosa** [comment]
Technically a monitor composite/rgb switch should be a slot option being an HW connection, in general a full QA of the Tandy Radio Shack stuff is something that I have in my radar.

**Comment by drencorxeen** [comment]
> 
> 
> Technically a monitor composite/rgb switch should be a slot option being an HW connection, in general a full QA of the Tandy Radio Shack stuff is something that I have in my radar.

That is nifty :D can't wait to see that :D

**Comment by npwoods** [comment]
As the person who put the most work on the CoCo drivers over the last two decades, I am open to suggestions on better ways to represent this.

That said, having representing Composite & RGB as two monitors is probably the most "by the book" way to handle this.  As memory serves, the CoCo 3 had two independent ports for monitors, one that emitted the Composite signal and one that emitted the RGB signal.  It is possible to hook these up to two independent monitors the same way that a PC with two HDMI ports can be hooked up to two independent monitors.

**Comment by vadosnaprimer** [comment]
Does that mean mame outputs a YUV signal in this case?

**Comment by rb6502** [comment]
I do think it violates least surprise for -snapview to not default to -view.

**Comment by drencorxeen** [comment]
> 
> 
> As the person who put the most work on the CoCo drivers over the last two decades, I am open to suggestions on better ways to represent this.
> 
> That said, having representing Composite & RGB as two monitors is probably the most "by the book" way to handle this. As memory serves, the CoCo 3 had two independent ports for monitors, one that emitted the Composite signal and one that emitted the RGB signal. It is possible to hook these up to two independent monitors the same way that a PC with two HDMI ports can be hooked up to two independent monitors.

@npwoods ,
Yes the CoCo3 does have two outputs and they both output their own perspective of the output.  I myself am happy with the CoCo 3 emulation itself.  I am also glad for the work you have done with the CoCo emulation and keeping it going.

I myself just found out about the AVIWRITE feature and just wish it would switch/follow what the active display is, but at least for now I know how to get around it.
