### ISSUE TITLE
HP optional ROM slots probably don’t need device_slot_interface

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#5839]
Slots/sockets that are only used for storage and never need to instantiate additional devices don’t need to implement `device_slot_interface`, they only need to implement `device_image_interface`.  For example of this, see `intel_imm6_76_device` (src/mame/machine/imm6_76.{h,cpp}) or `ng_memcard_device` (src/mame/machine/ng_memcard.{h,cpp}).  Yes, I realise that the latter is physically identical to a PCMCIA Type I slot, but we make simplifying assumptions because the hosts only support JEIDA Version 3 which pre-dates PCMCIA 1.0 (PCMCIA JEDEC SRAM cards effectively identical to JEIDA Version 3 SRAM cards).

As far as I can tell, the HP optional ROM slots are only used for storage.  Each of them has a single type of card device, and all the logic is in the slot device itself.  The card devices are effectively placeholders.  I don’t see anything preventing these from losing the `device_slot_interface` base and being moved to src/mame, simplifying them considerably.

The affected devices are in:
* src/devices/bus/hp80_optroms
* src/devices/bus/hp9825_optroms
* src/devices/bus/hp_optroms (this one is poorly named – it seems to be specific to the HP9845)

Can you comment on this please @fulivi?  In real life, are these slots ever (ab)used for other peripherals, e.g. real-time clocks or some other expansion devices?

**Comment by fulivi** [comment]
Hi,

I think you're right, those HP optional ROMs only hold ROM cartridges 
and nothing else. The only (slight) complication is that some cartdriges 
have some sort of bank switching mechanism (in HP9825 mass storage ROMs 
mainly).

And, yes, "hp_optroms" should be "hp9845_optroms". It was the first I 
developed and at the time there was no need to differentiate it from 
other HP systems.

Do you need me to touch any of this code? Need anything else? Just let 
me know.

Thanks.

--F.Ulivi

**Comment by cuavas** [comment]
It would be nice if you could do it, but if you don’t have time, someone else will get to it eventually.

**Comment by fulivi** [comment]
Ok, I should have some time for this over the next few days.
