### ISSUE TITLE
CHD converted from new Dreamcast Redump files in CUE+BIN format don't work

### ISSUE THREAD

**Issue by luke-70it** [mamedev/mame#5866]
CHDs generated from previous Redump set in gdi+bin work fine.
CHDs converted from new set in cue+bin format don't work.

**Comment by luke-70it** [comment]
I'm not sure the problem is related to chdman. It may be an emulator issue...

**Comment by rb6502** [comment]
GD-ROMs are only supported from .GDI files.  We do not plan to support other formats at this time.
