### ISSUE TITLE
chdman extractcd output is not the same as input on multiple audio bins

### ISSUE THREAD

**Issue by luke-70it** [mamedev/mame#5867]
It would be nice to obtain same cue+bin files used to convert to CHD, when extracting it.
Original CD dump consisting in multiple bins are converted back in a single bin file.

**Comment by Zenjir0** [comment]
I too would like to see the output the same as the input, instead of having a merged single BIN file.

**Comment by oblivioncth** [comment]
Would it be acceptable to add a switch for the extractcd command to specify if you want multi-track images as separate bins or not?

**Comment by eddlang** [comment]
I think this is a rather important feature to have. If my input is split-bin files, I'd expect to get the same files after extraction.

**Comment by MestreLion** [comment]
I was really surprised when I noticed that, not only split BIN files were not the default behavior of `extractcd`, but there was no option to make it so in `chdman` at all! Mame devs being so zealots about preservation, this was quite shocking.

Does `chdman` stores the original filenames, or does the CHD format even supports this?

**Comment by rb6502** [comment]
MAME is preserving the actual CD data, not the intermediate rip format.  You can import an ISO or CDRDAO bin/toc rip and export it as bin/cue and vice-versa.  The data is what's important, not the cue file.

**Comment by eddmanx** [comment]
> MAME is preserving the actual CD data, not the intermediate rip format. You can import an ISO or CDRDAO bin/toc rip and export it as bin/cue and vice-versa. The data is what's important, not the cue file.

You're correct that the data is preserved, and if you split the extracted bin into multiple ones their checksum would match the originals.

It's just that it's less user friendly, when the input was originally multiple bins.

**Comment by Immersion95** [comment]
> > MAME is preserving the actual CD data, not the intermediate rip format. You can import an ISO or CDRDAO bin/toc rip and export it as bin/cue and vice-versa. The data is what's important, not the cue file.
> 
> You're correct that the data is preserved, and if you split the extracted bin into multiple ones their checksum would match the originals.
> 
> It's just that it's less user friendly, when the input was originally multiple bins.

Binmerge can do : Multiple bin/cue <-----> Single bin/cue
Oxyromon can do : chd <-----> Multiple bin/cue

**Comment by eddmanx** [comment]
> Binmerge can do : Multiple bin/cue <-----> Single bin/cue Oxyromon can do : chd <-----> Multiple bin/cue

I'm well aware.

**Comment by MestreLion** [comment]
Yes, a lot of tools can handle `chd` and `cue/bin` (with varying degrees of usability, I've already reported 2 issues/requests in `binmerge`). 

So what?

`chdman` _itself_ is still unable to do a perfect round-trip conversion of its input data. True, all actual _data_ is preserved, but `chdman` being the reference implementation of the `CHD` format, whose "losslessness" was one of its major "selling points", it is a bit surprising one would have to resort to third-party tools to fully restore the original data _in its original format_.

**Comment by galibert** [comment]
The original format is a set of pits and lands on a polycarbonate support.  Not bin/cue files.

**Comment by BParks21** [comment]
> I too would like to see the output the same as the input, instead of having a merged single BIN file.
> 
> EDIT: Right now the only way you can break up the BIN file into multiple BINs is if you use a third party tool called binmerge: https://github.com/putnam/binmerge

How do I use it? Do I decompress the chd back to bin/cue then run the bin/cue in binmerge? I'm not sure how to use binmerge? Man I wish CHDMAN could just do this on it's own. I did not know going in that it couldn't return all the bin files separately when decompressed. I like having the option to revert them back to the original format matching redump database.

**Comment by landfillbaby** [comment]
> Would it be acceptable to add a switch for the extractcd command to specify if you want multi-track images as separate bins or not?

I just made a PR for this :) #11727

**Comment by cuavas** [comment]
This should be addressed by PR #12191 (merged as 79c1ae350d07b2c7516e4d2652453cb955067814).
