### ISSUE TITLE
Possible wd_fdc wd1772 bug?

### ISSUE THREAD

**Issue by TwistedTom** [mamedev/mame#5893]
I'm trying to write a driver for ZX Spectrum expansion device that uses WD1772 floppy controller. Looking at rom code, it sends one single command 0xd0 (type IV command "Force Interrupt") to the fdc command reg, it then reads the fdc status reg and does bit test on bit 1 (index pulse).
It expects this bit to be 1, then 0, then back to 1. If that doesn't happen it bails out with no disk error.
I know nothing about this fdc except reading datasheet so I don't know if this's typical or unusual behaviour (I guess the latter otherwise other machines wouldn't work). I know the index pulse should be a steady stream of bits, what I'm not clear about is that one single 0xd0 command all it should take to spin up the disk? 
I've found if I use mame debugger, if I don't mount an image, send command 0xd0, break, then "insert" the disk/image, then continue it works! Also patching out that bit of rom code fixes it too.
Does this sound like it could be a bug in wd_fdc or some other part of mame?

**Comment by ajrhacker** [comment]
My guess is that the WD controller's "force interrupt" command should actually cause the motor to spin up much like every other command received with bit 3 = 0 when MO is off.

**Comment by TwistedTom** [comment]
Hmm, so sounds like a bug then, good source, never thought to look for a logic definition for a fdc :)
I'll have to go through that and any other available info, get a good understanding of the devise before I tackle this!

**Comment by p1pkin** [comment]
> I'll have to go through that and any other available info, get a good understanding of the device before I tackle this!

sadly there is lack of really detailed WD FDC info.
I've sneak peek at RE'd 1772 'schematics' here http://dlcorp.nedopc.com/viewtopic.php?f=21&t=1580
and it seems MO pin latch may be set or reset only by specific values of 6bits of microcode ROM, but sadly I dont understand all the underlying ROM data fetch logic.

**Comment by TwistedTom** [comment]
Nice find, great work those guys have done there!

**Comment by TwistedTom** [comment]
So turns out wd_fdc does not spinup on receipt of 0xd0, i've made it do so and has fixed my problem. Does seem to be the expected behaviour from what I can tell (ajrhacker's link, other emulator sources etc.) Also found the Sam Coupe driver was suffering the same problem and this fixes that too!

**Comment by rb6502** [comment]
That sounds great.  Can you submit the WD1772 change?

**Comment by TwistedTom** [comment]
Included in PR #5931
