### ISSUE TITLE
build fails on centos 8

### ISSUE THREAD

**Issue by gsgatlin** [mamedev/mame#5914]
Hello. Not sure if there is a way around this but I get an error when trying to build on centos 8 that I do not see on centos 7 or fedora.

It seems to do this when building a new rpm as well and when just typing

make TOOLS=1 PYTHON_EXECUTABLE=python3

after extracting.

Here is the output:

cc1plus: warning: ./../../../../linux_gcc/obj/x64/Release/emu.h.gch: had text segment at different address
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: fatal error: ../../../../linux_gcc/obj/x64/Release/emu.h: No such file or directory
compilation terminated.

I added "-Winvalid-pch" to get a more detailed error message. Without that I just get:

cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: ../../../../linux_gcc/obj/x64/Release/emu.h: No such file or directory
compilation terminated.

Or when just running make after extracting:
make TOOLS=1 PYTHON_EXECUTABLE=python3 REGENIE=1

Done. Generated 381/381 projects.
Compiling src/emu/drivers/empty.cpp...
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: ../../../../linux_gcc/obj/x64/Release/emu.h: No such file or directory
compilation terminated.
make[2]: *** [precompile.make:338: ../../../../linux_gcc/obj/x64/Release/src/emu/drivers/empty.o] Error 1
make[1]: *** [Makefile:88: precompile] Error 2
make: *** [makefile:1349: linux_x64] Error 2

Is this a bug in the compiler on centos 8 or might there be a way around this? Thanks for any ideas you may have.

**Comment by cracyc** [comment]
Maybe https://bugzilla.redhat.com/show_bug.cgi?id=1721553#c4 ?  Did you upgrade gcc without make clean?

**Comment by gsgatlin** [comment]
Hmnn. I didn't upgrade gcc. after make clean it still gives the same error. But thank you for the link to the bug report. I have added a comment and added myself to the cc list on that bug.

I don't actually see a way to update gcc in centos 8 yet. Maybe at some point they will make a  module streams for gcc v9? But I'm not able to figure that out.

**Comment by angelosa** [comment]
From what I can tell you were using gcc 8.x.x, is that even supposed to compile with current tree?
And Centos 8 is [EOL](https://blog.centos.org/2020/12/future-is-centos-stream/) anyway, wontfix?

**Comment by gsgatlin** [comment]
It turns out you can install  gcc-toolset-9-gcc-c++-9.2.1-2.2.el8.x86_64 from AppStream in centos 8 stream. So this is the suggested workaround.

**Comment by devtram** [comment]
> Maybe https://bugzilla.redhat.com/show_bug.cgi?id=1721553#c4 ? Did you upgrade gcc without make clean?

You rock it worked  with `make -j3` after `make clean` within `mame` folder
