### ISSUE TITLE
Autofire Lua script doesn't support mouse buttons

### ISSUE THREAD

**Issue by Firehawke** [mamedev/mame#5950]
You can't set up autofire trigger buttons on mouse buttons as of the new 0.216 autofire script. While I can't think of any games off the top of my head where this is needed, I'm sure at least one exists.

**Comment by cracyc** [comment]
I can't get mouse buttons to respond in the input menu either.

**Comment by Firehawke** [comment]
Make sure 

> mouse 1

 is in the .ini file. I believe it defaults to off.

**Comment by cracyc** [comment]
Thanks, adding -mouse to command line is the same.  When I do that though, the autofire plugin detects the mouse clicks.

**Comment by Firehawke** [comment]
I'm seeing this in the logs now:

```
[LUA ERROR] in menu_callback: plugins/autofire/autofire_menu.lua:116: sol: attempt to index (get) lua_nil value "seq_poll_modified" on userdata (bad (misspelled?) key name or does not exist)
[LUA ERROR] in menu_callback: plugins/autofire/autofire_menu.lua:116: sol: attempt to index (get) lua_nil value "seq_poll_modified" on userdata (bad (misspelled?) key name or does not exist)
[LUA ERROR] in menu_callback: plugins/autofire/autofire_menu.lua:116: sol: attempt to index (get) lua_nil value "seq_poll_modified" on userdata (bad (misspelled?) key name or does not exist)
[LUA ERROR] in menu_callback: plugins/autofire/autofire_menu.lua:116: sol: attempt to index (get) lua_nil value "seq_poll_modified" on userdata (bad (misspelled?) key name or does not exist)
[LUA ERROR] in menu_callback: plugins/autofire/autofire_menu.lua:116: sol: attempt to index (get) lua_nil value "seq_poll_modified" on userdata (bad (misspelled?) key name or does not exist)
```

**Comment by cracyc** [comment]
Yep, that was added earlier this week.

**Comment by Firehawke** [comment]
Okay, 99% certain this and the other are going to be user error. I'll close both once I've confirmed post-recompile.

**Comment by Firehawke** [comment]
Yeah, updating EXE fixed the issue. Apparently something changed since my previous build that allowed mouse buttons to be bound. Not a bug.
