### ISSUE TITLE
Discord presence plugin doesn't seem to be working.

### ISSUE THREAD

**Issue by Firehawke** [mamedev/mame#5952]
Here's a sample run, no errors appear in the output but Discord is definitely not detecting the MAME instance and showing any information:

```
PS C:\emu\mame-indev> .\mame64.exe alcon
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Attempting load of vertical.ini
Attempting load of arcade.ini
Attempting load of raster.ini
Parsing raster.ini
Attempting load of source\slapfght.ini
Attempting load of alcon.ini
Starting plugin autofire...
Starting plugin data...
Starting plugin discord...
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Attempting load of vertical.ini
Attempting load of arcade.ini
Attempting load of raster.ini
Parsing raster.ini
Attempting load of source\slapfght.ini
Attempting load of alcon.ini
Video: Monitor                                                           131122 = "\\.\DISPLAY1" (primary)
Video: Monitor                                                           131073 = "\\.\DISPLAY2"
Video: Monitor                                                            65588 = "\\.\DISPLAY3"
Video: Monitor                                                        455282921 = "\\.\DISPLAY4"
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: found H:\Support\MAME\artwork\alcon.zip ECD
unzip: H:\Support\MAME\artwork\alcon.zip has no ZIP64 ECD locator
unzip: read H:\Support\MAME\artwork\alcon.zip central directory
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
Physical width 1920, height 1080
RawInput: APIs detected
RawInput: APIs detected
RawInput: APIs detected
DirectSound: Primary buffer: 48000 Hz, 16 bits, 2 channels
Input: Adding keyboard #0: HID Keyboard Device (device id: \\?\HID#VID_1532&PID_0067&MI_01&Col01#7&39ff06a5&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #1: Razer BlackWidow Chroma V2 (device id: \\?\HID#VID_1532&PID_0221&MI_01&Col01#7&de0654a&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #2: HID Keyboard Device (device id: \\?\HID#VID_1532&PID_0306&MI_00&Col01#2&373ba01a&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #3: Razer Naga Trinity (device id: \\?\HID#VID_1532&PID_0067&MI_02#7&26ceea67&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #4: HID Keyboard Device (device id: \\?\HID#VID_1532&PID_0221&MI_00#7&15f6d878&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding mouse #0: HID-compliant mouse (device id: \\?\HID#VID_1532&PID_0306&MI_00&Col00#2&38176d1f&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding mouse #1: Razer BlackWidow Chroma V2 (device id: \\?\HID#VID_1532&PID_0221&MI_02#7&31b7a30c&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding mouse #2: Razer Naga Trinity (device id: \\?\HID#VID_1532&PID_0067&MI_00#7&7f08&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding lightgun #0: HID-compliant mouse (device id: \\?\HID#VID_1532&PID_0306&MI_00&Col00#2&38176d1f&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding lightgun #1: Razer BlackWidow Chroma V2 (device id: \\?\HID#VID_1532&PID_0221&MI_02#7&31b7a30c&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding lightgun #2: Razer Naga Trinity (device id: \\?\HID#VID_1532&PID_0067&MI_00#7&7f08&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding joystick #0: Wireless Controller (device id: Wireless Controller product_05c4054c-0000-0000-0000-504944564944 instance_a21ff450-ea05-11e9-8002-444553540000)
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
Region ':maincpu' created
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: found h:\ROMs\MAME\alcon.zip ECD
unzip: h:\ROMs\MAME\alcon.zip has no ZIP64 ECD locator
unzip: read h:\ROMs\MAME\alcon.zip central directory
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':audiocpu' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':bmcu:mcu' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':gfx1' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':gfx2' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':gfx3' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':proms' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':bmcu:mcu:bootstrap' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: opened archive file h:\ROMs\MAME\m68705p5.zip
unzip: found h:\ROMs\MAME\m68705p5.zip ECD
unzip: h:\ROMs\MAME\m68705p5.zip has no ZIP64 ECD locator
unzip: read h:\ROMs\MAME\m68705p5.zip central directory
unzip: closing archive file h:\ROMs\MAME\m68705p5.zip and sending to cache
Optional memory region ':screen' not found
Starting Alcon (US) ':'
  (missing dependencies; rescheduling)
Starting Zilog Z80 ':maincpu'
Starting 74LS259 Addressable Latch ':mainlatch'
Starting Zilog Z80 ':audiocpu'
Starting Taito MC68705 MCU Interface ':bmcu'
Starting Motorola MC68705P5 ':bmcu:mcu'
Starting Buffered 8-bit Sprite RAM ':spriteram'
Starting Video Screen ':screen'
  (missing dependencies; rescheduling)
Starting gfxdecode ':gfxdecode'
Starting palette ':palette'
Starting Speaker ':mono'
  (missing dependencies; rescheduling)
Starting AY-3-8910A PSG ':ay1'
Starting AY-3-8910A PSG ':ay2'
Starting Alcon (US) ':'
  (missing dependencies; rescheduling)
Starting Video Screen ':screen'
Starting Speaker ':mono'
Starting Alcon (US) ':'
un7z: opened archive file cheat.7z
un7z: closing archive file cheat.7z and sending to cache
Loading cheats file from cheat
un7z: found cheat.7z in cache
un7z: closing archive file cheat.7z and sending to cache
Attempting to parse: default.cfg
Attempting to parse: alcon.cfg
Starting Alcon (US)
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
Average speed: 100.00% (15 seconds)
```

**Comment by cracyc** [comment]
Works for me.  Just to make sure, you are using the Discord client and not just a normal web browser right?

**Comment by Firehawke** [comment]
Yep, I'm on the Discord client. I'll get a screenshot here in a moment.

**Comment by cracyc** [comment]
If you aren't using the latest copy of discord/init.lua from the master branch, try it because extra verbose output was recently added and it doesn't need a new mame build to work.

**Comment by Firehawke** [comment]
A quick overview of my setup---
This is Windows 10. I have a c:\emu\mame-indev folder that uses symlinks and junctions to point to the c:\msys64\src\mame\ folders and files for the critical necessary stuff (plugins, bgfx, etc) so that I can keep my source tree clean and my INI and other user-created stuff over in the c:\emu\mame-indev structure.

Since I just went back to origin/master this morning, my plugins are up to date with mamedev/mame as of three hours ago. The only thing that's NOT up to date is my actual .EXE, which is perhaps too old. That's why I'm doing a recompile now.

**Comment by Firehawke** [comment]
Okay, still not working. Turned off local firewall to be on the safe side. 

With the latest version, and with highscores DAT support turned on so we can see if other plugins are working:

``
PS C:\emu\mame-indev> .\mame64.exe alcon -verbose -window
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Attempting load of vertical.ini
Attempting load of arcade.ini
Attempting load of raster.ini
Parsing raster.ini
Attempting load of source\slapfght.ini
Attempting load of alcon.ini
Reading translation file English: 1 strings, original table at word offset 7, translated table at word offset 9
Loaded 0 translations from file English
Starting plugin autofire...
Starting plugin hiscore...
Starting plugin discord...
Starting plugin data...
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Attempting load of vertical.ini
Attempting load of arcade.ini
Attempting load of raster.ini
Parsing raster.ini
Attempting load of source\slapfght.ini
Attempting load of alcon.ini
Video: Monitor                                                           131122 = "\\.\DISPLAY1" (primary)
Video: Monitor                                                           131073 = "\\.\DISPLAY2"
Video: Monitor                                                            65588 = "\\.\DISPLAY3"
Video: Monitor                                                        455282921 = "\\.\DISPLAY4"
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: found H:\Support\MAME\artwork\alcon.zip ECD
unzip: H:\Support\MAME\artwork\alcon.zip has no ZIP64 ECD locator
unzip: read H:\Support\MAME\artwork\alcon.zip central directory
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
Physical width 797, height 1080
RawInput: APIs detected
RawInput: APIs detected
RawInput: APIs detected
DirectSound: Primary buffer: 48000 Hz, 16 bits, 2 channels
Input: Adding keyboard #0: HID Keyboard Device (device id: \\?\HID#VID_1532&PID_0067&MI_01&Col01#7&39ff06a5&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #1: Razer BlackWidow Chroma V2 (device id: \\?\HID#VID_1532&PID_0221&MI_01&Col01#7&de0654a&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #2: HID Keyboard Device (device id: \\?\HID#VID_1532&PID_0306&MI_00&Col01#2&373ba01a&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #3: Razer Naga Trinity (device id: \\?\HID#VID_1532&PID_0067&MI_02#7&26ceea67&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding keyboard #4: HID Keyboard Device (device id: \\?\HID#VID_1532&PID_0221&MI_00#7&15f6d878&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding mouse #0: HID-compliant mouse (device id: \\?\HID#VID_1532&PID_0306&MI_00&Col00#2&38176d1f&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding mouse #1: Razer BlackWidow Chroma V2 (device id: \\?\HID#VID_1532&PID_0221&MI_02#7&31b7a30c&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding mouse #2: Razer Naga Trinity (device id: \\?\HID#VID_1532&PID_0067&MI_00#7&7f08&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding lightgun #0: HID-compliant mouse (device id: \\?\HID#VID_1532&PID_0306&MI_00&Col00#2&38176d1f&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding lightgun #1: Razer BlackWidow Chroma V2 (device id: \\?\HID#VID_1532&PID_0221&MI_02#7&31b7a30c&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding lightgun #2: Razer Naga Trinity (device id: \\?\HID#VID_1532&PID_0067&MI_00#7&7f08&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})
Input: Adding joystick #0: Wireless Controller (device id: Wireless Controller product_05c4054c-0000-0000-0000-504944564944 instance_a21ff450-ea05-11e9-8002-444553540000)
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
Region ':maincpu' created
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: found h:\ROMs\MAME\alcon.zip ECD
unzip: h:\ROMs\MAME\alcon.zip has no ZIP64 ECD locator
unzip: read h:\ROMs\MAME\alcon.zip central directory
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':audiocpu' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':bmcu:mcu' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':gfx1' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':gfx2' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':gfx3' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':proms' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: opened archive file h:\ROMs\MAME\alcon.zip
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
Region ':bmcu:mcu:bootstrap' created
unzip: found h:\ROMs\MAME\alcon.zip in cache
unzip: closing archive file h:\ROMs\MAME\alcon.zip and sending to cache
unzip: opened archive file h:\ROMs\MAME\m68705p5.zip
unzip: found h:\ROMs\MAME\m68705p5.zip ECD
unzip: h:\ROMs\MAME\m68705p5.zip has no ZIP64 ECD locator
unzip: read h:\ROMs\MAME\m68705p5.zip central directory
unzip: closing archive file h:\ROMs\MAME\m68705p5.zip and sending to cache
Optional memory region ':screen' not found
Starting Alcon (US) ':'
  (missing dependencies; rescheduling)
Starting Zilog Z80 ':maincpu'
Starting 74LS259 Addressable Latch ':mainlatch'
Starting Zilog Z80 ':audiocpu'
Starting Taito MC68705 MCU Interface ':bmcu'
Starting Motorola MC68705P5 ':bmcu:mcu'
Starting Buffered 8-bit Sprite RAM ':spriteram'
Starting Video Screen ':screen'
  (missing dependencies; rescheduling)
Starting gfxdecode ':gfxdecode'
Starting palette ':palette'
Starting Speaker ':mono'
  (missing dependencies; rescheduling)
Starting AY-3-8910A PSG ':ay1'
Starting AY-3-8910A PSG ':ay2'
Starting Alcon (US) ':'
  (missing dependencies; rescheduling)
Starting Video Screen ':screen'
Starting Speaker ':mono'
Starting Alcon (US) ':'
un7z: opened archive file cheat.7z
un7z: closing archive file cheat.7z and sending to cache
Loading cheats file from cheat
un7z: found cheat.7z in cache
un7z: closing archive file cheat.7z and sending to cache
Attempting to parse: default.cfg
Attempting to parse: alcon.cfg
Starting Alcon (US)
hiscore: found hiscore.dat entry for alcon
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
unzip: found H:\Support\MAME\artwork\alcon.zip in cache
unzip: opened archive file H:\Support\MAME\artwork\alcon.zip
unzip: closing archive file H:\Support\MAME\artwork\alcon.zip and sending to cache
hiscore: scores read FAIL
```

We never even get the other error messages. I might need to trace the script with debug output to see where it stops.

**Comment by Firehawke** [comment]
Tracing the script is showing that it's running and apparently generating data (I removed the comments on the output lines) but it's not actually changing anything on Discord itself. Hmmm. Discord says it doesn't detect a game (and yes, the feature is on..)

**Comment by Firehawke** [comment]
...and then suddenly it started working out of nowhere. Seems like a Discord-side issue. I'm going to close this.

**Comment by cracyc** [comment]
If you started discord while the old version of mame was running then it might have taken the named pipe filename that discord uses.  The new version won't try to create the pipe if it doesn't exist so if that is what happened, it shouldn't happen any more.
