### ISSUE TITLE
laserdisc games showing four squares instead of ld video with -bgfx_backend opengl

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#5961]
I just tested 9efc500cc00546a78e918915eedf085231e6397a on linux. While there are no crashes with firefox with neither opengl or vulkan, hlsl enabled or not, LD video is not displayed properly with opengl:
![Zrzut ekranu z 2019-11-20 20-53-13](https://user-images.githubusercontent.com/1208329/69273357-7f038500-0bd8-11ea-8e52-5c52b441e19e.png)
with vulkan everything works fine:
![Zrzut ekranu z 2019-11-20 20-53-43](https://user-images.githubusercontent.com/1208329/69273379-8c207400-0bd8-11ea-9c7c-627c168eabad.png)
This is with Fedora 31 with 440.31 nvidia drivers.
Can it be that the shaders are causing some sort of edge case only the nvidia drivers know how to deal with without crashing?

_Originally posted by @belegdol in https://github.com/mamedev/mame/issues/5830#issuecomment-556321453_

**Comment by belegdol** [comment]
The issue is present as of 14d8cce3466d8a3dc744c5f52483f4b4fccf275b

**Comment by cuavas** [comment]
Confirmed it happens on Windows 10 Pro 1803 as well when using OpenGL backend.  I did a quick check of some other systems with 16-bit palette mode, 32-bit RGB mode and palettes with screen colour and didn't see any issues.  So it seems to affect a fairly specific class of machine.

**Comment by couriersud** [comment]
All works fine if "-bgfx_screen_chains none,none,none,none" is used. Firefox/PR8210 is using Yuv textures for the laser disc content.

**Comment by belegdol** [comment]
This is very strange, why would setting screen chains to none be required for OpenGL but not for vulkan?

**Comment by MooglyGuy** [comment]
Because the issue only affects OpenGL. Duh. Unless you're going to try debugging it, don't ask rhetorical questions like that, it just irritates me and disinclines me from actually wanting to try to work on fixing it.

**Comment by MooglyGuy** [comment]
Fix committed. Works on Windows. Please double-check on Linux and close if fixed.

**Comment by belegdol** [comment]
I can confirm that the issue is fixed as of 8dd5e3d2006f3f28c6bc2a5108c8db324ec3845d:
![Zrzut ekranu z 2019-11-24 20-09-46](https://user-images.githubusercontent.com/1208329/69500070-2265da00-0ef8-11ea-8c10-9cd9c927623d.png)
Thank you MG!
