### ISSUE TITLE
How to detect game state and get game data

### ISSUE THREAD

**Issue by ritterzhou1989** [mamedev/mame#5974]
I would like to detect MAME game state such as game start/game over, and I also want to get the game data such score/health point. How can I achieve this？

**Comment by cuavas** [comment]
Depends entirely on the game.  You have to reverse-engineer the game code to see how it represents this information.  MAME’s built-in debugger and the unidasm tool are useful tools for doing this.  However, this is not the right venue for discussing this.  Try joining a ROM hacking or reverse-engineering forum.

**Comment by ritterzhou1989** [comment]
thx！
