### ISSUE TITLE
MAME ROM set 0.215

### ISSUE THREAD

**Issue by theblackpig75** [mamedev/mame#5986]
None of my Arcade games are now working I am getting the following message. How can I find the ROM sets? I have searched but the only site I have found will not allow download as it is too large 48 GB.

Street Fighter (US, set 1) (sf.zip) requires:

sf.zip  	- INCORRECT SET

These ROMs must be from a MAME 0.215 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files.

**Comment by happppp** [comment]
If you updated your MAME install, some romsets will have become outdated. It is expected and not an issue with MAME.

example:
- newer game revision was found and has become the new main set
- badly dumped romchip was redumped and added
- undumped romchip was added

**Comment by cuavas** [comment]
This message does not come from MAME. Please take this up with whoever you got the front-end or derivative build from.

**Comment by theblackpig75** [comment]
What does that even mean? It is an issue I am experiencing in OpenEmu. Where can I find the ROM set 0.215?

**Comment by cuavas** [comment]
You need to dump ROMs from systems you own or obtain them some other way. Linking to unlicensed ROMs is contributory copyright infringement in many jurisdictions.

OpenEmu is not baseline MAME and we don't support it here.
