### ISSUE TITLE
error compiling groovymame (0.216) on Debian 10 x64

### ISSUE THREAD

**Issue by kaedwood** [mamedev/mame#6019]
I'm trying to compile groovymame (0.216) on Debian 10 x64 and I'm encountering these problems. Any tips? 

Dependencies: 
sudo apt install git build-essential libsdl2-dev libsdl2-ttf-dev libfontconfig-dev qt5-default dos2unix libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev build-dep mame

Building driver list...
36400 driver(s) found
Compiling generated/mame/mame/drivlist.cpp...
Compiling generated/version.cpp...
Linking mame64...
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libSDL2_ttf.so: undefined reference to `SDL_ceilf'
collect2: error: ld returned 1 exit status
make[2]: *** [mame.make:269: ../../../../../mame64] Error 1
make[1]: *** [Makefile:1102: mame] Error 2
make: *** [makefile:1350: linux_x64] Error 2

**Comment by rb6502** [comment]
GroovyMAME is a derivative project and we do not support it here.  This github project is only for vanilla MAME.
