### ISSUE TITLE
SDLMAME 0.216 (bgfx) on macOS 10.14 crashes OS user session

### ISSUE THREAD

**Issue by gregorulm** [mamedev/mame#6021]
I encountered a serious issue with the bgfx backend in SDLMAME on macOS 10.14. When using this option, which is the current default, SDLMAME crashes the user session of macOS upon exit and takes you back to the macOS login screen. This is reproducible. As a workaround, the flag `-video opengl `can be used, which seems to work fine.

**Comment by rb6502** [comment]
-bgfx_backend opengl should also correct the issue and still be faster than -video opengl.

Note that if the OS user session is crashing and you aren't running MAME as root, then it's a fault in the operating system/drivers, not in MAME or BGFX.

**Comment by StLouisCPhT** [comment]
Go into the mame.ini and change the bgfx_path to the specific location of the folder only. For example, I have my path set as such: 

bgfx_path                 "/Users/stlouiscpht/Library/Application Support/mame/bgfx"

Anything else in that path causes the crash to occur at start.

**Comment by cuavas** [comment]
This doesn’t seem to be a problem any more.
