### ISSUE TITLE
Diagonal inputs should be ignored for tgmj, tgm2, tgm2p

### ISSUE THREAD

**Issue by gregorulm** [mamedev/mame#6025]
There is a discrepancy between MAME and the arcade experience in the games tgmj, tgm2, and tgm2p (Tetris: The Grand Master). These games are supposed to be played with a square restrictor plate so that you can only hit left, right, up, and down [1]. Diagonals should not be valid inputs. However, the game code itself does not enforce this limitation. For instance, if you play with an octagonal restrictor plate and you hit a diagonal, horizontals have precedence over verticals. The behavior of MAME is thus similar to playing with an octagonal restrictor, which is sub-optimal and does not mirror the arcade experience.

To reproduce, do:
- launch tgmj (possibly with slowdown option to make verification easier)
- start default game [with tgm2/tgm2p, pick Master or Normal]
- hit down and right (or left) keyboard keys together
- with a square restrictor, D/R or D/L should not register at all, yet in MAME the piece the player currently controls moves to R or L, depending on the key that was pressed

I noticed that some forks of MAME have an option to ignore diagonal inputs as this is an issue with some other games as well [3]. On Reddit, MAME developer Haze remarked that MAME ignores diagonals for games that are marked as requiring 4-way input [2]. If this information is still correct, then the issue is that the aforementioned three games are not marked in that way.

As a general idea, since there is apparently code in MAME that ignores diagonals, could you maybe make this accessible via a command-line switch? This would mirror the real-world situation where users change the restrictor plate on their arcade sticks.

[1] This is community knowledge. There are countless references to this convention on enthusiast forums, e.g. the second post in this thread: https://tetrisconcept.net/threads/how-are-diagonals-registered-in-tgm-3.2976/
[2] https://www.reddit.com/r/MAME/comments/abq57g/anyway_to_restrict_xbox_360_controller_to_4way/
[3] See post #9 in this thread for how this issue was fixed in the fork ShmupMAMETGM by usin the 4-way option via src/emu/inptport:
https://tetrisconcept.net/threads/shmupmametgm-on-linux.2645/

**Comment by DavidHaywood** [comment]
The games are marked as 4-way in the source.

I guess MAME's way of ignoring the diagonals (it will ignore the first input direction pressed and only send the 2nd one - it never sends a diagonal) is just not how you want it to be.

In reality, you can't hit a diagonal on the stick, you can hit a diagonal on the keyboard, MAME has to do *something* about that scenario.

**Comment by gregorulm** [comment]
Would it be possible to simply ignore diagonal inputs? MAME seems to do something similar with contradictory inputs such as pressing L/R at the same time, which can be disabled with the `-joystick_contradictory` flag. If MAME can drop L/R and U/D when pressed simultaneously, then the existing code could be adapted for dropping diagonals with 4-way games, e.g. with a flag `-ignore_diagonals`.

**Comment by cuavas** [comment]
Doing that makes it harder to play platform games that use a 4-direction stick.  You want to be able to make a very snappy transition from horizontal to vertical to horizontal (and vice versa), so you don't want any dead zone between directions at all.

**Comment by rb6502** [comment]
That third link claims the 4-way option was broken in 2011 and the variable that enables it never got set.  Do we know if that's still true, given that was a long time and many refactorings ago?

**Comment by rb6502** [comment]
Answering myself, the flag is set properly in current code, so the 4-way lockout *is* being applied.

**Comment by gregorulm** [comment]
> Doing that makes it harder to play platform games that use a 4-direction stick. You want to be able to make a very snappy transition from horizontal to vertical to horizontal (and vice versa), so you don't want any dead zone between directions at all.

This is not relevant to the current issue, which is specifically about the three games mentioned in the subject line.

**Comment by gregorulm** [comment]
> Answering myself, the flag is set properly in current code, so the 4-way lockout _is_ being applied.

The original post stated that the flag is set but MAME never checks it. Did you also check that this value has an effect?

**Comment by DavidHaywood** [comment]
> This is not relevant to the current issue, which is specifically about the three games mentioned in the subject line.

It's very relevant because MAME is a large project and runs many more than just those 3 games, and any change made is going to affect a lot more than just those 3 games.

**Comment by gregorulm** [comment]
I don't doubt that. However, my suggestion is about an optional flag. Nobody would be forced to use it.

**Comment by smf-** [comment]
It sounds like you want something like -joystick_map extended to
keyboard input as well?

**Comment by cuavas** [comment]
You can get the effect you want with "not" combinations.  You want this kind of arrangement:
* P1 Up = «Up» not «Left» not «Right»
* P1 Down = «Down» not «Left» not «Right»
* P1 Left = «Left» not «Up» not «Down»
* P1 Right = «Right» not «Up» not «Down»

That will cause diagonals to do nothing.

**Comment by gregorulm** [comment]
This works like a charm. Thank you!
