### ISSUE TITLE
Error compiling mame0.216 on Debian10 X64

### ISSUE THREAD

**Issue by kaedwood** [mamedev/mame#6026]
Error:

Archiving liboptional.a...
Compiling src/mame/mame.cpp...
Building driver list...
Compiling generated/version.cpp...
36400 driver(s) found
Compiling generated/mame/mame/drivlist.cpp...
Linking mame64...
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so: undefined reference to `SDL_ceilf'
collect2: error: ld returned 1 exit status
make[2]: *** [mame.make:269: ../../../../../mame64] Error 1
make[1]: *** [Makefile:1102: mame] Error 2
make: *** [makefile:1350: linux_x64] Error 2

**Comment by kaedwood** [comment]
sudo apt list --installed | grep "sdl"


libsdl-image1.2-dev/stable,now 1.2.12-10+deb10u1 amd64 [installed]
libsdl-image1.2/stable,now 1.2.12-10+deb10u1 amd64 [installed,automatic]
libsdl-net1.2-dev/stable,now 1.2.8-6 amd64 [installed]
libsdl-net1.2/stable,now 1.2.8-6 amd64 [installed,automatic]
libsdl-sound1.2/stable,now 1.0.3-9 amd64 [installed,automatic]
libsdl1.2-dev/stable,now 1.2.15+dfsg2-4 amd64 [installed]
libsdl1.2debian/stable,now 1.2.15+dfsg2-4 amd64 [installed,automatic]
libsdl2-2.0-0/stable,now 2.0.9+dfsg1-1 amd64 [installed]
libsdl2-2.0-0/stable,now 2.0.9+dfsg1-1 i386 [installed,automatic]
libsdl2-dev/stable,now 2.0.9+dfsg1-1 amd64 [installed]
libsdl2-gfx-1.0-0/stable,now 1.0.4+dfsg-3 amd64 [installed,automatic]
libsdl2-gfx-dev/stable,now 1.0.4+dfsg-3 amd64 [installed]
libsdl2-image-2.0-0/stable,now 2.0.4+dfsg1-1+deb10u1 amd64 [installed]
libsdl2-image-dev/stable,now 2.0.4+dfsg1-1+deb10u1 amd64 [installed]
libsdl2-mixer-2.0-0/stable,now 2.0.4+dfsg1-1 amd64 [installed]
libsdl2-mixer-dev/stable,now 2.0.4+dfsg1-1 amd64 [installed]
libsdl2-ttf-2.0-0/stable,now 2.0.15+dfsg1-1 amd64 [installed]
libsdl2-ttf-dev/stable,now 2.0.15+dfsg1-1 amd64 [installed]
vlc-plugin-sdl/now 2.2.7-1~deb9u1 amd64 [installed,local]

**Comment by rb6502** [comment]
If the system-provided SDL2_ttf doesn't link against the system-provided SDL2 that's not a MAME. problem, it's a distro problem.  Report it to Debian.
