### ISSUE TITLE
pfmt::format_element is not safe

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#6034]
There are multiple issues with the `pfmt::format_element` function:
* Sets changes the global locale.  This is not thread-safe and should be avoided.  It *definitely* shouldn’t be done in something that could be called frequently.
* It uses C varargs, making it impossible to enforce type safety.
* It uses a fixed size 2KiB buffer which is a big (and hence inefficient) stack frame if the string is a lot shorter than this, but will cause truncation if the input is long.
* It uses its own format syntax, making the code less approachable for new developers.

Is there a good reason the netlist code can't use the formatting functions from src/lib/util/strformat.h like the rest of MAME?  They have numerous advantages:
* Fully type-safe – at worst you’ll get leftover format specifiers in the output.
* Implements the majority of POSIX/SUS/GNU/MSVCRT printf functionality – syntax is familiar for new developers.
* Heavily tested – it’s used pervasively in MAME, and has been adopted outside MAME due to its permissive license.
* Accepts locale as a parameter or uses stream locale – not dependent on global state.
* Doesn’t use any fixed-size buffers.

**Comment by couriersud** [comment]
@cuavas: At which code revision have you been looking? This is the actual version of `pfmt::format_element`.
```
		template <typename T>
		pfmt &format_element(const char32_t cfmt_spec, T &&v)
		{
			rtype ret;
			m_arg++;
			do {
				std::stringstream strm;
				strm.imbue(m_locale);
				ret = setfmt(strm, cfmt_spec);
				if (ret.ret>=0)
				{
					ptype_traits<typename std::decay<T>::type>::streamify(strm, std::forward<T>(v));
					const pstring ps(strm.str());
					m_str = m_str.substr(0, ret.p) + ps + m_str.substr(ret.p + ret.sl);
				}
			} while (ret.ret == 1);
			return *this;
		}
```
None of your comments applies. I therefore propose to close this.
strformat is not an option. netlist and the tools are designed to be compiled standalone as well.

**Comment by couriersud** [comment]
Closing this.
