### ISSUE TITLE
Debian wheezy

### ISSUE THREAD

**Issue by KipourosV** [mamedev/mame#606]
Is there a way/guide on how to build on Debian wheezy?

**Comment by rb6502** [comment]
Compile prerequisties for Jessie (which should also cover Wheezy) are at: http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=103256#Post103256

Actual compiling is simply a matter of "make -jX" and waiting a while.  (X = # of CPU cores plus 1, so -j3 for dual-core, -j5 for quad-core, and -j9 for 8-core).

**Comment by KipourosV** [comment]
Thanx very much!

**Comment by rb6502** [comment]
Check your packages and see if either GCC 4.9 or Clang 3.5 or later are available; if so, installing them may work.  If not, you may need to update your distro if possible.  Otherwise, stick with 0.168 which predates our use of modern C++11 coding techniques.

**Comment by h0tw1r3** [comment]
@KipourosV Compile gcc 4.9+ yourself or try my completely unsupported - figure it out yourself - you break it you buy it - patches. (Hint: you'll need to enable backports). That said, I did try building on Wheezy with the patches below. Worked just fine.

https://github.com/zaplabs/buildsupport/tree/sdlmame

**Comment by rb6502** [comment]
Just a fair warning, if you use any kind of compiler version workaround you lose 100% of support, even if the problem *is* our fault.

**Comment by balr0g** [comment]
@rb6502 it looks like most of those patches seem pretty helpful as they improve minor build system problems. The compiler-support patches seem to be mainly an implementation of make_unique so that it can be used on pre-C++14 compilers. Of course, this will not work in the future when more C++14 features are added...

**Comment by h0tw1r3** [comment]
@balr0g @rb6502  Most of the patches came out of building everything cross platform (linux host, macosx and windows targets). I'd be happy to submit some PR's if you think they would be useful.

**Comment by rb6502** [comment]
Cross-compilation patches would be very acceptable, I just don't want the C++14 workarounds :)

**Comment by mmicko** [comment]
Comments regarding patches :

0001-Refactor-MACOSX_USE_LIBSDL-to-USE_LIBSDL-for-windows.patch  - FINE
0002-add-TOOLCHAIN-make-flag-for-explicit-toolchain-prefi.patch - FINE
0003-allow-libs-to-be-linked-multiple-times.patch - Need to go upstream
0004-upstream-patch-to-fix-threaded-build-race-condition.patch - This will
work on Linux and OSX but will break on windows, that is reason why it is
such as it is now
0005-check-STRIP_SYMBOLS-in-strip-function-add-strip-supp.patch - FINE
0006-fix-cross-windows-targetextension.patch - FINE
0007-genie-make-targets-for-packager-scripts.patch - FINE
0008-fix-windows-bgfx-link-in-sdl-builds.patch - FINE
0009-make-sdl-osd-the-same-size-as-directx.patch - ??? PLEASE CHECK RB
0010-set-plist-dependency-before-task-to-fix-parallel-bui.patch -- FINE
0011-osx-clang-silence-flac-unknown-attribute-error.patch - FINE
0012-implement-remove_extent_t-and-make_unique-for-unsupp.patch - NOPE :)

**Comment by rb6502** [comment]
I have no idea what that 0009- patch is meant to do, could we get some clarification?

**Comment by mmicko** [comment]
thing is that UI window is fullscreen on D3D and BGFX and not on OpenGL

**Comment by rb6502** [comment]
Ok.  That should be fine then if it's been tested.

**Comment by h0tw1r3** [comment]
> 0003-allow-libs-to-be-linked-multiple-times.patch - Need to go upstream

Done

>> 0009-make-sdl-osd-the-same-size-as-directx.patch - ??? PLEASE CHECK RB
> Ok. That should be fine then if it's been tested.

It works quite well for me, I have noticed the aspect appears to be wrong before the machine starts (Initializing message). Could just be SDL trying to be smart, but I will do more testing before I submit a PR.

**Comment by startaq** [comment]
What's with those patches? Is there anything that still needs to be applied?
