### ISSUE TITLE
mame  debug cmd load log error  [:maincpu](no context) :unmapped program memory wite to

### ISSUE THREAD

**Issue by zengfr** [mamedev/mame#6062]
mame rom is capcom dino.zip
maincpu address range is 0x0000-0x180000
mame  debug cmd:  load dino2f.bin,0,10105A
see screen img 
log error [:maincpu](no context) :unmapped program memory wite to xxxxx
![捕获](https://user-images.githubusercontent.com/9524903/70970857-78363800-20da-11ea-9b30-05f909bfbbc2.PNG)

**Comment by angelosa** [comment]
You're attempting to load to a ROM area, hence you get write error messages in log.
If the plan is to remap the ROM to a custom one then you need to override the original ROM name with a separate folder with the same romname (expect CRC/SHA1 errors and may not work if the custom length and original doesn't match).
Arguably arbitrary custom ROM loading can be a "feature request", certainly not this one tho hence closing.
