### ISSUE TITLE
vformula: Crash (access violation) in attract mode.

### ISSUE THREAD

**Issue by Hydreigon223** [mamedev/mame#6081]
This started to happen after the TGP updates in 0.217GIT (tested in both 0.216 and recent GIT versions to verify vformula doesn't crash in 0.216). The crash happens during the second attract loop right before the "pit in" sequence. This is what the crash message said:

Exception at EIP=0000000000449634 (not found): ACCESS VIOLATION
While attempting to read memory at fffffffe0ee5e0a0

RAX=000000000ee4e0a0 RBX=0000000002380410 RCX=0000000006366cc0 RDX=fffffffe00010000
RSI=0000000005549e80 RDI=0000000000000000 RBP=00000000054ec150 RSP=0000000003259118
 R8=0000000000000003  R9=00000000ffffffff R10=0000000006366cc0 R11=0000000006346ab0
R12=0000000000000000 R13=000000001c1e3227 R14=0000000000000119 R15=0000000000000027

Stack crawl:
  0000000003259110: 0000000000449634 (not found)
  00000000032592b0: 00000000007bda43 (not found)
  0000000003259320: 0000000000a56e30 (not found)
  0000000003259410: 0000000000a123f8 (not found)
  000000000325f0c0: 0000000000549376 (not found)
  000000000325f390: 00000000005c9a3b (not found)
  000000000325f620: 00000000005c9ed6 (not found)
  000000000325f680: 0000000000547279 (not found)
  000000000325fe20: 0000000002220679 (not found)
  000000000325fef0: 00000000004013b4 (not found)
  000000000325ff20: 000000000040150b (not found)
  000000000325ff50: 00007ffaf63b7bd4 (BaseThreadInitThunk+0x0014)
  000000000325ffd0: 00007ffaf650ced1 (RtlUserThreadStart+0x0021)

This does not happen in vr as I tested that game in both versions.

**Comment by Tafoid** [comment]
About 75 seconds into the demonstration for machine vformula ONLY in testing.

-----------------------------------------------------
Exception at EIP=0000000001638264 (model1_state::copro_atan_r(address_space&, unsigned int, unsigned int)+0x0024): ACCESS VIOLATION
While attempting to read memory at fffffffe18460f60
-----------------------------------------------------
Stack crawl:
  0000000000229050: 0000000001638264 (model1_state::copro_atan_r(address_space&, unsigned int, unsigned int)+0x0024)
  0000000000229080: 000000000767d175 (handler_entry_read_delegate<2, -2, 0, emu::device_delegate<unsigned int (address_space&, unsigned int, unsigned int)> >::read(unsigned int, unsigned int)+0x0025)
  00000000002290b0: 000000000774724a (handler_entry_read_dispatch<14, 2, -2, 0>:::read(unsigned int, unsigned int)+0x001a)
  00000000002290e0: 000000000779c8bb (handler_entry_read_dispatch<16, 2, -2, 0>::read(unsigned int, unsigned int)+0x001b)
  0000000000229110: 00000000074b26e1 (address_space_specific<2, -2, (endianness_t)0>::read_dword(unsigned int)+0x0021)
  00000000002292b0: 00000000048f5ae6 (mb86233_device::execute_run()+0x1ac6)
  0000000000229330: 00000000059a4e70 (device_scheduler::timeslice()+0x02f0)
-----------------------------------------------------

**Comment by galibert** [comment]
Ok, I think I know what's going on, lemme repro and fix.

  OG.

**Comment by Hydreigon223** [comment]
Someone explain how Taifoid got the "copro_atan_r" to show in his error log? All I did was run Mame64 only with verbose from the command line. Otherwise, the game straight up exits seemingly without a log.

**Comment by Tafoid** [comment]
You need to compile and produce a .SYM file - just like the mamedev.org integer produced binaries.
You can get such compile flags needed from [HERE](https://github.com/mamedev/build/blob/master/build-release.bat)

**Comment by cuavas** [comment]
You can also run with GDB attached and it'll use function names from the unwind tables.
