### ISSUE TITLE
make hng64.cpp error

### ISSUE THREAD

**Issue by zjwkof** [mamedev/mame#6096]
make SOURCES=src/mame/drivers/hng64.cpp PTR64=0 -j3

.........................................................................................................................

../../../../mingw-gcc/bin/x32/Release/mame_mame/libmame_mame.a(hng64.o):hng64.cpp
(.text+0x992): undefined reference to `hng64_state::reset_net()'

../../../../mingw-gcc/bin/x32/Release/mame_mame/libmame_mame.a(hng64.o):hng64.cpp
(.text+0x320b): undefined reference to `hng64_state::hng64_network(machine_config&)'

collect2.exe: error: ld returned 1 exit status
mame.make:270: recipe for target '../../../../../mame.exe' failed
make[2]: *** [../../../../../mame.exe] Error 1
makefile:100: recipe for target 'mame' failed
make[1]: *** [mame] Error 2
makefile:1101: recipe for target 'windows_x86' failed
make: *** [windows_x86] Error 2

**Comment by cuavas** [comment]
The stuff in separate files should be turned into proper devices, but you can just add the other hng64 files to your SOURCES= to include them in the build.

**Comment by Robbbert** [comment]
Nothing further heard, closing.
