### ISSUE TITLE
Motor Raid Twin weird graphics issue

### ISSUE THREAD

**Issue by BroKill** [mamedev/mame#6117]
First all, Happy New Year to all.
I have a problem running Motor Raid Twin in MAME, both standalone and RA core.
Sometimes ( often ) the graphic seems damaged, game doesn't render properly and it's impossible to play it especially in Junos circuit ( the snowed one ).
Later I will upload a video to show what I'm talking about.
My hw specs are :
i7 4790k
GTX 770 2gb
16 gb DDR3
Roms are stored on a SSD Samsung 1tb.

**Comment by BroKill** [comment]
Link for the video
https://www.dropbox.com/s/wjw5inuemu4tcga/motoraid-200101-135034.mkv?dl=0

**Comment by Tafoid** [comment]
Graphics and sound are known issues here.  Each time you start MAME you should see a warning screen cautioning you that both are "imperfectly emulated features".  I'm not sure what we can do here.

**Comment by cuavas** [comment]
Known issue.  There’s no point opening issues for systems with warnings.
