### ISSUE TITLE
pluginspath is getting lost in boot.lua

### ISSUE THREAD

**Issue by DanRoscigno** [mamedev/mame#6122]
MAME 0.216
Ubuntu 16.04 x86

I am trying to enable the hiscore plugin and seeing an error `function lfs.env_replace(str)`.  I am not a LUA dev, but it looks to me like the local var `str` needs to be declared.  After adding `local str = ""` I then have an error at `local json = require('json')`.  I had to hardcode `local dir` like so:
```
 -- local dir = lfs.env_replace(manager:options().entries.pluginspath:value())
 local dir = "/usr/share/games/mame/plugins"
```

After making this change I am able to see my highscores being saved.

I would be happy to document the proper ini file settings is someone wants to help me understand if I missed something in my configuration of MAME.

**Comment by cracyc** [comment]
You need to update your plugins.  That line was changed in the current version of boot.lua (https://github.com/mamedev/mame/commit/d4cb1ba742fecd3e2ba0610ec046b977ad4bd33d#diff-d4ef91b46fdc7a038b9f81c2fc8addc9).

**Comment by DanRoscigno** [comment]
Thanks @cracyc , using master gets me a little further, but then it fails when iterating over manager:plugins() at line 38 of boot.lua.  This is the error:

![IMG_20200102_184924](https://user-images.githubusercontent.com/25182304/71703990-bbb0c780-2da5-11ea-839a-20ccbaf6ed49.jpg)

Here is my command:
```
mame -v \
-homepath     /home/rastan/.mame \
-rompath      /home/rastan/mame/roms \
-inipath      /etc/mame \
-pluginspath  /usr/share/games/mame/plugins \
-skip_gameinfo \
-plugins \
-plugin hiscore \
puckman
```

If I change `-pluginspath  /usr/share/games/mame/plugins` to `-pluginspath  /usr/share/games/mame/plugins,foo` that error stops, but hiscores still do not get saved.

**Comment by DanRoscigno** [comment]
I am embarrassed, I had downgraded from Ubuntu 18.04 to 16.04 and did not notice that the default MAME package fro 16.04 is v .189.  I am installing GCC 7 now and will compile .217 and try again.

**Comment by DanRoscigno** [comment]
closing, I still had problems with the match on the line reading from hiscore.ini, but I see you have [updated line 49](https://github.com/mamedev/mame/commit/97642338756d08a9dc5817587d7bbd867e09df57#diff-a99166d582580737e120e8e05c32de2f) and this fixes my final issue also.  Thanks so much!!
