### ISSUE TITLE
megadriv.xml error

### ISSUE THREAD

**Issue by telanus** [mamedev/mame#6198]
The entry quacksht seems to have a cut and paste error. 

According to the dat it's 262144 big while on https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=1764 its 524288

**Comment by etabeta78** [comment]
This has been discussed several times: the ROM in the cart is
only 262144  large and it is just mapped in memory in a different way
compared to other MD cart.

MAME XML is correct (you can read more about it in the XML comment itself)

**Comment by telanus** [comment]
wouldn't the checksums then be different?

**Comment by p1pkin** [comment]
@telanus  you should learn MAME's ROM definitions / load features - there is 2 lines, 1st line tell to load 256Kbyte of file at offset 0, next line tell to load next 256 Kbyte at offset 0x100000. so, the total ROM file size if 512Kbyte.

is it clear now and issue can be closed ?

**Comment by telanus** [comment]
@p1pkin well at the moment the available rom from no-intro and the mame entry has the same crc and sha1

According to no-intro:

`<rom name="QuackShot Starring Donald Duck ~ QuackShot - I Love Donald Duck - Guruzia Ou no Hihou (World) (Rev A).md" size="524288" crc="5DD28DD7" md5="ADE4E47B0FBD329ACAF36EFC4F8D637D" sha1="CA02845FA49CD46CCB0A4023B91B10695573668E" status="verified"/>`

and according to MAME: 

`<rom name="mpr-14371-f.ic1" size="262144" crc="5dd28dd7" sha1="ca02845fa49cd46ccb0a4023b91b10695573668e"/>`

They both can't have the same crc & sha1 values if the sizes aren't the same, so if mame want to use an 262144 sized dump it needs to have the right crc/sha1 values, using the no-intro's crc/sha1 and not their size is pure ludicrous

**Comment by etabeta78** [comment]
Sorry, my bad. I mis-remembered the sizes probably adding to the confusion.

@telanus: if you check the XML you will see that the line you pasted is
followed by a line where the following 256K are loaded in a different part
of the emulated memory.
The file is still 512K, but it's just split in two lines of 262144.

As I stated before, the point has been already discussed several times both
on MAME boards and ClrMAME boards. Just search there and you will find more
explanation.

**Comment by p1pkin** [comment]
I repeat - it worth to learn a bit MAME's software list concepts.
this line `<rom name="mpr-14371-f.ic1" size="262144" crc="5dd28dd7" sha1="ca02845fa49cd46ccb0a4023b91b10695573668e"/>`
does NOT mean the whole file equal 256K, it just tell to load 256K of it at specific offset.
next line `<rom size="262144" offset="0x100000" loadflag="continue"/>`
tells load next 256K of this file.
basically, there might be number of lines with loadflag="continue" flags, and actual file size will be sum of sizes in each of these lines plus size in "<rom name" line.

**Comment by telanus** [comment]
@p1pkin I knew the software list concepts. Created three or four back in 2011-2012ish, and still listed as the last contributor on at least one of them.
