### ISSUE TITLE
[LUA] load_dat.lua attempt to index a function

### ISSUE THREAD

**Issue by telanus** [mamedev/mame#6199]
Getting this when running mame from the terminal:

`[LUA ERROR] in execute_function: plugins/data/load_dat.lua:39: attempt to index a function value (upvalue 'db')`

I'm on kubuntu 18.04.03 using mame git

**Comment by cracyc** [comment]
db should be the dbtable table from database.lua.  You sure database.lua isn't corrupt?

**Comment by telanus** [comment]
Thanx @cracyc that seems to have ben the problem
