### ISSUE TITLE
Model2 Disassembly Incorrect

### ISSUE THREAD

**Issue by cglmrfreeman** [mamedev/mame#6207]
Looking to disassemble how player models are loaded in House of the Dead, I found what I believe to be an error in the debug disassembly.

Specifically, at line `0x4DEB8` in the maincpu.

In hex, the raw data is as follows:
`94 39 80 90 D0 10 0C 00`

MAME shows this as the raw opcode:
`09803994 00C10D0`

The MAME disassembler shows the following:
`ld 		g0,0xc10d0[g4*3]`

IDA Pro dissassembles this instruction as:
`ld 		0xC10D0[g4*8], g0`

Using onlinedisassembler.com with the i960mc processor set gives us the following disassembly:
`ld 0x000c1d0[g4*8], g0`

I have come across similar behavior in debugging Dynamite Cop but I can't remember if it was 2A, 2B, or 2C, but I think the results would be the same across them.

I have no suggested fix but this seems like it could be a bug affecting multiple Model2 titles and could improve accuracy if fixed.

**Comment by angelosa** [comment]
That sounds like i960 CPU dasm going lvalue instead of rvalue. Page 6-1 (85) of the [manual](http://bitsavers.trailing-edge.com/components/intel/i960/271081-001_80960MC_Programmers_Reference_Manual_Jul88.pdf) states that rvalue is correct so MAME is at fault.

**Comment by p1pkin** [comment]
should be OK now. on a side note - actual emulation was not affected, it was only incorrect representation in disassembler.
