### ISSUE TITLE
Debugger unable to save/load "gfx" memory region

### ISSUE THREAD

**Issue by howprice** [mamedev/mame#621]
The integrated debugger save and load commands allow a CPU name to be passed as a parameter but don't allow a memory region name to be passed. So if for example a cps1 game is being debugged, the Memory Window can be used to view a list of address spaces (as shown in the drop-down):

M68000 ':maincpu' program space memory
Z80 ':audiocpu' program space memory
Z80 ':audiocpu' io space memory
OKI6295 ':oki' samples space memory
Region ':maincpu'
Region ':gfx'
Region ':audiocpu'
Region ':oki'
Region ':aboardplds'
etc

and the following commands succeed:

> save out.bin,0,100,":maincpu"
> save out.bin,0,100,":audiocpu"
> save out.bin,0,100,":oki"

but these commands fail:

> save out.bin,0,100,":gfx"
> Unable to find CPU ':gfx'
> save out.bin,0,100,"Region ':gfx'"
> Unable to find CPU 'Region ':gfx''
> save out.bin,0,100,":aboardplds"
> Unable to find CPU ':aboardplds'
> save out.bin,0,100,"Region ':aboardplds'"
> Unable to find CPU 'Region ':aboardplds''

**Comment by rb6502** [comment]
Right.  The idea is that memory regions load from ROMs, so there's no need to save them; they already exist in a file on your disk.  Do you have a use case where that's not valid?

**Comment by howprice** [comment]
The gfx memory region in cps1 game sf2hfj is composed by taking the roms in sets of 4 and interleaving them a word at a time.

```
	ROM_START( sf2hfj )
	ROM_REGION( CODE_SIZE, "maincpu", 0 )      /* 68000 code */
	ROM_LOAD16_WORD_SWAP( "s2tj_23.8f", 0x000000, 0x80000, CRC(ea73b4dc) SHA1(efbc73277d00bac86505755db35225e14ea25a36) )
	ROM_LOAD16_WORD_SWAP( "s2tj_22.7f", 0x080000, 0x80000, CRC(aea6e035) SHA1(ce5fe961b2c1c95d231d1235bfc03b47de489f2a) )   // == s2te_22.7f
	ROM_LOAD16_WORD_SWAP( "s2tj_21.6f", 0x100000, 0x80000, CRC(fd200288) SHA1(3817b67ab77c7b3d4a573a63f18671bea6905e26) )   // == s2te_21.6f

	ROM_REGION( 0x600000, "gfx", 0 )
	ROMX_LOAD( "s92_01.3a",  0x000000, 0x80000, CRC(03b0d852) SHA1(f370f25c96ad2b94f8c53d6b7139100285a25bef) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-1m.3a
	ROMX_LOAD( "s92_02.4a",  0x000002, 0x80000, CRC(840289ec) SHA1(2fb42a242f60ba7e74009b5a90eb26e035ba1e82) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-3m.5a
	ROMX_LOAD( "s92_03.5a",  0x000004, 0x80000, CRC(cdb5f027) SHA1(4c7d944fef200fdfcaf57758b901b5511188ed2e) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-2m.4a
	ROMX_LOAD( "s92_04.6a",  0x000006, 0x80000, CRC(e2799472) SHA1(27d3796429338d82a8de246a0ea06dd487a87768) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-4m.6a
	ROMX_LOAD( "s92_05.7a",  0x200000, 0x80000, CRC(ba8a2761) SHA1(4b696d66c51611e43522bed752654314e76d33b6) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-5m.7a
	ROMX_LOAD( "s92_06.8a",  0x200002, 0x80000, CRC(e584bfb5) SHA1(ebdf1f5e2638eed3a65dda82b1ed9151a355f4c9) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-7m.9a
	ROMX_LOAD( "s92_07.9a",  0x200004, 0x80000, CRC(21e3f87d) SHA1(4a4961bb68c3a1ce15f9d393d9c03ecb2466cc29) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-6m.8a
	ROMX_LOAD( "s92_08.10a", 0x200006, 0x80000, CRC(befc47df) SHA1(520390420da3a0271ba90b0a933e65143265e5cf) , ROM_GROUPWORD | ROM_SKIP(6) )    // == s92-8m.10a
	ROMX_LOAD( "s2t_10.3c",  0x400000, 0x80000, CRC(3c042686) SHA1(307e1ca8ad0b11f3265b7e5467ba4c90f90ec97f) , ROM_GROUPWORD | ROM_SKIP(6) )
	ROMX_LOAD( "s2t_11.4c",  0x400002, 0x80000, CRC(8b7e7183) SHA1(c8eaedfbddbf0b83311d2dbb9e19a1efef0dffa9) , ROM_GROUPWORD | ROM_SKIP(6) )
	ROMX_LOAD( "s2t_12.5c",  0x400004, 0x80000, CRC(293c888c) SHA1(5992ea9aa90fdd8b9dacca9d2a1fdaf25ac2cb65) , ROM_GROUPWORD | ROM_SKIP(6) )
	ROMX_LOAD( "s2t_13.6c",  0x400006, 0x80000, CRC(842b35a4) SHA1(35864a140a0c8d76501e69b2e01bc4ad76f27909) , ROM_GROUPWORD | ROM_SKIP(6) )
```

**Comment by ajrhacker** [comment]
The debugger also lacks save/load/dump commands for the decrypted opcode space, though this seems like a minor oversight.

**Comment by yz70s** [comment]
This could be solved easily by adding a new debugger command
saver start address, size, "region tag"
dedicated to save data from regions

**Comment by Osso13** [comment]
the option was added in https://github.com/mamedev/mame/pull/6837

**Comment by howprice** [comment]
Excellent. Many thanks.
