### ISSUE TITLE
[Sega-System1] Dipswitch issue for nprinceso

### ISSUE THREAD

**Issue by wwark** [mamedev/mame#6217]
Hi,

The dips switch for nprinceso is not ok for example "demo sound on/off" the demo sound is present for each value.
It uses the same dips switch of the parent rom.
I didn't test other clones.
I don't have also the information related to the dip switch of the game nprinceso

Thanks for the fix,
Wwark

**Comment by Osso13** [comment]
To me it seems to work as intended: with the dip on you can here the music as the title scrolls, while with it off there's no music.
Though it can be confusing, since it doesn't affect sound effects during attract mode.

**Comment by wwark** [comment]
ok I understand and thanks for the check.
I close this ticket.
