### ISSUE TITLE
A whole bunch of undefined references

### ISSUE THREAD

**Issue by Sterophonick** [mamedev/mame#6223]
When compiling mame, there are a whole bunch of undefined reference errors.
Windows x64

Log:
https://pastebin.com/tgjTYekm

**Comment by Tafoid** [comment]
It looks like some stuff didn't properly compile.  This sometimes happens on Windows platforms.  Try reissuing the same MAKE command you used and see if it reaches "Linking mame64.exe..."  If that fails as well, empty your BUILD folder and "make clean" before trying again.

You may want to monitor your compile as the errors will show in real time as it compiles if something fails.  If you cannot, capture the compile output to a file.

Please note that full build Windows 64 builds will take an hour or more to link, even on decent machines.

**Comment by Tafoid** [comment]
I do see at least m72.cpp didn't finish correctly - so make sure that isn't a 0 sized file (or any others).

**Comment by Sterophonick** [comment]
This was done from a clean compile, and m72.cpp is 231 KB.

Oh, and I did make -j8 to speed things up. Does that hurt anything?

**Comment by Sterophonick** [comment]
Oh, I got it working.
