### ISSUE TITLE
Building MAME with Visual Studio 2015

### ISSUE THREAD

**Issue by howprice** [mamedev/mame#624]
I'd like to contribute to MAME using Visual Studio 2015 as IDE. When I heard that the project had moved to use GENie I imagined the build process would be something like:

```
$ git clone https://github.com/mamedev/mame/
$ 3rdParty\bin\windows\genie.exe vs2015
<open .sln, and hit F5>
```

Before I get stuck in I'd like to confirm that the actual process as described on these pages is up to date:

http://mamedev.org/tools/
http://wiki.mamedev.org/index.php?title=Building_MAME_using_Microsoft_Visual_Studio_compilers

Thanks

**Comment by mmicko** [comment]
There is still part of build require you to have mingw compiler installed.
Promise to try to resolve this.

And yes we suck at documentation maintenance :)

**Comment by rb6502** [comment]
The actual setup described there is not exactly correct, you have to include something like "msvc" at the end of the commnand line to generate an MSVC solution file.  The build system is badly under-documented; end user documentation is nearing good shape thanks to Firehawke's efforts.

**Comment by howprice** [comment]
Thanks for the quick response.

> And yes we suck at documentation maintenance :)

Does this mean that the existing docs are still valid, or is there anything I should be aware of? (or any steps that can be skipped?)

**Comment by howprice** [comment]
If any VS users could give me a quick ABC of how to generate a solution file that can be used to build mame.exe I'd be extremely grateful.

**Comment by mmicko** [comment]
Docs are not valid

Command line would be:

make vs2015

But it require you to have our official tools that include mingw and Python.
Since they are needed to compile. And put your Python root in PATH

**Comment by rb6502** [comment]
There we go.  "make vs2015" and then load the .sln into MSVC2015.

Note that MSVC is not an official compiler, so you must ensure any changes you plan to submit compile and operate correctly with MinGW.

**Comment by yz70s** [comment]
You do not need to add the python folder in the path.
If the mame build tools have been installed in c:\buildtools , as an example, you can use

make vs2015 PYTHON_EXECUTABLE=c:/buildtools/usr/bin/python.exe

And if you want to build an executable with only a single driver, use (substitute drivername with the name of the driver)

make vs2015 SUBTARGET=drivername SOURCES=src\\mame\\drivers\\drivername.cpp PYTHON_EXECUTABLE=c:/buildtools/usr/bin/python.exe

**Comment by howprice** [comment]
I've fallen at the first hurdle. I already had Git (for Desktop) installed. So installed `msys64-2016-01-07.exe`. Opened `c:\msys64\win32env.bat` and entered `git config --global core.autocrlf true` which returns `error: could not lock config file /home/Howard/.gitconfig: No such file or directory`

My existing .gitconfig file resides at `C:\Users\Howard\.gitconfig` Is there some msys specific git setup required?

**Comment by yz70s** [comment]
Mame build environment has its own copy of git installed (so you cannot use your installation of git for windows from a bash command prompt started by win32env.bat)
In your case the /home/Howard directory is actually c:\msys64\home\Howard

**Comment by howprice** [comment]
c:\msys64\home\Howard doesn't exist. Do I need to create this manually, or add user somehow?

**Comment by howprice** [comment]
I'm now debugging MAME with Visual Studio 2015. Many thanks for the help.

Do you want me to update the pages at:
http://wiki.mamedev.org/index.php/Building_MAME_using_Microsoft_Visual_Studio_compilers
http://mamedev.org/tools/

or should I leave that to the core team?

**Comment by mmicko** [comment]
Working on a change to make mame deps also pacman packages from our own repo

It should be done during today, will update tools page then

**Comment by howprice** [comment]
I just installed the tools on another machine. However this time when I ran win32env.bat for the first time the console said

```
Copying skeleton files.
These files are for the users to personalise their msys2 experience.

They will never be overwritten nor automatically updated.

'./.bashrc' -> '/home/Howard//.bashrc'
'./.bash_logout' -> '/home/Howard//.bash_logout'
'./.bash_profile' -> '/home/Howard//.bash_profile'
'./.inputrc' -> '/home/Howard//.inputrc'
'./.profile' -> '/home/Howard//.profile'
'./.vimrc' -> '/home/Howard//.vimrc'

[MINGW64] C:\msys64\src>
```

This didn't happen the first time round which complicated the process because there was no home directory which meant that git config failed.

**Comment by mmicko** [comment]
Right, your feedback was one of the reasons to fix this :)
Idea is always to keep things simple for users

**Comment by howprice** [comment]
> And if you want to build an executable with only a single driver, use (substitute drivername with the name of the driver)
make vs2015 SUBTARGET=drivername SOURCES=src\\mame\\drivers\\drivername.cpp PYTHON_EXECUTABLE=c:/buildtools/usr/bin/python.exe

That's a great tip. Thanks.

**Comment by ocornut** [comment]
May I suggest updating the Wiki page above?
I got stuck on this for a while following the Wiki instruction.

**Comment by mmicko** [comment]
Updated wiki page, there is also info on main README.md

**Comment by ocornut** [comment]
Thanks a lot! Yeah it's my fault for just relying on Google "mame visual studio" and for some reason it didn't occur to me to read the main github readme. 
(I am amazed that you are managing to keep such a big project building at all !)
