### ISSUE TITLE
Download Mirror

### ISSUE THREAD

**Issue by inukaze** [mamedev/mame#6241]
Hi there i am trying to download two versions of mame for i want try to compile under Slackware 14.2 (32 Bits version & 64 Bits version, yes i had two installed)

`wget -O "mame-mame0187.tar.gz" -c https://codeload.github.com/mamedev/mame/tar.gz/mame0187`

i want to try with '0187' becuase in SlackBuild the QMC2 is version 0.187 and in before occations with version too high in comparation of QMC2 that software don't work fine neither detect mame is the version be superior.

`wget -O "mame-mame0214.tar.gz" -c "https://codeload.github.com/mamedev/mame/tar.gz/mame0214" `

Well the thing is in "**Longitude**" ever says "**Not specify**" or something like that, i am from venezuela and my internet connection is slow, and i can't resume some of this download, when i try to resume, the download start from the begining

i had try today with "mame0217" but under slackware the gcc is 5.5.0 and this latest version needs gcc 7.0 or superior. 

On some site of internet you had mirror i can use to download and resume the download of the archives of mame ? Thanks for readme

**Comment by cuavas** [comment]
The gzipped tarball and zip archive generated by GitHub are generally slow and unreliable to download.  Try downloading the self-extracting 7zip archive (mame0214s.exe) and extracting it with the 7za tool from [p7zip](http://p7zip.sourceforge.net/).  Releases are available from both GitHub (via Amazon CDN) and SourceForge (via their mirror network):
* https://github.com/mamedev/mame/releases/mame0214/
* https://sourceforge.net/projects/mame/files/mame/0.214/

**Comment by stilett0** [comment]
Or in the case of the requested MAME 0.187:

- https://github.com/mamedev/mame/releases/mame0187/
- https://sourceforge.net/projects/mame/files/mame/0.187/

There's also some unofficial mirrors out there like ProgettoSNAPS:
- http://www.progettosnaps.net/MAME/src/mame0187s.zip

**Comment by inukaze** [comment]
Thank you very much.
