### ISSUE TITLE
How compile under Slackware64 14.2?

### ISSUE THREAD

**Issue by inukaze** [mamedev/mame#6251]
Hi there look with both versions of mame 0187 & 0214 when i try to compile, after hours (near 8 hours of compilation). show me this error : 

```
ps2vif1.cpp:(.text._ZN3emu6detail21device_type_impl_base13create_deviceI15ps2_vif1_deviceEESt10unique_ptrI8device_tSt14default_deleteIS5_EERKS1_RK14machine_configPKcPS5_j[_ZN3emu6detail21device_type_impl_base13create_deviceI15ps2_vif1_deviceEESt10unique_ptrI8device_tSt14default_deleteIS5_EERKS1_RK14machine_configPKcPS5_j]+0xb7): referencia a `vtable for device_finder<ps2_gs_device, true>' sin definir
../../../../linux_gcc/bin/x64/Release/mame_arcade/liboptional.a(ie15.o): En la función `ie15_device::device_reset()':
ie15.cpp:(.text+0x553): referencia a `beep_device::set_state(int)' sin definir
../../../../linux_gcc/bin/x64/Release/mame_arcade/liboptional.a(ie15.o): En la función `ie15_device::ie15_device(machine_config const&, emu::detail::device_type_impl_base const&, char const*, device_t*, unsigned int)':
ie15.cpp:(.text+0x1cbc): referencia a `vtable for device_finder<beep_device, true>' sin definir
../../../../linux_gcc/bin/x64/Release/mame_arcade/liboptional.a(ie15.o): En la función `ie15_device::beep_w(address_space&, unsigned int, unsigned char, unsigned char)':
ie15.cpp:(.text+0x2724): referencia a `beep_device::set_state(int)' sin definir
../../../../linux_gcc/bin/x64/Release/mame_arcade/liboptional.a(ie15.o): En la función `ie15_device::ie15core(machine_config&)':
ie15.cpp:(.text+0x34fe): referencia a `beep_device::beep_device(machine_config const&, char const*, device_t*, unsigned int)' sin definir
../../../../linux_gcc/bin/x64/Release/mame_arcade/liboptional.a(ie15.o): En la función `ie15_device::ie15_beepoff(void*, int)':
ie15.cpp:(.text+0x3ca): referencia a `beep_device::set_state(int)' sin definir
collect2: error: ld devolvió el estado de salida 1
mamearcade.make:250: fallo en las instrucciones para el objetivo '../../../../../mamearcade64'
make[2]: *** [../../../../../mamearcade64] Error 1
Makefile:409: fallo en las instrucciones para el objetivo 'mamearcade'
make[1]: *** [mamearcade] Error 2
makefile:1290: fallo en las instrucciones para el objetivo 'linux_x64'
make: *** [linux_x64] Error 2

```

Well i don't know how compile without errors i use the follow command to make it : 
`make DEPRECATED=0 OPTIMIZE=3 PTR64=1 TOOLS=1 NOWERROR=1 SUBTARGET=arcade`

During compilation, i got the follow dunno : 
if i just want to compile the tools without emulator, which is the option i should use for that?

Because i need is chdman and <<Qt Chdman Gui>> and well in some point is probably i need another mame-tool. 

Well right now which information you need for i can compile the emulator ?

**Comment by cuavas** [comment]
The `mess` and `arcade` subtargets are not officially supported and are not guaranteed to build or work.  You will need to either do a full build, or adjust the build scripts yourself so the subtarget builds.

Also, we don’t support anything but the latest.  If you want to use an older release, you'll need to support it yourself.  Also, this isn't a general help forum.  These kinds of discussions are better suited to a community forum, reddit or IRC.

**Comment by inukaze** [comment]
the latest version need GCC 7.0 and Slackware had GCC 5.5.0 and i don't upgrade it if the Slackpkg don't update it. and becuase of that i need use and older version compatible with the GCC of this distro.
