### ISSUE TITLE
Improve Debugger documentation for how to invoke

### ISSUE THREAD

**Issue by roughana** [mamedev/mame#6265]
Current documentation discusses the commands but does not provide information on how to enter the debugger.

Need to add coverage of using -debug option to invoke the debugger.

Perhaps on this page
https://docs.mamedev.org/debugger/index.html

**Comment by p1pkin** [comment]
it seems current documentation provide enough information about emulator's debug options
https://docs.mamedev.org/commandline/commandline-index.html#core-debugging-options

**Comment by roughana** [comment]
Wow. How user unfriendly. 

The reason why I raised the ticket is so that a person who searches for "debugger" finds the answer quickly. This first page of results is not helpful:
https://docs.mamedev.org/search.html?q=debugger&check_keywords=yes&area=default
I had to search outside of the site to find the answer.

**Comment by rb6502** [comment]
This is definitely an issue.  I know our documentation guy is currently RMAing his motherboard so there will be a delay on addressing it.

**Comment by stilett0** [comment]
> This is definitely an issue. I know our documentation guy is currently RMAing his motherboard so there will be a delay on addressing it. I updated the source page on Github but I have no idea how to publish the changes to the live site.

It's automagic! See: https://docs.mamedev.org/debugger/index.html

**Comment by rb6502** [comment]
Thanks Stiletto!  

@roughana does that change to the debugger's section index work for you?

**Comment by roughana** [comment]
Yes. Great. Would’ve saved me time if it was there when I went looking.

Thanks
