### ISSUE TITLE
Built-in GUI shows all clones as unavailable if ROM is merged

### ISSUE THREAD

**Issue by elisimpson** [mamedev/mame#6266]
With a merged ROM all clones show in the "Unavailable" list, with only the parent available. Even though MAME built-in GUI sees them as unavailable, they are playable, if selected.

If I split the ROMs into separate files they show up properly in the "Available" list.

**Comment by Tafoid** [comment]
It is possible that doing a -verifyroms audit your unavailble (F1) will take the time to deep audit your romsets and correct this for you.  The front-end assumes split romsets in quick startup checks and assumes you use a proper rom manager (clrmamepro, romcenter, etc).

**Comment by elisimpson** [comment]
My romsets are all verified good with Rom Center.

It'd be nice if the GUI could look inside the parent rom to see if the clones are there, but I understand if this is considered too slow.

Seems like merged ROMs might not be the best idea if you're using the internal GUI.

**Comment by Tafoid** [comment]
Like I said, try using F1 at the UI Game Select screen and force audit your romsets within the UI.
I tested on machines which didn't require romsets (at least) and it placed them as available for me.  If you are dealing with full sets, it may take a while but at least you'll have your romsets showing up.  Also, if you are one to try to keep a full romsets, available is likely irrelevant and you can select "Unfiltered" to show everything.

**Comment by elisimpson** [comment]
Okay I'll try that. It seems like maybe it doesn't work with software lists though, only the main roms?

**Comment by Tafoid** [comment]
The F1 audit stuff is for machine romsets only.  AFAIK there is no facility for showing only softlist items based on any audit and will simply show you all that is possible to use, again assuming you have scanned externally.   There is a command line -verifysoftlists which will do that, but no hook in the program to do it, take the data and allow you to show only what was found.

**Comment by cuavas** [comment]
It works as intended – the default check just shwos presence/absence of files, and the audit looks at the contents of archives.
