### ISSUE TITLE
mamedev.org 403 forbidden for me

### ISSUE THREAD

**Issue by Agijnnuwy** [mamedev/mame#627]
Not sure if it is the right place to ask. But it seems that I am not able to go to the official page of mamedev. the following information appears:

403 Forbidden

You don't have permission to access / on this server.
Apache/2.4.7 (Ubuntu) Server at mamedev.org Port 80

Any ideas on how might i solve the problem?

**Comment by mr-t-guru** [comment]
mamedev.org works fine. if there is a problem it's at your end.

**Comment by balr0g** [comment]
@Agijnnuwy, what browser are you using? Does using a different browser make a difference?

**Comment by Agijnnuwy** [comment]
Don't know. the system is Debian the desktop environment is mate. the browser is iceweasel

**Comment by cuavas** [comment]
It's likely IP range blocking - mamedev.org blocks large ranges of IP addresses because of supposed malware. This probably blocks 1/4 world population.

**Comment by Agijnnuwy** [comment]
@cuavas Does it block Chinese address?

**Comment by cuavas** [comment]
It blocks most Chinese IP address ranges with a few exceptions.

**Comment by Agijnnuwy** [comment]
... I see. no luck for me then...

**Comment by mr-t-guru** [comment]
use a VPN. there are free programs out there. ViperVPN is a good one. there are MANY others.
Or use TOR browser which has VPN built-in.
