### ISSUE TITLE
C++20 forbids inserting inappropriate character types into standard streams

### ISSUE THREAD

**Issue by CaseyCarter** [mamedev/mame#6275]
The C++20 draft standard incorporates a change to help avoid confusion when inserting inappropriate character types to iostreams. In previous C++ versions, insertion of inappropriate character types into output streams (e.g., `wchar_t`/`char16_t`/`char32_t` into `std::cout`) doesn't result in transcoding of the character, but instead outputs a representation of its integral value. Insertion of pointers to such character types also does not transcode but outputs the value of the pointer. C++20 will add deleted stream insertion operators so that the expression `os << x` will instead be ill-formed when `os` is a `std::ostream` (a narrow character stream) and `x` is a `wchar_t`/`char16_t`/`char32_t` or pointer to such.

We're implementing these changes right now in MSVC, and our automated tests show that your product (or its tests) will fail to compile with these changes in `/std:c++latest` mode unless the "escape hatch" macro `_HAS_STREAM_INSERTION_OPERATORS_DELETED_IN_CXX20` is defined. Specifically, https://github.com/mamedev/mame/blob/mame218/src/lib/util/strformat.h#L771 seems to be inserting a `char32_t` into a `std::ostream`.

**Comment by cuavas** [comment]
That particular line isn't supposed to result in the character being transcoded, it’s supposed to treat it as an unsigned integer and print it as hex.  I’ll change it to special-case other character types.

**Comment by cuavas** [comment]
This should be addressed as of fead8792cc7efc5a003220c728b66986822cb1c2 – that makes the integer formatting code considerably more paranoid.

**Comment by angelosa** [comment]
@cuavas safe to close this one?

**Comment by cuavas** [comment]
Just tested it with GNU libstdc++ 10 in C+20 mode, and it’s still an issue.  I’m having trouble working around it, my inference test isn't working.

**Comment by cuavas** [comment]
Addressed in d1e68f25dd9ce56c623cfdd96425bad0fa35dcdb.
