### ISSUE TITLE
Incorrect environment handling in Lua plugins

### ISSUE THREAD

**Issue by grcancelliere** [mamedev/mame#6283]
I wanted to change the location of `history.db` from the `data` Lua plugin, but the file could not be written. After some research I've found out that with this configuration

```
...
historypath               $XDG_CACHE_HOME/mame/history;history;dats;.
...
```

The variable [`dbpath`](https://github.com/mamedev/mame/blob/master/plugins/data/database.lua#L12) would be incorrectly set to `XDG_CACHE_HOME/mame/history`. This happens because the `%w` character class in the regexes ([Linux/OSX](https://github.com/mamedev/mame/blob/master/plugins/boot.lua#L19) and [Windows](https://github.com/mamedev/mame/blob/master/plugins/boot.lua#L17)) of the helper function `lfs.env_replace` doesn't include the `_` ([lua pattern reference](https://www.lua.org/manual/5.3/manual.html#6.4.1)). If the `%w` is replaced with `[%w_]` the path is correctly resolved.

**Comment by cracyc** [comment]
made the change in https://github.com/mamedev/mame/commit/a0a658a11148f3dac497d24a3eb16460df9b69c0
