### ISSUE TITLE
pstring.h should include ostream

### ISSUE THREAD

**Issue by StephanTLavavej** [mamedev/mame#6293]
`pstring.h` uses `std::basic_ostream` without including the `<ostream>` header:

https://github.com/mamedev/mame/blob/e0183b56e77f3ecd710602f68c05c1282459a485/src/lib/netlist/plib/pstring.h#L13-L18
https://github.com/mamedev/mame/blob/e0183b56e77f3ecd710602f68c05c1282459a485/src/lib/netlist/plib/pstring.h#L201-L205

This is a conformance issue - the code may fail to compile depending on how the platform's C++ Standard Library has been implemented. (According to https://eel.is/c++draft/res.on.headers#1 , Standard Library headers include one another in unspecified ways, so assuming that `<string>` includes `<ostream>` is non-portable.)

The Visual C++ team regularly builds MAME in our "Real World Code" test suite in order to prevent compiler/library regressions from shipping and affecting you. This test coverage also allows us to provide advance notice of conformance issues and source-breaking changes like this one. Here, I believe we've encountered a compiler error because we recently merged https://github.com/microsoft/STL/pull/355 , breaking header inclusion assumptions like this one. ~~I'm not 100% sure about the chain of events because our internal logs are referring to the VS 2017 toolset, but~~ (edit: that was a red herring caused by Microsoft-internal infrastructure) the merged change affects upcoming versions of VS 2019. In any event, the issue in `pstring.h` seems to be clear-cut and the fix is simple and non-risky.

**Comment by couriersud** [comment]
Thanks a lot! I will fix this.

**Comment by couriersud** [comment]
added ostream to pstring includes.
