### ISSUE TITLE
mame-0.218: -listxml broken

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#6294]
In mame-0.218, `-listxml` is not working for me:
````
# mame -listxml
No matching machines found for 'soft'
````

**Comment by Tafoid** [comment]
At least using official 0.218 from mamedev.org, -listxml works as it should.  The only way I could duplicate your output is actually attempting look up -listxml information for a machine called 'soft'.

> F:\OLDER_MAME>mame64_218 -listxml soft
> No matching machines found for 'soft'

So, check your launcher/front-end and/or mame.ini or any .cfg settings for an errant setting.
Best way to test is to install a fresh copy of MAME in a new folder and try that.  You fail to ID your OS - so cannot help much further.

**Comment by 0-wiz-0** [comment]
Sorry, local problem, I had a broken shell alias.
