### ISSUE TITLE
gbcolor: RTC in pokegold*/pokecrys*/pokesilv* not emulated

### ISSUE THREAD

**Issue by rootfather** [mamedev/mame#630]
As you might now, the 2nd generation Pokémon games for the Gameboy Color feature a battery backed real-time clock in their modules. This allows features like day and night time or timed events (e.g. some of the ingame radio shows only appear on certain hours).

This RTC is not emulated in current revisions of MAME. The RTC is always stuck at the time set when playing the game first, no matter how often you save or how long the game plays, it's always the same.

Normally, when the battery for the RTC in the cart died, the game recognizes this and allows to set the time after each power-cycle of the Gameboy. This is not the case for the gbcolor and the gameboy driver in MAME, the time is always stuck, as I said previously.

Are there any plans to implement either a working battery backed RTC for these games or at least emulate a dead RTC so the time can be set? Would be a cool improvement if you ask me.

Best regards
rootfather

**Comment by rb6502** [comment]
From the source:
"TODO: add proper RTC and Rumble support"

So it is a known/planned thing although I don't think eta is working on it right now.

**Comment by rootfather** [comment]
Great to hear :)

**Comment by rootfather** [comment]
@etabeta78, any plans regarding this for the nearer future? :)

**Comment by rb6502** [comment]
This has been solved as far as implementation.  I'll close it when the next release comes out :-)

**Comment by rootfather** [comment]
Thanks again @etabeta78 for the implementation!

**Comment by BPzeBanshee** [comment]
Great stuff @etabeta78 ! That just leaves the distorted graphics when stats are raised/lowered in battle and Pokemon fans can find it fully working in MAME!

**Comment by wilbertpol** [comment]
The distorted graphics might be fixed when I'm done with some changes that I'm working on for the gameboy drivers.

**Comment by rootfather** [comment]
A perfect experience of the 1st/2nd Pokemon generation games in MAME would be really awesome. @wilbertpol, I'm really looking forward to your changes!
