### ISSUE TITLE
Apple II family: HGR monochrome with bit 7 set has incorrect pixel horizontal shifts that cause HLSL's NTSC shader to produce wrong colors.

### ISSUE THREAD

**Issue by colinhowell** [mamedev/mame#6308]
On the Apple II family, I checked standard hires graphics on an emulated monochrome display, similar to what SoltanGris42 did [in a posting made back in 2015](https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=99830). At that time he noted that setting the most significant bit of a hires display byte did not horizontally shift its pixels by a half-pixel, as it does on real Apple II hardware to generate the NTSC colors orange and blue. @rb6502 very recently attempted to fix this (b4bc924018e7120e495fb5a03af85bd9de7f978a), but the fix has problems. The shift is in the wrong direction, so the NTSC colors are reversed, "orange" showing up as blue and vice versa. Furthermore, pixels in the leftmost updated 7-pixel column (which is normally the screen's leftmost column, unless only part of the screen is modified) aren't offset at all, due to an off-by-1 indexing error. For these pixels in the NTSC shader, "orange" shows up as green and "blue" as purple.

The following Applesoft BASIC command line will show the problem:

`HGR:HCOLOR=5:FOR X=70 TO 83:HPLOT X,0 TO X,159:NEXT`

(You can change the range of X values; I chose to start at 70 to show that the color anomaly for the leftmost pixels can happen elsewhere, not just on the screen's left edge.)

On an emulated color display, this shows a broad orange band, as it should. On an emulated monochrome display, it shows 7 vertical lines separated by gaps of the same width, except for a thinner (half-pixel) gap between the third and fourth lines. With the HLSL NTSC color shader activated and set properly for Apple II graphics, it again appears as a broad band, but the band is green on the left and blue on the right.

(Edit: forgot to mention the settings I used for the NTSC color shader. They are similar to those SoltanGris42 used: NTSC A Value = 0.0, NTSC B Value = 0.0, and NTSC Scanline Duration (uSec) = 39.1. These are enough to give output similar to an Apple II color display.)

The problem is in a2_video_device::hgr_update(), which has code like the following for monochrome displays (mon_type != 0):

                                case 1:
                                        w >>= 7;
                                        if (vram_row[col] & 0x80)
                                        {
                                                p--;
                                        }
                                        for (b = 0; b < 7; b++)
                                        {
                                                v = (w & 1);
                                                w >>= 1;
                                                *(p++) = v ? WHITE : BLACK;
                                                *(p++) = v ? WHITE : BLACK;
                                        }
                                        if (vram_row[col] & 0x80)
                                        {
                                                p++;
                                        }
                                        break;

The check of each column's most significant bit, "if (vram_row[col] & 0x80) ..." is off by one column from the way the array vram_row[] is set up; "col" should be "col+1". Also, the corresponding pixel shift goes in the wrong direction. On Apple II hardware, setting a hires display byte's most significant bit shifts the byte's visible display bits *right* by half a pixel, by delaying the video PICTURE signal's output by one 14 MHz cycle. To get the correct shift direction, the bracketing "p--;" and "p++;" statements should be swapped. These changes should be made for all three monochrome cases.

Note that this means that orange pixels in the extreme right-hand position (X = 279) will be shifted off the screen's right edge by a half-pixel, so they will only be half a pixel wide and their color will be brown instead of orange. This happens on the real hardware, because the horizontal blanking of the video signal is never delayed.

Problem: my proposed fix would write off the displayed right edge of the bitmap by one bitmap pixel, and I'm not sure whether this is safe. I don't know how MAME's Apple II driver allocates its display bitmap and whether I need to do bounds checking, or whether such a write would be safely clipped, though I would assume not. Didn't cause an obvious problem when I tried it, but that doesn't really tell you anything.

I suppose that the case of an emulated color display (mon_type==0) should really have a shift as well, because even though a color display's resolution wouldn't be as sharp, you should still be able to see the horizontal shift between, say, a vertical line of green pixels and the same line of orange pixels. The horizontal positioning isn't completely filtered out.

Another complication for perfectly accurate emulation is that, if I understand correctly, on the IIe and later models, this pixel half-shift for hires display bytes with the most significant bit set will be disabled if the video output delay is turned off with soft switch $C05E. The normal state is to have this delay on in hi-res mode; the delay can be turned on explicitly with soft switch $C05F. Toggling these soft switches can make orange and blue colors on the hi-res display flash to green and purple (or make their pixels "jitter" on a monochrome monitor).

**Comment by rb6502** [comment]
Is it possible to make this work with the BGFX version of the CRT shader?  I develop on MacOS so I'm completely blind to what my changes do in the setup you've described.

(For BGFX, use -video bgfx, bring up the MAME slider controls, and turn the screen effect to "HLSL", which will cause all of the other sliders to appear).

**Comment by colinhowell** [comment]
Yes, in fact I have a MacOS system as well, and setting the screen effect to HLSL is exactly how I've been checking the NTSC shader. In my case I've also had to specify "-bgfx_backend opengl" when testing potential fixes to the driver, because otherwise bgfx just doesn't work for some reason—my guess is because it's picking an alternate backend which doesn't work on my system. (I'm still running Sierra, 10.12.6.)

**Comment by rb6502** [comment]
Great!  What other settings are you putting the sliders at to get proper Apple II color?

**Comment by colinhowell** [comment]
Effect = "hlsl"
Enable NTSC = On
NTSC A Value = 0.0
NTSC B Value = 0.0
NTSC Scanline Duration (uSec) = 39.1

Everything else I've been leaving at the defaults. 

(Technically, the resulting NTSC colors are ideal. According to the "Calculating RGB Values" tab of the [Apple II Video Display Theory spreadsheet](https://docs.google.com/spreadsheets/d/1rKR6A_bVniSCtIP_rrv8QLWJdj4h6jEU1jJj0AebWwg/) you referenced in the recent palette-fix commit (017b53b2f58fa3c1b3e0b74d23f248892256dad5), and a couple other references ([here](https://mrob.com/pub/xapple2/colors.html) and [here](https://www.kreativekorp.com/miscpages/a2info/munafo.shtml)), the phase of the Apple II's NTSC colors is reportedly off by pi/15 radians (12 degrees) from the ideal values. But that minor difference doesn't matter for the purpose of this bug; actual Apple IIs had a "COLOR TRIM" adjustment to set the color phase, and of course the monitor would have a tint control.)

**Comment by rb6502** [comment]
Perfect, thanks!  With a working NTSC display I can fix this properly now.

**Comment by colinhowell** [comment]
Just so you know, I actually have similar bugs to report for standard lores, double lores, and double hires modes, all related to relative pixel/dot positioning and the resulting NTSC color. I didn't want to make this bug report too long by putting them all in one bug, and I figured this standard hires bug was the best one to start with.

**Comment by rb6502** [comment]
(Double) lores is just a matter of understanding how those map to the character generator ROM; the patterns were all programmed in by Woz and those modes should be drawn the same way as text mode, just from a different area of the ROM.

**Comment by rb6502** [comment]
And never mind any of that, The Apple II Circuit Description says that's not how it works :)

**Comment by colinhowell** [comment]
Heh.

I've also found Jim Sather's books, _Understanding the Apple II_ and _Understanding the Apple IIe_, particularly helpful, especially the latter for the double-resolution modes.

**Comment by rb6502** [comment]
Change fe2a7d760763f2591a10a4b2ec38c8b035caad96 gives improved results for hires, lores, and double-lores (COLOR DEMOSOFT looks good with the shader-generated NTSC color now).  I'm not clear what's going on with double-hires yet, I'll check the Sather book.

**Comment by rb6502** [comment]
31141db finally fixes double-hires as well, so all modes should work properly with shader-generated NTSC color.

**Comment by benrg** [comment]
I think this should be reopened as the new logic is still broken. If you do `HGR: POKE 8192,127: POKE 8193,255`, you get 14-pixel and 13-pixel white stripes with 1 black pixel between them, while on real hardware I think you should get a 28-pixel white stripe.

More suspiciously, if you follow it with `POKE 8193,127: POKE 8193,255`, you now see a 28-pixel stripe even though the contents of the video RAM are the same as before. The code fails to update one pixel at each 0-to-1 high bit transition.

I think the correct logic is:

* If the high bit is 0, emit bits 0,1,2,3,4,5,6 twice each
* If the high bit is 1, emit latched bit 6 of the previous byte (or a zero bit at the beginning of the line) once, then bits 0,1,2,3,4,5 twice each, then bit 6 once
