### ISSUE TITLE
Disassembler for the Jaguar not displaying the movei instruction correctly.

### ISSUE THREAD

**Issue by ElectronAsh** [mamedev/mame#6314]
Originally, this value would have been shown as something like "movei $f1d3a0"...

![unknown (4)](https://user-images.githubusercontent.com/24658385/74599895-43664300-5081-11ea-9b10-f3ff0f69710f.png)

So I changed line 130 in jagdasm.cpp to this...
```cpp
case 38:    util::stream_format(stream, "movei   $%x%x,r%d", opcodes.r16(pc+2),opcodes.r16(pc), reg2); size = 6; break;
```

And it seemed to fix the problem.
I haven't spotted any other issues yet, and the jump instructions look OK.

https://github.com/mamedev/mame/blob/88af85e0da543183a6de97dca55f88f84d4a7dd0/src/devices/cpu/jaguar/jagdasm.cpp#L130

**Comment by smf-** [comment]
fixed https://github.com/mamedev/mame/commit/bfb182b56c4c99f223bf0b20fb5dcf3756bcc8df
