### ISSUE TITLE
[patch] vtvideo add back pixel stretching feature

### ISSUE THREAD

**Issue by hodefoting** [mamedev/mame#6319]
See attached patch for improvement, I permit use of any OSI approved license for this change.

[0001-vtvideo.cpp-Implement-pixel-stretching-of-characters.patch.txt](https://github.com/mamedev/mame/files/4215192/0001-vtvideo.cpp-Implement-pixel-stretching-of-characters.patch.txt)

**Comment by felipesanches** [comment]
Hey, Pippin! Nice to see you around here :-D

I may be wrong, but I think that the mamedev team would prefer to receive a pull request instead of a patch file.

**Comment by hodefoting** [comment]
@felipesanches  The instructions on mamedev.org ask for diffs sent to code@mamedev.org - to me attaching a git formatted patch to an issue is the best of both worlds. I find the clickety merge/pull request workflows of git[lab|hub] to be both confusing and burdensome ;-]

**Comment by hodefoting** [comment]
Closing the issue after creating merge request 6626, since that might get expedited faster here than an issue with a patch.
