### ISSUE TITLE
sdk80: monitor ROM image is incorrect due to error in original manual listing. Corrected from different Intel listing document.

### ISSUE THREAD

**Issue by colinhowell** [mamedev/mame#6324]
The monitor ROM image for the Intel SDK-80 specified in src/mame/drivers/sdk80.cpp, which was added in commit 64d113d15e40059c5b0d82abff6f2dde91c911e4 and marked BAD_DUMP, does in fact have an error which causes the monitor to not work. For example, if you try a display memory command, e.g. "D9,2A", which should show the bytes in addresses 0009-002A, the monitor will output one byte and then hang. This is despite the fact that it was typed in from a manual listing, probably the one in Appendix A (p. 29) of _Intel MCS-80 System Design Kit User's Guide_, [available on bitsavers](http://bitsavers.org/components/intel/MCS80/9800203B_SDK-80_Users_Guide.pdf).

The error is in the listing itself, in the function HILO on p. 46 of the User's Guide, marked as page 18 of the listing. Lines 894-903 of the listing (ROM addresses 029D-02AA) are as follows:

```
029D 47           894         MOV     B,A     ; SAVE A REGISTER
    029E 23           895         INX     H       ; INCREMENT HL BY 1
    029F 7C           896         MOV     A,H     ; WANT TO TEST FOR 0 RESULT AFTER
    02A0 B5           897         ORA     L       ; /INCREMENTING
02A1 CABD02       898         JZ      HIL05   ; WE`RE AUTOMATICALLY DONE IF IT IS
02A4 23           899         INX     H       ; INCREMENT HL BY 1
02A5 7C           900         MOV     A,H     ; WANT TO TEST FOR 0 RESULT AFTER
02A6 B5           901         ORA     L       ; /INCREMENTING
02A7 CABD02       902         JZ      HIL05   ; IF SO, HL MUST HAVE CONTAINED 0FFFFH
02AA E1           903         POP     H       ; IF NOT, RESTORE ORIGINAL HL
```

The error is on lines 895-897, addresses 029E-02A0, which I've indented for emphasis. They are obviously just duplicates of lines 899-901, addresses 02A4-02A6, and this breaks the code. I'm not sure how Intel made this error, perhaps a goof in entering their source code or a bug in their development software, but the result is that a call to this routine ends up running off into la-la land.

Fortunately, another listing of the monitor is also [available on bitsavers](http://bitsavers.org/components/intel/MCS80/Intel_SDK-80_Monitor_Listing.pdf) which does not have this error. Although it is provided as a separate document, it clearly came from a larger manual, being titled "Appendix B" with its first page numbered as 29. On this listing's page 18 (numbered as 46), ROM addresses 029D-02AA are given as follows. Again, I've indented the changed lines for emphasis:

```
029D 47                    MOV     B,A     ; SAVE A IN B REGISTER
    029E E5                    PUSH    H       ; SAVE HL PAIR
    029F 7A                    MOV     A,D     ; CHECK FOR DE = 0000H
    02A0 B3                    ORA     E
02A1 CABD02                JZ      HIL05   ; WE`RE AUTOMATICALLY DONE IF IT IS
02A4 23                    INX     H       ; INCREMENT HL BY 1
02A5 7C                    MOV     A,H     ; WANT TO TEST FOR 0 RESULT AFTER
02A6 B5                    ORA     L       ; /INCREMENTING
02A7 CABD02                JZ      HIL05   ; IF SO, HL MUST HAVE CONTAINED 0FFFFH
02AA E1                    POP     H       ; IF NOT, RESTORE ORIGINAL HL
```

I've tried the SDK-80 emulation with this change of bytes 029E-02A0 in my ROM image, and the monitor now appears to work properly, though I haven't tested it exhaustively or compared the respective listings for any other differences, other than a cursory check that they end with the same bytes in the same place.

Given that the bug in the erroneous monitor listing renders the monitor useless, I doubt whether any copies of it would have made it to the field in that form. The corrected version is certainly vastly preferable.

The corrected monitor ROM image has CRC 9bb1c268 and SHA1 e84e358f81f181f40f4f8d4c4f76370b7d82e615.

**Comment by Robbbert** [comment]
Addressed in https://github.com/mamedev/mame/commit/51628f7532d2bd6af3dbcacb94d4abac24be44e1
