### ISSUE TITLE
isbc8010: ROM monitor "M" command is broken by a single incorrect byte in the ROM image, due to OCR error in label in source archive's assembly file. Corrected from original listings in Intel manuals.

### ISSUE THREAD

**Issue by colinhowell** [mamedev/mame#6336]
The image of ROM sbc80p.a23 specified in src/mame/drivers/isbc8010.cpp for the Intel iSBC 80/10's ROM monitor currently has a broken "M" (move memory) command. Executing this command will cause the monitor to sit with an empty blank line instead of giving a new command prompt. It turns out that the monitor is waiting for character input as if it were in the "I" (insert instructions) command. Typing Escape to terminate input will bring back the prompt, but examining memory will show that only the first byte of the requested range has been moved.

The problem is that the "M" command's routine, MCMD, has a one-byte error near the end, within the JMP instruction at address 0x10C. This JMP is supposed to loop back into the routine at address 0xF7 (label MCM05), to move the remaining memory in the range, but the bad byte (at address 0x10D) changes the jump address to 0xB4, which happens to match label ICM05. That's the point within the "I" command's routine, ICMD, where that routine would wait for character input. Hence the behavior I see.

Comparing the ROM byte with the listings in Intel's manuals available on bitsavers (either p. 220 of [_System 80/10 Microcomputer Hardware Reference Manual_](http://bitsavers.org/pdf/intel/iSBC/9800316B_System_80_10_Microcomputer_Hardware_Reference_Manual_77.pdf) or p. 184 of [_SBC 80/10 and SBC 80/10A Single Board Computer Hardware Reference Manual_](http://bitsavers.org/pdf/intel/iSBC/9800230F_iSBC_80-10_SBC_Hardware_Reference_Manual_Aug77.pdf))  shows that it's the ROM image which is wrong; the originally listed code is correct. When I tracked down the [archive](http://www.nj7p.org/Computers/Software/Monitors/work/sbc80p_1_0a.7z) (on [NJ7P's ROM monitors page](http://www.nj7p.org/Computers/Software/Mon.html)) where the ROM image's data originally came from and looked at its assembly source, which came from an OCR of the manual listing, it's clear that the OCR misrecognized the MCM05 label, the branch's intended target, as "ICM05", the "I" command routine's label. Hence the branch was assembled to go there instead.

As I said, the error is at ROM address 0x10D, at offset 0x10D in the image of ROM sbc80p.a23, the first of the two ROMs for the 80/10 Monitor v1.1. The bad byte has value 0xB4; the correct value should be 0xF7. The corrected ROM image should have CRC 30e58470 and SHA1 9ceca8b683e9348d37577d950136024ce9f47b6a.

**Comment by Robbbert** [comment]
Addressed by https://github.com/mamedev/mame/commit/354e0a65c8effbc73e79af5b20c1196329de7158
