### ISSUE TITLE
isbc8010: So-called "BASIC-80" BIOS isn't really BASIC-80 at all, but some weird derivative of Palo Alto Tiny BASIC. Needs a less misleading, more descriptive name.

### ISSUE THREAD

**Issue by colinhowell** [mamedev/mame#6338]
This is more of an accuracy or documentation complaint than a real bug, but the isbc8010 driver's alternate BIOS, although labeled as "BASIC-80" (and calling itself that on startup) isn't real BASIC-80 at all. As people figured out on the [forum thread](https://stardot.org.uk/forums/viewtopic.php?f=3&t=9821) where it was first mentioned, it's some derivative of Palo Alto Tiny BASIC, a very small, stripped-down BASIC. In particular, its extremely terse error messages, "WHAT?", "HOW?", and "SORRY", and its ability to abbreviate commands using ".", such as "P." for PRINT, are specific to Palo Alto Tiny BASIC and its descendants. However, unlike normal Palo Alto Tiny BASIC, which had only integer math, this has only floating-point math.

I suggest the BIOS option should be renamed to make its actual heritage clearer.

Real BASIC-80 was Microsoft's BASIC interpreter for 8080/8085/Z80 systems. Intel offered its own version of BASIC-80 which seems to have been the same product under the hood, specialized for Intel's 8080 and 8085 development systems. Although Intel's version (documented in Intel's _BASIC-80 Reference Manual_, available on [bitsavers](http://bitsavers.org/pdf/intel/ISIS_II/9800758-02_BASIC-80_Reference_Manual_Sep79.pdf)) normally ran on its Intellec systems as a disk-based program under its ISIS disk operating system, it could also run on the iSBC 80/10 (or other iSBC 80 systems) under Intel's RMX/80 real-time OS, either being booted from disk or being entirely ROM-resident. The hardware requirements were considerable, however. The iSBC system needed add-on boards to provide enough RAM space. If it was set up to boot from disk, or expected to perform disk access in BASIC, it needed a disk controller board and disk drives. If it was ROM resident, an add-on ROM board was needed to provide enough ROM space. (For the gory details, see Appendix F of the aforementioned Intel manual, starting on p. 93.) Of course, supporting this would require expanding the isbc8010 driver to emulate such add-on hardware.

**Comment by Robbbert** [comment]
A note was added to the source, pointing back here.

https://github.com/mamedev/mame/commit/354e0a65c8effbc73e79af5b20c1196329de7158
