### ISSUE TITLE
Support for Merlin: The 10th Quest handheld

### ISSUE THREAD

**Issue by flarn2006** [mamedev/mame#6399]
https://toytales.ca/wp-content/uploads/2015/06/DSC_86041.jpg

I used to love this toy and being able to emulate it would be awesome. :)

**Comment by Robbbert** [comment]
If you want it emulated, you need to supply the information we need, such as technical info, hardware dumps, photos of the internals and so on. Random requests where you don't lift a finger are not allowed. Closing.

**Comment by flarn2006** [comment]
Oh okay, I didn't know that. I just thought I'd post it here in case someone had one lying around and felt like looking at it. I'll see what I can do if I find it—hopefully its firmware is on a chip that's easy to dump!
