### ISSUE TITLE
Build fails on RetroPie 4.5.1 (Raspbian Stretch) on RPi3B+ due to only having clang 6 

### ISSUE THREAD

**Issue by c0d3h4x0r** [mamedev/mame#6409]
Please see https://github.com/libretro/mame/issues/139 for details and relevant discussion.  I was told to report this issue upstream, so here I am.

**Comment by MooglyGuy** [comment]
RetroPie is a conglomeration of ancient toolchains designed to support an equally-ancient conglomeration of emulators. The fact that a modern version of MAME fails to compile on RetroPie's toolchain should not come as a shock to anyone.

**Comment by cuavas** [comment]
For what it’s worth, MAME builds just fine with clang 6.0.1 on x86-64 targets.  I test every release with clang on Linux.
```
$ clang++ --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
