### ISSUE TITLE
Crush Roller/Make Trax constantly adding to the coin counter in the background

### ISSUE THREAD

**Issue by elisimpson** [mamedev/mame#6419]
How to recreate issue:
Launch game
Hit Tab key
Select Bookkeeping Info

You'll see the Coin A counter steadily increasing. Doesn't seem to affect game play but this can't be expected behavior can it?

**Comment by angelosa** [comment]
While the report is legit (the port doesn't seem to be used as a coin counter at all) this kind of bug report is more suited for [MAMEtesters](https://mametesters.org/)
Issues are for MAME framework faults not for individual game bug reports, please make an account there.
