### ISSUE TITLE
D3D HLSL "Color Saturation" slider misconfigured

### ISSUE THREAD

**Issue by elisimpson** [mamedev/mame#6432]
The saturation slider has an "extra zero" bug I believe. The default value is set to 10 instead of 1, max value 40 instead of 4. The "1" value is still the neutral setting, so if it's set to the default of 10 it results in a super-saturated look which can't be desirable.

Tested on .219 Windows 10 64bit

**Comment by angelosa** [comment]
Looks fixed by current 0.228 hlsl package.
![hlsl_color_saturation](https://user-images.githubusercontent.com/9251271/107443944-03258d80-6b3a-11eb-822b-ed127919d2f2.png)
Closing.
