### ISSUE TITLE
[Regression] Great Swordsman (gsword) and clones - NO SOUND

### ISSUE THREAD

**Issue by fastpop72** [mamedev/mame#6478]
No more sound in gsword and clones.

Tested on Linux & Win10.

**Comment by Osso13** [comment]
Hi,
thanks for the report but this is known: see note in the source.
https://github.com/mamedev/mame/blob/1bf9b8ea42e34a7f44e2b60329308a1421b30f1a/src/mame/drivers/gsword.cpp#L198

**Comment by fastpop72** [comment]
Thank you!

**Comment by fastpop72** [comment]
@Osso13 So why such a regression with the sound? To me seems ok on this old videosnap https://www.youtube.com/watch?v=290YO9sGfRk

**Comment by Osso13** [comment]
Some months ago the driver was updated to use the dumped MCU contents:
https://git.redump.net/mame/commit/src/mame/drivers/gsword.cpp?id=057fcc429f726ee6f15637e5a49d7825c6eabe77
This caused a temporary regression in sound It's possible it will be solved when the other 3 MCUs are read. You can read more about the effort here: https://www.mameworld.info/ubbthreads/showthreaded.php?Cat=&Number=385612&page=0&view=expanded&sb=5&o=&fpart=1&vc=1
