### ISSUE TITLE
Model2 Disassembly Instruction Display Issues

### ISSUE THREAD

**Issue by cglmrfreeman** [mamedev/mame#6559]
At `0x015EEC` in the `maincpu` of Rail Chase 2, the raw data is as follows: `00 10 05 86`

In IDA Pro, the instruction disassembles to the following: `callx   (g4)`

In MAME, the raw opcode is displayed as `86051000` with the following as the dasm instruction: `callx pfp,(g4)`

Using onlinedisassembler.com with the i960mc processor set gives us the following disassembly: `callx   (g4)`

Also, at `0x0117BC` in the `maincpu` of Sonic the Fighters (not Championship), the raw data is as follows: `8F 8F 73 58`

In IDA Pro, the instruction disassembles to the following: `alterbit 0xF, r14, r14`

In MAME, the raw opcode is displayed as ` 58738F8F` and... hmmm... disassembles to `58 58:f 58738f8f 0 3`

I am unsure if `alterbit` was ever implemented?

Using onlinedisassembler.com with the i960mc processor set gives us the following disassembly: `alterbit 15, r14, r14`

I apologize that this is the second time I am filing an issue with the 80960kb disassembler, but I am very interested in Model2 games. Unfortunately, again, I have no suggested fix.

**Comment by SailorSat** [comment]
The i960 dasm of MAME certainly does not implement `alterbit`.

After adding it to the `mnem_reg` array results, the output of that particular line in Sonic the Fighters reads `alterbit r14,r14,0xf` which seems off too.

**Comment by SailorSat** [comment]
Turns out, the issue with `alterbit` seems also affect `clrbit`.

`5841C606` in MAME gets disassembled to `clrbit  r8,r7,r6`

seems like the operands get turned around
onlinedisassembler.com with the i960mc gives: `clrbit r6,r7,r8`

**Comment by SailorSat** [comment]
Hm...
Indeed the disassembly of MAME seems to turn operands around.

The i960 Processor Assembler Users's Guide shows an example like:
```
lda _target,tmpreg
callx (tmpreg)
```

A somewhat similar code in MAME gives:
```
ld      r3,0x2274e4[r3*4]
callx   pfp,(r3)
```

An example of a leaf routine could look like:
```
lda  subr_ret,g14
mov  g14,g7
...
mov  0,g14
bx   (g7)
ret
```

Again MAME seems off:
```
lda     g14,0x1e45c
mov    g0,g14
...
bx    pfp,(g0)
ret
```

**Comment by cglmrfreeman** [comment]
Just built MAME post #6612, and indeed this fixes the Rail Chase 2 issue and adds alterbit in Sonic the Fighters. Closing issue.
