### ISSUE TITLE
[IBM 5170] Hash doom2 - installation failed during creation of DOOM2.WAD

### ISSUE THREAD

**Issue by wwark** [mamedev/mame#6573]
Hi,

I used the floppy available there (https://github.com/mamedev/mame/blob/master/hash/ibm5170.xml)
I validate the hash of those floppy but I have an error during creating the DOOM2.wad.

Anyone have the same experience ?
Thanks,

**Comment by DopefishJustin** [comment]
I can confirm this, it looks like disk 1 of the "doom2" set is a bad dump. The "doom2a" clone works so I will replace it with that one.

**Comment by DopefishJustin** [comment]
Thank you for the report!

**Comment by wwark** [comment]
Thank you
