### ISSUE TITLE
[IBM 5170] hash flashb - Installation failed on the first floppy

### ISSUE THREAD

**Issue by wwark** [mamedev/mame#6574]
Hi,

I used the floppy available there (https://github.com/mamedev/mame/blob/master/hash/ibm5170.xml)
I validate the hash of those floppy but I have an error during installing the first floppy of flashb.

Anyone have the same experience ?
Thanks,

**Comment by DopefishJustin** [comment]
Works fine for me with the "ct486" driver in MAME.

**Comment by wwark** [comment]
it tried on fpga replica of 486 but i have an issue maybe related to my setup.
Thank you for the check.
