### ISSUE TITLE
[IBM 5150] Sim City questions/request

### ISSUE THREAD

**Issue by wwark** [mamedev/mame#6578]
Hello,

in the simcity parent and clones we have two games simcity (1989) and simcity classic (1993).
https://en.wikipedia.org/wiki/SimCity_(1989_video_game) (cf wikipedia page)

I think it might be good to split them or relabel the parent to inform it is the classic version it will help to differentiate them.

Thanks !

**Comment by DopefishJustin** [comment]
Split them, thanks.
