### ISSUE TITLE
[Mame 0.171] Missing strings to translate...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [mamedev/mame#658]
Hello, 

I found some missings strings to translate. Is it possible to add them ?

![mame_1 0 171](https://cloud.githubusercontent.com/assets/12481242/13378702/c6299e2a-de0e-11e5-871a-81761dedc0e7.png)
![mame_2 0 171](https://cloud.githubusercontent.com/assets/12481242/13378703/c62c40ee-de0e-11e5-8e6d-9a7a769e64f8.png)
![mame_3 0 171](https://cloud.githubusercontent.com/assets/12481242/13378704/c68a0e4a-de0e-11e5-96c0-6d540ff9939e.png)
![mame 0 171](https://cloud.githubusercontent.com/assets/12481242/13378707/ce1711d0-de0e-11e5-9031-284e63b79ccc.png)

**Comment by cuavas** [comment]
As we improve the code, more strings will become localisable. I believe at least most of the strings you've pointed out are already localisable in the latest source in the github repository.

**Comment by BenjaminSiskoo** [comment]
I'll check it, thanks
