### ISSUE TITLE
SN76489 noise control register

### ISSUE THREAD

**Issue by michelgerritse** [mamedev/mame#6580]
The SN76489 noise control register (register #6) should also be updated during a data write (bit7 = 0) and not only during a latch/data write (bit7 = 1).

Normally, the data write will update the upper 6 bits of a tone control register. But in the case of the noise control it will always update the 3 lower bits.

This is at least true for the Sega version of this sound chip, as the Master System game "Micro Machines" makes use of this undocumented feature. The snare drum in this game is wrong without correctly implementing this feature.

**Comment by rb6502** [comment]
Why was this closed?  Did it turn out not to be correct?

**Comment by michelgerritse** [comment]
The code turned out to be correct, I was wrong. Better should have stated that before I closed the issue.

I was triggered by reading this line:

if ((data & 0x80) == 0) logerror("sn76496_base_device: write to reg 6 with bit 7 clear; data was %03x, new write is %02x! report this to LN!\n", m_register[6], data);

However, I missed the fact that the next line of code was doing this:

if ((data & 0x80) == 0) m_register[r] = (m_register[r] & 0x3f0) | (data & 0x0f);

The result is that the 3 noise control bits always get updated, regardless of data bit 7 being set or not.
Sorry for the confusion.



Van: R. Belmont
Verzonden: vrijdag 1 mei 2020 19:45
Aan: mamedev/mame
CC: michelgerritse; State change
Onderwerp: Re: [mamedev/mame] SN76489 noise control register (#6580)

Why was this closed? Did it turn out not to be correct?

**Comment by rb6502** [comment]
Thanks, glad to hear the code was OK :)
