### ISSUE TITLE
RetroArch core has low performance compared to Standalone version

### ISSUE THREAD

**Issue by BroKill** [mamedev/mame#6594]
Hello,
 
as the title description says I'm wondering why?

Tested this using same version of both RA core and Standalone and running Road Burners v1.04 rom + chd.
Settings are the same, no bilinear filter, autoframeskip and v-sync active.
In RA I'm getting bad performance and in standalone all is good.

Can some MAME dev check this?

Thanks in advance.

CHEERs

**Comment by cracyc** [comment]
We don't have anything to do with the Retroarch build, you'd have to ask them about it.

**Comment by rb6502** [comment]
And to amplify: we want you to use our standalone version, so we're not seeing the problem here.  The RA cores have many features and options disabled or removed compared to what we ship.

**Comment by BroKill** [comment]
Ok guys, didn't know that.
I thought both version are from same devs, I aoologize for that.

I will use the standalone one, need just a bit of practice to set it with LaunchBox :)

CHEERs
