### ISSUE TITLE
mc1502 machine: random bugs during execution of sigma four dos and other programs

### ISSUE THREAD

**Issue by wadim-al** [mamedev/mame#6613]
Problem:
During execution of sigma four dos on mc1502 machine after issuing "dir" command several times once or more in 5 attempts the command returns garbage. Also sometimes running other apps from the diskette fails. For example "tree" command returns error message about incorrectly typed command.

Steps:
1. Start mc1502 machine with default bios and 640k configuration with basic rom attached and diskette controller attached
2. Boot from sigma four dos using @ directive in the monitor
3. After dos boots issue the "dir" command several times
4. Issue the "tree"command several times.

![mameui64_2020-04-29_19-22-04](https://user-images.githubusercontent.com/29713984/80621556-228e7680-8a50-11ea-8ee7-d5b3ce3d7802.png)
![mameui64_2020-04-29_19-26-45](https://user-images.githubusercontent.com/29713984/80621558-23bfa380-8a50-11ea-96fb-d8d0da774c5c.png)

**Comment by cracyc** [comment]
Something is up with the motor_on bit.   It doesn't try to turn on the motor if 0x10a returns 1.  Maybe @shattered can look at it.  FreeDOS appears to also be affected by this but MSDOS 3.3 doesn't for whatever reason.

**Comment by wadim-al** [comment]
Here are manual pages for FDD controller. Maybe that will help.
I've tried translating, but I'm not a native English speaker.

Manual says:
motor ON signal 10Ah Read-only bit
Interchange control scheme synchronises io between CPU and drive using RDY and DRQ signals.
When CPU accesses state port DRQ, ready flag turns off and CPU waits for DRQ signal arrival.
When the next data byte arrives or inquired ready flag is set and CPU continues execution of commands.
When there is no data, readyness will be set by INTRQ or MOTOR ON signal
If additional info is needed please ask. I have all pages of docs.

![p0008](https://user-images.githubusercontent.com/29713984/80683065-41cae980-8acc-11ea-8376-76c4b71a1ab1.png)

**Comment by p1pkin** [comment]
@wadim-al возможно это следсвие каких-то относительно недавних изменений в эмуляции FD17xx-подобных контроллеров FDD, в т.ч. ВГ93. есть возможность проверить на более старых версиях MAME ?

**Comment by wadim-al** [comment]
> @wadim-al возможно это следствие каких-то относительно недавних изменений в эмуляции FD17xx-подобных контроллеров FDD, в т.ч. ВГ93. есть возможность проверить на более старых версиях MAME ?

Попробую, отпишусь

**Comment by wadim-al** [comment]
Reproduced with 0.202 too.
Воспроизвел на 0.202.

**Comment by p1pkin** [comment]
thanks, probably some old-standing issue then.

**Comment by cracyc** [comment]
The schematic at http://retropc.org/biblioteka/0106.djvu looks to show the motor lines connected.  The problem seems to be that if the motor on bit doesn't show which drive motor is on so if drive 1 motor is on but the access is to drive 0 then it fails.

**Comment by p1pkin** [comment]
according to docs I/O **read** from 0x100 should activate motorON 3sec timer, not write as it now in src\devices\bus\isa\mc1502_fdc.cpp

**Comment by p1pkin** [comment]
should be fine now

**Comment by wadim-al** [comment]
Thank you all very much for such a quick fix! Confirmed fixed. Tested using both a and b disk drives, 2 OSes.
