### ISSUE TITLE
Simplify OSDs by using std::mutex, std::thread, std::chrono, etc

### ISSUE THREAD

**Issue by rb6502** [mamedev/mame#662]
This would allow porting MAME with fewer external requirements beyond a working C++11 compiler, and move the maintenance of a chunk of code over to the C++ standard library maintainers.

**Comment by mmicko** [comment]
I have cleared and covert to std::atomic and std::mutex usage. But if anyone would take care of osd_work implementation and move it to use std::thread it would be great. 
Do not have time for that right now.

**Comment by rb6502** [comment]
I think this is done to the extent possible with osd_work now using std::thread.  ISO C++ hasn't yet approved standardized networking or filesystem abstractions.  So I'm closing it.  Thanks Micko!
