### ISSUE TITLE
Debugger : Mortal Kombat (rev5.0) can't dump the memory/empty 

### ISSUE THREAD

**Issue by ugurkanates** [mamedev/mame#6672]
Hello , 
I'm trying to dump CPU memory of Mortal Kombat rev5.0 (T-unit) to find some specific addresses such as P1,P2 healths, state of game / is it in fighting mode, round info (who won first round etc)

Unfortunately I cant see memory info when use dump. It dumps alright and says it succesfull but all memory is filled with dots.(.....) I tried multiple commands  to dump
"/mamearcade64 -window -debug mk"
I usually stop the game with two player set up in start of match.

dump a.txt,0,0xFFFF -> empty memory
dump a.txt,0
memdump a.txt -> empty memory

I looked into file of src/driver MK t unit which is same unit as MK2 and NBA Jam etc. I ROM starting  adresss still no success unfortunately. Output was like 38MB (which I used starting and ending points in .cpp file)

Is it bugged or am i doing everything wrong

**Comment by p1pkin** [comment]
you should learn target hardware architecture first.
Midway T-Unit hardware have 'main' RAM at 0x01000000 - 0x013fffff, not at 0

**Comment by ugurkanates** [comment]
@p1pkin  I believe I couldn't tell it properly but I said I tried starting and ending address mentioned in cpp file just like you mentioned after trying 0 adresses.
And that file outputs 38MB empty dots.
![test](https://i.ibb.co/gjD5tz0/Screenshot-from-2020-05-09-20-22-04.png)

Here are some parts of txt I outputted

Starting
`01000000:   ................
01000010:   ................
01000020:   ................
01000030:   ................
01000040:   ................
01000050:   ................
01000060:   ................
01000070:   ................
01000080:   ................
01000090:   ................
010000A0:   ................
010000B0:   ................
010000C0:   ................
010000D0:   ................
010000E0:   ................
010000F0:   ................
01000100:   ................
01000110:   ................
01000120:   ................
01000130:   ................
01000140:   ................
01000150:   ................
01000160:   ................
01000170:   ................
01000180:   ................
01000190:   ................
010001A0:   ................
010001B0:   ................
010001C0:   ................
010001D0:   ................
010001E0:   ................
010001F0:   ................
01000200:   ................
01000210:   ................
01000220:   ................
01000230:   ...............



`

I inspected entire file and all  empty.

**Comment by p1pkin** [comment]
works fine here,
mame64.exe mk -d
then
dump mk.txt,1000000,100
and I see RAM start as was expected
> 01000000:  D7E3 D7E3 E3E3 E3E3 D7D7 E3D7 D7E3 E3C5  ................
01000080:  E3D7 E3E3 D7E3 D7D7 E3E3 D7D7 E3D7 E3D7  ................

here is issue tracker, not help of support forum. you should better go to https://mameworld.info/ or http://cheat.retrogames.com
