### ISSUE TITLE
konami.ops TYPO on ROLD, RORD opcodes?

### ISSUE THREAD

**Issue by RndMnkIII** [mamedev/mame#6713]
The implementation of those opcodes should replace **m_temp.w** by **m_q.r.d** in the while inner sentences:

- `m_temp.w = set_flags<uint16_t>(CC_NZ, rotate_left(m_temp.w));`

- `m_temp.w = set_flags<uint16_t>(CC_NZ, rotate_right(m_temp.w));`

resulting:
- `m_q.r.d = set_flags<uint16_t>(CC_NZ, rotate_left(m_q.r.d));`

- `m_q.r.d = set_flags<uint16_t>(CC_NZ, rotate_right(m_q.r.d));`

```
ROLD:
	@m_temp.b.l = read_operand();

	// doing this as a loop is lame
	while(m_temp.b.l--)
		m_temp.w = set_flags<uint16_t>(CC_NZ, rotate_left(m_temp.w));

	eat(1);
	return;

RORD:
	@m_temp.b.l = read_operand();

	// doing this as a loop is lame
	while(m_temp.b.l--)
		m_temp.w = set_flags<uint16_t>(CC_NZ, rotate_right(m_temp.w));

	eat(1);
	return;
```

**Comment by happppp** [comment]
You're right, thanks =)
https://github.com/mamedev/mame/commit/6e0906445d02195575a07c4ebd03f2f9c26d07ed
