### ISSUE TITLE
[ibm5170] SimLife should be moved to ibm5150

### ISSUE THREAD

**Issue by ArcadeShadow** [mamedev/mame#6728]
The SimLife in the ibm5170 Software List, should be a clone of the SimLife in the ibm5150 Software List.
I compare the installed file in the DOS system and some of the files are different. In the game it seams equal. But I found that the readme file has a difference too.
In the ibm5150 SoftList, you can find this line "3) Type PROMPT $P$G[ENTER]" but in the ibm5170 version the word "[ENTER]" is missing (see attached image). The file in the ibm5170 are dated 1992 and the ibm5150 are 1993 dated. So I thing the ibm5170 version is an older one.
![simlife readme dif](https://user-images.githubusercontent.com/26376777/82706362-5173c300-9c71-11ea-95b1-7374787b9c92.JPG)

**Comment by DopefishJustin** [comment]
Nice catch. Actually, I will be moving both of them to ibm5170 because it requires a 386 processor to run.

**Comment by DopefishJustin** [comment]
Fixed.
