### ISSUE TITLE
Missing include file?

### ISSUE THREAD

**Issue by johnparker007** [mamedev/mame#673]
The driver mephisto.cpp has this include line:

#include "includes/mboard.h"

But the file "mboard.h" doesn't exist (And so it doesn't build).  Am I missing something, or has someone inadvertently broken the build?  (First time compiling MAME, but experienced coder - this just looks broken)...

Cheers,
John :)
gyrox007@gmail.com

**Comment by Tafoid** [comment]
Yes.  Both mephisto.c and mmodular.c will need to be adjusted.
Locally you could simply adjust source file:   scripts\target\mame\mess.lua and delete the two lines below:
	MAME_DIR .. "src/mame/drivers/mephisto.cpp",
	MAME_DIR .. "src/mame/drivers/mmodular.cpp",
Unsure when the actual fix will happen as the recently dropped mboard file is needed for those chessboard drivers.

**Comment by LnmVolbo** [comment]
@ Tafoid, thanks for the quick fix, compiling properly again.

**Comment by johnparker007** [comment]
Hey thanks guys! :)  I have some more free time over the weekend, will make the local changes and build again - cheers John :)

**Comment by LnmVolbo** [comment]
No need to make local changes now, it's been corrected properly: https://github.com/mamedev/mame/commit/cc2330d739ab68afed3b6725b7d2f80bb582ef50

**Comment by mmicko** [comment]
Sorry for this, was late and I made mistake by not checking full build.

**Comment by johnparker007** [comment]
Thanks for this fix!  Having resynced to latest - it then failed during linking:

_---------------------------------------------------------------------------------------------------------
Building driver list...
33050 driver(s) found
Compiling generated/mame/mame/drivlist.cpp...
Emitting mamevers.rc...
Compiling resources src/mame/osd/windows/mame/mame.rc...
Linking mame64.exe...
../../../../mingw-gcc/bin/x64/Release/mame_mame/libsvi.a(svi318.o):svi318.cpp:(.
rdata$.refptr._ZTV12svi318_state[.refptr._ZTV12svi318_state]+0x0): undefined ref
erence to `vtable for svi318_state'
collect2.exe: error: ld returned 1 exit status
mame.make:228: recipe for target '../../../../../mame64.exe' failed
make[2]: *** [../../../../../mame64.exe] Error 1
makefile:952: recipe for target 'mame' failed
make[1]: *** [mame] Error 2
makefile:851: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

[MINGW64] C:\msys64\src\mame>
---------------------------------------------------------------------------------------------------------------------
_


Though I've not compiled MAME before so I could be being a noob ;)  - suspect it's related to the svi318 driver?

Cheers,
John :)

**Comment by cuavas** [comment]
That's been fixed since

**Comment by johnparker007** [comment]
Awesome thanks :)  I have resynced and successfully compiled MAME - some of
my commits will be on the way in a few weeks! ;)
