### ISSUE TITLE
mmatrix/mmatrixd/mmatrixj invincibility cheat syntax issue

### ISSUE THREAD

**Issue by esotericDisciple** [mamedev/mame#6742]
self-care is playing all shmups with the invincibility cheat on, which makes it super depressing when the cheat doesn't work...Whenever enabled for Mars Matrix all that happens is an endless stream of:
```Error executing expression "maincpu.pw@((maincpu.pd@FF49BC)+72)=0002": syntax error```
No idea what's going on, but I suspect it is a syntax error and I don't know what needs fixing. The only hint I've managed to extract is that splitting the line into 
```maincpu.pw@FF49BC=0002``` and ```maincpu.pd@FF49BC=0002``` causes some of the game to think that its playing in TATE mode and sends attacks in that direction; the exact same glitch happens when playing the Retroarch FBNeo version of mame with the invincibility cheat enabled...

**Comment by esotericDisciple** [comment]
Update: I decided to try this and it works...was not expecting to succeed...
```
  <cheat desc="P1 Invincibility">
    <script state="run">
      <action>temp0=maincpu.pd@FF49BC</action>
      <action>temp0=temp0+72</action>
      <action>maincpu.pw@temp0=0002</action>
<!--       <action>maincpu.pw@((maincpu.pd@FF49BC)+72)=0002</action> -->
    </script>
  </cheat>
```

**Comment by Tafoid** [comment]
I don't see this error with a current version of MAME upon activating the Invincibility cheat for that game, using either -cheat or the CHEAT Lua Plugin.  That said, this is not the place for cheat fixes or discussion as it is an externally controlled file not shipped with the emulator, so support lies elsewhere:

http://www.mamecheat.co.uk/forums

**Comment by esotericDisciple** [comment]
What if this is part of an underlying issue with any changes made to linux and/or gcc that affects the source code for cheats?
