### ISSUE TITLE
chdman bug (not suported universal character)

### ISSUE THREAD

**Issue by DarkFrost89** [mamedev/mame#6757]
Hi
ı use turkish language my pc but chdman not work my desktop folder and
chdman see my cue but chdman not see my bin and not convert the files
https://imgur.com/4jt86Lv
but if ı move chd and included folder "C:\ " and change my folder name "Yeni klasör" to "a" working
otherwise not working frown
Please Support Universal Character in mame and chdman

**Comment by cuavas** [comment]
Fixed for chdman command line arguments in 35c46962957ff46e854833f25dd3d153b345fc97.  The issues with console output on Windows are more complicated to fix.
