### ISSUE TITLE
distate.h needs a double template specialisation for device_pseudo_state_register

### ISSUE THREAD

**Issue by couriersud** [mamedev/mame#6769]
Currently I am implementing the following code in netlist.cpp (code not yet committed). 
Actually the implementation below should be in distate.h.

I am creating an issue here because I hope somebody with more mame core knowledge than myself can pick this up.

```
template<>
class device_pseudo_state_register<double> : public device_state_entry
{
public:
	typedef typename std::function<double ()> getter_func;
	typedef typename std::function<void (double)> setter_func;

	// construction/destruction
	device_pseudo_state_register(int index, const char *symbol, getter_func &&getter, setter_func &&setter, device_state_interface *dev)
		: device_state_entry(index, symbol, sizeof(double), ~u64(0), DSF_FLOATING_POINT, dev),
			m_getter(std::move(getter)),
			m_setter(std::move(setter))
	{
	}

protected:
	// device_state_entry overrides
	virtual u64 entry_value() const override { return u64(m_getter()); }
	virtual void entry_set_value(u64 value) const override { m_setter(double(value)); }
	virtual double entry_dvalue() const override { return m_getter(); }
	virtual void entry_set_dvalue(double value) const override { m_setter(value); }

private:
	getter_func             m_getter;               // function to retrieve the data
	setter_func             m_setter;               // function to store the data
};
```

**Comment by cuavas** [comment]
The debugger doesn’t support floating point expressions.  There’s a huge amount of work involved in adding real support for doubles.  I’d rather have it obvious doubles aren’t supported than have something like this in the interface.

**Comment by couriersud** [comment]
That's ok and why I put it here as a an issue. The code currently is in netlist.cpp. The debugger supports the display of doubles. That's enough for the netlist debugger interface to display analog nets. 

Fine to close this.
