### ISSUE TITLE
sunplus_unsp20soc.cpp doesn't exist

### ISSUE THREAD

**Issue by mcfilmmakers** [mamedev/mame#6789]
The repo can't find https://github.com/mamedev/mame/blob/master/src/mame/drivers/sunplus_unsp20soc.cpp

404 error results.

**Comment by stilett0** [comment]
Hmm, I'm guessing Github doesn't support underscores? Works fine in standard git tho.

**Comment by mcfilmmakers** [comment]
It definitely supports underscores. i literally have gone through every single one. This is the only one that doesn't work.

**Comment by stilett0** [comment]
Oh! No, actually it's been deleted or renamed or something, as the link to redump.net shows.
https://git.redump.net/mame/tree/src/mame/drivers/sunplus_unsp20soc.cpp

**Comment by stilett0** [comment]
https://github.com/mamedev/mame/commit/a17d577403aa224720e5761b422f4ce2002d2278 shows:
Its functions were expanded and split:
```
MAME_DIR .. "src/mame/drivers/generalplus_gpl16250.cpp",
	MAME_DIR .. "src/mame/drivers/sunplus_unsp20soc_mobigo.cpp",		MAME_DIR .. "src/mame/drivers/generalplus_gpl16250_rom.cpp",
	MAME_DIR .. "src/mame/drivers/generalplus_gpl16250_romram.cpp",
	MAME_DIR .. "src/mame/drivers/generalplus_gpl16250_nand.cpp",
	MAME_DIR .. "src/mame/drivers/generalplus_gpl16250_mobigo.cpp",
	MAME_DIR .. "src/mame/drivers/generalplus_gpl16250_spi.cpp",
	MAME_DIR .. "src/mame/includes/generalplus_gpl16250.h",
	MAME_DIR .. "src/mame/includes/generalplus_gpl16250_romram.h",
	MAME_DIR .. "src/mame/includes/generalplus_gpl16250_nand.h",
	MAME_DIR .. "src/mame/machine/generalplus_gpl16250.cpp",
	MAME_DIR .. "src/mame/machine/generalplus_gpl16250.h",

```

**Comment by DavidHaywood** [comment]
it was renamed, but somehow didn't get deleted (even if it should have been) I also deleted it in a recent PR
