### ISSUE TITLE
Require write/push access please :)

### ISSUE THREAD

**Issue by johnparker007** [mamedev/mame#679]
Hi,

Am new to using github - I have a first test commit I'd like to make, 2x new files (.lay layout files) and 2x revised files (driver files).

I think I require write/push access to commit my local branch "fruit_machine_layouts" into "master" - is that right..?

Thanks in advance for advice or giving me the access required - cheers John :)

**Comment by LnmVolbo** [comment]
That's one way, but the conventional way is to make a pull request.

**Comment by johnparker007** [comment]
Hey LnmVolbo :)

So, I am using a visual client - I can make a pull request into one of the existing branches, but not Master.

I am unable to create a new branch of my own online (the "fruit_machine_layouts" branch is one I created locally.

I can create a Pull request where I commit my changes into say "bgfx_shader" branch, however that seems bad since my changes have nothing to do with background effects shaders ;)

So - should I be able to make a branch online called "fruit_machine_layouts"?  Or do I need permissions setting up?

Cheers for the help :)  John

**Comment by johnparker007** [comment]
Realised a screenshot might be clearer  :)

https://dl.dropboxusercontent.com/u/15679918/Github_permissions.png

So I can commit to "origin\bgfx_shader", but not to "master".  I am unable to create a new branch online via the web interface.

**Comment by ArnaudRinquin** [comment]
@johnparker007 You need to first clone the repository to your own account. Then create a branch, push your changes to that branch, then create a pull request (via github website) to merge your changes into official `mamedev/mame` repo.

Here is [a guide](https://yangsu.github.io/pull-request-tutorial/) for you

**Comment by johnparker007** [comment]
Thanks for the advice, much appreciated - am trying to get this going
now... :)
