### ISSUE TITLE
Problem with -mouse switch in Fairlight CMI

### ISSUE THREAD

**Issue by haiqu** [mamedev/mame#6791]
The OS9 disk boots into the LightWriter WP app, which needs a mouse. However, when shelling out to DOS the keyboard is not selected, so:

1. There's no way to do anything, and
2. There's no way to close the emulation either.

Requires machine reboot. A YouTube video from 2017 shows it working correctly, see https://www.youtube.com/watch?v=c1wKlParRz4&feature=youtu.be

**Comment by stilett0** [comment]
To tell you the truth, this would go better reported at MAMETesters. https://www.mametesters.org

**Comment by haiqu** [comment]
Will report there, once I get out of viewer status.

**Comment by Tafoid** [comment]
https://mametesters.org/view.php?id=7677

**Comment by haiqu** [comment]
Issue can be closed. I created the cmi2x.zip ROM file from "official" Fairlight sources and evidently one of the files was bad. Downloading from another source fixed this issue.
