### ISSUE TITLE
Appveyor GCC build is broken

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#6804]
I am posting it here so it does not get forgotten. Appveyor gcc build has been failing for a while due to undefined references in emumem.cpp making it exceed the 1 hour build limit:
https://ci.appveyor.com/project/startaq/mame/builds/33369429/job/0sd05r2ytk8f473m

**Comment by belegdol** [comment]
According to the build history the last successful build was 2a755734, and 4bd6f63c is the first one which fails.

**Comment by belegdol** [comment]
The issue appears to only happen with OPTIMIZE=1, not with OPTIMIZE=3 (default).

**Comment by belegdol** [comment]
OPTIMIZE=2 seems to be affected too, it requires NOWERROR=1 to reach linking though.

**Comment by belegdol** [comment]
I have bisected the issue down to 22513fb6.

**Comment by belegdol** [comment]
There is definitely something dodgy going on. This works:
```
make SOURCES=src/mame/drivers/model1.cpp NOWERROR=1 OPTIMIZE=3 VERBOSE=1 -j12
```
but this one does not:
```
make SOURCES=src/mame/drivers/model1.cpp NOWERROR=1 OPTIMIZE=2 OPT_FLAGS="-fgcse-after-reload -fipa-cp-clone -floop-interchange -floop-unroll-and-jam -fpeel-loops -fpredictive-commoning -fsplit-loops -fsplit-paths -ftree-loop-distribution -ftree-loop-vectorize -ftree-partial-pre -ftree-slp-vectorize -funswitch-loops -fvect-cost-model -fvect-cost-model=dynamic -fversion-loops-for-strides" VERBOSE=1 -j12
```
According to man gcc, the above commands should be equivalent:
> -O3 Optimize yet more.  -O3 turns on all optimizations specified by -O2 and also turns on the following optimization            flags:
> -fgcse-after-reload -fipa-cp-clone -floop-interchange -floop-unroll-and-jam -fpeel-loops -fpredictive-commoning -fsplit-loops -fsplit-paths -ftree-loop-distribution -ftree-loop-vectorize -ftree-partial-pre -ftree-slp-vectorize -funswitch-loops -fvect-cost-model -fvect-cost-model=dynamic -fversion-loops-for-strides

**Comment by jwakely** [comment]
> According to man gcc, the above commands should be equivalent:

No it doesn't actually say they are equivalent.

There are some optimization effects that depend on the optimization level and don't have a specific flag to control them.

**Comment by belegdol** [comment]
I did not know that, thank you for clarifying.
I have reported the bug to gcc upstream in the meantime:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95949

**Comment by belegdol** [comment]
Here is feedback from GCC upstream:
> What we inline and what not changes across releases, without a testcase my suspicion is that mame uses extern template but fails to provideall necessary instantiations.

I am not able to provide a testcase, would anyone be able to help?

**Comment by jwakely** [comment]
It doesn't need to be a complete standalone program. The bug reporting instructions ask for preprocessed source, which should be sufficient to show the problem.

**Comment by belegdol** [comment]
I have filed  #6987 as a temporary (hopefully) workaround.

**Comment by belegdol** [comment]
Closing as we no longer use appveyor.
