### ISSUE TITLE
Regression: 04938: mpatrol: Screen right offset and sprites with Flip Screen on

### ISSUE THREAD

**Issue by maziac** [mamedev/mame#6845]
The issue  [04938: mpatrol: Screen right offset and sprites with Flip Screen on](https://mametesters.org/view.php?id=4938)
which was supposed to be fixed in 0.148 is still in there or again in there.

Found the same issue in 0.155 and 0.200. Could not test 0.221 but since it was claimed to be fixed already for 0.148 I would guess that it will not work in 0.221 as well.

**Comment by Robbbert** [comment]
It looks perfect to me. You need to test against the latest version of MAME, reports against old versions are not valid. And, since you claim it has been there a long time, you need to log a mametesters report, with evidence supplied.

**Comment by Tafoid** [comment]
This appears to have re-regressed at some point, but starting MAME 0.203 all looks good.  As others are saying, it is best to test current version before reporting anything is wrong.  Never assume something will not work, especially when you have nearly 2 years of development between last tested version and current.

For the record, an external submission fixed it.
https://github.com/mamedev/mame/pull/4061
https://github.com/mamedev/mame/commit/844cd2cee9449bec100791f59199d1a810c74456

**Comment by Tafoid** [comment]
It re-regressed in 0.153 - but tracing the reason is tricky as there is over 4 months of development between integer releases as well as driver changes/filename changes.
