### ISSUE TITLE
Passing -nomouse parameter still captures host mouse input on mouse driven systems

### ISSUE THREAD

**Issue by farvardin** [mamedev/mame#6847]
I'm using mame 0.215 from linux mint 19.3

When launching mame, it grabs my mouse, and I have to use alt-tab or exit to get it again.
I can pass the -nomouse argument in command-line, so it disables the capture of my mouse.

But the man said it should be -nomouse by default, which is not the case:
https://github.com/mamedev/mame/blob/0374e6f542cdffa50b7f48e228fb16ef91d0db2c/docs/man/mess.6

**Comment by DavidHaywood** [comment]
worse, as I mentioned elsewhere, some systems capture the mouse regardless (eg. cpc6128)

**Comment by rb6502** [comment]
This is not the default behavior on Linux/Mac that we ship (Windows builds are more aggressive but also don't default to mouse-grab).  Are you building from source or using a binary package?

**Comment by farvardin** [comment]
I'm using the repository binary package for mame 0.215 from linux mint 19.3

**Comment by smf-** [comment]
Windows grabs the mouse if you launch a computer that has a mouse
connected (annoyingly even on systems where a mouse wasn't even common
or useful).

It's because

-mouse_device        enable (none|keyboard|mouse|lightgun|joystick) if a
mouse control is present

Is set to mouse by default, if you set it to none then it stops bugging
you (but then systems that need a mouse are a pain).

**Comment by angelosa** [comment]
Tested plain 0.228 on Windows with:
`mame.exe aa310 -bios 2 -mouseprovider N -nomouse`
Where N is any [combination listed in documentation page](https://docs.mamedev.org/commandline/commandline-index.html?highlight=mouseprovider) but `sdl`, can move mouse pointer after POST in all cases except for `win32` and `none`.

**Comment by qazmko1029** [comment]
Tested 0.251 built with MESS subtarget on Windows with pretty all machines me often use, without running with "-mouse_device none" mouse defaults to be grabbed and there's no "release mouse" function I can use, only operations taking away MAME window's focus release the mouse, including all fujitsu FM-Towns, all NEC PC-9800 series, mmr4000le, many IBM PC compatibles, etc.
It's quite annoying.

**Comment by cuavas** [comment]
The interface between the OS-specific modules that deal with this stuff and MAME’s UI is a mess.  This will get fixed in the process of refactoring that.

**Comment by cuavas** [comment]
I think what’s going on here is you’re seeing interaction between the `-[no]mouse` and `-mouse_device` options.  First of all, here’s the relevant part of the usage information:
```
% mamed -showusage
...
#
# CORE INPUT OPTIONS
#
-coin_lockout        ignore coin inputs if coin lockout output is active
-ctrlr               preconfigure for specified controller
-mouse               enable mouse input
-joystick            enable joystick input
-lightgun            enable lightgun input
-multikeyboard       enable separate input from each keyboard device (if present)
-multimouse          enable separate input from each mouse device (if present)
-steadykey           enable steadykey support
-ui_active           enable user interface on top of emulated keyboard (if present)
-offscreen_reload    convert lightgun button 2 into offscreen reload
-joystick_map        explicit joystick map, or auto to auto-select
-joystick_deadzone   center deadzone range for joystick where change is ignored (0.0 center, 1.0 end)
-joystick_saturation end of axis saturation range for joystick where change is ignored (0.0 center, 1.0 end)
-joystick_threshold  threshold for joystick to be considered active as a switch (0.0 center, 1.0 end)
-natural             specifies whether to use a natural keyboard or not
-joystick_contradictoryenable contradictory direction digital joystick input at the same time
-coin_impulse        set coin impulse time (n<0 disable impulse, n==0 obey driver, 0<n set time n)

#
# CORE INPUT AUTOMATIC ENABLE OPTIONS
#
-paddle_device       enable (none|keyboard|mouse|lightgun|joystick) if a paddle control is present
-adstick_device      enable (none|keyboard|mouse|lightgun|joystick) if an analog joystick control is present
-pedal_device        enable (none|keyboard|mouse|lightgun|joystick) if a pedal control is present
-dial_device         enable (none|keyboard|mouse|lightgun|joystick) if a dial control is present
-trackball_device    enable (none|keyboard|mouse|lightgun|joystick) if a trackball control is present
-lightgun_device     enable (none|keyboard|mouse|lightgun|joystick) if a lightgun control is present
-positional_device   enable (none|keyboard|mouse|lightgun|joystick) if a positional control is present
-mouse_device        enable (none|keyboard|mouse|lightgun|joystick) if a mouse control is present
...
```

Note that there are options to automatically enable a particular type of host input device if certain emulated inputs are present.  These options can override `-nomouse`, `-nolightgun` and/or `-nojoystick` depending on how they’re set.

If we check the defaults:
```
% mamed -noreadconfig -showconfig
...
#
# CORE INPUT OPTIONS
#
coin_lockout              1
ctrlr
mouse                     0
joystick                  1
lightgun                  0
multikeyboard             0
multimouse                0
steadykey                 0
ui_active                 0
offscreen_reload          0
joystick_map              auto
joystick_deadzone         0.15
joystick_saturation       0.85
joystick_threshold        0.3
natural                   0
joystick_contradictory    0
coin_impulse              0

#
# CORE INPUT AUTOMATIC ENABLE OPTIONS
#
paddle_device             keyboard
adstick_device            keyboard
pedal_device              keyboard
dial_device               keyboard
trackball_device          keyboard
lightgun_device           keyboard
positional_device         keyboard
mouse_device              mouse
...
```

The last quoted line is the key point: by default, MAME will automatically enable host mouse devices (and by extension mouse capture) if the emulated system has mouse inputs, overriding the `-nomouse` setting.  If you really don’t want mouse input enabled for emulated systems with mouse inputs, you need to change this setting, for example:
* `mame -nomouse -mouse_device none ...` or
* `mame -nomouse -mouse_device joystick ...`
won’t automatically enable mouse capture if the emulated system has mouse inputs.

I’ll update the documentation to make this clearer.

**Comment by cuavas** [comment]
43e30203bd06e98fd55b491872e5e225faf86eda explains what’s going on explicitly.  I still intend to clean up the mess of how mouse capture works in the future, but the current behaviour appears to be correct and should be less confusing with better documentation.
