### ISSUE TITLE
About the Knights of Valour HD

### ISSUE THREAD

**Issue by kakaluote7** [mamedev/mame#6854]
I wanted to know about the Knights of Valour HD simulation, and I and a lot of people who love this game are waiting. I don't have any access to the game I love or don't love, so I'm eager to see how the simulation is going.

**Comment by kakaluote7** [comment]
Sorry, I said Knights of Valour3 HD

**Comment by happppp** [comment]
Ok, it's not much but there are some notes in the driver:
https://github.com/mamedev/mame/blob/master/src/mame/drivers/pgm3.cpp
