### ISSUE TITLE
Mouse cursor with clickable artwork

### ISSUE THREAD

**Issue by Anuskuss** [mamedev/mame#6855]
When playing with clickable artwork, the mouse should not be hidden (in fullscreen). This was first brought up [in 2009 by Mr. Do himself](https://mametesters.org/view.php?id=3459) but nothing came out of it, so I'm reporting this here as well. Honestly this seems to be such an easy thing to fix - there's not even a need for an config option. Just hide the cursor as usual but if an artwork is active and said artwork has clickable elements, unhide it.

P.S. I hope the possibility to turn off specific elements of the artwork (eg bezels) returns in the future :)

**Comment by cuavas** [comment]
There’s already a report at MAME Testers for discussing this – having a duplicate here isn’t productive.  It’s also not as simple as you think.  For example if there are clickable artwork elements but the game is not dependent on them, the mouse pointer may be an unwanted distraction when playing with keyboard or gamepad controls (e.g. with Game & Watch artwork is clickable but it isn’t practical to play that way).

**Comment by Anuskuss** [comment]
I'm aware of the MAME Testers issue (I've even linked it), it just seemed strange to me that nothing has happend in 11 years to fix this. Maybe an option would be better, I was just looking for a more immediate solution. Who knows. maybe someday I'll learn how to code and fix it myself. Then our names will be next to each other :P
