### ISSUE TITLE
QT version

### ISSUE THREAD

**Issue by TrungACZNE** [mamedev/mame#686]
Hi, trying to compile this on Ubuntu 15.04, not sure which version of QT to use.

With QT 5.5.1:
```
Compiling generated/osd/modules/debugger/qt/debuggerview.moc.cpp...
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:13:2: error: #error "This file was generated using the moc from 4.8.6. It"
 #error "This file was generated using the moc from 4.8.6. It"
  ^
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:14:2: error: #error "cannot be used with the include files from this version of Qt."
 #error "cannot be used with the include files from this version of Qt."
  ^
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:15:2: error: #error "(The moc has changed too much.)"
 #error "(The moc has changed too much.)"
```

With QT4.8.6:
```
../../../../../src/osd/modules/debugger/debugqt.cpp:20:45: fatal error: QtCore/QAbstractNativeEventFilter: No such file or directory
compilation terminated.
```
Seems like [QAbstractNativeEventFilter](http://doc.qt.io/qt-5/qabstractnativeeventfilter.html) is a QT5 feature.

**Comment by rb6502** [comment]
QT5 is the correct version; it appears you tried building with Qt5 after building with Qt4 and so the old .moc file wasn't cleaned up.  'make clean' should fix things.

**Comment by galibert** [comment]
Or genie didn't pick the correct moc/didn't manage to tell moc what version
of qt to generate for.

  OG.

**Comment by TrungACZNE** [comment]
Oh I realized that I have Qt4 files lying around after installing some KDE packages.

```$ QT_SELECT=5 make  ```
solves it
