### ISSUE TITLE
Can't do a SYMBOLS=1 build on 64-bit

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#6863]
Using the following command line:

`build SUBTARGET=cave SOURCES=src/mame/drivers/cave.cpp -j5 REGENIE=1 SYMBOLS=1 SYMLEVEL=2`

The build fails with the following message:

```
D:/mame/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: ../../../../mingw-gcc/obj/x64/Release/src/emu/emumem.o: too many sections (37096)
{standard input}: Assembler messages:
{standard input}: Fatal error: can't write 6 bytes to section .text of ../../../../mingw-gcc/obj/x64/Release/src/emu/emumem.o because: 'File too big'
D:/mame/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: ../../../../mingw-gcc/obj/x64/Release/src/emu/emumem.o: too many sections (37096)
{standard input}: Fatal error: can't close ../../../../mingw-gcc/obj/x64/Release/src/emu/emumem.o: File too big
emu.make:1179: recipe for target '../../../../mingw-gcc/obj/x64/Release/src/emu/emumem.o' failed
make[2]: *** [../../../../mingw-gcc/obj/x64/Release/src/emu/emumem.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

I have tried using STRIP_SYMBOLS=1 to no avail. I am currently trying a build with SYMLEVEL=3 to see if that helps. Unfortunately, if this issue persists, I will be unable to do performance profiling, which is a bit unfortunate.

**Comment by cuavas** [comment]
Can you try adding `ARCHOPTS_CXX-Wa,-mbig-obj` and see if it fixes it?  (“Regular” Windows object files have a 16-bit section count, while “big” object files have a 32-bit section count.)

**Comment by MooglyGuy** [comment]
Thanks Vas, I'll give that a try. Also, hap points out that this might be a limitation of GCC 7.x, I'm going to try upgrading if your suggested fix doesn't work.

**Comment by MooglyGuy** [comment]
Thanks again, this worked absolutely brilliantly!
