### ISSUE TITLE
Compiling in Ubuntu

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#6873]
I haven't been able to compile MAME for ages in Ubuntu Mate. I always get this error:

```
GCC 7 detected
Compiling src/osd/modules/debugger/debugqt.cpp...
../../../../../src/osd/modules/debugger/debugqt.cpp:18:10: fatal error: QtWidgets/QApplication: File or folder not found
 #include <QtWidgets/QApplication>
          ^~~~~~~~~~~~~~~~~~~~~~~~
```

The file does exist here: `/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication`

I have followed the instructions in [here](https://docs.mamedev.org/initialsetup/compilingmame.html#debian-and-ubuntu-including-raspberry-pi-and-odroid-devices). But it didn't work.

I really need to be able to compile MAME. Your help will be greatly appreciated.

**Comment by rb6502** [comment]
Which version of Mate is it?

**Comment by belegdol** [comment]
Is this normal that the includes are in x86_64-linux-gnu subfolder? On Fedora 32 the qt5 folder sits directly in /usr/include.

**Comment by couriersud** [comment]
qt5 sits in the same folder on ubuntu 16.04. qt4 has /usr/include/qt4
I am using ` QT_SELECT=5 QT_HOME=/usr/lib64/qt5` as make arguments. I assume @jotego has to find a similar solution.

**Comment by jotego** [comment]
@rb6502 the Ubuntu version is 18.04
@belegdol that might be the cause, I guess. I have both x86_54 and i386 architectures of Ubuntu installed. This is important because I compile retro cores for the [MiST FPGA](https://github.com/mist-devel/mist-board/wiki), which needs a 32 bit environment. So I guess that enabling that architecture creates some movement around folders.
@couriersud that sounds like what I need, but I need to specify the include folder too. Is there a way to define that folder as an argument to make?

**Comment by couriersud** [comment]
@jotego: Not that I know of. Try `make clean` and `make QT_SELECT=5 QT_HOME=/usr/lib64/qt5 REGENIE=1` 
This works here and the QT5 include files are in the same folder as on your machine.
If this doesn't work your qt installation is somehow broken. The build system use qmake from the QT_HOME folder to determine the include folders. `grep -r qmake scripts/` shows the details.

**Comment by jotego** [comment]
I haven't been able to make it work. I give up.
