### ISSUE TITLE
IBM5150 - size property

### ISSUE THREAD

**Issue by ArcadeShadow** [mamedev/mame#6876]
In some games the size property in the Floppy tag isn't the same of the size property in the Rom tag.
There are 2 games, like this ("centiped", "mspacman"). Is it normal or not?
As you can see below:

	<software name="centiped">
		<description>Centipede</description>
		<year>1983</year>
		<publisher>Atarisoft</publisher>
		<info name="usage" value="PC Booter" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" **size="1049469"**>
				<rom name="centipede.mfm" **size="1011265"** crc="29332053" sha1="d34519a6cd21ac50ada1d78b28be138e77128635"/>
			</dataarea>
		</part>
	</software>

**Comment by rzero9** [comment]
This is just me being lazy with copy-pasting stuff, it should be the same. I have submitted a PR to fix it.

**Comment by angelosa** [comment]
Safe to assume it has been addressed by linked PR, closed.
