### ISSUE TITLE
rf5c400: Loop position is not being calculated correctly

### ISSUE THREAD

**Issue by zniqco** [mamedev/mame#6883]
In [rf5c400.cpp:301](https://github.com/mamedev/mame/blob/1b3322edc39ee2f0d9f8f233f7887c3f1d9501a6/src/devices/sound/rf5c400.cpp#L301),

```
			if ((pos>>16) > end)
			{
				pos -= loop<<16;
				pos &= 0xFFFFFF0000U;
			}
```
The upper bit is lost in the process of << 16 of the uint32_t loop (has 24-bit value)
I think the loop variable should be cast as uint64_t

This issue can be seen on the song selection screen of bmiidx8.

**Comment by zniqco** [comment]
@cam900 After this modification was applied, there was a problem with the sound of the play did not stop.
The end and loop values seem to be being calculated incorrectly.

**Comment by cam900** [comment]
Fixed in https://github.com/mamedev/mame/pull/6889.
