### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [mamedev/mame#691]
I would like to point out that identifiers like "[`__ATOM_DSK_H__`](https://github.com/mamedev/mame/blob/39f3243a201e77c11917a71a0f426bfe09a78a6a/src/lib/formats/atom_dsk.h#L3)" and "[`__CBM_CRT__`](https://github.com/mamedev/mame/blob/73b44c94291c4d086477167a76fd7db239936c3b/src/lib/formats/cbm_crt.h#L13)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by cuavas** [comment]
Yes we realise any name containing two successive underscores is reserved. But I think we have bigger things to worry about than this.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by cuavas** [comment]
MAME depends on undefined behaviour all over the place.  In fact the CPU cores heavily depend on twos-complement signed integer overflow and the results of right-shifting signed integers.  If you look at src/emu/validity.cpp you'll see tests for actual compiler behaviour for a number of behaviours that MAME depends on which are undefined by the C/C++ standards.  Using macros with __ in them as #include guards is a far lesser sin than some of the other things we do out of necessity, and if it's going to break something, we'll probably notice very quickly.

That said, if you want to create a pull request replacing these macros with the form MAME_LIB_FORMATS_ATOM_DSK_H and MAME_LIB_FORMATS_CBM_CRT_H, feel free.  It will probably be accepted if it's done cleanly and consistently.

**Comment by rb6502** [comment]
I'd argue that include guards are no longer necessary since we have a strict compiler check which enforces compilers which support #pragma once.  I would accept a clean patch that replaced them with that no problem.

**Comment by elfring** [comment]
Do you care for standard compliance more than [using such a pragma](http://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#23699893 "Is #pragma once part of the C++11 standard?")?

**Comment by cuavas** [comment]
You're not being constructive.

**Comment by elfring** [comment]
Have you got any preferences for the name pattern of safer include guards?
