### ISSUE TITLE
Number of floppy disk drives is limited to 2 on CoCo Emulation should be 4 floppy drives

### ISSUE THREAD

**Issue by nowhereman999** [mamedev/mame#692]
I'm not sure when this changed, it used to be that you could use 4 drives with mame/mess (that is how a real coco works) with any coco1, coco2 or coco3 with the coco_fdc (floppy disk controller ROM).  I looked through the sourcecode in src/devices/bus/coco/coco_fdc.cpp and the code still shows it can handle 4 disk drives (drives 0-3).

But when you try to run mame with option -flop3 you get message Error: unknown option: -flop3 same with option -flop4 you get message Error: unknown option: -flop4.

I don't know where in the source code the number of floppy drives is set for a particular emulated computer.

Please change it back to 4 for the CoCo 1, CoCo 2 & CoCo 3.

Thanks,
Nowhereman999

**Comment by startaq** [comment]
The driver still supports 4 floppy drives, it's just that by default only two are attached. If you need more, you can attach them with the slot system like this:

`mame coco -ext fdc -ext:fdc:wd17xx:2 qd` (to attach floppy drive 3)

You can use the `-listslots` option to list the available options.

**Comment by nowhereman999** [comment]
Wow that was fast, thanks for the quick response.  I tried to figure this out looking through the code for the last 2 hours.  I see mame has changed quite a bit since I last used it about a year ago.

Now I can go play with my Raspberry Pi or should I say CoCo Pi.  :)

Cheers,
Nowhereman999
