### ISSUE TITLE
Portname script information for documentation

### ISSUE THREAD

**Issue by Firehawke** [mamedev/mame#6925]
@cracyc 

I've started doing some research for documentation for the plugins that come with MAME.

As such, I need some information about your portname Lua script. It says it reads .json files named for the system name; where are these .json files to be stored, and where does a user get them?

**Comment by cracyc** [comment]
It's put in <ctrlrpath>/portname or portname.zip if they are zipped up.  You can find some work in progress at https://github.com/RalfVB/mame-portnames/tree/hexmask/portname

**Comment by Firehawke** [comment]
Okay, I see how this works. Not sure if Vas wants us linking to outside resources that may or may not be present in the long term, so I probably won't be able to tell people where to get the data but I can explain how to generate entries for themselves and how to use it in general.
