### ISSUE TITLE
makefile doesn't build the tools after compiling MAME

### ISSUE THREAD

**Issue by nowhereman999** [mamedev/mame#693]
I just compiled the latest MAME version here then I wanted to make the TOOLS (imgtool, floptool,...)  to use with computer emulation but using the command "make -j4 TOOLS=1" doesn't make the tools, either does the command "make -j4 TARGET=mame TOOLS=1" All that happens is it shows the GCC version waits a few seconds and ends without doing anything.

It did work is I used "make -j4 SUBTARGET=mess TOOLS=1" but since MAME already includes all of MESS's features I don't see why it should force you to make both MAME and MESS if you want to do some computer emulation and also emulate some arcade machines you only need MAME.

I had to edit the makefile and remove the '#" symbol in front of the line # TOOLS = 1
Then I did a "make -j4" and it built all the TOOLS.

FYI - This is from my Raspberry Pi 2, but I think it would be the same with any GCC 4.9 environment.

Thanks for all the awesome work on MAME!  It is amazing, you all rock.  :)

**Comment by rb6502** [comment]
There's general agreement that making tools a target instead of a feature of other targets makes a lot more sense.  I don't know if it'll happen though.

Also, it's important that if you make from non-clean and change anything about the build, you include REGENIE=1 to regenerate the makefiles.
