### ISSUE TITLE
[mac.cpp] Floppy drive emulation errata

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [mamedev/mame#6955]
Actually, **macclas2** became the final machine to ever have support for an external floppy drive through the 19-pin D-sub connector.
Furthermore, **macse**, **macsefdhd**, **macprtb** and **maclc** were the only 4 machines that supported up to a staggering 3 floppy drives!

**Comment by MooglyGuy** [comment]
ok

**Comment by cuavas** [comment]
That isn’t true.  SCSI floppy drives were available for later Macs that lacked the 19-pin D-sub connector, and USB floppy drives are still supported for MFM formats.

**Comment by CRTRevivalDreamer** [comment]
Alright! I updated the opening post.

**Comment by rb6502** [comment]
I don't understand the point of this issue.
