### ISSUE TITLE
ROM auditing creates incorrect dependencies on some clones for clean/complete parent roms

### ISSUE THREAD

**Issue by DontCallMeDave** [mamedev/mame#6981]
I like my roms split, not merged.

For certain parent roms in MAMEUI64 v.222 **that successfully pass individual auditing**, I get errors related to bad/missing files for their unavailable and unwanted clones when I choose **Audit existing sets**.  If I have a good, working parent, shouldn't **Audit existing sets** skip unavailable clones?

Some of these errors (for example, punchita) are *at least* two years old. The errors for pettanp and shinoblda are new to me for the upgrade from v.216 to v.222.

aliensyn (clean parent)
Clone errors:
	aliensyn2   : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759) FOUND: CRC(49e882e5)
	aliensyn3   : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759) FOUND: CRC(49e882e5)
	aliensyn5   : 317-0037.key (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759) FOUND: CRC(49e882e5)
	aliensynj   : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759) FOUND: CRC(49e882e5)
	aliensynjo  : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759) FOUND: CRC(49e882e5)

banbam (clean parent)
Clone errors:
	pettanp     : tvg2-16a.7 (16384 bytes) - NOT FOUND
	pettanp     : tvg3-16a.8 (8192 bytes) - NOT FOUND
	pettanp     : tvg4-16a.9 (8192 bytes) - NOT FOUND
	pettanp     : tvg5-16a.10 (8192 bytes) - NOT FOUND
	pettanp     : tvg6-16.90 (8192 bytes) - NOT FOUND
	pettanp     : tvg7-16.92 (8192 bytes) - NOT FOUND
	pettanp     : tvg8-16.94 (8192 bytes) - NOT FOUND
	pettanp     : tvg11-16.102 (8192 bytes) - NOT FOUND
	pettanp     : tvg10-16.101 (8192 bytes) - NOT FOUND
	pettanp     : tvg9-16.100 (8192 bytes) - NOT FOUND
	pettanp     : tvg12-16.2 (4096 bytes) - NOT FOUND

monymony (clean parent)
Clone errors:
	monymony2   : cpu1.1a (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(907225b2) SHA1(88955d21deee8364e391413c8e59361ca5f7e534) FOUND: CRC(13c227ca)
	monymony2   : cpu3.1c (8192 bytes) - INCORRECT

nibbler (clean parent)
Clone errors:
	nibbler7    : ic12 (4096 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(8685d060) SHA1(64b10f9afc9ca97db7b4f7784da0df1574a56919) FOUND: CRC(ac6a802b)
	nibbler7    : ic7 (4096 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(b07195c7) SHA1(7aeccb274eb83aa9c24ccd1e72c694f316d25c4d) FOUND: CRC(35971364)
	nibbler7    : ic8 (4096 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(61034cca) SHA1(8aa06784afe60b7ce9c1ea1c27685610fa9104cf) FOUND: CRC(6b33b806)
	nibbler7    : ic14 (4096 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(7a87c766) SHA1(8660cf78de7a4e2aec178155d2941094a3978ba3) FOUND: CRC(063f05cc)

punchout (clean parent)
Clone errors:
	punchita    : chp1-c.8l (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(1d595ce2) SHA1(affd43bef96c68f953e66cfa14ad4e9c304dc022)  FOUND: CRC(a4003adc)
	punchita    : chp1-c.8k (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(c062fa5c) SHA1(8ebd6fd76f1fd1b85216a4e21d8a13be8317b9e2)  FOUND: CRC(745ecf40)
	punchita    : chp1-c.8j (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(48d453ef) SHA1(145f3ace8bec87e83b64c6472e2b71f1ebea13ea)  FOUND: CRC(7a7f870e)
	punchita    : chp1-c.8h (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(67f5aedc) SHA1(c63a8b0696eec87bb147d435c18ee7e26d19e2a4)  FOUND: CRC(5d8123d7)
	punchita    : chp1-c.8f (16384 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(761de4f3) SHA1(66754bc762c14fea620fabf408f85e6e3acb89ad)  FOUND: CRC(c8a55ddb)
	punchita    : chp1-b.4c (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(9a9ff1d3) SHA1(d91adf69acb717f238cd5954909701a8748f2185)  FOUND: CRC(49b763bc)
	punchita    : chp1-b.4d (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(4c23350f) SHA1(70a76002db9209699cdf1f092b2b5ef32d0b7b75)  FOUND: CRC(08bc6d67)
	punchouta   : chp1-b.4c (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(e26dc8b3) SHA1(a704d39ef6f5cbad64a478e5c109b18aae427cbc)  FOUND: CRC(49b763bc)
	punchouta   : chp1-b.4d (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(dd1310ca) SHA1(918d2eda000244b692f1da7ac57d7a0edaef95fb)  FOUND: CRC(08bc6d67)
	punchouta   : chp1-b.4a (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(20fb4829) SHA1(9f0ce9379eb31c19bfacdc514ac6a28aa4217cbb)  FOUND: CRC(c075f831)
	punchouta   : chp1-b.4b (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(edc34594) SHA1(fbb4a8b979d60b183dc23bdbb7425100b9325287)  FOUND: CRC(c4cc2b5a)
	punchouta   : chp1-v.6p (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(16588f7a) SHA1(1aeaaa5cc2477c3aa4bf80df7d9474cc9ded9f15)  FOUND: CRC(75be7aae)
	punchouta   : chp1-v.6n (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(dc743674) SHA1(660582c76ee68a7267d5686a2f8ea0fd6c2b25fc)  FOUND: CRC(daf74de0)
	punchouta   : chp1-v.8p (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(c2db5b4e) SHA1(39d009af597fa28d34af31aec111aa6fe09fea39)  FOUND: CRC(4cb7ea82)
	punchouta   : chp1-v.8n (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(e6af390e) SHA1(73984cbdc8fbf667126ada63ab9500609eb25c61)  FOUND: CRC(1c0d09aa)

quartet (basically clean parent, with the following unrelated 'no good dump known' errors)
315-5147.pal16r6a.23g (260 bytes) - NO GOOD DUMP KNOWN
315-5143.pal16r6a.24g (260 bytes) - NO GOOD DUMP KNOWN

Clone errors:
	quarteta    : epr-7458.9b (32768 bytes) - NOT FOUND
	quarteta    : epr-7455.6b (32768 bytes) - NOT FOUND
	quarteta    : epr-7459.10b (32768 bytes) - NOT FOUND
	quarteta    : epr-7456.7b (32768 bytes) - NOT FOUND

shinobi (clean parent)
Clone errors:
	shinoblda   : 12.bin (65536 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(68c91fd5) SHA1(54dc1d26711c73b30cbb5387dde27ba21cc102f4) FOUND: CRC(757a0c71)
	shinoblda   : 14.bin (65536 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(9e887c80) SHA1(798a3dc499ef14b362bc37ff91b247e367f42ab9) FOUND: CRC(a65870b2)
	shinobldb   : sh1.ic6 (65536 bytes) - NOT FOUND
	shinobldb   : sh2.ic3 (65536 bytes) - NOT FOUND

wb3 (basically clean parent, with the following unrelated 'no good dump known' error)
317-0098.c2 (4096 bytes) - NOT FOUND - NO GOOD DUMP KNOWN

Clone errors:
	wb31d       : bootleg_epr12084.bin (65536 bytes) - NOT FOUND
	wb31d       : bootleg_epr12082.bin (65536 bytes) - NOT FOUND
	wb35        : 317-0086.key (8192 bytes) - INCORRECT CHECKSUM: EXPECTED: CRC(5b8e7076) SHA1(387d6446266c32668a5182f825bb60b059d67f10) BAD_DUMP FOUND: CRC(ec480b80)
	wb35d       : bootleg_epr-12120.43 (65536 bytes) - NOT FOUND
	wb35d       : bootleg_epr-12118.26 (65536 bytes) - NOT FOUND

Is there a way to incorporate these requirements into the parent roms if they are truly required, or fix **Audit existing sets** to ignore these missing clones?

**Comment by Robbbert** [comment]
MAMEUI is not MAME and is unsupported here. You must check your findings with MAME.
