### ISSUE TITLE
ROM auditing creates incorrect dependencies on some clones for clean/complete parent roms - Mark II

### ISSUE THREAD

**Issue by DontCallMeDave** [mamedev/mame#6985]
My original issue #6981 was closed because I mentioned MAMEUI. This time, I downloaded MAME64 v.222, copied only the following roms into the roms folder:

aliensyn
banbam
monymony
nibbler
punchout
quartet
shinobi
wb3

Note that these are split roms, not merged.

The output of `mame64 -verifyroms` is in the attached file: [_mame64v222_output.txt](https://github.com/mamedev/mame/files/4961094/_mame64v222_output.txt)

The results are exactly the same as I described in the other issue: the parent is good, but MAME is squawking about clones that aren't present as bad, which it shouldn't do, because those roms aren't present.

As I stated in the other issue, some of these errors (for example, punchita) are at least two years old as I remember. The errors for pettanp and shinoblda are new to me for the upgrade from v.216 to v.222.

These are the relevant highlights from the attached text file:

```
romset aliensyn is good
aliensyn2   : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759)
   FOUND: CRC(49e882e5)
romset aliensyn2 [aliensyn] is bad
aliensyn3   : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759)
   FOUND: CRC(49e882e5)
romset aliensyn3 [aliensyn] is bad
aliensyn5   : 317-0037.key (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759)
   FOUND: CRC(49e882e5)
romset aliensyn5 [aliensyn] is bad
aliensynj   : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759)
   FOUND: CRC(49e882e5)
romset aliensynj [aliensyn] is bad
aliensynjo  : 317-0033.key (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(68bb7745) SHA1(f0c60d8a503a90ba6a2443be856b18322e3ec759)
   FOUND: CRC(49e882e5)
romset aliensynjo [aliensyn] is bad

romset banbam is good
... [had to skip way down in the output]
pettanp     : tvg2-16a.7 (16384 bytes) - NOT FOUND
pettanp     : tvg3-16a.8 (8192 bytes) - NOT FOUND
pettanp     : tvg4-16a.9 (8192 bytes) - NOT FOUND
pettanp     : tvg5-16a.10 (8192 bytes) - NOT FOUND
pettanp     : tvg6-16.90 (8192 bytes) - NOT FOUND
pettanp     : tvg7-16.92 (8192 bytes) - NOT FOUND
pettanp     : tvg8-16.94 (8192 bytes) - NOT FOUND
pettanp     : tvg11-16.102 (8192 bytes) - NOT FOUND
pettanp     : tvg10-16.101 (8192 bytes) - NOT FOUND
pettanp     : tvg9-16.100 (8192 bytes) - NOT FOUND
pettanp     : tvg12-16.2 (4096 bytes) - NOT FOUND
pettanp     : sun-8212.ic3 (2048 bytes) - NO GOOD DUMP KNOWN
romset pettanp [banbam] is bad

romset monymony is good
monymony2   : cpu1.1a (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(907225b2) SHA1(88955d21deee8364e391413c8e59361ca5f7e534)
   FOUND: CRC(13c227ca)
monymony2   : cpu3.1c (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(3c874c16) SHA1(5607475638c3c313a8150aaa0e3b653226c2442a)
   FOUND: CRC(6aea9c01)
romset monymony2 [monymony] is bad

romset nibbler is good
romset nibbler6 [nibbler] is good
nibbler7    : ic12 (4096 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(8685d060) SHA1(64b10f9afc9ca97db7b4f7784da0df1574a56919)
   FOUND: CRC(ac6a802b)
nibbler7    : ic7 (4096 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(b07195c7) SHA1(7aeccb274eb83aa9c24ccd1e72c694f316d25c4d)
   FOUND: CRC(35971364)
nibbler7    : ic8 (4096 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(61034cca) SHA1(8aa06784afe60b7ce9c1ea1c27685610fa9104cf)
   FOUND: CRC(6b33b806)
nibbler7    : ic14 (4096 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(7a87c766) SHA1(8660cf78de7a4e2aec178155d2941094a3978ba3)
   FOUND: CRC(063f05cc)
romset nibbler7 [nibbler] is bad

punchita    : chp1-c.8l (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(1d595ce2) SHA1(affd43bef96c68f953e66cfa14ad4e9c304dc022)
   FOUND: CRC(a4003adc)
punchita    : chp1-c.8k (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(c062fa5c) SHA1(8ebd6fd76f1fd1b85216a4e21d8a13be8317b9e2)
   FOUND: CRC(745ecf40)
punchita    : chp1-c.8j (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(48d453ef) SHA1(145f3ace8bec87e83b64c6472e2b71f1ebea13ea)
   FOUND: CRC(7a7f870e)
punchita    : chp1-c.8h (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(67f5aedc) SHA1(c63a8b0696eec87bb147d435c18ee7e26d19e2a4)
   FOUND: CRC(5d8123d7)
punchita    : chp1-c.8f (16384 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(761de4f3) SHA1(66754bc762c14fea620fabf408f85e6e3acb89ad)
   FOUND: CRC(c8a55ddb)
punchita    : chp1-b.4c (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(9a9ff1d3) SHA1(d91adf69acb717f238cd5954909701a8748f2185)
   FOUND: CRC(49b763bc)
punchita    : chp1-b.4d (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(4c23350f) SHA1(70a76002db9209699cdf1f092b2b5ef32d0b7b75)
   FOUND: CRC(08bc6d67)
romset punchita [punchout] is bad
romset punchout is good
punchouta   : chp1-b.4c (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(e26dc8b3) SHA1(a704d39ef6f5cbad64a478e5c109b18aae427cbc)
   FOUND: CRC(49b763bc)
punchouta   : chp1-b.4d (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(dd1310ca) SHA1(918d2eda000244b692f1da7ac57d7a0edaef95fb)
   FOUND: CRC(08bc6d67)
punchouta   : chp1-b.4a (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(20fb4829) SHA1(9f0ce9379eb31c19bfacdc514ac6a28aa4217cbb)
   FOUND: CRC(c075f831)
punchouta   : chp1-b.4b (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(edc34594) SHA1(fbb4a8b979d60b183dc23bdbb7425100b9325287)
   FOUND: CRC(c4cc2b5a)
punchouta   : chp1-v.6p (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(16588f7a) SHA1(1aeaaa5cc2477c3aa4bf80df7d9474cc9ded9f15)
   FOUND: CRC(75be7aae)
punchouta   : chp1-v.6n (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(dc743674) SHA1(660582c76ee68a7267d5686a2f8ea0fd6c2b25fc)
   FOUND: CRC(daf74de0)
punchouta   : chp1-v.8p (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(c2db5b4e) SHA1(39d009af597fa28d34af31aec111aa6fe09fea39)
   FOUND: CRC(4cb7ea82)
punchouta   : chp1-v.8n (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(e6af390e) SHA1(73984cbdc8fbf667126ada63ab9500609eb25c61)
   FOUND: CRC(1c0d09aa)
romset punchouta [punchout] is bad

quartet     : 315-5147.pal16r6a.23g (260 bytes) - NO GOOD DUMP KNOWN
quartet     : 315-5143.pal16r6a.24g (260 bytes) - NO GOOD DUMP KNOWN
romset quartet is best available
quarteta    : epr-7458.9b (32768 bytes) - NOT FOUND
quarteta    : epr-7455.6b (32768 bytes) - NOT FOUND
quarteta    : epr-7459.10b (32768 bytes) - NOT FOUND
quarteta    : epr-7456.7b (32768 bytes) - NOT FOUND
quarteta    : 315-5147.pal16r6a.23g (260 bytes) - NO GOOD DUMP KNOWN
quarteta    : 315-5143.pal16r6a.24g (260 bytes) - NO GOOD DUMP KNOWN
romset quarteta [quartet] is bad

romset shinobi is good
romset shinobi2 [shinobi] is good
romset shinobi2d [shinobi] is good
romset shinobi3 [shinobi] is good
romset shinobi4 [shinobi] is good
romset shinobi5 [shinobi] is good
romset shinobi6 [shinobi] is good
romset shinobld [shinobi] is good
shinoblda   : 12.bin (65536 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(68c91fd5) SHA1(54dc1d26711c73b30cbb5387dde27ba21cc102f4)
   FOUND: CRC(757a0c71)
shinoblda   : 14.bin (65536 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(9e887c80) SHA1(798a3dc499ef14b362bc37ff91b247e367f42ab9)
   FOUND: CRC(a65870b2)
romset shinoblda [shinobi] is bad
shinobldb   : sh1.ic6 (65536 bytes) - NOT FOUND
shinobldb   : sh2.ic3 (65536 bytes) - NOT FOUND
romset shinobldb [shinobi] is bad

wb3         : 317-0098.c2 (4096 bytes) - NOT FOUND - NO GOOD DUMP KNOWN
romset wb3 is best available
romset wb31 [wb3] is good
wb31d       : bootleg_epr12084.bin (65536 bytes) - NOT FOUND
wb31d       : bootleg_epr12082.bin (65536 bytes) - NOT FOUND
romset wb31d [wb3] is bad
wb35        : 317-0086.key (8192 bytes) - INCORRECT CHECKSUM:
EXPECTED: CRC(5b8e7076) SHA1(387d6446266c32668a5182f825bb60b059d67f10) BAD_DUMP
   FOUND: CRC(ec480b80)
romset wb35 [wb3] is bad
wb35d       : bootleg_epr-12120.43 (65536 bytes) - NOT FOUND
wb35d       : bootleg_epr-12118.26 (65536 bytes) - NOT FOUND
romset wb35d [wb3] is bad
wb3bble     : d8749h.mcu (4096 bytes) - NOT FOUND - NO GOOD DUMP KNOWN
romset wb3bble [wb3] is best available
```

**Comment by Tafoid** [comment]
https://mametesters.org/view.php?id=5556

Such inconsistencies have been logged.  It is complicated by machines and/or devices which operate without any need of rom data (no bioses, etc).  MAME is unique in that it tries to determine if you intended to have a romset or not and doesn't want to encourage people to obtain romsets just because they are there.  Detection is known not to be 100% perfect, sadly, and obtaining this is not as easy as it sounds.

**Comment by DontCallMeDave** [comment]
@Tafoid, thanks for the response. I realize this is more of a nuisance than a burning issue, but it would sure be great if these issues could be fixed, although after 6 years on some of these, I realize it's not likely. If I had the slightest shred of coding ability, I would try to fix it myself, but alas, I'm dependent on the charity of others.

**Comment by cuavas** [comment]
For the first case, you have a bad file in your `aliensyn` ROM set.  You have a file called `317-0033.key` with CRC `49e882e5` which is not part of the `aliensyn` ROM set at all.  The presence of this file is causing MAME to detect a merged clone with a bad ROM.

In the second case, the clone `pettanp` has a ROM with an identical label to one in the parent `banbam` but with a no dump flag.  MAME finds a ROM with the correct name for the clone set but can’t verify the contents, so it reports an error.  I can probably add a heuristic to detect this and suppress the report, but this is a cosmetic issue, so it’s not going to be high priority.

The third one is a similar situation.  The clone has identically labelled ROMs with different content.  Once again, suppressing it is possible, but not high priority.

I haven’t checked the other ones, but they look like more cases of the same thing.

**Comment by DontCallMeDave** [comment]
@cuavas, interesting. I never thought to check the existing parent ROMS since they validated.

I got new/fresh 0.222 versions of the following ROMs. These are the only ROMs in my \roms folder:

aliensyn.zip
banbam.zip
monymony.zip
nibbler.zip
punchout.zip
quartet.zip
shinobi.zip
spnchout.zip
wb3.zip

I re-ran `mame64 -verifyroms` the results are attached and are quite similar.
[_mame64v222_output_rev2.txt](https://github.com/mamedev/mame/files/5037765/_mame64v222_output_rev2.txt)

 For `aliensyn` the offending '317-0033.key' file is no longer present, yet the audit is still complaining about missing clones. There seems to be more going on.

Thanks.

**Comment by Shoegzer** [comment]
I've also encountered some strange issues with mame -verifyroms:
```
$ ./mame64 -verifyroms spectrum_kempcentreu
romset spectrum_kempcentref is good
1 romsets found, 1 were OK.

$ ./mame64 -verifyroms spectrum_swiftdisc2
romset spectrum_swiftdisc is good
1 romsets found, 1 were OK.
```
Other device roms report the correct name.  

Using mame64 0.223 self-compiled on linux kernel 5.4 using gcc 9.3.0

**Comment by Shoegzer** [comment]
Thanks for looking into this @smf- .  The issue reported above no longer exists.

However, as an update for 0.224, the following sets aren't audited properly, I assume due to the fact that they represent machines which have nodump main roms but have devices attached which the machine expects:

d2k300axp
d2k500axp
nshrz
nshrz2mhz
sarpc

Using mame64 0.224 self-compiled on linux kernel 5.4 using gcc 9.3.0

**Comment by cuavas** [comment]
This should be resolved as of 0f6a1cec4adb9c59f323c4608f1a7b7a81eaaa79

**Comment by Tafoid** [comment]
Reopened per request

**Comment by Shoegzer** [comment]
Thanks @Tafoid .  Unfortunately the issue reported above is back in 0.226.  Specifically, the romsets **nshrz2mhz** and **sarpc** include "NO DUMP" roms exclusively and are not audited properly.

On a related note, the romsets **ng_mv1f** and **ng_mv1fz** will not rebuild (using qmc2's rebuilder - here's the [log](https://pastebin.com/AcMSKfXe) in case it helps) and are also reported as "not found" by both qmc2 and mame -verifyroms.  Note these are the only romsets that won't rebuild and qmc2 has not had problems rebuilding sets before now.  MAME launches these sets without complaining, likely due to the fact that they are clones of the neogeo romset which is fully intact.  Perhaps qmc2 is confused by something new with the mame audit process, so please disregard if this is a qmc2 issue rather than mame.

**Comment by cuavas** [comment]
It's impossible to do what toy want without preventing systems from being launched from the built-in UI. We had one release go out where it was impossible to launch snes and fds from the internal UI. That's unacceptable.
