### ISSUE TITLE
MAME debugger feature requests

### ISSUE THREAD

**Issue by ScottTunstall** [mamedev/mame#7034]
Hi,

I have some more feature requests that would make reverse engineering old games a bit quicker.

Would it be possible to implement the following features:

- [x] Copy (CTRL+C) from debugger console history?

I know there is an undocumented CONDUMP command (I looked @ the MAME source) but this would be faster.

- [x] Copy assembly code from diassembly window and be able to paste into a document? 

With my reverse engineering work, I discover code is actually data and vice versa. It would be good if, instead of me using the dasm command all the time to create a file I copy and paste from, I could just copy and paste the text verbatim from the MAME disassembly window. It would literally save me hours!

- [x] Copy bytes from memory window, with specified bytes per line in clipboard.  This is what I'd like to see:

Say I used CTRL+O and CTRL+P to size the memory window to 8 bytes per line. When I copy and paste from it, the text pasted will contain the address of each line and 8 bytes as hex, e.g. copying 2 rows of 8 bytes per row from memory address 1234 would result in:
  
1234: 01 02 03 04 05 06 07 08
123C: 09 0A 0B 0C 0D 0E 0F 10

The DUMP command doesn't let me specify bytes per line and its tedious having to format the output manually.

If anyone could look at these requests, that would be fantastic. I'd be a very happy man! Thanks very much in advance.

Scott

**Comment by ajrhacker** [comment]
> The DUMP command doesn't let me specify bytes per line

It actually does through the optional fifth argument I added a while ago.

**Comment by ScottTunstall** [comment]
For dump's help text it says the following: 

dump[{d|i}] <filename>,<address>,<length>[,<size>[,<ascii>[,<CPU>]]]

It doesn't mention rowSize, so I took a look at the MAME source and yeah it's there. Excellent :) 

if I substitute 9 for "CPU" parameter and "0" afterwards (which I see is new CPU param position?) then it dumps 9 bytes per line. Good work!

**Comment by stilett0** [comment]
@cuavas - Partially or completely addressed by https://github.com/mamedev/mame/commit/83c9637635c575972c039d7d63a48d788e41ba34 etc. in MAME 0.229?

**Comment by cuavas** [comment]
Well, besides the help for the dump command apparently being out-of-sync with the actual argument syntax, it’s addressed.

**Comment by cuavas** [comment]
Actually, looking at the code, I’m not sure you can control bytes-per-line with `dump`, only bytes-per-chunk.

**Comment by jotego** [comment]
I'd like to see the feature to copy text too. It would be very useful to be able to select text from the output window and copy it for analysis in other tools.

**Comment by cuavas** [comment]
> I'd like to see the feature to copy text too. It would be very useful to be able to select text from the output window and copy it for analysis in other tools.

 You can already do that: right--click and choose "copy visible" from the context menu.

**Comment by cuavas** [comment]
All of these have been addressed.  You can right-click views and copy the visible content, which includes console history.
