### ISSUE TITLE
mametiny build should be made more representative

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#7037]
In the process of updating Fedora package to 0.223 I have noticed that s390x and aarch64 builds are broken by asmjit. I thought that my previous Travis CI PR would have caught that, but it appears that no drivers using the DRC are actually built as a part of tiny build which is what is being used for CI. Could the tiny build be overhauled to include DRC?

**Comment by cuavas** [comment]
The `tiny` subtarget contains a set of drivers where MAMEdev has rights to distribute ROMs for personal use, and/or where the rights holders have released the ROMs freely for personal use.  I’m open to the possibility of creating a different subtarget for CI builds, but `tiny` and `virtual` should not change.

**Comment by belegdol** [comment]
I did not know that, thank you for clarifying. I will start by just adding one drc needing driver to the list used by tiny build. Hopefully this will not cause the build times to degrade beyond the allowed timeouts.

**Comment by cuavas** [comment]
Please do not change the list of drivers in the `tiny` subtarget.

**Comment by belegdol** [comment]
I should have expressed myself differently, sorry for misunderstanding: I will submit a new ci target which would be tiny + one drc driver as a starting point.
