### ISSUE TITLE
Unable to build using emscripten – asmjs_x86_clang error

### ISSUE THREAD

**Issue by robhawkes** [mamedev/mame#704]
I'm trying to create a Dragon build using emscripten but I keep hitting the following error and I'm unsure how to proceed in regards to debugging it and ideally fixing it / avoiding it all together. I'm able to replicate this on 2 separate machines.

I see the same error when trying to build using other drivers too, like the pacman driver [in the emscripten mame docs](https://raw.githubusercontent.com/mamedev/mame/master/docs/emscripten.txt).

I am able to build the Dragon driver successfully on OSX without using emscripten.

Any recommendations on how to proceed?

Versions:
* OSX 10.11.3 (15D21)
* emscripten 1.35.0
* Latest mame clone as of today (b0cfd60)

Process:
* Clone mame
* Install the emscripten SDK [as per the following instructions](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html)
* Run the build command for the Dragon:
```
emmake make SUB_TARGET=dragon32 SOURCES=src/mame/drivers/dragon.cpp
```

Log of build output:

```
$ emmake make SUB_TARGET=dragon32 SOURCES=src/mame/drivers/dragon.cpp
Clang 7.0.2 detected
Creating obj/Release
Creating obj/Release/src/host/lua-5.3.0/src
os_getcwd.c
os_stat.c
os_chdir.c
premake_main.c
os_uuid.c
os_isfile.c
os_ticks.c
os_copyfile.c
scripts.c
string_endswith.c
string_hash.c
os_pathsearch.c
os_rmdir.c
os_match.c
premake.c
os_isdir.c
os_mkdir.c
path_isabsolute.c
os_is64bit.c
ldump.c
lvm.c
ltable.c
lstrlib.c
liolib.c
lcode.c
lparser.c
loadlib.c
lbitlib.c
lzio.c
ldblib.c
lmathlib.c
lfunc.c
lmem.c
lgc.c
lstring.c
linit.c
ltm.c
lapi.c
lctype.c
lstate.c
lbaselib.c
ltablib.c
lauxlib.c
lcorolib.c
llex.c
ldo.c
lundump.c
lopcodes.c
lutf8lib.c
loslib.c
lobject.c
ldebug.c
Creating ../../bin/darwin
Linking genie
make: *** No rule to make target `asmjs_x86_clang', needed by `all'.  Stop.
```

**Comment by robhawkes** [comment]
Ok, so after digging around within the mame `makefile` I realised that the error message was referring to the commands / targets within the `makefile` – specifically, that none existed under the name `asmjs_x86_clang`.

I manually changed [both `asmjs` strings here](https://github.com/mamedev/mame/blob/master/makefile#L1091) to `asmjs_x86_clang` and the build now proceeds.

I doubt this is the right fix (seems like the `_x86_clang` suffix isn't expected for emscripten builds), but it works.

**Comment by robhawkes** [comment]
Can confirm that changing the above succeeded in a working build that I was then able to bundle into the browser using [emularity](https://github.com/db48x/emularity/):

![](http://cl.ly/1z3U0O212o0k/Screen%20Shot%202016-03-10%20at%2013.15.43.png)

**Comment by DopefishJustin** [comment]
Please try again with 7346a874a3a6e6610991bdce9fb10ba645d63816

**Comment by robhawkes** [comment]
Awesome stuff – looks to be fixed now. Thank you for looking at it so quickly!
