### ISSUE TITLE
How to debug emscripten builds?

### ISSUE THREAD

**Issue by kevzettler** [mamedev/mame#7044]
I'm trying to get an emscripten build working in browser. I am following the guide at https://docs.mamedev.org/initialsetup/compilingmame.html#emscripten-javascript-and-html

I have the pacmantest example compiled with
`emmake make SUBTARGET=pacmantest SOURCES=src/mame/drivers/pacman.cpp`

I have this included in a browser page and loading. Once loaded it throws a javascript exception:

```
src.9caef6c7.js:31844 exception thrown: 8710264
printErr @ src.9caef6c7.js:31844
:1234/pacmantest/mamepacmantest.js:1 Uncaught 8710264
```

The error is not very helpful with the obfuscated and minimized js code.

at this point I would try to recompile with the `emcc` debugging flags like `-g4 ASSERTIONS=1 DEMANGLE_SUPPORT=1`

how can I pass these flags in to the existing build chain?

Any ideas on the exception would be much appreciated as well

**Comment by DopefishJustin** [comment]
You can pass flags to emcc with the ARCHOPTS variable:

`emmake make SUBTARGET=pacmantest SOURCES=src/mame/drivers/pacman.cpp SYMBOLS=1 SYMLEVEL=4 ARCHOPTS="-s ASSERTIONS=1 -s DEMANGLE_SUPPORT=1" REGENIE=1`

**Comment by DopefishJustin** [comment]
My first guess on the exception would be that your browser page is not loading the pacman.zip ROM file in a place where MAME can see it. I would recommend using [Emularity](https://github.com/db48x/emularity) as building your own loader is somewhat involved.

**Comment by kevzettler** [comment]
thank you @DopefishJustin .

I am aware of Emularity and basing my work on it. Emularity is missing functionality that I want, its not actively maintained and the code doesn't follow best practices and is hard to extend. The majority of Emularitys convince is actually from the browserfs filesystem it creates. I have that replicated in my project and can mount zip files. However i'm not sure at which path mame would be looking for these rom files. If you could point me to where in the code or documentation I can find what file path the roms should be at that would be very helpful. 

I'm happy to make PR's to update docs on all this as well.

**Comment by DopefishJustin** [comment]
By default MAME will look in the "roms" subdirectory of the current working directory, but this can be changed with the `-rompath` parameter: https://docs.mamedev.org/commandline/commandline-all.html#core-search-path-options

Feel free to stop by #jsmess on EFNet as well.

**Comment by kevzettler** [comment]
ty @DopefishJustin I was able to fix the paths to the ROM files and get it running

**Comment by oulianov** [comment]
Hello @kevzettler, I'm also building MAME with emscripten and I have issues with roms folder. Do you remember what was your issue and what you did to solve it ?
