### ISSUE TITLE
Trademark incompatiblilty with some free software distrobutions

### ISSUE THREAD

**Issue by g4jc** [mamedev/mame#705]
Hello,
Currently, it is not possible to include MAME in fully free distros due to the trademark issue of your name and logo. As you may remember, Mozilla FireFox had to be rebranded as IceWeasel on Debian for similar reasons. https://en.wikipedia.org/wiki/Iceweasel

If possible please consider releasing the logo and name from trademark so that it will be fully compatible with free distributions. (e.g. Debian and others.)
https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses
https://www.gnu.org/prep/standards/html_node/Trademarks.html

Thank you for all your hard work thus far, and I look forward to seeing MAME packaged into mainline distros in the near future. :)

**Comment by valgrind** [comment]
(I am not a part of, nor do I speak for the Mame project)

Have you asked Debian legal if there is an actual issue with Mame? The problem with Firefox was that Mozilla refused the right for Debian to modify the Browser for the distribution and still call it Firefox.

Example of things that are trademarked that the Debian project have no problem with: Python (both name and logo), MySQL (both name and logo).

Regards,
/Peter Bortas

**Comment by balr0g** [comment]
@g4jc: The fact that the name is trademarked is not what prevents Firefox from being branded that way on Debian. Rather, it is the fact that the requirements for use of the trademarked name require use of the official Firefox artwork, which is not under a free and open source license.
The second link you reference is irrelevant as this project is not part of the GNU organization.

Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=354622#25 and the rest of this thread for details regarding the Firefox/Iceweasel issue.

**Comment by rb6502** [comment]
Yeah, my understanding is that valgrind is right and our current trademark isn't an issue for the DFSG.

**Comment by jmallach** [comment]
This is (as one of the Debian maintainers) my understanding too. Expecting a 0.172 upload to main in the next few days.

**Comment by balr0g** [comment]
In that case I will close this issue. If there are concerns with trademarks or licensing, feel free to contact us and we will work things out.

**Comment by jmallach** [comment]
FWIW, https://ftp-master.debian.org/new/mame_0.172-1.html

As soon as it's processed by the ftp-masters, it'll appear in sid and eventually Debian 9.
