### ISSUE TITLE
chdman -c documentation is lacking

### ISSUE THREAD

**Issue by Cyan4973** [mamedev/mame#7050]
From the `man` page : 

```
--compression, -c none|type1[,type2[,...]]
              Which compression codecs to use (up to 4).
```

There is no place where available `types` are listed. 
Not in the `man` page, not when using `chdman help`.

Circumstantial evidences found in various external sources point to existence of `cdlz`, `cdzl` and `cdfl`, but that's hardly a clean way to find out available options.

**Comment by Firehawke** [comment]
I'll look into this. Thanks for the report.

**Comment by Sanaki** [comment]
Thus far I'm aware of these:
```
cdlz - CD LZMA
cdzl - CD Deflate
cdfl - CD FLAC
lzma - LZMA
zlib - Deflate
huff - Huffman
flac - FLAC
```
The first three are defaults when generating CD CHDs, the next four when generating raw/HDD CHDs. I don't have a laserdisc dump at this time to check those defaults.

**Comment by cuavas** [comment]
It’s documented here now: https://docs.mamedev.org/tools/chdman.html#compression-algorithms

The man page is badly outdated and has been for a long time – unmaintained man pages are a separate issue.  IIRC the man pages were originally contributed by @wallyweek, and no-one has ever kept them up-to-date.
