### ISSUE TITLE
fail build with python3 in linux

### ISSUE THREAD

**Issue by sl1pkn07** [mamedev/mame#706]
in the makefile:

    # PYTHON_EXECUTABLE = python3

but when use it: (in archlinux, python3 is named as python)

```
Converting translation language/Danish/strings.po...
/usr/bin/python scripts/build/msgfmt.py --output-file language/Danish/strings.mo language/Danish/strings.po
  File "scripts/build/msgfmt.py", line 87
    0x950412deL,       # Magic
              ^
SyntaxError: invalid syntax
makefile:1282: recipe for target 'language/Danish/strings.mo' failed
make: *** [language/Danish/strings.mo] Error 1
```

but build all ok if use python2

python(3) is 3.5.1

greetings

**Comment by rb6502** [comment]
Yeah, most of our Python code is dual-compatible but the translation stuff is very new so it hasn't been shook out that way yet.

**Comment by balr0g** [comment]
@sl1pkn07  The Python issue is hopefully fixed in https://github.com/mamedev/mame/commit/9fbc9397817a3da58d7abf435e08a9573a9fc643.

**Comment by sl1pkn07** [comment]
nop, same problem
