### ISSUE TITLE
Autoboot command pointless without ability to play tape

### ISSUE THREAD

**Issue by mcfilmmakers** [mamedev/mame#7061]
MANY of the software lists are unable to take advantage of the autoboot command because the command does not allow for playing the tape and waiting until the tape is loaded to continue input.

Example: Apogee BK-01 requires the user to Type I, followed by Enter, followed by play tape, waiting until the tapeis loaded and then typing G followed by Enter.

Example #2: Amstrad PCW requires the user to type CLOAD followed by ] followed by play tape, waiting untile the tape is loaded and then typing run]

**Comment by cuavas** [comment]
It isn’t useless, but it also isn’t flexible enough to do what you want.  You’d be better off using the Lua scripting functionality.

**Comment by mcfilmmakers** [comment]
The point was that it is useless for those use cases and the mame documentation makes no effort to describe how to use lua to call the play function nor listen to wait for the tape to have loaded.
