### ISSUE TITLE
Pressing any key on an error message does also do an additional action

### ISSUE THREAD

**Issue by Sworddragon** [mamedev/mame#707]
I'm using MAME 0.170 and if I try to start a ROM that is invalid the error message "The selected game is missing one or more required ROM or CHD images. Please select a different game. Press any key to continue.". But on pressing any key besides removing this message the next action will be done. For example on pressing enter the ROM is tried to be loaded again which results that the error message appears again. I think pressing any key at this point should really only remove the error message and nothing more.

**Comment by Tafoid** [comment]
The UI got a major change in 0.171, which is the latest binary.  It is
working fine for games which are not able to load with a clear message what
to do.

**Comment by Robbbert** [comment]
This has been fixed. Closing.
