### ISSUE TITLE
Problems with various CPS games in colors

### ISSUE THREAD

**Issue by ToniBC** [mamedev/mame#7071]
Recently several games of CPS1 and CPS2 are giving graphic problems in certain areas with colors, something that did not happen before.

For example, in the game Magic Sword: Heroic Fantasy, during the intro, when the sword appears, errors are observed that did not occur before.
![msword-200813-132556](https://user-images.githubusercontent.com/45365478/90197171-290de780-ddce-11ea-98dc-76d30e2e2073.png)
![msword-200813-132604](https://user-images.githubusercontent.com/45365478/90197177-2ca16e80-ddce-11ea-9443-7c43e266f98f.png)

On the scoreboard the game also happens.
![msword-200813-132615](https://user-images.githubusercontent.com/45365478/90197184-2f9c5f00-ddce-11ea-930b-bf417032a244.png)

In the game Mega Twins, in the intro there are also several errors.
![mtwins-200813-132326](https://user-images.githubusercontent.com/45365478/90197228-5195e180-ddce-11ea-9e4f-2b43e1f5f303.png)
![mtwins-200813-132337](https://user-images.githubusercontent.com/45365478/90197229-55296880-ddce-11ea-981b-6069d701d149.png)

And in the game Super Street Fighter II: The New Challengers, the same thing happens on the selection screen.
![ssf2-200813-132424](https://user-images.githubusercontent.com/45365478/90197240-5b1f4980-ddce-11ea-93ff-51e041a1ef03.png)

It happens in several other games, some of the CPS 1 and 2 driver was modified and several things fail.

**Comment by happppp** [comment]
Hi,

"something that did not happen before" Did you get a better monitor recently and are noticing it easier with the increased contrast?
Those darkgrey boxes have been in MAME for many years, and it was confirmed to be the same on real CPS1.

**Comment by rb6502** [comment]
Also, those screenshots are through some kind of 2XSAI or similar filter.  We do not accept graphical bug reports when filters are in use.

**Comment by ToniBC** [comment]
Unlike other projects, I see that MAME's are quite unsympathetic as always, seeing those errors that apparently are like that in the original games, the first thing is to criticize and question things as with the first comment almost mocking for having notified something which clearly appears to be a bug.

And then doubt it because of the shaders issue, that reports with applied shaders are not accepted, when by default MAME applies the bilinear “filter / shader”, which is the same and that leaves the whole image blurry.

I understand that, if you use complex CRT shaders, color modification, etc ... and you report something related to the colors caused by the shader, I could understand it, but the graphical errors are always, whether or not you have a shader.

We waste time testing with different versions, trying things, and then report them and what you get are mocking or critical answers, I don't know, you would have to calm down a little and lower your ego a little.

We all try to help within our means, not to be criticized.

A greeting.

**Comment by happppp** [comment]
Why did you claim it did not happen before? Your post doesn't clarify it, it is mostly about your feelings. I can't speak for rb6502, but reading my own post back, I don't see any malice.

**Comment by MooglyGuy** [comment]
Nobody criticized you.

@hap asked if you had acquired a new monitor, with a potentially different color gamut, which would make such errors in the original game more obvious.

@rb6502 pointed out, correctly, that we do not accept bug reports with anything other than no filtering, or the default bilinear stretch which by definition would not induce an error like this.

Nobody here has been unsympathetic, they have been factual, and this is one of the few situations where it would be entirely accurate to point out that the facts do not care about your feelings.

**Comment by MooglyGuy** [comment]
As for being unsympathetic, unsympathetic would be if the comments were locked so that no further whining about how mean and evil the MAME devs are. Which is exactly what I'm going to do now.
