### ISSUE TITLE
MacOs  SDL2 not found

### ISSUE THREAD

**Issue by kevzettler** [mamedev/mame#7076]
I have SDL2 installed with homebrew

at `/usr/local/Cellar/sdl2/2.0.12_1`

```
$ ls /usr/local/Cellar/sdl2/2.0.12_1
COPYING.txt		README.txt		bin			lib
INSTALL_RECEIPT.json	TODO.txt		include			share
```

I have tried variations of `SDL_INSTALL_ROOT` and `SDL_FRAMEWORK_PATH` with no success

like:
`make -j 5 SUBTARGET=arcade REGENIE=1 SDL_INSTALL_ROOT=/usr/local/Cellar/sdl2/2.0.12_1`

The error i'm seeing is:
```
Linking mamearcade64...
ld: framework not found SDL2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../../../../mamearcade64] Error 1
make[1]: *** [mamearcade] Error 2
make: *** [macosx_x64_clang] Error 2
```

**Comment by cuavas** [comment]
Have you set `USE_LIBSDL=1` to make it prefer a UNIX-style library installation over a NeXT-style framework?

**Comment by kevzettler** [comment]
thanks @cuavas that worked
