### ISSUE TITLE
Some ROM's are not detected

### ISSUE THREAD

**Issue by Sworddragon** [mamedev/mame#709]
I'm using MAME 0.170 and trying to test MAME and putting a SNES ROM in the rompath and starting MAME does not cause the ROM to appear in the GUI. Executing "/usr/games/mame -listfull | grep snes" does list the SNES as supported platform.

**Comment by mahlemiut** [comment]
You select the system first (snes or snespal) then the software you wish to use it with.
./mame snes -cart _softlist name or full path to (optionally) zipped ROM_
Through the GUI (0.171 or later) you select the system, then if needed it will let you select a game from the softlist.

**Comment by Sworddragon** [comment]
Ah, this does the trick, thanks for the information. But maybe MAME could also support to autodetect which system the ROM's belong, list them in the GUI and do these steps automatically.

**Comment by rb6502** [comment]
It's not possible to autodetect the system reliably.  Closing this issue.
