### ISSUE TITLE
i recreated brdrline sounds from schematics - but file names in mame don't fit

### ISSUE THREAD

**Issue by beta-tester** [mamedev/mame#7091]
hello,
i recreated Borderline (brdrline) sound files according its (original) schematic in LTSpice.

i used this [Borderline_-_1981_-_Sega.pdf](https://www.gamesdatabase.org/Media/SYSTEM/Arcade/Manual/formated/Borderline_-_1981_-_Sega.pdf) schematic.
the schematic is a little bit buggy (e.g. transistors were swapped)
but the result sounds like I mean to know them from my memory...

now i rebuild the folowing sounds from schematic:
* **ANIMAL-SOUND**, loop + fades out, uses MB4391.
* **CRY-SOUND**, fades out, uses MB4391.
* **EMAR-SOUND**, fades out, uses MB4391.
* **GUN-SOUND**, fades out, uses MB4391.
* **HIT-SOUND**, fades out, uses MB4391.
* **JEEP-SOUND**, loop.
* **POINT-SOUND**, fades out, uses MB4391.
* **WALK-SOUND**, loop, unknown period.

note: all sounds that fades out uses the MB4391. i could not find any information about that IC on internet,
so i assumed it is an audio mixer, but i don't know its characteristics - linearity.
i simply multiplied the control signal (at pin CON) with the input signal (at pin IN).
because of that, maybe the timing of the fade is too long.

ok, now i have the sound files but the file names at [mame/src/mame/audio/vicdual.cpp](https://github.com/mamedev/mame/blob/master/src/mame/audio/vicdual.cpp#L580) do absolutely not correspond to the names from the schematic.
so i don't know, what file name is the counterpart to the sound trigger from the schematic.

please, could somebody help me to give the files the right filename - or nicer, if somebody could define the the file names according the schematics.

and can somebody tell my how i can see how long which trigger is pulled high/low,
to be able to shorten sound files to the correct length.
also for the WALK-SOUND i don't know how long a period is.

here the recreation in LTSpice files and its sound files:
[brdrline-LTSpice.zip](https://github.com/mamedev/mame/files/5088926/brdrline-LTSpice.zip)

**Comment by stilett0** [comment]
Thanks.

We'd rather this be implemented as a MAME netlist than by adding more sample sets, especially because you've gone and made a netlist with LTSpice anyways.

We've been discussing the MB4391 ourselves lately.

**Comment by beta-tester** [comment]
is there a documentation of how to recreate sounds with the MAME netlist?
maybe i can contribute the missing netlist / sounds if it is not too complicated to me.

**Comment by balr0g** [comment]
@beta-tester take a look at the nltool documentation here:
https://github.com/mamedev/mame/tree/00bff3e7030dcbc40c06dc2ac45c8d764ddbaa05/src/lib/netlist/documentation

We have a discussion channel for netlist work on the MAME Discord. You can join using this link: https://discord.gg/BkHvquH

**Comment by beta-tester** [comment]
thank you for the invitation... i just joined.

**Comment by beta-tester** [comment]
see attached the netlist of all sounds from the schematics of borderline (brdrline) i recreated:
[nl_brdrline - 2020-08-31a.zip](https://github.com/mamedev/mame/files/5151647/nl_brdrline.-.2020-08-31a.zip)

the netlist is not optimized, because i have no clue how to do so ...
and the MB4391 is totally fake, but i think it is good enough for this netlist.

**Comment by MooglyGuy** [comment]
This is not the correct way to submit changes to MAME; you should open a "pull request" once your changes are ready for inclusion. It should be possible to do a Google search for instructions on how to open a pull request.

Additionally, people are currently trying to help you work on optimizing it in #netlist-dev on Discord, it is fairly rude to say that you "have no clue how to do so" when people are actively trying to help you. Perhaps try to take their advice, or ask educated questions first.

**Comment by aaronsgiles** [comment]
Hi there, I finally got the chance to wire up your work into the Sega vicdual driver. Please see https://github.com/mamedev/mame/pull/7328 and give it a try. Let me know if you notice anything incorrect about sound triggering, or if you have any information about 'Star Raker', which I also connected to the same netlist (but not 100% correct).

**Comment by beta-tester** [comment]
thank you very much, that you "wired up" the netlist file.
by myself i woulden't be able to do so.

i have some suggestions in trigger input assignments, see #7332

**Comment by beta-tester** [comment]
just found a video with sounds of the real arcade machine:
[Borderline (Sega, 1981) Arcade Game](https://www.youtube.com/watch?v=-U8iGhnAVCI)

**Comment by MooglyGuy** [comment]
Neat.
