### ISSUE TITLE
chdman compression is worse with larger hunk size

### ISSUE THREAD

**Issue by whocares0101** [mamedev/mame#7135]
1Xtreme (USA)
http://redump.org/disc/15241/

Using mame0223b_64bit on windows 10.
chdman.exe createcd -np 12 -hs 195840

default, 19584
301 MiB

39168
338 MiB

195840
339 MiB

As the numbers show, for this game the compression gets worse with a larger hunk size.
Shouldn't it at least stay about the same size if it's not better compressible?
Just for reference 7z can crush this to 150 MiB so there should still be room for improvement with a larger hunk size.

**Comment by DavidHaywood** [comment]
CHD is designed to be streamable and quick to decompress, larger hunk size defeats the purpose.

Also CHD does some basic duplicate hunk checks, if you increase the size you're less likely to hvae small duplicate hunks, which is probably why compression gets worse.

**Comment by angelosa** [comment]
@DavidHaywood I'm gonna presume that this is a non-issue -> closing with a yes.

**Comment by DavidHaywood** [comment]
yes, it's a non-issue, expected behavior
