### ISSUE TITLE
rpmlint error: missing-call-to-setgroups-before-setuid

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#714]
When I checked my 0.171 RPM packages with rpmlint, the following error was picked up:
mame.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/mame
mame-ldplayer.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/ldplayer

According to rpmlint, this means the following:

> This executable is calling setuid and setgid without setgroups or initgroups. There is a high probability this means it didn't relinquish all groups, and this would be a potential security issue to be fixed. Seek POS36-C on the web for details about the problem.

Unfortunately, rpmlint does not say where does the error come from exactly

**Comment by rb6502** [comment]
setuid and setgid come from libuv, so if you're building with the system one it's not our fault ;-)
