### ISSUE TITLE
apple2gs command/option keys

### ISSUE THREAD

**Issue by ksherlock** [mamedev/mame#7147]
https://github.com/mamedev/mame/blob/e85dc0ce428a3878de3e37ca9a4fdb864789fb57/src/mame/drivers/apple2gs.cpp#L4508-L4509

The apple IIgs doesn't have a closed apple key.  There's a command key (sometimes called open apple) and an option key.

From the IIgs hardware ref:

> Command key: A modifier key on the Apple IIGS keyboard, marked with both an Apple icon and a propeller, the icon used on the equivalent key on some Macintosh keyboards. It performs the same functions as the Open Apple key on standard Apple II machines.

> Open Apple: A modifier key on some Apple II keyboards. On the Apple IIGS keyboard, the equivalent key is called the Command key: it is marked with both an Apple icon and a propeller, the icon used on some Macintosh keyboards.

From "From the Apple IIe to the Apple IIgs" upgrade kit manual:

> *Note*: On the Apple IIgs detached keyboard, the Solid Apple Key is labeled *Option*.

Aside from the naming, they seem to be backwards - right alt/'solid apple" set the command key bit (7) in the keyboard modifier register and left alt/"open apple" sets the option key bit (6) in the keyboard modifier register.

```
10 x = peek(49189)
20 if x<>0 then print x
30 goto 10
```

**Comment by rb6502** [comment]
Thanks for the report!  This along with an issue reported elsewhere where the IIgs wasn't respecting Reset key sequences is fixed in 3cc6415c081ecd1cd0b8d49bfaf0f0f9e3afbdc7.

**Comment by ksherlock** [comment]
Thanks!
