### ISSUE TITLE
pgm.cpp Games marked as not working

### ISSUE THREAD

**Issue by HyperScorpio** [mamedev/mame#7148]
I don´t know how to do this, but please check this games...
MAME Version: 0.224

kovytzy
kovshp
oldsplus
puzlstar

They are Marked as Not Working, but it seems is possible to finish this games completely? And they should be as "Working with problems" - Any reason for still Not Working? Sound Issues we already know about this. But graphics and gameplay and finish the games i believe they are ok. 

pgm3in1 -  As we can see, still not working yet.

I hope this helps a little.
Thank You.

**Comment by DavidHaywood** [comment]
they're all marked as NOT WORKING for good reason.
