### ISSUE TITLE
MAME crashes with key pressing in RM Nimbus machine

### ISSUE THREAD

**Issue by qazmko1029** [mamedev/mame#7159]
As the title says. Since MAME 0.219, any key press in RM Nimbus machine would crash MAME. No setting works for it.

**Comment by cracyc** [comment]
It's an infinite loop between z80sio_device::z80daisy_irq_ack and rmnimbus_state::sio_interrupt.  The new z80sio device has different interrupt handling.

**Comment by ajrhacker** [comment]
How would the real system prioritize external interrupts? The existing interrupt code in `mame/machine/rmnimbus.cpp` seems to only roughly approximate what it needs to do.

**Comment by cracyc** [comment]
I don't know and I'm not aware of any documentation about it.  Possibly the 8051 is involved but there are several fujitsu black box asics in it.

**Comment by cracyc** [comment]
fixed by https://github.com/mamedev/mame/commit/4a0e04f45844519e409bd9827c9709f1629f2298
