### ISSUE TITLE
Left-Control + Right-Arrow-Key does not work for sliders

### ISSUE THREAD

**Issue by ImJezze** [mamedev/mame#716]
As the title says, the key combination Left-Control + Right-Arrow-Key, which is used to increment values by 10 ticks, does not work since 0.171.

Right-Arrow-Key (1 tick increment) works fine
Left-Control + Left-Arrow-Key (10 ticks decrement) works fine
Right-Control (instead of Left-Control) + Right-Arrow-Key (10 ticks increment) works fine

I tried to debug this issue, but it seems the event isn't even fired, ui_menu_sliders::handle() never receives a message with menu_event.iptkey == 190 (Right-Arrow-Key) when Left-Control is pressed.

OS: Windows 10

**Comment by dankan1890** [comment]
Fixed.
