### ISSUE TITLE
Gunlock miss sound effects (MAME 0.224)

### ISSUE THREAD

**Issue by GeraBlackHnd** [mamedev/mame#7171]
The game Gunlock miss the sound effects when i put other coin, The game starts well, but in the second coin the issue happens, the music keep going. I am using MAME 0.224.

**Comment by angelosa** [comment]
Cannot repro (?) with bleeding edge.

**Comment by happppp** [comment]
Insert coin and start, go game over, insert coin and start again, and indeed there are now problems with sound.

**Comment by angelosa** [comment]
Alright thanks for the feedback.
Opened a new bug report at [MAMEtesters](https://mametesters.org/view.php?id=7861) and closing this, definitely needs regression version etc.
