### ISSUE TITLE
Gauntlet highscore.dat address breaks game

### ISSUE THREAD

**Issue by mahoneyt944** [mamedev/mame#7176]
Found this in a older core but seems to be an issue in all cores. The highscore.dat addresses for gauntlet causes the game to malfunction. 

How to reproduce the glitch: 
Launch the game, turn the service menu on, once loaded, turn service menu off. Coin up and start the game. Go to the bottom left of the screen to collect the first key, then travel through the first locked door. Go all the way to the right side of the screen to collect the second key and travel through the big locked door straight above. In the top right of the screen there is a place to warp to level 8 but when you use it you will warp back to level 1.

Information on why this is happening:
I've tested this a fair amount and this is what I've found. When you exit the service menu the .hi file gets saved which zero's out large sections within the .hi file. This highscore address in the dat is related to how the warps function in the game. So this effectively is saving the glitch.

How to fix:
I think we need to disable the .hi save when exiting the service menu, for some reason it's being triggered here. Another option might be to change our save addresses in the dat so there's not a conflict.

Dat reference:
https://github.com/mamedev/mame/blob/44af4d00edfa65d11109704bbf41c62cd8d01d14/plugins/hiscore/hiscore.dat#L6834-L6843

This may effect gaunt2 as well.

**Comment by p1pkin** [comment]
core ? Retroarch bug reports is not accepted here. be sure to check if issue exists in latest official MAME build from official web site.

**Comment by mahoneyt944** [comment]
All cores that use highscore.dat for gauntlet. The bug is game related.

**Comment by p1pkin** [comment]
>I'm only posting it here so more people see it.

here is MAME project issue tracker, not a place to post anything so more people will see it
appropriate place - try to contact Leezer, maintainer of hiscore.dat https://www.mameworld.info/highscore/index.htm

**Comment by mahoneyt944** [comment]
Well the issue exists within **YOUR MAME PROJECT** as well so that's why it's posted here too.

**Comment by mahoneyt944** [comment]
@p1pkin this issue is in this mame project too... Not sure why you closed it.

**Comment by p1pkin** [comment]
@mahoneyt944 because history.dat 3rd-party made (but shipped with MAME). here is no developers interested in maintaining this .dat, except for cases when it causes critical bugs to emulator, and as you may see from git history - it was mainly maintained by Leezer.
so, if you are really interested to fix something in this .dat - you may try do it yourself (you seems a developer form librestro, right ?), or try to ask Leezer to do this.

**Comment by mahoneyt944** [comment]
Right, but this could be a issue in the emulation itself. It's saving the .hi file as you exit the service menu and I don't think it should be.  high score files are not native to the game so this functionality must be handled somewhere in emulation. I'm not sure if the issue is the address that dat is using or a handler when you close the service menu. Which is why I'm posting here to get the the root of it. If it's just the address it can be handled by the dat maintainer but if the emulation is saving this address at the wrong time then it needs fixed in the driver.

**Comment by cracyc** [comment]
I'll look at this.

**Comment by mahoneyt944** [comment]
@cracyc I believe exiting the service menu is triggering mame to save the .hi file which corrupts it. The address is probably ok in the dat.

**Comment by p1pkin** [comment]
>Right, but this could be a issue in the emulation itself or a trigger in the highscore.cpp.

we don't have any highscore.cpp in emulator, highscore is external lua plugin since ages ago

**Comment by rb6502** [comment]
That said, opening bugs with RetroArch terminology does not endear you to MAMEdev, @mahoneyt944.  Please test and report things here only on officially shipped MAME.  The RA cores are considered abandoned and unsupported here.

**Comment by mahoneyt944** [comment]
To be honest I'm not familiar with this mame repo or how you guys handle stuff. All I know is this is a global issue across many mame versions so I wanted to bring it to your attention. What you guys do with it is your business.

**Comment by mahoneyt944** [comment]
The issue still exists in this repo? Why is this a pissing match?

**Comment by rb6502** [comment]
Because the error ultimately is in the .dat file, which is not made or maintained by MAMEdev.

**Comment by mahoneyt944** [comment]
The issue isn't the dat, if any of the maintainers here would read and put the ego away.... It's most likely in the save handler for the dat. The high file save is being triggered at the wrong time for gauntlet, ie when you exit the service menu. I'm not here to fight anyone. This is a hobby for me. The issue is clear, you exit the service menu in gauntlet and it saves a hi file which corrupts the game play of gauntlet since the game play warps the player at these addresses.

**Comment by rb6502** [comment]
There is always the possibility of hiscore.dat screwing up the game, because it's like a more invasive Game Genie code.  With older datfiles it happened all the time in popular games even when you didn't do unusual things like go into the service menu, which is exactly why the support was dropped and only much later brought back as a not-enabled-by-default plugin.

It's quite possible that there isn't a fix for this other than adding a note to not go into the service menu though.  These games were not designed with the intention that random bits of RAM would be saved and restored out from under the assumptions of the original programmer, and weird stuff can and does happen.

**Comment by mahoneyt944** [comment]
Which is understandable, I just wanted to see if there was a easy solution to this, such as an added exception in the handler for that game. Exiting the service menu probably internally resets the game and the handler sees this as a chance to save the hi file, and does filling it with garbage. This could be a glitch with other games but I'm not sure.

**Comment by cracyc** [comment]
` ; note saves last level completed and high scores `
This is the clue.  The "@:maincpu,program,904010,2,0,7" line saves the last level completed.  Remove it and the problem goes away.

**Comment by galibert** [comment]
Not just older, *seventeen years* older.  We're not in the practice of
checking current versions on bugs of 17 years ago, get real.

  OG.
