### ISSUE TITLE
appveyor build cache seems corrupted

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#7194]
It appears that appveyor build cache got corrupted. In order to purge it, two commits are required: one commenting out line 34 in .appveyor.yml, and another one uncommenting it [1]. I could do it with PRs but it is going to be much faster if someone with direct access to the repo does it. Thanks!
[1] https://www.appveyor.com/docs/build-cache/

**Comment by cuavas** [comment]
I’m not comfortable with introducing commit noise in our mainline repository to manipulate a CI service.  Would it be sufficient to push a branch with this line commented out and delete it after a build is triggered, or to create a pull request to trigger a build?

**Comment by cuavas** [comment]
Actually, a better solution is apparently to send a request via the REST API.  I’m not sure how to set up the auth headers though.  @startaq I think you’ll have to do it since it's your project on AppVeyor.  The necessary WebDAV-like request appears to be:
```
DELETE https://ci.appveyor.com/api/projects/startaq/mame/buildcache
```

**Comment by belegdol** [comment]
The guide to setting up headers is available here:
https://www.appveyor.com/docs/api/#authentication

**Comment by belegdol** [comment]
This appears to have worked for my fork:
```
$ export APPVEYOR_TOKEN="xxxxxxx"
$ curl -H "Authorization: Bearer $APPVEYOR_TOKEN" -H "Content-Type: application/json" -X DELETE https://ci.appveyor.com/api/projects/belegdol/mame/buildcache
```

**Comment by startaq** [comment]
I've deleted the build cache (I think). But isn't this just the known error of not being able to update the build tools?

**Comment by belegdol** [comment]
@startaq, thanks! I think it is a separate problem. I was able to work around the update issue earlier and it was working for a while. We will know soon enough.

**Comment by belegdol** [comment]
Looks like it is working now:
https://ci.appveyor.com/project/startaq/mame/builds/35053211/job/euc0a94b6f9487fx

**Comment by belegdol** [comment]
Hmm, weird: two builds worked:
https://ci.appveyor.com/project/startaq/mame/builds/35053211/job/euc0a94b6f9487fx?fullLog=true
https://ci.appveyor.com/project/startaq/mame/builds/35053631/job/9dxalrm7ycb5etp8?fullLog=true
Third build tried to restore the cache and failed:
https://ci.appveyor.com/project/startaq/mame/builds/35055066/job/g4axo9dphh9okxbh
@startaq, would you mind trying to nuke the cache again? If it keeps acting weird I might just disable it, 30 seconds or so are saved at best.

**Comment by belegdol** [comment]
Hmm I just tried deleting cache for my fork again and it appears like the cache was not deleted after all, just the cache service appears to have been unavailable for a while.

**Comment by belegdol** [comment]
I have now posted a question to appveyor support:
https://help.appveyor.com/discussions/problems/28134-unable-to-delete-build-cache

**Comment by belegdol** [comment]
APPVEYOR_CACHE_SKIP_RESTORE appears to be the solution. I will post the curl command which worked for me once I get back home.

**Comment by belegdol** [comment]
This is the command I used:
```
$ curl -H "Authorization: Bearer $APPVEYOR_TOKEN" -H "Content-Type: application/json" -X "POST" https://ci.appveyor.com/api/account/belegdol/builds -d "{accountName: \"belegdol\", projectSlug: \"mame\", branch: \"master\", environmentVariables: {APPVEYOR_CACHE_SKIP_RESTORE: \"true\"}}"
```
It skipped cache restore but not its update effectively refreshing it.

**Comment by startaq** [comment]
Okay, new build queued.

**Comment by belegdol** [comment]
blimey, the request only sets the no-cache-restore for the next build. If someone commits anything to master (which just happened), the build gets cancelled and the next build tries to restore cache. Back to the drawing board.

**Comment by belegdol** [comment]
According to appveyor support there was a bug in the cache cleanup routine which is now fixed. The DELETE request should work now. I have tested it on my fork and indeed no cache was restored:
https://ci.appveyor.com/project/belegdol/mame/build/job/fvt5u7axejyg94p5
@startaq, would you mind issuing the DELETE request again?

**Comment by belegdol** [comment]
@startaq, ping? Would you mind firing off another cache delete request? Thanks!

**Comment by startaq** [comment]
I've issued the DELETE command again.

**Comment by belegdol** [comment]
Thanks a lot, looks like it worked:
https://ci.appveyor.com/project/startaq/mame/builds/35303072
