### ISSUE TITLE
Segabill ROM required for optional video setting

### ISSUE THREAD

**Issue by cglmrfreeman** [mamedev/mame#7199]
I get the idea that ROM archives may change over time as emulation progresses and dumps of machine data replace work-arounds and fixes. However, Segabill's integration into MAME has forced many ROM archives to update with this non-essential data to the game's functionality. Not to mention, there is a limit to the number of games this ROM can actually interface with.

Would it not be possible to include the ROM as an external archive within the ROMs folder, almost like a BIOS I guess, and enable the extra video feature based on if it is detected or not? I'm really not sure blanket changing all model2, model3, and stv ROMs was the right approach for this optional feature.

As an owner of a Sega Versus Billboard unit myself, I would argue that it behaves more like a BIOS if anything, as it can be booted and run without any game interfaced with it, complete with a dip switch that changes the behavior when not connected with a game, as such, I think it would be worth while to be able to boot into this video mode by itself, like booting into a bios.

I'm not experienced enough with MAME's directive here, so I could be wrong.

**Comment by happppp** [comment]
It already is an external archive named "segabill", You mean this one?
epr-18022.ic2, crc32=0ca70f80

Put it in segabill.zip and MAME should find it.

**Comment by cglmrfreeman** [comment]
Huh, so there you have it. However, it's still _required_ by the game, even in an external archive. Should it be? Or should not having it simply disable that video mode?

**Comment by rb6502** [comment]
Yes, it should be.  We've moved MAME towards a model where individual devices inside a cabinet and sometimes individual subsystems on a single PCB are in separate archives.  This eliminates a problem common in the bad old days of MAME where you'd end up with 50 copies of a common ROM file in 50 different games, wasting space and bandwidth.  It still makes sense that you'd need all of the component archives to run a particular game though.

**Comment by cglmrfreeman** [comment]
Alright then, that's that. Closing the issue.
