### ISSUE TITLE
Switch to alternative build system

### ISSUE THREAD

**Issue by extrowerk** [mamedev/mame#7201]
Dear mame developers and contributors,

i did the mame Haiku port back then which was capable to fully boot IRIX and all the games i tested.

I tried to upstream the required patches here, but i was informed i should upstream my genie/bx/etc. patches separately in their respective repository, which i did. Sadly the Genie developer didn't accepted my patches as he cannot test/maintain it, which is 100% understandable.

Since then mame and the genie source tree diverged pretty much, so every major revision requires me to redo all the patches and i am clearly not the sharpest tool in the shed, it makes me really hard time to understand the lua code and get it in working shape.

As MAME targets plenty obscure platform, probably it would be a better idea to use some basic or widely supported build system like simple makefiles or cmake.

I dont posess enough knowledge about the special requiments and about the internals of the different build systems, but i checked some open tickets where genie was mentioned, and it seems i am not the first who directly or indirectly expressed the wish for a different build system.

Please consider to introduce or completely switch to a different build system.
Thanks.

**Comment by npwoods** [comment]
I second this.  The project files generated by 'make vsllvm' seem to require manual touch up to work correctly, and I couldn't make heads or tails of the Genie stuff.  I've settled for a manual recipe that I apply when I regenerate project files.

**Comment by hadess** [comment]
A lot of major projects in FOSS-land (Mesa, Xorg, most of GNOME, and Freedesktop projects) are migrating to [meson](https://mesonbuild.com/), which has great reference documentation, readable sources, and some Haiku support (even it [could be better](https://github.com/mesonbuild/meson/issues/7073)).

I struggled with the genie build system as well as I was trying to disable building everything but imgtool. I ended up with something that worked well enough if I remember the incantations to build 2 separate directory trees, I've now promptly forgotten everything about it.

**Comment by startaq** [comment]
Note that a few years ago the author of Meson migrated the build system of MAME to Meson as a test: https://www.mameworld.info/ubbthreads/showflat.php?Cat=&Number=332119&page=&view=&sb=5&o=&vc=1

**Comment by rb6502** [comment]
There's a GitHub project I've seen that provides CMake scripts to build BGFX, so it is possible.  And CMake can generate clean, working MSVC and Xcode projects, which other solutions do poorly if at all.

SOURCES= builds are the major thing though, and they're hard to do in anything other than GENie/Premake.

**Comment by hadess** [comment]
I don't know what bgfx is, but I know that I've used cmake for years, and it was only mildly better than the autotools (which I've used for 20 years).

CC @jpakkane.

**Comment by hadess** [comment]
>  And CMake can generate clean, working MSVC and Xcode projects, which other solutions do poorly if at all.

From https://mesonbuild.com/Quick-guide.html
```
Meson can [...] generate native VS and XCode project files.
```

**Comment by cuavas** [comment]
We’re aware of limitations of the current build system.  This isn’t the right venue for this discussion, and MAME is not a democracy.

**Comment by hadess** [comment]
> We’re aware of limitations of the current build system. This isn’t the right venue for this discussion, and MAME is not a democracy.

And how exactly is one supposed to propose, let alone implement, a new build system if there's nowhere to gather the requirements? Are folks supposed to do the work, propose it, iterate, only to be told that "MAME is not a democracy" and that the effort has gone to waste?

Having an obtuse and antiquated build system and no way to discuss how to replace is really not a great way to get people to contribute tests:
https://github.com/mamedev/mame/issues/7124#issuecomment-689884492

**Comment by cuavas** [comment]
It’s not practical to have something as fundamental as the build system replaced by an outside contributor.

**Comment by cuavas** [comment]
Thanks for letting us know.  Every significant change in the build system is a major upheaval, particularly with the size and number of contributors MAME has.  It’s not a decision to make lightly, and it’s not something that’s going to be done without a lot of planning.

**Comment by galibert** [comment]
Oh, maybe it's practical.  We just need to enumerate the requirements:
- we want cmake, that one is not really negotiable
- we want to have the same capabilities we currently have:
* compile with or without symbols
* compile with or without optimization
* compile with or without debugging
* separate the symbols from the executable (symbols map?  Not sure, it's
more of a windows thing)
* can select compiler, linker, etc
* can generate at least makefiles, VC solutions and whatever it is xcode
uses
* can compile a subset of drivers, e.g. the SOURCES=... capability
- we also want to be able to generate sources and header files in the
process of compilation (see what's currently pre-generated for the 68000
for instance) and have the dependencies generated correctly
- we'd like to able able to use more modern builders on linux, ninja in
particular

Vas, what am I missing?

  OG.

**Comment by hadess** [comment]
> - we want cmake, that one is not really negotiable

Ok, good luck then.

**Comment by rb6502** [comment]
> I hope I made it clear that the current one is a blocker for contributions (at least for me).

The problem you're citing (not being able to build tools individually) was a choice by @mmicko who set up the current build scripts.  It's not a property of the build system itself.  If you (or anyone) want to make tools able to be built individually we'd be happy to review the PR.

**Comment by mmicko** [comment]
He he blast from the past :) Anyway in time when we started using GENie it was mostly because we were lacking CMake experience and CMake was lacking support on some things we needed (or it was just too complicated there). Having custom or not very popular build system is maintenance problem, but so far I see there was no big issues with GENie scripts. Also not sure how easy would be to get build from SOURCES capability on anything else. 
To be honest I was not doing anything for a long long time on project, but could take a look and try to tackle CMake if there is overall consensus, supporting things current system does (as @galibert pointed out).

**Comment by hadess** [comment]
> It's not a property of the build system itself.

The build system being so niche that it's impossible to find good documentation about it is a property of the build system. I've managed to hack together the build system for my sole (non-trivial) contribution but I'm not doing it again.

> If you (or anyone) want to make tools able to be built individually we'd be happy to review the PR.

I already said "the current build system isn't conducive to contributions". Like, if I could have figured out how to do it cleanly, I probably would have. I couldn't.

**Comment by rb6502** [comment]
@mmicko I think there's a general consensus amongst myself, Vas, and OG that attempting CMake is a good idea if you have the bandwidth to try it.

**Comment by LegalizeAdulthood** [comment]
Not to kick a dead horse, but additional advantages to using CMake:
- you get `compiler_commands.json` generated for free, opening application of tools like `clang-tidy` to the MAME code base
- you get a `ninja` generator for *really* fast builds

If there are others interested in collaborating on a CMake build pull request, please include me.

**Comment by rb6502** [comment]
This is being worked on internally; the major tree organization changes that have been happening for the last week or so are prep for that eventual switch.

**Comment by LegalizeAdulthood** [comment]
If I can be of assistance, please don't hesitate to contact me.  I've given several presentations on CMake:
- May 13th, 2020: [Utah C++ Programmers: Installation and Packaging with CPack](https://www.meetup.com/Utah-Cpp-Programmers/events/xxrjflybchbrb/) ([video](https://www.youtube.com/watch?v=JuZPu4yJA7k))
- April 8th, 2020: [Utah C++ Programmers: Automated Testing with CMake, CTest and CDash](https://www.meetup.com/Utah-Cpp-Programmers/events/xxrjflybcgblb/) ([slides](https://www.slideshare.net/LegalizeAdulthood/automated-testing-with-cmake-ctest-and-cdash), [video](https://www.youtube.com/watch?v=YlIqlVVJWuo))
- March 11, 2020: [Utah C++ Programmers: Feature/Platform Testing with CMake](https://www.meetup.com/Utah-Cpp-Programmers/events/xxrjflybcfbpb/) ([slides](https://www.slideshare.net/LegalizeAdulthood/feature-and-platform-testing-with-cmake))
- February 12, 2020: [Utah C++ Programmers: Consuming 3rd Party Libraries with CMake](https://www.meetup.com/Utah-Cpp-Programmers/events/xxrjflybcdbqb/) ([slides](https://www.slideshare.net/LegalizeAdulthood/consuming-libraries-with-cmake))
- January 8, 2020: [Utah C++ Programmers: Basic Modern CMake](https://www.meetup.com/Utah-Cpp-Programmers/events/xxrjflybccblb/)

I've also given presentations on vcpkg for managing dependencies (another sticky point in large builds); it integrates well with CMake and despite what the name might imply is cross-platform, open source and build system agnostic:
- December 9th, 2020: [Utah C++ Programmers: VcPkg: The Open Source Cross-Platform Package Manager from Microsoft](https://www.meetup.com/Utah-Cpp-Programmers/events/xxrjflybcqbmb/) ([video](https://www.youtube.com/watch?v=gpBDHh47w-I))
- Various other talks about different libraries that I've consumed with vcpkg, where the emphases of the talk was on the other library.

What brought me into MAME's code base is that I was looking around for a Motorola 6805 simulator for a [6805 SBC vintage computing project](https://github.com/LegalizeAdulthood/6805_SBC) and MAME looks like the most mature environment for poking around with a simulator (e.g. mekd1).
