### ISSUE TITLE
[LUA] getting the state of controls assigned in Input(General) - possible?

### ISSUE THREAD

**Issue by oomek** [mamedev/mame#7213]
I have a little problem with my plugin for Defender. I did an 8-way control for this game, but I'm struggling to find a way of getting the state of the controls assigned in `Input (general)` I know how to get the state of the keyboard keys:
`manager:machine():input():code_pressed(inp:code_from_token("KEYCODE_LEFT"))`
I also know how to get the state of controls from `Input (this Machine)` by checking ports exposed by the game:
`manager:machine():ioport().ports`
But in Defender for example Left and Right directions are absent, just Up and Down.

Am I missing something, or this kind of functionality is not implemented?

Reassuming: I need to check the state of the keyboard, joystick, or whatever is assigned to `P1 Left/Right` in `Input(general)`

**Comment by cracyc** [comment]
Added in https://github.com/mamedev/mame/commit/6aa3840d181d86e11b9b77d76a475b9a228bde6f, ioport():type_seq(type, player, seqtype) which will return a sequence containing the codes for an input type.  type comes from https://github.com/mamedev/mame/blob/master/src/emu/ioport.h#L92, for now you're on your own getting the values from the enum.

**Comment by oomek** [comment]
Awesome, thank you very much. I'm gonna build and try.

**Comment by cuavas** [comment]
This is possible in current builds.
