### ISSUE TITLE
fuck！ log is to Super big!Any good way？

### ISSUE THREAD

**Issue by zengfr** [mamedev/mame#7300]
1   mame debug is setting output to local log file（Export files for subsequent processing）
 2   i use debug some cmds like  bp ,,,{printf........; or  wp  ,,,{printf........; or trace log..... and so on.
 3   log file is Super big！ more 1G ！ Oh my God！
Any good way？output remove duplicate or distinst lines ?
Can it be improved？ 
1  add dbg cmds like "printfd " (output remove duplicate)?
2  add a channel  output  log to tcp/udp ？then Third-party program receive to processing。Hate large local files fuck！

**Comment by cuavas** [comment]
There are a few suggestions here:
* Log debug console output to a file
* A feature akin to the UNIX `uniq` command to collapse repeated lines
* A feature to send debug console output to some kind of socket (e.g. TCP/UDP)

**Comment by zengfr** [comment]
> There are a few suggestions here:
> 
> * Log debug console output to a file
> * A feature akin to the UNIX `uniq` command to collapse repeated lines
> * A feature to send debug console output to some kind of socket (e.g. TCP/UDP)

 output to a file is too big  o my god!

**Comment by Robbbert** [comment]
I think we're done here.
