### ISSUE TITLE
travis is no longer listed among checks

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#7310]
Even though travis CI is still running, its results are not listed when one hovers above the ticks next to commits or PRs. Is this intentional?

**Comment by stilett0** [comment]
I don't think that's intentional.

I took a quick look but I can't see what the issue is so I'm paging @startaq who set up a lot of the CI things :)

**Comment by stilett0** [comment]
Okay I didn't change anything with the travis config, either the .yaml, the server-side setup or anything, but they seem to be appearing now? Weird

**Comment by stilett0** [comment]
Okay, definitely appearing on some and not on others.

It looks like... Okay, I can't tell you what happened yet but looking at the commit history, every check was being run on every PR and commit until a few days ago when https://github.com/mamedev/mame/commit/9a08e63fd3c462dcca28efa076121528ff4500e2 went in.

Check this out: click on the checkmarks here or notice the lack of them here: https://github.com/mamedev/mame/commits/master?after=f5d8c8cbb74d09de54c1659157862bbf9b6eebf2+34&branch=master

Going back further and there are other commits from couriersud's without any checks run. I am thinking this is something to do with something he did...  Just a guess, tho, as the version bump for release that Vas did doesn't show a Travis check either.
https://github.com/mamedev/mame/commit/5a1fd0cc172cf10c9519152391283a90da33d0c9

Minutes after I logged into Travis, they seem to be happening again, see https://github.com/mamedev/mame/commit/f5d8c8cbb74d09de54c1659157862bbf9b6eebf2
which weirdly enough is following https://github.com/mamedev/mame/commit/467b8f7d0920ee8f9f83086bc7323feed8fe76ea ... another couriersud commit, this time a revert.

**Comment by belegdol** [comment]
Super strange. @couriersud, do you have any special travis CI set up by any chance?

**Comment by stilett0** [comment]
As an experiment last night before I fell asleep, I took one of the builds where no Travis check was showing previously, and told Travis to re-launch the build.
This morning, a Travis check shows on that commit.
... I can try that for the rest, but I still don't understand why it happened. Few if any of these were marked as "Build Canceled".

**Comment by stilett0** [comment]
7 hours ago @couriersud had two commits:
https://github.com/mamedev/mame/commit/b49a86981c1e2d635f738dbddf285d03d2bce183
https://github.com/mamedev/mame/commit/a64784a7dbd3428913372df856ac21f6a8b214f7
and there's no Travis test reports OR Appveyor test reports.

Travis doesn't even have builds for them.

This is unrelated to the ones that -do- have builds but Github doesn't indicate them.

My hypothesis is that this isn't a setting but is for the most part related to the amount of code churn going on with netlist.

**Comment by belegdol** [comment]
It seems like there are some issues with GH communicating with CI services. The last 10 commits have both checks on them, maybe the problem will just go away on its own.

**Comment by stilett0** [comment]
All the more reason to get Github Actions going? Hmm, I sense a plot. @startaq and @balrog have been looking into Github Actions at any rate.

**Comment by belegdol** [comment]
I looked into GH actions too a little bit:
https://github.com/balr0g/mame/pull/1
Last time I checked, only x86_64 was supported so we would need to keep travis for that. But x86_64 linux and mac could be transferred, same as everything appveyor does.

**Comment by belegdol** [comment]
This seems to be working now.
