### ISSUE TITLE
0.225: missing roms listed as bad

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#7314]
I have upgraded to 0.225 and now qmc2 shows 376 bad roms as opposed to 5 or so 0.224 was showing. Both versions were recognising some missing roms as bad, but now the situation is much worse. For example:
```
$ mame -verifyroms mvsca
mvsca       : mvca.03a (524288 bytes) - NOT FOUND
mvsca       : mvca.04a (524288 bytes) - NOT FOUND
mvsca       : mvsca.key (20 bytes) - NOT FOUND
romset mvsca [mvsc] is bad
$ mame -verifyroms xmvsf
xmvsf       : xvse.03f (524288 bytes) - NOT FOUND
xmvsf       : xvse.04f (524288 bytes) - NOT FOUND
xmvsf       : xvs.05a (524288 bytes) - NOT FOUND
xmvsf       : xvs.06a (524288 bytes) - NOT FOUND
xmvsf       : xvs.07 (524288 bytes) - NOT FOUND
xmvsf       : xvs.08 (524288 bytes) - NOT FOUND
xmvsf       : xvs.09 (524288 bytes) - NOT FOUND
xmvsf       : xvs.13m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.15m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.17m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.19m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.14m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.16m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.18m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.20m (4194304 bytes) - NOT FOUND
xmvsf       : xvs.01 (131072 bytes) - NOT FOUND
xmvsf       : xvs.02 (131072 bytes) - NOT FOUND
xmvsf       : xvs.11m (2097152 bytes) - NOT FOUND
xmvsf       : xvs.12m (2097152 bytes) - NOT FOUND
xmvsf       : xmvsf.key (20 bytes) - NOT FOUND
romset xmvsf is bad
```
It looks like a rom or two from a bios or a parent rom makes -verifyroms consider the rom available and bad as opposed to not found.

**Comment by cuavas** [comment]
The "fix" for this committed for this was worse than the issue. In MAME 0.224 many systems were in correctly reported as not found when ROMs were present, making them impossible to launch from the internal UI. Affected systems included `snes`, `fds` and many others.

I don't see how it's possible to fix this without preventing systems from being launched incorrectly. Clone systems that only differ in undumped ROMs don't need any additional ROMs over the parent to be in the best available state, so they'll be listed in a full audit even if they have no ROMs present.

**Comment by belegdol** [comment]
Hmm, maybe going back to 0.223 is the best way forward if there is no better alternative? Before the initial round of fixes went in only 7 or so roms were falsely reported as missing. The initial fixes brought this down to 5 or so.

**Comment by p1pkin** [comment]
@belegdol are you sure you really have all the required ROMs ? I can't reproduce issue here.

> mame64.exe -verifyroms mvsca
> romset mvsca [mvsc] is good
> 1 romsets found, 1 were OK.
> 
> mame64.exe -verifyroms xmvsf
> romset xmvsf is good
> 1 romsets found, 1 were OK.

**Comment by Robbbert** [comment]
I'm not even sure what you are doing?

C:\MAME>mame -verifyroms mvsca
romset mvsca [mvsc] is good
1 romsets found, 1 were OK.

C:\MAME>mame -verifyroms xmvsf
romset xmvsf is good
1 romsets found, 1 were OK.

**Comment by belegdol** [comment]
I do not have the roms so mvsca or xmvsf should be recognised as not found, not as bad. For example:
```
$ mame -verifyroms term2
romset "term2" not found!
```

**Comment by Robbbert** [comment]
For mvcsa, it is the same as mvcs except that 3 roms are different. So, MAME sees the roms in mvcs and thinks you almost have mvcsa, that's why it says bad rather than not found - it was able to find 19 of the needed roms.

**Comment by belegdol** [comment]
For xmvsf everything is missing though. The only available file seems to be qsound.

**Comment by Robbbert** [comment]
Yes, I agree with you there. Parents shouldn't be influenced by bioses or devices.

**Comment by cuavas** [comment]
The net changes from 0.223 to 0.225 are minimal, just correcting the size check for ROMs that use multiple load commands (e.g. ignore and continue):

```
$ git diff mame0223..mame0225 src/frontend/mame/audit.cpp
diff --git a/src/frontend/mame/audit.cpp b/src/frontend/mame/audit.cpp
index 6f2157a3ac4..c5ee2e30e7d 100644
--- a/src/frontend/mame/audit.cpp
+++ b/src/frontend/mame/audit.cpp
@@ -515,7 +515,7 @@ device_t *media_auditor::find_shared_device(device_t &device, const char *name,
 		{
 			for (const rom_entry *rom = rom_first_file(region); rom; rom = rom_next_file(rom))
 			{
-				if (ROM_GETLENGTH(rom) == romlength)
+				if (rom_file_size(rom) == romlength)
 				{
 					util::hash_collection hashes(ROM_GETHASHDATA(rom));
 					if ((dumped && hashes == romhashes) || (!dumped && ROM_GETNAME(rom) == name))
@@ -535,7 +535,7 @@ device_t *media_auditor::find_shared_device(device_t &device, const char *name,
 				{
 					for (const rom_entry *rom = rom_first_file(region); rom; rom = rom_next_file(rom))
 					{
-						if (ROM_GETLENGTH(rom) == romlength)
+						if (rom_file_size(rom) == romlength)
 						{
 							util::hash_collection hashes(ROM_GETHASHDATA(rom));
 							if ((dumped && hashes == romhashes) || (!dumped && ROM_GETNAME(rom) == name))
```

I’m not sure how this is having the effect you’re seeing, it needs more investigation.

**Comment by belegdol** [comment]
Only a couple drivers appear to be heavily affected: cps1, cps2 and zn. The remaining issues are with naomi (mbaao and mushi2eo) and stv (ffrevng10), these were present in 0.224 too. So it does look like qsound might be the culprit. The qsound rom itself appears to be good:
```
$ mame -verifyroms qsound
romset qsound is good
1 romsets found, 1 were OK.
```

**Comment by belegdol** [comment]
I can reproduce this with official binary too by putting qsound_hle.zip in the roms folder.

**Comment by cuavas** [comment]
0f6a1cec4adb9c59f323c4608f1a7b7a81eaaa79 should clear up most of them again, it should be no worse than 0.223 now.

**Comment by cuavas** [comment]
The remaining issues are described in (MT07410)[https://mametesters.org/view.php?id=7410].  If a system has no ROMs that differ from the parent, and you have ROMs from a device/BIOS set but not the parent, it will report the set as bad.

**Comment by belegdol** [comment]
Indeed, only 4 ROMs are showing as missing now:

- ymmu100.cpp: mu100r
- stv.cpp: ffrevng10
- naomi.cpp: mushi2eo & mbaao

As good as 0.224. Thanks!

**Comment by cuavas** [comment]
You should no longer see `ffrevng10` reported as bad as of aca0aaaa3d6870f0372316912031794329a5ca41.

**Comment by belegdol** [comment]
All of the incorrectly reported ROMs are gone now, not only ffrevng10. Thanks!
