### ISSUE TITLE
GitHub: Consider adding `hacktoberfest` topic to the project

### ISSUE THREAD

**Issue by darkstar** [mamedev/mame#7315]
DigitalOcean's Hacktoberfest is now opt-in: https://hacktoberfest.digitalocean.com/hacktoberfest-update

I have some more softlist PRs in the queue and would love to have them count towards Hacktoberfest

**Comment by cuavas** [comment]
I’m not sure we really want to do that.  Do we want people to see MAME as a vehicle for getting a free shirt?  It seems it would mostly attract people who don’t really have an interest in it and just want the merchandise.

**Comment by angelosa** [comment]
Nothing can go wrong, I still have my red pen handy :)

**Comment by DavidHaywood** [comment]
I'm not entirely sure what the expected benefits are of this, it seems like another one of those things that might result in low quality submissions to try and get a free t-shirt, but at the end of the day there are plenty of low-hanging fruit, such as Softlist additions, where we really need to be encouraging external contributors to step in, there's a lot of material that's simply never been added when it should be a simple, quick add, quick merge process but instead prototypes and rare dumps are appearing online, not being recorded anywhere, and subsequently becoming very difficult to find.

**Comment by darkstar** [comment]
The last 2 years, hacktoberfest was opt-out, so MAME did take part. And I don't think there were any spam PRs back then...

**Comment by darkstar** [comment]
another solution would be to have a `hacktoberfest-accepted` label that can be added to PRs by maintainers on request of the submitter. Would that work better (without exposing the whole repo to spammy PRs)?

**Comment by angelosa** [comment]
Closing, event ended.
