### ISSUE TITLE
Old and vulnerable Expat 2.1.1 bundled at 3rdparty/expat/; please update to 2.2.10

### ISSUE THREAD

**Issue by hartwork** [mamedev/mame#7317]
Hi!

I found an old and vulnerable copy of Expat 2.1.1 bundled at folder [`3rdparty/expat`](https://github.com/mamedev/mame/tree/master/3rdparty/expat). Please consider upgrading to Expat 2.2.10, the [change log](https://github.com/libexpat/libexpat/blob/master/expat/Changes) has more details about the fixes since release 2.1.1.

Thanks and best, Sebastian

**Comment by cuavas** [comment]
Update to 2.2.10 in d256f069a5aa30bf5ffcfc4b73047ce0f372ea10

You can also build against your system expat library with `USE_SYSTEM_LIB_EXPAT=1` on UNIX-like systems.

**Comment by hartwork** [comment]
Thanks for the update!
