### ISSUE TITLE
enable dynamic libraries in Lua console

### ISSUE THREAD

**Issue by bsl** [mamedev/mame#732]
If I try to `require` a Lua module from the console or a script, I see `"dynamic libraries not enabled; check your Lua installation"`.

But if I set `CFLAGS=-DLUA_USE_MACOSX` when building, `require`ing modules works fine, and the usual functionality seems unaffected.

I think `LUA_USE_MACOSX` works for me because in Lua's `luaconf.h`, it enables `LUA_USE_DLOPEN`.

If there's no reason not to enable this functionality, could you please alter the build to enable it?

**Comment by mmicko** [comment]
Aware of this, but dynamic libraries are disabled by intention. Idea is to always give users code that is multi-platform.

**Comment by mskraddoc** [comment]
Hmmm....
I think almost every environment that supports MAME also supports Lua. No?  Even if there are exceptions, wouldn;t they represent a small minority of use cases? Enabling the use of dynamic libraries through the Lua console would enhnace MAME development, IMHO.  

Hey, thanks!
