### ISSUE TITLE
ParaParaParadise 2ndMIX does not boot

### ISSUE THREAD

**Issue by pm41224** [mamedev/mame#7326]
I tried booting PPP 2ndMIX on MAME 0.225 using the GM941B01 option, but it wouldn't boot past the BIOS screen. The error shows up as "E801 SECURITY ERROR". This is what the boot screen looks like after I cleared the backup RAM and restarted the game.
![0000](https://user-images.githubusercontent.com/55181080/95026675-0cb95900-0661-11eb-9540-92cf73ca4ad2.png)
As we all know this game does not work in current versions of MAME. Just wanted to raise this issue to the devs.

**Comment by einstein95** [comment]
The game is marked as MACHINE_NOT_WORKING, which means the devs are very much aware that the game doesn't work.

**Comment by rb6502** [comment]
Yes, you should've seen a message on startup that the game does not work.
