### ISSUE TITLE
unidasm doesn't link

### ISSUE THREAD

**Issue by Robbbert** [mamedev/mame#7333]
Using GCC10.1 on Windows 10, 64-bit, and with the faster lld linker.

Linking unidasm.exe...
lld-link: error: undefined symbol: vtable for upd177x_disassembler
>>> referenced by ../../../../mingw-gcc/obj/x64/Release/src/tools/unidasm.o:(.refptr._ZTV20upd177x_disassembler)

lld-link: error: undefined symbol: vtable for romp_disassembler
>>> referenced by ../../../../mingw-gcc/obj/x64/Release/src/tools/unidasm.o:(.refptr._ZTV17romp_disassembler)

lld-link: error: undefined symbol: vtable for pic1670_disassembler
>>> referenced by ../../../../mingw-gcc/obj/x64/Release/src/tools/unidasm.o:(.refptr._ZTV20pic1670_disassembler)

lld-link: error: undefined symbol: vtable for pic16_disassembler
>>> referenced by ../../../../mingw-gcc/obj/x64/Release/src/tools/unidasm.o:(.refptr._ZTV18pic16_disassembler)

lld-link: error: undefined symbol: vtable for pdp8_disassembler
>>> referenced by ../../../../mingw-gcc/obj/x64/Release/src/tools/unidasm.o:(.refptr._ZTV17pdp8_disassembler)

lld-link: error: undefined symbol: vtable for nuon_disassembler
>>> referenced by ../../../../mingw-gcc/obj/x64/Release/src/tools/unidasm.o:(.refptr._ZTV17nuon_disassembler)

lld-link: error: undefined symbol: vtable for lc58_disassembler
>>> referenced by ../../../../mingw-gcc/obj/x64/Release/src/tools/unidasm.o:(.refptr._ZTV17lc58_disassembler)
collect2.exe: error: ld returned 1 exit status
unidasm.make:253: recipe for target '../../../../../unidasm.exe' failed
make[2]: *** [../../../../../unidasm.exe] Error 1
makefile:1171: recipe for target 'unidasm' failed
make[1]: *** [unidasm] Error 2
makefile:1094: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

**Comment by ajrhacker** [comment]
This often happens when attempting a build with TOOLS=1 after doing a standard build. In my experience, removing libdasm.a and/or libformats.a and then trying the TOOLS=1 build again usually solves the problem.

**Comment by Robbbert** [comment]
This works. I had actually done a completely clean build yesterday in an attempt to get somewhere, but had then forgotten to comment back in the affected disassemblers. Doing this produced a successful build.
