### ISSUE TITLE
License of several files

### ISSUE THREAD

**Issue by jmallach** [mamedev/mame#734]
Hi,

I'm nearly ready to upload MAME 0.171 to Debian (and Ubuntu). While checking the licence of the source in order to move MAME to Debian's main section, I find the following (random example, there are more)

In src/devices/video/mos6566.cpp:

    The rights on the source code remain at the author.
    It may not - not even in parts - used for commercial purposes without explicit written permission by the author.
    Permission to use it for non-commercial purposes is hereby granted als long as my copyright notice remains in the program.
    You are not allowed to use the source to create and distribute a modified version of Frodo.

However, the first line of the file notes:

    // license:BSD-3-Clause

So what should I be believing? This is in 0.171 and current git master.

Is 0.171 already the full GPL'd MAME, or will that be 0.172?

**Comment by DopefishJustin** [comment]
cc @curt-coder 

Frodo itself has been GPL2 for some time now so this particular case shouldn't be too big a deal to sort out.

The intention was for 0.172 to be the first GPL release, and for current git to already be ready to go in that respect but it's always possible we missed something here or there.

**Comment by stilett0** [comment]
The code in question (mos6566.cpp) with that source header had modifications based off Frodo 4.1b source package as available from http://frodo.cebix.net as of 2002/01/02 - http://frodo.cebix.net/downloads/FrodoV4_1b.Src.tar.gz

We can determine this based on the comment of the original author (in MAME/MESS) robiza, who given those licensing restrictions decided to ask for special permission from Christian Bauer (cebix) to distribute code alterations based on Frodo under the MAME/MESS license of 2009: You can see permission asked and granted here in 2009 to distribute under MAME license: http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=53101

robiza's contribution was later rewritten by @curt-coder as of here in 2012:
https://github.com/mamedev/mess-svn/commit/79997501592dd7f461d6632e29bd94aca1acc396
mirror: http://git.redump.net/mess/commit/?id=516960a313b851d1931c40086f34010eba04bf20
but the credit to Christian Bauer remained.

However, what @DopefishJustin is referring to - it seems what robiza didn't know is that in Frodo's CVS, Christian Bauer/cebix had relicensed Frodo to GPL 2.0+. This occurred on 2003/07/01: http://www.cebix.net/viewvc/cebix/Frodo4/Docs/legalmush.html?r1=1.1&r2=1.2
source: http://www.cebix.net/viewvc/cebix/Frodo4/Src/VIC.cpp?view=log
or in other words Frodo 4.2, which is on the cebix.net CVS.

So all that needs to happen is a final review and sign-off by @curt-coder or someone prior to MAME 0.172 that the information gleaned from the Frodo 4.1b source is identical (or enhanced) in the Frodo 4.2 source that exists on the cebix.net CVS. (And maybe someday, cebix will officially release Frodo 4.2 in a package) - and then update the header in mos6566.cpp to reflect this by saying "// license:GPL-2.0+" and "// copyright-holders:Curt Coder, Christian Bauer" or something along those lines. And then legally, this code should be fine. 

----

As Justin said, MAME 0.172 is intended to be the "official relicense", which of course has not yet been released.

@jmallach  you say there is other code with similar license situations? Can you point it out? Perhaps it was inadvertently missed, or there are similar situations. Please post any you've seen, thanks.

**Comment by mmicko** [comment]
Thanks for pointing to this. Checked the rest and found cases where restriction is mentioned and removed those where we have direct approval. Also contacted one more external author and even get more permissive license

**Comment by jmallach** [comment]
Thank you. I'll check current git to see if I can find anything else before 0.172. Any clue when that release might happen? I might want to hold my Debian upload until that release happens.

**Comment by mmicko** [comment]
Release is always last Wednesday of month, so 30th of March for next release

**Comment by jmallach** [comment]
thanks @mmicko! See some line comments I added on one of the comments:

https://github.com/mamedev/mame/commit/5965f07e9888e32ae79953f64107e846a1873fbc

**Comment by jmallach** [comment]
Err, one of the commits, I mean.

**Comment by jmallach** [comment]
The last questionable block I've been able to find is:

https://github.com/mamedev/mame/blob/master/src/mame/drivers/system16.cpp#L3032

    /*
    Program Roms contain
    
    Designed and Programmed by A.M.T. Research & Development Department 03/30/1991.
    Copying or Revising for Commercial Use Is Not Permitted.
    */

**Comment by balr0g** [comment]
@jmallach that's referring to the contents of the referenced program ROMs for beautyb which are not distributed with MAME.

Should the comment be changed to state:
```The below-referenced Program Roms contain```...?

**Comment by mmicko** [comment]
This is related to roms not to code, so that is fine :)

**Comment by jmallach** [comment]
Thanks for the clarifications, everyone!

**Comment by stilett0** [comment]
No problem, @jmallach . Thanks for the "alley-oop", @mmicko ! :smile:
