### ISSUE TITLE
Don't create windows for "-video none"

### ISSUE THREAD

**Issue by YannNeobards** [mamedev/mame#7345]
Is it possible not to create windows when option "-video none"

**Comment by YannNeobards** [comment]
using this `if (video_config.novideo) m_extra_flags = SDL_WINDOW_SKIP_TASKBAR | SDL_WINDOW_HIDDEN | SDL_WINDOW_MINIMIZED;`
in `src/osd/sdl/windows.cpp` line 735
maybe there is better way

**Comment by rb6502** [comment]
What is your use case where showing a window is a problem?

**Comment by galibert** [comment]
It tends to be hard to have inputs if you don't have a window on some OSes.

  OG.

**Comment by cuavas** [comment]
It is possible to not show a window using the SDL OSD – I use it for testing performance and writing AVIs with INP playback on completely headless Linux machines with no X server running:
```
env SDL_VIDEODRIVER=dummy mame64 -video none -sound none ...
```

I’m not sure it’s a great idea to make this more accessible, because without a window it can become difficult to manage the MAME process on desktop environments that assume applications have visible windows.

**Comment by YannNeobards** [comment]
I have implemented a Run Ahead version by forking mame, and reinputing keys, I don't need window for the master, as I reinput keys from slave

**Comment by YannNeobards** [comment]
I have changed this in windows.cpp (src/ods/sdl/) working well 
line around 790 (on version 0225 of mame)
```
	if (!video_config.novideo) {
		SDL_ShowWindow(platform_window());
		//SDL_SetWindowFullscreen(window->sdl_window(), 0);
		//SDL_SetWindowFullscreen(window->sdl_window(), window->fullscreen());
		SDL_RaiseWindow(platform_window());
	}
	else {
		SDL_HideWindow(platform_window());
	}

```

**Comment by YannNeobards** [comment]
@rb6502 the other case is, if you launch a batch of many replay's to check your change doesn't break the result you have popping windows all the time, still can launch on a xvfb but less convenient in some cases

**Comment by YannNeobards** [comment]
@rb6502 the last case is using a UDP server into mame streaming video and listening key inputs, I don't need any windows
need to try this, looks very interesting `env SDL_VIDEODRIVER=dummy mame64 -video none`

**Comment by cuavas** [comment]
If you’re running MAME in an exotic configuration as a slave process, you’d be better served by writing custom OSD modules for your fork.  I believe the options currently available are adequate for MAME’s primary use case as an interactive emulator.
