### ISSUE TITLE
(nes.cpp) black screen in sanguo2

### ISSUE THREAD

**Issue by 280696516** [mamedev/mame#7350]
this is a hack rom of Sangokushi II: Haō no Tairiku（Published by Namco Limited）
nestopia can run it。
三国志2 - 霸王的大陆 (中文加强版) [外星科技汉化]

**Comment by Osso13** [comment]
Please do not upload ROM files.

**Comment by 280696516** [comment]
![屏幕截图(186)](https://user-images.githubusercontent.com/54297406/97816546-fb4f8500-1cd0-11eb-921e-841459a94a26.png)

**Comment by angelosa** [comment]
From what I can gather best candidate is `sanguo2` in `nes.xml` SW list, which is marked as `supported="partial"` except testing it just returns a black screen. 
So unless it regressed in some way (and I doubt it) then should be at least demoted to `supported="no"`.

**Comment by 0kmg** [comment]
Based on the ROM sizes and mapper # reported by FCEUX in the screen shot I think this is `sanguo2a`, which seems to work in MAME. A loose ROM from the wild also loaded fine, so maybe the user had a file with a bad header?

I've marked `sanguo2` as unsupported and unimplemented in #9131. I don't think we need this issue ticket any longer?
