### ISSUE TITLE
prot_fatfury2 changes

### ISSUE THREAD

**Issue by hanasu** [mamedev/mame#7356]
The changes to this in .225 have caused some gameplay issues: https://www.twitch.tv/videos/771633011?t=2h25m32s

The first match of the 1P mode against the CPU will be perfectly fine. The second match will have no hurtboxes, however grabs will still work. The third match will start with 0 seconds on the clock and immediately draw game.

**Comment by cuavas** [comment]
Already reported and resolved for 0.226 – see discussion on #7224 and #7331.
