### ISSUE TITLE
Add ZStandard support to CHD

### ISSUE THREAD

**Issue by kcgen** [mamedev/mame#7386]
ZStandard decompresses typically 20-fold faster (or 20-fold less latent) than CHD's existing xz/lzma format, at equivalent compression levels.

It's so fast that in many cases extracting is faster than reading uncompressed data because it often exceeds disk rates.

It's liberally licensed, widely used, institutionally supported, extensively tested and optimized across an array of embedded and PC platforms, and has interfaces for all popular languages.

It's basically the best-in-class compression codec all things considered, and only getting better.

**Comment by MooglyGuy** [comment]
We await your pull request.
