### ISSUE TITLE
compile error on windows

### ISSUE THREAD

**Issue by sum2012** [mamedev/mame#739]
I installed mingw and Python34
os:windows 7 64 bit
![1](https://cloud.githubusercontent.com/assets/2177532/14018245/ab0d05de-f207-11e5-8498-73a265c0608f.png)

**Comment by h0tw1r3** [comment]
Python3 is not fully supported yet. See issue #706

**Comment by sum2012** [comment]
Switch to Python2.7
Now it complain mingw64.
I try to download mingw64 but it only has header file.
How to solve it ? Thanks
![2](https://cloud.githubusercontent.com/assets/2177532/14051404/8e0c5678-f2fd-11e5-8ba1-7e1d5ca89982.png)

**Comment by mmicko** [comment]
Easiest way to setup is to use : https://github.com/mamedev/buildtools/

or you can set MINGW64 to point to root path of your mingw installation and
try out

**Comment by balr0g** [comment]
@sum2012 hopefully fixed in https://github.com/mamedev/mame/commit/9fbc9397817a3da58d7abf435e08a9573a9fc643 but I haven't tested on Windows.

**Comment by sum2012** [comment]
I am running windows 7 64 bit
More test
I only can complile with msys64-2016-02-16.exe
msys32-2016-02-16.exe cannot compile (same error as Mingw64 is not set)
I will test again on windows xp after 20 hours

**Comment by sum2012** [comment]
winxp compile ok with msys32-2016-02-16.exe
So remain problem "msys32-2016-02-16.exe cannot compile with win7 64 bit"

**Comment by sum2012** [comment]
@balr0g I reinstall Python 3.4
I confirm fixed Python issue.

**Comment by sum2012** [comment]
@mmicko set  MINGW64 = C:\msys32\mingw32\bin don't work
![2](https://cloud.githubusercontent.com/assets/2177532/14064922/62185ed6-f447-11e5-9ab1-a702209b3351.png)

**Comment by mmicko** [comment]
set MINGW64 = C:\msys32\mingw32\bin is wrong

you are using 32bit tools on 64 bit system

use :
set MINGW32 = C:\msys32\mingw32\bin
make PTR64=0

to create 32bit executable if that is what you wish

**Comment by sum2012** [comment]
@mmicko 
make:*** No rule to make target 'PTR64' . Stop

**Comment by sum2012** [comment]
@mmicko I have an idea to solve .But I need compile finish to ensure I am not wrong

**Comment by sum2012** [comment]
Test finish ok :)
