### ISSUE TITLE
CI is broken and I'm getting spammed about it

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#7417]
The following step in our CI is failing: "Run msys2/setup-msys2@v2"

The CI system has become convinced that this is somehow my fault, so I'm getting e-mail spam about it. Either disable the CI or fix it ASAP.

**Comment by startaq** [comment]
I've removed the "update" step, that should prevent this specific error. See https://github.com/msys2/setup-msys2/issues/82

Unrelated to that, the MSVC build seems to be broken.

**Comment by DavidHaywood** [comment]
I've just ended up redirecting any mail listed as coming from myself to spam.

**Comment by cuavas** [comment]
Unfortunately GitHub lacks features for controlling CI notifications.  There’s no way to only notify on new failures, aggregate notifications, etc.  The only real option is to turn off CI notifications in your own [user settings](https://github.com/settings/notifications).
