### ISSUE TITLE
[question] is multi keyboard support in Linux working?

### ISSUE THREAD

**Issue by massimiliano-brocchini** [mamedev/mame#7420]
Hi,
are multiple keyboards supported under Linux?

I cannot configure mame under linux to distinguish input from multiple keyboards,
I compiled mame from source with NO_USE_XINPUT=0,
I enabled multikeyobard in mame.ini,
I configured keyb_idx1 and keyb_idx2 passig xinput device IDs (tried both with two xinput slave keyboards and with two xinput masters)
mame -v always reports
"Input: Adding keyboard #0: System keyboard (device id: System keyboard)"

I also tried to export SDL_XINPUT_ENABLED=1 (don't know if this makes sense or not) but I didn't see any changes.

Do I need to manually edit default.cfg and add device mapping options?
Does anybody have working configuration files to share?

Thanks
Massi

**Comment by rb6502** [comment]
Multiple keyboards are only supported on Windows at this time.  MAME relies on SDL2 to read the keyboard on Linux, and SDL2 originally was intended to have multiple keyboard support but it was removed before the 2.0 release.  We're currently hoping it comes back for 2.1, but that's up to the SDL maintainers.

**Comment by cuavas** [comment]
At this point, I wouldn’t hold my breath for the feature to be added to SDL.  It would probably be quicker for someone to write an xinput keyboard provider module for MAME.

Anyway, multiple keyboards cannot be logically separated due to the limitations of SDL.  This is a known issue.
