### ISSUE TITLE
Header information for SoftwareList XML 

### ISSUE THREAD

**Issue by newton9278** [mamedev/mame#7427]
Hello,
Would it be possible to add information in the header of the SoftwareList XML files for **more transparency** (version, author, category,date, etc...)
For example :
![Capture1](https://user-images.githubusercontent.com/26112709/98023656-8c287c80-1e07-11eb-9ca1-21b946045092.JPG)

Header XML for Progetto-snaps (example) : 
![Capture2](https://user-images.githubusercontent.com/26112709/98023663-8df24000-1e07-11eb-8486-00b41f0aa66b.JPG)

I hope you can respond favorably to this request
Best Regards

**Comment by cuavas** [comment]
The only versioning information you get is source control revision or tag, and the release it came from.  Authors come from version control history, no software list has a single author as such.

**Comment by newton9278** [comment]
Hello, 

Could we at least have the Version that displays when MAME goes out ?
BR
