### ISSUE TITLE
hey guys input issues with pacland

### ISSUE THREAD

**Issue by grant2258** [mamedev/mame#7433]
left and right are mapped to buttons dont have schematics or anything and I know you guys do things properly. Feel free to close this it just informational for yourselves

https://github.com/mamedev/mame/blob/96490888396584845d0fd923b44c3b7611e56f8e/src/mame/drivers/pacland.cpp#L370-L380

**Comment by cuavas** [comment]
This is correct.  Pac-Land uses buttons to move left and right, not a joystick.  It’s possible to press both left and right at the same time.  You can remap the controls if you don’t like it.

**Comment by cuavas** [comment]
Photo of Pac-Land panel for reference: http://www.ukvac.com/forum/uploads/416/pacland.png

**Comment by grant2258** [comment]
not a problem at all thought it could be something i missed. I like how you guys stick with the jamma layouts for authenticity. Our local arcade must have used a bootleg it had a joystick sorry for the bother.

**Comment by Pernod70** [comment]
Pac-Land was one of the games I used to play in the 80's and in the UK always had a joystick. I distinctly remember continually nudging the joystick right for the springboard water jumps.

**Comment by grant2258** [comment]
Yea same here up Scotland again could have been bootlegs we had nrt sure if there  was a joystick version in the scheme of things its not that hard to fix anyway.

**Comment by smf-** [comment]
I don't think the UK got the official control panel...

http://www.ukvac.com/forum/pacland-dedicated-cabs_topic331403.html

"well, the US-made cabinet (midway) used buttons.. the game was never
officially distributed here by any of the major companies, but namco did
sell kits in the UK, and these would likely have been played on
joystick-cabs, and is likely what you would have played."
