### ISSUE TITLE
Unimplemented SM8521 instructions

### ISSUE THREAD

**Issue by simontime** [mamedev/mame#7451]
[Opcodes 0x5a and 0x5b aren't implemented yet in MAME.](https://github.com/mamedev/mame/blob/master/src/devices/cpu/sm8500/sm85ops.h#L1285L1336)

They're just `cmp` and `mov` respectively, with additional addressing modes as listed in the SM8521 datasheet.

Here's the instruction encoding based on the machine code emitted by Sharp's SM85 assembler:

0x5a:
```
01011010 00000XXX YYYYYYYY          = cmp @rX,#Y
01011010 01000XXX YYYYYYYY          = cmp (rX)+,#Y
01011010 11000XXX YYYYYYYY          = cmp -(rX),#Y
01011010 10000XXX YYYYYYYY ZZZZZZZZ = cmp Y(rX),#Z
```

0x5b:
```
01011011 00000XXX YYYYYYYY          = mov @rX,#Y
01011011 01000XXX YYYYYYYY          = mov (rX)+,#Y
01011011 11000XXX YYYYYYYY          = mov -(rX),#Y
01011011 10000XXX YYYYYYYY ZZZZZZZZ = mov Y(rX),#Z
```

**Comment by Robbbert** [comment]
We'd also need the number of cycles used by each variant, and also the affect on the flags. Do you have that information?

**Comment by simontime** [comment]
Unfortunately I don't have the cycle information (yet, I am working with someone with hardware knowledge to get code execution on actual game.com units!), but I can hazard some educated guesses w/r/t the flags:
`mov` affects no flags in any addressing mode, so I assume the same for these.
`cmp` affects `C`, `Z`, `S` and `V` in every other addressing mode, so I assume the same for these too.

**Comment by Robbbert** [comment]
I'll work on this then, and do some testing.

**Comment by Robbbert** [comment]
Done.
