### ISSUE TITLE
[Bug] atarisy2.cpp games endlessly stuck in demo loop.

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#7462]
0.226 (mame0226-195-g4a2e49d2c7e)

1. Launch 720, APB, Super Sprint, or Paperboy, etc.
2. Observe the graphic initialization routine doesn't seem to finish, it just loops over and over.

Observed with afternoon's pull build, wanted to give it another day and fresh/clean make.
Works fine in release .226.
Win10 x64

**Comment by Osso13** [comment]
Right now MAME is very unstable, due to some big memory changes. Should be all fixed before 0.227 is released.

**Comment by john-iv** [comment]
Fixed, closing against 0.226 (mame0226-282-g48d1f0de37f).
