### ISSUE TITLE
Mystic Warriors: unable to apply "cheatinit" on certain memory range, "wpset" works fine

### ISSUE THREAD

**Issue by FredYeye** [mamedev/mame#7494]
I'm trying to inspect memory in mystic warriors (_mystwarrj_, specifically), but i'm having problems doing so.
I tried _cheatinit uw,0x407030,0x10_ on the maincpu to watch the memory region i was interested in, but it says _no writable bytes found in this area_. However, doing _wpset 0x407030,0x10,w_ works as expected, and triggers on write to this region.

_cheatinit ub_ marks 65536 bytes, so i'm guessing it's only looking at 0x200000 - 0x20FFFF, and ignoring 0x400000-0x40FFFF and 0x700000 - 0x70FFFF. I don't know how to tell it to include those areas.

I'm a novice when it comes to mame debugging, so it's entirely possible i'm just doing something wrong.

Repro (should be clear already but):
Start mystic warriors with debug tools (i did _mame64 -debug mystwarrj_ here).
Try to apply cheatinit on memory range 0x400000-0x40FFFF on the maincpu.

**Comment by galibert** [comment]
There's no ram at 4xxxxx, only handlers.  That's why you can't cheatinit on
it.

  OG.

**Comment by FredYeye** [comment]
Hmm, alright. Not sure what "handlers" mean in this context, but the values i'm looking for are not present in the main ram, only in the 0x400000 range which makes them unscannable by mame. I can work around it by using cheatengine to search there myself.
Thanks for the quick answer!
