### ISSUE TITLE
Wrong IBM 5170 entry

### ISSUE THREAD

**Issue by arcadehistory** [mamedev/mame#7505]
Hello,

While investigating the games on the ibm5170 softlist, I noticed that the game Cruise for a Corpse (cruisecr) should appears in the ibm5150 and not on the ibm5170.

Here you can see the front cover of the IBM PC game : https://www.arcade-history.com/images/goodies/132629_1.jpg

As you can see, it is supported by "IBM PC / XT / AT..." and not AT only. So, it should be switched from the ibm5170 to the ibm5150 softlist.

For info:
IBM PC = ibm5150
IBM XT = ibm5160 (basically an ibm5150 with a harddrive), goes to the ibm5150 softlist for now. (no 5160 SL for now)
IBM AT = ibm5170

I'll submit other switchable entries if I found them.

Best regards,

**Comment by arcadehistory** [comment]
Another wrong 5170 entry is "sserv2" (Silent Service II), it already appears in the ibm5150 as "silents2_35". Same CRC, same SHA1.  So, "sserv2" can be removed from the ibm5170.

It was originaly published in the USA as a dual media release (3.5 and 5.25 in the same box), and IBM PC/XT compatible (ibm5150 in MAME). see first cover here => https://www.mobygames.com/game/dos/silent-service-ii/cover-art

**Comment by DopefishJustin** [comment]
Fixed, thanks.
