### ISSUE TITLE
Disabling a memory view doesn't necessarily work

### ISSUE THREAD

**Issue by ajrhacker** [mamedev/mame#7516]
In tim100.cpp, I added a view to switch the entire `AS_PROGRAM` space to read from `tim100_state::dma_r` (which pushes all bytes read into the CRTC) if and only if SOD is 1; otherwise, `AS_PROGRAM` should handle identically to `AS_OPCODES`. This would be prettier if the `AS_OPCODES` map could just be included within `AS_PROGRAM` rather than be duplicated within the view; however, making that modification and changing `m_dma_view.select(1)` to `m_dma_view.disable()` results in the operands for the first JMP instruction being 00 (despite `map.unmap_value_high()`), killing the system.

When that buggy change is made, the debugger memory view of the program space reveals some additional weirdness is going on. The code ROM is mapped starting at 0x2000, even though that area is clearly defined as RAM. Furthermore, examining the ranges starting at 0x6000 or 0x8000 (where the 8251 USARTs live) causes a segmentation fault.

**Comment by cuavas** [comment]
Please attach a diff here showing the code that doesn’t work.

**Comment by ajrhacker** [comment]
[tim100_diff.txt](https://github.com/mamedev/mame/files/5600012/tim100_diff.txt)
