### ISSUE TITLE
amigaocs_flop - Eye of the Beholder II - Legende von Darkmoon

### ISSUE THREAD

**Issue by ArcadeShadow** [mamedev/mame#7522]
The set [eyebeho2g] Eye of the Beholder II - Legende von Darkmoon (Ger) should be clone of the:
[eyebeho2] Eye of the Beholder II - The Legend of Darkmoon (Euro)
and not:
[eyebehol] Eye of the Beholder (Euro)

**Comment by Robbbert** [comment]
Corrected, thanks.
https://github.com/mamedev/mame/commit/b1131c0f093b5c8ec67588841bd3588e921a0fc4
