### ISSUE TITLE
Exerion in Cocktail mode: bullets last only a few pixels

### ISSUE THREAD

**Issue by maziac** [mamedev/mame#7529]
Mame 0.226.

1. Load Exerion
2. Change DIP switches to cocktail mode
3. Exit/Enter mame Exerion again
4. Enter 2 coins
5. Start a 2 player game
6. If it's 2nd player's turn try to shoot with both buttons (both bullets)

Result:
You can see the bullets but they last just for a few seconds.
For player 1 the bullets reach the top of the screen.
For player 2 (flipped/cocktail mode) the bullets hardly reach the middle of the screen.

**Comment by MooglyGuy** [comment]
Github Issues for this project should only be filed on broad issues that affect the emulator core itself.

For game-specific bug reports, please make use of MAMETesters: http://mametesters.org/

**Comment by maziac** [comment]
I would like to but, sorry, I'm not able to create an account at the same testers site.

**Comment by MooglyGuy** [comment]
Why not?

**Comment by maziac** [comment]
When registering I get a confirmation mail.
When clicking that link I get:
![Bildschirmfoto 2020-12-07 um 07 44 51](https://user-images.githubusercontent.com/3081973/101318201-36108400-3860-11eb-8c3f-b0794a037dff.jpg)

I can do that again and again.
No success.

**Comment by Tafoid** [comment]
Browsers tend to chop up the authorization code link so you have a link clickable, but there is text visible under the link
Copy the entire text and send that - don't just blindly click the link.

Do that and there should be no troubles.

**Comment by maziac** [comment]
I know.
I did this already.
Same result.

**Comment by Tafoid** [comment]
Sorry for the trouble.  You have to make sure there aren't any spurious linefeed or other characters in your copied text.

Best way I've found to do that is to copy and paste into a notepad/text file and then make sure the two sections of code do not have anything in between them.  I had to do this earlier this week for someone already, so I know how it can be difficult.   It shouldn't be - blame the browsers to making links out of something which obviously isn't the intent.

All that said I can confirm there are flip screen issues and I'll see it get logged even if you cannot get the confirmation done.

**Comment by maziac** [comment]
If I try to sign-up again I get this:
![Bildschirmfoto 2020-12-07 um 18 54 55](https://user-images.githubusercontent.com/3081973/101386685-cfba4e80-38bd-11eb-8f13-0236c342976f.jpg)

So the system has created an account for me. But I couldn't verify it yet.
If I try to reset the password I get an email. If I enter that url in the browser (copy/paste) I get:

![Bildschirmfoto 2020-12-07 um 18 53 49](https://user-images.githubusercontent.com/3081973/101386904-0f813600-38be-11eb-97d8-b04417e5879d.jpg)
![Bildschirmfoto 2020-12-07 um 18 53 44](https://user-images.githubusercontent.com/3081973/101386934-190a9e00-38be-11eb-9a20-99c2eb241307.jpg)

**Comment by Tafoid** [comment]
I'll contact you privately via email to resolve this.

**Comment by Tafoid** [comment]
Bug now tracked at mametesters.org:
https://mametesters.org/view.php?id=7811
