### ISSUE TITLE
Apple2 SCSI card allows reads from $C0nA

### ISSUE THREAD

**Issue by gorlik** [mamedev/mame#7544]
MAME incorrectly allows reads from C0nA.
According to the apple documentation C0nA is write only.
From the schematics I don't see a way to retrieve the content of the 74LS273.

I also checked on my IIgs with the card in slot7
*c0f8.c0ff
00/c0f8:00 80 FF FF FF FF 7F FF
*c0fa:00
*c0f8.c0ff
00/c0f8:00 80 FF FF FF FF 7F FF

**Comment by rb6502** [comment]
Thanks!  Resolved in https://github.com/mamedev/mame/commit/7f22d342658bbde72184c12caa8a62bd28ba4ed4
