### ISSUE TITLE
Apple2 weird slot behavior

### ISSUE THREAD

**Issue by gorlik** [mamedev/mame#7566]
mame 0226
Apple IIgs rom3 with scsi card in slot 7. No devices attached. (I went in the menu and detach both the cdrom and the harddisk, then reset the machine).
Go to the monitor:
*c0f0.c0ff
00/C0F0:00 00 00 00 00 08 00 00
00/C0F8:00 80 00 FF FF FF 00 FF
so far so good vs a real rom3 machine with the apple scsi card. C0FA is fixed by #7544 (thanks rb6502)  C0FE should be 7F but it's likely a don't care as the only useful bit in the register is bit 7.

*cfff:0
*cc00.cc08
00/CC00:00 00 A0 A0 A0 00 00 C3
on my IIgs this returns:
00/CC00:FF FF FF FF FF FF FF FF
which for what I understand seems to match the documentation (i.e. disable all slot roms)

*c700.c70f
00/C700:00 00 00 00 00 00 00 00
this also does not match the IIgs which is the start of the scsi ROM
00/C700:A2 20 A2 00 A2 03 A2 00

*c0fa:0
*cc00.cc07
00/CC00:04 B1 28 91 2A 88 10 F9
which seems odd as it should also be the beginning of the scsi ROM as shown on real HW:
00/CC00:A2 20 A2 00 A2 03 A2 00

The SCSI emulation works as I can boot HDD images with no problems but I am puzzled by the behavior.
I uncommented the debug logging in the driver and I see reads and writes to the card registers/card RAM/ROM during boot.
However once I go to the monitor only the C0nx accesses seem to go through.

It's likely i am missing something and I would really appreciate if anyone could point it out.

**Comment by rb6502** [comment]
Thanks for the report, I've verified the weirdness you describe.

**Comment by rb6502** [comment]
Thanks again!  I have addressed the 3 issues with slot mapping described here (and slightly simplified the driver and made it use less CPU in the process).  Those changes are in https://github.com/mamedev/mame/commit/9dee87654a7b7adf74dd8e18c456b0a9dc4dfed1 and https://github.com/mamedev/mame/commit/4ccd61f086c96bc4e2a765c08477c624b3c9ee01
