### ISSUE TITLE
BGFX partially working on multi-screen games on DISPLAY1

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7570]
Hi,

I found a problem in BGFX and I'm not sure if I'm missing something in mame.ini, but please look at screenshot what's happening.
If I try to run the ROM warriorb, which is 2-screen game with BGFX enabled on 1 physical monitor (DISPLAY1), ONLY the left emulated screen has BGFX applied, while the right screen has no BGFX at all.

Attached is my mame.ini (zipped) in which I have enabled BGFX by following settings:

#
# OSD VIDEO OPTIONS
#
video                     bgfx
numscreens                1
window                    0
maximize                  1
waitvsync                 0
syncrefresh               0
monitorprovider           auto

#
# BGFX POST-PROCESSING OPTIONS
#
bgfx_path                 bgfx
bgfx_backend              auto
bgfx_debug                0
bgfx_screen_chains        crt-geom
bgfx_shadow_mask          slot-mask.png
bgfx_lut                  
bgfx_avi_name             auto

Those settings work for each 1-screen game.

Can anybody tell me how to enable BGFX for the right emulated screen?

[mame.zip](https://github.com/mamedev/mame/files/5719733/mame.zip)
![a](https://user-images.githubusercontent.com/75265542/102693614-1c861980-421c-11eb-80dd-72816bbef656.jpg)

PS: I don't know if this issue has something to do with it: https://github.com/mamedev/mame/issues/4073

best regards

**Comment by MooglyGuy** [comment]
Your BGFX options are incorrect. For multi-screen games, you need to specify which effect to apply to each screen, like so:

bgfx_screen_chains crt-geom,crt-geom
