### ISSUE TITLE
Memory views aren't saved

### ISSUE THREAD

**Issue by ajrhacker** [mamedev/mame#7579]
I've noticed that the new implementation memory views has no code to support save states. This is the likely cause of Tafoid's observed save state regressions in simpsons.

The easiest way I see involves `register_postload`, something which Aaron has wanted to eliminate at least for drivers and devices. One could also throw up one's hands and implement save state restoration at the device level, but I believe that approach scales too poorly.

**Comment by galibert** [comment]
Damn, I forgot.  Not sure why Aaron tried to remove postload, because the
concept is pretty much required for everything that involves pointers.
Fixing it.

  OG.

**Comment by galibert** [comment]
Fixed in cf472744a2696e1c91756c7a14743a74b00a85eb
