### ISSUE TITLE
window mode resolution change error

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7582]
Hi

If I try to change the resolution of window mode by using this command line option:

-window -switchres -resolution 640x480

I get following error by MAME:

![afbeelding](https://user-images.githubusercontent.com/75265542/102815591-dfad5480-43cc-11eb-911c-66c71eb47ac2.png)

Unknown option -res , while I used -resolution

Is this a bug and if not, how to change a window mode to a certain resolution?

**Comment by MooglyGuy** [comment]
MAME does not pop open modal dialogs. You are obviously not using an official build of MAME as found on http://mamedev.org/ and as such we do not support it.
