### ISSUE TITLE
cc1plus.exe: out of memory allocating 65536 bytes

### ISSUE THREAD

**Issue by Hydreigon223** [mamedev/mame#7590]
I (mostly) can't compile mame properly anymore and starts to get this error when Mame gets to compiling the emumem related files. Tried this under winenv32 and mingw64. The flags OPTIMIZE=3 SYMBOLS=1 SYMLEVEL=1 REGENIE=1 -j5 didn't work either. Updating GCC to the latest didn't work as well. For the rare instances Mame did compile successfully, the application size would be over 400mb as opposed to the usual ~273mb. This is from a computer with an i5 8600k with 16GB of ram.

My best guess would be what caused this would the emumem cleanup: https://git.redump.net/mame/commit/?id=b8c338858a101d14308c64c87b0f714db4f05326. This could be the reason why 0.227 was delayed to December of 2020 but this issue still happens to me for some reason.

**Comment by happppp** [comment]
FYI this is not a user support forum, but I won't leave you empty handed:

Is it a 32bit build? try 64 bit.
Do you need symbols? If not, disable them.
Try less threads, eg. -j3

**Comment by cuavas** [comment]
It’s no longer possible to do a complete MAME build with line number symbols using 32-bit tools.  (There are tricks to allow building only certain files with line number symbols, but it’s one of those things where if you can understand how to do it, you’ll be able to work it out yourself.)  The trouble with the MSYS2 build environment is you can only build a 32-bit application using 32-bit tools.

If you really need 32-bit MAME for Windows, you can cross-compile using MinGW tools on a 64-bit Linux installation, or you can build with Visual Studio using the 64-bit toolchain.  Keep in mind that Visual Studio builds perform quite poorly.

Building MAME is resource-intensive.  Ensure you have swap enabled, and reduce the number of concurrent jobs if you’re hitting RAM or I/O bottlenecks.
