### ISSUE TITLE
apple2 ingame key problem

### ISSUE THREAD

**Issue by arcadehistory** [mamedev/mame#7598]
I encoutered a strange problem/bug trying to play a game from the apple2_flop_clcracked softlist.

Questron (cleanly cracked)
The game loads fine, then ingame, the LEFT key seems to be pressed. Your hero is heading to the left indefinitely.

I tried with many different compatible machines (apple2, apple2e, apple2efr, apple2gs and even the las128e2), the same bug appears.

HOW TO REPRODUCE:
- Load questron via for example :  "mame64.exe apple2e questron".
- Once in the menu, choose  "3. Play a Game".
- Then, choose "4. Delete a character from disk" (the dump is not so clean since 8 characters are already created on the disk).
- Put FRED as character name to delete it.
- Once deleted, choose "1. Start a new character".
- Name your character with the name of your choice.
- Then, skip the introduction by pressing a key.
- Insert "Game Disk I" in the MAME file manager (TAB menu) when asked.
- The game will loads and once loaded, your hero will go to the left indefinitely.

**Comment by rb6502** [comment]
Thanks, confirmed!  I really appreciate the in-depth steps on reproducing it.  I'll let you know what I find out.

**Comment by rb6502** [comment]
So the thing is Questron supports a joystick to move.  MAME currently defaults to nothing being plugged into the game I/O port, which causes the game to think the joystick is pushed all the way left.  You can plug in an emulated joystick with **-gameio joy** or select Slot Devices from the Tab menu (same place as the File Manager) and change "gameio" to "joy".

Let me know if that works for you.

**Comment by arcadehistory** [comment]
Yes, the problem is fixed by choosing joy in the gameio. It works here too.

**Comment by rb6502** [comment]
Great!
