### ISSUE TITLE
Feature Req: Rename NTSC settings

### ISSUE THREAD

**Issue by NULUSIOS** [mamedev/mame#760]
As NTSC seems to be related to analog system distortions in general, it named badly (esp. for people not in US or Japan).
Maybe the parameters should be replaced with a more generic term ("radio"? "modulation"?)...

I suspect if such a change takes place, it would need to parse both old names and new names for a few versions until phase out.

**Comment by cuavas** [comment]
It's called NTSC because simulates an NTSC receiver.  A simulation of a PAL or SECAM receiver would produce different artifacts.
