### ISSUE TITLE
atarisy1 erro

### ISSUE THREAD

**Issue by manotroll** [mamedev/mame#7603]
games with atarisy1 are not running Marble Madness
is there any way to fix this?

**Comment by cuavas** [comment]
This is not a help forum, and Marble Madness does in fact run.

**Comment by Tafoid** [comment]
You can do two things - use released 0.226 or use binary based on most recent Git source (0.227 to be released in a few days).  Delete NVRAM in case you are still having troubles.  Avoid reports using out of date Git sources.

**Comment by manotroll** [comment]
> You can do two things - use released 0.226 or use binary based on most recent Git source (0.227 to be released in a few days). Delete NVRAM in case you are still having troubles. Avoid reports using out of date Git sources.


so I'll wait a few days to download this update

**Comment by manotroll** [comment]
https://i.imgur.com/2HP7Liu.png
the problem continues
is there any way to log a report
