### ISSUE TITLE
AtariSy1 LSI bios file changed to bad version

### ISSUE THREAD

**Issue by AaronLiddiment** [mamedev/mame#7609]
On the 13th May 2020 the following LSI rom was changed from
ROM_LOAD16_BYTE_BIOS(2, "136032.115.j10", 0x00001, 0x04000, CRC(7275b4dc) SHA1(0896ab37ea832a1335046353612c1b4c86d8d040) )
to
ROM_LOAD16_BYTE_BIOS(2, "136032.115.j10", 0x00001, 0x04000, CRC(9af9fe29) SHA1(1d5077662e4111ece9f8a5124394dad8b1abdc13) )

This is not valid, I have 2 sets of original 114/115 Atari eproms both of which match the original file. If you run Marble Madness with this updated rom you are not able to enter the settings! It just keeps resetting.

**Comment by happppp** [comment]
Ok! Thanks for letting us know, it will be corrected.

**Comment by manotroll** [comment]
through the terminal he complains more normally runs
mame64 marble
136032.115.j10 WRONG CHECKSUMS:
    EXPECTED: CRC(9af9fe29) SHA1(1d5077662e4111ece9f8a5124394dad8b1abdc13)
       FOUND: CRC(7275b4dc) SHA1(0896ab37ea832a1335046353612c1b4c86d8d040)
WARNING: the machine might not run correctly.
gdbstub: debugger not enabled
gdbstub: debugger not enabled
Average speed: 100.01% (30 seconds)
136032.115.j10 WRONG CHECKSUMS:
    EXPECTED: CRC(9af9fe29) SHA1(1d5077662e4111ece9f8a5124394dad8b1abdc13)
       FOUND: CRC(7275b4dc) SHA1(0896ab37ea832a1335046353612c1b4c86d8d040)
WARNING: the machine might not run correctly.
gdbstub: debugger not enabled
gdbstub: debugger not enabled
Average speed: 100.00% (408 seconds)

try to run through the terminal to see if your dump works

**Comment by happppp** [comment]
The correction is in MAME 0.228.
