### ISSUE TITLE
0.227 GBFX lut.json not working

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7617]
If you apply lut.json as BGFX screen chain, the emulated image is completely black.

**Comment by MooglyGuy** [comment]
What backend?

**Comment by the-namelessone** [comment]
#
# BGFX POST-PROCESSING OPTIONS
#
bgfx_path                 bgfx
bgfx_backend              auto
bgfx_debug                0
bgfx_screen_chains       lut
bgfx_shadow_mask          slot-mask.png
bgfx_lut                  
bgfx_avi_name             auto

**Comment by MooglyGuy** [comment]
So you're using lut.json as a screen chain but not supplying a LUT texture. Also not a MAME bug.
