### ISSUE TITLE
0.227 BGFX different screen chains not working

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7618]
The following BGFX screen chains give unplayable distorted image when applied:

pillarbox_left_horizontal
pillarbox_left_vertical
pillarbox_right_horizontal
pillarbox_right_vertical

**Comment by MooglyGuy** [comment]
Those screen chains are intended to be applied to duplicates of the main screen to the left and right, in order to provide a subdued infill when playing 4:3 games on a 16:9 screen. They're working just fine.
