### ISSUE TITLE
0.227 -window resolution switching not working

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7620]
If I run any game using following command line switch:

-window -switchres -resolution 800x600

the game is run in window mode but uses the desktop resolution.
No matter what resolution is specified after the "-resolution" option, the game ALWAYS runs in window mode @ desktop resolution.

Is it not possible to specific a window mode resolution maybe?
At least: it doesn't work and MAME gives no error message.

**Comment by the-namelessone** [comment]
So a summary:

- window mode works
- switchres on window mode doesn't

**Comment by MooglyGuy** [comment]
This is an unfortunately long document, but it describes -switchres as being applicable specifically to full-screen mode: https://docs.mamedev.org/commandline/commandline-all.html

Additionally, the switchres option in the INI file is under a heading which refers to full-screen options.

That said, you're 100% correct in your observation that the use of -switchres appears to suppress the -resolution option when running in windowed mode.

I agree that this is a bug, so I'd prefer to leave this one open until I can resolve it.

**Comment by MooglyGuy** [comment]
I just double-checked, and I can't actually reproduce the issue anymore, though I was able to a month or two ago, which was the source of my response.

If it's not too much trouble, can you upload your entire mame.ini file (if you have one) to somewhere like Gist so that I can look at it more closely?

**Comment by the-namelessone** [comment]
Thank you so much!

I use window mode to run games in their native resolution.

In the meanwhile, is there a way (a -video mode option) to use to run a game fullscreen but in NATIVE resolution I specify myself using -resolution but NOT enlarging/stretching the emulated screen to the whole monitor area? (which I now get no matter what -video output)

So I mean by this: black borders on top, bottom, left and right must appear (to fill the unused pixels of the screen) around the emulated screen which is running in the resolution I specified
Is this possible and if yes, can you give me the full command line option string which enables this?

I can't find a way to do this.

**Comment by the-namelessone** [comment]
I use no mame.ini file for the -window command line option.

**Comment by the-namelessone** [comment]
Can I ask why you want mame.ini?
I understand command line arguments have HIGHER priority then mame.ini
But for this test, I have no mame.ini

**Comment by the-namelessone** [comment]
An additional question: if you use -window in combination with -video (for example openg), is the -video setting "opengl" applied INSIDE the window too or is the -video option only for full screen?

So basically: are -video options applied in window mode too?

**Comment by the-namelessone** [comment]
Answer my questions.
You think I have days to wait for you n00bs?
This is an issue and even if it's one, youdon't fix it...

**Comment by the-namelessone** [comment]
This issue -switchres -resolution 800x600 is not working for any video mode: opengl, bgfx, software, ...
