### ISSUE TITLE
mame 0.227: macos build failure: src/lib/netlist/solver/nld_solver.cpp: aligned deallocation function of type 'void  (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer

### ISSUE THREAD

**Issue by mascguy** [mamedev/mame#7629]
When building Mame for the MacPorts project, compilation failures are occurring for MacOS releases prior to 10.14.

Source file `src/lib/netlist/solver/nld_solver.cpp` seems to be the problem, with the following:

```
In file included from ../../../../../src/lib/netlist/solver/nld_solver.cpp:10:
In file included from ../../../../../src/lib/netlist/solver/nld_ms_direct.h:16:
../../../../../src/lib/netlist/solver/nld_matrix_solver_ext.h:21:8: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
         class matrix_solver_ext_t: public matrix_solver_t
               ^
```

The complete list of compilation errors is attached, below.

Note that Mame 0.226 builds and runs on MacOS releases from 10.6, up to and including 10.15. (Support for Big Sur is being worked on.)

Is this a known/expected issue?

[mame-0227-build-error-10.12.txt.gz](https://github.com/mamedev/mame/files/5761233/mame-0227-build-error-10.12.txt.gz)

**Comment by Robbbert** [comment]
10.14 is the minimum version. See https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=118262#Post118262

**Comment by Robbbert** [comment]
This information was forwarded to me.  

> ARCHOPTS_CXX = -fno-aligned-allocation -DTARGET_OS_OSX

> in the makefile fixes the build on old machines

**Comment by rb6502** [comment]
That workaround reportedly produces a defective binary.  Games using net lists or netlist audio will randomly crash.  I'm serious that we don't support macOS below 10.14 starting with MAME 0.227, and I plan to start taking advantage of that to shut up deprecation warnings in the next year or so.

**Comment by the-namelessone** [comment]
Why does mamedev.org not provide compiled version of mame for the latest (or close to latest) MacOS rreleases?
Only windows binaries are provided, so to avoid all these issues provide COMPILED binaries for SPECIFIC MacOS releases.

Why are windows binaries ONLY provided anyway, as you promote mame as CROSS platform?
Well start compiling then!

best regards

**Comment by MooglyGuy** [comment]
Is this how you think "contributing" to an open-source project is supposed to go? Abjectly ordering the developers around with statements like "Well start compiling then"?

**Comment by the-namelessone** [comment]
A cross platform software which ONLY gives windows-ONLY binaries is a really funny project :-)
That's the same as: it's cross platform, but we OURSELVES have no idea how to compile it properly for the other supported OS.
The question above proofs it's indeed not really cross platform. Many issues on many version of the target OS. You can hardly call it cross platform then.

So either only support windows or provided binaries for ALL 3 platforms like true cross platforms software does (google for examples)

**Comment by the-namelessone** [comment]
Please take a not on mamedev.org and see for yourself what 3 OS logos are placed there, including "download" button.
I think GOD did not put them there, but the developers did or the maintainer of mame?

So if you say A, then say B too.
You guys are only saying A...

**Comment by MooglyGuy** [comment]
I say you're rapidly wearing out your welcome and have absolutely no sense of etiquette.

**Comment by balr0g** [comment]
@mascguy I just did a test compile of latest Git (specifically, commit `3f1d4bbc76dbca602ffa0fd79a4c9835cdcbad38`) on a Mac running macOS 10.13.6 and I did not have this failure. I'll test with 0.227 next, but is it possible that the diagnostic is indicating the wrong macOS version for when this feature was introduced?

**Comment by mascguy** [comment]
> @mascguy I just did a test compile of latest Git (specifically, commit `3f1d4bbc76dbca602ffa0fd79a4c9835cdcbad38`) on a Mac running macOS 10.13.6 and I did not have this failure. I'll test with 0.227 next, but is it possible that the diagnostic is indicating the wrong macOS version for when this feature was introduced?

I was able to build successfully on MacOS 10.13 too. Based on some initial research, it sounds like 10.13 supports it, and the message is simply wrong. However, I can confirm that this build failure occurs on MacOS 10.12... and it's a problem on 10.12 and prior versions.

That being said, I've been chatting with my MacPorts colleagues. And apparently, we have a way to replace the system libc++, with a modern version supporting the latest Clang/LLVM toolchain. Not only that, but said replacement is possible from Big Sur, all the way back to 10.6. So if Mame doesn't depend on newer MacOS API calls, we'll be able to support both C++ 2017, and Mame 0.227, back to 10.6. (Mame 0.226 builds and runs from 10.6 through 10.15, via MacPorts.)

So that's great news!

We're still figuring out the logistics, but we have a long-term solution. Do you folks know whether future Mame releases will depend on newer MacOS API calls?

**Comment by balr0g** [comment]
> That being said, I've been chatting with my MacPorts colleagues. And apparently, we have a way to replace the system libc++, with a modern version supporting the latest Clang/LLVM toolchain. Not only that, but said replacement is possible from Big Sur, all the way back to 10.6. So if Mame doesn't depend on newer MacOS API calls, we'll be able to support both C++ 2017, and Mame 0.227, back to 10.6. (Mame 0.226 builds and runs from 10.6 through 10.15, via MacPorts.)

Some time ago I asked about this in the MacPorts IRC and was told that while it is possible, it was avoided as it can lead to problems. If this plan will go forward, though, that's great to hear, partly because software other than MAME is likely to require C++17 and C++20 down the road, and also because MAME will be using more C++17 features that require standard library support in the near future.

> We're still figuring out the logistics, but we have a long-term solution. Do you folks know whether future Mame releases will depend on newer MacOS API calls?

MAME depends on a minimal set of macOS API calls — it mainly relies on SDL2 for platform abstraction and optionally bgfx for rendering. I would expect to see some use of newer APIs for features that require it, such as JIT on Apple Silicon, but it should be a limited subset. Overall I don't expect this to impact older macOS versions.
I am not sure what the long-term plans involving graphics/rendering are — though I do hope that a basic renderer is available far in the future.

**Comment by cuavas** [comment]
There really isn’t anything else to say here.  MAME is a fairly forward-looking project.  There’s a minimum level of C++17 required right now, and we’ll move to newer standards when they become widespread.  MAME may use newer macOS APIs in the future if it provides benefits in functionality or maintainability.

**Comment by mascguy** [comment]
> There really isn’t anything else to say here. MAME is a fairly forward-looking project. There’s a minimum level of C++17 required right now, and we’ll move to newer standards when they become widespread. MAME may use newer macOS APIs in the future if it provides benefits in functionality or maintainability.

Sounds good. If there's anything that the MacPorts project can do to help support older MacOS releases, let me know!
