### ISSUE TITLE
0.227 compiling without MSYS2 ?

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7630]
Is there a way to compile MAME on windows without MSYS2 by using ONLY GCC 10 or 9 (or what version supported)?
(I can't find any information on what GCC is supported)

So I mean not following the default way here https://www.mamedev.org/tools/

If yes, how to do it?
My current attempts all failed because there is just no documentation for windows compiles, except MSYS2.

thx

**Comment by the-namelessone** [comment]
The same question for linux: what's the minimum supported GCC Version and where are instructions to compile it?

thx

**Comment by happppp** [comment]
Your question is not an issue with MAME. Github issues is not meant for user support. Therefore I will close this.

Yes it is possible, there are many ways to compile MAME and we won't document each and every one of them.
Some of the methods are described here: https://docs.mamedev.org/initialsetup/compilingmame.html and it also mentions the minimum GCC version.
