### ISSUE TITLE
0.227 -video opengl -switchres not working

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7634]
The following command line option is not working on 0.227

-video opengl -switchres -resolution 640x480

The game runs in desktop resolution no matter what resolution you specifiy.

This is an issue, don't close it please.

**Comment by the-namelessone** [comment]
So using -switchres -resolution 640x480 has no effect at all in combination with -video opengl

**Comment by galibert** [comment]
Open another duplicate issue and you won't open issues anymore.

**Comment by the-namelessone** [comment]
d

**Comment by the-namelessone** [comment]
i warn you about threatening me on github
i can post AS MANY ISSUES I WANT
YOU CANT DO ANTYHING ABOUT THAT

LAST WARNINGç

**Comment by MooglyGuy** [comment]
I have to hand it to you, Wellington, you actually managed to fool us for a few days this time. But once you start slamming your fists on the keyboard in all-capitals, it becomes just too obvious. Goodbye, Wellington.

**Comment by the-namelessone** [comment]
Who is Wellington?

**Comment by the-namelessone** [comment]
you guys are morons :)

**Comment by MooglyGuy** [comment]
Oh, sorry, I mistook you for another annoying person who we've had to repeatedly ban. It took a while, but you finally made it obvious that you're repeatedly-banned psychopath JessicaJones, or one of "her" many alternate accounts. Goodbye, Jessica.
