### ISSUE TITLE
apple2e: Lock up during mouse initialization

### ISSUE THREAD

**Issue by inexorabletash** [mamedev/mame#7643]
MAME 0.227 (via https://github.com/ksherlock/ample wrapper) on macOS Catalina.

Repro:
1. Grab a disk image that uses a mouse, e.g. [Dazzle Draw](http://mirrors.apple2.org.za/ftp.apple.asimov.net/images/productivity/graphics/dazzle_draw/dazzledraw1.dsk)
2. `mame64 apple2e -skip_gameinfo -window -nomax -sl2 mouse -flop1 dazzledraw1.dsk -nothrottle`

The emulated system freezes when the mouse is initialized. Without `-sl2 mouse` the app detects no mouse and does not freeze. From the perspective of the emulated app, the call to INITMOUSE never returns.

Initially mentioned in #7640 where @rb6502 writes: 

> I tested A2D and Dazzle Draw with the mouse card not too long ago (maybe a year ago or so) and it was fine. Now it locks up waiting on some handshake from the 68HC05, it appears.

**Comment by rb6502** [comment]
Narrowing this down now.  0.218 (released late February 2020) is fine, so there's a limited set of changes it could be.

**Comment by rb6502** [comment]
It's fine in 0.226 so that narrows it down even more.  Heh.

**Comment by rb6502** [comment]
I have verified the problem as this change: https://github.com/mamedev/mame/commit/3395aa5a88d41ac9069932d248aaa2c2248a80b4 and notified the author.

**Comment by rb6502** [comment]
Fixed in https://github.com/mamedev/mame/commit/486a4e5ca3e7f2e9d469fcc1f6dc94292a53f55b

Thanks @ajrhacker !
