### ISSUE TITLE
snes NTSC games run on snespal.zip [MAME 0.227]

### ISSUE THREAD

**Issue by thundercats-ho** [mamedev/mame#7646]
Hi 

The snes software list has 2 machines available, the snes and snespal. The only difference between both in the XML is this line:

snes:

`<display tag="screen" type="raster" rotate="0" width="512" height="225" refresh="60.098476" pixclock="10738636" htotal="682" hbend="0" hbstart="512" vtotal="262" vbend="0" vbstart="225" />`

snespal:

`<display tag="screen" type="raster" rotate="0" width="512" height="240" refresh="49.858937" pixclock="10609184" htotal="682" hbend="0" hbstart="512" vtotal="312" vbend="0" vbstart="240" />`

I have an issues about those 2 machines:

Why does MAME allow NTSC games of the snes software list to run on the PAL machine? This was never possible on real SNES devices. PAL and NTSC had different machines needed to run the games.

For example you can run any game from USA (NTSC) on snespal.zip, while in the real world this is not possible.

**Comment by thundercats-ho** [comment]
So MAME allows something which was never possible in the real world. I think this is in contradiction with accurate emulating things.

**Comment by einstein95** [comment]
> So MAME allows something which was never possible in the real world.

This is very much possible in the real world as 5 seconds of googling show that the only thing stopping you is merely plastic in the cartridge slot.

**Comment by cuavas** [comment]
> > So MAME allows something which was never possible in the real world.
> 
> This is very much possible in the real world as 5 seconds of googling show that the only thing stopping you is merely plastic in the cartridge slot.

Nope, that only works for playing NTSC Super Famicom (Japan) games on a NTSC Super NES (US).  They use the same CIC but have physically different cartridges to implement region lockout.  The PAL Super NES uses a different CIC, so the cartridges are incompatible despite being the same physical shape as the NTSC Super Famicom carts.

You can still bypass it – there are region bypass devices that have a pass-through cartridge slot and a device to emulate the CIC well enough to get the console to boot.  Some of the later games can detect this and show a message saying they’re incompatible (e.g. Yoshi’s Island).

**Comment by cuavas** [comment]
FWIW MAME doesn’t emulate the CIC, but games that detect running on the wrong console type by other means do show the error message.  If it makes you happier, you can tell yourself that MAME emulates a SuFami/SNES with a piracy device attached.
