### ISSUE TITLE
apple2gs keypad = key is missing

### ISSUE THREAD

**Issue by ksherlock** [mamedev/mame#7658]
The Apple IIgs keyboard has a number pad `=` key (adb code $51).  Conveniently, Macintosh extended keyboards also have a number pad `=` key.  However, it doesn't generate an emulated key code.

**Comment by rb6502** [comment]
Thanks!  This is resolved in https://github.com/mamedev/mame/commit/854bd7a84d3266da3bc803b80ec690dcc2ef2826 .
