### ISSUE TITLE
mame: dist.mak: some tools executables missing

### ISSUE THREAD

**Issue by mascguy** [mamedev/mame#7672]
In short, `dist.mak` is missing some of the tools-related executables.

Line 104 is currently:
`
BINARIES = $(MAINBIN) castool chdman floptool imgtool jedutil ldresample ldverify nltool nlwav romcmp unidasm
`

But should be:
`
BINARIES = $(MAINBIN) aueffectutil castool chdman floptool imgtool jedutil ldresample ldverify nltool nlwav pngcmp regrep romcmp split srcclean testkeys unidasm
`

Pull request created with fix:
[mame: dist.mak: add missing tools executables](https://github.com/mamedev/mame/pull/7671)

**Comment by cuavas** [comment]
Not all the tools are useful to everyone:
* pngcmp and regrep are internal testing tools. They're inflexible and unintuitive. You wouldn't need them if you aren't doing development, in which case you'll be compiling MAME yourself anyway.
* srcclean enforces some simple source formatting rules. If you're editing the source, you should be compiling it yourself before submitting anyway.
* split is still around for historical reasons, but it isn't very useful most of the time.
* aueffectutil is only built on macOS, and I've heard it stopped working after some macOS version (no longer creates menu bar).
* testkeys and ledutil are also only built for specific target configurations and can't be included in that line.

**Comment by mascguy** [comment]
Since this isn't applicable, I'll close. Sorry guys!
