### ISSUE TITLE
Graphical regression in Wiping (related to 'emumem'?)

### ISSUE THREAD

**Issue by dnlopez** [mamedev/mame#7680]
When I run the game Wiping in MAME 0.227, the player sprite and most of the enemy sprites are invisible. It's noticeable both in the attract mode and during a game. In MAME 0.226 it's okay.

By bisecting, I find that this first happens with the commit "b8c338858a1 emumem: Simplify memory management."

I don't have the knowledge to take this further at present. Hopefully it makes sense to someone!

**Comment by Tafoid** [comment]
Fix was just committed to source [Here](https://github.com/mamedev/mame/commit/881182beba5ff0a35883702195bd590f96202223)
If you could update your source and verify on your end it is correct, we can close this.

**Comment by dnlopez** [comment]
Yep, I reverted to the mame0227 tag and added this change, and it works. Thanks!
