### ISSUE TITLE
make Error (Delete megaduck)  

### ISSUE THREAD

**Issue by zjwkof** [mamedev/mame#770]
../../../../mingw-gcc/bin/x64/Release/mame_mame/liboptional.a(sgb.o):sgb.cpp:(.rdata$.refptr._ZN13gb_lcd_device5oam_rER13address_spacejh[.refptr._ZN13gb_lcd_device5oam_rER13address_spacejh]+0x0): undefined reference to `gb_lcd_device::oam_r(address_space&, unsigned int, unsigned char)'
../../../../mingw-gcc/bin/x64/Release/mame_mame/liboptional.a(sgb.o):sgb.cpp:(.rdata$.refptr._ZN13gb_lcd_device5oam_wER13address_spacejhh[.refptr._ZN13gb_lcd_device5oam_wER13address_spacejhh]+0x0): undefined reference to `gb_lcd_device::oam_w(address_space&, unsigned int, unsigned char, unsigned char)'
../../../../mingw-gcc/bin/x64/Release/mame_mame/liboptional.a(sgb.o):sgb.cpp:(.rdata$.refptr._ZN13gb_lcd_device6vram_rER13address_spacejh[.refptr._ZN13gb_lcd_device6vram_rER13address_spacejh]+0x0): undefined reference to `gb_lcd_device::vram_r(address_space&, unsigned int, unsigned char)'
../../../../mingw-gcc/bin/x64/Release/mame_mame/liboptional.a(sgb.o):sgb.cpp:(.rdata$.refptr._ZN13gb_lcd_device6vram_wER13address_spacejhh[.refptr._ZN13gb_lcd_device6vram_wER13address_spacejhh]+0x0): undefined reference to `gb_lcd_device::vram_w(address_space&, unsigned int, unsigned char, unsigned char)'
../../../../mingw-gcc/bin/x64/Release/mame_mame/liboptional.a(sgb.o):sgb.cpp:(.rdata$.refptr.GB_LCD_SGB[.refptr.GB_LCD_SGB]+0x0): undefined reference to `GB_LCD_SGB'
collect2.exe: error: ld returned 1 exit status
mame.make:234: recipe for target '../../../../../mame64.exe' failed
make[2]: *** [../../../../../mame64.exe] Error 1
Makefile:946: recipe for target 'mame' failed
make[1]: *** [mame] Error 2
makefile:879: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

**Comment by startaq** [comment]
What command did you use to compile? Did you `make clean` before compiling?

**Comment by zjwkof** [comment]
make

for a MAME build

**Comment by stilett0** [comment]
So you've deleted "megaduck" from mame.list, ran "make" and sgb.cpp collapses in compile errors?

**Comment by zjwkof** [comment]
Example:
@source:dccons.cpp
dc                              // 1999 Sega Dreamcast (USA)
dcdev                           // 1998 Sega HKT-0120 Sega Dreamcast Development Box
dceu                            // 1999 Sega Dreamcast (Europe)
dcjp                            // 1998 Sega Dreamcast (Japan)

@source:gb.cpp
megaduck                        // Megaduck

@source:snes.cpp
snes                            // Nintendo Super Nintendo NTSC
snespal                         // Nintendo Super Nintendo PAL
************************************************************************

Delete 1.megaduck (gb.cpp)   2.snes.cpp
 ( mame0172s : mame.lst )
make compile
___________________________________
Delete 1.megaduck (gb.cpp)   
 ( mame0172s : mame.lst )
make  error

**Comment by zjwkof** [comment]
mame 0.174 fix

**Comment by zjwkof** [comment]
mame 0.174 fix

**Comment by zjwkof** [comment]
mame 0.174 fix
