### ISSUE TITLE
make "install" target missing

### ISSUE THREAD

**Issue by rain-1** [mamedev/mame#771]
Hello!

What about adding an 'install' target that copies mame64 to "$PREFIX/bin/"?

This would ease packaging mame for distros that expect to run make them make install.

**Comment by galibert** [comment]
Given the existence of artwork, hash, plugin...  that wouldn't be enough.
Plus we'd need to generate a default config with $PREFIX in it.  Plus the
whole binary package organization is very os-dependent.

It's not that easy to have a decent install target.

  OG.
