### ISSUE TITLE
mame-0.228 & NetBSD: drc_cache: Error marking cache read/write

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#7712]
On NetBSD 9.99.79/amd64 with gcc 9.3.0, I see a problem in mame 0.228 that I didn't see with mame 0.227:
0.227:
````
#  mame -listxml > a
#
````
works. But with 0.228:
````
# mame -listxml > a
drc_cache: Error marking cache read/write
````
and in the output file (i.e. stdout) there are a couple more of these:
````
Ignoring MAME exception: drc_cache: Error marking cache read/write
Ignoring MAME exception: drc_cache: Error marking cache read/write
Ignoring MAME exception: drc_cache: Error marking cache read/write
Ignoring MAME exception: drc_cache: Error marking cache read/write
Ignoring MAME exception: drc_cache: Error marking cache read/write
````

Can you please point me to the relevant source code that was changed between 0.227 and 0.228 so I can debug this a bit more?

**Comment by cuavas** [comment]
Previously MAME completely ignored errors allocating virtual memory for the recompiler.  I suspect this problem is a lot older but was just being silently ignored for you before.  The commit where errors started being reported was 6e1bbe8be89349038995df2aaa4f11019439e39e.

**Comment by galibert** [comment]
Independently, is it expected for listxml to alloc drc ram?

  OG.

**Comment by cuavas** [comment]
It calls all the machine configuration functions, which constructs all the devices.  The DRC CPUs allocate their DRC memory in their constructors, so yes, it’s expected given the current implementations.

**Comment by galibert** [comment]
Ah ok, I didn't realize that was done at constructor level.

  OG.

**Comment by 0-wiz-0** [comment]
Thanks for the pointer. I tracked it down - the initial `mmap()` is done without any protection flags, and the mprotect calls later fails.

The following diff fixes it, but I'm not sure how you want to integrate it - you seem to avoid having operating-system specific `#ifdef`s if possible.

````
--- src/osd/modules/lib/osdlib_unix.cpp.orig    2021-01-26 04:43:24.000000000 +0000
+++ src/osd/modules/lib/osdlib_unix.cpp
@@ -189,7 +189,11 @@ void *virtual_memory_allocation::do_allo
        // TODO: portable applications are supposed to use -1 for anonymous mappings - detect whatever requires 0 specifically
        int const fd(0);
 #endif
+#ifdef __NetBSD__
+       void *const result(mmap(nullptr, s, PROT_MPROTECT(PROT_EXEC|PROT_WRITE|PROT_READ), MAP_ANON | MAP_SHARED, fd, 0));
+#else
        void *const result(mmap(nullptr, s, PROT_NONE, MAP_ANON | MAP_SHARED, fd, 0));
+#endif
        if (result == (void *)-1)
                return nullptr;
        size = s;
````

**Comment by galibert** [comment]
You're making me curious, why is netbsd refusing going none -> rw?

  OG.

**Comment by 0-wiz-0** [comment]
Actually, I don't know.
Here's the `mmap` man page:
http://man.netbsd.org/mmap.2

**Comment by galibert** [comment]
Do you have pax mprotect globally active perchance?

https://man.netbsd.org/security.7

  OG.

**Comment by galibert** [comment]
Ah no, it's within's netbsd mprotect definition.  Wonder how posix it is.

  [EACCES]           The new protection is less restrictive than the
protection originally set with mmap(2)
<https://man.netbsd.org/mmap.2>.

**Comment by 0-wiz-0** [comment]
Yes, pax mprotect is enabled, but I think that's the default.

**Comment by cuavas** [comment]
That’s completely incompatible with W^X policy – you need to be able to make the protection less restrictive because you can’t initially set write *and* execute.  I really hate having to hack around stuff like this.

**Comment by galibert** [comment]
Looks like in a discussion of 2017 it was decided that mmap(RWX) would mean
"RW with the option to switch to RX".  The "and back" patch is unclear fwiw.

  OG.

**Comment by 0-wiz-0** [comment]
The mremap(2) man page (http://man.netbsd.org/mremap.2) contains a complete example how to have a anonymous memory location mapped rw once and rx another time on NetBSD.

Please note that the initial `mmap` argument is `PROT_MPROTECT(PROT_EXEC|PROT_WRITE|PROT_READ)`, not `PROT_EXEC|PROT_WRITE|PROT_READ` (also in the patch I pasted above).

But perhaps I misunderstood your point.

**Comment by cuavas** [comment]
MAME doesn't work that way - we have on be mapping and flip it between RW and RX, not multiple mappings of the same pages with different protection.

**Comment by 0-wiz-0** [comment]
AFAIK that's not supported on NetBSD :(

**Comment by cuavas** [comment]
Actually, it might be possible to get it working for NetBSD – you can declare desired permissions but start with no permissions.

**Comment by 0-wiz-0** [comment]
> you can declare desired permissions but start with no permissions

Isn't that what my patch above does?

> flip it between RW and RX

I think this part is not supported on NetBSD.

Anyway, with the patch above, `make -listxml` works on NetBSD.
Is there a further test I can do for the other issues we've discussed here?

**Comment by cuavas** [comment]
With just that change, can you post `-verbose` output for something that uses a recompiler? You could use Killer Instinct (MIPS III recompiler), one of the Street Fighter III games (SH-2), or something on Hyperstone like Elfin.  Just up to where it starts will be fine.

**Comment by 0-wiz-0** [comment]
With just my patch, I tried elfin, and it works (I got a game screen and could press start). The stdout/stderr log contains the line:
````
drc_cache: Using W^X mode
````
twice. I guess you don't need the rest of the log :)

**Comment by cuavas** [comment]
OK, I’ll do it properly later (for some values of properly).

**Comment by 0-wiz-0** [comment]
Thanks, @cuavas!

**Comment by cuavas** [comment]
Should be working with 86666f388eb8ee809a953e320acb828f2bd574c1 – if now we can reopen it.
