### ISSUE TITLE
Launching ldresample with no parameters causes SIGSEGV

### ISSUE THREAD

**Issue by angelosa** [mamedev/mame#7722]
On Windows, attempt to run `ldresample.exe` with no parameters for the usage instructions causes a segmentation fault (error code 3221225725).

**Comment by cuavas** [comment]
It’s caused because `chd_resample_compressor` is too large to allocate on the stack – it tries to allocate 0x105628 bytes (just over 1 MB) of stack space and slams into a guard page.  Fixed by 9baa810ef2ae34ae7090fa00e740e945d6e93940.
