### ISSUE TITLE
bgfx texture selection disappears if artpath has multiple entries

### ISSUE THREAD

**Issue by cgwg** [mamedev/mame#7736]
The default configuration on Fedora has
`artpath            /usr/share/mame/artwork;/usr/share/mame/effects`
When this setting has more than one path like shown above, the bgfx texture selection sliders (used to select the shadow mask pattern in the crt-geom and hlsl chains) disappear. The texture corresponding to the default setting is still correctly loaded. If I specify just one path, then the sliders work correctly.

**Comment by Robbbert** [comment]
Please provide the full command line that you use.

**Comment by cgwg** [comment]
`1. mame -video bgfx -bgfx_screen_chains crt-geom -artpath /usr/share/mame/artwork sf2`
If I do this then go to slider controls, the shadow mask slider is present.
`2. mame -video bgfx -bgfx_screen_chains crt-geom -artpath "/usr/share/mame/artwork;/usr/share/mame/effects" sf2`
If I do this (or omit the -artpath option, since this is the default in /etc/mame/mame.ini on Fedora), then the slider is absent.

**Comment by Robbbert** [comment]
I only use Windows, however the problem occurs there too. Thanks for the information.

**Comment by ajrhacker** [comment]
f806cfd21c83cf0c013cf721ab2adae3eecdb6ad fixes this.
