### ISSUE TITLE
Make TOOLS a target instead of a build parameter.

### ISSUE THREAD

**Issue by BailShamber** [mamedev/mame#7743]
It would be nice to have the option to build tools seperately to save compilation time and to be able to compile on target machines (e.g termux on android) where it's not that easy to setup some dependencies like qt-devel.

**Comment by angelosa** [comment]
In CI integration test scenarios we eventually need this as a trigger option too, unless we want to just rely on uploaded artifacts.

**Comment by Robbbert** [comment]
I thought cuavas fixed this?

**Comment by cuavas** [comment]
This is essentially the same use case as #8606.
