### ISSUE TITLE
Reflective LCD Grain

### ISSUE THREAD

**Issue by anikom15** [mamedev/mame#779]
Reflective LCDs, such as that on the Game Boy, have a shimmering effect that looks like glitter. This effect would be impossible to implement in 2D, since it depends on angle. However, a similar static effect can be employed using randomly generated noise. Essentially, every RGB element of every pixel is modulated by some amount of noise. The amount of noise for each pixel should _not_ change over time (i.e. it is not film grain). This image shows a cropped screenshot of Super Mario Land, with some other HLSL effects applied, and then GIMP was used to add RGB noise to demonstrate the result of the grain effect. This was made to be a bit too dramatic in order to clearly show the effect.

[Super Mario Land with HLSL & Added Grain](http://i.imgur.com/9fyRnd8.png)

This could be done with artwork, given that it does not appear obviously tiled. HLSL implementation should be cheap as well, since a texture of random pixels to be added to the view need only be calculated once.

**Comment by rb6502** [comment]
MAME is not in the business of simulating all of the possible imperfections of LCDs, especially since at optimal viewing angles they don't have any.  You can get the effect you want with an overlay PNG without modifying MAME in any way.
