### ISSUE TITLE
Debugger: Rewind is not functional

### ISSUE THREAD

**Issue by czxinc** [mamedev/mame#7806]
Debug command "rw" can not load previous rewind state.

**Comment by vadosnaprimer** [comment]
I checked. Rewinding does happen, but debugger doesn't update its contents.

**Comment by vadosnaprimer** [comment]
Looks like rewind wasn't working since https://github.com/mamedev/mame/commit/08ba9b0536178d83b89e2380e8323727055cec29

And even before that, in some games (tested btoads), disasm view doesn't update upon rewind.
