### ISSUE TITLE
Mame failed to build due to error C2131 C3863 on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [mamedev/mame#7823]
Hi All,

Mame failed to build due to error C2131 C3863 on windows with MSVC. It can be reproduced on latest commit b466a9c and it failed to compile ..\..\..\..\..\src\tools\chdman.cpp due to error C2131: expression did not evaluate to a constant. Could you please help take a look at this issue? Thanks in advance!

Environment
mame(latest revision from github) + VS 2019 + Windows Server 2016

[mame_build.log](https://github.com/mamedev/mame/files/6048089/mame_build.log)
[Patches.zip](https://github.com/mamedev/mame/files/6048102/Patches.zip)

Repro steps:
1. Open x64 native tools command prompt for VS2019
2. git clone https://github.com/mamedev/mame F:\gitP\mamedev\mame
3. Apply 2 patches mame_c2440.patch and mame_genie.patch in attachment Patches.zip
4. cd F:\gitP\mamedev\mame
5. set PATH=F:\gitP\mamedev\mame\..\tools\msys64\usr\bin;F:\gitP\mamedev\mame\..\tools\msys64\mingw64\bin;%PATH%
6. make SUBTARGET=tiny PTR64=1 TOOLS=1 OPTIMIZE=0 vs2019 -j4
bootstrap-vcpkg.bat
7. cd F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019
8. msbuild /m /p:Platform=x64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 mametiny.sln /t:Rebuild

Actual result:
62>F:\gitP\mamedev\mame\src\tools\chdman.cpp(508,34): error C2131: expression did not evaluate to a constant [F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019\chdman.vcxproj]
F:\gitP\mamedev\mame\src\tools\chdman.cpp(508,34): error C2131: 				int16_t *samplesptr[std::size(m_audio)]; [F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019\chdman.vcxproj]
F:\gitP\mamedev\mame\src\tools\chdman.cpp(508,34): error C2131: 				                             ^ [F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019\chdman.vcxproj]
62>F:\gitP\mamedev\mame\src\tools\chdman.cpp(513,24): error C3863: array type 'int16_t *['function']' is not assignable [F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019\chdman.vcxproj]
F:\gitP\mamedev\mame\src\tools\chdman.cpp(513,24): error C3863: 					samplesptr[chnum] = &m_audio[chnum][0]; [F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019\chdman.vcxproj]
F:\gitP\mamedev\mame\src\tools\chdman.cpp(513,24): error C3863: 					                  ^ [F:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2019\chdman.vcxproj]

**Comment by cuavas** [comment]
Please report it to Microsoft.  `std::size` is supposed to be `constexpr` so applying it to a data member that is an array should be a constant expression.

**Comment by ajrhacker** [comment]
Microsoft Visual Studio's online bug reporting forum seems to be rather messed up. A very similar bug with std::size (https://developercommunity.visualstudio.com/t/stdsize-expression-did-not-evaluate-to-a-constant/1111617) was reported but closed as a duplicate of another bug (https://developercommunity.visualstudio.com/t/problem-in-visual-studio-cummunity-c/589292) that was closed because it "uses C99 variable length array which isn't part of C++." This sort of thing seems to happen quite often there (https://developercommunity.visualstudio.com/t/bugs-are-incorrectly-closed/1149416).

**Comment by yz70s** [comment]
Here it is the bugreport i did
https://developercommunity2.visualstudio.com/t/strange-problem-with-stdsize-and-fixed-size-arrays/1351450

I will also commit a fix with something like
static constexpr int maximum_channels = 8;
std::vector<int16_t> m_audio[maximum_channels];
int16_t *samplesptr[maximum_channels];

**Comment by spacelg** [comment]
Hi All, Thanks for your info and help. I've tried @yz70s's workaround. It works. And I found that the reported vs feedback ticket has been tracked by a bug again. So close this. 

Thanks,
Lin
