### ISSUE TITLE
Launching mame from Visual Studio without game argument results in assertion fail

### ISSUE THREAD

**Issue by vadosnaprimer** [mamedev/mame#7842]
Happens on debug build with `vs2019` and `vs2019_clang`. VS affected is 16.9.0, maybe earlier versions too. This does have a workaround (launching it with a game), but hard to tell if it's a complete false positive or VS simply being overly safe. So maybe it's worth fixing moving forward.

![unknown](https://user-images.githubusercontent.com/7092625/110113251-e6404b00-7dc3-11eb-9f48-49f7d225d6fe.png)

**Comment by ajrhacker** [comment]
ad3fa37944c02ef6f39663c039d88e7bb90cf8ee may fix this.

**Comment by vadosnaprimer** [comment]
Thanks! It works now.
