### ISSUE TITLE
Feature request: automatic mute when using nothrottle

### ISSUE THREAD

**Issue by galibert** [mamedev/mame#7843]
When you're listening to music on the PC and start a system repeatedly when working on it, the heavily distorded "bong" some systems like the mac or the 2gs do on startup with -nothrottle is rather painful. Since in general -nothrottle/F10 means the sound is going to be horrible, automatic mute would make sense, wouldn't it?

**Comment by Osso13** [comment]
In general I agree and I'd appreciate such a change, but wouldn't this cause problem for audio regression testing? Maybe would be better to have it configurable.

**Comment by Robbbert** [comment]
I prefer the sound unmuted, so if we're going to have this, it needs to be configurable as Osso13 said.

**Comment by galibert** [comment]
You like the sound unmuted when unthrottled?

It would make sense to only mute the audio output and not things like
wavfile, which would avoid the issues with testing.

**Comment by happppp** [comment]
When I fastforward emulation (the INS key in this case), it's usually impatience waiting for a cue, this can either be visual or audio. For example I want to skip to an arcade game attract demo loop with sounds playing, but the game only plays demo sounds 1 every 4 times.

**Comment by DavidHaywood** [comment]
yeah, I often use audio cues to know when to release the throttle, so what hap said really

**Comment by cuavas** [comment]
I prefer to have sound on when running unthrottled for testing.

**Comment by antonioginer** [comment]
Also please bear in mind that -nothrottle -waitvsync is the only way that
makes possible to correctly run synchronized with the monitor's refresh
(ideally -syncrefresh should do exactly this but that's another topic).

**Comment by smf-** [comment]
what about something like:

mame neogeo -nothrottle 10 -nosound 10

Where it would fast forward the first 10 seconds without sound, there
are boot sounds that are annoying when running normal speed and fast
forwarding automatically for a set number of seconds would save wearing
out insert keys.
