### ISSUE TITLE
Neo Geo Pocket / Neo Geo Pocket Color: System configuration not saving

### ISSUE THREAD

**Issue by Immersion95** [mamedev/mame#7844]
I think this is a known issue : 
https://mametesters.org/view.php?id=5279

I'm wondering if any improvement has been done.

MAME is the only known emulator to emulate the BIOS for the Neo Geo Pocket so solving this bug would be fantastic !

**Comment by cuavas** [comment]
Don’t make duplicate issues.  If you haven’t heard anything, nothing has changed.
