### ISSUE TITLE
window mode resolution switch

### ISSUE THREAD

**Issue by proghettocraps** [mamedev/mame#7854]
Hello developers,

I'm trying to switch resolution in window mode using command line arguments but whatever I try, it just won't switch to another resolution then my desktop resolution.

Can somebody tell me the exact working command line to pass to the mame executable on windows to do this?

Thank you for reading!

**Comment by Tafoid** [comment]
Example below using **-window** only.  Full screen display is controlled by your OS/Video Card options and cannot be assigned outside available resolutions).  Best to keep as a multiple of the original resolution so the emulation/window matches up without empty space.  Looks like crap but it can be done.

> mame defender -window -resolution 1168x240 -autostretchxy -nokeepaspect
