### ISSUE TITLE
(ppp) Incorrect song start time.

### ISSUE THREAD

**Issue by pm41224** [mamedev/mame#7863]
When playing the song "SPEEDWAY" by NIKO, in ParaParaParadise games (1.0, 1.1, PPD and 1st MIX Plus; Viper-based ParaParaParadise 2ndMIX is still being worked on atm), the game begins the song 3 seconds inward (begins with the vocalist singing "-the pilots are just about to cry" instead of the car-like guitar lick that begins the song). When the song ends, the first ~3 seconds of "EUROBEAT" by DR. LOVE begins playing.

I've always known that this has happened since the game advanced to a playable state in version 0.148; if you feel like closing this issue feel free to do so. Thanks in advance anyways and advance apologies if I wasted your time.

**Comment by 987123879113** [comment]
This should've been fixed in https://github.com/mamedev/mame/pull/7822 which will be included in MAME 0.230. If you use a nightly build it should be fixed.
