### ISSUE TITLE
Multiple TRS-80 model 1 and 3 disks which previously worked no longer boot.

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#7865]
These disk images worked in version 0.224 and now no longer work in 0.229.
Model 1
M1-TRS27.DSK

Model 3
M3-DOSPLUS.imd
M3-TRSDOS13.imd
ND80M3.dmk
ND80M3.imd
ld3-531.imd

[M3-LDOS.zip](https://github.com/mamedev/mame/files/6142040/M3-LDOS.zip)

I am attaching the model 3 LDOS disk for troubleshooting since it has been released by the copyright holder.

**Comment by Tafoid** [comment]
Please avoid using both MAMETESTERS and GitHub Issues for the same bug report.  Discuss it there.
https://mametesters.org/view.php?id=7903
