### ISSUE TITLE
apple IIgs key latch 

### ISSUE THREAD

**Issue by ksherlock** [mamedev/mame#7867]
Currently the IIgs key latch is only readable at `$c000`.  The Apple IIe was [fixed](https://github.com/mamedev/mame/commit/545df40e7f9942bc29a98212945e07eb64bef3ba) a couple years ago so the key latch was available throughout the `$c000`-`$c00f` range and I believe that applies the to IIgs as well. All other IIgs emulators treat a `$c000`-`$c00f` read equally. I recently encountered some software that does a 16-bit read of `$c000` and expects the `$c001` to be valid.

        LDA   >$E0C000
        BPL   *-$04
        STA   >$E0C010
        AND   #$007F

**Comment by rb6502** [comment]
This (and the analogous issue for $C01X) should be addressed in https://github.com/mamedev/mame/commit/2e749cdd86e43bfb8435566c7ec2496a16426547

**Comment by ksherlock** [comment]
Looking good, thanks!
