### ISSUE TITLE
Build with NO_X11=1 is not fully honored in drawbgfx.cpp 

### ISSUE THREAD

**Issue by wakass** [mamedev/mame#7888]
Thought this bug as reported on [mametesters](https://mametesters.org/view.php?id=7738) deserved some attention.

>  When building with the option NO_X11=1, a component of BGFX is not fully processing the directive in the file ./src/osd/modules/render/drawbgfx.cpp
> At line #172, 195 and 196 there are hard references to X11.
> 
> I personally workaround this by replacing:
>  - Line #172 with: return nullptr;
>  - Line #195-196 with:
>       pd.ndt = NULL;
>       pd.nwh = _window;
> 
> It seems that a check for SDL2 Video Ouput is missing for the Raspberry Pi using KMS/DRM video output (without X11).

**Comment by cuavas** [comment]
It doesn't need a duplicate report - all that will do is potentially split discussion.

**Comment by wakass** [comment]
Sorry, was not aware mametesters was part of global mame bugtracking.
