### ISSUE TITLE
Apple //e: CTRL+RESET leaves internal Cx ROM switched in

### ISSUE THREAD

**Issue by tomcw** [mamedev/mame#7909]
Using MAME 0.229 or 0.230...

For models `apple2e` and `apple2ee`, then CTRL+RESET (Control+F12) switches in internal Cx ROM and erroneously leaves it switched in.

Repro:
- Use default apple2e/apple2ee card config, eg. with Mockingboard in slot-4
- Boot a DOS 3.3 or ProDOS dsk
- CALL-151
- C400.C47F
- Note that the 6522 regs are visible at $C400.C40F $(C410 is correctly the same as $C400, but erroneously the remaining bytes are all 0x00!)
- CTRL+RESET
- CALL-151
- C400.C47F
- Note that the data is very different
- C006:0  ; enable slot ROM
- C400.C47F
- now back to the 6522 regs

**Comment by rb6502** [comment]
I guess not that full range since the versions with SSI-263 speech put that at Cn40.

**Comment by tomcw** [comment]
For the Mockingboard, the SSI263 is write-only (with the IRQ providing the phoneme complete status), so the mirroring is simply as you state it, ie.
>repeats of the first VIA from Cn00-Cn7F and the second from Cn80-CnFF

Also writes to SSI263 ($Cn40-Cn47 for the main one; and $Cn20-Cn27 for the 2nd one) will do a chip-select + write to the first VIA (there's a bug in "Willy Byte" that hits this nuanced behaviour).

For the Phasor card (in native Phasor mode), access to the chips (AY8913,SSI263) is via a GAL/PLD. And the mapping is slightly different (eg. $Cn00-Cn0F is floating bus, with the 1st VIA now at $Cn10). Also the SSI263's single status bit is now readable in bit7 of the SSI263 I/O space (and SSI263 IRQ is handled differently too).

NB. With the VIA mapped to $Cn10, this means that SSI263 r/w's don't interfere with the first VIA (unlike the original Mockingboard). which is presumably why Applied Engineering made this change.
