### ISSUE TITLE
keyboardprovider=win32 breaks search on the machine list

### ISSUE THREAD

**Issue by nicholas-ochoa** [mamedev/mame#7911]
At some point I had set `keyboardprovider` in `mame.ini` to `win32`. I later noticed I could no longer search in the unfiltered / working list of machines. I finally got around to trying to reproduce this on a vanilla copy of MAME (0.230 as of creating this issue) and it comes down to having `keyboardprovider` set to `win32` instead of the default `auto`.

When set to `win32` search just doesn't work. One odd thing I noticed however was that if I hold down a key it will work however the key repeats a few times - so it's essentially useless anyway.

Not sure how high the priority is on this, I don't use `keyboardprovider` with a value of `win32` any longer, but I figured it was worth reporting.

**Comment by cuavas** [comment]
Fixed by 26833301afc3140cc86b074acec967a1955db82a.
