### ISSUE TITLE
Apple II: Mockingboard's SC-01 - inflection bits not written

### ISSUE THREAD

**Issue by tomcw** [mamedev/mame#7918]
Hi @rb6502,

I'm just looking at the Mockingboard's SC-01 support here: https://github.com/mamedev/mame/blob/master/src/devices/bus/a2bus/a2mockingboard.cpp

It only seems to be calling m_sc01->write((m_portb1), but never m_sc01->inflection_w((m_portb1>>6).

NB, the implementation of `votrax_sc01_device::inflection_w(uint8_t data)` expects inflection to be in b1:0 (so m_portb1 would need shifting down by 6).
See: https://github.com/mamedev/mame/blob/289efafb392c7d0407b302bf21b202cc642f992f/src/devices/sound/votrax.cpp#L117

**Comment by rb6502** [comment]
You're right, and this is fixed in https://github.com/mamedev/mame/commit/68b16c6f51fe74ab488c59dcf17aa3a79b09ffc0.  Thanks again!

**Comment by tomcw** [comment]
Thanks for fixing those things.

And a few very minor "off by one" issues are these comparisons:

https://github.com/mamedev/mame/blob/46d17663b3f0400d83bd8e0436f7e636a57da4cf/src/devices/bus/a2bus/a2mockingboard.cpp#L196

https://github.com/mamedev/mame/blob/46d17663b3f0400d83bd8e0436f7e636a57da4cf/src/devices/bus/a2bus/a2mockingboard.cpp#L232

Where each of the two checks `<=` should be `<`, ie.
```
	if ((offset < 0x20) || (offset >= 0x80 && offset < 0xa0))
```

**Comment by rb6502** [comment]
Thanks!  Those are addressed in https://github.com/mamedev/mame/commit/195d45d3358b11e581d5a7251199337726d21806.

**Comment by tomcw** [comment]
Nearly... but you have missed the two ` <= 0xa0` conditions :-)

**Comment by rb6502** [comment]
I need to stop doing these changes right before bed :-)

Fixed in https://github.com/mamedev/mame/commit/029f7fdf878f237d591a91a1c6f9b033c5cb7aa2.

**Comment by tomcw** [comment]
Thanks - all looking good now.
