### ISSUE TITLE
chdman0230 does NOT recreate correct TOSEC's .gdi

### ISSUE THREAD

**Issue by cinnamonmatexfce** [mamedev/mame#7935]
>  this latest version of chdman (0.227) now creates conformant CHDs (conformant as to GD-ROM real physical disks) using ReDump **.cue**/.bin?

Correct.

> And what if I would create CHDs from TOSEC .gdi format?

That also works.

_Originally posted by @nhand42 in https://github.com/mamedev/mame/issues/7422#issuecomment-752937916_

**Comment by cinnamonmatexfce** [comment]
Hey, please have a look and let me know if I'm doing something wrong.

1. Starting from proper TOSEC dump, the files are good and audited against TOSEC's DAT.
```
<game name="Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!]">
		<description>Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!]</description>
		<rom name="Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].gdi" size="87" crc="d7ab4c6b" sha1="9d50b816d3f69ad192f5986ab487769965c2e082" md5="b3ecdf113fd42344dd84142679e4cb36"/>
		<rom name="track01.bin" size="705600" crc="ad62f288" sha1="516f61b7d2c5e97cbc46700fec881aba9a705e60" md5="6072e4e055036e7b63ce52a0d971de63"/>
		<rom name="track02.raw" size="13994400" crc="15e73429" sha1="b643df4def042b6c23f90f54c690ac7df431233f" md5="d1838bcbca4a24b39deddeae2a9d371a"/>
		<rom name="track03.bin" size="1185760800" crc="c876c66c" sha1="e9e3afd65c57f28ae372b99d84186283efb88332" md5="7536ebe487b0b05da9ae622e7834197c"/>
	</game>
```

2. _GDItoCHD_: OK
```
$ chdman createcd -i 'Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].gdi' -o 'Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].chd'
```

3. Verify + infos
```
$ chdman verify -i 'Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].chd' 
chdman - MAME Compressed Hunks of Data (CHD) manager 0.230 (unknown)
Raw SHA1 verification successful!
Overall SHA1 verification successful!

- - - - -

$ chdman info -i 'Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].chd' 
chdman - MAME Compressed Hunks of Data (CHD) manager 0.230 (unknown)
Input file:  Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].chd
File Version: 5
Logical size: 1,344,333,888 bytes
Hunk Size:    19,584 bytes
Total Hunks:  68,645
Unit Size:    2,448 bytes
Total Units:  549,156
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     87,899,776 bytes
Ratio:        6.5%
SHA1:         3e1a1516c1906bca1edb05b7b0c17baf98f45d51
Data SHA1:    ba3c9d119b1a5a67688cb7bbdc3de1896ef7c281
Metadata:     Tag='CHGD'  Index=0  Length=98 bytes
              TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:450 PAD:150 PREGA
Metadata:     Tag='CHGD'  Index=1  Length=98 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44550 PAD:38600 PREGA
Metadata:     Tag='CHGD'  Index=2  Length=99 bytes
              TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PAD:0 PREG
```

4. Re-creating original files: FAILED (_GDItoCHDtoGDI_)
```
$ chdman extractcd -i 'Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].chd' -o 'Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].gdi'

- - - - -

$ sha1sum *
8f9e6d6098bbdf7628f2282cb1ae9f1a122f8f64  Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].gdi
516f61b7d2c5e97cbc46700fec881aba9a705e60  Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!]01.bin
b643df4def042b6c23f90f54c690ac7df431233f  Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!]02.raw
e9e3afd65c57f28ae372b99d84186283efb88332  Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!]03.bin
c00941403375027c06b335daeccc405d8eb86426  Sega Bass Fishing v1.020 (1999)(Sega)(PAL)[!].chd

**Comment by cynodesmus** [comment]
From your example, I see that your checksums for the cue file do not match, but they will not match, since the unpacked cue (gdi) contains other track names (other than the TOSEC names).
However, the checksums of the bin and raw files are correct.
In order to achieve 100% coincidence of checksums for all files, you will need to - download from the TOSEC website the original cue/gdi files and date files with checksums. Then use the collection manager (for example: RomVault) - to rename the bin and raw files in accordance with the contents of the original cue/gdi file.

This problem occurs due to the fact that TOSEC uses the file name - "track *. *"
If you need to restore a single image, you can manually edit the gdi file (this is a text file) and rename the bin and raw files to the corresponding "track *.bin" and "track *.raw".

**Comment by cinnamonmatexfce** [comment]
> manually edit the gdi file (this is a text file) and rename the bin and raw files to the corresponding "track *.bin" and "track *.raw".

That worked! Thank you @cynodesmus
