### ISSUE TITLE
MAME will not accept mouse input from connected Parsec clients

### ISSUE THREAD

**Issue by therealbungus** [mamedev/mame#7937]
When using [Parsec](https://parsecgaming.com/), a client connected to the host running MAME will not have their mouse inputs registered in games. The clients mouse will move around the Windows cursor and is able to interact with the MAME tab menu, but won't send any inputs for MAME to pick up for the game being played.

I encountered this bug trying to play some 2 player trackball games. I use Parsec as a way to play some 2 player arcade games with a friend in another state and it works very well with gamepads, fightsticks and keyboard inputs with playable amounts of latency. With the trackball analog X/Y inputs set as Mouse X/Y, the host's mouse will register in the game but the clients will not.

**Comment by cuavas** [comment]
How does Parsec deliver mouse input to the target?  Does it create a virtual HID mouse device, or does it work some other way?  The default RawInput mouse provider only supports HID mouse devices, and won’t work if mouse events are delivered in any other way.  If Parsec delivers mouse input as pointer window events, it might work if you use MAME’s Win32 mouse provider.  If it appears as a different kind of virtual HID device (e.g. a digitiser or precision touchpad), it isn’t supported by MAME at this time.

**Comment by firewave** [comment]
Possibly related to https://mametesters.org/view.php?id=3451

**Comment by rb6502** [comment]
It's probably related as far as in both cases -keyboardprovider win32 -mouseprovider win32 will likely fix the problem, at a cost in additional lag.  But if you're playing over VNC or whatever, lag is kind of built into the equation.

**Comment by cuavas** [comment]
Without any evidence otherwise, closing as working as expected.  Use `dinput` or `win32` mouse module for mouse drivers that don’t support RawInput.

**Comment by cuavas** [comment]
> I recently tried Parsec, it allows mouse input from client from the UI only but not in-game. Windows 10 / -mouse_provider auto

Yes, because Parsec **does not look like an HID mouse device to RawInput**.  Try `-mouseprovider dinput` or if that still doesn’t work, try `-mouseprovider win32`.
