### ISSUE TITLE
"Error playing: 8888001" when starting with redirected audio output on Windows 10

### ISSUE THREAD

**Issue by mooware** [mamedev/mame#7938]
A Windows 10 update added the possibility to set the audio output device per application (see e.g. here https://www.howtogeek.com/352787/how-to-set-per-app-sound-outputs-in-windows-10/). This is very useful for streaming, to separate the game audio from other audio sources in OBS.

When I change the audio output device for MAME as described above while MAME is running, it works fine. But Windows remembers the setting and will reuse it when the same application is started again later. In that case, I'm getting the message "Error playing: 8888001" when starting a game and when returning to the game list. Changing the audio output device to default and back after that fixes the issue.

The issue originally occurred for me when redirecting to a virtual audio output device, which is common for streaming afaik. To rule out that the virtual device causes the issue, I attached my USB headset, which then becomes the default output, and then redirected MAME to the speakers, which still resulted in the same error.

The error seems to come from deep inside DirectSound, and I could not find any documentation for the error code, so it's possible that this is a bug in Windows / DirectSound, but it only happens in MAME for me, so it might be the case that there is an issue in MAME.

I tried debugging the error, and found that the error code comes from this location:

> dsound.dll!CEngineRendererConnection::Initialize(unsigned short const *,unsigned int,struct tWAVEFORMATEX const *,void *)
dsound.dll!CLeapSystem::ConnectRenderer(unsigned short const *,unsigned int,struct tWAVEFORMATEX const *,void *,struct ILeapRendererConnection * *)
dsound.dll!CLeapRenderDevice::ConnectRenderer(struct tWAVEFORMATEX const *)
dsound.dll!CLeapSecondaryRenderWaveBuffer::Connect(void)
dsound.dll!CLeapSecondaryRenderWaveBuffer::SetState(unsigned long)
dsound.dll!CDirectSoundSecondaryBuffer::SetBufferState(unsigned long)
dsound.dll!CDirectSoundSecondaryBuffer::Play(unsigned long,unsigned long)
dsound.dll!CImpDirectSoundBuffer<class CDirectSoundSecondaryBuffer>::Play(unsigned long,unsigned long,unsigned long)
mame64d.exe!sound_direct_sound::stream_buffer::play_looping() Line 140    C++
mame64d.exe!sound_direct_sound::dsound_init() Line 445    C++
mame64d.exe!sound_direct_sound::init(const osd_options & options) Line 260    C++
mame64d.exe!osd_module_manager::init(const osd_options & options) Line 62    C++
mame64d.exe!osd_common_t::init_subsystems() Line 685    C++
mame64d.exe!windows_osd_interface::init(running_machine & machine) Line 569    C++
mame64d.exe!running_machine::start() Line 210    C++
mame64d.exe!running_machine::run(bool quiet) Line 340    C++
mame64d.exe!mame_machine_manager::execute() Line 269    C++
mame64d.exe!cli_frontend::start_execution(mame_machine_manager * manager, const std::vector<std::string,std::allocator<std::string>> & args) Line 265    C++
mame64d.exe!cli_frontend::execute(std::vector<std::string,std::allocator<std::string>> & args) Line 281    C++
mame64d.exe!emulator_info::start_frontend(emu_options & options, osd_interface & osd, std::vector<std::string,std::allocator<std::string>> & args) Line 400    C++
mame64d.exe!main(int argc, char * * argv) Line 323    C++

**Comment by rb6502** [comment]
Do the different audio backends all do this?  -sound xaudio2 or -sound portaudio, for instance?

**Comment by mooware** [comment]
Neither xaudio2 nor portaudio give me the error, and sound works with both. xaudio2 also lets me redirect the audio output, but I can't redirect portaudio. So I can use xaudio2 as a workaround, thanks for the hint!

**Comment by rb6502** [comment]
Great!  We may eventually change xaudio2 to the default on Windows as it's more modern/supported than DirectSound.
