### ISSUE TITLE
SDLMAME for macOS messes up colors of Laserdisc games

### ISSUE THREAD

**Issue by kode54** [mamedev/mame#7939]
SDLMAME for macOS, as built and provided here:

https://sdlmame.lngn.net

Version 0.230.

Playing the cliffhgr Laserdisc title, it produces correct screen shots, like this:

![0000](https://user-images.githubusercontent.com/796316/113809563-44db4a80-971d-11eb-820f-051dd3340ea3.png)

But the default OpenGL output turns that into the following:

![cliffhgr_mac](https://user-images.githubusercontent.com/796316/113809774-b3200d00-971d-11eb-9266-a7a0529d3935.jpg)

The output looks the same whether I use the x86_64 or arm64 build. It also looks the same on my Intel MBP with Iris Pro Graphics.

**Comment by cuavas** [comment]
Are you sure you’re using OpenGL?  There’s an issue with BGFX video output producing vertical stripes like that on YUV video (see [MT07760](https://mametesters.org/view.php?id=7760)), but OpenGL should work.

**Comment by kode54** [comment]
Oh, you're right, I didn't know it was the `video` option, not the `videodriver` option. It defaults to `auto` here, now I've got it set to `opengl`.
