### ISSUE TITLE
How to make an empty floppy image for FM Towns?

### ISSUE THREAD

**Issue by Rugaliz** [mamedev/mame#7946]
So for some games I need a floppy inserted into the drive in order to save my progress.
How would I go about creating an empty floppy image for FM Towns? Is it possible to do it with MAMEs internal tools?

**Comment by cuavas** [comment]
This is not a discussion forum.  Please please ask general user questions on a community forum (e.g. [r/MAME](https://reddit.com/r/MAME), [Emuversal board](https://forums.bannister.org), [MAMEdev forum](https://forum.mamedev.org/) or #mame on EFnet IRC).
