### ISSUE TITLE
ksys573-based games are reporting 'BAD' CD-ROM in v0.172

### ISSUE THREAD

**Issue by justindarc** [mamedev/mame#796]
Launching games that are based on ksys573 (such as the DDR games) results in "CDR BAD" at boot-up with the message "HARDWARE ERROR...RESET". These games previously did not have this issue in v0.171.

**Comment by Tafoid** [comment]
Funny, I just put up a report for this at MAMETESTERS
http://mametesters.org/view.php?id=6176

If you find other confirmed bugs/regression and it is something that can be
duplicated with the release version (not current GIT), the report should be
filed at mametesters.org, not here.

**Comment by justindarc** [comment]
Cool, thanks! I will do that in the future.

**Comment by startaq** [comment]
Fixed in commit 22798a7.
