### ISSUE TITLE
Wrong speed video on Killer Instinct on Attract Mode

### ISSUE THREAD

**Issue by toniosj** [mamedev/mame#7970]
I think I have detected another bug in Killer Instinct.

It seems that the speed of the attract mode is not in accordance with the original, and the music is bugged from a certain point in time.

**Video MAME**: In the emulated game, you can see how at 0:54, it says KILLER INSTINCT when the guitar is playing and it cuts out and stops being heard in the GLACIUS and JAGO video and already during the The rest of the video is not heard again while the music is playing.
[Video MAME](https://www.youtube.com/watch?v=WcjAticJ_2Q)

**ORIGINAL board video**: Here you have the video of the intro of an original plate where the music sounds correctly throughout the video.
At minute 1:25, when the voice-over says "KILLER INSTINCT" on the original plate, the guitar continues to sound with the video of GLACIUS and JAGO.
[ORIGINAL board video](https://youtu.be/r_GKyTm_wtI)

I think the cause is that the video is faster in the emulated version. Here I put a comparative video between original board(left) against emulated version (right).
[Original & Emulated Comparison](https://www.youtube.com/watch?v=i5h-x3IOzfs)

**Comment by Hydreigon223** [comment]
Best to submit this to Mametesters. Quite frankly, it's a known issue since screen timings and parameters were never measured for this game to begin with.

**Comment by toniosj** [comment]
> Best to submit this to Mametesters. Quite frankly, it's a known issue since screen timings and parameters were never measured for this game to begin with.

Done! https://mametesters.org/view.php?id=7952
