### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by popey** [mamedev/mame#800]
Checking out latest revision from github I'm unable to successfully build mame on Ubuntu 16.04 AMD64.

Compiling src/osd/modules/render/binpacker.cpp...
Compiling src/osd/modules/render/bgfx/blendreader.cpp...
Compiling src/osd/modules/render/bgfx/chain.cpp...
Compiling src/osd/modules/render/bgfx/chainentry.cpp...
Compiling src/osd/modules/render/bgfx/chainentryreader.cpp...
Compiling src/osd/modules/render/bgfx/chainmanager.cpp...
In file included from ../../../../../3rdparty/rapidjson/include/rapidjson/document.h:20:0,
                 from ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:16:
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:200:15: error: expected unqualified-id before ‘bool’
     bool Bool(bool) { return static_cast<Override&>(*this).Default(); }
               ^
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:200:15: error: expected ‘)’ before ‘bool’
In file included from ../../../../../3rdparty/rapidjson/include/rapidjson/allocators.h:18:0,
                 from ../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:20,
                 from ../../../../../3rdparty/rapidjson/include/rapidjson/document.h:20,
                 from ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:16:
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h: In member function ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseTrue(InputStream&, Handler&)’:
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:720:45: error: expected unqualified-id before ‘int’
             if (RAPIDJSON_UNLIKELY(!handler.Bool(true)))
                                             ^
../../../../../3rdparty/rapidjson/include/rapidjson/rapidjson.h:466:51: note: in definition of macro ‘RAPIDJSON_UNLIKELY’
 #define RAPIDJSON_UNLIKELY(x) __builtin_expect(!!(x), 0)
                                                   ^
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:720:45: error: expected ‘)’ before ‘int’
             if (RAPIDJSON_UNLIKELY(!handler.Bool(true)))
                                             ^
../../../../../3rdparty/rapidjson/include/rapidjson/rapidjson.h:466:51: note: in definition of macro ‘RAPIDJSON_UNLIKELY’
 #define RAPIDJSON_UNLIKELY(x) __builtin_expect(!!(x), 0)
                                                   ^
In file included from ../../../../../3rdparty/rapidjson/include/rapidjson/document.h:20:0,
                 from ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:16:
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:725:5: error: expected ‘)’ at end of input
     }
     ^
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:725:5: error: expected statement at end of input
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:725:5: error: expected ‘}’ at end of input
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:725:5: error: expected ‘}’ at end of input
In file included from ../../../../../3rdparty/rapidjson/include/rapidjson/allocators.h:18:0,
                 from ../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:20,
                 from ../../../../../3rdparty/rapidjson/include/rapidjson/document.h:20,
                 from ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:16:
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h: In member function ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseFalse(InputStream&, Handler&)’:
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:733:45: error: expected unqualified-id before ‘int’
             if (RAPIDJSON_UNLIKELY(!handler.Bool(false)))
                                             ^
../../../../../3rdparty/rapidjson/include/rapidjson/rapidjson.h:466:51: note: in definition of macro ‘RAPIDJSON_UNLIKELY’
 #define RAPIDJSON_UNLIKELY(x) __builtin_expect(!!(x), 0)
                                                   ^
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:733:45: error: expected ‘)’ before ‘int’
             if (RAPIDJSON_UNLIKELY(!handler.Bool(false)))
                                             ^
../../../../../3rdparty/rapidjson/include/rapidjson/rapidjson.h:466:51: note: in definition of macro ‘RAPIDJSON_UNLIKELY’
 #define RAPIDJSON_UNLIKELY(x) __builtin_expect(!!(x), 0)
                                                   ^
In file included from ../../../../../3rdparty/rapidjson/include/rapidjson/document.h:20:0,
                 from ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:16:
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:738:5: error: expected ‘)’ at end of input
     }
     ^
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:738:5: error: expected statement at end of input
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:738:5: error: expected ‘}’ at end of input
../../../../../3rdparty/rapidjson/include/rapidjson/reader.h:738:5: error: expected ‘}’ at end of input
In file included from /usr/include/SDL2/SDL_syswm.h:72:0,
                 from ../../../../../src/osd/sdl/sdlinc.h:10,
                 from ../../../../../src/osd/sdl/window.h:14,
                 from ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:13:
../../../../../3rdparty/rapidjson/include/rapidjson/document.h: In member function ‘bool rapidjson::GenericValue<Encoding, Allocator>::Accept(Handler&) const’:
../../../../../3rdparty/rapidjson/include/rapidjson/document.h:1757:44: error: expected unqualified-id before ‘int’
         case kFalseType:    return handler.Bool(false);
                                            ^
../../../../../3rdparty/rapidjson/include/rapidjson/document.h:1757:44: error: expected ‘;’ before ‘int’
../../../../../3rdparty/rapidjson/include/rapidjson/document.h:1758:44: error: expected unqualified-id before ‘int’
         case kTrueType:     return handler.Bool(true);
                                            ^
../../../../../3rdparty/rapidjson/include/rapidjson/document.h:1758:44: error: expected ‘;’ before ‘int’
In file included from ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:16:0:
../../../../../3rdparty/rapidjson/include/rapidjson/document.h: At global scope:
../../../../../3rdparty/rapidjson/include/rapidjson/document.h:2320:15: error: expected unqualified-id before ‘bool’
     bool Bool(bool b) { new (stack_.template Push<ValueType>()) ValueType(b); return true; }
               ^
../../../../../3rdparty/rapidjson/include/rapidjson/document.h:2320:15: error: expected ‘)’ before ‘bool’
osd_sdl.make:947: recipe for target '../../../../linux_gcc/obj/x64/Release/osd_sdl/src/osd/modules/render/bgfx/chainmanager.o' failed
make[2]: *** [../../../../linux_gcc/obj/x64/Release/osd_sdl/src/osd/modules/render/bgfx/chainmanager.o] Error 1
Makefile:19: recipe for target 'osd_sdl' failed
make[1]: *** [osd_sdl] Error 2
makefile:1171: recipe for target 'linux_x64' failed
make: *** [linux_x64] Error 2

**Comment by balr0g** [comment]
@popey this is a known issue. We are working on resolving it within the next several hours.

**Comment by couriersud** [comment]
It should be fixed now. SDL2 includes X library headers in it's headers.
That really hurts.

On 04/09/2016 10:17 PM, balr0g wrote:
>
> @popey <https://github.com/popey> this is a known issue. We are
> working on resolving it within the next several hours.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mamedev/mame/issues/800#issuecomment-207848005>
>

-- 
André Hufschmidt
Feldbergstr. 60A
81825 München
M: +49 170 4570195

**Comment by popey** [comment]
Yup. Tested and now builds successfully. Thank you!
