### ISSUE TITLE
Error compiling 0.231 on latest Fedora Linux

### ISSUE THREAD

**Issue by Rugaliz** [mamedev/mame#8013]
I get this error while trying to compile the latest version on Fedora 34. I specifically used the bump version coommit to 0.231
Already installed all the packages for my system listed on the MAME doc. 
`GCC 11 detected
Compiling src/mame/machine/bbc.cpp...
../../../../../src/mame/machine/bbc.cpp: In member function ‘void bbc_state::insert_device_rom(memory_region*)’:
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
 1437 |                 if (!memcmp(rom->base(), m_region_swr->base() + (bank * 0x4000), 0x400))
      |                      ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
../../../../../src/mame/machine/bbc.cpp:1437:28: error: ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ specified bound 1024 exceeds source size 0 [-Werror=stringop-overread]
cc1plus: all warnings being treated as errors
make[2]: *** [acorn.make:520: ../../../../linux_gcc/obj/x64/Release/src/mame/machine/bbc.o] Error 1
make[1]: *** [Makefile:109: acorn] Error 2
make: *** [makefile:1395: linux_x64] Error 2
`

**Comment by startaq** [comment]
Possibly https://bugzilla.redhat.com/show_bug.cgi?id=1892100

**Comment by Tafoid** [comment]
You can likely work around (since they appear to be all -Werror) by using **NOWERROR=1** in your make string.

**Comment by Rugaliz** [comment]
@Tafoid That worked. Thanks for the quick responses both of you!
