### ISSUE TITLE
Sega System 16 Altered Beast does not start from version 0.227.

### ISSUE THREAD

**Issue by HubKing** [mamedev/mame#8030]
I am not sure if it is a bug or not, starting from version 0.227, Sega System 16 Altered Beast does not start with an error message like "315-5298.b9" is missing. The same ROM started fine with versions older than 0.227.

**Comment by quasiscroto** [comment]
You're missing the file by that name. It's an additional recent ROM dump required starting in 0.227. You'll either have to stick with a earlier version of MAME or update your altbeast set.

**Comment by HubKing** [comment]
> 
> 
> You're missing the file by that name. It's an additional recent ROM dump required starting in 0.227. You'll either have to stick with a earlier version of MAME or update your altbeast set.

Thanks for the information.
