### ISSUE TITLE
maclc3 : Unimplemented m68k FPU opcode causes 3D Atlas to crash

### ISSUE THREAD

**Issue by Saph32** [mamedev/mame#8049]
Hello!
I tried the new CD-ROM support for Macintosh and got that error while trying 3D Atlas on an LC III machine:

`Fatal error: M68kFPU: READ_EA_FPE: unhandled mode 7, reg 4, at 408EFC3E`

git revision 41a77f06d06af07c1d232de21458d709de6e4ec0  (May 9 2021)

Command line parameters : `mame.exe maclc3 -hard1 e:\MacMame\mac755.chd -ram 32M`

Using System 7.5.5. Pre-installed disk image can be found here : https://www.savagetaylor.com/downloads/downloads-macintosh/

3D Atlas can be found here : https://archive.org/details/EA3DAtlasmac

The crash happens after the first splash screen.

I fixed it locally by implementing the opcode based on https://github.com/jotd666/musashi040/blob/master/m68kfpu.c

Thank you !

**Comment by rb6502** [comment]
Thanks, this has been fixed and 3D Atlas launches and seems to work now.
