### ISSUE TITLE
ipf support broken ?

### ISSUE THREAD

**Issue by Flupper** [mamedev/mame#8061]
A while back I used ct486 driver + MS-DOS 6.22 to test some dual and tri-format Rob Northen formatted cover disks in ipf format.
I mounted them in -flop1, that went ok, but now I can't seem to mount them at all.
If I run from command line I get this error:
Fatal error: Device 3.5" high density floppy drive load failed: Unable to identify the image format

It used to work though
https://eab.abime.net/showpost.php?p=1439059&postcount=12

**Comment by ICEknigh7** [comment]
Couldn't find that IPF anywhere (@Flupper maybe you could [add those](https://wiki.mamedev.org/index.php/Submitting_Source_Code) to the softlist, please?), but can confirm that it also happens in the Spectrum +3 core.
![image](https://user-images.githubusercontent.com/47050710/118341797-ce521980-b520-11eb-9dd2-eebe2c56715e.png)

**Comment by Flupper** [comment]
Thanks for confirming the issue.
You can grab cover disks here:
https://mega.nz/file/awU3kSCL#SeHrawhLEEgvBgM17heF2Qe7DWkOloh74iytaVSxQmU
I also sent them to email in link above.

**Comment by Flupper** [comment]
Thanks for fixing the issue.
I can confirm ipf is now working again with a freshly built MAME.exe.
