### ISSUE TITLE
midtunit and midxunit (maybe more) crash on "Loading game"

### ISSUE THREAD

**Issue by Bloodbat** [mamedev/mame#8066]
When trying to load Midway games, such  as Mortal Kombat 1, 2 and Revolution X, with the latest official and stable Windows build the program crashes to desktop on "Loading machine xx%" with different percentages each time due to what the program reports as an access violation. What I think are the relevant parts of the -verbose log follow:

un7z: found revx.7z in cache
un7z: closing archive file revx.7z and sending to cache
419_revolution-x_u444.u444 ROM NEEDS REDUMP
snd-gal16v8a.u17 NOT FOUND (NO GOOD DUMP KNOWN) (tried in revx)
WARNING: the machine might not run correctly.
Optional memory region ':nvram' not found
Optional memory region ':screen' not found
Optional device ':dcs:data_map_bank' not found
Starting Revolution X (rev 1.0 6/16/94) ':'
  (missing dependencies; rescheduling)
Starting Midway W-Unit Video ':video'
Starting Texas Instruments TMS34020 ':maincpu'
  (missing dependencies; rescheduling)
Starting
-----------------------------------------------------
Exception at EIP=0000000000000001 (+0x0001): ACCESS VIOLATION
While attempting to write memory at 0000000000000001
-----------------------------------------------------
RAX=00000000001493a0 RBX=00000000001493e0 RCX=00000001515d7ec0 RDX=0000000000149260
RSI=0000000000000020 RDI=0000000000000000 RBP=0000000000149240 RSP=00000000001491b8
 R8=0000000000149368  R9=0000000000149224 R10=0000000000149238 R11=0000000000000001
R12=00000001515d7ec0 R13=000000014f198eb3 R14=0000000000149210 R15=0000000000149260
-----------------------------------------------------
Stack crawl:
  00000000001491b0: 0000000000000001 (+0x0001)
  00000000001492d0: 0000000143ca7a61 (std::ostream::off_type util::detail::stream_format<std::ostream, std::ostream>(std::ostream&, util::detail::format_argument_pack<std::ostream> const&)+0x0361)
  0000000000149300: 0000000147264294 (non-virtual thunk to osd_common_t::output_callback(osd_output_channel, util::detail::format_argument_pack<std::ostream> const&)+0x0044)
  0000000000149330: 0000000143cbc1dc (osd_vprintf_verbose(util::detail::format_argument_pack<std::ostream> const&)+0x002c)
  0000000000149460: 0000000143e94fe7 (running_machine::start_all_devices()+0x0117)
  0000000000149590: 0000000143e9ac59 (running_machine::start()+0x0ab9)
  00000000001496f0: 0000000143e9c753 (running_machine::run(bool)+0x00c3)
  000000000014f340: 00000001472718d0 (mame_machine_manager::execute()+0x01f0)
  000000000014f720: 000000014a094877 (cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x0397)
  000000000014f9e0: 000000014a094e33 (cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x0053)
  000000000014fa40: 000000014726ee0c (emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x002c)
  000000000014fe20: 000000014b05807f (main+0x017f)
  000000000014fef0: 00000001400013c1 (__tmainCRTStartup+0x0231)
  000000000014ff20: 00000001400014f6 (mainCRTStartup+0x0016)
  000000000014ff50: 00007fffcc877034 (BaseThreadInitThunk+0x0014)
  000000000014ffd0: 00007fffcdd02651 (RtlUserThreadStart+0x0021)

**Comment by Robbbert** [comment]
Known problem:
https://mametesters.org/view.php?id=7858

Workaround: turn off -verbose option

**Comment by Bloodbat** [comment]
> 
> 
> Known problem:
> https://mametesters.org/view.php?id=7858
> 
> Workaround: turn off -verbose option

I did the verbose because they crash without it as well.

The log for the attemped launch of Mortal Kombat WITHOUT -verbose.

un7z: reopened archive file E:\Emulators\mameroms\mk.7z
un7z: closing archive file E:\Emulators\mameroms\mk.7z and sending to cache
Optional device ':cvsd' not found
Optional device ':dcs' not found
Optional memory region ':nvram' not found
Optional memory region ':screen' not found
Starting Mortal Kombat (rev 5.0 T-Unit 03/19/93) ':'
  (missing dependencies; rescheduling)
Starting Midway T-Unit Video ':video'
Starting Texas Instruments TMS34010 ':maincpu'
  (missing dependencies; rescheduling)
Starting
-----------------------------------------------------
Exception at EIP=0000000000000001 (+0x0001): ACCESS VIOLATION
While attempting to write memory at 0000000000000001
-----------------------------------------------------
RAX=00000000001493a0 RBX=00000000001493e0 RCX=00000001515d7ec0 RDX=0000000000149260
RSI=0000000000000020 RDI=0000000000000000 RBP=0000000000149240 RSP=00000000001491b8
 R8=0000000000149368  R9=0000000000149224 R10=0000000000149238 R11=0000000000000001
R12=00000001515d7ec0 R13=000000014f198eb3 R14=0000000000149210 R15=0000000000149260
-----------------------------------------------------
Stack crawl:
  00000000001491b0: 0000000000000001 (+0x0001)
  00000000001492d0: 0000000143ca7a61 (std::ostream::off_type util::detail::stream_format<std::ostream, std::ostream>(std::ostream&, util::detail::format_argument_pack<std::ostream> const&)+0x0361)
  0000000000149300: 0000000147264294 (non-virtual thunk to osd_common_t::output_callback(osd_output_channel, util::detail::format_argument_pack<std::ostream> const&)+0x0044)
  0000000000149330: 0000000143cbc1dc (osd_vprintf_verbose(util::detail::format_argument_pack<std::ostream> const&)+0x002c)
  0000000000149460: 0000000143e94fe7 (running_machine::start_all_devices()+0x0117)
  0000000000149590: 0000000143e9ac59 (running_machine::start()+0x0ab9)
  00000000001496f0: 0000000143e9c753 (running_machine::run(bool)+0x00c3)
  000000000014f340: 00000001472718d0 (mame_machine_manager::execute()+0x01f0)
  000000000014f720: 000000014a094877 (cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x0397)
  000000000014f9e0: 000000014a094e33 (cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x0053)
  000000000014fa40: 000000014726ee0c (emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x002c)
  000000000014fe20: 000000014b05807f (main+0x017f)
  000000000014fef0: 00000001400013c1 (__tmainCRTStartup+0x0231)
  000000000014ff20: 00000001400014f6 (mainCRTStartup+0x0016)
  000000000014ff50: 00007fffcc877034 (BaseThreadInitThunk+0x0014)
  000000000014ffd0: 00007fffcdd02651 (RtlUserThreadStart+0x0021)
