### ISSUE TITLE
aviwrite cropped output for Megadrive based drivers

### ISSUE THREAD

**Issue by Bob-Z** [mamedev/mame#8094]
This is the output of

`mame megadriv sonic -aviwrite sonic.avi`

https://www.youtube.com/watch?v=AvxyfZEko6A

And the output of 

`mame barekch -aviwrite barekch.avi`

https://www.youtube.com/watch?v=_skySNW79F4

The right side of image is cropped. I have seen this only on Megadrive based hardware.

**Comment by DavidHaywood** [comment]
.avi doesn't support resolution changes / refresh rate changes mid-video

the megadrive hardware changes resolution based on the video registers

if you force a -snapsize all the output will scale to that, and you won't get a cropped video.

**Comment by vadosnaprimer** [comment]
MAME has code to stop the current segment and start a new one, so if it's used every time resolution or framerate changes, it'd be a neat solution.

**Comment by cd4053** [comment]
Create a `ini\source\megadriv.ini` file and add

`snapsize 320x224`

**Comment by Bob-Z** [comment]
Thanks all !

This fixes the croping:
`mame megadriv sonic -snapsize 320x224 -aviwrite sonic.avi`

Just out of curiosity, why the resolution is not set to 320x224 by default ?

**Comment by vadosnaprimer** [comment]
I bet the game (or just the driver itself?) starts out in lowres mode (256x244).
