### ISSUE TITLE
Where are defined Glyph colors used for rendering COMMAND.DAT ? (Not an issue)

### ISSUE THREAD

**Issue by stygmate** [mamedev/mame#8097]
I search the (monstruous) code base of mame and i cant' find where are defined glyph colors ...

**Comment by cracyc** [comment]
That was removed some time ago.

**Comment by stygmate** [comment]
> That was removed some time ago. Before they were removed they were in https://github.com/mamedev/mame/blob/4d7ef2749083e5e3aaf41e5b2c6b03a93c237c47/src/emu/ui/cmddata.h and they had been unused for years even then.

Thanks ! does this mean recent don’t handle command.dat anymore?

**Comment by cracyc** [comment]
It's supported no colors though.

**Comment by stygmate** [comment]
> It's supported no colors though.

Thank you !
