### ISSUE TITLE
Fatal error: fpgen_rm_reg: unimplemented opmode 1F at 408EF7D8

### ISSUE THREAD

**Issue by unassumingbadger** [mamedev/mame#8109]
MAME: 0.232
ROM: maclc3
Mac OS 7.6.1
Software: Photoshop 3.0

Executing Photoshop 3.0 crashes MAME 0.232 every time.

[MAME0.232_maclc3_photoshop3.txt](https://github.com/mamedev/mame/files/6557148/MAME0.232_maclc3_photoshop3.txt)

Photoshop 2.0 has the same status as 3.0 and with any 68030 Mac.

**Comment by angelosa** [comment]
Missing FGETMAN (Floating point GET MANtissa) opcode emulation from [68k FPU](https://github.com/mamedev/mame/blob/master/src/devices/cpu/m68000/m68kfpu.cpp#L1554)

**Comment by unassumingbadger** [comment]
Just for fun, I tried loading Strata 1.1. I knew there would be an FPU error, but its a new one this time.
fpgen_rm_reg: unimplemented opmode 31 at 01BC8DE0

You guys are killing me with nostalgia here.

**Comment by angelosa** [comment]
That's FSINCOS opcode (simultaneous SINe and COSine).

**Comment by rb6502** [comment]
With latest, Photoshop 3.0 now starts up and can load pictures.  https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=119340#Post119340
