### ISSUE TITLE
VGMPlay don´t works

### ISSUE THREAD

**Issue by Josmar34** [mamedev/mame#8119]
Good afternoon, MAME DEV Team. My name is Josmar Neyra Arellan and i will a problem with the new MAME 0.232. When i enter the command mame vgmplay in cmd, appears this error. It´s new the emulator version I have.[
![Captura de pantalla (1)](https://user-images.githubusercontent.com/38147271/120121836-4f3d2200-c16b-11eb-83f7-087f501df354.png)
](url)

**Comment by mahlemiut** [comment]
Looks like you're missing device ROMs - ym2413.zip, ym2608.zip and qsound.zip.

**Comment by Josmar34** [comment]
> Looks like you're missing device ROMs - ym2413.zip, ym2608.zip and qsound.zip.

Where I find that files or solve this problem? Other than that, I've been testing the emulator using my Turtles In Time rom and many music instruments sound louder than others or with certain problems, compared to past versions.

**Comment by galibert** [comment]
Telling you where to find rom files would be contributory copyright
infringement, so we don't do that.

  OG.
