### ISSUE TITLE
Remove rapidjson non-free bits from the distribution

### ISSUE THREAD

**Issue by jmallach** [mamedev/mame#814]
Hi,

While I was reviewing the licenses of all of the MAME distribution, I came across:

    3rdparty/rapidjson/bin/jsonchecker

The license of the material in this particular directory is considered non-free by Debian, Red Hat and all other major distributors. As it serves of no purpose for MAME, I suggest it is removed entirely from the next version.

From 3rdparty/rapidjson/license.txt:

    To avoid the problematic JSON license in your own projects, it's sufficient to exclude the
    bin/jsonchecker/ directory, as it's the only code under the JSON license.

The problem in particular is the JSON license has the following pointless clause:

    The Software shall be used for Good, not Evil.

**Comment by mmicko** [comment]
This is part of 3rdparty package, we try to keep those same as their
distribution. Guess problem is in distributing source package for MAME only?

**Comment by jmallach** [comment]
The problem is the contents of that directory would force all of the source package in non-free in Debian, and out of Fedora entirely, etc.

I would just post-process the import of new rapidjson versions to rm -rf jsonchecker entirely, or possibly better, switch to any of the many alternatives that were written to work around this license:

https://wiki.debian.org/qa.debian.org/jsonevil

**Comment by mmicko** [comment]
Ok clear.

**Comment by mmicko** [comment]
Fixed in 1a83c84eaeede7f5a735ac1f299bb43a47ca4a47
