### ISSUE TITLE
Vertical counter problem on Apple //GS emulation

### ISSUE THREAD

**Issue by jeremysrand** [mamedev/mame#8156]
I wrote a game called BuGS for the GS which is available here:

https://github.com/jeremysrand/BuGS/releases/download/1.0/BuGS_100.2mg

This game ran well under mame until v0.231.  From v0.231, I am finding that the bugs and the player on the screen tend to be invisible.  The game "races with the beam" and redraws the background as soon as the beam passes that point.  I was waiting for the vertical counter to reach (scan line + 256) before redrawing that part of the screen.  If I change that to (scan line + 280), then things start to work again.  It seems like the vertical counter is offset incorrectly from 0.231 onwards.

I believe this problem was introduced with commit e7d317c44a48d7e5d41d30e93eeb973fc71f35d6.

In order to demonstrate this problem in a smaller test case, please see the attached verttest.2mg file.  It draws lines at y = 7, 15, 23, etc down the screen.  Then, it waits for the beam to reach these lines and quickly makes the border colour white then black.  The border should have a thin white line just below the line across the screen.

I tested this in GSPlus (another GS emulator), mame 0.230 through 0.232 and finally on a real GS and got the images attached.  Note that in mame 0.231 and 0.232, there are border lines above scan line 7.  That indicates that the vertical counter is not following the actual emulated beam.  GSPlus, mame 0.230 and the real HW all look about the same to my eye.  So, I believe there is something wrong with the vertical counter commit referenced above.

If you would like the source code to vert test, let me know and I can make it available.  Thanks!
<img width="816" alt="GSPlus_verttest" src="https://user-images.githubusercontent.com/2031179/121119129-1810e580-c7e9-11eb-8273-79be4c8f868d.png">
<img width="1520" alt="mame_0 230_verttest" src="https://user-images.githubusercontent.com/2031179/121119133-1a733f80-c7e9-11eb-93d3-ffc44726973b.png">
<img width="1520" alt="mame_0 231_verttest" src="https://user-images.githubusercontent.com/2031179/121119135-1ba46c80-c7e9-11eb-9478-8b30150b048b.png">
<img width="1520" alt="mame_0 232_verttest" src="https://user-images.githubusercontent.com/2031179/121119136-1c3d0300-c7e9-11eb-8851-0517c88f9af5.png">
![real_GS_verttest](https://user-images.githubusercontent.com/2031179/121119251-48588400-c7e9-11eb-91b1-01b4ebe9c219.jpg)
[verttest.2mg.zip](https://github.com/mamedev/mame/files/6613335/verttest.2mg.zip)

**Comment by jeremysrand** [comment]
I should also mention that the picture of "real HW" was done through a VidHD that outputs a HDMI stream.  So, there is another interpretation of the video signal going on in that picture in order to translate the GS video to an HDMI signal.  I do think this is a good indication of what "real HW" would do and it is the best I can accomplish.  I don't think I have a working RGB monitor for my GS to test on.

**Comment by rb6502** [comment]
I was going to ask if that was an upscan or a VidHD, but in general I trust the VidHD.

**Comment by rb6502** [comment]
This has been fixed, and I verified that BuGS plays fine as well.
