### ISSUE TITLE
Bad joystick sorting on Linux

### ISSUE THREAD

**Issue by clebercasali** [mamedev/mame#8166]
On Linux, joysticks should by default be sorted by their device files (/dev/input/js*).
Joystick 1 should be "/dev/input/js0", joystick 2 should be "/dev/input/js1", and so on. This was the default behavior on older MAME versions, and it simply worked.
Currently they are sorted in the opposite order. Last joystick always gets enumerated as "joystick 1", the last but one always gets enumerated as "joystick 2". This is super counterintuitive.
Right now it's impossible to use "-joy_idx*" or "mapdevice" to sort joysticks on Linux if you have multiple devices with the same name/GUID.
Also, "-joy_idx*" and "mapdevice" should accept "/dev/input/js*" as parameter, to make things easier.

**Comment by rb6502** [comment]
Joysticks are presented in the order that SDL gives them to us.  Someone would need to write a joystick provider module that works directly with the kernel to change the order and make GUID mapping work.

**Comment by clebercasali** [comment]
Let's see what they say: https://github.com/libsdl-org/SDL/issues/4430
Didn't the old xmame have such a joystick provider?
I remember many years ago passing "/dev/input/js*" as a parameter.
How about this one: https://github.com/BirchJD/xmame-0.103-RPi/blob/master/src/unix/joystick-drivers/joy_standard.c

**Comment by cuavas** [comment]
That is a version of MAME so old it isn’t the same piece of software.  It’s like suggesting copying Windows 2 code into Windows 2000.

**Comment by clebercasali** [comment]
https://github.com/libsdl-org/SDL/issues/4430
It's in the SDL 2.0.16 milestone.

**Comment by cuavas** [comment]
This issue is a misunderstanding of how MAME works anyway – the SDL joystick provider module presents joysticks in the order SDL reports them and uses SDLs UUIDs for stable controller mapping.  This is consistent across targets that support the SDL joystick provider.

**Comment by clebercasali** [comment]
> This issue is a misunderstanding of how MAME works anyway – the SDL joystick provider module presents joysticks in the order SDL reports them and uses SDLs UUIDs for stable controller mapping. This is consistent across targets that support the SDL joystick provider.

Works great until you discover identical joysticks are impossible to manage because they have the same UUIDs and you have no clue which is which.

**Comment by clebercasali** [comment]
This script fixes my issue: [https://github.com/HugLifeTiZ/configs-scripts/blob/master/scripts/sdl-joystick-device](https://github.com/HugLifeTiZ/configs-scripts/blob/master/scripts/sdl-joystick-device)

**Comment by clebercasali** [comment]
Looks like it's fixed by this commit: https://github.com/libsdl-org/SDL/commit/ba8bc143c1691a837a9265d1911ea737d7bb8002
