### ISSUE TITLE
F1 Super Lap possible priority issue?

### ISSUE THREAD

**Issue by Riddler1** [mamedev/mame#8180]
I think the title screen score screen should look like this....

![Screenshot_20210612-132627_Gallery](https://user-images.githubusercontent.com/43607359/121776469-f5822200-cb84-11eb-9a54-035af8452d91.jpg)

with current mame, the forground road seems to cover the 3rd place and below entries

**Comment by Robbbert** [comment]
Already known:
https://mametesters.org/view.php?id=6100

**Comment by angelosa** [comment]
Noted in source too:
https://github.com/mamedev/mame/blob/master/src/mame/video/segas32.cpp#L43
Closing

**Comment by Riddler1** [comment]
thank you. The Priority issue is fixed in mame 2003+ so it seems it cannot be applied easily to current mame

**Comment by angelosa** [comment]
Most likely hacked around rather than "fixed".
Sega sprite priority levels are well known to have modes, and last time I checked wasn't able to pinpoint where it sets them out.
