### ISSUE TITLE
Debugger hotspots: irretrievably broken?

### ISSUE THREAD

**Issue by ajrhacker** [mamedev/mame#8193]
The debugger's hotspot tracker blatantly does not work as designed in current versions of MAME. This is due in part to bugs that have crept in with faulty code modernization, but a more fundamental problem is that it blindly traps all CPU reads that go through the memory system. Before @galibert's grand rewrite of the memory system, these did not include opcode and operand fetches (which were read "direct" from banks), but they do now, and this causes any useful information to be buried in noise.

A possible fix would involve restricting hotspot tracking to specific ranges of specific address spaces, possibly coupling the whole feature to the existing watchpoint system that handles that part quite well. I'm not sure that's even worthwhile, though: the existing implementation, not much different from the "rudimentary" version first implemented in 0.101u3, gives no feedback except when the whole search buffer fills up. Furthermore, I have doubts that the "speedup opportunities" whose discovery is its stated purpose constitute anything more than crude driver-specific and ROM-specific hacks with no applicability to the console and computer systems MAME has been increasingly concerned with emulating since the MESS merger.

Does this feature have a future? If so, how should it be reconceived?

**Comment by rb6502** [comment]
What's the hotspot tracker actually meant to do?  One thing some other computer emulators do that we don't is to show "heat maps", where the background color of each byte in a memory view gets progressively redder if it's hit more.  This allows you to come up with possible optimizations in programs being written for the original hardware.  For that use case, you don't want to restrict what addresses it sees.

**Comment by galibert** [comment]
For that use case, you probably don't want to remove the opcode accesses
either, since they have a massive performance impact.  Could the
memorization capabilities be made better (we can actually afford a 64-bits
counter per byte for most systems) and then we provide better filtering
capabilities when looking at the result?  Not that our current UI is
anything to write home about...

  OG.

**Comment by smf-** [comment]
For optimisation I would have thought the opcodes/operands were most
important. The data addresses that get read or written seem rather
redundant.

**Comment by aaronsgiles** [comment]
At this point probably best to just remove it, I think. The idea was to help auto-find tight loops in the code where speedup optimizations could be added, but we've largely moved away from that.

**Comment by smf-** [comment]
There are still systems where we apply speedup optimizations.

It would be a nice feature for people writing their own software.

But it does really need to be able to trigger only on the instruction
fetches, potentially it might be useful for data fetches too but I can't
think why.

**Comment by ajrhacker** [comment]
The hotspot tracker has been removed as of 57ddc51b52f53cc33bfe810beb5f38dabf73ab85. There might be a reason for bringing something vaguely like it back later, but how it parses read accesses really needs to be rethought.
