### ISSUE TITLE
windows 11 crash

### ISSUE THREAD

**Issue by arcade-legend** [mamedev/mame#8221]
Hello,

Mame crashes on windows 11 64 bit (leaked version)

No error message given by mame but windows 11 says 'program needs to close'.

Any ideas?

Latest audio and nvidia drivers installed, while my games all run fine.

**Comment by rb6502** [comment]
We don't support pre-beta operating systems, and you definitely shouldn't run them directly on your main computer - that's what VirtualBox/VMWare/qemu-kvm/etc are for.
