### ISSUE TITLE
Question about ctrlr files : remap? origcode? newcode?

### ISSUE THREAD

**Issue by clebercasali** [mamedev/mame#8241]
`<remap origcode="KEYCODE_UP" newcode="KEYCODE_8PAD" />
<remap origcode="KEYCODE_DOWN" newcode="KEYCODE_2PAD" />
<remap origcode="KEYCODE_LEFT" newcode="KEYCODE_4PAD" />
<remap origcode="KEYCODE_RIGHT" newcode="KEYCODE_6PAD" />`

I have seen this code in some example ctrlr files, but I can't find an explanation in the docs on what exactly does it do.
I couldn't notice any difference either.
Can anyone explain it? Thanks.

**Comment by cuavas** [comment]
This is not a discussion forum.  Please do not abuse the issue tracker.  Consider asking your question on reddit at r/MAME or on another forum.

**Comment by arcade-legend** [comment]
This is exactly the problem of mame
there are no docs and the 'other forums' which will give this person his explanation for his question do not exist...

**Comment by cuavas** [comment]
FWIW basic controller configuration file features are now documented: https://docs.mamedev.org/advanced/ctrlr_config.html

However, we maintain our position that the issue tracker is not to be abused for user questions and general discussion.  We have IRC presence, a number of us are on Reddit’s r/MAME, we have an official forum, and a number of us frequent Emuversal and MAME World forums.  There are plenty of places you can ask questions and have a discussion.
