### ISSUE TITLE
MIDI Out on Linux = crash

### ISSUE THREAD

**Issue by human222** [mamedev/mame#8249]
mame -rompath "/run/media/segphault/SSDData/Content/mame roms" x68000 -flop1 "/run/media/segphault/SSDData/Content/sharp x68000 floppy/daimakai/daimakaimura (1994)(capcom)(disk 1 of 2)(system).dim" -flop2 "/run/media/segphault/SSDData/Content/sharp x68000 floppy/daimakai/daimakaimura (1994)(capcom)(disk 2 of 2)(data).dim" -exp1 x68k_midi -midiout "Midi Through Port-0"
/usr/include/c++/11/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::reference = unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

----------------

Tested on Fedora 34 with the distro's packages.

**Comment by cuavas** [comment]
This is caused by Fedora packagers turning on debug assertions for release builds against our recommendations.  Please take it up with the packagers.

**Comment by rb6502** [comment]
Just adding: it's easy enough to compile MAME yourself on Fedora, and then you don't have weirdness like this.

Instructions are here: https://docs.mamedev.org/initialsetup/compilingmame.html#fedora-linux

**Comment by human222** [comment]
Thanks, compiling MAME was much easier than I expected. I'll do that from now on.

![mame midi](https://user-images.githubusercontent.com/86888468/124488066-b627a980-ddaf-11eb-88c2-cf64acd2d227.png)

**Comment by DavidHaywood** [comment]
any way we can detect this and throw up a warning that the build has been incorrectly compiled (and that they should contract the distro / compile it themselves) thus making it clear the feature is not available rather than crashing?

**Comment by cuavas** [comment]
I've asked the distro packagers to provide a disclaimer in the package description. There's not much else we can do. If we add warnings for things like iterator debug and fortify source in release builds, they'll probably patch them out anyway.

**Comment by DavidHaywood** [comment]
why would they patch them out? they're informative / useful.
