### ISSUE TITLE
C++23 prohibits constructing `std::string` from `nullptr`

### ISSUE THREAD

**Issue by StephanTLavavej** [mamedev/mame#8265]
I work on MSVC's C++ Standard Library implementation, and we regularly build MAME (along with many other open-source projects) to identify compiler/library bugs that would break your project, so we can fix them before shipping. This also allows us to provide advance notice of source-breaking changes - which is the case here.

The paper [P2166R1](https://wg21.link/P2166R1) "Prohibiting `basic_string` And `basic_string_view` Construction From `nullptr`" has been accepted for the upcoming C++23 Standard, and we recently implemented it by merging https://github.com/microsoft/STL/pull/1995 from our contributor @sam20908. Our open-source test pass then discovered the following code in MAME that is now disallowed by C++23:

https://github.com/mamedev/mame/blob/b0bc45a6a419de726a060b3b350065b156b35977/src/lib/formats/cassimg.cpp#L224-L230

Here, `cassette_image::open()` is passing `nullptr` for the `const std::string &extension` parameter of `cassette_image::open_choices()`. This has always been undefined behavior in C++98 through C++20 (`basic_string`'s constructor has a precondition that the pointer is non-null); C++23 has added a deleted overload of `basic_string`'s constructor to detect when the argument is known to be `nullptr` at compile-time. (Runtime values of `const char *` that happen to be null are still undefined behavior.)

There are several possible ways to fix this code; you could pass an empty string with `""` or `std::string{}` or even `{}` (depending on whether `open_choices()` is overloaded).

There may be additional occurrences of this throughout MAME's codebase - this is simply the first one we encountered. Hope this helps!

**Comment by cuavas** [comment]
Yeah, we shouldn’t be constructing `std::string` from `nullptr`.  In this case, I think it should be passing `std::string()` rather than `nullptr` in the call to `open_choices`.  Could someone (e.g. @Tafoid or @Robbbert) test this change?

**Comment by ajrhacker** [comment]
Constructing strings from `nullptr` already causes segmentation faults or runtime assertion errors on many builds. Bugs like this (e.g. 3a04996ab50ff2e18240747a8dbf0a0c60acc9b7) have persisted mostly due to obscurity.

**Comment by Robbbert** [comment]
This bug was created almost 5 years ago and survived a number of refactors since.

I tested `std::string()`, however a different bug appeared which I can't explain, that being if the tape was preset to PLAY, it instead was STOPPED. So I used `{}` instead.

See 645aef00d7b133dc65a3c5aa54563a0590bcb1ad

**Comment by Robbbert** [comment]
No further comments, so closing.
