### ISSUE TITLE
nemesis.cpp: video crystal math possibly incorrect

### ISSUE THREAD

**Issue by Firebrandx** [mamedev/mame#8280]
Line 1733 shows the following:

m_screen->set_raw(XTAL(18432000.0)/4, 288, 0, 256, 264, 2 * 8 , 30 * 8);

However, dividing the crystal by 4 makes for a very wide PAR. According to PCB examination and output testing, the crystal is actually divided by 3, making for a PAR of 5625:5632 (effectively square pixels on a CRT). Further, this information of the crystal being divided by 3 is actually mentioned twice in the basic arcade specs in the same document.

Credit to Ace for checking his Salamander PCB to confirm the crystal is divided by 3, not 4. I've already corrected the PAR information on https://pineight.com/mw/?title=Dot_clock_rates

-FBX

**Comment by Firebrandx** [comment]
BTW we only found out about this because Pin Eight cited this document as to their conclusion of the PAR being based on the crystal being divided by 4. I updated the entry, but then someone from Pin Eight lumped my research into the Namco timings (because they happened to end up in the same PAR), sent me a really rude letter, and then apologized to MAMEDevs as though I somehow did something wrong (when Pin Eight was the one that cited the document in the first place).

I am absolutely done contributing PAR research to that site, and will begin coding my own database.

**Comment by angelosa** [comment]
So if I'm following correctly:
`m_screen->set_raw(XTAL(18432000.0)/3, 384, 0, 256, 264, 2 * 8 , 30 * 8);`
a.k.a. htotal = 384?

**Comment by Firebrandx** [comment]
Probably. The main point being the document was cited for the frequency being 4.608 MHz and thus a rather wide PAR that doesn't match existing hardware behavior. In reality, the frequency should be 6.144 MHz, making for a PAR that is almost perfectly square.

**Comment by galibert** [comment]
Hopefully Phil B will be able to check the exact screen/blank/sync sizes in
dot clocks soon.

  OG.

**Comment by pinobatch** [comment]
I seek help toward figuring out what would be an appropriate way to show different crystal derivations that lead to the same PAR.

**Comment by galibert** [comment]
The /3 seems correct.  The difficulty is figuring out the exact screen
width and height, position and duration of the blanks, and phase of the
V256 signal.  The schematics don't help at all.

  OG.
