### ISSUE TITLE
lwriter has "Fatal system error @ 0x2a8416" when running text drawing code

### ISSUE THREAD

**Issue by jrmuizel** [mamedev/mame#8309]
This happens when trying to print the test page or when running the following code from the executive:
```ps
/Helvetica findfont 12 scalefont setfont
300 400 moveto
(Hello) show
```

One thing I've noticed when trying to debug this, is that it seems related to something going on in the framebuffer. Perhaps more interestingly, some of the accesses to the framebuffer seem to happen through the mirrored portion of the DRAM. 
https://github.com/mamedev/mame/blob/c58ba7d39ca0ad23c6d961525e7606f54d3b6cbe/src/mame/drivers/lwriter.cpp#L228

More specifically, the framebuffer is cleared through the `0x400000-0x5fffff` range but then later modified through the `0x600000, 0x7fffff` range. @rb6502 can you think of why it would be written to do this vs. just always using the `0x400000-0x5fffff` range?

**Comment by rb6502** [comment]
As a guess, maybe it's not supposed to be mirrored and it's misdetecting 4 MB of RAM?  I'd try without the .mirror and see if that helps.  Or remove the mirror and make it a true 4MB of RAM.

**Comment by jrmuizel** [comment]
So I took a closer look the usage of the `0x600000-0x7fffff` range and it appears that when code writes to that range it expects the written value to be bitwise or'd with existing value instead of overwriting it. @rb6502, is that kind of behaviour at all plausible? If so what's the best way to implement it in MAME?

**Comment by rb6502** [comment]
That's certainly plausible, although it's kind of surprising.  I guess it's kind of an accelerator feature.

For implementation, remove the .mirror from the DRAM range and add regular read and write handlers for the 0x600000-0x7fffff range that use the existing m_dram_ptr to access the DRAM.
