### ISSUE TITLE
CFG files don't save the settings of UI

### ISSUE THREAD

**Issue by arcade-legend** [mamedev/mame#8322]
Hi

I quote you: "That isn’t true. Input settings (host input bindings, analog sensitivity, DIP switch state, machine configuration state, and toggle and adjuster state) are saved per system in CFG files. "

I changed a DIP switch state for the game "005" (number of lives).
I opened the CFG file 005.CFG and this is the content of the file (see attachment).

No sign of a saved DIP switch value in this XML file while the dip switch value is remembered in the UI.
Where is it saved then?

[005.zip](https://github.com/mamedev/mame/files/6851095/005.zip)

**Comment by cuavas** [comment]
You are doing something wrong.  DIP switch settings are saved correctly between runs in mainline MAME, and it’s such a fundamental feature, we’d notice incredibly quickly if it wasn’t working.  Here’s the content of my Money Idol Exchanger configuration file (miexchng.cfg) after changing a few settings:
```
<?xml version="1.0"?>
<!-- This file is autogenerated; comments and unknown tags will be stripped -->
<mameconfig version="10">
    <system name="miexchng">
        <video>
            <target index="0" view="Screen 0 Stretched (304x224)" />
        </video>
        <counters>
            <coins index="0" number="6" />
        </counters>
        <input>
            <port tag=":DSW" type="DIPSWITCH" mask="1" defvalue="1" value="0" />
            <port tag=":DSW" type="DIPSWITCH" mask="24" defvalue="24" value="16" />
            <port tag=":edge:joy:JOY1" type="P1_BUTTON1" mask="16" defvalue="16">
                <newseq type="standard">
                    KEYCODE_LSHIFT
                </newseq>
            </port>
            <port tag=":edge:joy:JOY1" type="P1_BUTTON2" mask="32" defvalue="32">
                <newseq type="standard">
                    KEYCODE_Z
                </newseq>
            </port>
        </input>
        <image_directories>
            <device instance="memcard" directory="C:\Users\_merlin\Documents\checkout\mamedev\mame-mainline" />
            <device instance="cartridge" directory="C:\Users\_merlin\Documents\checkout\mamedev\mame-mainline" />
        </image_directories>
    </system>
</mameconfig>
```

Note that it’s saved the selected view, the coin counter value, DIP switch settings (settings mode and cabinet number are modified), the host key bindings for player 1 buttons A and B, and the last loose media directories used for the memory card and cartridge slot.

**Comment by arcade-legend** [comment]
Only working for specific values, very very inconsistently!
