### ISSUE TITLE
bug: CFG file does NOT save specific DIP switch values

### ISSUE THREAD

**Issue by arcade-legend** [mamedev/mame#8323]
Hi

Please stop closing reports about bugs!

Following these steps:

- run game 005
- change DIP switch number of lives to 3
- exit MAME

Open the file 005.cfg and there is NO DIP switch value saved...

However if you set number of lives to 4, then there is a value in the CFG file.

That's a VERY strange way of saving things. Value 3 is not saved, but value 4 is indeed.

**Comment by cuavas** [comment]
Stop opening reports for things you don’t understand.  If you do it one more time, you will be banned.  This is not a discussion forum.

The default lives DIP switch setting is 3 lives, so the value does not need to be saved.  MAME does not save settings for DIP switches that are set to the defaults.  (The same goes for host input assignments and a few other things.)

If you want to better understand how MAME works, you can discuss it on a forum of some kind.  You’re just wasting everyone’s time including your own by creating invalid issue reports.

**Comment by arcade-legend** [comment]
and in what file is the value 3 saved then?

**Comment by 0kmg** [comment]
> and in what file is the value 3 saved then?

It's in the mame executable itself. If you run `mame 005 -listxml` it will give you various info about the game including the dipswitch settings. You can find in the output a section that looks like:
```
               <dipswitch name="Lives" tag="D3D2" mask="3">
                        <diplocation name="SW1" number="8"/>
                        <diplocation name="SW1" number="7"/>
                        <dipvalue name="3" value="0" default="yes"/>
                        <dipvalue name="4" value="2"/>
                        <dipvalue name="5" value="1"/>
                        <dipvalue name="6" value="3"/>
                </dipswitch>
```
Have a pleasant day.
