### ISSUE TITLE
some issues to make myself clear

### ISSUE THREAD

**Issue by arcade-legend** [mamedev/mame#8324]
1) Stop opening reports for things you don’t understand. If you do it one more time, you will be banned. This is not a discussion forum.

YOU ARE NOT HERE TO TELL WHAT I CAN DO OR NOT
MAME IS OPEN SOURCE AND NOBODY OWNS IT
GITHUB IS NOT YOUR PROPERTY

2) I can't help posting "invalid reports" if mame saves some values, some not all and finally some for a certain value,all without any consistency or any logic behind it.

BUY YOURSELF A DICTIONARY AND LOOK UP THE WORD "CONSISTENCY" AND APPLY THIS TO THE SOURCE CODE 
BECAUSE OF THIS INVALID REPORTS ARE OCCURING...
WE USERS CANT KNOW ALL THE WEIRD IDEAS YOU JUST TELL ME...

3) YOU OR ANYBODY ELSE CANT BAN ANYONE HERE BECAUSE GITHUB ACCOUNTS CAN BE CREATED FOR FREE AND UNLIMITED

*Sigh*

**Comment by arcade-legend** [comment]
You should also learn some manners and don't scare people away.

**Comment by arcade-legend** [comment]
so if you want to "ban" me based on very valid reports I post here because as a user I can't know all the ideas behind the " save or not" of a UI setting, go ahead!
this will make you very popular among developers here and confirm your agressive and non patient way of talking.

please not that because of the inconsisent saving of UI setting of mame, reports like mine occur...
so it's not my fault

Best regards

**Comment by rb6502** [comment]
It's not inconsistent.  If the value is the same as MAME powers up with out of the box, it isn't saved because THE SETTING IS ALREADY THAT VALUE.

**Comment by angelosa** [comment]
You won't get anyone's sympathy by writing in ALL CAPS, please learn the netiquette.

It's also very wise idea opening new issues stating 4 times you don't understand how .cfg works out.
For me (and for the sanity of anybody willing to do some project management in the future) marking these all as invalid is the right choice since to my eyes this is blatant attention seeker spam. You would have continued the discussion on the original issue if you really bothered.

**Comment by arcade-legend** [comment]
I just moved to retroarch using libretro mame core

FYI:

- friendly support on the forum
- mame core runs on ALL devices and OSes you can imagine (compared to mame's poor OS support, not even android...)
- mame core saves ALL settings and there are a ton more of them as in mame itself...

**Comment by rb6502** [comment]
Enjoy the lower framerates, games that don't randomly work, and a "mame core" that's 6 months behind our current progress and lagging further all the time.

**Comment by arcade-legend** [comment]
See my feature request then...

**Comment by MooglyGuy** [comment]
You've been working on a libretro-oriented frontend for months. I have a feature request that you either take your medication, or try harder when trolling next time.
