### ISSUE TITLE
Original LaserWriter support

### ISSUE THREAD

**Issue by jrmuizel** [mamedev/mame#8325]
It looks like the original LaserWriter is quite similar to the LaserWriter II NT and the LaserWriter ROMs from --moderated indirect link to roms-- mostly work with a couple of small changes (https://github.com/jrmuizel/mame/commit/88585be07ebfa460c917102147ed4d1d55da3fd8). However, both LaserWriter and LaserWriter II NT ROMs are version 47.0 so it's not that interesting or useful to run those original LaserWriter ROMs. It would be a lot more interesting, though, to run the earlier "Rev 2" or "Rev 1" ROMs. If anyone has access to dumps of these, I'd love to get them running.

**Comment by Robbbert** [comment]
So this is a rom request?

You'll have to do that elsewhere.

**Comment by kossow** [comment]
if it has roms matching the NT, it is a late production Laserwriter Plus
the original laserwriter has roms half that size, and the plus has 16 roms instead of 8

**Comment by jrmuizel** [comment]
Those Laserwriter ROMs don't match the NT ROMS exactly they're just using the same version of PostScript (i.e. 47). They are half the size and there are 8 of them so I'm pretty sure they're not from a Laserwriter Plus. Here's a picture of the board that they're from: https://i.redd.it/iatn323rrt311.jpg

**Comment by happppp** [comment]
1) Is it worth having this issue open? Or is it like having "MAME doesn't emulate Crazy Otto"?
2) does https://github.com/mamedev/mame/pull/8391 resolve it?

**Comment by jrmuizel** [comment]
#8391 will resolve it.
