### ISSUE TITLE
feature request: android version

### ISSUE THREAD

**Issue by arcade-legend** [mamedev/mame#8327]
hi

why is there no android version available and therefore keeping mame completely off the mobile world?

why do we need to use retroarch to play mame on our phones/tablets?

Ps: this is not a negative comment, but only a question to try to find the reason behind.
I know this is not a discussion forum but this is a feature request/question all in one 🙂

Thx

**Comment by Robbbert** [comment]
This is not a discussion forum Jessica/Alexis whatever you're calling yourself today.
Go away.
