### ISSUE TITLE
nscsi/cd.cpp magic apple mode sense page is missing page id byte

### ISSUE THREAD

**Issue by sneakywumpus** [mamedev/mame#8351]
I was playing around with the SGI Indy emulation in mame0233 and couldn't boot from CD.
After git bisecting i narrowed the failure down to commit 32151b1f0c3b80f8f2e59bc4bcc9b62f477d28c5,
which added a special Apple mode sense page for CD-ROM.
But this code doesn't add a page id, which messes up the structure of the mode sense result.
Appended is a patch which allows me to boot the emulated Indy from CD.
[cd.txt](https://github.com/mamedev/mame/files/6872404/cd.txt)

**Comment by rb6502** [comment]
Fixed in https://github.com/mamedev/mame/commit/cce5ce373d10b3987dffc891f567b1a04f8de411 and I verified it doesn't break the Mac.
