### ISSUE TITLE
The display problem since 0.234：fullscreen aspect ratio is incorrect when use integer scaling

### ISSUE THREAD

**Issue by crashGG** [mamedev/mame#8387]
When setting “unevenstretch  0” in mame.ini, the window playback looks good, but the ratio is wrong when switching to fullscreen.The same setting is normal in 0.233 and previous versions.
I think the integer scaling is very useful. A perfect point-to-point display effect can be achieved on modern LCD screens. Please fix it.

Attach my settings file, I think anyone can reproduce this pro
[mame.ini.zip](https://github.com/mamedev/mame/files/6912866/mame.ini.zip)
blem.

**Comment by antonioginer** [comment]
Please, could you be more specific? What screen resolution are you using? What game is exposing the issue?

Please bear in mind that, regardless of the possible issue, aspect ratio is going to be incorrect most of the times when using integer scaling on an LCD.

**Comment by cuavas** [comment]
@antonioginer it also appears that the change causes `-uesx` and/or `-uesy` to interfere with screenshot size calculation: https://www.reddit.com/r/MAME/comments/ornl22/is_this_a_desired_effect/ (I think that‘s what the user is trying to say there, it’s not a particularly helpful report).

**Comment by antonioginer** [comment]
Ok I didn't know about the screenshot issue, but my understanding is that OP is just starting with -nomaximize, then does ALT+ENTER.

**Comment by cuavas** [comment]
Yes, that’s unrelated to the issue reported here – I just wanted to draw it to your attention.

**Comment by antonioginer** [comment]
> Yes, that’s unrelated to the issue reported here – I just wanted to draw it to your attention.

Thanks for pointing to that, it's an easy fix. In short, all scaling and aspect settings should be turn off for hidden targets, on render target creation. Are there any other cases of hidden targets aside of snapshots and video recording that would need any fancy scaling?

**Comment by cuavas** [comment]
I can’t think of any others at the moment.

**Comment by crashGG** [comment]
I'm sorry I didn't write it in detail. This problem affects all games. So I thought everyone had discovered this problem.My operating system is win10 x64 1809, graphics is intel HD 5300, and the LCD display resolution is 1920x1080.

The first example: **shadfrce**
mame 0.233 in window:
<img width="960" alt="233 shadfrce w" src="https://user-images.githubusercontent.com/80488411/127873218-a58f48e4-f9d3-4a1b-a4b7-c8458e33420b.png">

press Alt+enter to fullscreen:
<img width="960" alt="233 shadfrce f" src="https://user-images.githubusercontent.com/80488411/127873332-dc56a4f0-007e-49d3-a341-d1da7ed0e946.png">

mame 0.234 in window:
<img width="960" alt="234 shadfrce w" src="https://user-images.githubusercontent.com/80488411/127873470-92f9387b-8826-4c41-aae4-f9e32535001c.png">

press Alt+enter to fullscreen:
<img width="960" alt="234 shadfrce f" src="https://user-images.githubusercontent.com/80488411/127873519-cf4babcf-e991-4a19-a5c0-1cd2061ec931.png">

The 2nd example: **sf2**
mame 0.233 in window:
<img width="960" alt="233 sf2 w" src="https://user-images.githubusercontent.com/80488411/127873641-f2aef438-e6d9-4005-80e6-7bf754dcfadf.png">
press Alt+enter to fullscreen:
<img width="960" alt="233 sf2 f" src="https://user-images.githubusercontent.com/80488411/127873676-ff2b6493-0168-4937-9c12-863335143974.png">
mame 0.234 in window:
<img width="960" alt="234 sf2 w" src="https://user-images.githubusercontent.com/80488411/127873836-32f9eac5-9921-4d4d-9688-62fa9048723f.png">
press Alt+enter to fullscreen:
<img width="960" alt="234 sf2 f" src="https://user-images.githubusercontent.com/80488411/127873882-79a35265-d87d-499a-8058-33294ac9c8e2.png">

mame0.233 and 0.234 are in the same mame.ini
in mame.ini, I used these personalization options:
window                    1
maximize                  1
unevenstretch           0

**Comment by crashGG** [comment]
I think these settings are very good. Because in the case of integer scaling,all pixels can be displayed on the screen point-to-point, which can bring the sharpest images and characters to the LCD screen without edge blur. As for the price, some areas around the screen are lost. But if the screen is big enough, who cares。And most games can achieve the correct ratio under these settings。Like the cps1 cps2 cps3 series machines, the native ratio is not 4:3 (384:224). After these settings, mame intelligently scales the horizontal pixels by 3 times and the vertical pixels by 4 times on my screen, reaching a close to 4:3 Ratio (actually 9:7)

**Comment by antonioginer** [comment]
Confirmed here. Let me do some checks.

**Comment by ICEknigh7** [comment]
> I think these settings are very good. Because in the case of integer scaling,all pixels can be displayed on the screen point-to-point, which can bring the sharpest images and characters to the LCD screen without edge blur. As for the price, some areas around the screen are lost. But if the screen is big enough, who cares。And most games can achieve the correct ratio under these settings。Like the cps1 cps2 cps3 series machines, the native ratio is not 4:3 (384:224). After these settings, mame intelligently scales the horizontal pixels by 3 times and the vertical pixels by 4 times on my screen, reaching a close to 4:3 Ratio (actually 9:7)

You can actually have sharp pixels without blurring and the correct aspect ratio if you set prescale to 4 in mame.ini.

**Comment by Rugaliz** [comment]
Is this issue being worked on? As of MAME 0.236 the image is really stretched when it shouldn't be. This is for the X68000 running castlevania. Its so stretched even though uneven stretch is off.
![Screenshot from 2021-10-05 11-34-21](https://user-images.githubusercontent.com/37263443/136007466-68bfe263-4bc8-458a-9e5a-24d1104746c4.png)

**Comment by ICEknigh7** [comment]
@Rugaliz Do you have "Correct aspect ratio" turned on?

**Comment by antonioginer** [comment]
> Is this issue being worked on? 

Yes, it's being worked on. I'll address this as soon as I have some time.

In the meantime, you should probably use -unevenstretchx instead of full integer scaling, that doesn't make much sense on LCDs, specially if you're passing the picture through filters as it looks like you are.

**Comment by Gryzor1363** [comment]
Hi everyone, glad to see this issue has been noticed and being addressed, thanks a lot to the devs, namely Antonio Giner for the last update here. For my part I posted about this issue a few weeks ago on reddit, and found a workaround by applying these settings : 

**unevenstrech 0
keepaspect 1
autostretchxy  1**

Basically, simply by adding the last additional parameter to the existing ones, which is autostretchxy 1, you will obtain identical results in 0.235 and 0.236 as you did before with just the first two usual flags.
That would be an interesting stop-gap until this is worked on. I tested with both Horizontal and Vertical games, and the setting work.

I did so following advice from a MAME developer called "cuavas", who pointed me to this ticket by Antonio himself, dating back June '21. I just noticed by willing to link it here. For reference, here it is : 

https://github.com/mamedev/mame/pull/8209

Oddly, from my interpretation, the new behavior would have been a "logical one" past 0.234 , since according to Cuavas, and I agree after thinking it through a bit, it is not feasible to obtain correct , pixel-perfect, integer X and Y axis when trying to adapt both from an "exotic" original ratio. So it seemed in the end an expected requirement to have one of the axis non-integer (usually the X axis, vertical compliance to 240p being of paramount importance to ensure correct scanline shape and position for any given game) but I also felt I was missing something.

**Comment by john-iv** [comment]
Perhaps tangentially related; seeing cropping of vertical games with -autostretchxy on a 2560x1440 monitor that does not happen on a 1920x1200 monitor.

mame puckman -nofilter -autostretchxy -verbose -norc

Mame Testers bug: https://mametesters.org/view.php?id=8110

**Comment by Gryzor1363** [comment]
Hi john-iv,

good call, I have the same issue for *some* vertical games as well. I can confirm this is related in my case too. Went through your mametesters bug report, and can confirm the cropping along X for some vertical games. Those indeed require not autostretchxy 1 to be sized properly but **unevenstretchx 1**

Best way to experiment "live" is to use MameUI's in-game video options. They indeed allow you to change core video option flags on the fly and see immediate results per game.

**Comment by antonioginer** [comment]
Hi, this is just a heads up in case it went unnoticed, I made a PR https://github.com/mamedev/mame/pull/8961 to fix all issues reported here and probably others.

Although I tested it extensively, it'd be appreciated if someone else could try it too to see if works as expected in their case.

**Comment by john-iv** [comment]
Would you mind making a Win x64 .exe available and I can check my use cases.  Thanks -

**Comment by stilett0** [comment]
> 

you can download the CI windows build artifact, I'd imagine, @john-iv :
https://github.com/mamedev/mame/suites/4760739483/artifacts/132222093

**Comment by john-iv** [comment]
Thanks Stiletto, this build does indeed address my issues reported above.  No more cropping w/ -autostretchxy on certain vertical games, esp. pacman and dkong.

**Comment by ICEknigh7** [comment]
I can't reproduce any unwanted cropping anymore, either. Great work!
