### ISSUE TITLE
Android versionCode is stuck at 1

### ISSUE THREAD

**Issue by mvdan** [mamedev/mame#839]
Any time you're bumping the versionName, you should be bumping versionCode too. It would be best to keep the two similar, like `0.173` and `173`.

Also, it seems like you forgot to bump it for the last tag.

**Comment by mvdan** [comment]
Just to clarify, someone is trying to add this app to F-Droid and I just noticed this. Not sure if the app is ready to be released at all.

**Comment by RQWorldblender** [comment]
This effort is to get upstream MAME ready for Android users. I have not seen any builds for Android so far, so this is the first opportunity to have it done.

**Comment by mmicko** [comment]
Thanks for report, fixed in e87b25b32b4a35358610a60f8ea27efb742457ac
