### ISSUE TITLE
Percussion Freaks (GQ881 VER. EAB) Must Find With Luck

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [mamedev/mame#8399]
This Dump Is Required Before Running Game (DrumMania (GQ881 VER. JAD)), But It's Very Hard To Find! How To Supposed to play?

**Comment by happppp** [comment]
ok good luck

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
NO GOOD DUNP KNOWN (pcnfrk 881xxb02)

**Comment by happppp** [comment]
Yeah we know, and the game is also marked not working.
