### ISSUE TITLE
Can't install via homebrew

### ISSUE THREAD

**Issue by nipponese** [mamedev/mame#8408]
Not sure if this is the place to file this issue, I tried to reach the cask maintainer @miccal directly, but couldn't find way to contact.
I'm on an m1 macbook pro running macOS 11.5.1

```
➜  ~ brew install mame
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
docuum
==> Updated Formulae
Updated 78 formulae.
==> New Casks
jiohome
==> Updated Casks
Updated 17 casks.

Warning: Treating mame as a formula. For the cask, use homebrew/cask/mame
==> Downloading https://ghcr.io/v2/homebrew/core/mame/manifests/0.234
Already downloaded: /Users/noahtsutsui/Library/Caches/Homebrew/downloads/2905da2b17eb055a1436b34ffb3e7132bc870add56e6ea0c476d55921eb908be--mame-0.234.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mame/blobs/sha256:02ff5a57ec332ab60269c544c7b27af5b3f63a05086e2cb32b8f7
Already downloaded: /Users/noahtsutsui/Library/Caches/Homebrew/downloads/82e1312a4843219b4e85b808edb3193c07cd12feb382652d94b4fa93db7f2a70--mame--0.234.arm64_big_sur.bottle.tar.gz
==> Pouring mame--0.234.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/mame/0.234: 2,256 files, 385.1MB
➜  ~ mame
Error opening translation file English
Unable to open effect file bgfx/effects/gui_opaque.json
Unable to open effect file bgfx/effects/gui_blend.json
Unable to open effect file bgfx/effects/gui_multiply.json
Unable to open effect file bgfx/effects/gui_add.json
Unable to open effect file bgfx/effects/screen_opaque.json
Unable to open effect file bgfx/effects/screen_blend.json
Unable to open effect file bgfx/effects/screen_multiply.json
Unable to open effect file bgfx/effects/screen_add.json
Ignoring MAME exception: BGFX: Unable to load required shaders. Please check and reinstall the bgfx folder

Fatal error: BGFX: Unable to load required shaders. Please check and reinstall the bgfx folder

[1]    31227 segmentation fault  mame
➜  ~ 
```

**Comment by 0kmg** [comment]
Yes, this is not the right place to seek help for this issue. Does brew have a forum?

That being said it looks like it installed fine (though my brew-fu is weak), but mame can't find the bgfx folder. Given the install location and that it's homebrew, it's probably in /opt/homebrew/Cellar/mame/0.234/share/mame/bgfx/. You'll need to set up your mame.ini's bgfx_path to point to the appropriate place. Alternatively use `mame -video opengl` to forgo using the newer bgfx driver until you can work out the settings on your machine.

**Comment by nipponese** [comment]
@0kmg Where should mame.ini live? I don't see a default file anywhere in the directory. I do see `/opt/homebrew/Cellar/mame/0.234/share/mame/ini` but no mame.ini in there.

**Comment by 0kmg** [comment]
Per user, I think MAME looks in ~/.mame/ on a Mac or Linux machine.

**Comment by miccal** [comment]
> Not sure if this is the place to file this issue, I tried to reach the cask maintainer @miccal directly, but couldn't find way to contact.

@nipponese you are installing `mame` as a Formula from `homebrew-core`, not as a Cask from `homebrew-cask`?

**Comment by nipponese** [comment]
@miccal Not sure how to answer this, but I am just using `brew install mame`

**Comment by miccal** [comment]
As shown in you output above:
```
Warning: Treating mame as a formula. For the cask, use homebrew/cask/mame
```

**Comment by nipponese** [comment]
@miccal got the `“MAME OS X” needs to be updated.` error. I guess this isn't an m1 build.

**Comment by nipponese** [comment]
@miccal It installed an old dmg from sourceforge. Is this right??

**Comment by nipponese** [comment]
Ok, I'm sorry, I get what's happening. @miccal only maintains the cask for the old binary. Sorry, I am new to casks.

**Comment by mschinca** [comment]
After installing mame via:
```
brew install mame
```
you need to create ```mame.ini``` file by doing:
```
mame -createconfig
```
Then edit ```mame.ini``` so that ```bgfx_path``` points to the correct location, in my case:
```
#
# BGFX POST-PROCESSING OPTIONS
#
bgfx_path                 /usr/local/Cellar/mame/0.238/share/mame/bgfx
```
