### ISSUE TITLE
LaserWriter video output doesn't work

### ISSUE THREAD

**Issue by jrmuizel** [mamedev/mame#8411]
I've started looking at this. As part of this the via6522 uses Timer 2 configured in pulse counting mode. @Lord-Nightmare are you able to figure out what PB6 on the via6522 is connected to on the LaserWriter II NT?

**Comment by jrmuizel** [comment]
It looks like it's hooked up to a divided version of the board clock. @rb6502, what's the best way to represent this in MAME?

**Comment by jrmuizel** [comment]
I managed to get video output sort of working.
<img width="1640" alt="lwriter-video-out" src="https://user-images.githubusercontent.com/332653/130340596-5c7bf85c-50df-441f-974f-f4c8389977bb.png">

**Comment by rb6502** [comment]
Nice work!  Kinda funny to get first working prints from the ImageWriter and LaserWriter on the same day.

I apparently missed your earlier question somehow, but PB6 is taking a divided clock as an input?  If the clock isn't super fast just run a MAME emu_timer that feeds it.

**Comment by jrmuizel** [comment]
I believe the clock is running at about 116488Hz.

Where's the ImageWriter work happening?

**Comment by rb6502** [comment]
116488 Hz is no problem, you don't seriously degrade emulation performance with a timer until you get into the MHz range.  I'm actually running an Apple II card with a 3.58 MHz timer right now and it's fine on my MacBook, which isn't a speed demon.

ImageWriter work is going on by "Golden Child" at the Bannister message boards, start at this post: https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=119557#Post119557

**Comment by jrmuizel** [comment]
Fixed by #9049
