### ISSUE TITLE
error: ‘layout_ex800’ was not declared in this scope

### ISSUE THREAD

**Issue by telanus** [mamedev/mame#8484]
Got this while compiling:
Compiling src/devices/bus/centronics/epson_ex800.cpp...
../../../../../src/devices/bus/centronics/epson_ex800.cpp: In member function ‘virtual void epson_ex800_device::device_add_mconfig(machine_config&)’:
../../../../../src/devices/bus/centronics/epson_ex800.cpp:230:28: error: ‘layout_ex800’ was not declared in this scope
  230 |  config.set_default_layout(layout_ex800);
[6:51 AM]
any ideas why?
[6:51 AM]
I'm on Kubuntu 20.04

**Comment by cuavas** [comment]
Possibly because you killed an earlier build in a weird way?  I don’t know.  At any rate, it’s generated from the corresponding XML layout file, and dependencies are specified correctly.  This is a local issue with your build.  It’s not appropriate to open an issue for it.
