### ISSUE TITLE
Compile with vs2019 gives a C2248 error [ioprocsfilter.cpp]

### ISSUE THREAD

**Issue by nabetse00** [mamedev/mame#8501]
`zlib_data` class constructor is declared protected:
https://github.com/mamedev/mame/blob/7ff2dbfb430e4f8eb84013f235a967b3b3ceeab7/src/lib/util/ioprocsfilter.cpp#L33-L40

Then `zlib_data` is inherited with private access inside `inflate_data`  and used as protected.
https://github.com/mamedev/mame/blob/7ff2dbfb430e4f8eb84013f235a967b3b3ceeab7/src/lib/util/ioprocsfilter.cpp#L105-L112

vs2019 then gives this error on compilation:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2248	'util::`anonymous-namespace'::zlib_data::zlib_data': cannot access inaccessible member declared in class 'util::`anonymous-namespace'::zlib_data'
	{
^	utils	C:\XXX\YYY\mame\src\lib\util\ioprocsfilter.cpp	378	

```

Changing Inheritance to protected solves the issue:
``` c++
class inflate_data : protected zlib_data
```

I think it's a vs2019 bug when a protected constructor ->derived as private -> used as protected.

**Comment by cuavas** [comment]
MSVC is not implementing `using` for constructors properly in this case.  See here for a minimal test case that reproduces the issue: https://github.com/mamedev/mame/pull/8499#issuecomment-907608005

Someone needs to report this to Microsoft.  It isn’t particularly fancy C++ and it’s functionality that hasn’t changed since C++11.

**Comment by yz70s** [comment]
This is the error report
https://developercommunity.visualstudio.com/t/in-vs2019-16112-wrong-c-error-c2248-with-stdc17-or/1516394

**Comment by nabetse00** [comment]
@yz70s [error report](https://developercommunity.visualstudio.com/t/in-vs2019-16112-wrong-c-error-c2248-with-stdc17-or/1516394) as been closed as duplicate of [this report](https://developercommunity.visualstudio.com/t/MSVC-compiler-improperly-implements-N489/1516410).

MS people marked it as `Under Investigation` (30/08/2021).
So good news: they are looking at it. Nevertheless we don't how much time will they take to make a patch or even if they will make a patch...

@cuavas can you confirm that changing inheritance to protected is a convenient workaround until MS team corrects this bug?
By "convenient workaround" i mean to be able to compile with vs2019 localy,  not to add it to mame source code.

**Comment by cuavas** [comment]
This is worked around for now.  However, I’d still strongly recommend using Visual Studio with the clang toolchain if you want to use the Visual Studio debugger.  It’s far better than MSVC for code generation and performance.
