### ISSUE TITLE
Killer Instinct 2 (Upgrade kit) Release Year Is Incorrect?

### ISSUE THREAD

**Issue by gspat1** [mamedev/mame#8546]
Hi!

According to Wikipedia, KLOV Etc. The release year is actually 1996 rather than 1995.

Sources: https://en.wikipedia.org/wiki/Killer_Instinct_2, https://www.arcade-museum.com/game_detail.php?game_id=8309

Of course, the game itself says 1994 - 1995 even though the first one came out in 1994? So, I'm not quite sure which is correct?

Regards!

**Comment by happppp** [comment]
Sure, changed kinst2 too
