### ISSUE TITLE
NEC PC-8801 clock

### ISSUE THREAD

**Issue by ValleyBell** [mamedev/mame#8560]
For NEC PC-8801 machines, the master clock is currently defined to exactly 4.0 MHz.

However, according to this blog, is should be 3993600 Hz: http://www7b.biglobe.ne.jp/~crazyunit/pc88.html#clock

I have looked at a few PC-8801 emulators and their clock values:
- M88 emulator: 3993600 Hz
- XM8 emulator: 3993624 Hz

I don't have a definitive source for the actual PC-8801 clock, but exact 4 MHz seems to be a bit off compared to what is documented, so it may be a good idea to fix it to one of the values above.

**Comment by happppp** [comment]
It's from a software measurement, a Z80 program to count number of clocks per frame, run it for a few hours and take the average.
If it is bug-free and accurate, it just means the XTAL in this person's computer is off by less than 1%, which is not abnormal.

**Comment by ValleyBell** [comment]
I just noticed that MAME even has the base XTAL defined already, which is 31.9488 MHz:
https://github.com/mamedev/mame/blob/668f3fd816e78dbab8affae8c645424288c55ee2/src/emu/xtal.cpp#L387

This page has a screenshot of a PC-8801 mainboard with a list of all components, including oscillators with frequencies:
http://www7b.biglobe.ne.jp/~crazyunit/pc88mbpic.html

---

Maybe we should just use `XTAL(31'948'800) / 8` here:
https://github.com/mamedev/mame/blob/668f3fd816e78dbab8affae8c645424288c55ee2/src/mame/drivers/pc8801.cpp#L272

Similarly, we could use `XTAL(31'948'800) / 16` and `XTAL(31'948'800) / 13` in PC-9801 systems:
https://github.com/mamedev/mame/blob/668f3fd816e78dbab8affae8c645424288c55ee2/src/mame/drivers/pc9801.cpp#L1465-L1466

**Comment by angelosa** [comment]
Never saw an actual hires PCB of PC-8801 and that link is no exception. Not sure where that `xtal.cpp` value comes from and most likely not used by anything. 
Also fwiw: 
1. Later models also have CPU ~8 MHz clock switch so there's need of a /4 divider too.
2. System has sensible waitstate penalties, if the clock is really ~32 MHz that turns the table a bit.

**Comment by wd40yasu** [comment]
https://kasutamu2.up.seesaa.net/image/E4BAA4E68F9BE5898DE38080E3839EE382B6E383BC.JPG
motherboard for PC-8801FH
OSC1 28.63636MHz
OSC2 42.1052MHz
OSC3 31.9488MHz (near main CPU),
also used by PC-9801 series that uses 8MHz/16MHz CPU clock (RS, FA, etc.)

-- 
Yasuhiro Ogawa ***@***.***>

**Comment by wd40yasu** [comment]
https://kyouichisato.blogspot.com/2014/11/pc-8801fh.html
https://2.bp.blogspot.com/-4EAf40EZJGY/VF-kM819MEI/AAAAAAAALLk/HO4eG0M-yP0/s1600/aDSCN4762.JPG
more easy to read the OSC3 value

https://kyouichisato.blogspot.com/2014/11/pc-8801fe.html
31.9488MHz is OSC1 for PC-8801FE

-- 
Yasuhiro Ogawa ***@***.***>

**Comment by wd40yasu** [comment]
https://kyouichisato.blogspot.com/2014/11/pc-8801fh.html
https://2.bp.blogspot.com/-4EAf40EZJGY/VF-kM819MEI/AAAAAAAALLk/HO4eG0M-yP0/s1600/aDSCN4762.JPG
OSC3 (near main CPU) is 31.9488MHz

https://kyouichisato.blogspot.com/2014/11/pc-8801fe.html
31.9488MHz is changed to OSC1 for PC-8801FE

-- 
Yasuhiro Ogawa ***@***.***>

**Comment by angelosa** [comment]
Thanks, this is definitely helpful.

PS: I'm gonna guess the μPD70008AC-8 is the main Z80 CPU while μPD780C on top right is the (internalized) PC80S31K floppy CPU, correct? Wasn't sure about latter, I guess this proves it.

**Comment by wd40yasu** [comment]
> PS: I'm gonna guess the μPD70008AC-8 is the main Z80 CPU while μPD780C on top right is the (internalized) PC80S31K floppy CPU, correct? Wasn't sure about latter, I guess this proves it.
That's correct. 4MHz only machines (before FH) have 2 μPD780C.
Second μPD780C is not dedicated to floppy, it can be used as sub CPU
(sylpheed uses it for decompressing data).

-- 
Yasuhiro Ogawa ***@***.***>
