### ISSUE TITLE
plib/ppmf.h suffers multiple issues

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#8590]
The pointer to member function code in src/lib/netlist/plib/ppmf.h suffers from issues I fixed for src/lib/util/delegate.h in #8589.  This further reinforces my opinion that it’s a bad idea to have so many things reimplemented in the netlist library.  It means more opportunities for bugs, and dual maintenance.

At a glance, I can see the following issues are present:
* Treating `this` pointer displacement as `int` rather than the correct `ptrdiff_t` for Itanium C++ ABI.
* Not right-shifting the `this` pointer displacement for ARM-like Itanium C++ ABI.
* Not applying the `this` pointer displacement for virtual member functions for ARM-like Itanium C++ ABI.
* Incorrectly applying the `this` pointer delta to the vptr for ARM-like Itanium C++ ABI.
* Not considering platforms where function pointers point to function descriptors.

**Comment by cuavas** [comment]
The major issues are addressed by #9752 – it should work for both variants of the Itanium ABI, and for most important cases with the MSVC ABI.  There’s still no provision for targets that store function descriptors in the virtual function table.

**Comment by couriersud** [comment]
> There’s still no provision for targets that store function descriptors in the virtual function table.

If I read `abi.h` (lines 85 to 96) correctly that is currently only the case for IA64 architecture?

**Comment by cuavas** [comment]
I’m still not fond of dual maintenance but PPMF should at least work properly now.

**Comment by cuavas** [comment]
> > There’s still no provision for targets that store function descriptors in the virtual function table.
> 
> If I read `abi.h` (lines 85 to 96) correctly that is currently only the case for IA64 architecture?

Yes, of the architectures abi.h covers, only IA64 stores function descriptors in vtables.
