### ISSUE TITLE
[Question] How about Android build ?

### ISSUE THREAD

**Issue by zminhquanz** [mamedev/mame#860]
When Mame release android build official ?

**Comment by NULUSIOS** [comment]
Question is, could you compile it? Because I couldn't...
If it cannot yet be compiled, it probably isn't ready for it.

**Comment by rb6502** [comment]
FWIW, the guidance is to type 'make android-arm', which will generate an Android Studio project you can open.  This is likely to only work on Linux, and possibly the Mac right now.

**Comment by NULUSIOS** [comment]
This is also discussed here:
http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=105425&page=all
(for reference and completeness)

**Comment by rb6502** [comment]
Complete instructions for building the Android version on a windows machine have been posted through the link NULUSIOS posted.
