### ISSUE TITLE
No way to build tools only?

### ISSUE THREAD

**Issue by x0r13** [mamedev/mame#8606]
Hey,

I'd like to build the tools only, and not the whole solution. It looks like this was possible a while back with 'make tools', but I can't find a way in current releases. Would it be possible to add such an option?

**Comment by DavidHaywood** [comment]
https://github.com/mamedev/mame/pull/8329  there's an entire PR to change the build system over, so right now would probably not be the best time to be adding features to the current one  (assuming that PR isn't dead in the water)

**Comment by galibert** [comment]
I really hope the PR is not dead in the water.  I plan to kick it in the tires after release.

**Comment by Firehawke** [comment]
I don't think it's dead, but I think that workload has caused the central people in that PR to not have time to progress discussion and get it moved forward towards a final merge.

That said, I do agree that a tools-only build is something that should probably be in the new build environment so I'll subscribe to this issue to keep track of it.

**Comment by Robbbert** [comment]
Didn't cuavas fix this?

**Comment by cuavas** [comment]
> Didn't cuavas fix this?

Well, @mmicko actually, not me, but you can now use `TOOLS=1 EMULATOR=0` to achieve this.
