### ISSUE TITLE
pleasuredome reported to police

### ISSUE THREAD

**Issue by jessicajones123** [mamedev/mame#8627]
Hi

Please say all a BIG THANK YOU to Antonio Paradossi (AntoPISA) of www.progettosnaps.net

Because he banned me on the mameworld forum many times after I made a tool for FREE for him to scan his collections for missing media, I decided to get a little revenge...

Some months ago I reported pleasuredome bittorrent tracker www.pleasuredome.org.uk to the cybercrime unit of the UK police.
Finally after some months it was forced to go offline.

All hate messages go directly to AntoPISA, because he is responsible for my revenge.
You know where to find this filthy spaghetti eater!!!

Legendary Jessica Jones...

**Comment by cuavas** [comment]
>You know where to find this filthy spaghetti eater!!!

Besides the rest of the unhinged rant, racism is instantly bannable.
