### ISSUE TITLE
Debugger “trackmem” command not working

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#8638]
As far as I can tell, the `trackmem` command doesn’t work.  I don’t think this is a new issue – I couldn’t get it to work on 28 January 2021, but I put it down to possibly not understanding what I was supposed to do.  However, after trying to exercise it again, it just doesn’t seem to work at all.

If I understand correctly, after turning it on with `trackmem 1` it should record memory writes, and allow retrieval of the PC value when the last write occurred for a given address.  It should be possible to see this information using the `pcatmem` family commands, or by right-clicking on the data in a memory view in the Win32 or Qt debugger.

However if I turn on `trackmem` and step over some writes so I can see the values being changed in the memory view, both the `pcatmem` command and the memory view context menu tell me that it’s unknown.

Did this command get broken when taps became a thing, or is this a separate issue?  Can the functionality be restored using taps?

**Comment by ajrhacker** [comment]
I'm working on a fix for this.

**Comment by ajrhacker** [comment]
30d6d250531e14ce947c6911cb01606703c0783d and 18d89a1d04a4667b6b8e4ff6796364830393118a seem to have fixed all major issues here.
