### ISSUE TITLE
Strange messages from Bgfx since 0.235 on my Mac...

### ISSUE THREAD

**Issue by noxx09** [mamedev/mame#8642]
On 0.236 and since 0.235 I have this message that slow down a lot my computer...
Warning: Attempting to retrieve a nonexistent target 'screen' for screen 0
Warning: Attempting to retrieve a nonexistent target 'screen' for screen 0
Warning: Attempting to retrieve a nonexistent target 'screen' for screen 0
Warning: Attempting to retrieve a nonexistent target 'screen' for screen 0
Warning: Attempting to retrieve a nonexistent target 'temp' for screen 0
Warning: Attempting to retrieve a nonexistent target 'temp' for screen 0
Warning: Attempting to retrieve a nonexistent target 'temp' for screen 0
Warning: Attempting to retrieve a nonexistent target 'temp' for screen 0
Warning: Attempting to retrieve a nonexistent target 'output' for screen 0
Warning: Attempting to retrieve a nonexistent target 'output' for screen 0
Warning: Attempting to retrieve a nonexistent target 'output' for screen 0
Warning: Attempting to retrieve a nonexistent target 'output' for screen 0
Warning: Attempting to retrieve a nonexistent target 'output' for screen 0
And so on...
 I can't play 1942 on iMac core i9...
 I'm on Big Sur 11.6.
I've try every options on bgfx or OSD video, but nothing change. I need to reinstall both mame 0.234 and bgfx 0.234 for retrieve a normal speed.
I search this message on Google, but nothing...
An idea ?
Thanks.

**Comment by gspat1** [comment]
Not a dev, or a Mac user, but I've seen something similar where I had weird BGFX issues on a windows machine.

Did you overwrite the entire folder for 236 or just drop the executable file in the old folder? 

My case was that some support files changed over time and didn't match the old ones still in the original folder.

Hope this helps?

**Comment by rb6502** [comment]
That sounds right, those errors would certainly occur if you updated the executable without also updating at least the bgfx folder.

**Comment by noxx09** [comment]
I always overwrite all files that comes with a new install. The last who works well was the 0.234. I had already compile myself the source 0.235, but the bug is always here... And this don't seems touch other Mac users... I'm perplexed.

**Comment by rb6502** [comment]
I'm typing this on my Core i9 MacBook Pro that I use to develop MAME, and I don't get any of that.  Check your mame.ini and see if the bgfx_path is reasonable.

**Comment by belegdol** [comment]
It might be that you need to refresh your mame.ini:
1. Copy existing mame.ini
2. Run mame -cc in the folder where the ini is stored
3. Optionally inspect the differences

**Comment by noxx09** [comment]
I do that, without change anything at the install, but the bug persist. I have verified the bgfx path. To read that error message you need to activate the verbose command at the core debugging options in mame.ini.
I saw that the bug is emphasized by the usage of a glsl shader, but with or without it, the bug still occur... on my computer.

**Comment by rb6502** [comment]
You should've said that at first.  -verbose does reproduce the issue, but it's unclear if it's actually a bug.  Meanwhile, don't run -verbose.

**Comment by noxx09** [comment]
With or without -verbose, a game like 1942 don't run at 100%, but -verbose seems to show the problem.
Today I find something. 
If I put video on opengl, the game run at 100% and without "nonexistent target" (Sorry, I start by that but I missed it because Mame used another mame.ini in another place that I had forgotten... :-/)... But the resolution is not good and I see a very partial image : perhaps a problem with retina display. And change resolution on Big Sur don't resolve the problem (I'm not sure that Finder change really the resolution, perhaps scalling elements (?), switchres & resolution do nothing visible.
if I put video on auto, don't use a glsl filter, don't verbose and put bgfx_backend on opengl... The speed is near correct, 99% and without a warning message... 
Perhaps it's not a bug but it's not good as before on my computer ;-)

**Comment by noxx09** [comment]
Today I try the same Mame with video on opengl, bgfx on auto, but after booting the same machine on Mojave. And all run ok. Without warning, at the good speed, with all image.

**Comment by MooglyGuy** [comment]
This should be closed.

Running with -verbose reports those warnings - which is all they are, warnings, not errors, it even says in the text, "Warning:" - because during the initial UI screens there isn't any screen from which to construct the 'target' or 'temp' targets.

Beyond that, if poor performance is being encountered on BGFX and not OpenGL, then that is down to user hardware, not a valid MAME issue.

**Comment by happppp** [comment]
Those warnings should be gone after https://github.com/mamedev/mame/commit/d2aa062d94a15a990e4392999bd3580592b4b9cf
