### ISSUE TITLE
apple2gsr1 Fatal System Error 0911

### ISSUE THREAD

**Issue by ksherlock** [mamedev/mame#8657]
https://github.com/mamedev/mame/blob/fbb2381f9e19e0f07906be0a883bb8e445208e6c/src/mame/drivers/apple2gs.cpp#L2487-L2491

I noticed on ROM 1 the above code can cause the command-control-escape control panel to generate a fatal system error 0901, which indicates a communication problem with the ADB.  

To recreate:  repeatedly enter and exit the control panel while one second interrupts are active.  Since it's very timing dependent, you could use the debugger to set a breakpoint at $FF85E0, command-control-escape to invoke it, set m_vgcint to 0xc4 (VGCINT_SECONDENABLE|VGCINT_SECOND|VGCINT_ANYVGCINT), and continue.  Note that interrupts are disabled at this point (because it's handling the desktop interrupt). ROM3 has different code and I'm not sure if it's susceptible.  

The code in question:
```
; send read available layouts ADB command
 FF:85E0  lda #$0f                                            A9 0F
 FF:85E2  jsr $83a2                                           20 A2 83
 FF:85E5  bcs ff8659 ($72)                                    B0 72

; read the response
 FF:85E7  ldy #$0000                                          A0 00 00
 FF:85EA  jsr $8442                                           20 42 84
 FF:85ED  bcs ff8659 ($6a)                                    B0 6A
 FF:85EF  sta $0301,y                                         99 01 03
 FF:85F2  iny                                                 C8
 FF:85F3  tya                                                 98
 FF:85F4  cmp $0301                                           CD 01 03


; wait 30 microseconds for a response
; 0x20 indicates data register full. 

 FF:8442  clc                                                 18
 FF:8443  ldx #$1d4c                                          A2 4C 1D
 FF:8446  dex                                                 CA
 FF:8447  beq ff8454 ($b)                                     F0 0B
 FF:8449  lda KMSTATUS                                        AD 27 C0
 FF:844C  and #$20                                            29 20
 FF:844E  beq ff8446 (-$a)                                    F0 F6
 FF:8450  lda DATAREG                                         AD 26 C0
 FF:8453  rts                                                 60

; timed out
 FF:8454  sec                                                 38
 FF:8455  rts                                                 60
```

if there is a pending one-second interrupt, the nucleus hack will cause KMSTATUS to be 0 which looks like no data is available, leading to the ADB system error 0911 and system death.

**Comment by rb6502** [comment]
This comes from an issue in the ADB HLE state machine (it always reports data available, which causes the ROM interrupt manager to never see one-second interrupts) which I was hoping to have eliminated by now.  Unfortunately progress on just running the actual M740 microcontroller code and having it speak bit-serial ADB to things has been slower than anticipated.
