### ISSUE TITLE
Strider starfield

### ISSUE THREAD

**Issue by Firehawke** [mamedev/mame#8659]
Per [Twitter](https://twitter.com/WydD/status/1443967258808786978), seems like there's been some improvements in CPS-1 via schematic study. This led to the following links for [CPS-A](https://gitlab.com/loic.petit/cps2-reverse/-/blob/master/DLs/DL-0311/doc/stars.md) and [CPS-B](https://gitlab.com/loic.petit/cps2-reverse/-/blob/master/DLs/DL-0921/doc/star-raster.md) which may help to perfect the small yet important bits for long-term preservation.

**Comment by jotego** [comment]
I think it is basically the two palette patterns that are missing in MAME. It's actually quite impressive how well the starfield was done before the full information was known. The way the original works is that some stars cycle through the full palette, whereas others skip the blank colour.

**Comment by dinkc64** [comment]
This problem doesn't affect MAME.

**Comment by happppp** [comment]
should be resolved
