### ISSUE TITLE
bfgx issues

### ISSUE THREAD

**Issue by HyperScorpio** [mamedev/mame#8696]
Hello. I just decided to test BGFX on MAME 0.236 today and i found a bad surprise inside of it.

When i was able to change to hq2x - hq3x - hq4x, it appears some bad pixelation on it.
lut - black screen
pillarbox left and right with horizontal and vertical - invisible with fog
xbr-lv2-accuracy-multipass / smart-blur - black screen
xbr-lv3-multipass - black screen
xbr-mlv4-dilation / multipass - black screen

This as been reported before and they are working on it?
Last version working: v0.233

![1](https://user-images.githubusercontent.com/30736913/137156865-1999e8a2-6365-4a75-89c8-b9560ca150c2.png)

Thank you. 

--//--

Also MAMEUI / ARCADE/ WOLFMAME / GROOVYMAME have the same problem. I believe they are all going to move at the same way.

**Comment by cuavas** [comment]
Besides the fact that the “issues” with the pillarbox shaders are intended behaviour, we already have enough open issues tracking bgfx behaviour.
