### ISSUE TITLE
Adjust CPU frequency arbitrarily

### ISSUE THREAD

**Issue by denjhang** [mamedev/mame#8711]
When I was running certain PC88 programs, I found that the CPU frequency must be changed to tens or even hundreds of MHz to get the correct music playback speed.
This function is implemented in the M88 simulator.

**Comment by denjhang** [comment]
![截图未命名1016180431](https://user-images.githubusercontent.com/61811583/137583419-6e4a9786-ef5f-4c10-9ba1-afcda97051dc.png)

**Comment by denjhang** [comment]
Here is an example program, in d88 format, I use the following console command to start it.
mame pc8801fa -flop1 k1.d88
When the disk is loaded correctly, it will enter a nsf music player interface.
[k1.zip](https://github.com/mamedev/mame/files/7357356/k1.zip)

**Comment by happppp** [comment]
Overclocking is already supported, not hundreds of MHz, but up to 4x.
Run MAME with -cheat enabled, and go to the sliders menu.

Does k1.zip contain copyrighted material? If so, please remove it from here.
