### ISSUE TITLE
Fast Lane score colours

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#8721]
The score colours are wrong. I can explain how it works in the original hardware but it's hard for me to point what's wrong with the way the MAME driver is coded. I see there is a routine that generates the palette, but I don't understand MAME enough to fix it.

Anyway, there is a PROM that contains some kind of colour conversion and it has to be applied **to the tile output** of the K007121, not the sprite output. 

This color arrangement is wrong:
![0014](https://user-images.githubusercontent.com/1863036/137778578-9b10a586-460a-4892-8e1b-a0bdd1d19d50.png)

It should look like this
![20211017_161454-screen](https://user-images.githubusercontent.com/1863036/137779087-9e289fe5-acf1-4c27-9099-c3a8a2e41379.png)
See it in action:
https://youtu.be/BQzDBRPF70M

I guess it is enough with the information above, but you can also track the signals in my FPGA version to see how they are connected, in case it helps.

https://github.com/jotego/jtcontra/blob/73711e137efcbd807641956fee868cf422ebb28c/cores/labrun/hdl/jtlabrun_video.v#L97

**Comment by happppp** [comment]
Yes it looks like in the video
