### ISSUE TITLE
No mouse in OSX El Capitan with SDL 2.0 and mame 0.173

### ISSUE THREAD

**Issue by symgryph** [mamedev/mame#873]
I tried in vain to get the mouse input to work. Turned on in the ini file etc. Still no mouse. Anyone gotten it to work?  I am running SDL 2.0.4 and currentest production mame (64 bit) on a mac mini.

**Comment by rb6502** [comment]
We know about this, and I was hoping Couriersud might have a look, but I think he's busy so I'll check it out.

**Comment by rb6502** [comment]
...well, I thought we did, but it's actually working fine for me on the latest El Cap.  Make sure your mame.ini has "mouse 1" and "mouse_device mouse".

**Comment by rb6502** [comment]
Hi, can you verify if this is still happening for you?  As I said, I have the mouse working fine on my Mac with El Cap and SDL 2.0.4.

**Comment by symgryph** [comment]
Will check today

Thomas J Munn

**Comment by CRP** [comment]
On my mac, mouse works in games but not initially in the UI. For the mouse to work there, I need to start then exit a game.

**Comment by bradhugh** [comment]
I looked at this today and may have a fix. I'll work on getting it in sometime tonight.

**Comment by symgryph** [comment]
cool!

Thomas J Munn

**Comment by bradhugh** [comment]
Should be fixed.  I could repro on my mac, now it works for me.  Let me know if it works for you.

**Comment by symgryph** [comment]
do you have link for fixed binary?

Thomas J Munn

**Comment by bradhugh** [comment]
I figured you'd build it, but I posted a 64-bit version for Mac here just in case https://1drv.ms/u/s!AohIe_qtFjndo7MjT3-tQQn3tEsVBQ

**Comment by bradhugh** [comment]
Any luck?

**Comment by symgryph** [comment]
Tyring now

**Comment by symgryph** [comment]
Stupid me i lost the DL link…

**Comment by bradhugh** [comment]
https://onedrive.live.com/redir?resid=DD3916ADFA7B4888!580003&authkey=!AE9_rUEJ97RLFQU

**Comment by bradhugh** [comment]
https://1drv.ms/u/s!AohIe_qtFjndo7MjT3-tQQn3tEsVBQ

**Comment by symgryph** [comment]
Mouse works

**Comment by bradhugh** [comment]
Awesome fixed by commit eb97703a4cadfca16c61553f382b5b44c173d6cd
