### ISSUE TITLE
A translation is missing from the interface

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#8731]
mame: `0.236 (mame0236-215-gb1c76441593)`
OS: `Debian 11` & `Windows 10`

Even thou there are translations for "General Info" in different languages, for some reason it doesn't translate.
Tested with the more recent translation for Chinese Traditional/Simplified, in Chinese it should be "一般資訊".
![missing_translation](https://user-images.githubusercontent.com/80734530/138151622-71b128dc-fc10-46dc-a528-7a074de57b5f.png)

**Comment by cuavas** [comment]
Have you rebuilt the .mo files?

**Comment by cd4053** [comment]
Thanks. ❤️
