### ISSUE TITLE
Incorrect Mapping for F-Zero AX Monster Ride on Triforce board

### ISSUE THREAD

**Issue by Zopolis4** [mamedev/mame#8754]
(While I am aware that triforce.cpp is only a skeleton driver, I feel that nonetheless it should at least load the roms correctly.) The fzeroaxm machine in triforce.cpp either is loading the wrong parts of the rom, or is a bad dump, as a decrypted memory dump of the areas containing the loaded rom yields an broken gamecube ISO (with an invalid fst), which it is not supposed to do. (I wasn't sure exactly where to report this, so I've reported it here)

**Comment by AnthonyRyuki** [comment]
The issue is caused by some dummy data in the ROMs, which are now skipped by the latest version of this app: https://github.com/AnthonyRyuki/triforce-nand-iso-extract
