### ISSUE TITLE
Windows 11 crash

### ISSUE THREAD

**Issue by happycodebeast** [mamedev/mame#8776]
Hi

MAME doesn't seem to work on windows 11. I have latest NVIDIA drivers.
It crashes without any error message.

Is windows 11 supported?

**Comment by cuavas** [comment]
Have you installed the DirectX 9 runtime?  Have you tried setting `video bgfx` in mame.ini?

**Comment by kokutoukiritsugu** [comment]
test on my windows 11 22000.282, mame works fine.
try clean install your windows 11.

**Comment by happppp** [comment]
If 0.236 works but 0.237 does not, try this build: https://github.com/mamedev/mame/actions/runs/1385642925
If it is that issue, changing video to bgfx as cuavas said will also work.

**Comment by rb6502** [comment]
They don't need an alternate build, just a different -video setting.

**Comment by happycodebeast** [comment]
@Cuavas: I don't find an official DirectX9 runtime for windows 11. Windows 11 is not between the supported OSes.
Can you give me a link?

@rb6502: is BGFX the only working video output supported on windows 11? Should opengl work too?

thx

**Comment by k2-git** [comment]
I used this.
https://www.microsoft.com/en-us/download/details.aspx?id=8109
This is for win7, but it runs fine.

**Comment by DavidHaywood** [comment]
both BGFX and D3D work fine on Win11, nothing has changed from Win10 essentially as far as MAME is concerned.

you need D3D for some things, like Golly Ghost if you want the artwork to work correctly and still show the game display, also BGFX still reportedly has one frame more latency than D3D (although I can't notice myself, but plenty of people I talk to still refuse to use the BGFX mode because it makes a big difference to them)

**Comment by happycodebeast** [comment]
Sorry David Gaywood with your rainbow color hair, but MAME crashes all the time in win 11.
Only BGFX work.

**Comment by DavidHaywood** [comment]
> 
> 
> Sorry David Gaywood with your rainbow color hair, but MAME crashes all the time in win 11. Only BGFX work.
> 
> Maybe I need to paint my hair red too to make it work?

Yes, I can confirm that works.

**Comment by happycodebeast** [comment]
> 
> 
> > Sorry David Gaywood with your rainbow color hair, but MAME crashes all the time in win 11. Only BGFX work.
> > Maybe I need to paint my hair red too to make it work?
> 
> Yes, I can confirm that works.

And now some real help please?

**Comment by rb6502** [comment]
Jessica Jones, I assume?  Tell me why I shouldn't block you again.

**Comment by happycodebeast** [comment]
> 
> 
> Jessica Jones, I assume? Tell me why I shouldn't block you again.

Suck my fucking clit. Is that enough to block me?
