### ISSUE TITLE
Timer plugin - Cycling back to first line after 1s

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#8798]
Version: `0.237 (mame0237-129-g2b5b1a4b918)`
OS: Debian 5.14.9-2
Command: ./mame -norc -sound none -window -plugins -plugin timer sf2
Plugin folder: **updated**

**How to reproduce**: Run mame with the above command and start the "timer" plugin, set reference to anything you want, use the keyboard directional keys or the joystick to move the cursor to "**Return to previous menu**", after 1s, the cursor returns back to "Reference" over and over again.

**Comment by cuavas** [comment]
Worked around: 7cc983601728fa852386f04cb7d85d93421d3dbb

(I’m not going to say “fixed” as the base menu behaviour is still far less than ideal, but the menu highlight won’t jump by itself on the timer menu any more.)

**Comment by cd4053** [comment]
Thanks!
