### ISSUE TITLE
ATI Rage video card emulation for PC Platform dos and windows and macintosh

### ISSUE THREAD

**Issue by WhiteMagicRaven** [mamedev/mame#8804]
The ATI Rage video card emulation is already on go
https://github.com/dingusdev/dingusppc/blob/master/devices/video/atirage.cpp

i don't know what stage it is.
It from Mac emulation
The value of Rage video card is Proprietary Graphic API 3DCIF and RAVE on Mac. Some games uses 3DCIF to enhance visuals.

**Comment by DavidHaywood** [comment]
the code there is GPL3, entirely unsuitable for MAME

**Comment by Robbbert** [comment]
Yes, David is correct. GPL3 is not compatible with MAME.
