### ISSUE TITLE
CHD count in mame

### ISSUE THREAD

**Issue by kirbypinkgamer** [mamedev/mame#8810]
Hi

When you generate a -listxml xml file and parse the file to find all games having one or more chd files, by checking if one or more "disk" xml tag are found inside the "machine" tag, you find 1065 games for mame 0.237.

However if you select chd in mame's UI, there are 1074 games listed that use chd files.

Is this a bug? I'm sure I counted them correctly by using some code and xml parser.

**Comment by Robbbert** [comment]
The 9 extra sets (bioses) have an empty DISK_REGION - a holder for a CHD, but none specified. The -listxml is therefore correct.

**Comment by kirbypinkgamer** [comment]
Hi

Why does mame's ui count those 9 sets as 'chd required' when no chd is specified?
That's a contradiction and therefore a bug in mame's ui.
Just see for yourself, 1074 games require chd files according to mame's ui but it are only 1065 (specified by listxml)

Greetz

**Comment by cuavas** [comment]
MAME’s internal UI doesn’t have an indexed database as it needs to reflect code changes on rebuild.  This means it has to make some trade-offs to maintain adequate performance.  This isn’t a severe enough issue to warrant more expensive code in the filters.

**Comment by kirbypinkgamer** [comment]
Then I suggest you DON'T create empty DISK_REGIONS and the problem is solved for the 9 games that, in reality, don't use chds.
Who put those there anyway and what shit do you sniff when those EMPTY things are created?!? If no chd is used, don't create this shit and definetely not an empty one...

So please don't move the problem to the UI that will become slower when the REAL cause of the problem should be destroyed (see above in case you don't understand me as always...). 

Jezus Christ

**Comment by kirbypinkgamer** [comment]
> The 9 extra sets (bioses) have an empty DISK_REGION - a holder for a CHD, but none specified. The -listxml is therefore correct.

REMOVE THOSE 9 EMPTY SHIT THINGS AND THE PROBLEM IS SOLVED BECAUSE THE UI WON'T SEE THEM ANYMORE
DO I NEED TO HOLD YOUR HAND, YOU FRICKING MAMEUI RETARD...

**Comment by Robbbert** [comment]
Any chance of getting anything changed just went out the door Jessica.

**Comment by cuavas** [comment]
>Then I suggest you DON'T create empty DISK_REGIONS and the problem is solved for the 9 games that, in reality, don't use chds.
>Who put those there anyway and what shit do you sniff when those EMPTY things are created?!? If no chd is used, don't create this shit and definetely not an empty one...

It’s for fixed system configurations when you want something like an empty CD-ROM drive, e.g. starting something like Konami M2 without software.

>So please don't move the problem to the UI that will become slower when the REAL cause of the problem should be destroyed (see above in case you don't understand me as always...).

You should take the time to understand how things work before making yourself look stupid.
