### ISSUE TITLE
Mac -cdrom only loading Legacy Recovery iso

### ISSUE THREAD

**Issue by unassumingbadger** [mamedev/mame#8813]
Host machine Debian amd64 Bullseye
MAME version 0.237
dd if=/dev/zero of=myhdd.hdv bs=1000000 count=500
./mame maclc3 -ramsize 32M -hard1 'myhdd.hdv' -cdrom 'Apple Legacy Recovery Oct 1999.iso'
Install System 7.6.1

No longer loads other cdrom images.
./mame maclc3 -ramsize 32M -hard1 'myhdd.hdv' -cdrom 'any toast or other iso image.iso'

If this is intentional behaviour, close this out.

**Comment by cuavas** [comment]
This is unclear.

What do you mean by "no longer"? A previous version of MAME loaded the CD images but current versions don't? If so, what's the approximate regression revision. Or do you mean after installing System 7.6.1 the emulated machine will no longer mount certain CD images?

Does itself MAME give you an error message? Does the emulated OS report an error? What partition map and filesystem do the CD images you're having trouble with use? Do they include Apple driver partitions?

There's not enough information here.

**Comment by unassumingbadger** [comment]
Okay it looks like this is an old issue going back to 0.234. MAME gives no error messages. The emulated machine simply doesn't mount the CD-ROM image. There is no icon of the CD-ROM on System 7.6.1 desktop. You can create an ISO with whatever software you want. It mounts with the -cdrom option in 0.233 and no longer in 0.234 and up. There is one exception and that is the Apple Legacy Recovery Oct 1999.iso. This makes me think perhaps it was intentional because it's a really weird bug otherwise.

**Comment by einstein95** [comment]
MAME emulates a Sony CDU-76S, install the patched Apple CD extension from https://macintoshgarden.org/sites/macintoshgarden.org/files/apps/Apple_CD-ROM_531_patched.sit

**Comment by unassumingbadger** [comment]
> MAME emulates a Sony CDU-76S, install the patched Apple CD extension from https://macintoshgarden.org/sites/macintoshgarden.org/files/apps/Apple_CD-ROM_531_patched.sit

That did the trick. Thanks!

**Comment by rb6502** [comment]
@einstein95 Do you have more detail on what the patched extension does?  If I can change MAME to work with the stock extension, I'd definitely like to.

**Comment by einstein95** [comment]
@rb6502 from the hack's details on https://web.archive.org/web/20040404121044/http://www.resexcellence.com/hack_html_99/12-21-98.shtml, it nops out 3 instructions, that, depending on the version, are
```
0: 6606       bne     $8
2: 4a84       tst.l   D4
4: 6700 0086  beq     $8c
```
or
```
0: 6604  bne     $6
2: 4a84  tst.l   D4
4: 6706  beq     $c
```
from the screenshot on the page, it's preceded by `tst.b   D0` after doing a `jsr`

**Comment by einstein95** [comment]
@rb6502 Looking at the full driver (v5.1.1) it appears it just checks the model of the drive against a list
```
CD-ROM CDU-8005
CD-ROM CR-8005
CD-ROM CDU-8004
CD-ROM CDR-8004
CD-ROM CR-8004
CD-ROM CDU-8003
CD-ROM CDU-8002 
CD-ROM CDU-8001 
```

**Comment by rb6502** [comment]
This is fixed in top-of-tree on Github so you don't need the modified CD extension.
