### ISSUE TITLE
linux_64 build fails in debuggerview.moc.cpp

### ISSUE THREAD

**Issue by popey** [mamedev/mame#882]
Did I do something wrong?

Creating ../../../../linux_gcc/bin/x64/Release
Archiving libprecompile.a...
Compiling src/osd/modules/debugger/debugqt.cpp...
Compiling src/osd/modules/debugger/qt/debuggerview.cpp...
Compiling src/osd/modules/debugger/qt/windowqt.cpp...
Compiling src/osd/modules/debugger/qt/logwindow.cpp...
Compiling src/osd/modules/debugger/qt/dasmwindow.cpp...
Compiling src/osd/modules/debugger/qt/mainwindow.cpp...
Compiling src/osd/modules/debugger/qt/memorywindow.cpp...
Compiling src/osd/modules/debugger/qt/breakpointswindow.cpp...
Compiling src/osd/modules/debugger/qt/deviceswindow.cpp...
Compiling src/osd/modules/debugger/qt/deviceinformationwindow.cpp...
Compiling generated/osd/modules/debugger/qt/debuggerview.moc.cpp...
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:13:2: error: #error "This file was generated using the moc from 4.8.7. It"
 #error "This file was generated using the moc from 4.8.7. It"
  ^
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:14:2: error: #error "cannot be used with the include files from this version of Qt."
 #error "cannot be used with the include files from this version of Qt."
  ^
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:15:2: error: #error "(The moc has changed too much.)"
 #error "(The moc has changed too much.)"
  ^
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:62:7: error: ‘QMetaObjectExtraData’ does not name a type
 const QMetaObjectExtraData DebuggerView::staticMetaObjectExtraData = {
       ^
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:68:35: error: ‘staticMetaObjectExtraData’ was not declared in this scope
       qt_meta_data_DebuggerView, &staticMetaObjectExtraData }
                                   ^
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp: In member function ‘virtual const QMetaObject* DebuggerView::metaObject() const’:
../../../../generated/osd/modules/debugger/qt/debuggerview.moc.cpp:77:71: error: conditional expression between distinct pointer types ‘QDynamicMetaObjectData*’ and ‘const QMetaObject*’ lacks a cast
     return QObject::d_ptr->metaObject ? QObject::d_ptr->metaObject : &staticMetaObject;
                                                                       ^
qtdbg_sdl.make:407: recipe for target '../../../../linux_gcc/obj/x64/Release/qtdbg_sdl/generated/osd/modules/debugger/qt/debuggerview.moc.o' failed
make[2]: *** [../../../../linux_gcc/obj/x64/Release/qtdbg_sdl/generated/osd/modules/debugger/qt/debuggerview.moc.o] Error 1
Makefile:16: recipe for target 'qtdbg_sdl' failed
make[1]: *** [qtdbg_sdl] Error 2
makefile:1195: recipe for target 'linux_x64' failed
make: *** [linux_x64] Error 2

**Comment by rb6502** [comment]
Typically that's the result of trying to compile MAME, discovering you didn't install Qt 5, and then continuing the compile without a "make clean" in between.

**Comment by popey** [comment]
Thanks for the tip. I had to set this environment variable which sorted it.
QT_SELECT=5
