### ISSUE TITLE
Mouse is nonfunctional

### ISSUE THREAD

**Issue by Superjustinbros** [mamedev/mame#885]
In 1.73, I noticed that the games will not register inputs from the mouse aside fro being used to navigate the menus when pressing Tab.

**Comment by rb6502** [comment]
Could you please clarify what you mean?  What game are you playing, did you enable "mouse" in mame.ini, and what OS?  And did it used to work and break in 0.173, or is this simply a new report?

**Comment by Superjustinbros** [comment]
This was an error I got in MAMEUI, so I'm guessing it may not be affecting normal MAME.

Primarily what happens is instead of the mouse cursor going into the screen and becoming invisible unless you exit out of the game or press the Windows key, it is always visible, and you can move it freely across the screen. When you press Tab to open up the menu, the system's mouse cursor is shown over the orange cursor in the MAME window.

Attempting to fiddle with the Hide Mouse option doesn't seem to work for me.

**Comment by galibert** [comment]
mameui changes things massively in that area, so we really can't help.

  OG.

**Comment by Superjustinbros** [comment]
Alright then.

**Comment by Robbbert** [comment]
MAMEUI cannot be used as a basis for reporting bugs with MAME.

The problem must occur in normal MAME for this report to be considered possibly valid.

Please see if the trouble happens in the latest version of standard MAME.

**Comment by stilett0** [comment]
> MAMEUI cannot be used as a basis for reporting bugs with MAME.
> The problem must occur in normal MAME for this report to be considered possibly valid.

Thank you, Robbbert. :smiley:

**Comment by Superjustinbros** [comment]
Well I assume this can be closed now as I can't really check if it occurs in normal MAME.

Since I'm here, mind if I ask if there's a way I can report this issue directly to the MAMEUI group/team?

**Comment by happppp** [comment]
There is no MAMEUI team. Try the contact address of the MAME fork you're
using, probably in the documentation or their website.
