### ISSUE TITLE
MAME question

### ISSUE THREAD

**Issue by retroboy00** [mamedev/mame#8862]
Why play certain arcade games in MAME when you can play them via their Arcade Archives releases instead? The Arcade Archives releases have far better and actually accurate emulation, online leaderboards, multiple ROM versions depending on the game (and Arcade Archives labels them better and more regionally accurate as well), and virtually no input lag. Plus, redefining controls actually works in Arcade Archives and isn't confusing in the least. Also, it's LEGAL. MAME will forever be known as that trash arcade emulator that everybody knows but secretly hates. Even FinalBurn Neo is a better arcade emulator than MAME. If you are a MAME dev reading this and taking offense, I don't care. Everybody hates garbage ass MAME. Suck it, David 'mamehaze' Haywood.

**Comment by cuavas** [comment]
Use a forum to ask questions.
