### ISSUE TITLE
Heavy regression in the FM Towns driver

### ISSUE THREAD

**Issue by rzero9** [mamedev/mame#8865]
First off, apologies if this isn't the right place to report this. Normally I'd go to MAMEtesters, but this is a driver marked as "not working" (even though it runs a lot of software pretty well these days), so it would probably be rejected, but I feel it's still worth documenting.

Anyway, it seems the FM Towns drivers has suffered a heavy regression lately, where garbage (or sometimes just black pixels) gets drawn on top of the graphics in almost any software:

![0076](https://user-images.githubusercontent.com/13178957/142855144-c0e3d7bb-8283-42b4-8c12-7ab58a103f61.png)

![0078](https://user-images.githubusercontent.com/13178957/142855168-cb48caa0-c820-4a9f-907e-f32684099a48.png)

The immediate cause seems to be commit 467a1168843fadda75b94ed82b93048042773b5c, but all it did was uncomment a line of code in the render_text_char function that is supposed to actually render the text RAM contents at 0xc8000 to VRAM, so something must be wrong with the way that text rendering is done.

However, as far as I can tell (and I could be wrong) the TVRAM area is only there for backwards compatibility with Fujitsu's older FMR series of computers and isn't used by native Towns software, so I haven't found any test cases that actually make use of it. The "FM Towns Technical Data Book" barely makes any reference to it, and the Tsugaru source code seems to ignore it completely (other than mentioning it's for FMR compatibility), so it's unclear how it's supposed to work. I don't think that code has ever been tested, AFAIK it has been commented since at least the MESS merge, if not always.

**Comment by Robbbert** [comment]
This should be fixed in 0.238 , also you can report major regressions in MameTesters, even if the machine is marked as non-working.

**Comment by rzero9** [comment]
Thanks, I will take that into account the next time I have to report something like this.
