### ISSUE TITLE
Mac: Apple CD driver refuses to work with CDU-76S

### ISSUE THREAD

**Issue by einstein95** [mamedev/mame#8877]
Making a new issue so my comments in #8813 don't get lost as the issue was closed. The Apple CD driver appears to have a whitelist of what drives it works with. [v5.1.1](https://macintoshgarden.org/sites/macintoshgarden.org/files/apps/CD_ROM_Software_5.1.1.sit)'s contains
```
CD-ROM CDU-8005
CD-ROM CR-8005
CD-ROM CDU-8004
CD-ROM CDR-8004
CD-ROM CR-8004
CD-ROM CDU-8003
CD-ROM CDU-8002 
CD-ROM CDU-8001 
```
Since the CDU-76S isn't on this list, only a patched extension to bypass this check will let Mac OS installs "see" the CD drive. I have personally verified this.
Pinging @rb6502 as they wanted to get MAME to work with the stock extension.

**Comment by rb6502** [comment]
Thanks!  Between your list and a few hours of stepping through the MacOS code to find the failing checks it reads CDs now with a 100% stock 7.5.5 install.
