### ISSUE TITLE
Master System Paddle bug

### ISSUE THREAD

**Issue by riggles1** [mamedev/mame#8910]
MAME 0.238, the way an actual MS Paddle works is by using an absolute value, a wheel input without auto-centering basically, in the MAME "Tab" menu for the game it reads Min-Max correctly, spinner maps perfectly and is read smoothly in the preview bar.

However, despite reading correctly in the menu, in game, testing a game like Galactic Protector, the ship will jitter all over the place despite what sensitivity you set it to. Auto-centering turned off, digital speed set to 0.

Any other paddle arcade game I've tried works, so it's not down to faulty hardware either, both my optical mouse and my dedicated spinner have issues with SMS specifically.

**Comment by 0kmg** [comment]
@riggles1, I presume you are running Galactic Protector on a non-Japanese machine? According to raphnet near the bottom of [this thread](https://www.smspower.org/forums/viewtopic.php?t=6783) Galactic Protector has region detecting code and is trying to read from a non-Japanese paddle. Yes, again it boils down to regional differences. For me `mame smsj galactpr -ctrl1 paddle` works just find. @riggles1, to be sure can you verify this works fine on your end so we can close this?

Additional info: despite games apparently having code for a non-Japanese paddle it was never released. Info about it has apparently been gleaned from studying the input routine of Out Run 3D. Source: https://www.smspower.org/Development/Paddle.

**Comment by riggles1** [comment]
Thank you! It was totally a region issue, had to load i with the japanese BIOS. Tip for anyone who can't figure out how to load the J bios, you'll also need the ym2413.zip BIOS file which you don't need for loading through the US SMS, shouldn't be an issue if your BIOS stuff is complete, but worth mentioning)

**Comment by 0kmg** [comment]
Excellent! You can also run it on the smsj predecessor sg1000m3 which requires no BIOS—particularly useful if you prefer PSG sound to FM sound. Happy spinning!
