### ISSUE TITLE
Software List vgmplay platform inconsistencies

### ISSUE THREAD

**Issue by oldcodewizard** [mamedev/mame#8921]
Hi

I'm making a music player for the Software List vgmplay. See screenshot.

![afbeelding](https://user-images.githubusercontent.com/95259159/144324594-13f8c74d-1876-449c-b090-7e6174a56717.png)
[a.txt](https://github.com/mamedev/mame/files/7637521/a.txt)
[b.txt](https://github.com/mamedev/mame/files/7637522/b.txt)

I'm making filters to filter the games by name, year, publisher, platform and audio core. The screenshot shows the platforms list.

The platform is written in the description tag of the XML file.
Example: "Bomberman Collection (1996)(Hudson) (Game Boy)"
Here the platform is "Game Boy" between brackets.

However some games don't have any platform between brackets so my music player can't read the platform (it is not written there).

Would it be possible to add the platform for those games I found below (those games have missing platform)?

File a.txt has games without any platform between brackets.

File b.txt has games with something written BEHIND the platform between brackets. Not sure what that extra string is.

Thank you for your time!

**Comment by Tafoid** [comment]
As per #8923 - I've answered questions related and stance towards description fixes,
