### ISSUE TITLE
mac128.cpp - unable to format hard disk

### ISSUE THREAD

**Issue by einstein95** [mamedev/mame#8922]
Using the System 6.0.8 images from `mac_flop/sys608`
```
chdman createhd -c none -chs 1023,63,16 -o myhdd.chd
mame macplus -ramsize 4M -hard myhdd.chd -flop1 "utilities 1.img"
```
Launching the Apple HD SC Setup and then testing the disk gives the error "Unable to write to the disk." Attempting to initialize the disk fails.

EDIT: I have tried this on all the parent drivers in mac128.cpp, all failed with the same error

**Comment by unassumingbadger** [comment]
I've tried formatting and installing System 6 "for all machines" using Apple Legacy Recovery Oct 1999.iso, but none of the mac128 machines will boot to it.

**Comment by rb6502** [comment]
HD SC Setup is copy protected in a similar way to the CD-ROM extensions.  That's why the tutorial uses Drive Setup.

The resulting HDD image boots great on macplus, macse, and macclasc from the mac128 driver.  I just tried it again myself.

**Comment by unassumingbadger** [comment]
Using the tutorial here
[](https://wiki.mamedev.org/index.php/Driver:Mac_68K)

If you want to go full DIY

dd if=/dev/zero of=myhdd.hdv bs=1000000 count=500

./mame maciici -ramsize 8M -hard1 'myhdd.hdv' -cdrom 'Old Mac/Apple Legacy Recovery Oct 1999.iso'

Run "Drive Setup 1.5" and select the HDD, which will appear as <uninitialized>, and proceed to initialize it. (sees it on desktop)

Open System 6.0.8 and used Net Install.scr

Customize Install: choose "System Software for all Macs"

shutdown

./mame macplus -ramsize 4M -hard1 'myhdd.hdv'

I hear the chime and see a checkered screen for a few seconds after which the screen goes black. 

I'm running Debian Bullseye up to date as of this post with i915 GPU driver and ext4 fs if that makes any difference. MAME version is 0.238.

I am blind so there's a good chance I missed something somewhere.

Also, this creates a file sized 515.8 kB. Does it expand?
chdman createhd -c none -chs 1023,63,16 -o myhdd.chd

**Comment by einstein95** [comment]
@rb6502 I've done the minimal formatting of the hard drive using the maciici driver as described, then attempted to boot using the System Tools disk like
```
mame macplus -ramsize 4M -hard macplus.chd -flop1 "system tools.img"
```
and it just goes into the weeds (unthrottled speed goes to ~600% etc.). This also happens when I install System 6.0.8 from the Apple Legacy CD onto the HD as unassumingbadger did.

Here's my formatted (no OS installed) CHD [macplus.zip](https://github.com/mamedev/mame/files/7649657/macplus.zip) fo you to test.

**Comment by rb6502** [comment]
I'll take a look, since that was working.  In the meantime, you can use the 6.0.8 image from here: https://wiki.mamedev.org/index.php/Driver:Mac_68K

It's got plenty of free space on it.
