### ISSUE TITLE
vgmlplay: year fixes

### ISSUE THREAD

**Issue by oldcodewizard** [mamedev/mame#8926]
Hi

@ Tafoid : since you are not interested in adding the missing platforms between brackets, could you maybe fix the year values in the XML file which contain one or more "?" characters. 

For example the games (and more):

`	<software name="m82">
			<description>M82 Game Selectable Working Product Display (Kiosk)</description>
			<year>199?</year>
			<publisher>Nintendo</publisher>
			<info name="cores" value="NES APU (N2A03)" />
			<part name="001" interface="vgm_quik">
				<feature name="part_id" value="m82 game selectable working product display - 01 - main music.vgz" />
				<dataarea name="quik" size="6427">
					<rom name="m82 game selectable working product display - 01 - main music.vgz" size="6427" crc="47c24614" sha1="3a324fbe83302af3d51572c477cfe3ba6308ad81" />
				</dataarea>
			</part>
		</software>`

`	<software name="tetrsark">
			<description>Tetris (Arcade)</description>
			<year>19??</year>
			<publisher>D. R. Korea</publisher>
			<info name="cores" value="YM2149" />
			<part name="001" interface="vgm_quik">
				<feature name="part_id" value="01 coin.vgz" />
				<dataarea name="quik" size="260">
					<rom name="01 coin.vgz" size="260" crc="3f2dbc55" sha1="d53f9e82d4fa8473ea772d85ebd04b2326269f21" />
				</dataarea>
			</part>
			<part name="002" interface="vgm_quik">
				<feature name="part_id" value="02 main bgm.vgz" />
				<dataarea name="quik" size="3804">
					<rom name="02 main bgm.vgz" size="3804" crc="018d3af4" sha1="6be530a79230724ce7c8cb0bded0a34341b048f2" />
				</dataarea>
			</part>
		</software>`

See screenshot of the small list of games that have a year value containing one or more "?" characters.

2 "?" characters:

![afbeelding](https://user-images.githubusercontent.com/95259159/144506132-791ebdf0-56c7-43fc-bdf4-39b2bdcc7d7e.png)

1 "?" character part 1:

![afbeelding](https://user-images.githubusercontent.com/95259159/144506511-d1218b24-ec8a-49f0-b4c0-22e683f7b1be.png)

1 "?" character part 2:

![afbeelding](https://user-images.githubusercontent.com/95259159/144506640-2264e336-9871-48cd-a1e0-1e5802e7c3be.png)

![afbeelding](https://user-images.githubusercontent.com/95259159/144506802-b549b1f6-5a5f-4884-b432-21928d98b5e3.png)

Not an incredible big list of games to fix, right?

**Comment by Tafoid** [comment]
You are using old source files.  Update!

This all was addressed over 15 months ago https://github.com/mamedev/mame/commit/489cd2a278bd097722e6cb87019db173c1b1e2b6 except for those 2 explicitly because there is no reliable known dates of release found or even documented in MAME.

Nothing to fix.

**Comment by oldcodewizard** [comment]
Hi

I'm sorry but the data I have shown is present in the -listsoftware using the following EXE:

https://github.com/mamedev/mame/releases/download/mame0238/mame0238b_64bit.exe

Please try it yourself!

**Comment by Tafoid** [comment]
The data from -listsoftware is produced from the HASH folder contents.  If you don't update the HASH support files, MAME will not show you the updated data.  I would suggest you verify your install uses all the 0.238 package files.

**Comment by oldcodewizard** [comment]
I'm going to tell again what files I am using:

- I have downloaded https://github.com/mamedev/mame/releases/download/mame0238/mame0238b_64bit.exe
and extract it to a new empty folder. So all my hash files are the latest version.

- I'm using -listsoftware by using the EXE above.

Did you check the EXE? Please try it and be surprised: all games with "?" are still inside...
Somebody did not put the correct vgmplay.xml inside the 2.38 archive.

**Comment by oldcodewizard** [comment]
You can trust on Alexis Bougises' (game historian of arcade-history) EXCELLENT titanic work to fill in the missing year values by looking in history.xml file here: https://www.arcade-history.com/dats/historyxml238.zip

For example: the ROMset "smgp2u_md" is identified in latest history.xml as year "1992" while vgmplay.xml (latest version) shows year "19??".
Many more can be identified this way.

`Sega Mega Drive cart. published 29 years ago:

Ayrton Senna's Super Monaco GP II (c) 1992 Sega Enterprises, Limited.

- TECHNICAL -

GAME ID: G-5514
COVER ID: 670-2076

- TRIVIA -

Released on July 17, 1992 in Japan.

Reviews:
[FR] August 1992 - Joypad N.11: 88/100

- STAFF -

Supervisor: Ayrton Senna
Project Manager: Fábio Machado (Oibaf Odahcam)
Programmer: Takahiro Hamano (Ham Tak), Masahiro Wakayama (M. Waka)
Designer: Kaki, Rieko Kodama (Phenix Rie), Kazuyoshi Tsugawa (L.C.)
Sound Creator: Tokuhiko Uwabo (Bo), Haruyo Oguro (Lotty)
Test Driver: Atsuhiko Nakamura (Kyamura), Osamu Hori (Horichan)
Producer: Shimachan
Director: Dohnattenno
Assistant Director: Makoto Oshitani (Pushvalley)
Special Thanks: Will Cane, Bob, Fisher, Tomohiro Kondo (Mu), Sunset, Bassdante, Takao Miyoshi (Taka Oh)

- CONTRIBUTE -

Edit this entry: https://www.arcade-history.com/?&page=detail&id=56339&o=2
`

**Comment by Tafoid** [comment]
I'll look into whatever I can fix over time.  Sadly, arcade-history.com is not the authoritative source on all things.

**Comment by Tafoid** [comment]
You are free to send in a PR if you feel you have accurate years that are not made up and don't depend on one particular "site" but rather have multiple/varied sources.

**Comment by oldcodewizard** [comment]
Ok, thank you. But please not the latest mame version STILL has all the year values with a "?" inside...

I doubt there is any better source for game information (certainly release year and publisher) then arcade-history.com

**Comment by Tafoid** [comment]
Yes, I can acknowledge there are ?'s in there.  I added all I could in the August 2020 commit.  Like I said, they cannot be magically fixed but it will take time.

**Comment by oldcodewizard** [comment]
This screenshot says enough too about the release year? :-)

https://www.arcade-history.com/?n=&page=detail&id=56339

**Comment by cuavas** [comment]
@oldcodewizard you’re still using issues for things that are better suited to forums.  We’re not going to treat arcade-history.com as authoritative, as it’s got plenty of hearsay and unreliably sourced information in it.  Think carefully before opening any more issues.

**Comment by oldcodewizard** [comment]
> @oldcodewizard you’re still using issues for things that are better suited to forums. We’re not going to treat arcade-history.com as authoritative, as it’s got plenty of hearsay and unreliably sourced information in it. Think carefully before opening any more issues.


1. I report issues here in the vgmplay.xml file. I don't ask questions about it. If you close the issue and don't fix it, that's your problem. The issue is still there and unfixed. Issues are not only source code related...

2. I'm not going to treat MAME xml files as authoritative because it's a playground of wrong and unreliable information. The "?" infested year values for example. MANY of those games have years that are known anywhere. Present in both -listxml and -listsoftware.

3. arcade-history.com is the definitive source of reliable game information. Each data of each game is multiple times verified by many sources including game box covers, flyers, ... before it's even added to the database.
Please give examples of the "hearsay and unreliably sourced information" and present me your source you think is "reliable".
I'm VERY curious what you will come up with...

**Comment by cuavas** [comment]
>I report issues here in the vgmplay.xml file. I don't ask questions about it. If you close the issue and don't fix it, that's your problem. The issue is still there and unfixed. Issues are not only source code related...

You’re trying to force structure onto descriptions that isn’t supposed to be there, and as for the years, we prefer marking things as unknown rather than jumping to conclusions.

>I'm not going to treat MAME xml files as authoritative because it's a playground of wrong and unreliable information. The "?" infested year values for example. MANY of those games have years that are known anywhere. Present in both -listxml and -listsoftware.

Provide proper sources if you have them and open a pull request (arcade-history.com is not a proper source).  Complaining provides no value.

>arcade-history.com is the definitive source of reliable game information. Each data of each game is multiple times verified by many sources including game box covers, flyers, ... before it's even added to the database.
>Please give examples of the "hearsay and unreliably sourced information" and present me your source you think is "reliable".
>I'm VERY curious what you will come up with...

OK, first random page I looked at has multiple errors – almost everything listed is wrong: https://www.arcade-history.com/?n=cat-and-mouse&page=detail&id=4330
* Incorrect screen refresh rate (it’s about 50.5 Hz, not 60 Hz)
* Incorrect resolution (it has layers with 368*247 and 246*247 where the last pixel is one third of the width, there is no 256*240 resolution layer)
* Only 256 possible colours, not 1024
* MC6802 sound CPU runs at about 3.58 MHz, not 895 kHz
* It’s two-player alternating, not one-player

My source is the schematic from the operator/service manual, examining photographs of actual boards, and writing the current working emulation for the game.  Note my name is on all the relevant source files:
* https://github.com/mamedev/mame/blob/mame0238/src/mame/includes/laserbat.h
* https://github.com/mamedev/mame/blob/mame0238/src/mame/drivers/laserbat.cpp
* https://github.com/mamedev/mame/blob/mame0238/src/mame/video/laserbat.cpp
* https://github.com/mamedev/mame/blob/mame0238/src/mame/audio/zaccaria.h
* https://github.com/mamedev/mame/blob/mame0238/src/mame/audio/zaccaria.cpp

You really need to learn when to stop arguing.  Enjoy a temporary ban while you cool off.

**Comment by johnlassenger** [comment]
@cuavas : Does the version 0.104 say something to you? No, nothing?

Maybe a look at the following screenshot?

![afbeelding](https://user-images.githubusercontent.com/95548100/144724504-6f47e672-4363-46c1-ac31-a0b3096f4255.png)


Still nothing? Please compare the values indicated with the data you think is coming from arcade-history.com and you posted yourself (above) ... I recommend downloading MAME 0.104 and running -listxml ...

PLEASE DO SOME RESEARCH BEFORE POSTING A USELESS ANSWER AND MAKING YOURSELF LOOK LIKE A TOTAL FOOL.
YOU ARE COMPARING TO MAME'S OWN DATA FROM SEVERAL RELEASES AGO... 

As a conclusion: MAME is definitely not a proper source for arcade-history for hardware data... 

PS: please unban the user "oldcodewizard" so he can fix the "?" HELL you guys are creating.
He hasn't done anything wrong and you ban people while giving USELESS answers...

**Comment by happppp** [comment]
Ok, thanks for the clarification.
As for your ban: all the Jessica reincarnations get banned eventually.

**Comment by cuavas** [comment]
You’re misunderstanding what `players=` represents – that’s the number of sets of player controls, it isn’t always the same as the supported number of players.  Games can support multiple alternating players with a single set of player controls (a lot of early video games are like this, carrying over the pinball tradition), or they may support a single player but have multiple sets of controls for different playing positions (quite a number of single-player mahjong games support play from either side of a cocktail cabinet, and hence have two sets of player controls).

But that aside, copying info from a non-working driver in MAME isn’t a good idea in general.  Laser Battle, Lazarian and Cat and Mouse weren’t really emulated properly until late 2015 or early 2016, almost a decade after MAME 0.104 was released.

Also, if arcade-history.com uses MAME as a source, if MAME were to treat it as a definitive source, we’d get the “Citogenesis” issue illustrated in this cartoon: https://xkcd.com/978/
