### ISSUE TITLE
[megacdj & megacd2j] System ROM emulation issues

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [mamedev/mame#8933]
1. With the CD TRAY empty, only megacdj with the v1.00C BIOS boots without having to wait for a moment and pressing the emulated machine's RESET switch (set as SERVICE Switch 1 by default).
2. The Backup RAM Tool can only be used in megacdj with the v1.00G BIOS and megacd2j, since the arrow cursor refuses to appear in the CD player interface in megacdj with any BIOS other than v1.00G.

**Comment by DavidHaywood** [comment]
all machines are marked as MACHINE_NOT_WORKING

**Comment by angelosa** [comment]
@CRTRevivalDreamer how many times you have to post malformed and basically duplicated Mega CD player issues?
