### ISSUE TITLE
vague error about missing ROM/disk images

### ISSUE THREAD

**Issue by jeffythedragonslayer** [mamedev/mame#8938]
Hi, I am trying to use MAME as an N64 emulator.  This error is pretty vague about which filenames are missing.

![image](https://user-images.githubusercontent.com/13253146/144780961-930452e6-4860-435d-8cc3-f3db1494b64f.png)

**Comment by MooglyGuy** [comment]
The drive is listed as "NOT WORKING" in the text at the bottom of the screen, so you're not going to have a good time even if you do track down the correct BIOS ROMs for it. Use another emulator if you want to play N64 games.

**Comment by galibert** [comment]
The error is vague because you're missing all of them.  We do not list them
in the GUI in that case.

  OG.

**Comment by cuavas** [comment]
It’s behaving as intended – if you have none of the media images for the system, it doesn’t list the missing ones.  You’ve got to at least *try* to supply something to run.
