### ISSUE TITLE
Constant “sound_assert: u32(start) < samples()” from many drivers

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#8951]
In a debug build, many drivers constantly spam “sound_assert: u32(start) < samples()”.  If this is a real issue, it needs to be fixed; if it’s a spurious error, the check needs to be fixed.  It started some time after MAME 0.228, but I don’t know exactly when.

Examples include:
* biofreak (seattle.cpp)
* mwskins (atlantis.cpp)
* radikalb (gaelco3d.cpp)
* rmpgwt (midwunit.cpp)
* sf2049 (vegas.cpp)

At a guess, it’s something to do with the DMA-driven DAC.

**Comment by ajrhacker** [comment]
Yes, it has to do with the dmadac device, but an analysis suggested the error should be regarded as spurious. I believe fab3259f433b2c4668abaa288a215d90f17bf049 fixes this issue.
