### ISSUE TITLE
Clang/GCC 11 compile error

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#8952]
OS: `Debian x64`
GCC: `gcc (Debian 11.2.0-12) 11.2.0`
CLANG: `Debian clang version 11.1.0-4`

Error **clang**:
Compile command: `make clean && make OVERRIDE_CC=/usr/bin/clang OVERRIDE_CXX=/usr/bin/clang++ LDOPTS=-fuse-ld=lld
SYMBOLS=1 SYMLEVEL=1 PTR64=1 OPTIMIZE=3 OVERRIDE_AR=/usr/bin/llvm-ar-11 -j5`
```
Compiling src/emu/drivers/empty.cpp...
error: AST file was compiled with the target feature '+lwp' but the current translation unit is not
error: current translation unit is compiled with the target feature '-lwp' but the AST file was not
```

Error **gcc**:
Compile command: `make clean && make LDOPTS=-fuse-ld=lld SYMBOLS=1 SYMLEVEL=1 PTR64=1 OPTIMIZE=3 OVERRIDE_AR=/usr/bin/llvm-ar-11 -j5`
```
Compiling src/emu/drivers/empty.cpp...
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: note: use -Winvalid-pch for more information
```

**Comment by cuavas** [comment]
This usually happens if you upgrade your standard library and/or compiler or change compile options without doing a clean build.

**Comment by cd4053** [comment]
Investigating the issue further, the problem is the option `ARCHOPTS=-march=native` inside the `useroptions.mak` that I set years ago, there is no other options in that file. Without it, mame compiles just fine.

That option works with clang/gcc 10 but not 11.

**Comment by bigmistercactus** [comment]
Can somebody tell me the recommended way to compile mame on linux?
I'm trying to make a 32 bit linux binary too but I'm a Linux noob. Is this possible with GCC 11?
Since there is no 32 bit windows mame exe , I switched to Linux in order to run mame on older PC.

**Comment by cd4053** [comment]
This is not the proper way to ask for help, the information you need is [here](https://docs.mamedev.org/initialsetup/compilingmame.html#fedora-linux).
