### ISSUE TITLE
MAME Bugs fixed to be added to Final Burn Neo Emulator

### ISSUE THREAD

**Issue by jmodlin210** [mamedev/mame#9004]
Will the MAME bugs that got fixed to be added in Final Burn Neo emulator which are:
- 03754: [Sound] (thunderx.cpp) scontra, scontraj: Flaws in sound emulation (d187a28) (Aaron Giles)
- 03737: [Speed] (nemesis.cpp) salamand, lifefrce: Music speed is slow. (d187a28) (Aaron Giles)
- 07078: [Sound] (tmnt.cpp) tmnt, tmntua, tmntj: Sound or gameplay is slow if comparing with arcade (d187a28) (Aaron Giles)
- 06764: [Misc.] (deco32.cpp) captaven and clones: Credits sequence out of sync (d187a28) (Aaron Giles)
- 03232: [Crash/Freeze] (gaelco.cpp) thoop: Black screen when you continue on 4 stage (edc0dfb) (David Haywood)
- 07191: [Documentation] (maygayep.cpp) ep_ijob: "The" is missing in the description. (51c083a)
- 08147: [Documentation] (vsnes.cpp) balonfgt: DIP Switches for Extra Lives are labeled wrong (f4ee98d) (kmg)
- 07839: [Gameplay] (vendetta.cpp) vendetta and all clones: All demo sequence broken (4d1fdd2) (Angelo Salese)
- 06393: [Gameplay] (vendetta.cpp) vendetta (all versions): Hit boxes for some grounded enemies are incorrect (4d1fdd2) (Angelo Salese)

**Comment by 0kmg** [comment]
This tracker is for issues related to development builds. **_MAME_** development builds. Please ask your questions in a forum relevant to FBNeo.

**Comment by jmodlin210** [comment]
thank you and would you be able to submit these mame bugs fixed to final burn neo are: 03754: [Sound] (thunderx.cpp) scontra, scontraj: Flaws in sound emulation (d187a28) (Aaron Giles)
03737: [Speed] (nemesis.cpp) salamand, lifefrce: Music speed is slow. (d187a28) (Aaron Giles)
07078: [Sound] (tmnt.cpp) tmnt, tmntua, tmntj: Sound or gameplay is slow if comparing with arcade (d187a28) (Aaron Giles)
06764: [Misc.] (deco32.cpp) captaven and clones: Credits sequence out of sync (d187a28) (Aaron Giles)
03232: [Crash/Freeze] (gaelco.cpp) thoop: Black screen when you continue on 4 stage (edc0dfb) (David Haywood)
07191: [Documentation] (maygayep.cpp) ep_ijob: "The" is missing in the description. (51c083a)
08147: [Documentation] (vsnes.cpp) balonfgt: DIP Switches for Extra Lives are labeled wrong (f4ee98d) (kmg)
07839: [Gameplay] (vendetta.cpp) vendetta and all clones: All demo sequence broken (4d1fdd2) (Angelo Salese)
06393: [Gameplay] (vendetta.cpp) vendetta (all versions): Hit boxes for some grounded enemies are incorrect (4d1fdd2) (Angelo Salese)

**Comment by Robbbert** [comment]
@jmodlin210 we've watched you annoying the FBN devs with an avalanche of issues, which got you banned. Don't start here, or you'll get the same.
