### ISSUE TITLE
Street Fighter II Hyper Fighting and clones running too fast

### ISSUE THREAD

**Issue by jmodlin210** [mamedev/mame#9005]
Street Fighter II Hyper Fighting and clones are running too fast.

**Comment by 0kmg** [comment]
If this is an issue with a release version of MAME, please report it at mametesters.org. Either way you'll need to provide a more detailed description of the problem and how to reproduce it. Exactly what is running to fast?

**Comment by angelosa** [comment]
Duplicate of [MT#00408](https://mametesters.org/view.php?id=408) etc. etc. etc.
