### ISSUE TITLE
pluginspath option not recognized

### ISSUE THREAD

**Issue by CRP** [mamedev/mame#901]
Upon starting mame I always get the following error:

`[LUA ERROR] /Users/Shared/Emu/mame/src/plugins//boot.lua:7: module 'json' not found:
	no field package.preload['json']
	no file '/Users/cprinoth/plugins/json.lua'
	no file '/Users/cprinoth/plugins/json/init.lua'
	no file '/usr/local/lib/lua/5.3/json.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './json.so'`

despite having set the pluginspath param correctly. Error disappears when I start mame from the source folder. So it looks like the param is not recognized/used at all.

**Comment by rb6502** [comment]
Agreed, it's using pluginspath to find boot.lua but the rest of the plugins assume ./plugins as the path.

**Comment by Tafoid** [comment]
http://mametesters.org/view.php?id=6221
Posted to MT

**Comment by cracyc** [comment]
This should be fixed.   Let us know if there's still an issue.
