### ISSUE TITLE
benchmark bug?

### ISSUE THREAD

**Issue by elmosesamestreet** [mamedev/mame#9026]
Hi!

When doing a benchmark on the game pacman by using -bench 120, I get very different rezults.
The % goes up/down by 60% when redoing the benchmark. Also for other games. Could this be a bug? What could explain this big change? My computer has plenty of hard drive space, free RAM, 16 cpu cores and is not running any program (tested on windows and linux).

I know this is not a support forum but to better understand what's happening in a benchmark, those questions:

- is the title screen of the game emulated or is the title screen skipped and the real game emulated in a benchmark?

- is it correct no sound/video is emulated or are they just not output to the sound/video hardware but really emulated?

- how many threads does an  average mame game uses? I'm not a programmer but I think 1 different thread for driver emulation/audio/video or is this wrong (so certainly 3 threads)?

- how many cpu cores are used by mame? More specific, how are the above different threads allocated to cpu cores and are all available cpu cores used or is there a maximum number (specified in the source code) of cores used, which is never exceeded?

Thank you so much for helping!

 ELMO

**Comment by happppp** [comment]
Not a MAME issue I believe. And as you said you know it yourself, github issues is not a user support forum.

It's known that benchmark results can differ between runs, let's say 5000% on run 1, 5060% on run 2, 4940% on run 3. MAME itself is always doing identical emulation, so it must be the OS or CPU (OS is doing work in the background, or CPU/memory caching, who knows). To get a more accurate result, do several benchmark runs and take the average.

**Comment by rb6502** [comment]
% as reported by MAME is the percentage of the game's full speed.  For a game running around 1000% unthrottled, which is pretty common, a 60% variance isn't much.  John IV's benchmarking site takes the average of 3 runs to smooth out the results.

Reasons the times can differ include:
- Systems with poor thermal management (e.g. laptops and SBCs) can get heated up by the first run and throttle afterwards
- With modern OSes background tasks and daemons can spawn at any time and eat CPU and I/O
- Some games do one-time setup the first time you run them in MAME because their NVRAM ("CMOS" in PC-speak) is blank.  MAME saves the NVRAM to disk after the first run.

Regarding your questions, most MAME games are single-threaded to ensure temporal coherence between the various components.  Games with 3D graphics can thread off the polygon rendering (which is done 100% in software in order to duplicate the weirdness of early GPUs).  Sound and video hardware are always emulated (most games wouldn't run otherwise), it's not a pure test of the emulated CPUs.  And the game runs exactly the same in benchmark as it does when played normally.

**Comment by elmosesamestreet** [comment]
Hi

Thanks for all the answers!

Is it possible to ask some final questions?

- are there plans to support multiple cpu cores in the future of MAME? Or is this asking for problems in the code?
A lot of CPU power is unused and I'm sure newer games can really use more cpu power to be emulated at full speed.

- are benchmarks also supported on software list games by running: mame machine game -bench 120
or is it only officially supported for arcade games (because MESS was added much later)?

ELMO

**Comment by cuavas** [comment]
This is not appropriate use of an issue tracker – you’re just asking questions, you don’t actually have an issue to report.  Use a more appropriate venue.

**Comment by elmosesamestreet** [comment]
SUCK MY MOTHERFUCKING DICK

GO BACK TO YOUR COUNTRY "cuavas" OR WHERE DICKHEADS LIKE YOU COME FROM

**Comment by elmosesamestreet** [comment]
THE ISSUE IS THAT THE BENCHMARK IN MAME IS A PIECE OF SHIT
IT GOES UP WITH 60%!!!!!!!

CORRECT BENCHMARKS DONT DO THAT

EXAMPLES

https://www.geekbench.com/
ETC ETC

YOU ARE EVEN TOO DUMB TO SEE THE ISSUE HERE

**Comment by elmosesamestreet** [comment]
SO FIX THE ISSUE INSTEAD OF CLOSING ISSUES YOU CANT FIX BECAUSE YOU HAVE NO IDEA HOW TO MAKE A CORRECTLY WORKING BENCHMARK

EITHER REMOVE THE BENCHMARK CODE THAT DOESNT WORK, FIX IT OR REOPEN THIS ISSUE AND TRY TO FIND A SOLUTION

DONT CLOSE IT IF YOU DONT KNOW SHIT

AND NOW FUCK OFF...

**Comment by elmosesamestreet** [comment]
> Not a MAME issue I believe. And as you said you know it yourself, github issues is not a user support forum.
> 
> It's known that benchmark results can differ between runs, let's say 5000% on run 1, 5060% on run 2, 4940% on run 3. MAME itself is always doing identical emulation, so it must be the OS or CPU (OS is doing work in the background, or CPU/memory caching, who knows). To get a more accurate result, do several benchmark runs and take the average.

SURE WE ALL BELIEVE YOU
IT IS THE OS OR CPU !!!!!

VERY VERY STRANGE ALL OTHER BENCHMARKS I RUN ARE NOT AFFECTED BY OS OR CPU...

ONLY MAME IS...

THAT TELLS WHICH SOFTWARE HAS A WRONG BENCHMARK AND WHICH ONES ARE CORRECT

**Comment by elmosesamestreet** [comment]
> % as reported by MAME is the percentage of the game's full speed. For a game running around 1000% unthrottled, which is pretty common, a 60% variance isn't much (36 FPS out of 600). John IV's benchmarking site takes the average of 3 runs to smooth out the results.
> 
> Reasons the times can differ include:
> 
>     * Systems with poor thermal management (e.g. laptops and SBCs) can get heated up by the first run and throttle afterwards
> 
>     * With modern OSes background tasks and daemons can spawn at any time and eat CPU and I/O
> 
>     * Some games do one-time setup the first time you run them in MAME because their NVRAM ("CMOS" in PC-speak) is blank.  MAME saves the NVRAM to disk after the first run.
> 
> 
> Regarding your questions, most MAME games are single-threaded to ensure temporal coherence between the various components. Games with 3D graphics can thread off the polygon rendering (which is done 100% in software in order to duplicate the weirdness of early GPUs). Sound and video hardware are always emulated (most games wouldn't run otherwise), it's not a pure test of the emulated CPUs. And the game runs exactly the same in benchmark as it does when played normally.

THATS NOT POSIBLE
SINCE A BENCHMARK CANT SKIP THE TITLE SCREEN WITHOUT USER INPUT

AS A RESULT THE BENCHMARK DOESNT RUN THE REAL GAME...

YOU GUYS DONT KNOW ANYTHING

**Comment by elmosesamestreet** [comment]
AND NOW YOU GUYS BLOCK ME BECAUSE ANOTHER ISSUE YOU CANT SOLVE HAS APPEARED ;-)
THATS MAME's TRADITION TO BLOCK ISSUES YOU CANT SOLVE

...

**Comment by smf-** [comment]
We can't solve the problem with your caps lock key, or your attitude.

Only you can do that.
