### ISSUE TITLE
Apple IIgs music is out of tune

### ISSUE THREAD

**Issue by ERolfi** [mamedev/mame#9045]
By running The Music Studio, the music appears to be out of tune. I confirmed it by using the Lingot guitar tuner. When you place the note on the C string, it is out of tune. C is tending to C# (no pun intended)

**Comment by rb6502** [comment]
Is this current MAME?  Older versions had some known tuning issues with looping samples in the ES5503, but those are fixed now.  Also, did you verify on a real machine that the same instrument in The Music Studio is in tune?

**Comment by ERolfi** [comment]
Yes, it's MAME 0.238 and I did verify it on a real machine and also in other emulators.

**Comment by rb6502** [comment]
This has been resolved for the next release (or if you compile yourself you can pull latest).  I verified with a tuner app on my phone that Music Studio and synthLAB are in tune and that Modulae now matches real hardware.
