### ISSUE TITLE
0.239 not working on win xp 64 bit

### ISSUE THREAD

**Issue by bigmistercactus** [mamedev/mame#9063]
Hello mame team,

What is the minimum supported windows version?
I have win xp 64 bit but mame 0.239 doesn't do anything. The exe does not run.

**Comment by startaq** [comment]
https://docs.mamedev.org/initialsetup/mameintro.html#supported-os

**Comment by bigmistercactus** [comment]
What specific features of windows 7 are used in MAME so that windows xp and windows vista are not supported?
It's kind of ridiculous I have to slow down my PC with slow windows 7 just in order to run MAME.
windows xp is 10x faster then windows 7 ... So all PC resources, including RAM, are eaten by windows 7 which is required for MAME.

**Comment by rb6502** [comment]
It's not a matter of specific features, it's a matter of we aren't being paid to do this, and so we choose not to support operating systems which are not supported by Microsoft.  Fortunately, Windows 11 performs quite well with MAME and other PC games and emulators, and if you can't do that, then there's always Linux.

**Comment by Firehawke** [comment]
There's also the fact that the compilers we're using aren't supporting XP binary targets.
See https://sourceforge.net/p/msys2/mailman/message/35191999/ -- it's been unsupported for roughly five years.  To continue to support XP would require dropping a lot of newer features in the C++ compiler to go back to a five-year-old build of msys2, which isn't going to happen.

**Comment by bigmistercactus** [comment]
Why use msys2 when there is GCC, supporting 32 and 64 bit windows versions...

https://gcc.gnu.org/

Is the reason 32 bit is dropped also this msys2 not supporting 32 bit?

All people having an old 32 bit pc, perfectly suitable to run old arcade games from the 80s in mame are not able to run mame because they first have to find out how to compile a 32 bit version. 

And the same is true for people having PCs too slow to run windows 7.

As a consequence, using an old pc to use for mame is getting harder and harder each day.
Isn't that the opposite of software preservation?

IMHO there should be a 32 bit exe supporting windows xp available for this purpose.

**Comment by npwoods** [comment]
Anybody who is up to the challenge is free to backport MAME to run on Windows XP, early versions of Mac OS X on PowerPC or DOS, or whatever platform they see fit.

**Comment by Robbbert** [comment]
There's a person who has been building for XP for over a year. I cannot personally vouch that these builds work, but there's been no bad feedback. Just remember that Mamedev does not support these builds.

The 0.239 version should be there in a few days.
https://drive.google.com/drive/folders/1eiNztWEpk0C7CiiZXz0SMDM_eJOmb0FO?usp=sharing

**Comment by rb6502** [comment]
32-bit PCs are being left behind by everyone.  Microsoft was actually late to that party with Win 11 finally cutting that cord.  Ubuntu and Fedora both require 64-bit CPUs, and the Mac's been 64-bit since 2007.  And as the tools and operating systems are leaving them behind, it's a lost cause for us to as well.

Contrary to popular misconception, 32-bit-only PCs are no longer capable of giving a good MAME experience.  1970s and early 80s games with analog sounds require significant CPU power.  Those were silent in earlier versions; they're a lot more fun with the sound.  We specify a 4th-generation Core i5 or better as minspec for that and other reasons.  You can get refurbished/used examples under US$100, and they'll run PS2/Dreamcast/Gamecube/PS3 emulators too if you drop in a video card.

**Comment by bigmistercactus** [comment]
I didn't know that. Thanks for the explanation!

**Comment by cuavas** [comment]
It’s well-known that x86-64 is about 30% faster than i686 because of architectural changes (more registers, PC-relative addressing, etc.).  Windows XP and Windows Vista are not supported, and that’s not changing.  If you want to build for an unsupported target, you’re on your own.
