### ISSUE TITLE
compiling using visual studio 2022

### ISSUE THREAD

**Issue by bigmistercactus** [mamedev/mame#9066]
Since the docs about compiling with visual studio are a bit outdated (and not much explanation + a specific visual studio compile problem), I hope to get some answers here.

1) if I need a visual studio 2022 solution file, do I need to generate a vs2017 solution and open this with visual studio 2022? Visual studio 2017 is not really used anymore and maybe not even available for download. Will visual studio 2022 compile it correctly, because I can see the compile problem there? What version of visual studio is able to compile it? 

https://wiki.mamedev.org/index.php/Building_MAME_using_Microsoft_Visual_Studio_compilers

2) I understand I need the msys2 environment even if I want to compile using visual studio in order to generate the visual studio solution file. I can find here a download link to it but it's not up to date.

https://www.mamedev.org/tools/

Can I use the latest version available on https://www.msys2.org/ too or is there a reason this specific older version on mamedev's website is needed?

3) Is it possible by using the way above (using visual studio) to compile a 32 bit exe or will only a 64 bit version compile without errors?

4) Can a "MESS", "ARCADE" etc build of MAME be achieved using visual studio too? I read this can be done when using 
GCC and specifying this in the "make" command, but can it also be done using the visual studio compiler?
(I understand this question is going maybe too far,but in fact,no docs are available about this)

My goal: I want to make a website offering 32 bit versions of mame for windows and also 64 bit versions that work on pre-windows 7 systems. But first I need to know how to compile using visual studio. I choose for visual studio because of the better debugger.

In the hope to accomplish this, maybe somebody can answer 1) to 4) please? So I just want to know the correct way to generate a visual studio 2022 solution file and the needed msys2 version for this. 

For All other things (in the source code) to achieve my goal , I understand I'm on my own and I also don't ask any support for that.

**Comment by MooglyGuy** [comment]
JJ, you really need to learn to make your accounts not so obvious, it takes all the fun out of the fun little back-and-forth we used to have.

At this point it's just a matter of "Oh, hey, yeah, this person is 'just asking questions', they literally registered on Github this month, and they've interacted with no projects at all other than MAME. Hiya, JJ."

You don't have to go leaping straight for the /mamedev/mame/issues/ like a bull at a gate.

**Comment by bigmistercactus** [comment]
I don't know what you are talking about.

I'm just looking for an answer to my question. Where else I need to ask this?
Thanks for the help or forwarding me.

**Comment by bigmistercactus** [comment]
Maybe if I tell I'm autistic, it can explain some things?

**Comment by Robbbert** [comment]
There's already someone else making builds for XP. No need for you to reinvent the wheel.

**Comment by bigmistercactus** [comment]
If somebody knows answer to 1) to 4), please help me?

Thanks

**Comment by cuavas** [comment]
This is not a forum for general questions and help.

Instructions for using a standard MSYS2 installation (if you can’t or don’t want to use the tools from mamedev.org) are here: https://docs.mamedev.org/initialsetup/compilingmame.html#using-a-standard-msys2-installation

You can cross-compile a 32-bit build using MinGW tools on a 64-bit Linux system, but it’s not supported, so don’t report issues against it.
