### ISSUE TITLE
make vs2019 compile error

### ISSUE THREAD

**Issue by bigmistercactus** [mamedev/mame#9068]
Trying to make a vs2019 solution file following these guidelines: 
https://wiki.mamedev.org/index.php/Building_MAME_using_Microsoft_Visual_Studio_compilers

I replaced make vs2017 PYTHON_EXECUTABLE=c:/msys64/mingw64/bin/python.exe by make vs2019 PYTHON_EXECUTABLE=c:/msys64/mingw64/bin/python.exe because vs2017 is not used anymore I saw in the makefile.

I'm using https://github.com/mamedev/buildtools/releases/download/6.0/msys64-2020-11-03.exe
and https://github.com/mamedev/mame/releases/download/mame0239/mame0239s.exe
There is nothing added/modified to both archives: they are extracted to my hard drive the way they are.

The error I have:

D:\mame0239>make vs2019 PYTHON_EXECUTABLE=d:/msys64/mingw64/bin/python.exe
GCC  detected
Creating obj/Release
Creating obj/Release/src/host
Creating obj/Release/src/host/lua-5.3.0/src
Creating ../../bin/windows
lapi.c
process_begin: CreateProcess(NULL, gcc -MMD -MP -MP -DNDEBUG -DLUA_COMPAT_MODULE -I../../src/host/lua-5.3.0/src -Wall -Wextra -Os -o obj/Release/src/host/lua-5.3.0/src/lapi.o -c ../../src/host/lua-5.3.0/src/lapi.c, ...) failed.
make (e=2)
genie.make:283: recipe for target 'obj/Release/src/host/lua-5.3.0/src/lapi.o' failed
make[1]: *** [obj/Release/src/host/lua-5.3.0/src/lapi.o] Error 2
makefile:1494: recipe for target '3rdparty/genie/bin/windows/genie.exe' failed
make: *** [3rdparty/genie/bin/windows/genie.exe] Error 2

I have no knowledge of the mingw64 so please tell me what I can try to solve this.
The goal is to have a vs2019 solution file which I will use to compile mame.

**Comment by cuavas** [comment]
Don’t use issues as a support forum.  This is a warning.
