### ISSUE TITLE
compile errors are issues

### ISSUE THREAD

**Issue by bigmistercactus** [mamedev/mame#9069]
Don’t use issues as a support forum.  This is a warning.

_Originally posted by @cuavas in https://github.com/mamedev/mame/issues/9068#issuecomment-1003117726_

Hello

Why do you close an issue about a compile error in latest source, using the environment provided by mamedev.org on a supported operating system?
Isn't a compile error an issue? There is no other place to ask this. The source code is coming right from here and the build environment too...

**Comment by cuavas** [comment]
Because the error you’re getting is caused by something in your environment, and you’re obviously trying to use issues as a support/discussion forum.
