### ISSUE TITLE
MAME 0.239 assertion failures when trying to search in the main UI

### ISSUE THREAD

**Issue by chungy** [mamedev/mame#9070]
Just by running mame without parameters and trying to type to search for a game, or click the left-side menu to navigate categories, MAME crashes with an assertion failure:
`/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = ui::menu_item; _Alloc = std::allocator<ui::menu_item>; std::vector<_Tp, _Alloc>::reference = ui::menu_item&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.`

This is happening at least on Arch Linux with GCC 11, Linux 5.15.10

**Comment by cuavas** [comment]
Don’t build with iterator debugging enabled, it’s not supported.

**Comment by chungy** [comment]
How do you disable it?

**Comment by cuavas** [comment]
Don’t define `_GLIBCXX_ASSERTIONS` (or if your compiler is built with a hacked-up spec that forces it on by default, undefine it, along with `_FORTIFY_SOURCE` which Gentoo and Ubuntu force on).

**Comment by chungy** [comment]
It is Arch, so "hacked-up spec" does apply pretty well. 

Noted, thanks :)

**Comment by chungy** [comment]
After recompiling with `_GLIBCXX_ASSERTIONS` undefined, same error still happens.
