### ISSUE TITLE
benchmark time issue

### ISSUE THREAD

**Issue by darealcookiemonster** [mamedev/mame#9085]
wrawrawrawrawrawrawrawrawra it's cookiemonster here!

Cookiemonster is making a tool for easy benchmarking mame. You can specify the rom, the time to benchmark etc.
After running all benchmarks, it displays a nice overview of the data.
See screenshot below. All process data is correct because I use this Class from Microsoft .NET: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-6.0
I tested this class on other programs like Microsoft Word, Notepad, ... and the memory usage and total processor time are reported correctly. So it must work correctly on the process mame.exe too.

![afbeelding](https://user-images.githubusercontent.com/96999734/147890118-9b6a19ce-f4ca-4109-bf67-aceada653343.png)

I found some issues, 1 of them is certainly wrong, but I don't know about the other one.
First I need some cookies!!!
wrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawrawra...

OK, I'm ready to explain!

In the screenshot you see in red the MAME output, in blue the Microsoft .NET output (process class).
The full game speed is calculated by dividing the benchmark value by 100.

1) Here is the log file of my tool:

22:30:27 MAME Afterburner airborne...
22:30:27 Benchmarking: blitz -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:31:03 Benchmarking: crusnusa -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:31:20 Benchmarking: cyvern -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:31:30 Benchmarking: dkong -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:31:33 Benchmarking: drivedge -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:32:02 Benchmarking: gnbarich -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:32:09 Benchmarking: gradius4 -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:32:22 Benchmarking: harddriv -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:32:39 Benchmarking: kidniki -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:33:02 Benchmarking: kof98 -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:33:13 Benchmarking: mario -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:33:23 Benchmarking: mk4 -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:33:58 Benchmarking: pacman -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:34:00 Benchmarking: pinkswts -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:34:09 Benchmarking: pong -bench 90 -rompath F:\MAMEUI\Roms;F:\MAMEUI\Software
22:34:32 MAME Afterburner has landed...

You can see in this example each game is benchmarked for 90 seconds. The command you see is directly passed to mame.exe
However you can see game 'blitz' started at 22:30:27 and ended at 22:31:03. 
This is not a 90 seconds time (it's not even 1/2 of that time). The same for all other games.

If you look at the screenshot the total processor time as reported by the Microsoft .NET output (process class) is for the game "blitz"
1 m 34 s 203 ms. This is +/- 90 seconds here.
But for all other games the total processor time is much much lower then 90 seconds.

Why is the MAME benchmark not run for 90 seconds if you specify for example "pacman -bench 90"? For "pacman" in the screenshot, you can see it only needed 1 sec of processor time. 

2) If you specify for example "blitz -bench 90", MAME gives following output:

Average speed: 267.86% (89 seconds)

If you run "blitz -bench 60", then you got following output:

Average speed: 293.00% (59 seconds)

So no matter what time you choose, MAME always gives output 1 second less then the time you entered.
Is this a bug or why is 1 seconds cut off from the specified time?

**Comment by cuavas** [comment]
* Benchmark times are specified in emulated time, not wall clock time or CPU time.
* MAME allows itself to stabilise for one second before measuring performance – this is why the emulated interval the calculated speed is based on is one second less than the specified interval.
* **This is not a help forum.**
