### ISSUE TITLE
chdman - can`t choose compression type

### ISSUE THREAD

**Issue by necros2k7** [mamedev/mame#9086]
what exactly is command line?
chdman -c lzma,flac -nocs -np 12 createcd -i "in.iso" -o "out.chd"
nothing happens

**Comment by MooglyGuy** [comment]
The Github issue tracker is not a support forum.

**Comment by darealcookiemonster** [comment]
Just smile and waves boys ... Smile and wave!!!

**Comment by smf-** [comment]
The command chdman help createcd

shows the correct usage, options go last not first.
