### ISSUE TITLE
CRAZY benchmark

### ISSUE THREAD

**Issue by darealcookiemonster** [mamedev/mame#9087]
* Benchmark times are specified in emulated time, not wall clock time or CPU time.
* MAME allows itself to stabilise for one second before measuring performance – this is why the emulated interval the calculated speed is based on is one second less than the specified interval.
* **This is not a help forum.**

_Originally posted by @cuavas in https://github.com/mamedev/mame/issues/9085#issuecomment-1003781090_

If you create a benchmark which cuts off 1 second and DON'T DOCUMENT this then you can expect people to report this as an issue. i don't use this as a forum, I report this CRAZY benchmark you guyd created...

There are 2 solutions:

- leave this as it is and expect more people report this as an issue so you can say your belovee words "this is not a forum"

- SNIFF LESS DRUGS while programming and let the benchmark run time +1 seconds and write the correct time as output

**Comment by darealcookiemonster** [comment]
Wrawrawrawrawrawrawrawra 
I want cookies!!!

**Comment by MooglyGuy** [comment]
Get psychological help, JJ. You need to be involuntarily committed to an asylum.

**Comment by darealcookiemonster** [comment]
I have no idea what this answer is all about. What is a "JJ"?
Fix thebenchmark instead of posting nonsense here

THIS IS NOT A SUPPORT FORUM!!!

**Comment by darealcookiemonster** [comment]
wrawrawrawrawrawrawra cookies!!!!ll wrawrawrawrawra

**Comment by MooglyGuy** [comment]
What does it feel like to be completely batshit insane? Do you ever take a break from your daily routine of painting the walls in your own feces to think to yourself, "Wow, it's incredible how fucking insane I am?"

Or do you just put those thoughts out of your mind before you huff the next can of paint, bring up the VPN, and go for another round on Github?
