### ISSUE TITLE
Support for Hugo Jungle Island

### ISSUE THREAD

**Issue by heroku-miraheze** [mamedev/mame#9172]
Hello.
I need to request Hugo Jungle Island to play this using MAME, please.
Thank you.

**Comment by telanus** [comment]
Afaik this only came out on Windows. So it won't run on MAME. You'll need something like pcem/86box to run it. That is if you want to run it and can't get it to run on Windows 8-11. On Linux you can try WINE.

**Comment by happppp** [comment]
Good luck finding that game, here is not the right place to ask.
