### ISSUE TITLE
Inaccurate Speed Reporting On Exit Loading a Savestate

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#9190]
While the behavior described in this issue is specific to the CPS-3 driver, it applies to all systems in MAME.

As a test case, I let the sfiii3 driver run for 558 seconds in MAME, using the command-line parameters:
```
mame sfiii3 -window -nodebug -nolog -sound none -video d3d -nohlsl -noafs -throttle`
```

Prior to exiting MAME, I saved the machine state using Shift+F7, and used slot 'A'. I then exited. This is what was subsequently reported on the command line.
```
[MINGW64] C:\mingw\mame>mame sfiii3 -window -nodebug -nolog -sound none -video d3d -nohlsl -noafs -throttle
Average speed: 99.60% (558 seconds)
```

I then re-started MAME with the same game again using the same parameters. I loaded the relevant save-state, then exited after about two seconds. This was the resulting output after exit:
```
[MINGW64] C:\mingw\mame>mame sfiii3 -window -nodebug -nolog -sound none -video d3d -nohlsl -noafs -throttle
Average speed: 33972.84% (559 seconds)
```

It appears that MAME is somehow factoring the run-time of a save-state into the statistics that are given at the end of a run. This is obviously incorrect and should be fixed.

**Comment by Tafoid** [comment]
In preliminary testing, it only seems to happen when using the during emulation via UI saving/loading of states.
Using _**-autosave**_ for your first run and **_-state auto_** for the second, letting the game run for a few seconds before exiting, I did not experience this issue.

**Comment by MooglyGuy** [comment]
Thank you for the additional information, that helps narrow down the potential code paths that could be causing the issue.

**Comment by ajrhacker** [comment]
77834407f23ad3418ed90168179ca895080dfa8d is the simplest way I could try to address this issue. A more complicated approach would involve summing all the intervals of emulated time (since loading states can make `machine().time()` jump around arbitrarily), but I don't think that's worth it.

**Comment by ajrhacker** [comment]
On a second analysis, I see the algorithm already sums intervals of emulated time, so the code has been simplified.

**Comment by MooglyGuy** [comment]
Closing issue as it now appears to be addressed.
