### ISSUE TITLE
info info info!!! Emu Loader is being continued as GNU GPL software!

### ISSUE THREAD

**Issue by emuloader** [mamedev/mame#9205]
Hello,

In the following github https://github.com/wp-xyz/emuloader
people are trying to compile Emu Loader after the developer Ciro Consentino passed away on December 7 in order to preserve the software for the future.

https://emuloader.mameworld.info/

* The latest source code that is complete and can be compiled is version 8.8.8 https://emuloader.mameworld.info/files/el888-src.rar
Newer versions have missing custom widget controls and can't be compiled.
This version is compiled in Delphi 7 and people are trying to remove dependencies on commercial 3rd party and Delphi 7 components in order to have a completely free and open source version.

* Once this is done the Lazarus IDE (https://www.lazarus-ide.org/) using the free pascal compiler (https://www.freepascal.org/) will be used to compile a completely free and open source version of Emu Loader (including the compiler itself is open source).
This ensures the future of the software and people can just use Lazarus to compile it on any platform (win/mac/linux), in the hope to find contributors for the project.

This is a HUGE task, so I want to ask if people want to test the program (you need Delphi 7 to compile it yourself, which is very easy and fast) or if there are Delphi/Pascal coders wanting to help.

best regards
Emu Loader preservation

**Comment by startaq** [comment]
This isn't the right place. Post it to a forum.
