### ISSUE TITLE
gnw_smb: Lakitu Timing Bug in Game & Watch: Super Mario Bros. (Crystal Screen) MAME 0.239

### ISSUE THREAD

**Issue by famiclone6502** [mamedev/mame#9225]
The timing for Lakitu is incorrect and super fast when dropping the hammers. It will instantly kill you if you're in its path, as it moves faster than the classic LCD screen could ever refresh. Once you reach a difficulty level with Lakitu, the game becomes nearly impossible at this point, and you cannot progress to more difficult loops.

How to reproduce:
Every time you complete all the worlds, you're presented with a more difficult loop. However, you can skip to an appropriate difficulty loop by holding the jump button and pressing start. You'll know you did the code correctly if you get Bullet Bill attacks on the first level. Play through this stage, and you should get at least one Lakitu blitz attack before the end of the level. 

Compared to the original hardware:
I have verified on multiple versions of the original game that Lakitu never moves this fast, and you can safely dodge the hammers Lakitu throws. 

This has been present since the game was first supported in MAME, but before reporting, I wanted to verify that it was still present in the latest version (as of this bug report, 0.239). I checked and did not find any duplicate reports, so my apologies if this is already known. 

I love that these types of games are finally supported, so thank you!

**Comment by happppp** [comment]
Ok I see what you mean. It does not happen consistently (all the time). It appears the hammer fall is much faster only if the fall 'animation' step is at the same time as a screen scroll step. Are you certain it's not a bug that happens on the real hardware?

You say you have verified on multiple versions of the original game, but I'd still like other people to test it.
@algestam do you still have this game?

**Comment by famiclone6502** [comment]
It was difficult to find a video demonstrating this since there's a new product with the same name, but here is what it's supposed to do:

[https://youtu.be/NdeG7xNSgvM?t=72](https://youtu.be/NdeG7xNSgvM?t=72) (Lakitu starts at around 1 min 12 seconds, another at around 1 min 44 seconds).

**Comment by algestam** [comment]
Thanks for the report. I have two variants of the game and will check if it's reproducible on the actual units.

**Comment by algestam** [comment]
Have tried to reproduce the issue on real hardware and from my observations and understanding of the issue, the actual hardware behaves in a similar way as the emulated game. The speed and acceleration of the Lakitu hammer seems to be set at random, sometimes it moves fast and sometimes slower. The hammer movement seems to sometimes move faster than the LCD/game refresh time even on actual hardware.

This video was taken from a real unit and Lakitu is appearing several times in this clip: https://youtu.be/lr5qo8QSjeM

The appearance at around 1:49 is an example of when the hammer moves very quickly on a real unit (https://youtu.be/lr5qo8QSjeM?t=109).

@famiclone6502 Do you still think there's any difference between the emulated game and the real hardware?

**Comment by famiclone6502** [comment]
@algestam 
I see what you mean with the one thrown at 1:49. If the screen could physically update as quickly as the game code attempts, the behavior might be the same... however, without that physical screen refresh limitation, the violently fast movement just _looks_ weird. 

Overall, I think there may be multiple possibilities MAME is different from my perspective:

1. As stated above, the code is running properly, but screen refreshes faster than physically possible on original hardware. The "problem" is purely aesthetic, and I never noticed the actual behavior was the same on real hardware. 
2. The randomness acts differently (or more unlucky?) for me than real hardware. I keep getting the super fast hammers in MAME. 
3. The code behavior I've experienced on real hardware is just a different revision than the dumped version. The last time I compared over and over with an original unit, I had no issues with Lakitu on real hardware. But, a new version of MAME came out, so I decided to hold off on the report until I could see if the new version acted the same. Right now, the closest hardware I have handy is a micro reissue, and after repeated attempts, Lakitu appeared zero times in 3-1! The buttons are also different, hitting Game during play will mute it, the MAME version restarts to 1-1.

So, if the actual code behavior is normal for the version dumped in MAME, would it benefit G&W games to limit them to their real-world refresh rate? 

Thank you for your time checking on this and videoing it! Should I go ahead and close this?

**Comment by happppp** [comment]
Yes this issue can be closed.
micro reissue = the Nelsonic watch? If it doesn't happen on that, it would mean they fixed it on that version. It's not the same rom (not the same MCU type, even)

**Comment by einstein95** [comment]
> micro reissue = the Nelsonic watch? If it doesn't happen on that, it would mean they fixed it on that version. It's not the same rom (not the same MCU type, even)

I believe they mean the 1998 "Nintendo Mini Classics" release, unrelated to the Nelsonic watches
https://en.wikipedia.org/wiki/Nintendo_Mini_Classics

**Comment by famiclone6502** [comment]
@happppp Sorry, the Mini Classics version as @einstein95 mentioned.
