### ISSUE TITLE
MAME v0.174's Video Mode's setting setup with None value makes MAME not show anything at its startup.

### ISSUE THREAD

**Issue by antdude** [mamedev/mame#924]
If MAME v0.174's Video Mode's setting setup from Auto to None, then starting up MAME shows nothing in my very old updated Windows XP Pro SP3 machine. Had to reset this by editing its INI file.

**Comment by happppp** [comment]
That is expected, none means exactly none.
However, it would be friendlier if MAME warned the user if they change
video mode to none in the UI.

**Comment by antdude** [comment]
Thanks Happppp. So the only way to get GUI back is to edit the INI file? :(

**Comment by happppp** [comment]
At the moment yes, and don't change it to "none" again now that you know
what it does.

**Comment by antdude** [comment]
Thanks. Yeah, there is need to be a GUI way to fix that "none". ;)

**Comment by galibert** [comment]
If you deliberately disable the graphics, you'd better be able to reenable
them without graphics.

  OG.

**Comment by anikom15** [comment]
I didn't even know it was possible to change the video mode in the UI.

**Comment by NULUSIOS** [comment]
Your requests are even weirder than mine. hehehe

**Comment by antdude** [comment]
Ha, what are your requests like NULUSIOS? I am always weird!
