### ISSUE TITLE
0.240: validation error on s390x

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#9243]
Inspired by @cuavas' [comment](https://github.com/mamedev/mame/issues/3157#issuecomment-1026837746), I enabled validation on Fedora RPMs. This has uncovered an error on s390x:
```
./mame -validate
Driver apxen (file apxen.cpp): 2 errors, 0 warnings
Errors:
   Address Map Bank device 'mem': program space is big-endian but references little-endian region ':bios'
   Address Map Bank device 'mem': program space is big-endian but references little-endian region ':bios'
Validity check failed (2 errors, 0 warnings in total)
```

**Comment by ajrhacker** [comment]
635658ef4135eff3125c62be1147c749541fa609 should fix this for now.

**Comment by belegdol** [comment]
It does, build has succeeded: https://koji.fedoraproject.org/koji/taskinfo?taskID=82269305
