### ISSUE TITLE
gnw_dkjr. starting game not responsive after recent Wakeup after CEND change

### ISSUE THREAD

**Issue by squalldc** [mamedev/mame#9252]
I tested this on the latest official Mame0240b.

If you load the game (or after an ACL), press "TIME", then try pressing "GAME A", it takes many presses (seems random) before the game actually registers the button and starts the gameplay.

In previous versions (I've verified by rolling back the CEND change), the game starts every time after the first press.

**Comment by happppp** [comment]
Ok, I guess it means external wakeup (via K pins) is level triggered, not edge triggered.

**Comment by happppp** [comment]
It should be fixed now.
