### ISSUE TITLE
request: add CHIP-8 emulator to MAME (ROM proof)

### ISSUE THREAD

**Issue by pygamedev** [mamedev/mame#9260]
I see your mommy learned you to use Google. But she forgot to give you your ADHD pills...

Since you don't give any ROM as proof, as I predicted, I won't read your shit.

All CHIP-8 programs run on any CHIP-8 emulator, by exception the super chip ones.
The hardware doesn't matter.

Since you don't give any ROM, this is Closed...

**Comment by cuavas** [comment]
Once again, this is flat-out wrong:
* Native subroutine call op 0x0nnn is inherently tied to the host architecture
* Some hosts use different start addresses
* Behaviour of the undocumented shift operations varies between implementations
* Some games depend on quirks of particular interpreters

All that aside, you don't get to say what MAME should or shouldn't do. Enjoy your ban.
