### ISSUE TITLE
ep64_cass images are all invalid

### ISSUE THREAD

**Issue by mcfilmmakers** [mamedev/mame#9264]
The images for ep64_cass all contain invalid images. I assume they aren't in a format MAME is expecting?

**Comment by ICEknigh7** [comment]
Attaching image of MAME's error pop up window:
![image](https://user-images.githubusercontent.com/47050710/152623389-570f4b6f-fea8-453f-8e75-fd0f336b262c.png)

**Comment by Robbbert** [comment]
This is known. See https://mametesters.org/view.php?id=6839

Note from my cassette spreadsheet:
_Needs support for TAP files (MT 06839). Hangs on save. Crash on load._

So, this machine is not really usable for tapes.
