### ISSUE TITLE
m1 macbook no working

### ISSUE THREAD

**Issue by 1017189542** [mamedev/mame#9267]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               mame [96419]
Path:                  /Users/USER/Downloads/*/mame
Identifier:            mame
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        Exited process [96407]
Responsible:           Terminal [66636]
User ID:               501

Date/Time:             2022-02-05 21:26:51.9175 +0800
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        600DDD8A-8F00-6B3E-829F-4523B248FA96

Sleep/Wake UUID:       98D19952-8558-4D76-B27A-238F71595446

Time Awake Since Boot: 1600000 seconds
Time Since Wake:       5831 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [96419]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 4366942200
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1044a4000-10e424000    [159.5M] r-x/r-x SM=COW  ...nloads/*/mame

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   mame                          	       0x10b2aee38 ImGui::ShutdownDockContext() + 24
1   mame                          	       0x10b2fdb6c imguiDestroy() + 16
2   mame                          	       0x10b2fdb6c imguiDestroy() + 16
3   mame                          	       0x1076886d8 renderer_bgfx::exit() + 12
4   mame                          	       0x1076be878 sdl_osd_interface::window_exit() + 220
5   mame                          	       0x1076bad0c sdl_osd_interface::osd_exit() + 12
6   mame                          	       0x10a9317c8 running_machine::run(bool) + 992
7   mame                          	       0x107ad5398 mame_machine_manager::execute() + 516
8   mame                          	       0x1076cc3dc cli_frontend::start_execution(mame_machine_manager*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) + 524
9   mame                          	       0x1076cd8d0 cli_frontend::execute(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) + 96
10  mame                          	       0x107ad5fe8 emulator_info::start_frontend(emu_options&, osd_interface&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) + 48
11  mame                          	       0x1076bab9c main + 176
12  dyld                          	       0x116ce50f4 start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x1a57382bc start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1a57382bc start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1a57382bc start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1a57382bc start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000116c9b200   x2: 0x000000013d8a2400   x3: 0x0000000000000003
    x4: 0x0000000020000800   x5: 0x0000000000000026   x6: 0x0000000000000600   x7: 0x0000000000000000
    x8: 0x0000000000000002   x9: 0x0000000000000103  x10: 0x000000000072be00  x11: 0x0000000000bf3d01
   x12: 0x0000000000006b30  x13: 0x00000000ffff8003  x14: 0x00000000000004d1  x15: 0x0000000000006b30
   x16: 0x0000000309ac2aec  x17: 0x00000001a5552218  x18: 0x0000000000000000  x19: 0x000000013d7400e0
   x20: 0x00000001102e7828  x21: 0x0000000110874000  x22: 0x0000000000000001  x23: 0x0000000110535450
   x24: 0x000000016b95b728  x25: 0x0000000110535450  x26: 0x000000010ed94998  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016b955990   lr: 0x000000010b2fdb6c
    sp: 0x000000016b955970   pc: 0x000000010b2aee38 cpsr: 0x60000000
   far: 0x0000000000000008  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1044a4000 -        0x10e423fff mame (*) <ede82ec3-36e7-3b26-a75d-cec0d769ad45> /Users/USER/Downloads/*/mame
       0x116ce0000 -        0x116d3ffff dyld (*) <86a8ba48-8bb4-3b30-9cda-051f73c74f44> /usr/lib/dyld
       0x1a5736000 -        0x1a5742fff libsystem_pthread.dylib (*) <4786e19a-9312-38e6-80ef-9c1394548118> /usr/lib/system/libsystem_pthread.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 74
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=880.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=880.8M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          160K        6 
CoreAnimation                       16K        1 
CoreGraphics                        16K        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           230.6M       36 
MALLOC guard page                  192K       11 
MALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        5 
Stack                             10.1M        5 
VM_ALLOCATE                        1.0G        4 
__AUTH                            1919K      188 
__AUTH_CONST                      11.4M      347 
__DATA                            18.6M      334 
__DATA_CONST                      37.8M      350 
__DATA_DIRTY                       737K      121 
__FONT_DATA                          4K        1 
__LINKEDIT                       670.5M        5 
__OBJC_CONST                      1619K      156 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3088K        1 
__TEXT                           420.8M      366 
__UNICODE                          588K        1 
dyld private memory               7168K        3 
mapped file                       65.5M       20 
shared memory                      864K       15 
===========                     =======  ======= 
TOTAL                              3.2G     1984 
TOTAL, minus reserved VM space     2.6G     1984 

-----------
Full Report
-----------

{"app_name":"mame","timestamp":"2022-02-05 21:26:54.00 +0800","app_version":"","slice_uuid":"ede82ec3-36e7-3b26-a75d-cec0d769ad45","build_version":"","platform":1,"share_with_app_devs":1,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"81047C5B-58E7-4193-A011-E4FCEBCF3C2F","name":"mame"}
{
  "uptime" : 1600000,
  "procLaunch" : "2022-02-05 21:26:48.5231 +0800",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro17,1",
  "procStartAbsTime" : 40316679025920,
  "coalitionID" : 110436,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2022-02-05 21:26:51.9175 +0800",
  "incident" : "81047C5B-58E7-4193-A011-E4FCEBCF3C2F",
  "bug_type" : "309",
  "pid" : 96419,
  "procExitAbsTime" : 40316757385675,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "mame",
  "procPath" : "\/Users\/USER\/Downloads\/*\/mame",
  "parentProc" : "Exited process",
  "parentPid" : 96407,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "600DDD8A-8F00-6B3E-829F-4523B248FA96",
  "responsiblePid" : 66636,
  "responsibleProc" : "Terminal",
  "wakeTime" : 5831,
  "sleepWakeUUID" : "98D19952-8558-4D76-B27A-238F71595446",
  "sip" : "enabled",
  "vmRegionInfo" : "0x8 is not in any region.  Bytes before following region: 4366942200\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1044a4000-10e424000    [159.5M] r-x\/r-x SM=COW  ...nloads\/*\/mame",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000008","rawCodes":[1,8],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000008"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":96419},
  "ktriageinfo" : "VM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\n",
  "vmregioninfo" : "0x8 is not in any region.  Bytes before following region: 4366942200\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1044a4000-10e424000    [159.5M] r-x\/r-x SM=COW  ...nloads\/*\/mame",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":74},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":66928644,"threadState":{"x":[{"value":0},{"value":4677284352},{"value":5327430656},{"value":3},{"value":536872960},{"value":38},{"value":1536},{"value":0},{"value":2},{"value":259},{"value":7519744},{"value":12532993},{"value":27440},{"value":4294934531},{"value":1233},{"value":27440},{"value":13047180012},{"value":7068787224,"symbolLocation":0,"symbol":"default_zone_free_definite_size"},{"value":0},{"value":5325979872},{"value":4566448168,"symbolLocation":0,"symbol":"osd_common_t::s_window_list"},{"value":4572266496,"symbolLocation":3328,"symbol":"preload_buf"},{"value":1},{"value":4568863824,"symbolLocation":0,"symbol":"driver____empty"},{"value":6099941160},{"value":4568863824,"symbolLocation":0,"symbol":"driver____empty"},{"value":4544088472,"symbolLocation":0,"symbol":"vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >"},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4482653036},"cpsr":{"value":1610612736},"fp":{"value":6099917200},"sp":{"value":6099917168},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4482330168,"matchesCrashFrame":1},"far":{"value":8}},"queue":"com.apple.main-thread","frames":[{"imageOffset":115387960,"symbol":"ImGui::ShutdownDockContext()","symbolLocation":24,"imageIndex":0},{"imageOffset":115710828,"symbol":"imguiDestroy()","symbolLocation":16,"imageIndex":0},{"imageOffset":115710828,"symbol":"imguiDestroy()","symbolLocation":16,"imageIndex":0},{"imageOffset":52315864,"symbol":"renderer_bgfx::exit()","symbolLocation":12,"imageIndex":0},{"imageOffset":52537464,"symbol":"sdl_osd_interface::window_exit()","symbolLocation":220,"imageIndex":0},{"imageOffset":52522252,"symbol":"sdl_osd_interface::osd_exit()","symbolLocation":12,"imageIndex":0},{"imageOffset":105437128,"symbol":"running_machine::run(bool)","symbolLocation":992,"imageIndex":0},{"imageOffset":56824728,"symbol":"mame_machine_manager::execute()","symbolLocation":516,"imageIndex":0},{"imageOffset":52593628,"symbol":"cli_frontend::start_execution(mame_machine_manager*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)","symbolLocation":524,"imageIndex":0},{"imageOffset":52598992,"symbol":"cli_frontend::execute(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)","symbolLocation":96,"imageIndex":0},{"imageOffset":56827880,"symbol":"emulator_info::start_frontend(emu_options&, osd_interface&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)","symbolLocation":48,"imageIndex":0},{"imageOffset":52521884,"symbol":"main","symbolLocation":176,"imageIndex":0},{"imageOffset":20724,"symbol":"start","symbolLocation":520,"imageIndex":1}]},{"id":66928832,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":2}]},{"id":66928833,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":2}]},{"id":66928835,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":2}]},{"id":66928839,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":2}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4366942208,
    "size" : 167247872,
    "uuid" : "ede82ec3-36e7-3b26-a75d-cec0d769ad45",
    "path" : "\/Users\/USER\/Downloads\/*\/mame",
    "name" : "mame"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4677566464,
    "size" : 393216,
    "uuid" : "86a8ba48-8bb4-3b30-9cda-051f73c74f44",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7070769152,
    "size" : 53248,
    "uuid" : "4786e19a-9312-38e6-80ef-9c1394548118",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 7067598848,
  "size" : 3072180224,
  "uuid" : "a6162d66-93e3-3251-93cc-b11f7c8c830e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=880.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=880.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          160K        6 \nCoreAnimation                       16K        1 \nCoreGraphics                        16K        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           230.6M       36 \nMALLOC guard page                  192K       11 \nMALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        5 \nStack                             10.1M        5 \nVM_ALLOCATE                        1.0G        4 \n__AUTH                            1919K      188 \n__AUTH_CONST                      11.4M      347 \n__DATA                            18.6M      334 \n__DATA_CONST                      37.8M      350 \n__DATA_DIRTY                       737K      121 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       670.5M        5 \n__OBJC_CONST                      1619K      156 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3088K        1 \n__TEXT                           420.8M      366 \n__UNICODE                          588K        1 \ndyld private memory               7168K        3 \nmapped file                       65.5M       20 \nshared memory                      864K       15 \n===========                     =======  ======= \nTOTAL                              3.2G     1984 \nTOTAL, minus reserved VM space     2.6G     1984 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61ef3bd729647d394933a0a6"
      },
      "deploymentId" : 240000378
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000102
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61ae8d06da72d16a4beb762e"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000231
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro17,1, BootROM 7429.41.5, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Sep 13 2021 21:06:59 version 18.20.310.14.7.8.119 FWID 01-9d72ee4a
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by cuavas** [comment]
You need to describe the steps to trigger the crash and provide information about your configuration (e.g. video output module, etc.).

**Comment by rb6502** [comment]
This report contains no actionable information.  What is the macOS version, the MAME version, the command line used, etc?

**Comment by Robbbert** [comment]
Looks like he isn't coming back. Closing for now.
If he ever does return, it can be reopened.
