### ISSUE TITLE
User interface issues: deformed snap image and missing romset name.

### ISSUE THREAD

**Issue by baarreth** [mamedev/mame#9268]
- [ ] When I load/reload the UI on 0.240, the snap image is deformed. However, it go back to normal if I select other game in the list.

- [ ] Also, I can't see the romset name just below the game list. Now it is necessary to read that on the "Infos" tab. This is annoying if you are using the UI to find roms you never played, and using this info to create an external subset (my case).

I am using Linux (Xubuntu 20.04).

![image](https://user-images.githubusercontent.com/5972526/152654061-9f541a22-562f-44cd-81a8-48f1365c3a5e.png)

![image](https://user-images.githubusercontent.com/5972526/152654065-b9f1e940-05a8-4200-a0b2-b23e0b89b44d.png)

**Comment by cuavas** [comment]
We aren’t wasting a line for the system short name – having another menu item visible is more useful.  The snapshots not being scaled properly on window resize is addressed as of f8480ce3f64ef309dea2ad96321536ff032c0764.

**Comment by baarreth** [comment]
> We aren’t wasting a line for the system short name – having another menu item visible is more useful.

How about putting in the same line of the driver info?
Like "Driver is parent (crkdown)"

**Comment by cuavas** [comment]
No, it’s staying in the info tab.
