### ISSUE TITLE
INI not read in Windows 11

### ISSUE THREAD

**Issue by XLRT** [mamedev/mame#9269]
![signal-2022-02-02-000703_001](https://user-images.githubusercontent.com/68155235/152659069-d160d097-5ca6-4f2a-a453-ac0e34d25d59.jpeg)

**Comment by cuavas** [comment]
Please put a proper description of the issue in the issue text.

**Comment by XLRT** [comment]
It's simple enough and super easy to reproduce. Just read the image.

**Comment by rb6502** [comment]
The image isn't super accessible to contributors who require screen readers and the like.  For the best chance of getting your issue fixed, you should describe it in text, including the steps taken, command line used, and mame.ini contents.
