### ISSUE TITLE
new ROMs found for 8080bw

### ISSUE THREAD

**Issue by iz8dwf** [mamedev/mame#9279]
Hi all,
I've dumped a couple of romset from acquired PCBs sold as unknown. One is an italian Lunar Rescue clone made by Model Racing, but not all dumped ROMs match with the romident content.
The other one is an "Attack Force" running on what it seems a Sidam Invasion PCB (no marks, but layout is identical).
None of the ROMs match any romident.
If anyone is interested in these dumps, please contact me.

**Comment by f205v** [comment]
Hi, I would be interested in the dumps and in gathering some more info about the hardware they are running on.
I'm the maintainer for: www.citylan.it
please contact me via email: f205v . f205v @ gmail . com
(remove spaces)
