### ISSUE TITLE
MAME should let users do sub(folder/directorie)s in current ROMs folders.

### ISSUE THREAD

**Issue by antdude** [mamedev/mame#928]
I told my 32-bit MAME v0.174 to look at all files deeply in I:\MAME in my very old, updated Windows XP Pro SP3 machine's HDD (NTFS partitions). I had a couple sub(directorie/folder)s in there as shown in my uploaded screen shot/capture: http://s33.postimg.org/rqlvak9tr/My_MAMEstorage.gif ... When I saved and let MAME rescan, it didn't see them. I had to tell it each location to find them. :(

Thank you in advance. :)

**Comment by Tafoid** [comment]
To my knowledge MAME has never allowed for recursive folder structure like that.  To support such a recursive path would likely cause a lot of slowdown (especially on startup).  Each path that has roms needs to be explicitly defined in ROMPATH in your .ini file.  In your pictured case, you should only need two:

rompath            "i:\mame\mame roms";"i:\mame\mame software list roms"

You'll do yourself a favor in the end by shortening your folder names and getting rid of spaces - most people just use "roms" and "software" for simplicity.  If you have a space, the path needs to be in quotes but the UI should do this for you if selecting them.

**Comment by cuavas** [comment]
Supporting subdirectories causes problems with things like NTFS junction points where you can create an effectively infinite directory tree.  This isn't something MAME is likely to support any time soon.

**Comment by antdude** [comment]
Thanks guys. That's a bummer. I also noticed clrmamepro doesn't do recursive directories too. :(

**Comment by danielocdh** [comment]
There should be a way for this to be possible, maybe scan 1 level of subdirectories on the main roms path or make the depth configurable with the default being as it is now
