### ISSUE TITLE
game names "Leader Board" in arsystems.cpp

### ISSUE THREAD

**Issue by f205v** [mamedev/mame#9280]
In [arsystems.cpp](https://github.com/mamedev/mame/blob/master/src/mame/drivers/arsystems.cpp) the 3 games "**Leader Board**" are called "**Leader Board _Golf_**" in the manual.
Manual scan available here: www.citylan.it/immagini/leader_board_golf_manual.pdf

**Comment by angelosa** [comment]
Manual also mentions 4-way sticks. Is it a thing specifically for this game or for all Arcadia games?

**Comment by f205v** [comment]
I do not know, unfortunately.

**Comment by DavidHaywood** [comment]
most of these are ports of budget Amiga games, 4 way sticks as a rule seems unlikely, although given that the whole concept of the system did not care about the games, or how they played at all....
