### ISSUE TITLE
Miissing file for download old Mame

### ISSUE THREAD

**Issue by lollo78** [mamedev/mame#929]
Hi, I need Mame 0.78, but the file is missing
https://github.com/mamedev/historic-mame/releases/download/mame078/mame078b.zip
Could you help me please?

**Comment by stilett0** [comment]
Sure.

**Comment by Tafoid** [comment]
The migration of the binaries are a WIP to use GITHUB as the primary host.  AFAIK we have from 0.100 onward covered pretty well on mamedev.org.  Prior binaries will be added sooner or later.

For now, you can use [https://mirrors.xmission.com/mame/releases](url) 
Google provides other places too depending on the version searched for so long as you are accurate in your searches.

**Comment by lollo78** [comment]
Thx a lot!
