### ISSUE TITLE
Quizard 3 and Quizard 4 Rainbow are working

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#9313]
The CD-i updates in MAME 0.240 fixes Quizard 3 (v3.4, German, i8751 DE 132 D3) and Quizard 4 Rainbow (v4.2, German, i8751 DE 142 D3). The games did not hang anymore after starting a game. The MACHINE_NOT_WORKING flag for both games can be removed!
See:
https://git.redump.net/mame/commit/src/mame/drivers/cdi.cpp?id=a3cc6df3495d4fd390c51170acaeaafe267ad964
https://git.redump.net/mame/commit/src/mame/drivers/cdi.cpp?id=255e3d6f3f2796ec1ae5e724970465d938159c2e

**Comment by angelosa** [comment]
Somehow I feel like:
- [ ] Needing to manually press the CD-i play button every time for booting an Arcade game isn't convenient for obvious operator implications;
- [ ] Extensive QA-ing a quiz game in German with 1 continue only isn't exactly a thrilling experience unless somebody finds a cheat for correct answer buffer;

**Comment by cuavas** [comment]
They’re marked working now anyway.
