### ISSUE TITLE
Main & Media BD ID information

### ISSUE THREAD

**Issue by HyperScorpio** [mamedev/mame#9335]
Please add on each game system the official code from the Main and Media BD ID info for improvements on Dolphin Triforce Emulator. This is very important.
If is not possible please Write in the comments below all the codes.
Thank you!

https://github.com/mamedev/mame/blob/master/src/mame/drivers/triforce.cpp

Image Example.
Virtua Striker 2002 (Japan or Export?)

![Virtua Striker 2002 (Intro) Triforce Arcade Actual Hardware 1-7 screenshot](https://user-images.githubusercontent.com/30736913/155504950-31e55ab7-91e9-40ae-815b-61614b94a34c.png)

**Comment by angelosa** [comment]
If you think that a 6th gen console can be emulated by simply adding a serial number then I suggest you to change hobby entirely.
Doesn't cope with [user story requirements](https://www.backhub.co/blog/best-practices-for-using-github-issues), closing.

**Comment by HyperScorpio** [comment]
I did not think of that way we could emulate things, we just need the codes.
