### ISSUE TITLE
Solar Assault (ver UAA) won't start - "EEPROM parameter is illigal"

### ISSUE THREAD

**Issue by baarreth** [mamedev/mame#9345]
Mame 0.241 - rom slrasslt
Linux (Xubuntu 20.04)
![image](https://user-images.githubusercontent.com/5972526/155868033-5a58eb8d-7f57-4f1e-bb67-7fbe2753f0f2.png)

**Comment by Tafoid** [comment]
First run requires the standard Konami sequence to create a default NVRAM.
https://wiki.mamedev.org/index.php/FAQ:Games
Search for "Solar Assault"

> Error will show for 24G. Hold F2 then hit Reset F3. Continue holding F2 until the game creates the EEPROM and tells you to release it.
