### ISSUE TITLE
rainbow.cpp: DEC Rainbow 400k raw image won't get loaded correctly

### ISSUE THREAD

**Issue by qazmko1029** [mamedev/mame#9354]
Since MAME 0.230, all previous 400k raw floppy image for DEC Rainbow, which I was using properly before, won't get loaded. They can't be used to boot or read content in MS-DOS and I saw floppy format declaration get changed in 0.230 code, but I don't know what made this happen.
However, both TD0 and IMD format works fine.
[tested failed bootdisk image](https://mega.nz/folder/HcI3wC5S#plgy5r3it996G06_0rs-FA)

**Comment by cracyc** [comment]
fixed by https://github.com/mamedev/mame/commit/04098a63d5b2d5847d8e237668f4f6f06d63e5a6
