### ISSUE TITLE
cheatfind.lua - lua error in menu_callback....

### ISSUE THREAD

**Issue by DjDiabolik** [mamedev/mame#9364]
In the recent version of cheatfind.lua i obtain this error:
It's appears sometime a windows say "LUA ERROR in menu_callback" 
init.lua:1052:attempt to call a nill value (field '?').

It's fixable ?

**Comment by DjDiabolik** [comment]
I can add a screenshot of error here:

https://i.postimg.cc/SscDWggC/immagine.png

**Comment by cuavas** [comment]
* What exact version of MAME are you using?
* Did you update your plugins along with your MAME executable?
* What are the steps to reproduce the error?

**Comment by DjDiabolik** [comment]
@cuavas 
Ops sorry me............. I try to post all information you ask:
On my side i have tryed whit two different Mame whit same version 0.241....... i have used:
MameUI64 -> http://www.mameui.info/MAMEUI.7z
And official Mame 0.241 from here -> https://www.mamedev.org/release.html

Update my plugins........ apparently yes.
I have compare the RAW file init.lua here on github whit init.lua on my pc apparently it's the same and updated.

Step to reproduce ? Ok......

Simply open a game........ open a game and open "CheatFind" plugins. 
Now try to navigate from the menu option........ if you select "Return To previous Menu" this errors popped up.

**Comment by DjDiabolik** [comment]
@cuavas 

Are you tryed to found a fix ?

On my side i have tryed to comment out the line 1052 but at this point when you open CheatFind Plugins it's not possible to open everything. If you select "Start New Search" the search it's not opened.

Otherwise on Mame0.241 if you use mouse to select the option "Return to Previous Menu" this errors it's not appears..... it's only appears only if you use Keyboard and select this voice.......

I know it's a BAD English...... :(

**Comment by cracyc** [comment]
fixed by https://github.com/mamedev/mame/commit/ea0cdde1486ed0d22f0a7d814d548efeabb67a80

**Comment by DjDiabolik** [comment]
@cracyc yeah... now i need only to download the new lua files and replace my actual of 0.241 instead waiting the 0.242 contain the fix... correct ?

**Comment by cracyc** [comment]
Yes.

**Comment by DjDiabolik** [comment]
@cracyc hi..... i have applyed the newest cheatfind folder to my mameUI and official mame 0.241 and apparently all it's works and this error it's not appears anymore.

Anyway there's present another little issue/trouble.
When i'm using the CheatFind and i start a new search if i add some cheat for TESTING it apparently works.
But when i click on "Return to Previous Menu" there's no back to previous but it's report me to the main menu of mame....

It's normal ?

**Comment by cuavas** [comment]
> But when i click on "Return to Previous Menu" there's no back to previous but it's report me to the main menu of mame....
> 
> It's normal ?

Yes, from MAME’s point of view, all the menus presented by the plugin are the same menu, just showing different items.  “Return to Previous Menu” will always take you back to the plugin options menu.  A plugin may provide some other way to back up to the previous plugin menu if it wants.
