### ISSUE TITLE
[Big Fight - Big Trouble In The Atlantic Ocean] Sword is not displayed properly...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [mamedev/mame#9390]
Mame 0.241

it should be in the hand

![image](https://user-images.githubusercontent.com/12481242/157873601-8cf63e6c-417c-4110-99aa-26f0772ba5b4.png)

**Comment by happppp** [comment]
https://mametesters.org/view_all_bug_page.php
Prefered website for game bugs. On github, quick/low priority reports like these get lost in the forest quick.

However, this driver has the warning flag for MACHINE_IMPERFECT_GRAPHICS, unless it's a new regression it won't be accepted there either.

**Comment by BenjaminSiskoo** [comment]
Ok :)

**Comment by angelosa** [comment]
Lack of rotation support for sprites in the Tatsumi driver. 
Noted in [source](https://github.com/mamedev/mame/blob/f29cd1988c4d94a743323d8c5cf69f6639e56822/src/mame/drivers/tatsumi.cpp#L14) as the very first task, any weapon that is picked up in-game basically needs it, last time I bothered with the commented out code in video was crashing and it's most likely very special being Tatsumi we're talking about.
