### ISSUE TITLE
[hng64.cpp] Many Hyper Neo Geo 64 games have visual/audio issues. 

### ISSUE THREAD

**Issue by cooperate** [mamedev/mame#9395]
Two games that I have tested, Buriki One and Beast Busters: Second Nightmare have similar visual issues.  There are missing effects and issues with layering.  Sometimes 2D sprites will appear in front of other objects.  

On the audio side audio is either completely missing or being squashed as it sounds heavily filtered.

Here is an image of Buriki with the layering issues I'm experiencing.

https://i.imgur.com/67UMFbZ.png

**Comment by angelosa** [comment]
> heavily filtered.

Wrong, and that’s only the last two words. 

6th gen HW with 6 games on it, closing cause way off target about stuff already noted in source. 

Friendly editor’s note: one can write a novel about what the Buriki One does with the background PiP screen alone.

**Comment by cooperate** [comment]
@angelosa 

Sorry if the vernacular was incorrect, just trying to point out issues I've noted.  When it comes to emulation I really don't know the terminology.  Did a search for this system in the open issues and found nothing.  As long as they've already been identified it's all good!

**Comment by rb6502** [comment]
@cooperate You should see a red warning screen on startup that states that emulation of that system is not working.  That means that reporting bugs is unnecessary because we do not assert that the emulation is production-quality.
