### ISSUE TITLE
0.174 crashes to desktop when pressing 'Configure machine', Windows 10

### ISSUE THREAD

**Issue by DocRevelator** [mamedev/mame#941]
Fresh install, put ROMs in folder. They're all there and working. 'Configure Machine' in the UI and it works fine. Quit out and back in, though, and pressing that option causes the programme to crash and quit. 

It appears to be something to do with the 'Favourites' folder. Accessed via search it doesn't seem to occur.

**Comment by dankan1890** [comment]
Fixed.
