### ISSUE TITLE
Support for debug dip switches in Neo Geo driver

### ISSUE THREAD

**Issue by bbfe** [mamedev/mame#9413]
Can MAME add the option to enable the debug dip switches 1_1 -> 1_8 and 2_1 -> 2_8 so that we don't have to use something like the universe bios to enable them?

There are all kinds of interesting debug features in the games that can be activated:

https://www.neo-geo.com/wiki/index.php?title=Neo-Geo_Big_List_of_Debug_Dipswitches

**Comment by DavidHaywood** [comment]
they're SOFTWARE switches, not hardware, so no.  That's why you have to use the Unibios, it sets the switch in RAM.

**Comment by bbfe** [comment]
Does MAME support any debug bios?

**Comment by cuavas** [comment]
Just use a Lua script (autoboot or plugin) to trick the software.  There are lots of shiny Lua bindings for this kind of thing now.  They aren’t physical DIP switches.

**Comment by bbfe** [comment]
I think the address of debug dip is 0x1000000 and 0x40 would enable it, but I don't know what the syntax for adding that to a lua script is. I don't get why these options shouldn't be documented by MAME though.
