### ISSUE TITLE
Gradius III Title Screen Bug

### ISSUE THREAD

**Issue by PeladoFeo** [mamedev/mame#943]
According to [this video](https://www.youtube.com/watch?v=6GY32ovt0cI),
the title screen should say "PRESS START" if there is at least one credit.

**Comment by PeladoFeo** [comment]
That video... of course it was recorded from a real PCB.

**Comment by happppp** [comment]
We'd prefer if you post these kind of emulation bugs to
http://mametesters.org/ and not here :)

**Comment by mamehaze** [comment]
gut feeling is the video is an undumped revision.

**Comment by Robbbert** [comment]
This has been transferred to https://mametesters.org/view.php?id=7850
