### ISSUE TITLE
Can't get clean integer tiles in F4 "GFX/Tilemap Viewer" after commit 4f495994c41cd2fbaf89c08f755e828ae3261828

### ISSUE THREAD

**Issue by BPzeBanshee** [mamedev/mame#9451]
As the statement says. Old behaviour prior to this commit was that I could at least hit the zoom out button enough times in say, `rdft`, and actually get a grid of 16x16 tiles. I can no longer seem to do that anymore, it seems to just zoom out into oblivion with no clear indicator which zoom value is 1.0. I get the desire to make the controls more like that of web browsers, but web browsers will tell you what size is 100%.

A button to actually just show a grid of tiles at their original size without scaling artifacts would be nice too (and would somewhat match behaviour on zooming out prior to this commit change, which makes everything autoscale without defined zoom values). It seems like the UI Reset button is supposed to do this, but all it does is set the amount of row/columns to 16 without any consideration for zoom size.

Alternatively, saving them to file in their original form based off selected palette would be nice to have, but from past history I'm told it's outside project scope and most forks I've seen that do this are out of date or closed-source.

**Comment by cuavas** [comment]
I can’t reproduce this.  When I use the zoom keys on the tilemap display, MAME shows the current zoom factor in a popup message after each change, and you can see unity zoom happen:

![image](https://user-images.githubusercontent.com/9678431/159416864-a8427062-ac7e-4da4-a177-1e2ccc915216.png)
![image](https://user-images.githubusercontent.com/9678431/159416893-51ee40e7-0153-4531-a147-8354a1e89cb9.png)
![image](https://user-images.githubusercontent.com/9678431/159416916-f209a60e-50bb-4c19-bfe0-6e67b41cee07.png)
