### ISSUE TITLE
Floating point exception in v9938.cpp

### ISSUE THREAD

**Issue by EtchedPixels** [mamedev/mame#9501]
From a crash in the genmod emulator where my buggy code basically ended up fuzzing the 9938 by just loading random crap into it in a loop

Thread 1 "mame" received signal SIGFPE, Arithmetic exception.
0x000055555fde1870 in v99x8_device::command_unit_w () at ../../../../../src/devices/video/v9938.cpp:3010
3010			m_mmc.NX = ((m_cont_reg[40]+((int)m_cont_reg[41]<<8)) & 1023)/PPB[SM];
Missing separate debuginfos, use: dnf debuginfo-install SDL2-2.0.20-1.fc34.x86_64 SDL2_ttf-2.0.15-7.fc34.x86_64 adwaita-qt5-1.4.1-3.fc34.x86_64 alsa-lib-1.2.6.1-3.fc34.x86_64 at-spi2-atk-2.38.0-2.fc34.x86_64 at-spi2-core-2.40.3-1.fc34.x86_64 atk-2.36.0-3.fc34.x86_64 bzip2-libs-1.0.8-6.fc34.x86_64 cairo-1.17.4-3.fc34.x86_64 cairo-gobject-1.17.4-3.fc34.x86_64 dbus-libs-1.12.20-3.fc34.x86_64 elfutils-libelf-0.186-1.fc34.x86_64 expat-2.4.6-1.fc34.x86_64 flac-libs-1.3.3-7.fc34.x86_64 fontconfig-2.13.94-5.fc34.x86_64 freetype-2.10.4-3.fc34.x86_64 fribidi-1.0.10-4.fc34.x86_64 gdk-pixbuf2-2.42.6-1.fc34.x86_64 glib2-2.68.4-1.fc34.x86_64 glibc-2.33-21.fc34.x86_64 graphite2-1.3.14-7.fc34.x86_64 gsm-1.0.19-5.fc34.x86_64 gtk3-3.24.30-1.fc34.x86_64 harfbuzz-2.7.4-3.fc34.x86_64 libICE-1.0.10-6.fc34.x86_64 libSM-1.2.3-8.fc34.x86_64 libX11-1.7.2-3.fc34.x86_64 libX11-xcb-1.7.2-3.fc34.x86_64 libXScrnSaver-1.2.3-8.fc34.x86_64 libXau-1.0.9-6.fc34.x86_64 libXcomposite-0.4.5-5.fc34.x86_64 libXdamage-1.1.5-5.fc34.x86_64 libXext-1.3.4-6.fc34.x86_64 libXfixes-6.0.0-1.fc34.x86_64 libXi-1.7.10-6.fc34.x86_64 libXrender-0.9.10-14.fc34.x86_64 libXxf86vm-1.1.4-16.fc34.x86_64 libasyncns-0.8-20.fc34.x86_64 libbrotli-1.0.9-4.fc34.x86_64 libcloudproviders-0.3.1-3.fc34.x86_64 libdatrie-0.2.13-1.fc34.x86_64 libepoxy-1.5.9-1.fc34.x86_64 libffi-3.1-28.fc34.x86_64 libgcc-11.2.1-9.fc34.x86_64 libgcrypt-1.9.3-3.fc34.x86_64 libglvnd-glx-1.3.3-1.fc34.x86_64 libgpg-error-1.42-1.fc34.x86_64 libicu-67.1-7.fc34.x86_64 libjpeg-turbo-2.0.90-3.fc34.x86_64 libmount-2.36.2-1.fc34.x86_64 libogg-1.3.4-4.fc34.x86_64 libpng-1.6.37-10.fc34.x86_64 libselinux-3.2-1.fc34.x86_64 libstdc++-11.2.1-9.fc34.x86_64 libuuid-2.36.2-1.fc34.x86_64 libvorbis-1.3.7-3.fc34.x86_64 libwayland-client-1.20.0-1.fc34.x86_64 libwayland-cursor-1.20.0-1.fc34.x86_64 libwayland-egl-1.20.0-1.fc34.x86_64 libxcb-1.13.1-7.fc34.x86_64 libxkbfile-1.1.0-6.fc34.x86_64 libxklavier-5.4-18.fc34.x86_64 libxml2-2.9.13-1.fc34.x86_64 libxshmfence-1.3-8.fc34.x86_64 llvm-libs-12.0.1-1.fc34.x86_64 mesa-dri-drivers-21.1.8-3.fc34.x86_64 ncurses-libs-6.2-4.20200222.fc34.x86_64 pango-1.48.11-1.fc34.x86_64 pcre-8.44-3.fc34.1.x86_64 pcre2-10.36-4.fc34.x86_64 pipewire-jack-audio-connection-kit-0.3.40-1.fc34.x86_64 pipewire-libs-0.3.40-1.fc34.x86_64 portaudio-19-34.fc34.x86_64 portmidi-217-39.fc34.x86_64 pugixml-1.11.4-2.fc34.x86_64 qgnomeplatform-qt5-0.8.4-5.fc34.x86_64 qt5-qtbase-5.15.2-30.fc34.x86_64 qt5-qtbase-gui-5.15.2-30.fc34.x86_64 qt5-qtx11extras-5.15.2-3.fc34.x86_64 sqlite-libs-3.34.1-2.fc34.x86_64 sssd-client-2.5.2-2.fc34.x86_64 systemd-libs-248.10-1.fc34.x86_64 utf8proc-2.6.1-2.fc34.x86_64 xcb-util-keysyms-0.4.0-15.fc34.x86_64 xcb-util-wm-0.4.1-20.fc34.x86_64 zlib-1.2.11-26.fc34.x86_64
(gdb) where
#0  0x000055555fde1870 in v99x8_device::command_unit_w(unsigned char) ()
    at ../../../../../src/devices/video/v9938.cpp:3010
#1  0x000055555fde1c6d in v99x8_device::register_write(int, int) ()
    at ../../../../../src/devices/video/v9938.cpp:896
#2  0x000055555fde1ef8 in v99x8_device::command_w(unsigned char) ()
    at ../../../../../src/devices/video/v9938.cpp:573
#3  v99x8_device::command_w(unsigned char) ()
    at ../../../../../src/devices/video/v9938.cpp:566
#4  0x000055555d8a7d26 in geneve_state::memwrite(unsigned int, unsigned char)
    () at ../../../../../src/mame/drivers/geneve.cpp:650
#5  0x000055555f4738b0 in tms9995_device::mem_write() ()
    at ../../../../../src/devices/cpu/tms9900/tms9995.cpp:2016
#6  0x000055555f475a2b in tms9995_device::execute_run() ()
    at ../../../../../src/devices/cpu/tms9900/tms9995.cpp:1254
#7  0x0000555561416306 in device_execute_interface::run() ()
    at ../../../../../src/emu/diexec.h:190
#8  device_scheduler::timeslice() () at ../../../../../src/emu/schedule.cpp:496
#9  0x00005555613b75f0 in running_machine::run(bool) ()
    at ../../../../../src/emu/machine.cpp:329
#10 0x000055555dcf211e in mame_machine_manager::execute() ()
    at ../../../../../src/frontend/mame/mame.cpp:270
#11 0x000055555dd90753 in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
    at ../../../../../src/frontend/mame/clifront.cpp:274
#12 0x000055555dd90952 in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () at ../../../../../src/frontend/mame/clifront.cpp:290
#13 0x000055555dcefa5a in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
    at ../../../../../src/frontend/mame/mame.cpp:401
#14 0x0000555559ca0de3 in main() ()
    at ../../../../../src/osd/sdl/sdlmain.cpp:219

**Comment by ajrhacker** [comment]
c127f891cbb2a6d86f4a8efd319947a4bf9ea4d2 should fix this. Can you confirm?

**Comment by EtchedPixels** [comment]
Well it was kind of random so I can't be 100% sure but it seems to
