### ISSUE TITLE
apple2e driver - disabled Zip Chip incorrectly re-enabled by timer

### ISSUE THREAD

**Issue by inexorabletash** [mamedev/mame#9503]
The IIc+ and non-IIc+ Zip Chip emulation differ in how writes to C05A/C05B affect the accelerator's behavior in response to temporary slowdowns. When disabling the accelerator through a write to C05A, the IIc+ version sets the `m_accel_fast` flag to false; the non-IIc+ version does not. The consequence of this is that when the temporary slowdown timer fires, the IIc+ accelerator remains disabled, but non-IIc+ accelerator gets re-enabled!

Repro in 6502 code:

```
  LDA #$5A
  STA $C05A
  STA $C05A
  STA $C05A
  STA $C05A ; unlock
  LDA #$00  ; anything but 5A and A5
  STA $C05A ; disable
  LDA #$A5
  STA $C05A ; lock

  STA $C070 ; trigger gameio timer
```

Verified (second hand, c/o @apple2geek) on a real IIe w/ Zip Chip, the above should leave the accelerator disabled when the 5ms timer fires. Note that the behavior should be the same regardless of whether the C070 access happens _before_ or _after_ the unlock/disable/lock (again, verified second hand on actual hardware).

From code inspection, the fix is likely to just be copying the two `m_accel_fast = ...;` lines from the IIc+ code into the normal code, for the 0x5a and 0x5b cases. 

cc @rb6502 @peterferrie

**Comment by rb6502** [comment]
Thanks for the report!  I already have a preliminary fix, but nothing good comes of git commits after midnight so I'm not going to push it quite yet. 😅

**Comment by rb6502** [comment]
Should be all set, that was definitely an oversight.  I will be getting to the Franklin function keys hopefully soon too.
