### ISSUE TITLE
Can't change tabs by clicking or double clicking on it

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#9522]
OS: Windows 10 and Debian Linux 11.0 (Bullseye)
mame: `0.242 (mame0242-142-gff4daf378ab)`

Download [history](https://www.arcade-history.com/), [commands](https://www.progettosnaps.net/command/), [mameinfo](https://mameinfo.mameworld.info/).
Run `mame -norc -rompath h:\roms sf2`, press `TAB > External DAT view`, you can see 3 tabs with their specific information, when you click at any of the 3 tabs, you can see the selection of the tab at the top and the DAT revision at the bottom of the screen, however, it doesn't load the respective DAT information page.

Bellow you can see that mame loads the commands tab and if you click or double click at mameinfo tab, it still displays the commands information page.
![image](https://user-images.githubusercontent.com/80734530/162016204-48a02d72-cbfd-4311-a96d-fcd66a199d01.png)

**Comment by cd4053** [comment]
> Correct, the tabs are not clickable.

I'll stop posting this stuff here, there is no way for a regular user to know what is or isn't with mame.

**Comment by cuavas** [comment]
I agree the internal UI isn’t as intuitive or consistent as it should be, but there’s no point keeping an issue open when the code is behaving as originally intended.  MAME has never responded to clicks on the headings on that screen, there’s no code to support it.  It isn’t a bug that clicking does nothing.

**Comment by cuavas** [comment]
Actually, maybe I’m misremembering, let me check the code.

**Comment by cuavas** [comment]
They’ll be clickable in 0.243 – hopefully you can wait a few weeks.

**Comment by cd4053** [comment]
Thank you @cuavas ❤
