### ISSUE TITLE
timetrv: DIP switch menu - difficulty switches don't toggle correctly

### ISSUE THREAD

**Issue by Arjak89** [mamedev/mame#9524]
Version tested: 0.242 (Windows)

Problem: In the dip switch menu for Time Traveler, when selecting the difficulty options you cannot select "Very Difficult." Pressing Right when Difficult is selected simply wraps around back to Medium.

**Comment by happppp** [comment]
should be fixed with https://github.com/mamedev/mame/commit/99657d0cbf7cdec3592e3c30d9a5ac839d08d62c
