### ISSUE TITLE
mame fails to build with glibc-2.23.90

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#953]
Mame does not build with glibc-2.23.90 from Fedora rawhide due to [1]:

> Precompiling src/emu/emu.h...
> g++    -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util  -m64 -pipe -Wno-deprecated-declarations -O2 -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Winvalid-pch -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-unused-result -Wno-array-bounds -m64 -x c++ -std=c++14 -Woverloaded-virtual -Wsuggest-override -x c++-header -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util -o "../../../../linux_gcc/obj/x64/Release/emu.h.gch" -c "../../../../../src/emu/emu.h"
> Compiling src/emu/drivers/empty.cpp...
> g++    -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DXMD_H -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util  -m64 -pipe -Wno-deprecated-declarations -O2 -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Winvalid-pch -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-unused-result -Wno-array-bounds -m64 -x c++ -std=c++14 -Woverloaded-virtual -Wsuggest-override -include ../../../../linux_gcc/obj/x64/Release/emu.h -o "../../../../linux_gcc/obj/x64/Release/src/emu/drivers/empty.o" -c "../../../../../src/emu/drivers/empty.cpp"
> cc1plus: warning: ./../../../../linux_gcc/obj/x64/Release/emu.h.gch: not used because `__malloc_initialize_hook' is poisoned [-Winvalid-pch]
> cc1plus: error: one or more PCH files were found, but they were invalid
> cc1plus: fatal error: ../../../../linux_gcc/obj/x64/Release/emu.h: No such file or directory
> compilation terminated.

emu.h.gch seems to be generated by genie, where should this be fixed?
[1] http://patchwork.sourceware.org/patch/12488/

**Comment by rb6502** [comment]
@belegdol is this still a problem?  We're up to F25 now and MAME builds fine.

**Comment by belegdol** [comment]
Hi,
yes it is working and it has been for a while, sorry for not updating the ticket. It was a problem during the package review but it seems to have been resolved on its own.
