### ISSUE TITLE
Apple IIGS (apple2gsr1) erratic joystick input on Rastan

### ISSUE THREAD

**Issue by yoshisuga** [mamedev/mame#9530]
MAME version: 0.242

When playing with joystick controls on Rastan for the Apple IIGS (`-gameio joy`), the joystick seems to be moving on its own and end up exhibiting jerking behavior when the joystick is in idle/centered position.

Command:
```
mame64 apple2gsr1 -skip_gameinfo -nosamples -window -nomax -gameio joy -flop3 '/path/to/rastan (1990)(taito)(us)(disk 1 of 2)[cr][t][b].2mg' -flop4 '/path/to/rastan (1990)(taito)(us)(disk 2 of 2)[cr][t][b].2mg'
```

I used the disk images from the `apple2gs_flop_misc` software list for `rastan`.

I'm not doing anything with joystick input in this gif:

![Apr-07-2022 15-01-10](https://user-images.githubusercontent.com/564774/162342963-696aae52-1416-4905-bbab-ee115f521f17.gif)

I suspect it might be a timing issue - running this at stock speed (no acceleration)

**Comment by ksherlock** [comment]
I tracked down the leftward motion - 

MAME currently triggers the joystick on all $c070-$c07f accesses (with a TODO comment to verify if that's how a IIgs behaves).  As it so happens, $c071-$c07f is also the location of the COP, BRK, ABORT, and (more importantly) IRQ vector handler code.  Sound or possibly scanline IRQs trigger the paddle read timer which leads to x/y being underreported and thus the leftward motion.

With the recent timing tweaks and not triggering on $c071-$c07f, Rastan is playable.

**Comment by rb6502** [comment]
23904ff is in that fixes this, and I've verified that Rastan now plays correctly with a joystick.

**Comment by yoshisuga** [comment]
Thanks so much @rb6502 ! I verified the fix and it's working perfectly! And thanks to @ksherlock, John Brooks and others for describing how the timing should work. I learned a lot!
