### ISSUE TITLE
Disk IO broken for COCO?

### ISSUE THREAD

**Issue by debmint** [mamedev/mame#9532]
Installed mame 0.241 on Manjaro (Arch Linux).  I scp'd my mame directory from a Linux Mint install using mame-0.228.  I had to change a few paths, but everything looked alright.  When I tried to start a session, I got the following error:

`While parsing $HOME/.mame/coco3h.ini:
Warning: unknown option in INI: record_timecode
wd177x_format: Number of tracks in image file too high for floppy drive (80 > 42)
Fatal error: Device 5.25" double density floppy drive load failed: Incompatible image format or corrupted data`

I then downgraded to mame-0.229, trying to match as closely as possible the Mint install, and this was the earliest version in the arch package archive where they had mame-tools.  This ran without problems with no changes to the existing mame config in my home directory
This was an 80-track floppy that I tried to boot, but I tried a nos9 disk I had - it was 40 tracks:

`os9 id ~/.mame/software/nos96309l2v030300coco3_40d_1.dsk 

LSN0 Information:
  Total sectors   :   1440
  Track size      :   18
  Bytes in bitmap :   180
  Sectors/Cluster :   1
  Root dir sector :   2
  Disk owner      :   0.0  
  Disk attributes :   dsewrewr
  Disk ID         :   $180
  Disk format     :   $3 (48 TPI, Double Density, Double Sided)
  Sectors/track   :   18
  Boot sector     :   12
  Bootfile size   :   22620
  Creation date   :   07/02/2019 14:29
  Disk name       :   NitrOS-9/6309 Level 2 Disk 1
  Bytes/Sector    :   256`

It would not load with 241.  IIRC, it claimed that disk contained 60 or so tracks.

It may be that you're not supposed to boot an 80-track drive, and earlier versions just let you get away with it and now catches the error.  I'm just wondering if this is an enhancement or a bug.

**Comment by tlindner** [comment]
It's an enhancement. The previous versions of MAME defaulted to an 80+ track disk drive. But it was changed to reflect what almost all people had at the time. Use `-listslots` command line option to view where in the slot structure you can set the drive to be a quad density drive: `525qd`.

**Comment by debmint** [comment]
> It's an enhancement. The previous versions of MAME defaulted to an 80+ track disk drive. But it was changed to reflect what almost all people had at the time. Use `-listslots` command line option to view where in the slot structure you can set the drive to be a quad density drive: `525qd`.

Thanks for the reply.  I sort of suspected this might be the case.

**Comment by npwoods** [comment]
In case it wasn't clear, its pretty easy to configure MAME to emulate a quad density drive, and I believe you can add this to the MAME.ini.

**Comment by angelosa** [comment]
I don't see anything wrong here, closing.
