### ISSUE TITLE
PIC16C5X tri-state ports

### ISSUE THREAD

**Issue by Paul-Arnold** [mamedev/mame#9534]
Hi,
I’ve been looking at the pic16c54 emulation, in particular the tri-state status of a port.
Although a user callback function is called when a port changes the user has no way of knowing which bits are valid outputs and which are set as inputs.
This isn’t a problem if the port bits never change but on the board I’m looking at they do.
The pic is used as a I2C device.

what’s the best way of resolving this ?
Add a function which I call to get the tri-state value ?
Or should the mask bits in the callback indicate this?
The callback currently looks like this…
m_write_b(PIC16C5x_PORTB, data & (uint8_t)(~m_TRISB), 0xff);

Thanks
Paul

**Comment by cuavas** [comment]
If you’re using a `devcb_write8` or whatever (which you should be), you can pass the mask of the actively driven lines in the third argument.  The MC68705 devices do this – see `m6805_hmos_device::port_cb_w`.

**Comment by cuavas** [comment]
In fact, in the line you’ve pasted there, you can see it’s currently passing `0xff` for the third argument – just put your tristate mask there instead.

**Comment by Paul-Arnold** [comment]
Thanks for your reply.
That was my original thinking, pass the tristate mask as the third argument so the above call is changed to
m_write_b(PIC16C5x_PORTB, data & (uint8_t)(~m_TRISB), (uint8_t)(~m_TRISB));

**Comment by cuavas** [comment]
Addressed by 0a18e664630af3aa977c93c0a8504939b68e3552 (#9970).
