### ISSUE TITLE
the new Apple2_flop_orig 0.242 roms are invalid

### ISSUE THREAD

**Issue by mcfilmmakers** [mamedev/mame#9543]
The overwhelming majority of the new 0.242 apple2_flop_orig roms added are in fact invalid images in the Apple II machines  but they're all marked as working.

However, they do work in the Apple IIgs machine. Are we sure these aren't Apple IIgs roms?

**Comment by Firehawke** [comment]
Can you specify two or three that you're not able to get working on older machines?

**Comment by mcfilmmakers** [comment]
Sure:
Basically any of the MECC 3.5 disks such as (they all start with mc and there are quite a few):
mchistmakr35
mcjennyj35

Some only get to a black screen such as:
hmsimpet

**Comment by rb6502** [comment]
mame apple2ee -sl7 superdrive -flop3 mchistmakr35 works fine for me.
Ditto mame apple2gs mchistmakr35.

**Comment by mcfilmmakers** [comment]
yeah the AppleIIgs isn't the problem, it was the regular Apple II. I'm used to running 3.5" disks from apple2cp. But I can confirm that using the superdrive with the apple2ee does work. Thank you.

**Comment by rb6502** [comment]
apple2cp's 3.5" drive is still the old code and doesn't support all the image types the new one does.  I hope to have the issues with it ironed out soon.

**Comment by cuavas** [comment]
At any rate, the issue as reported is invalid.  The vast majority of the floppy images are *not* invalid.
