### ISSUE TITLE
The Speed Rumbler (srumbler) wrong audio tempo

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#9595]
Currently the driver uses a fixed 240Hz interrupt for the music tempo. In reality the game uses the interrupt signal coming from one of the FM chips. The measured frequency of that interrupt is 250Hz. That difference is why the intro music is cut in MAME when the intro scene ends. Both the scene and the music finish at the same time when 250Hz is used instead.

Although the music will sound at the right tempo by replacing 240 by 250 in the MAME driver, the correct change is to connect the interrupt line to the Z80.

**Comment by happppp** [comment]
Thanks, should be fixed with https://github.com/mamedev/mame/commit/6d3c4ff49a52a814ac3fa8f63ffad36406b5bab7

**Comment by jotego** [comment]
That's exactly what was needed. Thanks a lot.
