### ISSUE TITLE
goldnaxe: DIP switch order wrong 

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#9602]
It looks like _easier_ and _easy_ are swapped in order, as _harder_ and _hard_ are too. If you go into the test mode (press F2) and then into the DIP switch assignments (move the cursor and press F2 again) you will see that the way the game refers to the options is not what MAME's OSD shows. Check out the image below, where the OSD says easier but the game screen shows easy. If you move then to _easy_, the game will show _easier_.

It probably happens in other Golden Axe sets. I have only tested the main one **goldnaxe**.

![imagen](https://user-images.githubusercontent.com/1863036/164390827-b714e4d8-4c77-485c-b386-d07afe6a2c0d.png)

**Comment by happppp** [comment]
should be in the correct order now https://github.com/mamedev/mame/commit/ad1f6584d52a870576b5e3997bd77c729e3d3425
