### ISSUE TITLE
No keyboard working after run a rom on PowerPC

### ISSUE THREAD

**Issue by tlosm** [mamedev/mame#963]
Im facing this issue, 2 days ago mame 0.174 build and keyboard was only working if i was run from tty mame -window romname ... from yesterday build the keyboard is not working fom gui and from tty console

**Comment by bradhugh** [comment]
What OS?

**Comment by tlosm** [comment]
Linux Ubuntu Mate 16.10

**Comment by bradhugh** [comment]
Hmm, I'm not able to repro. Are you running in Window mode or fullscreen mode?  Can anyone else out there repro or have any ideas how to?

**Comment by tlosm** [comment]
Both and the same issue.
The strange mouse pointer work in the gui and i can search a rom from the search form. but keyboard dont work when a rom is loaded.

**Comment by Tafoid** [comment]
To OP,
Am I to understand 0.174 worked for you for a time, then didn't?  Doesn't that point more to either a local system configuration problem or maybe an update gone awry?  Do you have other keyboards to test that might be non-USB and are supported by your system.  Does the OS/GUI for Mate have an on-screen keyboard which can be used with the mouse?

**Comment by bradhugh** [comment]
Have you tried a clean ini file?  If that were the problem, I'm not thinking the UI events would work if the keyboard device wasn't working though.  If I put together a build with a ton of tracing in it would you be able to clone, compile and run to help debug this?

**Comment by tlosm** [comment]
Tafoid, used on screen keyboard nothing change.
cleaned my ini files nothing changed 
Bradhugh ... why not , i will build it if help

**Comment by bradhugh** [comment]
I've added some additional traces (and fixed a minor bug where exit() was getting called twice).  The fix is available in https://github.com/bradhugh/mame/tree/sdlinput_trace.  Please build this and repro the issue with -verbose enabled.

git clone https://github.com/bradhugh/mame.git input_test
cd input_test
git checkout sdlinput_trace
make <options you prefer, SOURCES= or SUBTARGET=>
repro while running with -verbose

**Comment by tlosm** [comment]
Bradhugh here is 
[mame1.txt](https://github.com/mamedev/mame/files/333041/mame1.txt) loaded rom from gui
[mame2.txt](https://github.com/mamedev/mame/files/333042/mame2.txt) loaded rom ferom tty

same issue

**Comment by bradhugh** [comment]
Ok, this is helpful. Are you running 32-bit Ubuntu Mate? (The size of the pointer traces seem to say yes).  If so, maybe I can try that to get a repro.  It looks like SDL is truly just giving us no events for your keyboard.

**Comment by tlosm** [comment]
hi Bradhug, yes it is on 32 bit , brecause ubutus are only 32bit os on powerpc,fedora and suse are 64bit . when i will have spare time will install and check mame there too if can help the developing .

**Comment by bradhugh** [comment]
I can try Ubuntu Mate 32-bit and see if I repro. Hopefully i386 won't make a difference versus PowerPC.

**Comment by bradhugh** [comment]
Actually, I just updated this branch with another trace and a potential fix. I saw that I was assuming the SDL_EventType enum was the same size as int on all platforms and that may not be true.  Can you do a git pull to grab the lastest, compile and test again?  In the meantime, I'll be working on an Ubuntu 32-bit repro.

**Comment by tlosm** [comment]
Yes Bradhugh i will clone last git and build it no problem. did you will need the verbose too ?

**Comment by bradhugh** [comment]
Sure, yes, has one extra trace that will help confirm.

**Comment by bradhugh** [comment]
It looks like on Ubuntu Mate 32-bit for i386 I cannot repro. I'm guessing this must be some bug that really only manifests on PowerPC. I guess I need to buy one :)

**Comment by tlosm** [comment]
you dont need use
qemu-system-ppc ;-) 
im using a beta machine with last P5020 e5500 core not on market for now ... hope soon

**Comment by tlosm** [comment]
Bradhugh i been buil the official git and nothing change i have build your repo?

**Comment by bradhugh** [comment]
I integrated some fixes into the main repo, but I suppose they don't fix your issue. I will update that same branch you previously synced with one more round of tracing.  After knowing whether we do or don't get events directly from SDL, I'm not sure there's much else we can do.  I'll work on this tracing tonight and let you know when it's in so you can try one last round.

**Comment by bradhugh** [comment]
I updated the sdinput_trace branch on my repository with traces that are as close to SDL as we can get.  If you've still got the previous copy of this branch, the build should be quick if you just do "git pull" to grab the latest changes, then build.  This one will be very noisy but if it doesn't show events coming from SDL, I'll have to assume it's some sort of SDL bug.

**Comment by tlosm** [comment]
hi bradhugh, 
i will build it again time is relative with -j2 it will need 2 h for building  and isnt a problem.
If we find is an sdl issue i will ask the sdl2 ppc  manteiners to check it  , in case i will need your help for explain where the issue can be present. I know on Amigaos FE, the devs fixed something about input device on sdl2 becasue on dosbox there was wrong input signals.
I hope finally we will have mame 0.174 run becasue i will notice the ubuntu ppc maintainers for include it in main ppa.

**Comment by tlosm** [comment]
edit mame 0.174 is on mainstream https://launchpad.net/ubuntu/+source/mame/0.174-0ubuntu1 
i will test it too.. and report if something differ  about sefl build

**Comment by tlosm** [comment]
the proposed ubuntu mame have the bug ... start building your repo

**Comment by bradhugh** [comment]
Cool, I was able to actually get access to a Mac G5 where I was able to install Ubuntu Mate PowerPC.  It appears based on my build that it's building ppc64 - is that what yours is doing too?  Sorry, I've never compiled Linux/PowerPC before - do you have to specify any special parameters on MAME to make it build, or is it just "make"?

**Comment by tlosm** [comment]
great news.
yes im using mate here.
nano makefile
set bigendian=1
targetos linux 

Ps:build and tested your last mouse input work but keyboard not. lets hope :-)

**Comment by bradhugh** [comment]
Ok, good news. I can repro on the PowerPC build. I will investigate on my end and work on a fix.  Thanks for helping narrow this down.

**Comment by bradhugh** [comment]
Ok, I've got the fix.  I'll be working on it but it likely won't make the build we're about to ship.  I'll get it in before the next one.

**Comment by tlosm** [comment]
Great!,
Bradhugh was more an endianess in mame code or something missing/wrong in sdl2 ? in case i will ask to fix sdl2 code to the manteiners

**Comment by bradhugh** [comment]
Bug in mame code that only manifested on big endian. Working on it now.

**Comment by tlosm** [comment]
Thanks Brad, i will wait your ok for start the download the git and check it :+1:

**Comment by bradhugh** [comment]
This should be fixed now in the main mame repo. Feel free to pull the latest and test.

**Comment by tlosm** [comment]
Confirmed  mame 0.174 working on AmigaOne X5000 :+1: 
thanks for you help!
