### ISSUE TITLE
Typo in 'Head On N' ROM_START

### ISSUE THREAD

**Issue by MASHinfo** [mamedev/mame#9631]
There is a cut-n-paste error in the ROM_START for Head On N (headonn, vicdual.cpp).
The control PROM prom.b6 has the same checksum (67104ea9) as the color prom prom.g2:
-
	ROM_REGION( 0x0020, "proms", 0 )
	ROM_LOAD( "prom.g2", 0x0000, 0x0020, CRC(67104ea9) SHA1(26b6bd2a1973b83bb9af4e3385d8cb14cb3f62f2) )

	ROM_REGION( 0x0040, "user1", 0 )    /* timing PROMs */
	ROM_LOAD( "prom.b6", 0x0000, 0x0020, CRC(67104ea9) SHA1(26b6bd2a1973b83bb9af4e3385d8cb14cb3f62f2) )    /* control PROM */
	ROM_LOAD( "prom.f2", 0x0020, 0x0020, CRC(a1506b9d) SHA1(037c3db2ea40eca459e8acba9d1506dd28d72d10) )    /* sequence PROM */
-

All other sets like:
headon
headon1
headonmz
alphahob
heiankyo
sspaceat
sspaceat2
sspaceat3
sspaceatc

use a control PROM with the checksum (e60a7960).
Can someone check the original rom dump!

**Comment by Osso13** [comment]
Thanks, you're right. I messed up when adding the set. I'll fix it. The PROM is different from the other sets, though.
