### ISSUE TITLE
Mega Tech driver segfaults when service mode is activated on master

### ISSUE THREAD

**Issue by qeeg** [mamedev/mame#9638]
The segfault occurs in mtech_state::switch_cart(). I tried compiling with `SYMBOLS=1 SYMLEVEL=1` as that's the best my hardware can do ATM, and I don't really have enough info on where exactly the segfault occurs to make a fix.

**Comment by happppp** [comment]
Resolved https://github.com/mamedev/mame/commit/2b0277c650caa83f5b0fcb4aa6c3d0abb3a21efd
