### ISSUE TITLE
-intscaley does not work well for games changing the resolution

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#9663]
I have recently started experimenting with -intscalex and -intscaley. It works well for the most part, but games changing the resolution mid-game like radiant silvergun result in a cropped screen:
![Zrzut ekranu z 2022-05-01 14-12-32](https://user-images.githubusercontent.com/1208329/166145343-b913d462-ccb8-443d-8838-e0c27167c71a.png)
![Zrzut ekranu z 2022-05-01 14-12-43](https://user-images.githubusercontent.com/1208329/166145344-6301fcb5-6d91-45ef-9f7c-c67c8f742344.png)
Here is the verbose output:
```$ mame rsgun -sy 2 -autostretchxy -verbose
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Attempting load of horizont.ini
Attempting load of arcade.ini
drc_cache: RWX pages supported
drc_cache: RWX pages supported
Attempting load of raster.ini
Attempting load of source/stv.ini
Parsing source/stv.ini
Attempting load of stvbios.ini
Attempting load of rsgun.ini
Loading translation file /usr/share/mame/language/English/strings.mo
Reading translation file: 1 strings, original table at word offset 7, translated table at word offset 9
Loaded 0 translated string from file
Starting plugin data...
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Attempting load of horizont.ini
Attempting load of arcade.ini
drc_cache: RWX pages supported
drc_cache: RWX pages supported
Attempting load of raster.ini
Attempting load of source/stv.ini
Parsing source/stv.ini
Attempting load of stvbios.ini
Attempting load of rsgun.ini
drc_cache: RWX pages supported
drc_cache: RWX pages supported
Available videodrivers: x11 wayland KMSDRM dummy 
Current Videodriver: x11
	Display #0
		Renderdrivers:
			    opengl (0x0)
			 opengles2 (0x0)
			  opengles (0x0)
			  software (0x0)
Available audio drivers: 
	pulseaudio          
	alsa                
	jack                
	pipewire            
	dsp                 
	disk                
	dummy               
Build version:      0.243 (unknown)
Build architecure:  
Build defines 1:    SDLMAME_UNIX=1 SDLMAME_X11=1 SDLMAME_LINUX=1 
Build defines 1:    LSB_FIRST=1 PTR64=1 
SDL/OpenGL defines: SDL_COMPILEDVERSION=2020 USE_OPENGL=1 
Compiler defines A: __GNUC__=11 __GNUC_MINOR__=3 __GNUC_PATCHLEVEL__=1 __VERSION__="11.3.1 20220421 (Red Hat 11.3.1-2)" 
Compiler defines B: __amd64__=1 __x86_64__=1 __unix__=1 
Compiler defines C: _FORTIFY_SOURCE=2 __USE_FORTIFY_LEVEL=2 
Enter init_monitors
Adding monitor screen0 (3440 x 1440)
Leave init_monitors
Enter sdlwindow_init

Hints:
	SDL_FRAMEBUFFER_ACCELERATION             (NULL)
	SDL_RENDER_DRIVER                        (NULL)
	SDL_RENDER_OPENGL_SHADERS                (NULL)
	SDL_RENDER_SCALE_QUALITY                 (NULL)
	SDL_RENDER_VSYNC                         (NULL)
	SDL_VIDEO_X11_XVIDMODE                   (NULL)
	SDL_VIDEO_X11_XINERAMA                   (NULL)
	SDL_VIDEO_X11_XRANDR                     (NULL)
	SDL_GRAB_KEYBOARD                        (NULL)
	SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS         0
	SDL_IOS_IDLE_TIMER_DISABLED              (NULL)
	SDL_IOS_ORIENTATIONS                     (NULL)
	SDL_XINPUT_ENABLED                       (NULL)
	SDL_GAMECONTROLLERCONFIG                 (NULL)
	SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS     (NULL)
	SDL_ALLOW_TOPMOST                        (NULL)
	SDL_TIMER_RESOLUTION                     (NULL)
	SDL_RENDER_DIRECT3D_THREADSAFE           (NULL)
	SDL_VIDEO_ALLOW_SCREENSAVER              (NULL)
	SDL_ACCELEROMETER_AS_JOYSTICK            (NULL)
	SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK   (NULL)
	SDL_VIDEO_WIN_D3DCOMPILER                (NULL)
	SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT      (NULL)
	SDL_VIDEO_MAC_FULLSCREEN_SPACES          (NULL)
	SDL_MOUSE_RELATIVE_MODE_WARP             (NULL)
	SDL_RENDER_DIRECT3D11_DEBUG              (NULL)
	SDL_VIDEO_HIGHDPI_DISABLED               (NULL)
	SDL_WINRT_PRIVACY_POLICY_URL             (NULL)
	SDL_WINRT_PRIVACY_POLICY_LABEL           (NULL)
	SDL_WINRT_HANDLE_BACK_BUTTON             (NULL)
Leave sdlwindow_init
Enter sdl_info::create
Audio: Start initialization
Audio: Driver is pulseaudio
Audio: frequency: 48000, channels: 2, samples: 256
sdl_create_buffers: creating stream buffer of 25600 bytes
Audio: End initialization
Keyboard: Start initialization
Input: Adding keyboard #0: System keyboard (device id: System keyboard)
Keyboard: Registered System keyboard
Keyboard: End initialization
Mouse: Start initialization
Input: Adding mouse #0: System mouse (device id: System mouse)
Mouse: Registered System mouse
Mouse: End initialization
Lightgun: Begin initialization
Lightgun: End initialization
Joystick: Start initialization
Joystick: End initialization
Searching font Liberation Sans in -/usr/share/mame/fonts path/s
Matching font: 0x56020166f850
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip
unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip ECD
unzip: /mnt/openmediavault/emu/mame/roms/rsgun.zip has no ZIP64 ECD locator
unzip: read /mnt/openmediavault/emu/mame/roms/rsgun.zip central directory
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/stvbios.zip
unzip: found /mnt/openmediavault/emu/mame/roms/stvbios.zip ECD
unzip: /mnt/openmediavault/emu/mame/roms/stvbios.zip has no ZIP64 ECD locator
unzip: read /mnt/openmediavault/emu/mame/roms/stvbios.zip central directory
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/stvbios.zip and sending to cache
unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache
unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache
unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache
unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache
unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache
unzip: opened archive file /mnt/openmediavault/emu/mame/roms/segabill.zip
unzip: found /mnt/openmediavault/emu/mame/roms/segabill.zip ECD
unzip: /mnt/openmediavault/emu/mame/roms/segabill.zip has no ZIP64 ECD locator
unzip: read /mnt/openmediavault/emu/mame/roms/segabill.zip central directory
unzip: closing archive file /mnt/openmediavault/emu/mame/roms/segabill.zip and sending to cache
Optional I/O port ':P2_KEY4' not found
Optional I/O port ':P2_KEY3' not found
Optional I/O port ':P2_KEY2' not found
Optional I/O port ':P2_KEY1' not found
Optional I/O port ':P2_KEY0' not found
Optional I/O port ':P1_KEY4' not found
Optional I/O port ':P1_KEY3' not found
Optional I/O port ':P1_KEY2' not found
Optional I/O port ':P1_KEY1' not found
Optional I/O port ':P1_KEY0' not found
Optional I/O port ':PORTD' not found
Optional device ':hopper' not found
Optional device ':315_5838' not found
Optional memory bank ':protbank' not found
Optional device ':rax' not found
Optional device ':stv_slot4' not found
Optional device ':stv_slot3' not found
Optional device ':stv_slot2' not found
Optional device ':stv_slot1' not found
Optional I/O port ':fake' not found
Optional memory region ':smpc:smem' not found
Optional memory region ':eeprom' not found
Optional memory region ':screen' not found
Optional memory region ':scsp' not found
Starting Radiant Silvergun (JUET 980523 V1.000) ':'
  (missing dependencies; rescheduling)
Starting Hitachi SH-2 ':maincpu'
Starting Timer ':scantimer'
Starting Hitachi SH-2 ':slave'
Starting Timer ':slave_scantimer'
Starting Motorola MC68000 ':audiocpu'
Starting Sega System Control Unit ':scu'
Starting Sega SCUDSP ':scu:scudsp'
Starting Sega Saturn SMPC HLE (HD404920FS) ':smpc'
Starting NVRAM ':smpc:smem'
Starting Serial EEPROM 93C46 (64x16) ':eeprom'
Starting Video Screen ':screen'
Starting palette ':palette'
Starting gfxdecode ':gfxdecode'
Starting Speaker ':lspeaker'
  (missing dependencies; rescheduling)
Starting Speaker ':rspeaker'
  (missing dependencies; rescheduling)
Starting Yamaha YMF292-F SCSP ':scsp'
Starting Sega Billboard ':billboard'
Starting Zilog Z80 ':billboard:billcpu'
Starting Sega 315-5338A I/O Controller ':billboard:io'
Starting Sega 315-5881 Encryption ':315_5881'
Starting Radiant Silvergun (JUET 980523 V1.000) ':'
  (missing dependencies; rescheduling)
Starting Speaker ':lspeaker'
Starting Speaker ':rspeaker'
Starting Radiant Silvergun (JUET 980523 V1.000) ':'
Attempting to parse: default.cfg
Attempting to parse: rsgun.cfg
```

**Comment by john-iv** [comment]
FWIW, looks ok on Windows x64 build w/ BGFX and D3D/HLSL fullscreen and windowed. -intscaley / -intscalex / -autostretchxy
0.243 (mame0243-76-g4511b20768a)

From: Julian Sikorski ***@***.***>
Sent: Sunday, May 1, 2022 5:15 AM
To: mamedev/mame ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mamedev/mame] -intscaley does not work well for games changing the resolution (Issue #9663)


I have recently started experimenting with -intscalex and -intscaley. It works well for the most part, but games changing the resolution mid-game like radiant silvergun result in a cropped screen:
[Zrzut ekranu z 2022-05-01 14-12-32]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1208329%2F166145343-b913d462-ccb8-443d-8838-e0c27167c71a.png&data=05%7C01%7C%7Cd689bbe1f8554831f9fc08da2b6c3736%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637870041033178398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yjtM%2FOTKLsTEvm943E59at1HRbvTSG6j2agUIh2wn1A%3D&reserved=0>
[Zrzut ekranu z 2022-05-01 14-12-43]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1208329%2F166145344-6301fcb5-6d91-45ef-9f7c-c67c8f742344.png&data=05%7C01%7C%7Cd689bbe1f8554831f9fc08da2b6c3736%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637870041033178398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jJUw3YAbOEVGGHIinewFhgmQJsCGEwXAJScKnMPGKBQ%3D&reserved=0>
Here is the verbose output:

Attempting load of mame.ini

Parsing mame.ini

Attempting load of mame.ini

Parsing mame.ini

Attempting load of horizont.ini

Attempting load of arcade.ini

drc_cache: RWX pages supported

drc_cache: RWX pages supported

Attempting load of raster.ini

Attempting load of source/stv.ini

Parsing source/stv.ini

Attempting load of stvbios.ini

Attempting load of rsgun.ini

Loading translation file /usr/share/mame/language/English/strings.mo

Reading translation file: 1 strings, original table at word offset 7, translated table at word offset 9

Loaded 0 translated string from file

Starting plugin data...

Attempting load of mame.ini

Parsing mame.ini

Attempting load of mame.ini

Parsing mame.ini

Attempting load of horizont.ini

Attempting load of arcade.ini

drc_cache: RWX pages supported

drc_cache: RWX pages supported

Attempting load of raster.ini

Attempting load of source/stv.ini

Parsing source/stv.ini

Attempting load of stvbios.ini

Attempting load of rsgun.ini

drc_cache: RWX pages supported

drc_cache: RWX pages supported

Available videodrivers: x11 wayland KMSDRM dummy

Current Videodriver: x11

        Display #0

               Renderdrivers:

                           opengl (0x0)

                        opengles2 (0x0)

                         opengles (0x0)

                         software (0x0)

Available audio drivers:

        pulseaudio

        alsa

        jack

        pipewire

        dsp

        disk

        dummy

Build version:      0.243 (unknown)

Build architecure:

Build defines 1:    SDLMAME_UNIX=1 SDLMAME_X11=1 SDLMAME_LINUX=1

Build defines 1:    LSB_FIRST=1 PTR64=1

SDL/OpenGL defines: SDL_COMPILEDVERSION=2020 USE_OPENGL=1

Compiler defines A: __GNUC__=11 __GNUC_MINOR__=3 __GNUC_PATCHLEVEL__=1 __VERSION__="11.3.1 20220421 (Red Hat 11.3.1-2)"

Compiler defines B: __amd64__=1 __x86_64__=1 __unix__=1

Compiler defines C: _FORTIFY_SOURCE=2 __USE_FORTIFY_LEVEL=2

Enter init_monitors

Adding monitor screen0 (3440 x 1440)

Leave init_monitors

Enter sdlwindow_init



Hints:

        SDL_FRAMEBUFFER_ACCELERATION             (NULL)

        SDL_RENDER_DRIVER                        (NULL)

        SDL_RENDER_OPENGL_SHADERS                (NULL)

        SDL_RENDER_SCALE_QUALITY                 (NULL)

        SDL_RENDER_VSYNC                         (NULL)

        SDL_VIDEO_X11_XVIDMODE                   (NULL)

        SDL_VIDEO_X11_XINERAMA                   (NULL)

        SDL_VIDEO_X11_XRANDR                     (NULL)

        SDL_GRAB_KEYBOARD                        (NULL)

        SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS         0

        SDL_IOS_IDLE_TIMER_DISABLED              (NULL)

        SDL_IOS_ORIENTATIONS                     (NULL)

        SDL_XINPUT_ENABLED                       (NULL)

        SDL_GAMECONTROLLERCONFIG                 (NULL)

        SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS     (NULL)

        SDL_ALLOW_TOPMOST                        (NULL)

        SDL_TIMER_RESOLUTION                     (NULL)

        SDL_RENDER_DIRECT3D_THREADSAFE           (NULL)

        SDL_VIDEO_ALLOW_SCREENSAVER              (NULL)

        SDL_ACCELEROMETER_AS_JOYSTICK            (NULL)

        SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK   (NULL)

        SDL_VIDEO_WIN_D3DCOMPILER                (NULL)

        SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT      (NULL)

        SDL_VIDEO_MAC_FULLSCREEN_SPACES          (NULL)

        SDL_MOUSE_RELATIVE_MODE_WARP             (NULL)

        SDL_RENDER_DIRECT3D11_DEBUG              (NULL)

        SDL_VIDEO_HIGHDPI_DISABLED               (NULL)

        SDL_WINRT_PRIVACY_POLICY_URL             (NULL)

        SDL_WINRT_PRIVACY_POLICY_LABEL           (NULL)

        SDL_WINRT_HANDLE_BACK_BUTTON             (NULL)

Leave sdlwindow_init

Enter sdl_info::create

Audio: Start initialization

Audio: Driver is pulseaudio

Audio: frequency: 48000, channels: 2, samples: 256

sdl_create_buffers: creating stream buffer of 25600 bytes

Audio: End initialization

Keyboard: Start initialization

Input: Adding keyboard #0: System keyboard (device id: System keyboard)

Keyboard: Registered System keyboard

Keyboard: End initialization

Mouse: Start initialization

Input: Adding mouse #0: System mouse (device id: System mouse)

Mouse: Registered System mouse

Mouse: End initialization

Lightgun: Begin initialization

Lightgun: End initialization

Joystick: Start initialization

Joystick: End initialization

Searching font Liberation Sans in -/usr/share/mame/fonts path/s

Matching font: 0x56020166f850

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip

unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip ECD

unzip: /mnt/openmediavault/emu/mame/roms/rsgun.zip has no ZIP64 ECD locator

unzip: read /mnt/openmediavault/emu/mame/roms/rsgun.zip central directory

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/stvbios.zip

unzip: found /mnt/openmediavault/emu/mame/roms/stvbios.zip ECD

unzip: /mnt/openmediavault/emu/mame/roms/stvbios.zip has no ZIP64 ECD locator

unzip: read /mnt/openmediavault/emu/mame/roms/stvbios.zip central directory

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/stvbios.zip and sending to cache

unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache

unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache

unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache

unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache

unzip: found /mnt/openmediavault/emu/mame/roms/rsgun.zip in cache

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/rsgun.zip and sending to cache

unzip: opened archive file /mnt/openmediavault/emu/mame/roms/segabill.zip

unzip: found /mnt/openmediavault/emu/mame/roms/segabill.zip ECD

unzip: /mnt/openmediavault/emu/mame/roms/segabill.zip has no ZIP64 ECD locator

unzip: read /mnt/openmediavault/emu/mame/roms/segabill.zip central directory

unzip: closing archive file /mnt/openmediavault/emu/mame/roms/segabill.zip and sending to cache

Optional I/O port ':P2_KEY4' not found

Optional I/O port ':P2_KEY3' not found

Optional I/O port ':P2_KEY2' not found

Optional I/O port ':P2_KEY1' not found

Optional I/O port ':P2_KEY0' not found

Optional I/O port ':P1_KEY4' not found

Optional I/O port ':P1_KEY3' not found

Optional I/O port ':P1_KEY2' not found

Optional I/O port ':P1_KEY1' not found

Optional I/O port ':P1_KEY0' not found

Optional I/O port ':PORTD' not found

Optional device ':hopper' not found

Optional device ':315_5838' not found

Optional memory bank ':protbank' not found

Optional device ':rax' not found

Optional device ':stv_slot4' not found

Optional device ':stv_slot3' not found

Optional device ':stv_slot2' not found

Optional device ':stv_slot1' not found

Optional I/O port ':fake' not found

Optional memory region ':smpc:smem' not found

Optional memory region ':eeprom' not found

Optional memory region ':screen' not found

Optional memory region ':scsp' not found

Starting Radiant Silvergun (JUET 980523 V1.000) ':'

  (missing dependencies; rescheduling)

Starting Hitachi SH-2 ':maincpu'

Starting Timer ':scantimer'

Starting Hitachi SH-2 ':slave'

Starting Timer ':slave_scantimer'

Starting Motorola MC68000 ':audiocpu'

Starting Sega System Control Unit ':scu'

Starting Sega SCUDSP ':scu:scudsp'

Starting Sega Saturn SMPC HLE (HD404920FS) ':smpc'

Starting NVRAM ':smpc:smem'

Starting Serial EEPROM 93C46 (64x16) ':eeprom'

Starting Video Screen ':screen'

Starting palette ':palette'

Starting gfxdecode ':gfxdecode'

Starting Speaker ':lspeaker'

  (missing dependencies; rescheduling)

Starting Speaker ':rspeaker'

  (missing dependencies; rescheduling)

Starting Yamaha YMF292-F SCSP ':scsp'

Starting Sega Billboard ':billboard'

Starting Zilog Z80 ':billboard:billcpu'

Starting Sega 315-5338A I/O Controller ':billboard:io'

Starting Sega 315-5881 Encryption ':315_5881'

Starting Radiant Silvergun (JUET 980523 V1.000) ':'

  (missing dependencies; rescheduling)

Starting Speaker ':lspeaker'

Starting Speaker ':rspeaker'

Starting Radiant Silvergun (JUET 980523 V1.000) ':'

Attempting to parse: default.cfg

Attempting to parse: rsgun.cfg

-

**Comment by belegdol** [comment]
It might be a linux-specific issue then. I tried bgfx vulkan, bgfx opengl, opengl and software video. All exhibit the issue. I pointed the inipath to my home folder to make sure that it is not something I set in my ini causing this:
```
$ mame rsgun -sy 2 -autostretchxy -verbose -bgfx_backend opengl -inipath . -rp /mnt/openmediavault/emu/mame/roms/ -window -video soft
```

**Comment by belegdol** [comment]
I can reproduce this with a windows build too:
```
.\mame.exe -rompath \\ODROIDXU4\julian\emu\mame\roms -video bgfx  -window -sy 2 -autostretchxy -verbose rsgun
```

**Comment by john-iv** [comment]
Vaguely recall forcing an intscale could cause some hiccups when these were being implemented.  If you leave -sy2 off it appears to work in Windows.  SDL too?  Maybe @antonioginer will weigh in.

**Comment by antonioginer** [comment]
This happens because the window size is calculated at startup, based on the source screen size and your settings. Making the window size react to game's resolution changes would be possible, in the same way the Windows build refreshes its window size when different scaling options are set by the user from the UI. But I'm not sure if this is desired.

Notice that cropping only happens because you're forcing an scale factor (-sy 2). This has the effect of enabling `-intoverscan` internally. If you weren't forcing `-sy 2` and just used `-autostretchxy`, scaling would adapt to the current window size without cropping.

Also, notice that clicking on the window caption will make it resize to the current frame size.

**Comment by belegdol** [comment]
Thanks for explaining. I guess what confuses me is the difference to running without `-sy 2`, either in a window, in a maximized window, or in fullscreen. In all three cases the rendered picture stays the same size regardless of the internal resolution changes.
With `-sy 2` the window size is doubled, but the rendered size does change with the internal resolution changes.
What the desired behaviour is depends on what these options are intended to do. Personally I am looking for a setting which would allow me to use the maximum possible window size while keeping integer scaling. Are `-sy` and `-sx` correct options? Does using them together with shaders like crt-geom-deluxe or hlsl even make sense?

**Comment by antonioginer** [comment]
>  I guess what confuses me is the difference to running without `-sy 2`, either in a window, in a maximized window, or in fullscreen. In all three cases the rendered picture stays the same size regardless of the internal resolution changes.

Correct. In a normal situation, without forcing scale factors, these are calculated to be the maximum that fit either the screen or the window rectangle. If, instead, you force a scale factor, like `-sy 2`, now the priority will be to apply that factor, regardless of the constraints. Still, on startup the window would be resized to fit the resulting rectangle, it's just that this doesn't happen a second time without user interaction.

> Personally I am looking for a setting which would allow me to use the maximum possible window size while keeping integer scaling. Are `-sy` and `-sx` correct options?

I wouldn't use fixed `-sy` `-sx` factors unless you had a very good reason (testing, developing, etc.) so you're willing to have per-system settings. Instead, `-autostretchxy` alone provides the best compromise, applying integer scaling only to the short axis.
