### ISSUE TITLE
Documentation/comment issue in Konami 573 driver

### ISSUE THREAD

**Issue by simzy39** [mamedev/mame#9669]
This concerns some driver comments about the game Dance Dance Revolution Kids.

I apologise if this is wrong place to post this, but I cannot get MameTesteers login working for me.

In the Konami System 573 (https://github.com/mamedev/mame/blob/master/src/mame/drivers/ksys573.cpp)
it says: "? *Dance Dance Revolution Kids                  2000.12

The * denotes undumped.

Anyway, the game has been dumped and doesn't run on this hardware. DDR Kids belong in, and is in,
the Konami GSAN1 driver (https://github.com/mamedev/mame/blob/master/src/mame/drivers/konamigs.cpp).

The GSAN1 driver also has a confusing line: '    * denotes these games are archived'
I'm not used to this since that * usually denotes undumped.

**Comment by cuavas** [comment]
Surely you can open a pull request to remove one errant line?

There's no standard for formatting those lists in file header comments. You'll have to get used to then all being different.
