### ISSUE TITLE
zaxxon has no netlist, but is listed on src/mame/nl.lst 

### ISSUE THREAD

**Issue by felipesanches** [mamedev/mame#9689]
I see `@source:zaxxon.cpp` listed on `src/mame/nl.lst` but I was unable to find anything netlist related in the Zaxxon driver.

**Comment by couriersud** [comment]
Thanks for opening an issue. I still have a WIP netlist for congo which needs further work. I assume that I added zaxxon.cpp (which contains congo) because of this reason.

**Comment by couriersud** [comment]
Todo: Finalize work on congo netlist.

**Comment by cuavas** [comment]
The nl subtarget is only marginally supported, and inclusion doesn’t have precise criteria.  This issue is pointless.
