### ISSUE TITLE
Rendering isn't correct in Flipped Screen Mode (konamigx)

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [mamedev/mame#9690]
Sprites are in the correct place, but the background isn't.
Look at this MESS
![0011](https://user-images.githubusercontent.com/40109698/166861284-7d170f7b-d6bc-41a5-956d-e3bbbea2eadb.png)

**Comment by Tafoid** [comment]
Graphics are flagged as "imperfectly emulated" for all machines in that driver (konamigx.cpp).  By extension, the flip screens are also imperfect.  They are not expected to work correctly nor have they ever fully worked.  Given the flag, it is a known issue.

**Comment by MooglyGuy** [comment]
This is your third of three Github issues you've submitted to MAME, all three of which were invalid. It would be a good idea to take a step back and ask if this is a road you really want to go down.

**Comment by angelosa** [comment]
Known issue, if konamigx really needs an issue opened that would be a shopping list, and flip screen goes pretty low in priority.
