### ISSUE TITLE
Soldier Girl Amazon Dips/Debug Features

### ISSUE THREAD

**Issue by atrac17** [mamedev/mame#9697]
Sei Senshi Amatelass:

Toggling dip switch 7 will enable invincibility. When this is enabled, you can overclock the games framerate by holding the 2p Start Button. This feature was used for debugging during development.

In the "Debug" section you will find a toggle for "Turbo". Enabling this removes the requirement to press and hold the 2p Start Button to enable this feature.

This information is not listed in the mame driver and was discovered while adding support for "amazont" in the Terra Cresta FPGA implementation.

**Comment by cuavas** [comment]
Info added in be9cb8161a6b4cb0df551bc4c1c557ef7978d631.  It’s actually DP1-8, not 7, and you need to reset or enter/leave service mode for the change to apply.
