### ISSUE TITLE
Compile mame fail when using OPTIMIZE argument

### ISSUE THREAD

**Issue by czxinc** [mamedev/mame#9724]
I use this command to compile mame, but it gives me a unusedfunction error.

make REGENIE=1 OPTIMIZE=s -j7

Then I try to use this command to compile mame. It will print lots of errors when linking mame.exe.

make REGENIE=1 OPTIMIZE=s WERROR=1 -j7

Only when not giving OPTIMIZE argument or set OPTIMIZE to 3. It will print lots of errors when OPTIMIZE set to 0,1,2,s.

**Comment by czxinc** [comment]
I use msys64-2022-01-12 from official website to compile mame 0.243

**Comment by MooglyGuy** [comment]
The guide on how to compile MAME, found here - https://docs.mamedev.org/initialsetup/compilingmame.html#microsoft-windows - does not say anything about the use of `OPTIMIZE=s`, as such the configuration you are attempting to build is unsupported.

As you have unhelpfully not provided any console logs containing any of the specific errors, you're pretty much on your own.

**Comment by czxinc** [comment]
> The guide on how to compile MAME, found here - https://docs.mamedev.org/initialsetup/compilingmame.html#microsoft-windows - does not say anything about the use of `OPTIMIZE=s`, as such the configuration you are attempting to build is unsupported.
> 
> As you have unhelpfully not provided any console logs containing any of the specific errors, you're pretty much on your own.

Here is why it can use OPTIMIZE=s. I found in the guide of how to compile MAME, which you give to me.

> OPTIMIZE
Set optimisation level. The default is 3 to favour performance at the expense of larger executable size. Set to 0 to disable optimisation (can make debugging easier), 1 for basic optimisation that doesn’t have a space/speed trade-off and doesn’t have a large impact on compile time, 2 to enable most optimisation that improves performance and reduces size,` or s to enable only optimisations that generally don’t increase executable size`. The exact set of supported values depends on your compiler.

`OPTIMIZE=0`, `OPTIMIZE=1`, `OPTIMIZE=2` also make the compilation fail. Their console logs look almost the same as  `OPTIMIZE=s`.

And I am sorry about not post console logs. Here is the console output when I use `make OPTIMIZE=s REGENIE=1 -j7` and `make OPTIMIZE=s REGENIE=1 NOWERROR=1 -j7 `. Note that I only take a part of `make OPTIMIZE=s REGENIE=1 NOWERROR=1 -j7` logs because it's very long and takes much time.

[make OPTIMIZE=s REGENIE=1 -j7.txt](https://github.com/mamedev/mame/files/8649480/make.OPTIMIZE.s.REGENIE.1.-j7.txt)
[make OPTIMIZE=s REGENIE=1 NOWERROR=1 -j7 .txt](https://github.com/mamedev/mame/files/8649479/make.OPTIMIZE.s.REGENIE.1.NOWERROR.1.-j7.txt)

**Comment by cuavas** [comment]
The warning you’re getting in the first log:
```
J:/nMame/mame/src/lib/util/corefile.cpp:699:1: error: 'util::{anonymous}::core_osd_file::~core_osd_file()' defined but not used [-Werror=unused-function]
  699 | core_osd_file::~core_osd_file()
      | ^~~~~~~~~~~~~
```

Is definitely a compiler bug.  The virtual destructor is referenced by the vtable for `core_osd_file`, which itself is referenced when the class is instantiated in `core_file::open`: https://github.com/mamedev/mame/blob/mame0243/src/lib/util/corefile.cpp#L870

**Comment by cuavas** [comment]
The errors in the second log with vtables failing to be instantiated can only be caused by a compiler bug when using whatever options you’re specifying, or corrupt static library files.  Given that the compiler believes out-of-line virtual destructors are unreferenced when the out-of-line destructor should be causing the vtable which references to be instantiated, It’s very likely that this is the same bug.  Somehow you’re specifying options that cause the compiler to fail to instantiate vtables.

Please try to create a minimal test case and report it to the packagers for your compiler.

(I guess it’s theoretically possible you’re specifying some combination of compiler options that suppresses generation of vtables, but I can’t think what the purpose of this would be.)

**Comment by MistyDreams** [comment]
Im using manjaro (arch linux fork). make make line is 

```export CXXFLAGS="  -Wp,-U_GLIBCXX_ASSERTIONS" && make -j32```

in the makefile I have the following set.

```
 REGENIE = 1
 OPTIMIZE = 2

 USE_SYSTEM_LIB_ASIO = 1
 USE_SYSTEM_LIB_EXPAT = 1
 USE_SYSTEM_LIB_ZLIB = 1
 USE_SYSTEM_LIB_JPEG = 1
 USE_SYSTEM_LIB_FLAC = 1
# USE_SYSTEM_LIB_LUA = 1
 USE_SYSTEM_LIB_SQLITE3 = 1
 USE_SYSTEM_LIB_PORTMIDI = 1
 USE_SYSTEM_LIB_PORTAUDIO = 1
# USE_BUNDLED_LIB_SDL2 = 1
 USE_SYSTEM_LIB_UTF8PROC = 1
 USE_SYSTEM_LIB_GLM = 1
 USE_SYSTEM_LIB_RAPIDJSON = 1
 USE_SYSTEM_LIB_PUGIXML = 1
```
