### ISSUE TITLE
[32x] It feels to me that Sega 32x have 3d rendering core

### ISSUE THREAD

**Issue by WhiteMagicRaven** [mamedev/mame#9736]
If so its is true?
Can it be in distant future , in theory, upscale 3d like bsnes do it for mode 7 ?

**Comment by WhiteMagicRaven** [comment]
Well
the games like
Metal Head
and
Virtua Racing Deluxe
the cartridges with this games comes with additional 3d chip on own cartridge?

by reading wikipedia i get confused here
https://en.wikipedia.org/wiki/32X#Development
https://en.wikipedia.org/wiki/Sega_Genesis#Sega_Virtua_Processor
https://en.wikipedia.org/wiki/Sega_Genesis#Sega_32X

it tells that it has limited 3d capabilities

**Comment by happppp** [comment]
https://github.com/ares-emulator/ares/issues/552
