### ISSUE TITLE
Should save states work with Apple 2 machine? (I run it from command line)

### ISSUE THREAD

**Issue by necros2k7** [mamedev/mame#9739]
0.243 win11 
shift-f7, f7 - no effect while in game

**Comment by happppp** [comment]
In drivers that emulate a full keyboard, press SCROLL LOCK to toggle enabling MAME user interface inputs, such as the save/loadstate command.
This place is not a user help forum by the way.

**Comment by rb6502** [comment]
Complete Apple II-specific documentation for MAME is available at https://wiki.mamedev.org/index.php/Driver:Apple_II

**Comment by cuavas** [comment]
Also see the documentation: https://docs.mamedev.org/usingmame/ui.html
