### ISSUE TITLE
Atari 2600 (driver name: a2600) Paddle Button Bug

### ISSUE THREAD

**Issue by ravenheartss** [mamedev/mame#9755]
Looks like the fields P2 Button 1 and P1 Button 1 in port joyport1:pad:JOY are swapped. 
For example, in breakout, one has to press P2 Button 1 (A) to start the game and not the usual P1 Button 1 (Ctrl).

**Comment by cuavas** [comment]
Thanks.  This was fixed by @0kmg in #9756.
