### ISSUE TITLE
exidy.cpp: Games have 2 Coin 1/Coin 2

### ISSUE THREAD

**Issue by einstein95** [mamedev/mame#9757]
![Example from Venture](https://user-images.githubusercontent.com/2461173/168455218-3715f658-08a0-4f8f-b571-1985f9494ea9.png)

This comes from each game having `IPT_COIN1` and `IPT_COIN2` in both `IN0`/`DSW` and `INTSOURCE`. Not only is this confusing for redefining inputs, but the "Bookkeeping info" screen in MAME's GUI shows "NA" coins entered no matter how many you insert.

Opening an issue instead of submitting a PR as I'm unsure as to which ones should be kept.

**Comment by FoxhackDN** [comment]
This is a BTAB, as referenced here: https://mametesters.org/view.php?id=1288

As for the Bookkeeping info, it doesn't really work in a lot of games.

**Comment by einstein95** [comment]
Cool, I guess I'll close it then

**Comment by cuavas** [comment]
> This is a BTAB, as referenced here: https://mametesters.org/view.php?id=1288

I don’t know when that was written, but you can use custom port bit handlers or a handler function to combine the bits from multiple ports.

> the "Bookkeeping info" screen in MAME's GUI shows "NA" coins entered no matter how many you insert.

That shows the number of pulses on the coin counter outputs – if the game lacks coin counter outputs or they aren’t hooked up, that’s normal behavior.  Do the games actually have coin counter outputs?

**Comment by FoxhackDN** [comment]
> That shows the number of pulses on the coin counter outputs – if the game lacks coin counter outputs or they aren’t hooked up, that’s normal behavior. Do the games actually have coin counter outputs?

No, Venture doesn't have a service menu. The bookkeeping option in the tab menu is always there, even if it doesn't work (due to the game not having any coin counters), and that confused me a bit at first until Moogly explained it to me on Discord.

**Comment by cuavas** [comment]
> No, Venture doesn't have a service menu. The bookkeeping option in the tab menu is always there, even if it doesn't work (due to the game not having any coin counters), and that confused me a bit at first until Moogly explained it to me on Discord.

I think you’re misunderstanding.  The game doesn’t track coins in non-volatile RAM to display in a service menu, but it could still have outputs for electromechanical coin counters that just aren’t hooked up in MAME.  Is there an edge connector pinout available somewhere to confirm that it definitely lacks such outputs?

**Comment by FoxhackDN** [comment]
> > No, Venture doesn't have a service menu. The bookkeeping option in the tab menu is always there, even if it doesn't work (due to the game not having any coin counters), and that confused me a bit at first until Moogly explained it to me on Discord.
> 
> I think you’re misunderstanding. The game doesn’t track coins in non-volatile RAM to display in a service menu, but it could still have outputs for electromechanical coin counters that just aren’t hooked up in MAME. Is there an edge connector pinout available somewhere to confirm that it definitely lacks such outputs?

Oh yeah I definitely misunderstood. The schematics included in the operators manual do reference a Coin Counter, but I'm not sure if they work in the way you're describing.

https://archive.org/details/ArcadeGameManualVenture/page/n47/mode/2up

**Comment by cuavas** [comment]
> Oh yeah I definitely misunderstood. The schematics included in the operators manual do reference a Coin Counter, but I'm not sure if they work in the way you're describing.

So it’s a legitimate issue for Venture at least, which *does* have an electromechanical coin counter output that isn’t hooked up in MAME.

**Comment by cuavas** [comment]
Partially addressed by 3da1e6f2b799e0896de9b08883b841f5921ae64b – duplicate coin inputs have been removed, but coin counter outputs aren’t hooked up.

**Comment by cuavas** [comment]
At least for Venture, the coin counter outputs are just buffered signals from the coin inputs – they’re not CPU-driven.  You could hook them up using port changed members, but I’m not sure it’s worth it.

**Comment by cuavas** [comment]
Coin counters for Venture are hooked up in 6126ec74778bc6b4587a093fb53861f81357b3de.  If other games have coin counters using the same logic shown on schematics, they can be hooked up, too.  Closing this for now.
