### ISSUE TITLE
amd bgfx vulkan crashes

### ISSUE THREAD

**Issue by MistyDreams** [mamedev/mame#9795]
Just to let you know I have an old system for mame its a 8300-sff, I also got a cheap 340x for shaders to work. 

I also tested another old a radeon rx 480 both crashed with vulkan shaders on testing(different machines). Just to let anyone thats having this issues with freezing there is a fix for vulkan to use amdvlk and the issue goes away radv crashes both systems every time.

**Comment by MooglyGuy** [comment]
Thank you for posting this work-around. The driver situation for Vulkan on Linux leaves a lot to be desired, so I appreciate you taking the time to iron out a way of making it work.

**Comment by MistyDreams** [comment]
I did have some strange issues on radv i compiled with optimisation g and asan and the ui. This also happens without staring a game. Letters are displayed wrong ect switching to the amdvlk fixed this however, the strange thing is opengl was the bgfx backend causing this vulkan was fine but switching to amdvlk fixed it somehow

**Comment by MooglyGuy** [comment]
It wouldn't surprise me. While Mesa3D can be pretty good, I would expect that AMDVLK, being supplied by AMD themselves, would probably have the edge over RADV.

**Comment by MistyDreams** [comment]
I used the wrong bin seems only open backend has this opengl corruption with asan and optimization g. Ill test if this is happening with integrated intel gfx card when I get access to the machine.

**Comment by MistyDreams** [comment]
![Screenshot from 2022-05-21 13-19-39](https://user-images.githubusercontent.com/105502489/169651387-72be938d-e7bd-426e-9f38-c4b1d1788a43.png)

**Comment by MistyDreams** [comment]
There is also issues with fullscreen/window switching in bgfx

```
VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/amd_icd64.json" mame rygar -video bgfx -bgfx_backend opengl
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  0 ()
  Resource id in failed request:  0xe00013
  Serial number of failed request:  2560
  Current serial number in output stream:  2560
    ~/S/mame   @da`91682b !3   VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/amd_icd64.json" mame rygar -video bgfx -bgfx_backend vulkan
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  0 ()
  Resource id in failed request:  0xe00013
  Serial number of failed request:  2827
  Current serial number in output stream:  2827
```
with radv the vulkan window switches fine.

amdvlk fails the switch.

bgfx/opengl doesnt want to play at all (it works fine with -video opengl though).

im not sure if any of this information is useful will get back with the results from integrated intel card as well.

**Comment by MistyDreams** [comment]
The switch on FS/windowed is also doing this on both backends on the intel chip I have. Can only test on wayland at the moment as xorg wont start must be missing something will need to debug it. Can anyone switch in bgfx without it dropping back to the console ?

**Comment by sairuk** [comment]
@MistyDreams i don't get these issues with Vulkan/RADV combo on my RX580, Ubuntu 22.04. It is running fine here.

What distro are you running and have you tried forcing the icd for radv (e.g. `/usr/share/vulkan/icd.d/radeon_icd.x86_64.json`)? The last release of the `mesa-vulkan-drivers` packages broke radv for me (and others) because it was selecting the wrong icd at launch, different behaviours tho.

Try adding `-bgfx_debug` to you testing cli so you can confirm launch state

**Comment by MistyDreams** [comment]
It is using VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json by default. This causes a system freeze one shader does it not all. I added the recover options to the kernel so i can ssh in and kill mame and the system is usable again. 

VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/amd_icd64.json"  is what fixes it for me and including the full screen switching for vulkan and the shaders freezing. 

The opengl I have no solution for it the only symptom is you cant switch fullscreen and window and the thing with. I tried linux mint as as what im on no manjaro both system had issues. ill test more with rx480 another time just dealing with the 340x just now needed some amdgpu and radeon kernel options set to avoid conflicts. 

VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json" mame rygar -video bgfx -bgfx_backend vulkan -bgfx_debug


![Screenshot from 2022-05-22 00-20-23](https://user-images.githubusercontent.com/105502489/169671997-972f064c-c1ea-4a66-90eb-718ef35bf0d9.png)

**Comment by sairuk** [comment]
Can confirm the opengl backend is failing to switch window mode with alt-enter (nothing to do with OPTIMIZE compiler options, though since it fails on any)

```
$ VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json" mame rygar -video bgfx -bgfx_backend opengl -bgfx_debug
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  0 ()
  Resource id in failed request:  0x520001b
  Serial number of failed request:  5034
  Current serial number in output stream:  5034
```

For me switching to `amdvlk` causes a lock when cycling to `crt-geom` shader while using `radv` is OK. I've just installed the `amdvlk` package from the git repo here and my icd gets dumped into `/etc/vulkan/icd.d/amd_icd64.json`

`$ VK_ICD_FILENAMES="/etc/vulkan/icd.d/amd_icd64.json" mame rygar -video bgfx -bgfx_backend opengl -bgfx_debug`

Same shader for you?

**Comment by MistyDreams** [comment]
The shader that crashes on me is  xbr-lv2-accuracy-multipass. I seen there was a new mess and a fix cor current messa with radv crashes. I think its because we are using difefrnt chipsets. Im limited what i can put in that 8300-sff though. It has to be low profile for a start. I can get it working though so thats might be some good news.https://www.mesa3d.org/news/  

```
[ 6814.176926] amdgpu 0000:01:00.0: amdgpu: GPU fault detected: 147 0x01e85001
[ 6814.176931] amdgpu 0000:01:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0FF1560F
[ 6814.176932] amdgpu 0000:01:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x08050001
[ 6814.176933] amdgpu 0000:01:00.0: amdgpu: VM fault (0x01, vmid 4) at page 267474447, read from '' (0x00000000) (80)
[ 6824.303406] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=667526, emitted seq=667527
[ 6824.303887] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process mame pid 5376 thread mame pid 5379
[ 6824.304384] amdgpu 0000:01:00.0: amdgpu: GPU reset begin!
[ 6824.734127] amdgpu 0000:01:00.0: amdgpu: PCI CONFIG reset
[ 6824.737396] amdgpu 0000:01:00.0: amdgpu: GPU reset succeeded, trying to resume
[ 6824.737476] [drm] PCIE gen 3 link speeds already enabled
[ 6824.737966] amdgpu 0000:01:00.0: amdgpu: PCIE GART of 1024M enabled (table at 0x000000F40012C000).
[ 6825.311637] [drm] UVD initialized successfully.
[ 6825.582745] amdgpu 0000:01:00.0: amdgpu: recover vram bo from shadow start
[ 6825.582803] amdgpu 0000:01:00.0: amdgpu: recover vram bo from shadow done
[ 6825.582807] [drm] Skip scheduling IBs!
[ 6825.583175] [drm] Skip scheduling IBs!
[ 6825.583363] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
```

**Comment by MistyDreams** [comment]
> Can confirm the opengl backend is failing to switch window mode with alt-enter (nothing to do with OPTIMIZE compiler options, though since it fails on any)

The thing is with amd opengl shinobi is the only game so far ive found to mess the gui characters up as well as the game info screen when you start the game. Might be triggering some king of overflow asan doesnt report anything though. with options
```
 REGENIE = 1
 VERBOSE = 1
 SANITIZE = address
 OPTIMIZE = g

 USE_SYSTEM_LIB_EXPAT = 1
 USE_SYSTEM_LIB_ZLIB = 1
 USE_SYSTEM_LIB_JPEG = 1
 USE_SYSTEM_LIB_FLAC = 1
 USE_SYSTEM_LIB_SQLITE3 = 1
 USE_SYSTEM_LIB_PORTMIDI = 1
 USE_SYSTEM_LIB_PORTAUDIO = 1
 USE_SYSTEM_LIB_UTF8PROC = 1
 USE_SYSTEM_LIB_GLM = 1
 USE_SYSTEM_LIB_RAPIDJSON = 1
 USE_SYSTEM_LIB_PUGIXML = 1
 ```

**Comment by MistyDreams** [comment]
On the RX480 its only opengl that crashes the shaders.

**Comment by sairuk** [comment]
i recompiled against your settings above and cannot recreate the font corruption issue with shinobi here

![image](https://user-images.githubusercontent.com/526372/169915604-2be2e8a5-52f4-4a88-ad60-8a194d8066a0.png)

**Comment by MistyDreams** [comment]
its really odd has to be mesa/amgpu or bgfx related. Ill need to check this on the rx480 and see if the corruption happening there. Spending too much time on the machine I want to use mame on.  

I updated my kernel and mesa (20.0.4) the mesa updates improved the mainline examples of bgfx.  One of them do crash for me though. I tried copying the latest bgfx files over it not that easy to update to test. I dont know much about lua and what needs done. ill see if i can work out it in time. I like tinkering with things anyway.

I did try with setting my opengl driver to zink but that crashed on the same shader radv crashes on which makes sense and amdvlk doesnt work with zink.  I can use vulkan anyway with amdvlk. Ill keep on at it. The new mesa and kernel exit really nice with the example that fails it just closes. 

mame doesnt see to shut down i can alt tab and close it from the task bar any so thats a lot better than having to ssh in. If i find anything useful ill update this thread.

**Comment by MistyDreams** [comment]
> i recompiled against your settings above and cannot recreate the font corruption issue with shinobi here

I tried on the rx480 opengl is, fine radv is fine, amdvlk gives corrupt characters on the screen on mesa 22.0.4 one the mainline examples crash on each machine as well. Will need to double check what one it is.

**Comment by MistyDreams** [comment]
Further checking with upstream bgfx im having issues witth example 39 freezing so i tried with a debug build. 
```
/../../src/renderer_vk.cpp (4909): BGFX 	user: bgfx_clear_color (vec4), r.index   0, r.count  8, r.texComponent 0, r.texDimension 0
../../../src/bgfx.cpp (533): BGFX VertexLayout aaaa40da (e0896034), stride 8
../../../src/bgfx.cpp (549): BGFX 	attr  0: Attrib::Position     num 2, type 4, norm [ ], asint [ ], offset  0
../../../src/bgfx.cpp (3549): BGFX Init complete.
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle   3) u_combineParams
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle   4) u_rect
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle   5) u_params
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle   6) s_normal
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle   7) s_depth
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle   8) s_color
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle   9) s_albedo
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle  10) s_ao
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle  11) s_blurInput
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle  12) s_finalSSAO
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle  13) s_depthSource
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle  14) s_viewspaceDepthSource
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle  15) s_viewspaceDepthSourceMirror
../../../src/bgfx_p.h (4771): BGFX Creating uniform (handle  16) s_importanceMap
../../../examples/common/bgfx_utils.cpp(75): Failed to load shaders/spirv/vs_assao_gbuffer.bin.
../../../src/bgfx.cpp (4335): BGFX ASSERT _mem can't be NULL
../../../src/bgfx.cpp (4335): BGFX FATAL 0x00000000: _mem can't be NULL

Thread 2 "examplesDebug" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7fffe0920640 (LWP 2173)]

```
the file is there and i checked the file permissions is this example working for anyone else ?

**Comment by MooglyGuy** [comment]
While I appreciate the effort to diagnose these issues as they pertain to MAME itself, issues with compiling upstream BGFX samples are probably better posted over on the actual BGFX project's issue tracker.

**Comment by MistyDreams** [comment]
they updated the spirv shaders that sorted it

**Comment by MistyDreams** [comment]
can close this one zero issues on both cards with bgfx with latest mesa, the fullscreen windowed mode is the only issue left but im pretty sure thats something  sdl related.
