### ISSUE TITLE
this code needs fixed is causing an overflow

### ISSUE THREAD

**Issue by MistyDreams** [mamedev/mame#9809]
https://github.com/mamedev/mame/blob/5cab79bc53fc13c53ee0f1753b7568ff8f2091ac/src/devices/cpu/h8/h8_timer16.cpp#L328-L335

char tm[2];

should be char tm [timer_count] as its bigger than 2 unless I am miss reading the code.

**Comment by happppp** [comment]
h8_timer16.h: h8_timer16_channel_device *timer_channel[6];
tm[2] will contain a single digit number and a null.

**Comment by happppp** [comment]
It's harmless to increase the buffer size though, and removes a pitfall if anyone in the future increases timer_channel/timer_count.

**Comment by MistyDreams** [comment]
it just threw a flag up when i was compiling with asan for for netlist issues is all just though I would ask.

**Comment by galibert** [comment]
What did asan see?

**Comment by MistyDreams** [comment]
wasnt asan was gcc

**Comment by galibert** [comment]
Ah, I see, the compiler thinks it can be any number, which is wrong, but heh.
