### ISSUE TITLE
MAME Debugger request for a UI Dark Mode

### ISSUE THREAD

**Issue by phillipeaton** [mamedev/mame#9814]
As subject.

Most of the MAME debugging I do is in the evenings when the lights are low. Everything on my Windows PC has a dark mode these days. Except the MAME Debugger. My eyes are on fire, I'm not sure I can take it any longer!😳

Thanks for reading.

**Comment by cuavas** [comment]
As of c25428f519d401634d2e7555cc5cc0908efb5b0d, the Win32 debugger has a crude dark mode:
![image](https://user-images.githubusercontent.com/9678431/190728064-4225ed99-300c-41a3-af97-946f8d7c7467.png)

You can select the dark background theme from the Settings menu in the debugger console window.  Your choice is saved to default.cfg.

**Comment by phillipeaton** [comment]
Thanks for the update, it's not perfect, but it looks a lot better than before! 👍

**Comment by Robbbert** [comment]
I presume we can close this now.
