### ISSUE TITLE
sol2 build failure

### ISSUE THREAD

**Issue by ieure** [mamedev/mame#9818]
Building current master (536b162b5c41398886130648da28514987f6cde1) fails due to a warning in sol2, and warnings being treated as errors:

```
$ make SUBTARGET=arcade
GCC 10 detected
Compiling src/frontend/mame/luaengine_debug.cpp...
In file included from ../../../../../src/frontend/mame/luaengine.h:29,
                 from ../../../../../src/frontend/mame/luaengine.ipp:13,
                 from ../../../../../src/frontend/mame/luaengine_debug.cpp:12:
../../../../../3rdparty/sol2/sol/sol.hpp: In static member function ‘static _Res std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Res = long unsigned int; _Functor = lua_engine::symbol_table_wrapper::add(const char*, sol::protected_function, std::optional<sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> > >, std::optional<const char*>)::<lambda()>; _ArgTypes = {}]’:
../../../../../3rdparty/sol2/sol/sol.hpp:15823:17: error: ‘<anonymous>’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
15823 |       return UT();
      |                 ^
../../../../../3rdparty/sol2/sol/sol.hpp: In static member function ‘static _Res std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Res = long unsigned int; _Functor = lua_engine::initialize_debug(sol::table&)::<lambda(lua_engine::symbol_table_wrapper&, sol::this_state, const char*, int, int, sol::protected_function)>::<lambda(int, const u64*)>; _ArgTypes = {int, const long unsigned int*}]’:
../../../../../3rdparty/sol2/sol/sol.hpp:15823:17: error: ‘<anonymous>’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
15823 |       return UT();
      |                 ^
cc1plus: all warnings being treated as errors
make[2]: *** [frontend.make:754: ../../../../linux_gcc/obj/x64/Release/src/frontend/mame/luaengine_debug.o] Error 1
make[1]: *** [Makefile:100: frontend] Error 2
make: *** [makefile:1280: linux_x64] Error 2
```

I'm compiling on Debian Bullseye.

**Comment by ieure** [comment]
> gcc (Debian 10.2.1-6) 10.2.1 20210110

The failure happened on a fresh clone of the repo last night.  I just pulled and am trying to build commit e6180e3510bef6ea8ffb6abddf64d7d3006829ed.

**Comment by MistyDreams** [comment]
add ```CXXFLAGS="-Wno-error=maybe-uninitialized"``` to your makefile.

ie
```CXXFLAGS="-Wno-error=maybe-uninitialized" make -j8 REGENIE=1 ```

**Comment by cuavas** [comment]
The output doesn’t look like the latest source because it‘s only showing the major version of the compiler.  As of a3ee45c94cb02f1d40b42b70505966a6f51b8357 it should show the major.minor.patch version for GCC.

**Comment by cuavas** [comment]
Have the Debian people somehow screwed up GCC so `gcc -dumpfullversion` doesn’t print the full, three-part version?

**Comment by sairuk** [comment]
commit https://github.com/mamedev/mame/commit/a3ee45c94cb02f1d40b42b70505966a6f51b8357 only addressed cross-compilation for windows on linux. `-dumpversion` on bullseye/linux (still the in the makefile) will only output the major

```
root@retroNAS:/var/log# gcc -dumpfullversion
10.2.1
root@retroNAS:/var/log# gcc -dumpversion
10
root@retroNAS:/var/log# echo $PRETTY_NAME
Debian GNU/Linux 11 (bullseye)
```

i'll try building on bullseye a bit later on and see if can replicate

**Comment by ieure** [comment]
> commit [a3ee45c](https://github.com/mamedev/mame/commit/a3ee45c94cb02f1d40b42b70505966a6f51b8357) only addressed cross-compilation for windows on linux. `-dumpversion` on bullseye/linux (still the in the makefile) will only output the major
> 

Sure, fine, but the entire thing about what version is printed is a red herring which has nothing to do with the actual issue I reported.

**Comment by sairuk** [comment]
> Sure, fine, but the entire thing about what version is printed is a red herring which has nothing to do with the actual issue I reported.

Correct, added information to also demonstrate that was the case so we can get that line of thinking out of the way and focus on the actual issue

**Comment by cuavas** [comment]
The thing is, I’ve built with GCC 10.3 and beyond and I don’t get that error, although I’ve seen it with GCC 9 and earlier.  It’s a spurious warning, and you can work around it by adding `-flifetime-dse=1` to the compile options (see [here](https://github.com/mamedev/mame/blob/mame0244/scripts/genie.lua#L1088)).  GCC’s inconsistency in when it produces warnings is incredibly annoying, and we’re not going to be able to pander to every single variant that behaves differently for whatever weird reason.

**Comment by cuavas** [comment]
ea1e51636c68f6d07b3d62b7b9d960567d4e3f33 is the furthest I’m going to go with workarounds.  Apply a local workaround if you’re still having issues.

**Comment by smf-** [comment]
AFAICT we only use dumpfullversion on windows when using bash, we don't
call it in any other circumstance. Including using cmd under windows,
but certainly not Debian.

ifeq ($(OS),windows)
ifeq (posix,$(SHELLTYPE))
GCC_VERSION      := $(shell $(TOOLCHAIN)$(subst @,,$(CC))
-dumpfullversion 2> /dev/null)
