### ISSUE TITLE
chdman fails on filenames with dollar signs in them

### ISSUE THREAD

**Issue by Kreeblah** [mamedev/mame#9822]
Environment: M1 Max Mac running macOS 12.4
chdman from Homebrew's `rom-tools` package.

I'm attempting to compress BIN/CUE files to CHD files, and one thing I noticed is that BIN/CUE files seem to fail if given filenames with dollar signs in them.

For example, for a given directory with the following contents:

```
Test$Game Disc (USA)/Test$Game Disc (USA).cue
Test$Game Disc (USA)/Test$Game Disc (USA).chd
```

The following command fails (in zsh and fish; I haven't tried other shells):

```
chdman createcd -np 10 -i "Test$Game Disc (USA)/Test$Game Disc (USA).cue" -o "Test$Game Disc (USA)/Test$Game Disc (USA).chd"
chdman - MAME Compressed Hunks of Data (CHD) manager 0.243 (unknown)
Error parsing input file (Test Disc (USA)/Test Disc (USA).cue: No such file or directory)

Fatal error occurred: 1
```

Additionally, I have [a script](https://github.com/Kreeblah/organize_chd/blob/main/organize_chd.zsh) I've been writing which uses chdman for CHD creation, and it fails to do some sort of variable substitution:

```
$ ./organize_chd.zsh -d ~/disctest -c
chdman is /opt/homebrew/bin/chdman
Processing: /Users/kreeblah/disctest/Test$Game Disc (USA)/Test$Game Disc (USA).cue
chdman - MAME Compressed Hunks of Data (CHD) manager 0.243 (unknown)
Warning: osd_subst_env variable Game not found.
Warning: osd_subst_env variable Game not found.
ERROR: couldn't find bin file []
Error parsing input file (/Users/kreeblah/disctest/Test$Game Disc (USA)/Test$Game Disc (USA).cue: No such file or directory)

Fatal error occurred: 1
Error processing: /Users/kreeblah/disctest/Test$Game Disc (USA)/Test$Game Disc (USA).cue
```

I didn't see a way to disable variable substitution at runtime, and trying to escape the dollar sign with a backslash prior to calling chdman results in it looking for a filename with a literal `\$` sequence in it.

**Comment by cuavas** [comment]
This should be fixed by #9859 (merged as 13910382a5e846677f30d1645bfb44e4983de557).
