### ISSUE TITLE
Volfied incorrect joystick gate hooked up

### ISSUE THREAD

**Issue by johansmolinski** [mamedev/mame#9824]
I don't know where to find this piece of metadata, so please help me out here. For instance, at the bottom of this page,

https://www.gamesdatabase.org/mame-rom/volfied

there is a section called MAME XML Output. In this, you'll find `<control type="joy" ways="8"/>`. This is wrong. It really should be set to 4 instead of 8. The ship stops if pulled diagonally, making the game very hard to play, and it never utilises diagonal directions for anything.

If this is hidden in the source somewhere, please advice me where. I'd be glad to make a pull request for correcting this.

**Comment by johansmolinski** [comment]
I found this in `src/mame/drivers/volfied.cpp`:

```
	PORT_START("F0000B")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_TILT )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_JOYSTICK_UP ) PORT_8WAY
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN ) PORT_8WAY
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT ) PORT_8WAY
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT ) PORT_8WAY
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_BUTTON1 )
	PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_UNKNOWN )

	PORT_START("F0000D")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_JOYSTICK_UP ) PORT_8WAY PORT_COCKTAIL
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN ) PORT_8WAY PORT_COCKTAIL
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT ) PORT_8WAY PORT_COCKTAIL
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_BUTTON1 ) PORT_COCKTAIL
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_UNKNOWN )
	PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT ) PORT_8WAY PORT_COCKTAIL // TODO: probably correct based on initial analysis, but why is this on bit 0x80 when read through the c-chip when it was 0x08 in the simulation and for P1, is it just a Taito workaround for reading through ADC?
```

Is it as simple as changing `PORT_8WAY` to `PORT_4WAY`? Is this the source of truth for the above mentioned XML file and other similar ones found out there?

**Comment by angelosa** [comment]
Yup, `PORT_4WAY` hooked up for all joystick directions will disable diagonals like a real 4-way gate.
Can't find a manual, but definitely don't seem right with 8 way.

**Comment by bmcphail** [comment]
Original documentation confirms 4 way - Volfied.pdf (arcade-museum.com)
<https://www.arcade-museum.com/manuals-videogames/V/Volfied.pdf>

**Comment by johansmolinski** [comment]
Thank you for helping me out here! I have created a pull request. Fingers cross it doesn't break anything. I have not tested it.
