### ISSUE TITLE
chdman should record 'data sha1' from individual tracks in metadata

### ISSUE THREAD

**Issue by i30817** [mamedev/mame#9825]
This is for both speed, and for cases where other tools using chdman want to collect information of a big collection, to not trash the disk/ssd with unnecessary writes. I have a small tool to rename roms when redump decides to change their name, and i'd like it to support chd without absolutely murdering my SSD. Very unfortunately however, redump doesn't store checksums of the total of their dump tracks glued. Or rather, it does, but it's _only_ a crc32 and only in the site, not the dats. Which means it's unusable to me for both the fact the chd format only shows sha1 and because i would have to scrape redump instead of just look for a checksum on a dat collection.

So have a XY problem here. What i _want_ is to get checksums (of a certain kind, sha1) of tracks. What chd _has_ is checksum of the 'whole data' or 'extract that data, divide it yourself and calculate' (and murder your ssd). Not great because i can't solve it well from either side.

Note: named pipes are not a solution for this, for two reasons: chdman has more than one 'input' and 'output' file (as i will explain later) and because a named pipe as 'output' of a child program doesn't actually work - there is no way the caller of chdman could force chdman to append to a file instead of replacing it, which is what open in write mode does by default.

I could mention that linux has a convention to use '-' as a filename (for input or output) to mean 'stream it', but i don't think this is the best idea for this, because even if would be more versatile, it would not actually help simplify things because although chdman only has '1 input and 1 output file' that is misleading because the cue/gdi are index files themselves so it's more like 'at least 2 input file' and 'at least 2 output files' in my experience. So that trick would have to use more than the number of standard streams and to be sane would be limited to the 'output' (since it's a cue/ single bin at most) and it would be complicated code to calculate checksums for single tracks.

So what i really really want is metadata tracks to show their sha1 too (although crc32 is popular, i believe it's best to use the most commonly used larger checksum for this).

**Comment by i30817** [comment]
I believe myself that expecting redump to be obsoleted by a entire new ultra accurate format is something that is simply not going to happen, because it would require redumping ... everything ...

I suppose i can just wait until redump finally adds a field for 'total' with a sha1, but i fear that is going to take literally decades, if it ever happens.

As a alternative if you're not willing to add sha1 track metadata, could you consider a '--stream' command or something that would be a alternative to '--output' that simply writes the whole 'data' to stdout (suppressing the regular output)? Not the cue/toc since that can be parsed from `chdman info`, just some way to do calculations.

**Comment by rb6502** [comment]
Yeah, if you need track-by-track SHA1s or whatever, a separate tool could easily do so.  There's no value to us in having MAME do it.

**Comment by i30817** [comment]
There is the value we don't have to amortize it ourselves as users, and thus don't have to wait what is likely several hours to make the calculation, but i'm seeing where this going. Guess it's extended atttributes and bchunck for me again, wasting write cycles, or waiting for a python library of libchd.

**Comment by i30817** [comment]
BTW, there is already a tool that wants to identify chds of 'redump' and 'tosec' dumps that is forced to trash the harddrive/ssd of users by extracting the image and dividing it with bchunk (a approach that makes me not want to use the tool).

https://github.com/j68k/verifydump#readme

So this is not just me (i have another tool to 'rename' roms from updates from the .dats that i wanted to make support chd that caused me to open this in the hope i could avoid this problem).

**Comment by cuavas** [comment]
There’s no reason to actually extract the data to disk files to digest the individual tracks.  You just need a tool using one of the CHD format handling libraries to read the CHD file and digest the tracks as it goes.  We’re already thin on the ground, as shown by the lack of love chdman gets.  We simply don’t have the manpower to add and support more features like this.

Besides libchd, there’s also [chd-rs](https://github.com/SnowflakePowered/chd-rs) which has complete read support for the CHD format, and possibly other CHD handling libraries, so you have multiple options for the library to read CHDs.

**Comment by cuavas** [comment]
Putting more auxiliary data in the header complicates the format, causing knock-on effort for all implementations, more that can go wrong, and so on.  You’re talking about pushing this onto all users of the format for a peripheral use case.

**Comment by i30817** [comment]
Besides it being completely irrelevant the number (although 'most' is only something indicating 50%+) as even 10% would be more than enough to sabotage a tool that wants to identify files in sets; if they're a 'figment' of a drive imagination or not, that's completely irrelevant to the status quo, which is redump, which your own project is using the dumps of.

If you want to say you're going to do a new dumping project for all those platforms, by all means, godspeed, but currently the status quo is redump, which does not have a 'single file' sha1sum.

**Comment by smf-** [comment]
You can identify the game using the file hash. There is also a raw data 
hash, that doesn't include the meta data.

Each hunk of data also has a crc, if you want to identify differences 
between revisions of games.

             switch (lastcomp)

             {
                 case COMPRESSION_TYPE_0:
                 case COMPRESSION_TYPE_1:
                 case COMPRESSION_TYPE_2:
                 case COMPRESSION_TYPE_3:
                     assert(length < (1 << lengthbits));
                     bitbuf.write(length, lengthbits);
                     bitbuf.write(crc, 16);
                     if (firstoffs == 0)
                         firstoffs = offset;
                     break;

                 case COMPRESSION_NONE:
                     bitbuf.write(crc, 16);
                     if (firstoffs == 0)
                         firstoffs = offset;
                     break;

**Comment by smf-** [comment]
> Yes, i've told i understand that at least 4 times.

I've never seen anyone mention that every hunk of data has a hash already calculated (4k on the chd I'm looking at).

But in terms of making the hash match whatever redump stores, I am not sure it could possibly ever work as we store sectors differently.

We would specifically have to commit to storing redump compatible checksums.

**Comment by i30817** [comment]
Sorry about being hotheaded, i thought you meant the 'data sha1sum' that chdman outputs. Yes, those 'little' checksums are not good, unless you know of a way to get CKS(a) + CKS(b)... = CKS(a+b...) and i believe that to be impossible with sha1sum.
