### ISSUE TITLE
No "Bill In" Input Found in nbahangtl11 Mame 0.243

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [mamedev/mame#9844]
![image](https://user-images.githubusercontent.com/40109698/170817262-b2c2064e-6329-4f4a-bb26-bf3367e4c75c.png)

**Comment by cuavas** [comment]
Please give the issue a textual description to assist in searching, and summarising.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
There are 42 Inputs In NBA Hangtime, But Only 41 Are Registered.
START1 = 1 Player Start
START2 = 2 Players Start
START3 = 3 Players Start
START4 = 4 Players Start
JOY1 Left = P1 Left
JOY1 Down = P1 Down
JOY1 Up = P1 Up
JOY1 Right = P1 Right
JOY2 Left = P2 Left
JOY2 Down = P2 Down
JOY2 Up = P2 Up
JOY2 Right = P2 Right
JOY3 Left = P3 Left
JOY3 Down = P3 Down
JOY3 Up = P3 Up
JOY3 Right = P3 Right
JOY4 Left = P4 Left
JOY4 Down = P4 Down
JOY4 Up = P4 Up
JOY4 Right = P4 Right
P1 T = P1 Turbo
P1 S = P1 Shoot / Block
P1 P = P1 Pass / Steal
P2 T = P2 Turbo
P2 S = P2 Shoot / Block
P2 P = P2 Pass / Steal
P3 T = P3 Turbo
P3 S = P3 Shoot / Block
P3 P = P3 Pass / Steal
P4 T = P4 Turbo
P4 S = P4 Shoot / Block
P4 P = P4 Pass / Steal
COIN1 = Coin 1
COIN2 = Coin 2
COIN3 = Coin 3
COIN4 = Coin 4
SERVICE CREDIT = Service 1
BILL IN = No Input Found In Edit Binding Tab
SLAM TILT = Tilt
TEST = Service Mode
VOL. UP = Volume Up
VOL. DOWN = Volume Down

**Comment by ajrhacker** [comment]
7abaa7fe02bd7cfadbf5d5cdc2e7ef5ada35fa50 addresses this for nbahangt and all other games in the same driver.
