### ISSUE TITLE
Breaking Issue between 0.243 and 0.244

### ISSUE THREAD

**Issue by steve1515** [mamedev/mame#9860]
There seems to be an issue with audio on the `simpsons` rom set in 0.244 that wasn't in 0.243. Audio stops a few seconds into the attract intro sequence and does not return. I found other's with the same issue: https://www.reddit.com/r/MAME/comments/v0fa7m/the_simpsons_arcade_2p_audio_issue/
This might be an issue with the Z80 CPU according to the link above.

**Comment by Tafoid** [comment]
Already reported and logged
https://mametesters.org/view.php?id=8333

**Comment by steve1515** [comment]
Thank you! Closing ticket.
