### ISSUE TITLE
request: save font sprite sheet

### ISSUE THREAD

**Issue by tomdamaxx** [mamedev/mame#9868]
I would like to request a feature to be able to save the font sprite sheet of a game (when pressing F4).

![afbeelding](https://user-images.githubusercontent.com/106557161/171053329-671f1b22-6936-4e4a-aa51-8a8faac73b1b.png)

I also saw a problem here: why are the fonts so blurry compared to in-game? 
They are so blurry you can't see the individual pixels anymore.

![afbeelding](https://user-images.githubusercontent.com/106557161/171053386-859ea3f2-95d3-4618-8789-654248426331.png)

regards,
Tom

**Comment by tomdamaxx** [comment]
Ok, I see.

2 questions:

- can you tell me in what code file of MAME the sprite sheet is read from the ROM so I can implement this feature myself?

- do you know software that can do this already?

**Comment by happppp** [comment]
The gfx viewer source code: https://github.com/mamedev/mame/blob/master/src/frontend/mame/ui/viewgfx.cpp
You can use another video setting that doesn't blur (eg. -video gdi on Windows)

Extracting all that gfx? You're on your own, sorry.
