### ISSUE TITLE
answer to question?

### ISSUE THREAD

**Issue by tomdamaxx** [mamedev/mame#9869]
Can you please answer my questions without closing it?

https://github.com/mamedev/mame/issues/9868

It's not unlawful to ask in what source code file I have to look...
And since MAME's license allows you to modify the source code, this is not unlawful too.

thanks,
Tom

**Comment by happppp** [comment]
Please don't do this.

**Comment by tomdamaxx** [comment]
SCREW YOU LOSERS
I FIND THE SOURCE CODE FILE MYSELF

**Comment by tomdamaxx** [comment]
Being nice isn't a quality of any of the MAME developers?
That's why the project is probably close to abandonded compared to other popular emulators and that's why not any modern system is emulated in MAME because of this lack of developers.
Way to go! Just continue to behave like this to loose even more developers....

**Comment by happppp** [comment]
You should have rechecked the other issue.

**Comment by angelosa** [comment]
A simple source search will answer to that. 
Also technically you don't even need to modify source code for extracting GFXs, assuming by that you mean "exposing to an image file".
