### ISSUE TITLE
gfx view renders blurry tiles for BGFX

### ISSUE THREAD

**Issue by holub** [mamedev/mame#9878]
my setup: linux with "-video bgfx -bgfx_screen_chains unfiltered,unfiltered"
![unknown](https://user-images.githubusercontent.com/58155/171516698-8fe4f219-8304-47a9-80b9-2a8be7d448ef.png)

**Comment by cuavas** [comment]
Tracked at MAME Testers: https://mametesters.org/view.php?id=8340

**Comment by cuavas** [comment]
Fixed by 4a587fd7c1c512649320929f5e1fc3d44cc9c979.
