### ISSUE TITLE
Debugger step-over followed by enter no longer works.

### ISSUE THREAD

**Issue by Robbbert** [mamedev/mame#9900]
Since commit https://github.com/mamedev/mame/commit/c7597225b4f0a3531d53dd806048b136956eb850

If you enter **o** to skip a subroutine, and find that it is stuck in a loop, you could hit enter to go back to step mode. This no longer works. Please restore the original behaviour.

Example:
**>mame super80 -d
g c3f2
o**
(now it's in a loop waiting for a keypress) (you could hit enter to find out what's going on, but not any more)

I tried pressing various keys but the only one to do anything was F8 - I don't know if any others are supposed to do anything.

NOTE: This is by using the Windows debugger - I do not use the others so don't know if they had different behaviour.

**Comment by ajrhacker** [comment]
Fixed in 5f712ea70297112cd0a6a2b5257107fe201093c1.
