### ISSUE TITLE
apple2gs - America Online 80 column text

### ISSUE THREAD

**Issue by ksherlock** [mamedev/mame#9916]
The 80-column text screen in America Online ([self booting disk](https://archive.org/download/a2_America_Online/a2_America_Online.2mg) -- `mame apple2gsr1 -modem pty -flop3 a2_America_Online.2mg`, then work offline, setup, or options) and AppleLink Personal Edition don't render correctly.

Curiously, they set `$c054` / `TXTPAGE1`, write the odd characters to the text screen at`$e00400`, then set `$c055` / `TXTPAGE2`, and write the even characters to the text screen at`$e00400`.  `TXTPAGE2` only remaps `$0400-$07ff` in bank `$00` so the even columns overwrite the odd columns in bank `$e0`.

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/964904/173166510-00dc5c47-bb9d-4616-a71f-8aff6cad7f86.png">

**Comment by rb6502** [comment]
That's a dark corner of the machine.  I wonder if TXTPAGE1/2 actually only act on $E0 and the effect on $00 doesn't exist when shadowing is disabled, or if it happens in both banks the way the FPI has its own language cards.

**Comment by rb6502** [comment]
This is fixed now, but it does open up a fair number of questions as well.
