### ISSUE TITLE
sound.cpp: Save state issue

### ISSUE THREAD

**Issue by couriersud** [mamedev/mame#9917]
After a state load the sound system intializes the buffer times to `machine().time()`. In e.g. `kidniki` the machine time after a save is ahead of the time the sound devices have been processed up to prior to the state save. As a result, during the first sound update less samples are being processed than needed and sound devices may be slightly out of sync.
 
I assume that the output end time should be saved as a save state item and restored during `postload`. I am miles away from being MAME core knowledgeable and thus opening this up for discussion.
In netlist.cpp I have now used a workaround which better illustrates the issue - I can provide a PR with my current work if needed.

```
void sound_stream::postload()
{
	// set the end time of all of our streams to now
	for (auto &output : m_output)
		output.set_end_time(m_device.machine().time());
	// recompute the sample rate information
	sample_rate_changed();
}
```

**Comment by cuavas** [comment]
Seems to have been fixed in #9918 (merged as fe1e26a9fb437de24661a5cb16f82ec94cdb14fc).
