### ISSUE TITLE
mingw64 debug build

### ISSUE THREAD

**Issue by claydonkey** [mamedev/mame#9931]
Steps to reproduce the problem
debug build mame0244 on MinGW (DEBUG=1)

Mame version
mame0244

Compiler and version
gcc 11.2.0 (Rev6, Built by MSYS2 project)

Operating system and version
x86_64-w64-mingw32

Other relevant information
```
{standard input}: Assembler messages:
{standard input}: Fatal error: ../../../../libretro/obj/x64/libretrodbg/src/emu/emumem_aspace.o: file too big
make[3]: *** [emu.make:2084: ../../../../libretro/obj/x64/libretrodbg/src/emu/emumem_aspace.o] Error 1
make[2]: *** [Makefile:85: emu] Error 2
make[2]: Leaving directory '/c/Users/antho/OneDrive/Documents/Vectrx2020/mame/build/projects/retro/mamearcade/gmake-mingw64-gcc'
make[1]: *** [makefile:1126: windows_x64] Error 2
make[1]: Leaving directory '/c/Users/antho/OneDrive/Documents/Vectrx2020/mame'
make: *** [Makefile.libretro:243: build] Error 2
```

Thought that adding the following to genie.lua would fix problem but it hasn't 

configuration { "mingw*", "x64" }
		buildoptions {
			"-Wa,-mbig-obj"
		}

**Comment by cuavas** [comment]
You appear to be building a retroarch core.  We don’t support this configuration.

**Comment by claydonkey** [comment]
My bad. I posted this in the wrong place...
