### ISSUE TITLE
adding sound support in dribbling driver

### ISSUE THREAD

**Issue by aovestdipaperino** [mamedev/mame#9940]
Dribbling driver: 
https://github.com/mamedev/mame/blob/134f39bd33b89fe01d530f9caee11cae56f729eb/src/mame/drivers/dribling.cpp

The driver lacks support for sound. I've looked at the schematics online and there is only 1 chip that s missing in order to get this done: LM339, quad differential comparator

I started emulating the audio circuitry with Micro-Cap 12 and successfully tested one of them (Parata). I am attempting to replace the LM in the circuit with its equivalent transistors and diodes (4 PNP, 4 NPN, 2 diodes) and see if it works.
The 74393 seems more straightforward as it could be emulated with 74 logic gates.

If somebody can help bootstrap this effort, I will gladly join. There's too many things I am rusty at (C++, analog circuits) but we can get this completed and preserved.

**Comment by aovestdipaperino** [comment]
@cuavas pinging.
I have the SUBCKT model already.

**Comment by aovestdipaperino** [comment]
This can now be closed as complete. 😉

**Comment by cuavas** [comment]
> This can now be closed as complete. 😉

Indeed it can.
