### ISSUE TITLE
Linking errors since commit 1964365f34499ae5785c7b8f13836caa05156dfa

### ISSUE THREAD

**Issue by mizapf** [mamedev/mame#9941]
make -j4 SOURCES=src/mame/drivers/ti99_4x.cpp REGENIE=1 TOOLS=0 PYTHON_EXECUTABLE=python3

...
Compiling generated/mame/mame/drivlist.cpp...
Linking mame...
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(ui.o): in function `mame_ui_manager::get_general_input_setting[abi:cxx11](ioport_type, int, input_seq_type)':
ui.cpp:(.text+0x330d): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(luaengine_input.o): in function `lua_engine::initialize_input(sol::basic_table_core<false, sol::basic_reference<false> >&)::{lambda(ioport_field&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, osd::input_seq const&)#26}::operator()(ioport_field&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, osd::input_seq const&) const':
luaengine_input.cpp:(.text+0x1a814): undefined reference to `osd::input_seq::length() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(luaengine_input.o): in function `lua_engine::initialize_input(sol::basic_table_core<false, sol::basic_reference<false> >&)':
luaengine_input.cpp:(.text+0x47028): undefined reference to `osd::input_seq::length() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: luaengine_input.cpp:(.text+0x47061): undefined reference to `osd::input_seq::is_valid() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(luaengine_input.o): in function `input_sequence_poller::valid() const':
luaengine_input.cpp:(.text._ZNK21input_sequence_poller5validEv[_ZNK21input_sequence_poller5validEv]+0x5): undefined reference to `osd::input_seq::is_valid() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(inputmap.o): in function `ui::menu_input::handle(ui::menu::event const*)':
inputmap.cpp:(.text+0x3e6): undefined reference to `osd::input_seq::is_valid() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(inputmap.o): in function `ui::menu_input_specific::update_input(ui::menu_input::input_item_data&)':
inputmap.cpp:(.text+0x2980): undefined reference to `osd::input_seq::length() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(input.o): in function `input_manager::seq_clean(osd::input_seq const&) const':
input.cpp:(.text+0xf52): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: input.cpp:(.text+0xf98): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: input.cpp:(.text+0xfba): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(input.o): in function `input_manager::seq_from_tokens(osd::input_seq&, std::basic_string_view<char, std::char_traits<char> >)':
input.cpp:(.text+0x1153): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: input.cpp:(.text+0x11be): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: input.cpp:(.text+0x1286): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `input_type_entry::replace_code(input_code, input_code)':
ioport.cpp:(.text+0x7cf): undefined reference to `osd::input_seq::replace(input_code, input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `digital_joystick::frame_update()':
ioport.cpp:(.text+0x92e): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_field::seq(input_seq_type) const':
ioport.cpp:(.text+0xe04): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_field::defseq(input_seq_type) const':
ioport.cpp:(.text+0xe64): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_field::get_user_settings(ioport_field::user_settings&) const':
ioport.cpp:(.text+0x1343): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_manager::type_seq(ioport_type, int, input_seq_type) const':
ioport.cpp:(.text+0x22d5): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_manager::set_type_seq(ioport_type, int, input_seq_type, osd::input_seq const&)':
ioport.cpp:(.text+0x237d): undefined reference to `osd::input_seq::length() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_manager::type_pressed(ioport_type, int)':
ioport.cpp:(.text+0x2569): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_manager::load_remap_table(util::xml::data_node const&)':
ioport.cpp:(.text+0x2a9b): undefined reference to `osd::input_seq::replace(input_code, input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_configurer::field_add_code(input_seq_type, input_code)':
ioport.cpp:(.text+0x466a): undefined reference to `osd::input_seq::operator|=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `analog_field::frame_update(running_machine&)':
ioport.cpp:(.text+0x5c9a): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ioport.cpp:(.text+0x5d1a): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ioport.cpp:(.text+0x5d7a): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libemu.a(ioport.o): in function `ioport_field::frame_update(unsigned int&)':
ioport.cpp:(.text+0x79eb): undefined reference to `osd::input_seq::empty_seq'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(iptseqpoll.o): in function `input_sequence_poller::start(osd::input_seq const&)':
iptseqpoll.cpp:(.text+0x12cb): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(iptseqpoll.o): in function `input_sequence_poller::poll()':
iptseqpoll.cpp:(.text+0x1327): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(iptseqpoll.o): in function `axis_sequence_poller::do_poll()':
iptseqpoll.cpp:(.text+0x1949): undefined reference to `osd::input_seq::length() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x19d1): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x1a0f): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x1a78): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x1a95): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x1abc): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x1aed): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x1afd): undefined reference to `osd::input_seq::operator+=(input_code)'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../../../../linux_gcc/bin/x64/Release/libfrontend.a(iptseqpoll.o): in function `switch_sequence_poller::do_poll()':
iptseqpoll.cpp:(.text+0x2009): undefined reference to `osd::input_seq::length() const'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x2058): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x2074): undefined reference to `osd::input_seq::backspace()'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: iptseqpoll.cpp:(.text+0x208a): undefined reference to `osd::input_seq::operator+=(input_code)'

**Comment by cuavas** [comment]
60179d8c952f48d4ee28dc6e9e12332dac20cf20 should fix it for now.  Eventually we’ll untangle the web of circular dependencies.

**Comment by galibert** [comment]
Ok, I apologize, it's real, sorry.

  OG.

**Comment by mizapf** [comment]
Yes, seems to work now. Thanks!

**Comment by galibert** [comment]
How to say you didn't make clean without saying you didn't make clean.

  OG.
